### ISSUE TITLE
Ganache cannot re start if log directory has been removed

### ISSUE THREAD

**Issue by Naviabheeman** [trufflesuite/ganache#1012]
PLATFORM: darwin
GANACHE VERSION: 1.2.2

EXCEPTION:
```
Error: ENOENT: no such file or directory, mkdir '/.../Ganache Logs'
    at Object.fs.mkdirSync (fs.js:891:18)
    at Object.module.exports.generateLogFilePath (/src/chain/logging.js:68:8)
    at /src/chain/chain.js:54:17
    at stopServer (/src/chain/chain.js:41:5)
    at startServer (/src/chain/chain.js:46:3)
    at process.<anonymous> (/src/chain/chain.js:158:7)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:768:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: The Log Directory '/.../Ganache Logs' doesn't exist; attempting to create it now
```

**Comment by seesemichaelj** [comment]
@Naviabheeman did you delete the directory `Ganache Log` was located in to?

**Comment by seesemichaelj** [comment]
I was able to recreate the issue by deleting the directory in which the log directory was located. I have changed the logic to recreate the entire path if necessary. I also added logic to recreate the directory if it was deleted mid-session.

This will be in the next release! Thanks!
