### ISSUE TITLE
testrpc doesn't work with Mist

### ISSUE THREAD

**Issue by gnom1gnom** [trufflesuite/ganache#1038]
## Steps to Reproduce (for bugs)
1.  Start testrpc
2.  Start Mist with _--rpc localhost:8545_
3.  Select any account and try to send ether

## Current Behavior
First in the tranasaction window threre's a warning: 

> It seems this transaction will fail. If you submit it, it may consume all the gas you send.

and 

> Estimated fee consumption: We couldn't estimate the gas.

Then after clicking on send transaction following message is displayed:

> Error: RPC method personal_signAndSendTransaction not supported.
at GethApiDouble.handleRequest (C:\Users\jondoe\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\lib\subproviders\geth_api_double.js:49:16)
at next (C:\Users\jondoe\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\web3-provider-engine\index.js:95:18)
at SolcSubprovider.handleRequest (C:\Users\jondoe\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\web3-provider-engine\subproviders\solc.js:28:7)
at next (C:\Users\jondoe\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\web3-provider-engine\index.js:95:18)
at VmSubprovider.handleRequest (C:\Users\jondoe\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\web3-provider-engine\subproviders\vm.js:40:12)
at next (C:\Users\jondoe\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\web3-provider-engine\index.js:95:18)
at GethDefaults.handleRequest (C:\Users\jondoe\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\lib\subproviders\gethdefaults.js:17:12)
at next (C:\Users\jondoe\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\web3-provider-engine\index.js:95:18)
at FilterSubprovider.handleRequest (C:\Users\jondoe\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\web3-provider-engine\subproviders\filters.js:87:7)
at next (C:\Users\jondoe\AppData\Roaming\npm\node_modules\ethereumjs-testrpc\node_modules\web3-provider-engine\index.js:95:18)

## Context
I'm trying to test my contracts using Mist started with _--rpc localhost:8545_ to connect to testrpc.
Test accounts are listed properly with their actual balance.
Problems starts when I try to create a contract or send ether.

## Your Environment

* Version used:
* Environment name and version: TestRPC v3.0.3, Mist 0.8.7
* Operating System and version: Windows 7 SP1
* Link to your project:

**Comment by cds-amal** [comment]
closing for issue maintenance.
