### ISSUE TITLE
Potential issue of truffle project contracts not showing after building

### ISSUE THREAD

**Issue by seesemichaelj** [trufflesuite/ganache#1041]
I saw that after building successfully, I did not see the contracts page update. However, I restarted, removed the build directory, and then built and the page updated automatically. It's possible the first build didn't show because of an error during compiling? I had received the following build errors just before the first successful build:

```
/home/mike/work/consensys/decoding-sample/contracts/DecodingSample.sol:1:1: SyntaxError: Source file requires different compiler version (current compiler is 0.5.1+commit.c8a2cb62.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity ^0.4.23;
^----------------------^
,/home/mike/work/consensys/decoding-sample/contracts/Migrations.sol:1:1: SyntaxError: Source file requires different compiler version (current compiler is 0.5.1+commit.c8a2cb62.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity ^0.4.23;
^----------------------^
,/home/mike/work/consensys/decoding-sample/contracts/DecodingSample.sol:121:23: TypeError: Data location must be "memory" for parameter in function, but none was given.
  function emitEvents(string s, uint num) public {
                      ^------^
Compilation failed. See above.
```

This needs to be verified. Don't think this is blocking for 2.0 beta release, but it needs to be fixed

**Comment by seesemichaelj** [comment]
I saw these errors in the console; not sure if they were related to this issue:

```

{ message: 'getProjectDetails is not a function',
  stack: 'TypeError: getProjectDetails is not a function\n    at FSWatcher.configWatcher.fs.watch (/home/mike/work/consensys/ganache/src/truffle-integration/projectFsWatcher.js:44:22)\n    at emitTwo (events.js:125:13)\n    at FSWatcher.emit (events.js:213:7)\n    at FSEvent.FSWatcher._handle.onchange (fs.js:1376:12)',
  name: 'TypeError' }
{ message: 'getProjectDetails is not a function',
  stack: 'TypeError: getProjectDetails is not a function\n    at FSWatcher.configWatcher.fs.watch (/home/mike/work/consensys/ganache/src/truffle-integration/projectFsWatcher.js:44:22)\n    at emitTwo (events.js:125:13)\n    at FSWatcher.emit (events.js:213:7)\n    at FSEvent.FSWatcher._handle.onchange (fs.js:1376:12)',
  name: 'TypeError' }
{ message: 'Provided address "undefined" is invalid, the capitalization checksum test failed, or its an indrect IBAN address which can\'t be converted.',
  stack: 'Error: Provided address "undefined" is invalid, the capitalization checksum test failed, or its an indrect IBAN address which can\'t be converted.\nat Method.inputAddressFormatter (/home/mike/work/consensys/ganache/node_modules/web3/node_modules/web3-core-helpers/src/formatters.js:402:11)\n    at /home/mike/work/consensys/ganache/node_modules/web3/node_modules/web3-core-method/src/index.js:144:38\n    at Array.map (native)\n    at Method.formatInput (/home/mike/work/consensys/ganache/node_modules/web3/node_modules/web3-core-method/src/index.js:142:32)\n    at Method.toPayload (/home/mike/work/consensys/ganache/node_modules/web3/node_modules/web3-core-method/src/index.js:177:23)\n    at Eth.send [as getCode] (/home/mike/work/consensys/ganache/node_modules/web3/node_modules/web3-core-method/src/index.js:470:30)\n    at ProjectsWatcher.validateContractsOnChain (/home/mike/work/consensys/ganache/src/truffle-integration/projectsWatcher.js:82:46)\n  at ProjectsWatcher.setWeb3 (/home/mike/work/consensys/ganache/src/truffle-integration/projectsWatcher.js:72:16)\n    at process.<anonymous> (/home/mike/work/consensys/ganache/src/truffle-integration/index.js:43:15)\n    at emitTwo (events.js:125:13)\n    at process.emit (events.js:213:7)\n    at emit (internal/child_process.js:768:12)\n    at _combinedTickCallback (internal/process/next_tick.js:141:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)',
  name: 'Error' }
```

**Comment by seesemichaelj** [comment]
I'm pretty sure the above errors (particularly the `getProjectDetails` ones) are causing this issue (and other issues as well)
