### ISSUE TITLE
Ganache 2.0 spinning indefinitely

### ISSUE THREAD

**Issue by eloudsa** [trufflesuite/ganache#1056]
Hi

I have installed Ganache 2 beta 1 on my macOS (10.14.2).
I have created a workspace and opened the `truffle-config.js` file on my project (compliant with Truffle 5 and web3.js 1.0).

But Ganache 2 hangs and it is spinning indefinitely.

Have you noticed this issue?

Thanks,

Said

**Comment by seesemichaelj** [comment]
Hey @eloudsa! This is a generic symptom of something erroring under the hood. A couple of things you can do to help me figure out the source:

- Run Ganache using a terminal to see if there is any console output with errors
- Right click anywhere in Ganache and click Inspect Element. This will bring up the chrome dev tools; go to the Console tab and see if there are any errors there
- Link/send me to your truffle project if it's open source so I can try to reproduce the problem

Thanks!

**Comment by eloudsa** [comment]
Hi @seesemichaelj 

Thanks for your quick reply.

The Chrome's console window is empty.

But an error is displayed in the terminal:
```
$ /Applications/Ganache.app/Contents/MacOS/Ganache
Checking for update
Update for version 2.0.0-beta.1 is not available (latest version: 2.0.0-beta.1, downgrade is disallowed.
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at process.target._send (internal/child_process.js:671:23)
    at process.target.send (internal/child_process.js:582:19)
    at process.<anonymous> (/Applications/Ganache.app/Contents/Resources/app.asar/src/truffle-integration/index.js:65:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

{ message: 'Converting circular structure to JSON',
  stack: 'TypeError: Converting circular structure to JSON\n    at JSON.stringify (<anonymous>)\n    at process.target._send (internal/child_process.js:671:23)\n    at process.target.send (internal/child_process.js:582:19)\n    at process.<anonymous> (/Applications/Ganache.app/Contents/Resources/app.asar/src/truffle-integration/index.js:65:15)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)',
  name: 'TypeError' }
```

The project is available right here: [https://github.com/chainskills/chainlist-truffle5](url)

I hope this info will help.

**Comment by seesemichaelj** [comment]
I'll take a look at it as soon as I can, but it may wait until after the holidays. Thanks for helping provide the details; this info helps a lot finding the source of the issue.

**Comment by seesemichaelj** [comment]
Confirmed I can reproduce the issue based on the master branch of your repo (commit `5f093f9231c3d472c779be763f1ebb5630c2410b`). Thanks!

**Comment by eloudsa** [comment]
Happy new year @seesemichaelj ;-) 
Renaming "ganache" from `truffle-config.js` solves the issue as you suggested.
Thanks!

**Comment by seesemichaelj** [comment]
Happy new year! Let us know if there are any other issues; happy ganaching!
