### ISSUE TITLE
System Error when running Ganache 2.0.0-beta.1 on win32

### ISSUE THREAD

**Issue by FreemanHo** [trufflesuite/ganache#1063]
PLATFORM: win32
GANACHE VERSION: 2.0.0-beta.1

EXCEPTION:
```
TypeError: Cannot read property 'delete' of undefined
    at EventEmitter.<anonymous> (C:\Program Files\Ganache\resources\app.asar\src\main\main.js:376:22)
    at Generator.next (<anonymous>)
    at step (C:\Program Files\Ganache\resources\app.asar\src\main\main.js:71:191)
    at C:\Program Files\Ganache\resources\app.asar\src\main\main.js:71:437
    at Promise (<anonymous>)
    at EventEmitter.<anonymous> (C:\Program Files\Ganache\resources\app.asar\src\main\main.js:71:99)
    at EventEmitter.<anonymous> (C:\Program Files\Ganache\resources\app.asar\src\main\main.js:384:23)
    at emitTwo (events.js:125:13)
    at EventEmitter.emit (events.js:213:7)
    at WebContents.<anonymous> (C:\Program Files\Ganache\resources\electron.asar\browser\api\web-contents.js:266:13)
    at emitTwo (events.js:125:13)
    at WebContents.emit (events.js:213:7)
```

APPLICATION LOG:
```
T+0ms: Starting server (version 2.0.0-beta.1) with initial configuration: {"gasLimit":6721975,"gasPrice":20000000000,"hostname":"127.0.0.1","port":7545,"network_id":5777,"default_balance_ether":100,"total_accounts":10,"unlocked_accounts":[],"locked":false,"vmErrorsOnRPCResponse":true,"verbose":false,"db_path":"C:\\Users\\zero\\AppData\\Roaming\\Ganache\\workspaces\\ciwei\\chaindata"}
T+409ms: Ganache started successfully!
T+409ms: Waiting for requests...
T+508ms: eth_subscribe
T+528ms: eth_getLogs
T+589ms: eth_subscribe
T+607ms: eth_getCode
T+634ms: eth_getCode
T+650ms: eth_getCode
```

**Comment by seesemichaelj** [comment]
Thanks for reporting this issue! And thanks for trying out our new beta!

Do you know what you were doing when this error popped up?  Thanks!

**Comment by seesemichaelj** [comment]
https://github.com/trufflesuite/ganache/commit/e25b13617f608b5ee68469a530c7adfab0573fe4 will prevent the error from appearing, and I believe solves the general issue.

I'm going to go ahead and close the issue, but I'd still like to understand what you were doing when this error happened @FreemanHo? This error really shouldn't have happened, and may be hinting at a larger issue.

Thanks for your help!
