### ISSUE TITLE
System Error when running Ganache 2.0.0-beta.2 on darwin

### ISSUE THREAD

**Issue by jamesmorgan** [trufflesuite/ganache#1091]
Basic install of the new contract, I get this when clicking through to the contract

PLATFORM: darwin
GANACHE VERSION: 2.0.0-beta.2

EXCEPTION:
```
TypeError: Cannot read property 'ast' of undefined
    at Object.getContractNode (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:37:33)
    at getStateVariables (/node_modules/truffle-decoder/dist/allocate/references.js:187:45)
    at Object.getContractStateVariables (/node_modules/truffle-decoder/dist/allocate/references.js:209:27)
    at TruffleContractDecoder.<anonymous> (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:78:55)
    at Generator.next (<anonymous>)
    at /node_modules/truffle-decoder/dist/interface/contract-decoder.js:7:71
    at Promise (<anonymous>)
    at __awaiter (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:3:12)
    at TruffleContractDecoder.init (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:69:16)
    at Object.getContractState (/src/truffle-integration/decode.js:9:11)
    at process.<anonymous> (/src/truffle-integration/index.js:78:52)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:768:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+15430ms: eth_getBlockByNumber
T+15430ms: eth_getTransactionReceipt
T+15430ms: eth_getBlockByNumber
T+15430ms: eth_sendTransaction
T+15439ms:   Transaction: 0xe132bb96576ee6036848bb665f4549e4e101eecfd600b5a6bb186e4eab0ec8ab
T+15439ms:   Gas usage: 105853
T+15439ms:   Block Number: 26
T+15439ms:   Block Time: Mon Jan 21 2019 13:12:51 GMT+0000 (GMT)
T+15447ms: eth_getBlockByNumber
T+15460ms: eth_getTransactionReceipt
T+15468ms: eth_getBlockByNumber
T+15477ms: eth_sendTransaction
T+15488ms:   Transaction: 0x421ff4e0fecaf432d5812c210c7da9b4b3a8d10e4835e6bb79b7d73279f9bc15
T+15488ms:   Gas usage: 104865
T+15488ms:   Block Number: 27
T+15488ms:   Block Time: Mon Jan 21 2019 13:12:51 GMT+0000 (GMT)
T+15496ms: eth_getBlockByNumber
T+15509ms: eth_getTransactionReceipt
T+15517ms: eth_getBlockByNumber
T+15527ms: eth_sendTransaction
T+15540ms:   Transaction: 0x303217712ed7e3209193fd47a8686f51a70509e7f06da5de791e3b3bda1fdff8
T+15540ms:   Gas usage: 104929
T+15540ms:   Block Number: 28
T+15540ms:   Block Time: Mon Jan 21 2019 13:12:51 GMT+0000 (GMT)
T+15548ms: eth_getBlockByNumber
T+15556ms: eth_getTransactionReceipt
T+15568ms: eth_getBlockByNumber
T+15578ms: eth_sendTransaction
T+15587ms:   Transaction: 0x531be2114bd02c452c6958190d66d6a87181d7b76c808ee89f332f13ca7243f1
T+15587ms:   Gas usage: 104993
T+15587ms:   Block Number: 29
T+15587ms:   Block Time: Mon Jan 21 2019 13:12:51 GMT+0000 (GMT)
T+15598ms: eth_getBlockByNumber
T+15607ms: eth_getTransactionReceipt
T+15620ms: eth_getBlockByNumber
T+15627ms: eth_sendTransaction
T+15636ms:   Transaction: 0x711b9b883bbb3fcc2bd41f7c91840c054b8c7aa5730dd34172eb7bf166147f1c
T+15636ms:   Gas usage: 104865
T+15636ms:   Block Number: 30
T+15648ms:   Block Time: Mon Jan 21 2019 13:12:51 GMT+0000 (GMT)
T+15657ms: eth_getBlockByNumber
T+15666ms: eth_getTransactionReceipt
T+15676ms: eth_getBlockByNumber
T+15684ms: eth_sendTransaction
T+15693ms:   Transaction: 0xfa9da9df06885547bcb5e0bdb839f03b8cc9eecce6cdb8a238a0db0bdb8c44b2
T+15693ms:   Gas usage: 146408
T+15693ms:   Block Number: 31
T+15704ms:   Block Time: Mon Jan 21 2019 13:12:51 GMT+0000 (GMT)
T+15714ms: eth_getBlockByNumber
T+15723ms: eth_getTransactionReceipt
T+15733ms: eth_getBlockByNumber
T+15742ms: eth_sendTransaction
T+15754ms:   Transaction: 0x7c7b5a67cc86ecb6935646cd76e7e0d226c3a3884989064d6daabbb8ca183deb
T+15754ms:   Gas usage: 146472
T+15754ms:   Block Number: 32
T+15754ms:   Block Time: Mon Jan 21 2019 13:12:51 GMT+0000 (GMT)
T+15763ms: eth_getBlockByNumber
T+15771ms: eth_getTransactionReceipt
T+15784ms: eth_getBlockByNumber
T+15792ms: eth_sendTransaction
T+15801ms:   Transaction: 0x089552d579799714599f7e31c7af27f39e6572686b593e287622f5966597e3e3
T+15801ms:   Gas usage: 146792
T+15801ms:   Block Number: 33
T+15801ms:   Block Time: Mon Jan 21 2019 13:12:52 GMT+0000 (GMT)
T+15812ms: eth_getBlockByNumber
T+15820ms: eth_getTransactionReceipt
T+15829ms: eth_getBlockByNumber
T+15840ms: eth_sendTransaction
T+15849ms:   Transaction: 0x9f44c4f5df53ee23b54317aeffdf7f51ea15bed8b8458d243b21693e85c00f9c
T+15849ms:   Gas usage: 94221
T+15849ms:   Block Number: 34
T+15849ms:   Block Time: Mon Jan 21 2019 13:12:52 GMT+0000 (GMT)
T+15862ms: eth_getBlockByNumber
T+15870ms: eth_getTransactionReceipt
T+15879ms: eth_getBlockByNumber
T+15892ms: eth_sendTransaction
T+15902ms:   Transaction: 0xe9986f55def1c9e42f9373cb6c4f49a9a9a3e4098e06add329ea925c827cb897
T+15902ms:   Gas usage: 49076
T+15902ms:   Block Number: 35
T+15902ms:   Block Time: Mon Jan 21 2019 13:12:52 GMT+0000 (GMT)
T+15910ms: eth_getBlockByNumber
T+15921ms: eth_getTransactionReceipt
T+15929ms: eth_getBlockByNumber
T+15938ms: eth_getBlockByNumber
T+15951ms: eth_sendTransaction
T+15961ms:   Transaction: 0xf106db8dbda23bd53f61503b1aa14097376ea776099af48f81a0c35efba1f9a6
T+15961ms:   Gas usage: 26935
T+15961ms:   Block Number: 36
T+15973ms:   Block Time: Mon Jan 21 2019 13:12:52 GMT+0000 (GMT)
T+15981ms: eth_getBlockByNumber
T+15991ms: eth_getTransactionReceipt
T+22009ms: eth_unsubscribe
T+22009ms: eth_unsubscribe
T+22025ms: eth_unsubscribe
T+22043ms: eth_unsubscribe
```

**Comment by seesemichaelj** [comment]
Thanks @jamesmorgan for reporting this! Could you upload/point us to the source that you're using for the contract so we can try to reproduce this?

Thanks!

**Comment by davidmurdoch** [comment]
This should now be fixed in our latest beta: https://github.com/trufflesuite/ganache/releases/tag/v2.0.1-beta.0 Let me know if you have an issues or if the fix doesn't work for you.
