### ISSUE TITLE
System Error after running Ganache 2.5.4 on darwin

### ISSUE THREAD

**Issue by wh-sadalmelik** [trufflesuite/ganache#1095]
PLATFORM: darwin
GANACHE VERSION: 2.5.4

EXCEPTION:
```
UnknownBaseContractIdError: Cannot locate base contract ID 1444$ of contract$ PixelToken (ID 44)
    at /Applications/Ganache.app/Contents/Resources/static/node/node_modules/@truffle/decoder/lib/allocate/storage.ts:181:13
    at Array.map (<anonymous>)
    at allocateContract (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/@truffle/decoder/lib/allocate/storage.ts:178:59)
    at Object.getStorageAllocations (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/@truffle/decoder/lib/allocate/storage.ts:23:19)
    at TruffleContractDecoder.<anonymous> (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/@truffle/decoder/lib/interface/contract-decoder.ts:237:39)
    at Generator.next (<anonymous>)
    at fulfilled (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/@truffle/decoder/dist/interface/contract-decoder.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by wh-sadalmelik** [comment]
I created a new workspace and deployed a pure ERC271 token contract.

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "../node_modules/@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "../node_modules/@openzeppelin/contracts/access/Ownable.sol";
import "../node_modules/@openzeppelin/contracts/utils/Counters.sol";

contract PixelToken is ERC721, Ownable  {

    using Counters for Counters.Counter;
    Counters.Counter private _tokenIdCounter;

    constructor() ERC721("PixelToken", "PIX") {}

    function safeMint(address to) public onlyOwner {
        _safeMint(to, _tokenIdCounter.current());
        _tokenIdCounter.increment();
    }
}

```

After i mint a NFT to contract owner in truffle console. 

The error above occurred when i get into the transaction detail page.

And Event page return a black page with console errors:

```
renderer.js:2 TypeError: Cannot read property 'map' of undefined
    at EventDetailsScreen_EventDetailsScreen.render (webpack:/src/integrations/ethereum/renderer/screens/event-details/EventDetailsScreen.js:47)
```
