### ISSUE TITLE
Deleting entire Truffle project causes Ganache to crash

### ISSUE THREAD

**Issue by honestbonsai** [trufflesuite/ganache#1098]
## Expected Behavior

When I delete a Truffle project off my machine, (on startup at the very least, but ideally while it's running as well) Ganache should notice that the `truffle-config.js` is missing and stop tracking that project.

## Current Behavior

Ganache crashes.

## Steps to Reproduce (for bugs)

1. Link a Truffle project in Ganache
2. Close Ganache
3. Delete Truffle project
4. Open Ganache
5. Observe Ganache crashing

Error logs

```
Error: watch /Users/hl/development/test/truffle-config.js ENOENT
    at exports._errnoException (util.js:1024:11)
    at FSWatcher.start (fs.js:1394:19)
    at Object.fs.watch (fs.js:1420:11)
    at ProjectFsWatcher.start (/src/truffle-integration/projectFsWatcher.js:37:29)
    at new ProjectFsWatcher (/src/truffle-integration/projectFsWatcher.js:22:10)
    at ProjectsWatcher.add (/src/truffle-integration/projectsWatcher.js:130:23)
    at process.<anonymous> (/src/truffle-integration/index.js:59:34)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

## Possible Solution

It's probably just deleting `truffle-config.js`, deleting the rest of the contract files usually doesn't trigger a crash.

## Your Environment

* Version used: 2.0.0-beta.2
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1): node 10.9.0
* Operating System and version: MacOS 10.14.2

**Comment by davidmurdoch** [comment]
This should now be fixed in our latest beta: https://github.com/trufflesuite/ganache/releases/tag/v2.0.1-beta.0 Let me know if you have any issues or if the fix doesn't work for you.
