### ISSUE TITLE
System Error when running Ganache 1.6.11 on win32

### ISSUE THREAD

**Issue by lspecian** [trufflesuite/ganache#111]
PLATFORM: win32
GANACHE VERSION: 1.6.11

EXCEPTION:
Error: Lost heartbeat from server process!
    at Timeout.setInterval [as _onTimeout] (C:/Development/ethereum/ganache/src/Services/Chain.js:86:30)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

**Comment by benjamincburns** [comment]
Closing this as duplicate of #83.  Will comment on that case shortly.
