### ISSUE TITLE
System Error when running Ganache 1.2.2 on darwin

### ISSUE THREAD

**Issue by tharamalai** [trufflesuite/ganache#1112]
PLATFORM: darwin
GANACHE VERSION: 1.2.2

EXCEPTION:
```
TypeError: Cannot read property 'pop' of undefined
    at CheckpointTrie.Trie._updateNode (/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:360:23)
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:107:16
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:461:14
    at processNode (/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:471:23)
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:516:13
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:180:7
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/util.js:75:7
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:52:16
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:269:32
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:44:16
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/util.js:71:7
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:157:9
    at /node_modules/ganache-core/lib/database/levelupobjectadapter.js:30:23
    at /node_modules/ganache-core/node_modules/level-sublevel/shell.js:101:15
    at /node_modules/ganache-core/node_modules/level-sublevel/nut.js:121:19
    at /node_modules/ganache-core/node_modules/cachedown/index.js:58:21
    at ReadFileContext.callback (/node_modules/ganache-core/lib/database/filedown.js:27:14)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
```

APPLICATION LOG:
```
T+266362622ms: net_version
T+266362625ms: eth_sendTransaction
T+266363217ms:   Transaction: 0xacdf8dd8c0de3c55a3fd6b3dcc95c851f0de3d70a8a61bd6d936d41dc58aeae6
T+266363217ms:   Gas usage: 3887587
T+266363217ms:   Block Number: 8401
T+266363217ms:   Block Time: Mon Feb 04 2019 20:07:58 GMT+0700 (+07)
T+266363218ms: eth_getTransactionReceipt
T+266363399ms: net_version
T+266363405ms: eth_sendTransaction
T+266364060ms:   Transaction: 0x21505259806d256b266bc24a9f27969c238f865f7a3b2e162524207c0298c156
T+266364060ms:   Gas usage: 3875437
T+266364060ms:   Block Number: 8402
T+266364060ms:   Block Time: Mon Feb 04 2019 20:07:59 GMT+0700 (+07)
T+266364060ms: eth_getTransactionReceipt
T+266364192ms: net_version
T+266364192ms: eth_sendTransaction
T+266364968ms:   Transaction: 0x2492001fce0171337ec2f8e56e3e216838d4f1b90b398cb69d9a4cf0d2dd5dfc
T+266364968ms:   Gas usage: 4523987
T+266364968ms:   Block Number: 8403
T+266364968ms:   Block Time: Mon Feb 04 2019 20:08:00 GMT+0700 (+07)
T+266364968ms: eth_getTransactionReceipt
T+266365092ms: net_version
T+266365092ms: eth_sendTransaction
T+266365769ms:   Tra

**Comment by cds-amal** [comment]
Thanks for reporting @tharamalai! Please update to the latest version of ganache which includes the fix from trufflesuite/ganache-cli/issues/600.

**Comment by tharamalai** [comment]
oh, thanks
