### ISSUE TITLE
System Error when running Ganache 2.0.0-beta.2 on linux

### ISSUE THREAD

**Issue by uracilo** [trufflesuite/ganache#1114]
PLATFORM: linux
GANACHE VERSION: 2.0.0-beta.2

EXCEPTION:
```
Error: watch /home/uracilo/Desktop/hiuman/truffle-config.js ENOSPC
    at exports._errnoException (util.js:1024:11)
    at FSWatcher.start (fs.js:1394:19)
    at Object.fs.watch (fs.js:1420:11)
    at ProjectFsWatcher.start (/src/truffle-integration/projectFsWatcher.js:40:29)
    at new ProjectFsWatcher (/src/truffle-integration/projectFsWatcher.js:25:10)
    at ProjectsWatcher.add (/src/truffle-integration/projectsWatcher.js:130:23)
    at process.<anonymous> (/src/truffle-integration/index.js:59:34)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by nikita-fuchs** [comment]
Probably related to a full disc ?  See ENOSPC -> https://stackoverflow.com/questions/22475849/node-js-what-is-enospc-error-and-how-to-solve

**Comment by honestbonsai** [comment]
Thanks for the link @nikita-fuchs 

@uracilo Did going through that StackOverflow link that solve your issue?

**Comment by davidmurdoch** [comment]
Closing in favor of #579.
