### ISSUE TITLE
Ganache freezes after running for longer time [1.2.0. - 2.0b latest]

### ISSUE THREAD

**Issue by nikita-fuchs** [trufflesuite/ganache#1115]
Ganache freezes on Ubuntu when running for days.

## Expected Behavior
Ganache running normally.

## Current Behavior
Log entry at launch: 

```
[2019/01/27 14:02:53.270] - Starting server (version 2.0.0-beta.2) with initial configuration: 
{"gasLimit":8021975,
"gasPrice":20000000000,
"db_path":"/home/XYZ-software/.config/Ganache/workspaces/lowly-coal/chaindata",
"default_balance_ether":100,
"hostname":"0.0.0.0","
locked":false,
"network_id":5777,
"port":7545,
"total_accounts":100,
"unlocked_accounts":[],
"verbose":false,
"vmErrorsOnRPCResponse":true,
"logDirectory":"/home/XYZ-software/Desktop/XYZ-Blockchainpayment/truffle-project"} 
```

after around 77MB of log entries for `eth_getFilterChanges`, the last line reads:

```
[2019/02/05 13:11:44.356] - eth_getFilterChanges
```

and the window is just white.

## Steps to Reproduce (for bugs)
1. Start Ganache in Ubuntu with 100 accounts 
2. Deploy a contract
3. Have a nodejs instance filtering for contract events

## Your Environment
Ubuntu 16

**Comment by wbt** [comment]
This might be a duplicate of (same problem as) #947; I'm not sure.  
I have created a test repo [here](https://github.com/wbt/overwhelmer) which appears to demonstrate the issue, on Windows.

**Comment by davidmurdoch** [comment]
My _hunches_ why Ganache fails here is that:

1. ethereumjs-vm, used internally by ganache-core never evicts its cache under normal operations. The more addresses and storage you interact with the heavier that cache will become
2. the transaction log and events log pages are rendered in full. You could have 10s of thousands of logs stored and memory as well as all the DOM elements for each rendered to the UI.

It is possible to fix both issues.

This first issue probably doesn't cause too much harm, and the next version of ganache-core should alleviate much of this issue anyway.

Storing the logs in memory isn't the most immediate issue, but rendering that many elements to the DOM probably is. It is possible to lazy scroll these efficiently with something like: https://bvaughn.github.io/react-virtualized/#/components/List

**Comment by wbt** [comment]
@davidmurdoch 
Nice hunches.  However, I discount especially #1 as the test repo interacts with just **one** contract at **one** address, and in 'overwrite' mode, **one*** storage within that address.  (*: A little more complex because it's a string; you can change it if that seems important).  It also fires no events for event logs.
So while those points you identified may be issues and may be worth fixing, I suspect there's something else going on at the root of the observed problem. 
I could also be missing something, too.

**Comment by nikita-fuchs** [comment]
Thank you both guys, we will remove logging completely and do a custom build, as it is indeed not a good idea to bloat the DOM with thousands of entries. I thought they would be lazy loaded already (before looking at the code), but it's not the case obviously. Will report if that helps.

**Comment by davidmurdoch** [comment]
I _could_ be wrong about the DOM being the issue if you have different tab open. @honestbonsai or @adrianmcli would know better.

**Comment by pazolka** [comment]
Hey, 

I've removed logging in `./src/common/redux/logs/reducers.js` and I'll run a modified instance for a couple of days to see if the problem still occurs.

However, when testing with the [overwhelmer](https://github.com/wbt/overwhelmer) on Ubuntu 18.04 and sending 5000 transactions, the following error showed up:

![screenshot from 2019-02-22 11-21-01](https://user-images.githubusercontent.com/25148251/53242775-110c4a80-36a6-11e9-896e-374258810041.png)

It's probably unrelated to our issue, but it can have sth to do with #947. The full error message:

```
Error: CONNECTION ERROR: Couldn't connect to node on WS.
    at Object.InvalidConnection (/node_modules/web3-core-helpers/src/errors.js:35:16)
    at WebsocketProvider._timeout (/node_modules/web3-providers-ws/src/index.js:249:48)
    at W3CWebSocket.connection.onclose (/node_modules/web3-providers-ws/src/index.js:149:15)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onClose (/node_modules/websocket/lib/W3CWebSocket.js:228:10)
    at WebSocketConnection.<anonymous> (/node_modules/websocket/lib/W3CWebSocket.js:201:17)
    at emitTwo (events.js:125:13)
    at WebSocketConnection.emit (events.js:213:7)
    at WebSocketConnection.handleSocketClose (/node_modules/websocket/lib/WebSocketConnection.js:387:14)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at TCP._handle.close [as _onclose] (net.js:549:12)
```

**Comment by honestbonsai** [comment]
React should be unmounting the components if you switch to another tab. I'd have to look a bit closer at the exact implementation to be sure though.

**Comment by nikita-fuchs** [comment]
It unmounts them I think, but the memory issues get critical in general and
I think it shows, in the UI. plus if you open the logs tab, things suddenly
become really laggy.

Am Fr., 22. Feb. 2019 um 17:01 Uhr schrieb Heyse Li <
notifications@github.com>:

**Comment by wbt** [comment]
In my tests, I don't have any "different tabs" open in Ganache, beyond what shows up when the application is launched and starts running.  After a run, to test for responsiveness, I click "settings" and then (if that works) "cancel" to return, but I don't e.g. click on "logs."

**Comment by adrianmcli** [comment]
To truly test this and make sure it's a memory issue (and not a DOM one), we should try to disable the rendering of the log items at all and see if the issue persists.

**Comment by nikita-fuchs** [comment]
@pazolka did so in her custom build and ran the [overwhelmer](https://github.com/wbt/overwhelmer) , which made it crash as seen in the screen shot above. the migration script of the overwhelmer literally overwhelms truffle, though, by hammering thousands of promises simultaneously (look at the migrations script) instead of using async/await. Anyways, we will put that custom built into action for the original use case (just lots and lots of filter requests) in around 12h and see how it goes.

This use case and the overwhelmer need to be tested with ganache cli though, too, as the overwhelmer was also successful in overwhelming ganache cli.

@adrianmcli : It would be great to add numbers to each line of output, so it would be easier to find out when ganache exactly stops and whether it's always at the same output amount (both UI and GUI)

**Comment by nikita-fuchs** [comment]
So we found a workaround: excessive logging is indeed a way to make ganache freeze. And excessive logging is just what happens when constantly filtering for events.

Here is what you can do to disable it: https://github.com/nikita-fuchs/ganache/commit/51f96024d3fd74573776892186d02711e17c3621

Strangely, when we've built ganache ourselves, we got an error when reading the truffle.js file. But Simply doing ```npm run``` spawned a perfectly working instance that also keeps the working spaces' states (seems so for now, everyone test for her/himself) . 🥳

I suggest implemening lazyloading on the logs, 3000 elements in DOM makes it explode ;)

**Comment by honestbonsai** [comment]
@nikita-fuchs Broke out the lazy loading on logs into its own issue. Regardless of whether or not it resolves this issue (@pazolka 's investigation seems to indicate some other possible issues), it's a good thing to do anyways.
