### ISSUE TITLE
"Error: Missing parameter: provider" when using ganache-cli as web3 provider

### ISSUE THREAD

**Issue by v-almonacid** [trufflesuite/ganache#1116]
Using ganache-cli as a web3 provider library doesn't seem to work in the current version.

## Steps to reproduce:

```
const ganache = require('ganache-cli');
const Web3 = require('web3');
const provider = ganache.provider();
const web3 = new Web3();
web3.setProvider(provider);
```
Running this simple snippet throws:
```
Error: Missing parameter: provider
    at Function.throwIfMissing (/home/vicente/dev/testing/node_modules/web3-core/dist/web3-core.cjs.js:148:13)
    at Web3.AbstractWeb3Module (/home/vicente/dev/testing/node_modules/web3-core/dist/web3-core.cjs.js:17:107)
    at new Web3 (/home/vicente/dev/testing/node_modules/web3/dist/web3.cjs.js:30:68)
    at Object.<anonymous> (/home/vicente/dev/testing/ganache-web3/main.js:5:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

Environment: Ubuntu 16.04
ganache-cli version: ^6.3.0
web3: ^1.0.0-beta.43

Current fix: by downgrading to `web3@1.0.0-beta.37` everything works well

Not sure if this is linked to web3 or ganache.

**Comment by davidmurdoch** [comment]
Closing as we are currently tracking this issue in https://github.com/trufflesuite/ganache-core/issues/290 and https://github.com/ethereum/web3.js/issues/2266
