### ISSUE TITLE
System Error when running Ganache 1.3.0 on linux

### ISSUE THREAD

**Issue by dev1644** [trufflesuite/ganache#1118]
Hi, I tried to set-up the initial account balance of all accounts as `1e+21` and now I can't start Ganache,
it keeps crashing, I think ganache uses `toString()` method to convert the specified amount in String,
as I provided `1e+21` it is failing to do so.

PLATFORM: linux
GANACHE VERSION: 1.3.0

EXCEPTION:
```
Error: while converting number to string, invalid number value '1e+21', should be a number matching (^-?[0-9.]+).
    at numberToString (/node_modules/ganache-core/node_modules/ethjs-unit/lib/index.js:61:13)
    at Object.toWei (/node_modules/ganache-core/node_modules/ethjs-unit/lib/index.js:114:15)
    at Object.toWei (/node_modules/ganache-core/node_modules/web3-utils/src/index.js:227:75)
    at StateManager.initialize (/node_modules/ganache-core/lib/statemanager.js:102:45)
    at new GethApiDouble (/node_modules/ganache-core/lib/subproviders/geth_api_double.js:25:14)
    at new Provider (/node_modules/ganache-core/lib/provider.js:25:23)
    at Object.create (/node_modules/ganache-core/lib/server.js:14:20)
    at Object.server (/node_modules/ganache-core/public-exports.js:10:19)
    at /src/chain/chain.js:87:25
    at stopServer (/src/chain/chain.js:41:5)
    at startServer (/src/chain/chain.js:46:3)
    at process.<anonymous> (/src/chain/chain.js:158:7)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at process.emit (/node_modules/ganache-core/node_modules/source-map-support/source-map-support.js:461:21)
    at emit (internal/child_process.js:768:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: Starting server (version 1.3.0) with initial configuration: {"hostname":"127.0.0.1","port":7545,"network_id":5777,"default_balance_ether":1e+21,"total_accounts":10,"unlocked_accounts":[],"locked":false,"vmErrorsOnRPCResponse":true,"verbose":false,"gasLimit":6721975,"gasPrice":20000000000,"hardfork":"constantinople"}
```

**Comment by dev1644** [comment]
I fixed it, open the File `Settings`in directory `$HOME/.config/Ganache/`, and change the `default_balance_ether` to 100 or any other reasonable amount, save it and restart Ganache.

**Comment by davidmurdoch** [comment]
Probably related to https://github.com/trufflesuite/ganache/issues/847
