### ISSUE TITLE
System Error when running Ganache 1.3.0 on darwin

### ISSUE THREAD

**Issue by jkcomment** [trufflesuite/ganache#1124]
PLATFORM: darwin
GANACHE VERSION: 1.3.0

EXCEPTION:
```
Error: nonce generation function failed or private key is invalid
    at Object.exports.ecsign (/node_modules/ganache-core/node_modules/ethereumjs-util/dist/index.js:369:23)
    at Transaction.sign (/node_modules/ganache-core/node_modules/ethereumjs-tx/es5/index.js:252:23)
    at Transaction.sign (/node_modules/ganache-core/lib/utils/transaction.js:260:10)
    at Transaction.hash (/node_modules/ganache-core/node_modules/ethereumjs-tx/fake.js:66:12)
    at Transaction.fakeHash [as hash] (/node_modules/ganache-core/lib/utils/transaction.js:17:51)
    at RuntimeError.combine (/node_modules/ganache-core/lib/utils/runtimeerror.js:42:30)
    at new RuntimeError (/node_modules/ganache-core/lib/utils/runtimeerror.js:19:8)
    at Function.RuntimeError.fromResults (/node_modules/ganache-core/lib/utils/runtimeerror.js:89:13)
    at /node_modules/ganache-core/lib/blockchain_double.js:516:30
    at /node_modules/ganache-core/node_modules/ethereumjs-vm/dist/runTx.js:70:9
    at /node_modules/ganache-core/node_modules/async/dist/async.js:969:16
    at next (/node_modules/ganache-core/node_modules/async/dist/async.js:5225:18)
    at /node_modules/ganache-core/node_modules/ethereumjs-vm/dist/cache.js:93:9
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/util.js:51:36
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:52:16
    at done (/node_modules/ganache-core/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:246:17)
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:44:16
    at /node_modules/ganache-core/lib/database/levelupobjectadapter.js:110:7
    at /node_modules/ganache-core/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/node_modules/ganache-core/node_modules/async/dist/async.js:1064:13)
    at /node_modules/ganache-core/node_modules/async/dist/async.js:969:16
    at /node_modules/ganache-core/node_modules/level-sublevel/shell.js:53:51
```

APPLICATION LOG:
```
T+0ms: Starting server (version 1.3.0) with initial configuration: {"hostname":"127.0.0.1","network_id":5777,"port":7545,"total_accounts":10,"unlocked_accounts":[],"default_balance_ether":100,"locked":false,"vmErrorsOnRPCResponse":true,"verbose":false,"gasLimit":6721975,"gasPrice":20000000000,"hardfork":"constantinople"}
T+23ms: Ganache started successfully!
T+23ms: Waiting for requests...
T+53082ms: net_version
T+53092ms: eth_accounts
T+53120ms: eth_call
T+53155ms: eth_call
T+53176ms: eth_accounts
T+53195ms: eth_sendTransaction
T+53237ms:   Transaction: 0x0b3a7aa3ff97a65cf53aa9ce381e8b597fef0568741b87f03ac9139c4c9b4713
T+53237ms:   Contract created: 0x16056b56914a430f850890bf4afeca1534943423
T+53237ms:   Gas usage: 277462
T+53237ms:   Block Number: 1
T+53237ms:   Block Time: Thu Feb 14 2019 17:18:30 GMT+0900 (JST)
T+53238ms: eth_newBlockFilter
T+53240ms: eth_getFilterChanges
T+53255ms: eth_getTransactionReceipt
T+53261ms: eth_getCode
T+53271ms: eth_uninstallFilter
T+53272ms: eth_sendTransaction
T+53320ms:   Transaction: 0x609860ac8ec719798fffd974b76eb23ee326ed71847ba6b37caa0daa195bfb36
T+53320ms:   Gas usage: 42008
T+53320ms:   Block Number: 2
T+53321ms:   Block Time: Thu Feb 14 2019 17:18:31 GMT+0900 (JST)
T+53322ms: eth_getTransactionReceipt
T+53322ms: eth_accounts
T+53340ms: eth_sendTransaction
T+53375ms:   Transaction: 0x8ebc258da17459abf3d9fd2014521d038a23c515f5d9c77f63c4aa6d1c2d2ae5
T+53375ms:   Contract created: 0xf888fb02af3a87551d4dd05603c8fb2f9a4cae13
T+53375ms:   Gas usage: 252160
T+53375ms:   Block Number: 3
T+53376ms:   Block Time: Thu Feb 14 2019 17:18:31 GMT+0900 (JST)
T+53378ms: eth_newBlockFilter
T+53379ms: eth_getFilterChanges
T+53379ms: eth_getTransactionReceipt
T+53398ms: eth_getCode
T+53416ms: eth_uninstallFilter
T+53418ms: eth_sendTransaction
T+53453ms:   Transaction: 0x297631d037e42f39ce890274838b135c946ecbadc7940d778eb84a39df379a82
T+53453ms:   Gas usage: 27008
T+53453ms:   Block Number: 4
T+53454ms:   Block Time: Thu Feb 14 2019 17:18:31 GMT+0900 (JST)
T+53454ms: eth_getTransactionReceipt
T+128063ms: net_version
T+128073ms: eth_accounts
T+128100ms: eth_call
T+180683ms: net_version
T+180695ms: eth_accounts
T+180727ms: eth_call
T+279279ms: net_version
T+279289ms: eth_accounts
T+279315ms: eth_call
T+374971ms: net_version
T+374983ms: eth_accounts
T+375009ms: eth_call
T+421208ms: net_version
T+421221ms: eth_accounts
T+421260ms: eth_call
T+482570ms: net_version
T+482579ms: eth_accounts
T+482604ms: eth_call
T+553401ms: net_version
T+553410ms: eth_accounts
T+553438ms: eth_call
T+603332ms: net_version
T+603342ms: eth_accounts
T+603371ms: eth_call
T+673503ms: net_version
T+673512ms: eth_accounts
T+673539ms: eth_call
T+704170ms: net_version
T+704187ms: eth_accounts
T+704205ms: eth_call
T+785463ms: net_version
T+785473ms: eth_accounts
T+785498ms: eth_call
T+794273ms: eth_call
T+794296ms: eth_getCode
T+831727ms: net_version
T+831739ms: eth_accounts
T+831768ms: eth_call
T+857986ms: net_version
T+857995ms: eth_accounts
T+858020ms: eth_call
T+953989ms: net_version
T+953998ms: eth_accounts
T+954023ms: eth_call
T+966437ms: eth_call
T+966462ms: eth_unsubscribe
```

**Comment by DiscRiskandBisque** [comment]
Hi @jkcomment, can you provide some context for what was happening when you encountered this error?

**Comment by davidmurdoch** [comment]
Hey there, @jkcomment. Is it possible you can provide more information as to what triggered this error?

**Comment by jkcomment** [comment]
@DiscRiskandBisque @davidmurdoch 
I'm sorry so late reply. There is currently no environment for this bug at hand.
Could you kindly wait for a couple of days?

**Comment by YanB25** [comment]
Same problem encountered. 
I'am sorry that it's difficult to provide a context, because I'm currently working on a complex system.
I will try to offer you more information.
