### ISSUE TITLE
System Error when running Ganache 2.0.0-beta.2 on darwin

### ISSUE THREAD

**Issue by michael-iglesias** [trufflesuite/ganache#1127]
I only have 1 workspace, whose parameters are as follows:
* Pointed to my truffle-config.js
* Host: 127.0.0.1:7545 (networkId: 5777)
* Automine -> enabled
* error on transaction failure -> enabled
* verbose logs -> enabled

PLATFORM: Mac OSX (darwin)
GANACHE VERSION: 2.0.0-beta.2

EXCEPTION:
```
TypeError: Cannot read property 'ast' of undefined
    at Object.getContractNode (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:37:33)
    at getStateVariables (/node_modules/truffle-decoder/dist/allocate/references.js:187:45)
    at Object.getContractStateVariables (/node_modules/truffle-decoder/dist/allocate/references.js:209:27)
    at TruffleContractDecoder.<anonymous> (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:78:55)
    at Generator.next (<anonymous>)
    at /node_modules/truffle-decoder/dist/interface/contract-decoder.js:7:71
    at Promise (<anonymous>)
    at __awaiter (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:3:12)
    at TruffleContractDecoder.init (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:69:16)
    at Object.getDecodedTransaction (/src/truffle-integration/decode.js:34:11)
    at process.<anonymous> (/src/truffle-integration/index.js:96:56)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:768:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+24671ms:  <         "name": "TypeError"
T+24671ms:  <       }
T+24671ms:  <     }
T+24671ms:  <   }
T+24714ms:  <   {
T+24714ms:  <     "id": 1550371143729,
T+24714ms:  <     "jsonrpc": "2.0",
T+24714ms:  <     "error": {
T+24714ms:  <       "message": "Subscription ID 0x1 not found.",
T+24714ms:  <       "code": -32000,
T+24714ms:  <       "data": {
T+24714ms:  <         "stack": "Error: Subscription ID 0x1 not found.\n    at SubscriptionSubprovider.eth_unsubscribe (/node_modules/ganache-core/node_modules/web3-provider-engine/subproviders/subscriptions.js:77:8)\n    at SubscriptionSubprovider.handleRequest (/node_modules/ganache-core/node_modules/web3-provider-engine/subproviders/subscriptions.js:133:12)\n    at next (/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:116:18)\n    at DelayedBlockFilter.handleRequest (/node_modules/ganache-core/lib/subproviders/delayedblockfilter.js:31:3)\n    at next (/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:116:18)\n    at RequestFunnel.handleRequest (/node_modules/ganache-core/lib/subproviders/requestfunnel.js:32:12)\n    at next (/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:116:18)\n    at Web3ProviderEngine._handleAsync (/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:103:3)\n    at Timeout._onTimeout (/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:87:12)\n    at ontimeout (timers.js:469:11)\n    at tryOnTimeout (timers.js:304:5)\n    at Timer.listOnTimeout (timers.js:264:5)",
T+24714ms:  <         "name": "Error"
T+24714ms:  <       }
T+24714ms:  <     }
T+24714ms:  <   }
T+24758ms:  <   {
T+24758ms:  <     "id": 1550371143729,
T+24758ms:  <     "jsonrpc": "2.0",
T+24758ms:  <     "error": {
T+24758ms:  <       "message": "Subscription ID 0x2 not found.",
T+24758ms:  <       "code": -32000,
T+24758ms:  <       "data": {
T+24758ms:  <         "stack": "Error: Subscription ID 0x2 not found.\n    at SubscriptionSubprovider.eth_unsubscribe (/node_modules/ganache-core/node_modules/web3-provider-engine/subproviders/subscriptions.js:77:8)\n    at SubscriptionSubprovider.handleRequest (/node_modules/ganache-core/node_modules/web3-provider-engine/subproviders/subscriptions.js:133:12)\n    at next (/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:116:18)\n    at DelayedBlockFilter.handleRequest (/node_modules/ganache-core/lib/subproviders/delayedblockfilter.js:31:3)\n    at next (/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:116:18)\n    at RequestFunnel.handleRequest (/node_modules/ganache-core/lib/subproviders/requestfunnel.js:32:12)\n    at next (/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:116:18)\n    at Web3ProviderEngine._handleAsync (/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:103:3)\n    at Timeout._onTimeout (/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:87:12)\n    at ontimeout (timers.js:469:11)\n    at tryOnTimeout (timers.js:304:5)\n    at Timer.listOnTimeout (timers.js:264:5)",
T+24758ms:  <         "name": "Error"
T+24758ms:  <       }
T+24758ms:  <     }
T+24758ms:  <   }
T+24795ms:  <   {
T+24795ms:  <     "id": 1550371143730,
T+24795ms:  <     "jsonrpc": "2.0",
T+24795ms:  <     "result": true
T+24795ms:  <   }
```

**Comment by haltman-at** [comment]
Could you check if this problem still occurs if you use the latest version of `truffle-decoder` with Ganache?  I notice you're getting errors in `allocate/references.ts`, an area of the code I've changed substantially (and also since renamed, which is why that jumped out at me as out-of-date).  Thank you!

**Comment by haltman-at** [comment]
Err, sorry, `truffle-decoder` is probably not something you would deal with directly.  Sorry, I'll have to ask the Ganache people about making sure that's up to date.  Thanks again!

**Comment by davidmurdoch** [comment]
Related to https://github.com/trufflesuite/ganache/issues/1091

**Comment by davidmurdoch** [comment]
This should now be fixed in our latest beta: https://github.com/trufflesuite/ganache/releases/tag/v2.0.1-beta.0 Let me know if you have an issues or if the fix doesn't work for you.
