### ISSUE TITLE
System Error when running Ganache 2.0.0-beta.2 on linux

### ISSUE THREAD

**Issue by kimborgen** [trufflesuite/ganache#1134]
When looking at either the Events page or a transaction which has events, this error will appear.
This error did not appear on contract creating transactions (which have an Event), but I did not test it on other event creating transactions. 

So i am guessing that it has something to do with a more complex event? If so, this was the event: 
```
event EventName(
    uint256 indexed var1,
    bytes32 indexed var2,
    address var3,
    address var4,
    uint256 var5,
    uint256 var6
);
```
The transactions in question also had multiple events of the same type.

_I would be happy to debug more if it would help :)_

PLATFORM: arch linux (manjaro i3)
GANACHE VERSION: 2.0.0-beta.2
Was running ganache in development mode 

EXCEPTION:
```
TypeError: Cannot read property 'ast' of undefined
    at Object.getContractNode (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:37:33)
    at getStateVariables (/node_modules/truffle-decoder/dist/allocate/references.js:187:45)
    at Object.getContractStateVariables (/node_modules/truffle-decoder/dist/allocate/references.js:209:27)
    at TruffleContractDecoder.<anonymous> (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:78:55)
    at Generator.next (<anonymous>)
    at /node_modules/truffle-decoder/dist/interface/contract-decoder.js:7:71
    at Promise (<anonymous>)
    at __awaiter (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:3:12)
    at TruffleContractDecoder.init (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:69:16)
    at Object.getDecodedEvent (/src/truffle-integration/decode.js:25:11)
    at process.<anonymous> (/src/truffle-integration/index.js:87:55)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:768:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: Starting server (version 2.0.0-beta.2) with initial configuration: {"gasLimit":6721975,"gasPrice":20000000000,"hostname":"127.0.0.1","port":7545,"network_id":5777,"default_balance_ether":100,"total_accounts":10,"unlocked_accounts":[],"locked":false,"vmErrorsOnRPCResponse":true,"verbose":false,"db_path":"/home/kim/.config/Electron/workspaces/Testing-workspace/chaindata"}
T+98ms: Ganache started successfully!
T+98ms: Waiting for requests...
T+111ms: eth_getCode
T+128ms: eth_subscribe
T+139ms: eth_getLogs
T+149ms: eth_subscribe
T+161ms: eth_getCode
T+7575ms: eth_unsubscribe
T+7601ms: eth_unsubscribe
T+7629ms: eth_unsubscribe
T+7629ms: eth_unsubscribe
T+7654ms: eth_unsubscribe
```

**Comment by eshaben** [comment]
Possibly related to #1091

**Comment by davidmurdoch** [comment]
This should now be fixed in our latest beta: https://github.com/trufflesuite/ganache/releases/tag/v2.0.1-beta.0 Let me know if you have any issues or if the fix doesn't work for you.
