### ISSUE TITLE
System Error when running Ganache 1.3.0 on darwin

### ISSUE THREAD

**Issue by joeyBerger** [trufflesuite/ganache#1135]
PLATFORM: darwin
GANACHE VERSION: 1.3.0

EXCEPTION:
```
Error: while converting number to string, invalid number value '1.0000000000000003e+21', should be a number matching (^-?[0-9.]+).
    at numberToString (/node_modules/ganache-core/node_modules/ethjs-unit/lib/index.js:61:13)
    at Object.toWei (/node_modules/ganache-core/node_modules/ethjs-unit/lib/index.js:114:15)
    at Object.toWei (/node_modules/ganache-core/node_modules/web3-utils/src/index.js:227:75)
    at StateManager.initialize (/node_modules/ganache-core/lib/statemanager.js:102:45)
    at new GethApiDouble (/node_modules/ganache-core/lib/subproviders/geth_api_double.js:25:14)
    at new Provider (/node_modules/ganache-core/lib/provider.js:25:23)
    at Object.create (/node_modules/ganache-core/lib/server.js:14:20)
    at Object.server (/node_modules/ganache-core/public-exports.js:10:19)
    at /src/chain/chain.js:87:25
    at Server.close (net.js:1596:9)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at Server.emit (events.js:207:7)
    at emitCloseNT (net.js:1647:8)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: Starting server (version 1.3.0) with initial configuration: {"hostname":"127.0.0.1","port":7545,"network_id":5777,"default_balance_ether":1.0000000000000003e+21,"total_accounts":10,"unlocked_accounts":[],"locked":false,"vmErrorsOnRPCResponse":true,"verbose":false,"gasLimit":20000000000,"gasPrice":20000000000,"hardfork":"constantinople"}
```

**Comment by joeyBerger** [comment]
I tried to increase the gas limit to the upper limits, and now cannot open Ganache...

**Comment by davidmurdoch** [comment]
Thanks for opening this issue, @joeyBerger.

This appears to be related to #847.
