### ISSUE TITLE
System Error when running Ganache 2.0.0-beta.2 on darwin

### ISSUE THREAD

**Issue by cds-amal** [trufflesuite/ganache#1136]
Had Ganache servicing 1 truffle projects for a few days... today attempted to service a second truffle project and it broke on migrating the second one.

PLATFORM: darwin
GANACHE VERSION: 2.0.0-beta.2
Develop branch: [aeaac84](https://github.com/trufflesuite/ganache/commit/aeaac84)

EXCEPTION:
```
TypeError: Cannot read property 'pop' of undefined
    at CheckpointTrie.Trie._updateNode (/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:360:23)
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:107:16
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:461:14
    at processNode (/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:471:23)
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:516:13
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:180:7
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/util.js:75:7
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:52:16
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:269:32
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:44:16
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/util.js:71:7
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:157:9
    at /node_modules/ganache-core/lib/database/levelupobjectadapter.js:41:16
    at /node_modules/ganache-core/node_modules/level-sublevel/shell.js:101:15
    at /node_modules/ganache-core/node_modules/level-sublevel/nut.js:121:19
    at /node_modules/ganache-core/node_modules/encoding-down/index.js:51:21
    at /node_modules/ganache-core/node_modules/cachedown/index.js:58:21
    at ReadFileContext.callback (/node_modules/ganache-core/lib/database/filedown.js:26:14)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
```

APPLICATION LOG:
```
T+308170302ms: eth_blockNumber
T+308190310ms: eth_blockNumber
T+308210316ms: eth_blockNumber
T+308230326ms: eth_blockNumber
T+308250331ms: eth_blockNumber
T+308270337ms: eth_blockNumber
T+308290342ms: eth_blockNumber
T+308310349ms: eth_blockNumber
T+308330354ms: eth_blockNumber
T+308350362ms: eth_blockNumber
T+308370371ms: eth_blockNumber
T+308390379ms: eth_blockNumber
T+308410385ms: eth_blockNumber
T+308430393ms: eth_blockNumber
T+308450402ms: eth_blockNumber
T+308470409ms: eth_blockNumber
T+308490414ms: eth_blockNumber
T+308510425ms: eth_blockNumber
T+308530434ms: eth_blockNumber
T+308550441ms: eth_blockNumber
T+308570451ms: eth_blockNumber
T+308590461ms: eth_blockNumber
T+308610467ms: eth_blockNumber
T+308630475ms: eth_blockNumber
T+308650483ms: eth_blockNumber
T+308670492ms: eth_blockNumber
T+308690500ms: eth_blockNumber
T+308710505ms: eth_blockNumber
T+308730514ms: eth_blockNumber
T+308750524ms: eth_blockNumber
T+308770532ms: eth_blockNumber
T+308790537ms: eth_blockNumber
T+308810546ms: eth_blockNumber
T+308830553ms: eth_blockNumber
T+308850562ms: eth_blockNumber
T+308870569ms: eth_blockNumber
T+308890579ms: eth_blockNumber
T+308910586ms: eth_blockNumber
T+308930593ms: eth_blockNumber
T+308950603ms: eth_blockNumber
T+308970610ms: eth_blockNumber
T+308990619ms: eth_blockNumber
T+309010628ms: eth_blockNumber
T+309030636ms: eth_blockNumber
T+309050651ms: eth_blockNumber
T+309070664ms: eth_blockNumber
T+309090672ms: eth_blockNumber
T+309110678ms: eth_blockNumber
T+309130689ms: eth_blockNumber
T+309150695ms: eth_blockNumber
T+309170709ms: eth_blockNumber
T+309190722ms: eth_blockNumber
T+309210734ms: eth_blockNumber
T+309230740ms: eth_blockNumber
T+309250755ms: eth_blockNumber
T+309270770ms: eth_blockNumber
T+309290780ms: eth_blockNumber
T+309310789ms: eth_blockNumber
T+309330797ms: eth_blockNumber
T+309350807ms: eth_blockNumber
T+309370818ms: eth_blockNumber
T+309390824ms: eth_blockNumber
T+309410833ms: eth_blockNumber
T+309430840ms: eth_blockNumber
T+309450851ms: eth_blockNumber
T+309470857ms: eth_blockNumber
T+309490864ms: eth_blockNumber
T+309510873ms: eth_blockNumber
T+309530879ms: eth_blockNumber
T+309550888ms: eth_blockNumber
T+309570894ms: eth_blockNumber
T+309590904ms: eth_blockNumber
T+309610912ms: eth_blockNumber
T+309630922ms: eth_blockNumber
T+309650929ms: eth_blockNumber
T+309670938ms: eth_blockNumber
T+309690945ms: eth_blockNumber
T+309710952ms: eth_blockNumber
T+309730961ms: eth_blockNumber
T+309750967ms: eth_blockNumber
T+309770976ms: eth_blockNumber
T+309790982ms: eth_blockNumber
T+309810990ms: eth_blockNumber
T+309830997ms: eth_blockNumber
T+309851006ms: eth_blockNumber
T+309871012ms: eth_blockNumber
T+309891020ms: eth_blockNumber
T+309911026ms: eth_blockNumber
T+309931035ms: eth_blockNumber
T+309951044ms: eth_blockNumber
T+309971050ms: eth_blockNumber
T+309991056ms: eth_blockNumber
T+310011065ms: eth_blockNumber
T+310031071ms: eth_blockNumber
T+310051080ms: eth_blockNumber
T+310071088ms: eth_blockNumber
T+310091094ms: eth_blockNumber
T+310111102ms: eth_blockNumber
T+310131110ms: eth_blockNumber
T+310151118ms: eth_blockNumber
T+310171126ms: eth_blockNumber
T+310191135ms: eth_blockNumber
T+310211142ms: eth_blockNumber
T+310231151ms: eth_blockNumber
T+310251158ms: eth_blockNumber
T+310271164ms: eth_blockNumber
T+310291171ms: eth_blockNumber
T+310311242ms: eth_blockNumber
T+310331188ms: eth_blockNumber
T+310351196ms: eth_blockNumber
T+310367383ms: net_version
T+310367392ms: eth_accounts
T+310367426ms: eth_getBlockByNumber
T+310367433ms: eth_accounts
T+310367450ms: eth_getBlockByNumber
T+310367457ms: net_version
T+310367462ms: eth_getBlockByNumber
T+310367469ms: eth_getBlockByNumber
T+310367474ms: net_version
T+310367482ms: eth_estimateGas
T+310367514ms: eth_unsubscribe
T+310367522ms: eth_unsubscribe
T+310367531ms: eth_unsubscribe
T+310367540ms: eth_unsubscribe
T+310367540ms: eth_unsubscribe
```

**Comment by DiscRiskandBisque** [comment]
Possibly related to #1152

**Comment by wbt** [comment]
I just encountered the same issue, with the trace through all the same filenames and positions, using the same version of Ganache on Windows 10 Pro. 
I had on the order of hundreds of transactions in the workspace (Quickstart) with proper operation, followed by about a day of inactivity, and then another attempt to issue transactions.  I noticed Ganche was unresponsive on RPC, returned attention to the GUI window, and saw this error. 
My server was set to automine, so the number of blocks should have been on the order of hundreds, which suggests a lower probability that this is causally connected to #1152.
