### ISSUE TITLE
TypeError in ganache-2.0.0-beta.2

### ISSUE THREAD

**Issue by Alirun** [trufflesuite/ganache#1140]
## Steps to Reproduce (for bugs)

1. Migrate contracts to ganache
2. Import truffle-config.json to ganache
3. Run Events or Contracts tab
4. See the error

## Context

TypeError: Cannot read property 'ast' of undefined
    at Object.getContractNode (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:37:33)
    at getStateVariables (/node_modules/truffle-decoder/dist/allocate/references.js:187:45)
    at Object.getContractStateVariables (/node_modules/truffle-decoder/dist/allocate/references.js:209:27)
    at TruffleContractDecoder.<anonymous> (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:78:55)
    at Generator.next (<anonymous>)
    at /node_modules/truffle-decoder/dist/interface/contract-decoder.js:7:71
    at Promise (<anonymous>)
    at __awaiter (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:3:12)
    at TruffleContractDecoder.init (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:69:16)
    at Object.getDecodedEvent (/src/truffle-integration/decode.js:25:11)
    at process.<anonymous> (/src/truffle-integration/index.js:87:55)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:768:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

![image](https://user-images.githubusercontent.com/3462173/53648193-93b17e80-3c3f-11e9-86d4-2b373d0cdfc5.png)

## Your Environment

* Version used: 2.0.0-beta.2
* Operating System and version: MacOS

**Comment by honestbonsai** [comment]
@Alirun Do you have a test repo we could look at?

**Comment by Alirun** [comment]
@honestbnsai Unfortunately I can’t provide you code for reproducing :(

**Comment by davidmurdoch** [comment]
Related to https://github.com/trufflesuite/ganache/issues/1091

**Comment by davidmurdoch** [comment]
This should now be fixed in our latest beta: https://github.com/trufflesuite/ganache/releases/tag/v2.0.1-beta.0 Let me know if you have any issues or if the fix doesn't work for you.
