### ISSUE TITLE
System Error when running Ganache 2.0.0-rc.1 on darwin

### ISSUE THREAD

**Issue by britalexander4** [trufflesuite/ganache#1141]
PLATFORM: darwin
GANACHE VERSION: 2.0.0-rc.1

EXCEPTION:
```
Error: watch /Users/brittanyalexander/Desktop/newbox/truffle.js ENOENT
    at exports._errnoException (util.js:1024:11)
    at FSWatcher.start (fs.js:1394:19)
    at Object.fs.watch (fs.js:1420:11)
    at ProjectFsWatcher.start (/src/truffle-integration/projectFsWatcher.js:40:29)
    at new ProjectFsWatcher (/src/truffle-integration/projectFsWatcher.js:25:10)
    at ProjectsWatcher.add (/src/truffle-integration/projectsWatcher.js:130:23)
    at process.<anonymous> (/src/truffle-integration/index.js:59:34)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by DiscRiskandBisque** [comment]
Took a look at this over the weekend; a few observations:

Able to reproduce on Windows with the `appx`, unable to on Windows and Ubuntu with the `develop` branch. Looks potentially like something went wrong with the build.

The error is a little more verbose on windows and mentions `Cannot find module 'C:\Program Files\WindowsApps\Ganache_2.0.0.0_x64__zh355ej5cj694\app\resources\app.asar\src\truffle-project-loader\index.js'`. So either the reference to the file is incorrect or `truffle-project-loader\index.js` isn't getting added to the build properly.

**Comment by DiscRiskandBisque** [comment]
Full Windows error message:
```
Error: internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'C:\Program Files\WindowsApps\Ganache_2.0.0.0_x64__zh355ej5cj694\app\resources\app.asar\src\truffle-project-loader\index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

    at Socket.child.stderr.on.data (C:\Program Files\WindowsApps\Ganache_2.0.0.0_x64__zh355ej5cj694\app\resources\app.asar\src\truffle-integration\projectDetails.js:31:15)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at Socket.Readable.push (_stream_readable.js:197:10)
    at Pipe.onread (net.js:589:20)
```

**Comment by DiscRiskandBisque** [comment]
Things I've tried (that didn't work):
- revert `package-lock` to last working version (`rc.0`)
- swap out `path` stitching for `require.resolve()`
- turn off `asar` bundling
