### ISSUE TITLE
Solidity 0.4.24 events - System Error when running Ganache 2.0.0-beta.2 on darwin

### ISSUE THREAD

**Issue by matthieu-merlyn** [trufflesuite/ganache#1148]
Deployed a few contracts (solidity 0.4.24) and executed some functions here and there.
Error is thrown as soon as I want to take a look at the events triggered by those functions, using the Events link in the top menu bar. However, when I first go to the contract itself and then click on the event no error is thrown.

Contracts are loosely based on ERC20 Token and Crowdsale definitions of OpenZeppelin 2.0.1
Truffle project linked with truffle-config.js file

PLATFORM: darwin
GANACHE VERSION: 2.0.0-beta.2

EXCEPTION:
```
TypeError: Cannot read property 'ast' of undefined
    at Object.getContractNode (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:37:33)
    at getStateVariables (/node_modules/truffle-decoder/dist/allocate/references.js:187:45)
    at Object.getContractStateVariables (/node_modules/truffle-decoder/dist/allocate/references.js:209:27)
    at TruffleContractDecoder.<anonymous> (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:78:55)
    at Generator.next (<anonymous>)
    at /node_modules/truffle-decoder/dist/interface/contract-decoder.js:7:71
    at Promise (<anonymous>)
    at __awaiter (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:3:12)
    at TruffleContractDecoder.init (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:69:16)
    at Object.getDecodedEvent (/src/truffle-integration/decode.js:25:11)
    at process.<anonymous> (/src/truffle-integration/index.js:87:55)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:768:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: Starting server (version 2.0.0-beta.2) with initial configuration: {"gasLimit":6721975,"gasPrice":20000000000,"hostname":"127.0.0.1","port":8546,"network_id":5777,"default_balance_ether":100,"total_accounts":10,"unlocked_accounts":[],"locked":false,"vmErrorsOnRPCResponse":true,"verbose":false,"db_path":"/Users/matthieumerlyn/Library/Application Support/Ganache/workspaces/solidity-0.4.24/chaindata"}
T+108ms: Ganache started successfully!
T+108ms: Waiting for requests...
T+121ms: eth_getCode
T+131ms: eth_subscribe
T+131ms: eth_getLogs
T+143ms: eth_subscribe
T+152ms: eth_getCode
T+184ms: eth_getCode
T+196ms: eth_getCode
T+3152ms: eth_unsubscribe
T+3167ms: eth_unsubscribe
T+3177ms: eth_unsubscribe
T+3188ms: eth_unsubscribe
```

**Comment by DiscRiskandBisque** [comment]
To make sure we're understanding you correctly: The error is thrown when trying to view the event via the Events page, but can be viewed successfully if accessed through clicking the event in the single-contract view?

**Comment by DiscRiskandBisque** [comment]
Potentially related to #1140.

**Comment by matthieu-merlyn** [comment]
> To make sure we're understanding you correctly: The error is thrown when trying to view the event via the Events page, but can be viewed successfully if accessed through clicking the event in the single-contract view?

Yes.

**Comment by davidmurdoch** [comment]
Related to https://github.com/trufflesuite/ganache/issues/1091

**Comment by davidmurdoch** [comment]
This should now be fixed in our latest beta: https://github.com/trufflesuite/ganache/releases/tag/v2.0.1-beta.0 Let me know if you have any issues or if the fix doesn't work for you.
