### ISSUE TITLE
2.0.0-rc.3 on darwin: Can't link Truffle project

### ISSUE THREAD

**Issue by honestbonsai** [trufflesuite/ganache#1160]
Happens whenever you try to link a Truffle project.

PLATFORM: darwin
GANACHE VERSION: 2.0.0-rc.3

EXCEPTION:
```
Error: Could not find 'node'. NodeJS is required to be installed to link Truffle projects.
    at ChildProcess.child.on.error (/src/truffle-integration/projectDetails.js:65:17)
    at emitOne (events.js:115:13)
    at ChildProcess.emit (events.js:210:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by honestbonsai** [comment]
Possible leads 
1. https://github.com/electron/electron/issues/7688

**Comment by honestbonsai** [comment]
`2.0.0-rc.2` not working either
