### ISSUE TITLE
System Error when running Ganache 2.0.0 on win32

### ISSUE THREAD

**Issue by mscurie** [trufflesuite/ganache#1173]
PLATFORM: win32
GANACHE VERSION: 2.0.0

EXCEPTION:
```
Error: connection not open
    at WebsocketProvider.send (C:\Program Files\WindowsApps\Ganache_2.0.0.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\web3-providers-ws\src\index.js:276:18)
    at Timeout._onTimeout (C:\Program Files\WindowsApps\Ganache_2.0.0.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\web3-providers-ws\src\index.js:261:19)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
    at listOnTimeoutNT (timers.js:340:26)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: Starting server (version 2.0.0) with initial configuration: {"gasLimit":6721975,"gasPrice":20000000000,"hardfork":"petersburg","hostname":"0.0.0.0","port":7545,"network_id":5777,"default_balance_ether":100,"total_accounts":10,"unlocked_accounts":[],"locked":false,"vmErrorsOnRPCResponse":true,"verbose":false,"db_path":"C:\\Users\\gaibo\\AppData\\Roaming\\Ganache\\workspaces\\pet-shop-tutorial\\chaindata"}
T+77ms: Ganache started successfully!
T+77ms: Waiting for requests...
```

**Comment by davidmurdoch** [comment]
Thanks for opening the issue, @mscurie! This looks to be related to the bug #1172 you filed so I'm closing this Issue to track it there. Thanks!

**Comment by davidmurdoch** [comment]
This should now be fixed in our latest beta: https://github.com/trufflesuite/ganache/releases/tag/v2.0.1-beta.0 Let me know if you have an issues or if the fix doesn't work for you.
