### ISSUE TITLE
System Error when running Ganache 2.0.0 on darwin

### ISSUE THREAD

**Issue by bbjay** [trufflesuite/ganache#1175]
After "save & restart" after adding the following truffle.js with "add project"
```
var HDWalletProvider = require("truffle-hdwallet-provider");
const mnemonic = "...";
 module.exports = {
   networks: {
     development: {
       host: "127.0.0.1",
       port: 7545,
       network_id: "*"
     },
     ropsten: {
      provider: new HDWalletProvider(mnemonic, "https://ropsten.infura.io/"),
      gasPrice: 1200000000, // 1.2 Gwei
      network_id: "3"
    }
   }
 };


```

PLATFORM: darwin
GANACHE VERSION: 2.0.0

EXCEPTION:
```
Error: internal/child_process.js:715
    var string = JSON.stringify(message) + '\n';
                      ^

TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at process.target._send (internal/child_process.js:715:23)
    at process.target.send (internal/child_process.js:626:19)
    at Object.<anonymous> (/private/var/folders/d3/tzjgh9g08xj0kr001s7_nfjr0000gp/T/ganache119224-78370-1wu8lsz.s03k/index.js:33:11)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:696:3)

    at Socket.child.stderr.on.data (/src/truffle-integration/projectDetails.js:73:15)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at Socket.Readable.push (_stream_readable.js:197:10)
    at Pipe.onread (net.js:589:20)
```

**Comment by DiscRiskandBisque** [comment]
Related to #1182, #1181

**Comment by davidmurdoch** [comment]
This should now be fixed in our latest beta: https://github.com/trufflesuite/ganache/releases/tag/v2.0.1-beta.0 Let me know if you have any issues or if the fix doesn't work for you.

**Comment by bbjay** [comment]
It works now. Thanks!
