### ISSUE TITLE
System Error when running Ganache 2.0.0 on win32

### ISSUE THREAD

**Issue by RAKASG** [trufflesuite/ganache#1177]
PLATFORM: win32
GANACHE VERSION: 2.0.0

EXCEPTION:
```
Error: Could not find 'node'. NodeJS is required to be installed to link Truffle projects.
    at ChildProcess.child.on.error (C:\Users\Administrator\AppData\Local\Programs\Ganache\resources\app.asar\src\truffle-integration\projectDetails.js:65:17)
    at emitOne (events.js:115:13)
    at ChildProcess.emit (events.js:210:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by davidmurdoch** [comment]
This may now be fixed in our latest beta: https://github.com/trufflesuite/ganache/releases/tag/v2.0.1-beta.0 Let me know if you have any issues or if the fix doesn't work for you.
