### ISSUE TITLE
System Error when running Ganache 2.0.0 on darwin

### ISSUE THREAD

**Issue by akud82** [trufflesuite/ganache#1178]
PLATFORM: darwin
GANACHE VERSION: 2.0.0

EXCEPTION:
```
TypeError: Cannot read property 'nodes' of undefined
    at getStateVariables (/node_modules/truffle-decoder/dist/allocate/storage.js:146:24)
    at vars.concat.linearizedBaseContractsFromBase.map (/node_modules/truffle-decoder/dist/allocate/storage.js:154:73)
    at Array.map (native)
    at allocateContract (/node_modules/truffle-decoder/dist/allocate/storage.js:154:61)
    at Object.getStorageAllocations (/node_modules/truffle-decoder/dist/allocate/storage.js:28:23)
    at TruffleContractDecoder.init (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:87:43)
    at Object.getDecodedEvent (/src/truffle-integration/decode.js:42:11)
    at process.<anonymous> (/src/truffle-integration/index.js:92:31)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:768:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+73813ms: eth_getBlockByNumber
T+73813ms: eth_getBlockByNumber
T+73813ms: eth_getBlockByNumber
T+73813ms: eth_estimateGas
T+73813ms: eth_getBlockByNumber
T+73813ms: eth_blockNumber
T+73813ms: eth_sendTransaction
T+73873ms:   Transaction: 0xaf25d5a89e1c67aa5c8a6f8d5ccb6b6f64aa3353d3165d9b12890435c6f9925a
T+73873ms:   Contract created: 0x1aae84e31aa3ee2b3628b89835efd977d6e908e0
T+73873ms:   Gas usage: 107462
T+73873ms:   Block Number: 49
T+73873ms:   Block Time: Mon Mar 25 2019 15:21:55 GMT+0400 (+04)
T+73929ms: eth_getBlockByNumber
T+73987ms: eth_getTransactionReceipt
T+74043ms: eth_getCode
T+74110ms: eth_getTransactionByHash
T+74168ms: eth_getBalance
T+74426ms: eth_getBlockByNumber
T+74426ms: eth_getBlockByNumber
T+74426ms: eth_getBlockByNumber
T+74426ms: eth_estimateGas
T+74426ms: eth_getBlockByNumber
T+74426ms: eth_blockNumber
T+74426ms: eth_sendTransaction
T+74426ms:   Transaction: 0x970d0e90b9c1f21acea17513f68d9070adf7ca163a434668981f8dcdbf9c9720
T+74426ms:   Contract created: 0x070784fccd192df2375644d312f2ee4ae4fff296
T+74426ms:   Gas usage: 74306
T+74426ms:   Block Number: 50
T+74426ms:   Block Time: Mon Mar 25 2019 15:21:55 GMT+0400 (+04)
T+74426ms: eth_getBlockByNumber
T+74426ms: eth_getTransactionReceipt
T+74426ms: eth_getCode
T+74426ms: eth_getTransactionByHash
T+74426ms: eth_getBalance
T+74426ms: eth_getBlockByNumber
T+74426ms: eth_getBlockByNumber
T+74426ms: eth_getBlockByNumber
T+74426ms: eth_estimateGas
T+74426ms: eth_getBlockByNumber
T+74426ms: eth_blockNumber
T+74426ms: eth_sendTransaction
T+74426ms:   Transaction: 0x851bcaff82dddd6f9cb434c6fbf9c828bb8c065f7e1d01ef36fba80ecbee6539
T+74426ms:   Contract created: 0xb75b7f35f11fa30af479b1802e90bfb80354a254
T+74426ms:   Gas usage: 1947412
T+74426ms:   Block Number: 51
T+74426ms:   Block Time: Mon Mar 25 2019 15:21:55 GMT+0400 (+04)
T+74426ms: eth_getBlockByNumber
T+74426ms: eth_getTransactionReceipt
T+74426ms: eth_getCode
T+74426ms: eth_getTransactionByHash
T+74426ms: eth_getBalance
T+74467ms: eth_getBlockByNumber
T+74511ms: eth_getBlockByNumber
T+74561ms: eth_getBlockByNumber
T+74604ms: eth_estimateGas
T+74651ms: eth_getBlockByNumber
T+74651ms: eth_blockNumber
T+74887ms: eth_sendTransaction
T+74887ms:   Transaction: 0xba0e7e0d3fde1c3e2de64030653d5e9bb82c53dca65a8abf1475cd07d5476112
T+74887ms:   Contract created: 0x02a26fef61069e8f0a82ba6b767c38b7c8cf67a7
T+74887ms:   Gas usage: 412182
T+74887ms:   Block Number: 52
T+74887ms:   Block Time: Mon Mar 25 2019 15:21:56 GMT+0400 (+04)
T+74887ms: eth_getBlockByNumber
T+74887ms: eth_getTransactionReceipt
T+74887ms: eth_getCode
T+74887ms: eth_getTransactionByHash
T+74887ms: eth_getBalance
T+74887ms: eth_getBlockByNumber
T+74887ms: eth_getBlockByNumber
T+74887ms: eth_getBlockByNumber
T+74887ms: eth_estimateGas
T+74887ms: eth_getBlockByNumber
T+74887ms: eth_blockNumber
T+74887ms: eth_sendTransaction
T+74887ms:   Transaction: 0xe3a7b3cb4af1fdffc807080cfd4922b7426ed1b5ba1ef165f73b7cf824619672
T+74887ms:   Contract created: 0x5357c5a49865ea49d2a40ae4c96c51be583f3861
T+74887ms:   Gas usage: 199675
T+74887ms:   Block Number: 53
T+74887ms:   Block Time: Mon Mar 25 2019 15:21:56 GMT+0400 (+04)
T+74887ms: eth_getBlockByNumber
T+74887ms: eth_getTransactionReceipt
T+74887ms: eth_getCode
T+74887ms: eth_getTransactionByHash
T+74887ms: eth_getBalance
T+74887ms: eth_getBlockByNumber
T+74887ms: eth_getBlockByNumber
T+74887ms: eth_getBlockByNumber
T+74887ms: eth_estimateGas
T+75141ms: eth_getBlockByNumber
T+75141ms: eth_blockNumber
T+75141ms: eth_sendTransaction
T+75141ms:   Transaction: 0x4b0bca871bcfdc3a8fd2e5e222a11273665b89ebf4abcf84d36d754345767c6a
T+75141ms:   Contract created: 0xb611fcb7a05afca2b76a1ea85ac3491d20fb990f
T+75141ms:   Gas usage: 1745552
T+75141ms:   Block Number: 54
T+75141ms:   Block Time: Mon Mar 25 2019 15:21:56 GMT+0400 (+04)
T+75141ms: eth_getBlockByNumber
T+75141ms: eth_getTransactionReceipt
T+75141ms: eth_getCode
T+75141ms: eth_getTransactionByHash
T+75141ms: eth_getBalance
T+75141ms: eth_getBlockByNumber
T+75141ms: eth_getBlockByNumber
T+75141ms: eth_sendTransaction
T+75497ms:   Transaction: 0x13d5dab3bd6d78b50bb0f3d40e79566641ae88240ce38228b9f215c7a8cf2177
T+75497ms:   Gas usage: 27034
T+75497ms:   Block Number: 55
T+75497ms:   Block Time: Mon Mar 25 2019 15:21:56 GMT+0400 (+04)
T+75497ms: eth_getBlockByNumber
T+75497ms: eth_getTransactionReceipt
T+112131ms: eth_unsubscribe
T+112131ms: eth_unsubscribe
T+112208ms: eth_unsubscribe
T+112296ms: eth_unsubscribe
```

**Comment by tjvanderende** [comment]
Keep getting the same error.
Any fix?

**Comment by akud82** [comment]
Yes. I think the problem is here: https://github.com/trufflesuite/truffle/blob/a06a8c3204e17559173ccc13183935396b7e2279/packages/truffle-decoder/lib/interface/contract-decoder.ts#L135, when then getContractNode returns undefined, then the value in object is initialized as undefined.

**Comment by davidmurdoch** [comment]
Related: https://github.com/trufflesuite/ganache/issues/1169

**Comment by davidmurdoch** [comment]
Thanks for filing the issue, @akud82! We're working on a fix now!

**Comment by davidmurdoch** [comment]
This should now be fixed in our latest beta: https://github.com/trufflesuite/ganache/releases/tag/v2.0.1-beta.0 Let me know if you have any issues or if the fix doesn't work for you.

**Comment by davidmurdoch** [comment]
_Now_ Tthis issue should be fixed in the latest beta! https://github.com/trufflesuite/ganache/releases/tag/v2.0.2-beta.0
