### ISSUE TITLE
System Error when running Ganache 2.0.0 on win32

### ISSUE THREAD

**Issue by haraldini** [trufflesuite/ganache#1179]
Ganache crashing on each start

PLATFORM: win32
GANACHE VERSION: 2.0.0

EXCEPTION:
```
Error: connection not open
    at WebsocketProvider.send (C:\Users\user\AppData\Local\Programs\Ganache\resources\app.asar\node_modules\web3-providers-ws\src\index.js:276:18)
    at Timeout._onTimeout (C:\Users\user\AppData\Local\Programs\Ganache\resources\app.asar\node_modules\web3-providers-ws\src\index.js:261:19)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
```

APPLICATION LOG:
```
T+0ms: Starting server (version 2.0.0) with initial configuration: {"gasLimit":6721975,"gasPrice":20000000000,"hardfork":"petersburg","hostname":"0.0.0.0","port":8545,"network_id":5777,"default_balance_ether":100,"total_accounts":10,"unlocked_accounts":[],"locked":false,"vmErrorsOnRPCResponse":true,"verbose":false,"db_path":"C:\\Users\\user\\AppData\\Roaming\\Ganache\\workspaces\\edstack\\chaindata"}
T+410ms: Ganache started successfully!
T+410ms: Waiting for requests...
T+410ms: eth_blockNumber
T+445ms: eth_blockNumber
```

**Comment by davidmurdoch** [comment]
Thanks for opening the issue, @haraldini! This looks to be related to #1172 and is a bug in ganache-core that should get fixed in the next release (related PR: trufflesuite/ganache-core#385)!

**Comment by davidmurdoch** [comment]
This should now be fixed in our latest beta: https://github.com/trufflesuite/ganache/releases/tag/v2.0.1-beta.0 Let me know if you have an issues or if the fix doesn't work for you.
