### ISSUE TITLE
System Error when running Ganache 2.0.0 on darwin

### ISSUE THREAD

**Issue by akud82** [trufflesuite/ganache#1180]
PLATFORM: darwin
GANACHE VERSION: 2.0.0

EXCEPTION:
```
Error: CONNECTION ERROR: Couldn't connect to node on WS.
    at Object.InvalidConnection (/node_modules/web3-core-helpers/src/errors.js:35:16)
    at WebsocketProvider._timeout (/node_modules/web3-providers-ws/src/index.js:249:48)
    at W3CWebSocket.connection.onclose (/node_modules/web3-providers-ws/src/index.js:149:15)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onClose (/node_modules/websocket/lib/W3CWebSocket.js:228:10)
    at WebSocketConnection.<anonymous> (/node_modules/websocket/lib/W3CWebSocket.js:201:17)
    at emitTwo (events.js:125:13)
    at WebSocketConnection.emit (events.js:213:7)
    at WebSocketConnection.handleSocketClose (/node_modules/websocket/lib/WebSocketConnection.js:387:14)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at TCP._handle.close [as _onclose] (net.js:549:12)
```

APPLICATION LOG:
```
T+6520365ms:   Contract created: 0xf7956bb285cb873c2754ffd14e7da57deb8f480b
T+6520365ms:   Gas usage: 74306
T+6520365ms:   Block Number: 227
T+6520365ms:   Block Time: Mon Mar 25 2019 17:55:33 GMT+0400 (+04)
T+6520365ms: eth_getTransactionReceipt
T+6520365ms: eth_getCode
T+6520365ms: eth_getTransactionByHash
T+6520365ms: eth_getBalance
T+6520365ms: eth_getBlockByNumber
T+6520365ms: eth_getBlockByNumber
T+6520365ms: eth_getBlockByNumber
T+6520365ms: eth_estimateGas
T+6520365ms: eth_getBlockByNumber
T+6520365ms: eth_blockNumber
T+6520365ms: eth_sendTransaction
T+6521477ms:   Transaction: 0x44fec671816e76f181f82a60a3eef82c4b8a08c6c4fe7951c8509c73530b942c
T+6521477ms:   Contract created: 0x8ec403b61562c6c5cfe9b60a999a998d51eb8372
T+6521477ms:   Gas usage: 1944784
T+6521477ms:   Block Number: 228
T+6521477ms:   Block Time: Mon Mar 25 2019 17:55:34 GMT+0400 (+04)
T+6521477ms: eth_getTransactionReceipt
T+6521477ms: eth_getCode
T+6521477ms: eth_getTransactionByHash
T+6521477ms: eth_getBalance
T+6521477ms: eth_getBlockByNumber
T+6521477ms: eth_getBlockByNumber
T+6521477ms: eth_getBlockByNumber
T+6521477ms: eth_estimateGas
T+6521477ms: eth_getBlockByNumber
T+6521477ms: eth_blockNumber
T+6521477ms: eth_sendTransaction
T+6521477ms:   Transaction: 0x38a3caa1590de6d61fad514b48358b7c06085cea7b1c2b5fc4dff7ad1befdb00
T+6521477ms:   Contract created: 0x3d58a70f8a0e75d862203976d185576cfe38c853
T+6521477ms:   Gas usage: 412182
T+6521477ms:   Block Number: 229
T+6521477ms:   Block Time: Mon Mar 25 2019 17:55:34 GMT+0400 (+04)
T+6521477ms: eth_getTransactionReceipt
T+6521477ms: eth_getCode
T+6521479ms: eth_getTransactionByHash
T+6521713ms: eth_getBalance
T+6521713ms: eth_getBlockByNumber
T+6521713ms: eth_getBlockByNumber
T+6521713ms: eth_getBlockByNumber
T+6521713ms: eth_estimateGas
T+6521713ms: eth_getBlockByNumber
T+6521713ms: eth_blockNumber
T+6521713ms: eth_sendTransaction
T+6521713ms:   Transaction: 0x224e8dd7122ea5621153895934d1e92ac07209a82ac6e5d1858d40b277ba8c71
T+6521713ms:   Contract created: 0x7ee6674d3c95cf2898bbb242ac3b72f2814a7aa5
T+6521713ms:   Gas usage: 199675
T+6521713ms:   Block Number: 230
T+6521713ms:   Block Time: Mon Mar 25 2019 17:55:34 GMT+0400 (+04)
T+6521713ms: eth_getTransactionReceipt
T+6521713ms: eth_getCode
T+6521713ms: eth_getTransactionByHash
T+6521713ms: eth_getBalance
T+6521713ms: eth_getBlockByNumber
T+6521713ms: net_version
T+6521713ms: eth_getBlockByNumber
T+6521713ms: eth_getBlockByNumber
T+6521713ms: net_version
T+6521713ms: eth_estimateGas
T+6521713ms: eth_getBlockByNumber
T+6521713ms: eth_blockNumber
T+6521713ms: net_version
T+6521713ms: eth_sendTransaction
T+6521926ms:   Transaction: 0x6d4e39674ebdfc3940203acef36e1b848ba19144cfc2096920a0f276c2fcfe17
T+6521926ms:   Contract created: 0xe482b1a34e05e8918c9694d3f94f6eead0b2a671
T+6521926ms:   Gas usage: 1906529
T+6521926ms:   Block Number: 231
T+6521926ms:   Block Time: Mon Mar 25 2019 17:55:34 GMT+0400 (+04)
T+6521926ms: eth_getTransactionReceipt
T+6521926ms: eth_getCode
T+6521926ms: eth_getTransactionByHash
T+6521926ms: eth_getBalance
T+6521926ms: eth_getBlockByNumber
T+6521926ms: net_version
T+6521926ms: eth_getBlockByNumber
T+6521926ms: eth_getBlockByNumber
T+6521926ms: net_version
T+6521926ms: eth_estimateGas
T+6521926ms: eth_getBlockByNumber
T+6521926ms: eth_blockNumber
T+6521926ms: net_version
T+6521926ms: eth_sendTransaction
T+6521926ms:   Transaction: 0x738842ea3cdd327274d5df4d11c155f892ee1ade01eb9abaabe714477093f304
T+6521926ms:   Contract created: 0x2d3c67ae8c73c354b588ff248f634c2372795b0f
T+6521926ms:   Gas usage: 999395
T+6521926ms:   Block Number: 232
T+6521926ms:   Block Time: Mon Mar 25 2019 17:55:35 GMT+0400 (+04)
T+6521926ms: eth_getTransactionReceipt
T+6521926ms: eth_getCode
T+6521926ms: eth_getTransactionByHash
T+6521926ms: eth_getBalance
T+6521926ms: eth_getBlockByNumber
T+6521926ms: eth_getBlockByNumber
T+6521926ms: eth_getBlockByNumber
T+6522171ms: eth_estimateGas
T+6522171ms: eth_getBlockByNumber
T+6522171ms: eth_blockNumber
T+6522171ms: eth_sendTransaction
T+6522414ms:   Transaction: 0x765a023a89406f360cb53aec073adee782f8a6eab986a8865aaeea450bfbb7dc
T+6522414ms:   Contract created: 0x87d58f1e6ffb80f71d681e4c391098ebbaf132d2
T+6522414ms:   Gas usage: 1530794
T+6522414ms:   Block Number: 233
T+6522414ms:   Block Time: Mon Mar 25 2019 17:55:35 GMT+0400 (+04)
T+6522414ms: eth_getTransactionReceipt
T+6522414ms: eth_getCode
T+6522414ms: eth_getTransactionByHash
T+6522414ms: eth_getBalance
T+6541797ms: eth_unsubscribe
```

**Comment by davidmurdoch** [comment]
Closing in favor of #1497
