### ISSUE TITLE
System Error when adding truffle-config.js to Ganache 2.0.0 on linux

### ISSUE THREAD

**Issue by theevolvingfool** [trufflesuite/ganache#1181]
When I try to add the truffle-config.js of my project in the ganache quickstart or custom settings and try to save it I get the error mentioned below.

PLATFORM: linux
GANACHE VERSION: 2.0.0
EXCEPTION:
```
Error: internal/child_process.js:675
    var string = JSON.stringify(message) + '\n';
                      ^

TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at process.target._send (internal/child_process.js:675:23)
    at process.target.send (internal/child_process.js:586:19)
    at Object.<anonymous> (/tmp/ganache119226-6584-1u39kcw.gdwxi/index.js:33:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

    at Socket.child.stderr.on.data (/src/truffle-integration/projectDetails.js:73:15)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at Socket.Readable.push (_stream_readable.js:197:10)
    at Pipe.onread (net.js:589:20)
```

**truffle-config.js**

```
`const path = require("path");

module.exports = {
  contracts_build_directory: path.join(__dirname, "client/src/contracts"),
  networks: {
    development: {
      host: "127.0.0.1",
      port: 7545,
      network_id: "*" // Match any network id
    }
  }
};
`
```

**Comment by DiscRiskandBisque** [comment]
Potentially related to #1182

**Comment by davidmurdoch** [comment]
This should now be fixed in our latest beta: https://github.com/trufflesuite/ganache/releases/tag/v2.0.1-beta.0 Let me know if you have any issues or if the fix doesn't work for you.
