### ISSUE TITLE
Invalid behavior for selfdestructed contract

### ISSUE THREAD

**Issue by sarbogast** [trufflesuite/ganache#1186]
## Expected Behavior
After a contract selfdestructed, I expect any call to a view function on it, to give me an error saying the address is not a valid contract.
And I would expect any transaction sent to it to fail.

## Current Behavior
I'm using Ganache 2.0.0-beta.2 right now, and I wasn't able to test this behavior on Ganache 2.0.0 final, so it might have been fixed.
But right now, view function called to a selfdestructed contract result in the following cryptic error:
```
Error: Returned values aren't valid, did it run Out of Gas?
    at WebSocketConnection.processFrame (/usr/local/lib/node_modules/truffle/build/webpack:/~/websocket/lib/WebSocketConnection.js:552:1)
    at WebSocketConnection.EventEmitter.emit (domain.js:441:20)
    at WebSocketConnection.emit (events.js:189:13)
    at WebSocketConnection.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/websocket/lib/W3CWebSocket.js:205:1)
    at W3CWebSocket.onMessage (/usr/local/lib/node_modules/truffle/build/webpack:/~/websocket/lib/W3CWebSocket.js:234:1)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/usr/local/lib/node_modules/truffle/build/webpack:/~/yaeti/lib/EventTarget.js:107:1)
    at W3CWebSocket.WebsocketProvider.connection.onmessage (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/~/web3-providers-ws/src/index.js:98:1)
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/~/web3-providers-ws/src/index.js:121:1
    at Object.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:112:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-contract/~/web3-core-requestmanager/src/index.js:147:1
    at sendTxCallback (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-contract/~/web3-core-method/src/index.js:473:1)
    at Method.formatOutput (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-contract/~/web3-core-method/src/index.js:163:1)
    at Method.outputFormatter (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-contract/src/index.js:818:1)
    at Contract._decodeMethodReturn (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-contract/src/index.js:465:1)
    at ABICoder.decodeParameters (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-abi/src/index.js:226:1)
```

And when I send a transaction to it, the status of the transaction is still true and I don't get any error, even though the event at the end of my transactional function was not emitted, showing the function was interrupted alright.

## Context
I'm trying to show the students of my Udemy course what happens when you try to view the state or change the state of a selfdestructed contract, but this behaviour is completely inconsistent.

## Your Environment
* Version used: 2.0.0-beta.2
* Operating System and version: MacOS 10.14.3
* Link to your project:

**Comment by davidmurdoch** [comment]
This may be fixed in our latest beta: https://github.com/trufflesuite/ganache/releases/tag/v2.0.1-beta.0 Can you let me know if you have any issues or if the fix doesn't work for you?

**Comment by sarbogast** [comment]
I still have the same problem in the beta

**Comment by sarbogast** [comment]
To reproduce, you can:
- migrate the following project to Ganache: https://github.com/sarbogast/chainlist-truffle5 : `truffle migrate --compile-all --reset --network ganache`
- open a Truffle console: `truffle console --network ganache`
- get accounts: `accounts = await web3.eth.getAccounts()`
- get contract instance: `app = await ChainList.deployed()`
- call the kill function on the contract: `await app.kill({from: accounts[0]})`
- call any function on the now selfdestructed contract: `await app.getArticlesForSale()`
 
An I still get the same error as above:
Error: Returned values aren't valid, did it run Out of Gas?

**Comment by sarbogast** [comment]
And if I try to call a transactional function, I don't even get an error, the transaction just goes through with a 0 status and without emitting an event.
