### ISSUE TITLE
System Error when running Ganache 2.0.0 on win32

### ISSUE THREAD

**Issue by rohitraj27** [trufflesuite/ganache#1189]
PLATFORM: win32
GANACHE VERSION: 2.0.0

EXCEPTION:
```
Error: C:\Users\rohit\AppData\Local\Temp\ganache119228-3444-1wfjp68.h722i\index.js:9
  );
  ^

SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)

    at Socket.child.stderr.on.data (C:\Program Files\WindowsApps\Ganache_2.0.0.0_x64__zh355ej5cj694\app\resources\app.asar\src\truffle-integration\projectDetails.js:73:15)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at Socket.Readable.push (_stream_readable.js:197:10)
    at Pipe.onread (net.js:589:20)
```

**Comment by davidmurdoch** [comment]
@rohitraj27 Thanks for opening this issue!

This looks to be occurring when you add a truffle project to a Ganache workspace. Is that right? If so, it could be that your truffle.js (or truffle-config.js) file has a syntax error (an extra `)`). Can you check on this and let me know if that is what is happening here?

**Comment by davidmurdoch** [comment]
Possibly related: #1108

**Comment by davidmurdoch** [comment]
This should now be fixed in our latest beta: https://github.com/trufflesuite/ganache/releases/tag/v2.0.1-beta.0 Let me know if you have any issues or if the fix doesn't work for you.
