### ISSUE TITLE
System Error when running Ganache 2.0.0 on darwin (external file requirement)

### ISSUE THREAD

**Issue by loredanacirstea** [trufflesuite/ganache#1192]
Error when adding a Truffle project that contains:
```
const privateKey = fs.readFileSync("./private/privateKey.txt").toString().trim();
```
After removing the line, starting the project works.

PLATFORM: darwin
GANACHE VERSION: 2.0.0

EXCEPTION:
```
Error: fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open './private/privateKey.txt'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.<anonymous> (/Users/loredana/ETH/dType/contracts/truffle-config.js:24:23)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/private/var/folders/fk/p5q37dk97gd1bmbxtv3m45dr0000gp/T/ganache119229-88245-1lc3sti.2wsvl/index.js:31:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

    at Socket.child.stderr.on.data (/src/truffle-integration/projectDetails.js:73:15)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at Socket.Readable.push (_stream_readable.js:197:10)
    at Pipe.onread (net.js:589:20)
```

**Comment by davidmurdoch** [comment]
This should now be fixed in our latest beta: https://github.com/trufflesuite/ganache/releases/tag/v2.0.1-beta.0 Let me know if you have any issues or if the fix doesn't work for you.
