### ISSUE TITLE
System Error when running Ganache 2.0.0 on win32

### ISSUE THREAD

**Issue by freecsdn** [trufflesuite/ganache#1194]
PLATFORM: win32
GANACHE VERSION: 2.0.0

EXCEPTION:
```
Error: connection not open
    at WebsocketProvider.send (D:\Programs\Ganache\resources\app.asar\node_modules\web3-providers-ws\src\index.js:276:18)
    at Timeout._onTimeout (D:\Programs\Ganache\resources\app.asar\node_modules\web3-providers-ws\src\index.js:261:19)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
```

APPLICATION LOG:
```
T+0ms: eth_unsubscribe
T+0ms: eth_unsubscribe
T+0ms: eth_unsubscribe
T+0ms: eth_unsubscribe
T+1193ms: Starting server (version 2.0.0) with initial configuration: {"gasLimit":6721975,"gasPrice":20000000000,"hardfork":"petersburg","db_path":"C:\\Users\\Administrator\\AppData\\Roaming\\Ganache\\workspaces\\doubtful-horse\\chaindata","default_balance_ether":100,"hostname":"0.0.0.0","locked":false,"network_id":5777,"port":7545,"total_accounts":30,"unlocked_accounts":[],"verbose":false,"vmErrorsOnRPCResponse":true}
T+1860ms: Ganache started successfully!
T+1860ms: Waiting for requests...
```

**Comment by davidmurdoch** [comment]
Thanks for opening the issue, @freecsdn! This looks to be related to #1172; I'm just commenting here to link them together.

**Comment by davidmurdoch** [comment]
This should now be fixed in our latest beta: https://github.com/trufflesuite/ganache/releases/tag/v2.0.1-beta.0 Let me know if you have any issues or if the fix doesn't work for you.
