### ISSUE TITLE
System Error when running Ganache 2.0.0 on linux

### ISSUE THREAD

**Issue by tjvanderende** [trufflesuite/ganache#1203]
PLATFORM: linux
GANACHE VERSION: 2.0.0

EXCEPTION:
```
TypeError: Cannot read property 'nodes' of undefined
    at getStateVariables (/node_modules/truffle-decoder/dist/allocate/storage.js:146:24)
    at vars.concat.linearizedBaseContractsFromBase.map (/node_modules/truffle-decoder/dist/allocate/storage.js:154:73)
    at Array.map (native)
    at allocateContract (/node_modules/truffle-decoder/dist/allocate/storage.js:154:61)
    at Object.getStorageAllocations (/node_modules/truffle-decoder/dist/allocate/storage.js:28:23)
    at TruffleContractDecoder.init (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:87:43)
    at Object.getContractState (/src/truffle-integration/decode.js:18:11)
    at process.<anonymous> (/src/truffle-integration/index.js:76:31)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:768:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: Starting server (version 2.0.0) with initial configuration: {"gasLimit":6721975,"gasPrice":20000000000,"hardfork":"petersburg","hostname":"127.0.0.1","port":7545,"network_id":5777,"default_balance_ether":100,"total_accounts":10,"unlocked_accounts":[],"locked":false,"vmErrorsOnRPCResponse":true,"verbose":false,"db_path":"/home/xxx/.config/Ganache/workspaces/xxx-test/chaindata"}
T+136ms: Ganache started successfully!
T+136ms: Waiting for requests...
T+146ms: eth_getCode
T+158ms: eth_subscribe
T+158ms: eth_getLogs
T+166ms: eth_subscribe
T+179ms: eth_getCode
T+188ms: eth_getCode
T+22682ms: net_version
T+22738ms: eth_accounts
T+22752ms: eth_getBlockByNumber
T+22775ms: eth_getBlockByNumber
T+22786ms: eth_call
T+22809ms: eth_getBlockByNumber
T+22823ms: eth_getBlockByNumber
T+22837ms: eth_call
T+40399ms: net_version
T+40411ms: eth_accounts
T+40423ms: eth_getBlockByNumber
T+40441ms: eth_accounts
T+40452ms: eth_getBlockByNumber
T+40470ms: eth_getBlockByNumber
T+40481ms: eth_getBlockByNumber
T+40492ms: eth_estimateGas
T+40517ms: eth_getBlockByNumber
T+40529ms: eth_blockNumber
T+40547ms: eth_sendTransaction
T+45115ms:   Transaction: 0x8ac4c2b659bf97701b96ae217ec121b4641af096ad510d6748ca10ad2e554134
T+45115ms:   Contract created: 0xc92d11e12e2091a562f074ef1780efde61ecde0e
T+45115ms:   Gas usage: 2238033
T+45115ms:   Block Number: 43
T+45125ms:   Block Time: Tue Apr 02 2019 13:12:32 GMT+0200 (CEST)
T+45135ms: eth_getBlockByNumber
T+45151ms: eth_getTransactionReceipt
T+45161ms: eth_getCode
T+45186ms: eth_getTransactionByHash
T+45197ms: eth_getBalance
T+45215ms: eth_getBlockByNumber
T+45225ms: eth_getBlockByNumber
T+45236ms: eth_getBlockByNumber
T+45252ms: eth_estimateGas
T+45263ms: eth_getBlockByNumber
T+45280ms: eth_blockNumber
T+45290ms: eth_sendTransaction
T+45310ms:   Transaction: 0x3be792e6a0a9dd1a1abc6e1098c7e031935557dbe7dd20cb87f025938cb690a7
T+45310ms:   Contract created: 0xcf1372e957697f1848a81cb183eba9333e071a3b
T+45310ms:   Gas usage: 207013
T+45320ms:   Block Number: 44
T+45320ms:   Block Time: Tue Apr 02 2019 13:12:32 GMT+0200 (CEST)
T+45320ms: eth_getBlockByNumber
T+45332ms: eth_getTransactionReceipt
T+45355ms: eth_getCode
T+45373ms: eth_getTransactionByHash
T+45390ms: eth_getBalance
T+45401ms: eth_getBlockByNumber
T+45419ms: eth_getBlockByNumber
T+45429ms: eth_sendTransaction
T+45440ms:   Transaction: 0xbacd51cd3451a67c66daf8cf1a0b4de31e26cc1cbe331941c2eed1ce885b872c
T+45440ms:   Gas usage: 27034
T+45440ms:   Block Number: 45
T+45440ms:   Block Time: Tue Apr 02 2019 13:12:32 GMT+0200 (CEST)
T+45462ms: eth_getBlockByNumber
T+45472ms: eth_getTransactionReceipt
T+45502ms: eth_getBlockByNumber
T+45520ms: eth_accounts
T+45530ms: eth_getBlockByNumber
T+45541ms: eth_getBlockByNumber
T+45559ms: eth_getBlockByNumber
T+45569ms: eth_estimateGas
T+45587ms: eth_getBlockByNumber
T+45597ms: eth_blockNumber
T+45614ms: eth_sendTransaction
T+45625ms:   Transaction: 0x4a4a97fd7ae3427fd361279c7492d3703267ed61df50551fcf60e28d28f05354
T+45625ms:   Contract created: 0x6ce9109689ce075bba11def0bddd5eb961d65625
T+45625ms:   Gas usage: 284844
T+45625ms:   Block Number: 46
T+45625ms:   Block Time: Tue Apr 02 2019 13:12:32 GMT+0200 (CEST)
T+45625ms: eth_getTransactionReceipt
T+45625ms: eth_getCode
T+45636ms: eth_getTransactionByHash
T+45653ms: eth_getBalance
T+45665ms: eth_getBlockByNumber
T+45682ms: eth_getBlockByNumber
T+45693ms: eth_sendTransaction
T+45711ms:   Transaction: 0x1ef1ed94f1f65e5ee2e7ca54f5f699c3d9fd295a315ad64fbc5c34d1ecbc9759
T+45711ms:   Gas usage: 42034
T+45711ms:   Block Number: 47
T+45711ms:   Block Time: Tue Apr 02 2019 13:12:32 GMT+0200 (CEST)
T+45721ms: eth_getTransactionReceipt
T+45734ms: eth_getBlockByNumber
T+45800ms: eth_getBlockByNumber
T+55769ms: eth_unsubscribe
T+55784ms: eth_unsubscribe
T+55803ms: eth_unsubscribe
T+55816ms: eth_unsubscribe
T+55816ms: eth_unsubscribe
```
Can't seem to find any solution.
It happends when I create a custom function in my smart contract (the one which is crashed):

```
function getTotal() public pure returns (uint256 amount){
  return 10000000;
}
```
When I remove the function, it works without a problem.
Any ideas?

**Comment by davidmurdoch** [comment]
Related: https://github.com/trufflesuite/ganache/issues/1169

**Comment by davidmurdoch** [comment]
Thanks for filing the issue, @tjvanderende! We're working on a fix now!

**Comment by davidmurdoch** [comment]
This should now be fixed in our latest beta: https://github.com/trufflesuite/ganache/releases/tag/v2.0.1-beta.0 Let me know if you have any issues or if the fix doesn't work for you.

**Comment by davidmurdoch** [comment]
_Now_ this issue should be fixed in the latest beta! https://github.com/trufflesuite/ganache/releases/tag/v2.0.2-beta.0
