### ISSUE TITLE
System Error when running Ganache 2.0.0 on darwin

### ISSUE THREAD

**Issue by TsaiYee** [trufflesuite/ganache#1204]
PLATFORM: darwin
GANACHE VERSION: 2.0.0

EXCEPTION:
```
TypeError: Cannot read property 'nodes' of undefined
    at getStateVariables (/node_modules/truffle-decoder/dist/allocate/storage.js:146:24)
    at vars.concat.linearizedBaseContractsFromBase.map (/node_modules/truffle-decoder/dist/allocate/storage.js:154:73)
    at Array.map (native)
    at allocateContract (/node_modules/truffle-decoder/dist/allocate/storage.js:154:61)
    at Object.getStorageAllocations (/node_modules/truffle-decoder/dist/allocate/storage.js:28:23)
    at TruffleContractDecoder.init (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:87:43)
    at Object.getDecodedEvent (/src/truffle-integration/decode.js:42:11)
    at process.<anonymous> (/src/truffle-integration/index.js:92:31)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:768:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+44941ms: eth_estimateGas
T+44963ms: eth_getBlockByNumber
T+44984ms: eth_blockNumber
T+45000ms: eth_sendTransaction
T+45022ms:   Transaction: 0x994d2f23896134a67a21bb3aaba50ba9e9d4fefbd8d0df228098d57aa271858d
T+45022ms:   Contract created: 0x8e4f9c87596857bede8e7739bd1f8f3782885953
T+45022ms:   Gas usage: 3604888
T+45038ms:   Block Number: 4
T+45038ms:   Block Time: Tue Apr 02 2019 21:16:09 GMT+0800 (CST)
T+45124ms: eth_getBlockByNumber
T+45124ms: eth_getTransactionReceipt
T+45124ms: eth_getCode
T+45124ms: eth_getTransactionByHash
T+45124ms: eth_getBalance
T+45139ms: eth_getBlockByNumber
T+45162ms: eth_getBlockByNumber
T+45185ms: eth_sendTransaction
T+45202ms:   Transaction: 0x3c945f2cbdbcba458ccffd0fc3dfdd5a383a67c842f70f3b1cbf6a71a5da4379
T+45202ms:   Gas usage: 27034
T+45202ms:   Block Number: 5
T+45224ms:   Block Time: Tue Apr 02 2019 21:16:10 GMT+0800 (CST)
T+45239ms: eth_getBlockByNumber
T+45260ms: eth_getTransactionReceipt
T+177861ms: net_version
T+177861ms: eth_getBlockByNumber
T+177861ms: eth_accounts
T+177911ms: eth_getBlockByNumber
T+177911ms: eth_getBlockByNumber
T+177911ms: eth_getBlockByNumber
T+177911ms: eth_estimateGas
T+177944ms: eth_getBlockByNumber
T+177944ms: eth_blockNumber
T+177972ms: eth_sendTransaction
T+184855ms:   Transaction: 0xc06e7b0c0498be15781f822cb0eff316847cc668dd3dfefe6e7a0997ffc6f438
T+184855ms:   Contract created: 0xdb2d4ae180b2ec3b0dec1c8f75604b572da9c28a
T+184855ms:   Gas usage: 284908
T+184855ms:   Block Number: 6
T+184855ms:   Block Time: Tue Apr 02 2019 21:18:29 GMT+0800 (CST)
T+184855ms: eth_getTransactionReceipt
T+184855ms: eth_getCode
T+184855ms: eth_getTransactionByHash
T+184878ms: eth_getBalance
T+184898ms: eth_getBlockByNumber
T+184921ms: eth_getBlockByNumber
T+184921ms: eth_sendTransaction
T+184921ms:   Transaction: 0xc675d0cfed38621a2068206b9c523b347b4a3fdedbb0c1dbe699ac5c9287ffca
T+184921ms:   Gas usage: 42034
T+184921ms:   Block Number: 7
T+184921ms:   Block Time: Tue Apr 02 2019 21:18:29 GMT+0800 (CST)
T+184921ms: eth_getTransactionReceipt
T+184945ms: eth_getBlockByNumber
T+184960ms: eth_accounts
T+184960ms: eth_getBlockByNumber
T+184960ms: eth_getBlockByNumber
T+184982ms: eth_getBlockByNumber
T+185004ms: eth_getBlockByNumber
T+185020ms: eth_getBlockByNumber
T+185020ms: eth_estimateGas
T+185020ms: eth_getBlockByNumber
T+185020ms: eth_blockNumber
T+185020ms: eth_sendTransaction
T+185043ms:   Transaction: 0x39aa149c04b8472e2e598dfc2a18c8ee27df287053b2714628b681f451067781
T+185043ms:   Contract created: 0x15544fd8ab61846adc941faa2aff63416a25cded
T+185043ms:   Gas usage: 111791
T+185043ms:   Block Number: 8
T+185043ms:   Block Time: Tue Apr 02 2019 21:18:29 GMT+0800 (CST)
T+185043ms: eth_getBlockByNumber
T+185043ms: eth_getTransactionReceipt
T+185043ms: eth_getCode
T+185043ms: eth_getTransactionByHash
T+185043ms: eth_getBalance
T+185043ms: eth_getBlockByNumber
T+185043ms: eth_getBlockByNumber
T+185043ms: eth_getBlockByNumber
T+185043ms: eth_estimateGas
T+185146ms: eth_getBlockByNumber
T+185146ms: eth_blockNumber
T+185146ms: eth_sendTransaction
T+185146ms:   Transaction: 0xeab455ae07380d69a93d204367682b922e5fe50e1113a040db3bfddee7260fb2
T+185146ms:   Contract created: 0xdc3d0eef9f4fbd28d4e889012d764a76574b46d1
T+185146ms:   Gas usage: 3588857
T+185146ms:   Block Number: 9
T+185146ms:   Block Time: Tue Apr 02 2019 21:18:30 GMT+0800 (CST)
T+185146ms: eth_getBlockByNumber
T+185146ms: eth_getTransactionReceipt
T+185146ms: eth_getCode
T+185146ms: eth_getTransactionByHash
T+185146ms: eth_getBalance
T+185146ms: eth_getBlockByNumber
T+185146ms: eth_getBlockByNumber
T+185146ms: eth_sendTransaction
T+185146ms:   Transaction: 0xfa4b5b7168820fe325a7380c5a7d055e285c0c85f2f485be771460da4b694a50
T+185146ms:   Gas usage: 27034
T+185146ms:   Block Number: 10
T+185146ms:   Block Time: Tue Apr 02 2019 21:18:30 GMT+0800 (CST)
T+185146ms: eth_getBlockByNumber
T+185146ms: eth_getTransactionReceipt
T+196387ms: eth_call
T+196465ms: eth_call
T+196490ms: eth_sign
T+196512ms: eth_getTransactionCount
T+196540ms: eth_sendRawTransaction
T+198120ms:   Transaction: 0xbb83d1feaab205b602f76cf12ae690f3973679a018af2a3fe445a01649b64307
T+198120ms:   Gas usage: 54281
T+198120ms:   Block Number: 11
T+198138ms:   Block Time: Tue Apr 02 2019 21:18:48 GMT+0800 (CST)
T+198163ms: eth_getBlockByNumber
T+198267ms: eth_getTransactionReceipt
T+225487ms: eth_unsubscribe
T+225507ms: eth_unsubscribe
T+225535ms: eth_unsubscribe
T+225535ms: eth_unsubscribe
T+225563ms: eth_unsubscribe
```

**Comment by davidmurdoch** [comment]
Related: #1169

**Comment by davidmurdoch** [comment]
This should now be fixed in our latest beta: https://github.com/trufflesuite/ganache/releases/tag/v2.0.1-beta.0 Let me know if you have any issues or if the fix doesn't work for you.

**Comment by davidmurdoch** [comment]
_Now_ this issue should be fixed in the latest beta! :https://github.com/trufflesuite/ganache/releases/tag/v2.0.2-beta.0
