### ISSUE TITLE
System Error when running Ganache 2.0.0 on win32

### ISSUE THREAD

**Issue by NicolasHuchet** [trufflesuite/ganache#1205]
PLATFORM: win32
GANACHE VERSION: 2.0.0

EXCEPTION:
```
Error: 

    at Socket.child.stderr.on.data (C:\Program Files\WindowsApps\Ganache_2.0.0.0_x64__zh355ej5cj694\app\resources\app.asar\src\truffle-integration\projectDetails.js:73:15)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at Socket.Readable.push (_stream_readable.js:197:10)
    at Pipe.onread (net.js:589:20)
```

**Comment by davidmurdoch** [comment]
Thanks for opening this issue, @NicolasHuchet. Do you call `console.error` in your truffle config by any chance?

**Comment by NicolasHuchet** [comment]
I'm afraid that I do not. I'm new to using Ganache and the Trufflesuite so I can't do much more to help you ??

Nicolas HUCHETÉtudiant 3ème année EPITECH Nantes8 rue d'Alger, 44100 Nantes06-16-25-51-26nicolas.huchet@epitech.eu

________________________________

**Comment by davidmurdoch** [comment]
Hm. Do you mind sharing your truffle config file (truffle.js or truffle-config.js) here?

**Comment by davidmurdoch** [comment]
This may now be fixed in our latest beta: https://github.com/trufflesuite/ganache/releases/tag/v2.0.1-beta.0 Let me know if you have any issues or if the fix doesn't work for you.
