### ISSUE TITLE
System Error when running Ganache 2.0.0 on linux

### ISSUE THREAD

**Issue by KwahuNashoba** [trufflesuite/ganache#1206]
Steps to reproduce:
  1. Deploy contract via `truffle deploy` 
  2. Go to Contracts tab
  3. Click on newly deployed contract

PLATFORM: linux
GANACHE VERSION: 2.0.0

EXCEPTION:
```
TypeError: Cannot read property 'nodes' of undefined
    at getStateVariables (/node_modules/truffle-decoder/dist/allocate/storage.js:146:24)
    at vars.concat.linearizedBaseContractsFromBase.map (/node_modules/truffle-decoder/dist/allocate/storage.js:154:73)
    at Array.map (native)
    at allocateContract (/node_modules/truffle-decoder/dist/allocate/storage.js:154:61)
    at Object.getStorageAllocations (/node_modules/truffle-decoder/dist/allocate/storage.js:28:23)
    at TruffleContractDecoder.init (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:87:43)
    at Object.getContractState (/src/truffle-integration/decode.js:18:11)
    at process.<anonymous> (/src/truffle-integration/index.js:76:31)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:768:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: Starting server (version 2.0.0) with initial configuration: {"gasLimit":6721975,"gasPrice":20000000000,"hardfork":"petersburg","hostname":"127.0.0.1","port":7545,"network_id":5777,"default_balance_ether":100,"total_accounts":10,"unlocked_accounts":[],"locked":false,"vmErrorsOnRPCResponse":true,"verbose":false,"db_path":"/home/danilo/.config/Ganache/workspaces/.../chaindata"}
T+264ms: Ganache started successfully!
T+264ms: Waiting for requests...
T+280ms: eth_getCode
T+317ms: eth_subscribe
T+328ms: eth_getLogs
T+346ms: eth_subscribe
T+362ms: eth_getCode
T+7017ms: eth_unsubscribe
T+7033ms: eth_unsubscribe
T+7063ms: eth_unsubscribe
T+7083ms: eth_unsubscribe
```

**Comment by davidmurdoch** [comment]
Related: #1169

**Comment by davidmurdoch** [comment]
This should now be fixed in our latest beta: https://github.com/trufflesuite/ganache/releases/tag/v2.0.1-beta.0 Let me know if you have any issues or if the fix doesn't work for you.

**Comment by KwahuNashoba** [comment]
It works for truffles Migrations.sol contract. But crashes as soon as I try to open any of my contracts with:

`TypeError: Cannot read property 'nodes' of undefined
    at getStateVariables (/node_modules/truffle-decoder/dist/allocate/storage.js:146:24)
    at vars.concat.linearizedBaseContractsFromBase.map (/node_modules/truffle-decoder/dist/allocate/storage.js:154:73)
    at Array.map (native)
    at allocateContract (/node_modules/truffle-decoder/dist/allocate/storage.js:154:61)
    at Object.getStorageAllocations (/node_modules/truffle-decoder/dist/allocate/storage.js:28:23)
    at TruffleContractDecoder.init (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:85:43)
    at Object.getDecodedEvent (/src/truffle-integration/decode.js:42:11)
    at process.<anonymous> (/src/truffle-integration/index.js:92:31)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:768:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)`

**Comment by davidmurdoch** [comment]
_Now_ this issue should be fixed in the latest beta! https://github.com/trufflesuite/ganache/releases/tag/v2.0.2-beta.0
