### ISSUE TITLE
no such file or directory when I select workspace Ganache 2.0.0 on linux

### ISSUE THREAD

**Issue by KwahuNashoba** [trufflesuite/ganache#1214]
Steps to reproduce:
Use case 1:
  1. Put some logic that uses `fs` library in truffle-config.js (I use it to read my mnemonic when deploying to public testnet)
  2. Start Ganache
  3. Select Workspace of that project

Use case 2:
 1. Start Ganache
 2. Select workspace (without additional logic in truffle-config.js)
 3. Edit truffle-config.js to read from file and save it

Guess it's the problem with relative/absolute path

PLATFORM: linux
GANACHE VERSION: 2.0.0

EXCEPTION:
```
Error: fs.js:119
    throw err;
    ^

Error: ENOENT: no such file or directory, open '.secret'
    at Object.openSync (fs.js:448:3)
    at Object.readFileSync (fs.js:348:35)
    at Object.<anonymous> (/home/danilo/_dev/blockchain/sacret-contract/truffle-config.js:25:21)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/tmp/ganache11933-26724-ykd0ll.xv21/index.js:31:18)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:862:12)
    at internal/main/run_main_module.js:21:11

    at Socket.child.stderr.on.data (/src/truffle-integration/projectDetails.js:73:15)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at Socket.Readable.push (_stream_readable.js:197:10)
    at Pipe.onread (net.js:589:20)
```

**Comment by davidmurdoch** [comment]
Hey @KwahuNashoba! Thanks for opening the issue. This should be fixed by https://github.com/trufflesuite/ganache/commit/8b840dba43174d774f50e79be4e1355e6320f2d8 in the next release!
