### ISSUE TITLE
System Error when running Ganache 2.0.0 on darwin

### ISSUE THREAD

**Issue by saidlachhab** [trufflesuite/ganache#1216]
PLATFORM: darwin
GANACHE VERSION: 2.0.0

EXCEPTION:
```
TypeError: Cannot read property 'nodes' of undefined
    at getStateVariables (/node_modules/truffle-decoder/dist/allocate/storage.js:146:24)
    at vars.concat.linearizedBaseContractsFromBase.map (/node_modules/truffle-decoder/dist/allocate/storage.js:154:73)
    at Array.map (native)
    at allocateContract (/node_modules/truffle-decoder/dist/allocate/storage.js:154:61)
    at Object.getStorageAllocations (/node_modules/truffle-decoder/dist/allocate/storage.js:28:23)
    at TruffleContractDecoder.init (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:87:43)
    at Object.getDecodedEvent (/src/truffle-integration/decode.js:42:11)
    at process.<anonymous> (/src/truffle-integration/index.js:92:31)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:768:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+5944788ms: eth_getBlockByNumber
T+5944830ms: eth_getBlockByNumber
T+5945109ms: eth_blockNumber
T+5945787ms: eth_getBlockByNumber
T+5945833ms: eth_getBlockByNumber
T+5946121ms: eth_blockNumber
T+5946790ms: eth_getBlockByNumber
T+5946832ms: eth_getBlockByNumber
T+5947131ms: eth_blockNumber
T+5947791ms: eth_getBlockByNumber
T+5947836ms: eth_getBlockByNumber
T+5948184ms: eth_blockNumber
T+5948789ms: eth_getBlockByNumber
T+5948823ms: eth_getBlockByNumber
T+5949152ms: eth_blockNumber
T+5949793ms: eth_getBlockByNumber
T+5949837ms: eth_getBlockByNumber
T+5950165ms: eth_blockNumber
T+5950787ms: eth_getBlockByNumber
T+5950830ms: eth_getBlockByNumber
T+5951178ms: eth_blockNumber
T+5951787ms: eth_getBlockByNumber
T+5951821ms: eth_getBlockByNumber
T+5952192ms: eth_blockNumber
T+5952792ms: eth_getBlockByNumber
T+5952841ms: eth_getBlockByNumber
T+5953202ms: eth_blockNumber
T+5953793ms: eth_getBlockByNumber
T+5953836ms: eth_getBlockByNumber
T+5954215ms: eth_blockNumber
T+5954791ms: eth_getBlockByNumber
T+5954837ms: eth_getBlockByNumber
T+5955226ms: eth_blockNumber
T+5955793ms: eth_getBlockByNumber
T+5955839ms: eth_getBlockByNumber
T+5956236ms: eth_blockNumber
T+5956787ms: eth_getBlockByNumber
T+5956829ms: eth_getBlockByNumber
T+5957245ms: eth_blockNumber
T+5957789ms: eth_getBlockByNumber
T+5957840ms: eth_getBlockByNumber
T+5958258ms: eth_blockNumber
T+5958793ms: eth_getBlockByNumber
T+5958837ms: eth_getBlockByNumber
T+5959267ms: eth_blockNumber
T+5959791ms: eth_getBlockByNumber
T+5959835ms: eth_getBlockByNumber
T+5960279ms: eth_blockNumber
T+5960791ms: eth_getBlockByNumber
T+5960834ms: eth_getBlockByNumber
T+5961292ms: eth_blockNumber
T+5961791ms: eth_getBlockByNumber
T+5961825ms: eth_getBlockByNumber
T+5962303ms: eth_blockNumber
T+5962791ms: eth_getBlockByNumber
T+5962835ms: eth_getBlockByNumber
T+5963313ms: eth_blockNumber
T+5963791ms: eth_getBlockByNumber
T+5963834ms: eth_getBlockByNumber
T+5964327ms: eth_blockNumber
T+5964791ms: eth_getBlockByNumber
T+5964835ms: eth_getBlockByNumber
T+5965336ms: eth_blockNumber
T+5965791ms: eth_getBlockByNumber
T+5965834ms: eth_getBlockByNumber
T+5966349ms: eth_blockNumber
T+5966792ms: eth_getBlockByNumber
T+5966833ms: eth_getBlockByNumber
T+5967358ms: eth_blockNumber
T+5967791ms: eth_getBlockByNumber
T+5967827ms: eth_getBlockByNumber
T+5968371ms: eth_blockNumber
T+5968791ms: eth_getBlockByNumber
T+5968836ms: eth_getBlockByNumber
T+5969380ms: eth_blockNumber
T+5969789ms: eth_getBlockByNumber
T+5969833ms: eth_getBlockByNumber
T+5970392ms: eth_blockNumber
T+5970787ms: eth_getBlockByNumber
T+5970830ms: eth_getBlockByNumber
T+5971402ms: eth_blockNumber
T+5971787ms: eth_getBlockByNumber
T+5971832ms: eth_getBlockByNumber
T+5972415ms: eth_blockNumber
T+5972787ms: eth_getBlockByNumber
T+5972830ms: eth_getBlockByNumber
T+5973425ms: eth_blockNumber
T+5973793ms: eth_getBlockByNumber
T+5973828ms: eth_getBlockByNumber
T+5974436ms: eth_blockNumber
T+5974787ms: eth_getBlockByNumber
T+5974832ms: eth_getBlockByNumber
T+5975446ms: eth_blockNumber
T+5975789ms: eth_getBlockByNumber
T+5975832ms: eth_getBlockByNumber
T+5976458ms: eth_blockNumber
T+5976789ms: eth_getBlockByNumber
T+5976835ms: eth_getBlockByNumber
T+5977468ms: eth_blockNumber
T+5977790ms: eth_getBlockByNumber
T+5977849ms: eth_getBlockByNumber
T+5978481ms: eth_blockNumber
T+5978790ms: eth_getBlockByNumber
T+5978837ms: eth_getBlockByNumber
T+5979490ms: eth_blockNumber
T+5979787ms: eth_getBlockByNumber
T+5979824ms: eth_getBlockByNumber
T+5980500ms: eth_blockNumber
T+5980787ms: eth_getBlockByNumber
T+5980827ms: eth_getBlockByNumber
T+5981511ms: eth_blockNumber
T+5981865ms: eth_getBlockByNumber
T+5981920ms: eth_getBlockByNumber
T+5982657ms: eth_blockNumber
T+5982863ms: eth_getBlockByNumber
T+5982910ms: eth_getBlockByNumber
T+5983628ms: eth_blockNumber
T+5983937ms: eth_getBlockByNumber
T+5983937ms: eth_getBlockByNumber
T+5984677ms: eth_blockNumber
T+5984867ms: eth_getBlockByNumber
T+5984911ms: eth_getBlockByNumber
T+5985632ms: eth_blockNumber
T+5985896ms: eth_getBlockByNumber
T+5985943ms: eth_getBlockByNumber
T+5986560ms: eth_blockNumber
T+5986791ms: eth_getBlockByNumber
T+5986830ms: eth_getBlockByNumber
T+5987571ms: eth_blockNumber
T+5987792ms: eth_getBlockByNumber
T+5987828ms: eth_getBlockByNumber
T+5988584ms: eth_blockNumber
T+5988796ms: eth_getBlockByNumber
T+5988832ms: eth_getBlockByNumber
T+5989595ms: eth_blockNumber
T+5989791ms: eth_getBlockByNumber
T+5989827ms: eth_getBlockByNumber
T+5990679ms: eth_blockNumber
T+5990891ms: eth_getBlockByNumber
T+5990926ms: eth_getBlockByNumber
T+5991731ms: eth_unsubscribe
T+5991778ms: eth_unsubscribe
T+5991832ms: eth_unsubscribe
T+5991832ms: eth_unsubscribe
T+5991832ms: eth_unsubscribe
```

**Comment by davidmurdoch** [comment]
Thank you, @saidlachhab for opening the issue! This should be fixed in the next release, after https://github.com/trufflesuite/ganache/pull/1209 is merged in!

**Comment by davidmurdoch** [comment]
This should now be fixed in our latest beta: https://github.com/trufflesuite/ganache/releases/tag/v2.0.1-beta.0 Let me know if you have any issues or if the fix doesn't work for you.
