### ISSUE TITLE
System Error when running Ganache 2.0.0 on win32

### ISSUE THREAD

**Issue by developerhub0** [trufflesuite/ganache#1218]
PLATFORM: win32
GANACHE VERSION: 2.0.0

EXCEPTION:
```
TypeError: Cannot read property 'nodes' of undefined
    at getStateVariables (C:\Users\***\AppData\Local\Programs\Ganache\resources\app.asar\node_modules\truffle-decoder\dist\allocate\storage.js:146:24)
    at vars.concat.linearizedBaseContractsFromBase.map (C:\Users\***\AppData\Local\Programs\Ganache\resources\app.asar\node_modules\truffle-decoder\dist\allocate\storage.js:154:73)
    at Array.map (native)
    at allocateContract (C:\Users\***\AppData\Local\Programs\Ganache\resources\app.asar\node_modules\truffle-decoder\dist\allocate\storage.js:154:61)
    at Object.getStorageAllocations (C:\Users\***\AppData\Local\Programs\Ganache\resources\app.asar\node_modules\truffle-decoder\dist\allocate\storage.js:28:23)
    at TruffleContractDecoder.init (C:\Users\***\AppData\Local\Programs\Ganache\resources\app.asar\node_modules\truffle-decoder\dist\interface\contract-decoder.js:87:43)
    at Object.getDecodedEvent (C:\Users\***\AppData\Local\Programs\Ganache\resources\app.asar\src\truffle-integration\decode.js:42:11)
    at process.<anonymous> (C:\Users\***\AppData\Local\Programs\Ganache\resources\app.asar\src\truffle-integration\index.js:92:31)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:768:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+5040033ms: eth_blockNumber
T+5040592ms: net_version
T+5041015ms: eth_blockNumber
T+5042048ms: eth_blockNumber
T+5042265ms: net_version
T+5043079ms: eth_blockNumber
T+5044122ms: eth_blockNumber
T+5045140ms: eth_blockNumber
T+5046180ms: eth_blockNumber
T+5047210ms: eth_blockNumber
T+5048250ms: eth_blockNumber
T+5048380ms: net_version
T+5048405ms: eth_getBlockByNumber
T+5049280ms: eth_blockNumber
T+5050320ms: eth_blockNumber
T+5051375ms: eth_blockNumber
T+5052390ms: eth_blockNumber
T+5053430ms: eth_blockNumber
T+5054475ms: eth_blockNumber
T+5054514ms: net_version
T+5055510ms: eth_blockNumber
T+5056550ms: eth_blockNumber
T+5057639ms: eth_blockNumber
T+5058673ms: eth_blockNumber
T+5059575ms: net_version
T+5059686ms: eth_blockNumber
T+5060714ms: eth_blockNumber
T+5061775ms: eth_blockNumber
T+5062823ms: eth_blockNumber
T+5063614ms: eth_getBlockByNumber
T+5063883ms: eth_blockNumber
T+5064906ms: eth_blockNumber
T+5065661ms: net_version
T+5065939ms: eth_blockNumber
T+5068028ms: eth_blockNumber
T+5069371ms: eth_blockNumber
T+5070273ms: net_version
T+5070405ms: eth_blockNumber
T+5071424ms: eth_blockNumber
T+5072457ms: eth_blockNumber
T+5073498ms: eth_blockNumber
T+5073845ms: net_version
T+5074517ms: eth_blockNumber
T+5075552ms: eth_blockNumber
T+5076572ms: eth_blockNumber
T+5077613ms: eth_blockNumber
T+5078648ms: eth_blockNumber
T+5078933ms: eth_getBlockByNumber
T+5078964ms: net_version
T+5079690ms: eth_blockNumber
T+5080724ms: eth_blockNumber
T+5081743ms: eth_blockNumber
T+5082778ms: eth_blockNumber
T+5083820ms: eth_blockNumber
T+5084839ms: eth_blockNumber
T+5085071ms: net_version
T+5085874ms: eth_blockNumber
T+5086909ms: eth_blockNumber
T+5087935ms: eth_blockNumber
T+5088971ms: eth_blockNumber
T+5090004ms: eth_blockNumber
T+5091042ms: eth_blockNumber
T+5092062ms: eth_blockNumber
T+5093098ms: eth_blockNumber
T+5093870ms: net_version
T+5094133ms: eth_blockNumber
T+5095152ms: eth_blockNumber
T+5096194ms: eth_blockNumber
T+5096928ms: eth_getBlockByNumber
T+5097229ms: eth_blockNumber
T+5098271ms: eth_blockNumber
T+5099290ms: eth_blockNumber
T+5100322ms: eth_blockNumber
T+5101350ms: eth_blockNumber
T+5102029ms: net_version
T+5102361ms: eth_blockNumber
T+5103403ms: eth_blockNumber
T+5104438ms: eth_blockNumber
T+5105472ms: eth_blockNumber
T+5106514ms: eth_blockNumber
T+5107548ms: eth_blockNumber
T+5108583ms: eth_blockNumber
T+5109623ms: eth_blockNumber
T+5110110ms: net_version
T+5110644ms: eth_blockNumber
T+5111678ms: eth_blockNumber
T+5112697ms: eth_blockNumber
T+5113153ms: eth_getBlockByNumber
T+5113738ms: eth_blockNumber
T+5114773ms: eth_blockNumber
T+5115792ms: eth_blockNumber
T+5116833ms: eth_blockNumber
T+5117249ms: net_version
T+5117852ms: eth_blockNumber
T+5118864ms: eth_blockNumber
T+5119876ms: eth_blockNumber
T+5120903ms: eth_blockNumber
T+5121930ms: eth_blockNumber
T+5122971ms: eth_blockNumber
T+5124004ms: eth_blockNumber
T+5125063ms: eth_blockNumber
T+5125363ms: net_version
T+5126093ms: eth_blockNumber
T+5127123ms: eth_blockNumber
T+5128153ms: eth_blockNumber
T+5129193ms: eth_blockNumber
T+5129433ms: eth_getBlockByNumber
T+5130223ms: eth_blockNumber
T+5131278ms: eth_blockNumber
T+5132283ms: eth_blockNumber
T+5133313ms: eth_blockNumber
T+5133533ms: net_version
T+5134348ms: eth_blockNumber
T+5135363ms: eth_blockNumber
T+5136408ms: eth_blockNumber
T+5137443ms: eth_blockNumber
T+5138463ms: eth_blockNumber
T+5139493ms: eth_blockNumber
T+5139643ms: net_version
T+5140528ms: eth_blockNumber
T+5141563ms: eth_blockNumber
T+5142603ms: eth_blockNumber
T+5143673ms: eth_blockNumber
T+5144693ms: eth_blockNumber
T+5145728ms: eth_blockNumber
T+5146743ms: eth_blockNumber
T+5147258ms: eth_getBlockByNumber
T+5147363ms: net_version
T+5147778ms: eth_blockNumber
T+5148813ms: eth_blockNumber
T+5149823ms: eth_blockNumber
T+5150863ms: eth_blockNumber
T+5151890ms: eth_blockNumber
T+5152291ms: net_version
T+5152924ms: eth_blockNumber
T+5153948ms: eth_blockNumber
T+5154968ms: eth_blockNumber
T+5155995ms: eth_blockNumber
T+5157006ms: eth_blockNumber
T+5158035ms: eth_blockNumber
T+5158146ms: eth_unsubscribe
T+5158172ms: eth_unsubscribe
T+5158192ms: eth_unsubscribe
```

**Comment by davidmurdoch** [comment]
This should now be fixed in our latest beta: https://github.com/trufflesuite/ganache/releases/tag/v2.0.1-beta.0 Let me know if you have any issues or if the fix doesn't work for you.
