### ISSUE TITLE
System Error when switching to events tab while running Ganache 2.0.0 on win32

### ISSUE THREAD

**Issue by dulcedu** [trufflesuite/ganache#1228]
# Steps to Reproduce
Switch to the Events tab and BOOOM!

PLATFORM: win32
GANACHE VERSION: 2.0.0

EXCEPTION:
```
TypeError: Cannot read property 'nodes' of undefined
    at getStateVariables (C:\Program Files\Ganache\resources\app.asar\node_modules\truffle-decoder\dist\allocate\storage.js:146:24)
    at vars.concat.linearizedBaseContractsFromBase.map (C:\Program Files\Ganache\resources\app.asar\node_modules\truffle-decoder\dist\allocate\storage.js:154:73)
    at Array.map (native)
    at allocateContract (C:\Program Files\Ganache\resources\app.asar\node_modules\truffle-decoder\dist\allocate\storage.js:154:61)
    at Object.getStorageAllocations (C:\Program Files\Ganache\resources\app.asar\node_modules\truffle-decoder\dist\allocate\storage.js:28:23)
    at TruffleContractDecoder.init (C:\Program Files\Ganache\resources\app.asar\node_modules\truffle-decoder\dist\interface\contract-decoder.js:87:43)
    at Object.getDecodedEvent (C:\Program Files\Ganache\resources\app.asar\src\truffle-integration\decode.js:42:11)
    at process.<anonymous> (C:\Program Files\Ganache\resources\app.asar\src\truffle-integration\index.js:92:31)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:768:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: eth_unsubscribe
T+0ms: eth_unsubscribe
T+321ms: eth_unsubscribe
T+321ms: eth_unsubscribe
T+3887ms: Starting server (version 2.0.0) with initial configuration: {"gasLimit":6721975,"gasPrice":20000000000,"hardfork":"petersburg","hostname":"127.0.0.1","port":7545,"network_id":5777,"default_balance_ether":100,"total_accounts":10,"unlocked_accounts":[],"locked":false,"vmErrorsOnRPCResponse":true,"verbose":false,"db_path":"C:\\Users\\carlo\\AppData\\Roaming\\Ganache\\workspaces\\Collectable-Cards\\chaindata"}
T+4300ms: Ganache started successfully!
T+4300ms: Waiting for requests...
T+4336ms: eth_getCode
T+4392ms: eth_subscribe
T+4426ms: eth_getLogs
T+4457ms: eth_subscribe
T+4482ms: eth_getCode
T+4512ms: eth_getCode
T+4535ms: eth_getCode
T+66489ms: net_version
T+66565ms: eth_accounts
T+67432ms: eth_getBlockByNumber
T+67432ms: eth_accounts
T+67432ms: eth_getBlockByNumber
T+67432ms: net_version
T+67432ms: eth_getBlockByNumber
T+67432ms: eth_getBlockByNumber
T+67432ms: net_version
T+67432ms: eth_estimateGas
T+67995ms: eth_getBlockByNumber
T+67995ms: eth_blockNumber
T+67995ms: net_version
T+67995ms: eth_sendTransaction
T+76997ms:   Transaction: 0x29c86178290b90b50e9c181c468882b1af227df6b6a47c3f156864f77da9c343
T+76997ms:   Contract created: 0xab3ae87f8602b3c68feb110a92378fb842e42ee6
T+76997ms:   Gas usage: 284908
T+76997ms:   Block Number: 1
T+76997ms:   Block Time: Mon Apr 08 2019 14:23:26 GMT-0500 (Central Daylight Time (Mexico))
T+76997ms: eth_getTransactionReceipt
T+76997ms: eth_getCode
T+76997ms: eth_getTransactionByHash
T+76997ms: eth_getBalance
T+77274ms: eth_getBlockByNumber
T+77274ms: eth_getBlockByNumber
T+77274ms: eth_accounts
T+77274ms: eth_getBlockByNumber
T+77274ms: eth_getBlockByNumber
T+77274ms: eth_getBlockByNumber
T+77274ms: eth_estimateGas
T+77661ms: eth_getBlockByNumber
T+77661ms: eth_blockNumber
T+77661ms: eth_sendTransaction
T+77857ms:   Transaction: 0xafbcd2fe925f6c14d6c79cdfb5b74c177f3fa7930bd65774e9c45500ed088749
T+77857ms:   Contract created: 0x2c1e8379ff0607c12983e201adf88fb858f40b6d
T+77857ms:   Gas usage: 2028670
T+77857ms:   Block Number: 2
T+77857ms:   Block Time: Mon Apr 08 2019 14:23:27 GMT-0500 (Central Daylight Time (Mexico))
T+77857ms: eth_getTransactionReceipt
T+77857ms: eth_getCode
T+78057ms: eth_getTransactionByHash
T+78057ms: eth_getBalance
T+78057ms: eth_getBlockByNumber
T+78057ms: eth_getBlockByNumber
T+78057ms: eth_sendTransaction
T+78259ms:   Transaction: 0x504e344de9a75b88d18afeea5de0cd243e75c2970ca72189c20b1899d7347be3
T+78259ms:   Gas usage: 172269
T+78259ms:   Block Number: 3
T+78259ms:   Block Time: Mon Apr 08 2019 14:23:28 GMT-0500 (Central Daylight Time (Mexico))
T+78472ms: eth_getBlockByNumber
T+79820ms: eth_getBlockByNumber
T+418078ms: eth_unsubscribe
T+418124ms: eth_unsubscribe
T+418202ms: eth_unsubscribe
T+418276ms: eth_unsubscribe
```

**Comment by davidmurdoch** [comment]
This should now be fixed in our latest beta: https://github.com/trufflesuite/ganache/releases/tag/v2.0.1-beta.0 Let me know if you have an issues or if the fix doesn't work for you.
