### ISSUE TITLE
System Error when opening Events on Ganache 2.0.1-beta.0 on linux

### ISSUE THREAD

**Issue by KwahuNashoba** [trufflesuite/ganache#1240]
Steps to reproduce:
  1. Open Ganache
  2. Click on Events tab

P.S. Sorry if I hit duplicate, all the issues are the same, very few people really explain what was the problem.

PLATFORM: linux (Manjaro)
GANACHE VERSION: 2.0.1-beta.0

EXCEPTION:
```
TypeError: Cannot read property 'nodes' of undefined
    at getStateVariables (/node_modules/truffle-decoder/dist/allocate/storage.js:146:24)
    at vars.concat.linearizedBaseContractsFromBase.map (/node_modules/truffle-decoder/dist/allocate/storage.js:154:73)
    at Array.map (native)
    at allocateContract (/node_modules/truffle-decoder/dist/allocate/storage.js:154:61)
    at Object.getStorageAllocations (/node_modules/truffle-decoder/dist/allocate/storage.js:28:23)
    at TruffleContractDecoder.init (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:85:43)
    at Object.getDecodedEvent (/src/truffle-integration/decode.js:42:11)
    at process.<anonymous> (/src/truffle-integration/index.js:92:31)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:768:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: Starting server (version 2.0.1-beta.0) with initial configuration: {"gasLimit":6721975,"gasPrice":20000000000,"hardfork":"petersburg","hostname":"127.0.0.1","port":7545,"network_id":5777,"default_balance_ether":100,"total_accounts":10,"unlocked_accounts":[],"locked":false,"vmErrorsOnRPCResponse":true,"verbose":false,"db_path":"/home/danilo/.config/Ganache/workspaces/Secret-Life/chaindata"}
T+222ms: Ganache started successfully!
T+222ms: Waiting for requests...
T+249ms: eth_getCode
T+274ms: eth_subscribe
T+292ms: eth_getLogs
T+314ms: eth_subscribe
T+336ms: eth_getCode
T+358ms: eth_getCode
T+372ms: eth_getCode
T+99540ms: eth_unsubscribe
T+99558ms: eth_unsubscribe
T+99580ms: eth_unsubscribe
T+99580ms: eth_unsubscribe
T+99608ms: eth_unsubscribe
```

**Comment by davidmurdoch** [comment]
Related to https://github.com/trufflesuite/ganache/issues/1169

**Comment by haltman-at** [comment]
Hi!  Do you by any chance have an example project we could reproduce this with?  Thank you!

**Comment by haltman-at** [comment]
So, we're currently looking into the problem, but I wanted to suggest a workaround until such time as we have a fix.  Would you mind trying this and letting us know if it works?  Try recompling your Truffle project with `truffle compile --all`, or, if necessary, recompiling and redeploying the whole thing with `truffle migrate --compile-all --reset`.

See if that fixes the problem for now; let us know if it works.  Meanwhile, we are, as I said, looking into a more proper fix.  Thank you!

**Comment by davidmurdoch** [comment]
This issue should be fixed in the latest beta! https://github.com/trufflesuite/ganache/releases/tag/v2.0.2-beta.0

**Comment by KwahuNashoba** [comment]
Hey, really sorry for being inactive. Was traveling a bit :)

v2.0.2-beta.0 does not crash now when I open events so I guess this issue is resolved. However, if I click on any event, It shows event details for a very brief period and then the whole app goes blank white so I have to restart it. Should I report another issue for this?
