### ISSUE TITLE
System Error when running Ganache 2.0.0 on darwin

### ISSUE THREAD

**Issue by sarathsp06** [trufflesuite/ganache#1243]
PLATFORM: darwin
GANACHE VERSION: 2.0.0

EXCEPTION:
```
Error: nonce generation function failed or private key is invalid
    at Object.exports.ecsign (/node_modules/ganache-core/node_modules/ethereumjs-util/dist/index.js:369:23)
    at Transaction.sign (/node_modules/ganache-core/node_modules/ethereumjs-tx/es5/index.js:252:23)
    at Transaction.sign (/node_modules/ganache-core/lib/utils/transaction.js:270:10)
    at Transaction.hash (/node_modules/ganache-core/node_modules/ethereumjs-tx/fake.js:66:12)
    at Transaction.fakeHash [as hash] (/node_modules/ganache-core/lib/utils/transaction.js:17:51)
    at RuntimeError.combine (/node_modules/ganache-core/lib/utils/runtimeerror.js:42:30)
    at new RuntimeError (/node_modules/ganache-core/lib/utils/runtimeerror.js:19:8)
    at Function.RuntimeError.fromResults (/node_modules/ganache-core/lib/utils/runtimeerror.js:89:13)
    at /node_modules/ganache-core/lib/blockchain_double.js:519:30
    at /node_modules/ganache-core/node_modules/ethereumjs-vm/dist/runTx.js:70:9
    at /node_modules/ganache-core/node_modules/async/dist/async.js:969:16
    at next (/node_modules/ganache-core/node_modules/async/dist/async.js:5225:18)
    at /node_modules/ganache-core/node_modules/ethereumjs-vm/dist/cache.js:160:13
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/util.js:51:36
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:52:16
    at done (/node_modules/ganache-core/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:246:17)
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:44:16
    at /node_modules/ganache-core/lib/database/levelupobjectadapter.js:110:7
    at /node_modules/ganache-core/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/node_modules/ganache-core/node_modules/async/dist/async.js:1064:13)
    at /node_modules/ganache-core/node_modules/async/dist/async.js:969:16
    at /node_modules/ganache-core/node_modules/level-sublevel/shell.js:53:51
```

APPLICATION LOG:
```
T+0ms: Warning: stopMining called when miner was already stopped
T+0ms: Starting server (version 2.0.0) with initial configuration: {"gasLimit":6721975,"gasPrice":20000000000,"hardfork":"petersburg","hostname":"127.0.0.1","port":7545,"network_id":5777,"default_balance_ether":100,"total_accounts":10,"unlocked_accounts":[],"locked":false,"vmErrorsOnRPCResponse":true,"verbose":false}
T+50ms: Ganache started successfully!
T+50ms: Waiting for requests...
T+60ms: eth_subscribe
T+61ms: eth_getLogs
T+62ms: eth_subscribe
T+17531ms: eth_getTransactionCount
T+17533ms: eth_gasPrice
T+17536ms: eth_estimateGas
T+17549ms: eth_sendRawTransaction
T+24723ms: eth_getTransactionCount
T+24725ms: eth_gasPrice
T+24727ms: eth_estimateGas
T+24741ms: eth_sendRawTransaction
T+24807ms:   Transaction: 0xcdbafd5b84d7a8d1453dbcf39f4d82424d315a904fb506a16e46c5d73411bf90
T+24807ms:   Contract created: 0x0ca0e3057f0b0d43aeef61d2b94ddfbd11f7ca51
T+24807ms:   Gas usage: 591934
T+24807ms:   Block Number: 1
T+24807ms:   Block Time: Fri Apr 12 2019 23:40:46 GMT+0200 (CEST)
T+24808ms: eth_getBlockByNumber
T+26762ms: eth_getTransactionCount
T+26765ms: eth_gasPrice
T+26767ms: eth_getCode
T+26771ms: eth_estimateGas
T+26803ms: eth_sendRawTransaction
T+26855ms:   Transaction: 0x482bbedd18564efbd918430b515015ea8fe3b8bec8eef8e3e5b45b9acd30278b
T+26855ms:   Gas usage: 154383
T+26855ms:   Block Number: 2
T+26855ms:   Block Time: Fri Apr 12 2019 23:40:48 GMT+0200 (CEST)
T+26856ms: eth_getBlockByNumber
T+26856ms: eth_call
T+26859ms: eth_unsubscribe
T+26859ms: eth_unsubscribe
T+26860ms: eth_unsubscribe
T+26860ms: eth_unsubscribe
T+26861ms: eth_unsubscribe
```

**Comment by davidmurdoch** [comment]
Thanks for opening the issue, @sarathsp06. Can you try our newest release, [v2.0.1](https://github.com/trufflesuite/ganache/releases/tag/v2.0.1) and let me know if this fixes the issue here?

If not, can you provide more information about the last few calls/transactions in the log?

**Comment by sarathsp06** [comment]
Sure , one scenario that crashed `ganache` always` was passing an invalid index to an array.

**Comment by davidmurdoch** [comment]
@sarathsp06 Is passing an invalid index to an array what caused the above issue? If not, could you open a new issue for that?

**Comment by sarathsp06** [comment]
@davidmurdoch  don't remember that, have seen issues couple of times with v2.0.0. Will update next time I get a crash report , was at a hackathon trying out ethereum

**Comment by sarathsp06** [comment]
@davidmurdoch  don't remember that, have seen issues couple of times with v2.0.0. Will update next time I get a crash report, was at a hackathon trying out ethereum
