### ISSUE TITLE
System Error when running Ganache 2.0.0 on win32

### ISSUE THREAD

**Issue by seanjohnson1** [trufflesuite/ganache#1245]
PLATFORM: win32
GANACHE VERSION: 2.0.0

EXCEPTION:
```
Error: watch C:\Users\Aiden\truffle-config.js ENOENT
    at exports._errnoException (util.js:1024:11)
    at FSWatcher.start (fs.js:1394:19)
    at Object.fs.watch (fs.js:1420:11)
    at ProjectFsWatcher.start (C:\Program Files\WindowsApps\Ganache_2.0.0.0_x64__zh355ej5cj694\app\resources\app.asar\src\truffle-integration\projectFsWatcher.js:40:29)
    at new ProjectFsWatcher (C:\Program Files\WindowsApps\Ganache_2.0.0.0_x64__zh355ej5cj694\app\resources\app.asar\src\truffle-integration\projectFsWatcher.js:25:10)
    at ProjectsWatcher.add (C:\Program Files\WindowsApps\Ganache_2.0.0.0_x64__zh355ej5cj694\app\resources\app.asar\src\truffle-integration\projectsWatcher.js:130:23)
    at process.<anonymous> (C:\Program Files\WindowsApps\Ganache_2.0.0.0_x64__zh355ej5cj694\app\resources\app.asar\src\truffle-integration\index.js:59:34)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by TeNNoX** [comment]
Does the file `C:\Users\Aiden\truffle-config.js` exist?

**Comment by davidmurdoch** [comment]
Closing due to no response.
