### ISSUE TITLE
System Error when running Ganache 2.0.1-beta.0 on linux

### ISSUE THREAD

**Issue by TeNNoX** [trufflesuite/ganache#1247]
I used 2.0.0 without problems yesterday. Today (I deleted the AppImage file by accident, so I re-downloaded) it shows this exception (both 2.0.0 and 2.0.1-beta.0):

EXCEPTION:
```
Error: watch /home/manu/dev/odyssey/dapp/truffle.js ENOSPC
    at exports._errnoException (util.js:1024:11)
    at FSWatcher.start (fs.js:1394:19)
    at Object.fs.watch (fs.js:1420:11)
    at ProjectFsWatcher.start (/src/truffle-integration/projectFsWatcher.js:40:29)
    at new ProjectFsWatcher (/src/truffle-integration/projectFsWatcher.js:25:10)
    at ProjectsWatcher.add (/src/truffle-integration/projectsWatcher.js:130:23)
    at process.<anonymous> (/src/truffle-integration/index.js:59:34)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

This only happens after adding the truffle config to projects and then restarting (or when selecting it from the beginning).

I also tried clearing the `~/.config/Ganache` folder - problem persists.
**ENOSPC** suggests there is no space left on my device, but that is not the case.

```
$ ll /home/manu/dev/odyssey/dapp/truffle.js
-rwxr-xr-x 1 manu manu 763 Apr 13 10:48 /home/manu/dev/odyssey/dapp/truffle.js*
```

PLATFORM: linux
GANACHE VERSION: 2.0.1-beta.0

**Comment by davidmurdoch** [comment]
Related to https://github.com/trufflesuite/ganache/issues/1075.

Can you try the following and let me know if it fixes the issue for you?:

```
Run the below command to avoid ENOSPC:

    $ echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

For Arch Linux add this line to /etc/sysctl.d/99-sysctl.conf:

    $ fs.inotify.max_user_watches=524288

Then execute:

    $ sysctl --system

This will also persist across reboots.
```

**Comment by TeNNoX** [comment]
Sorry, I don't have Ganache installed anymore.
