### ISSUE TITLE
System Error when running Ganache 2.0.1-beta.0 on darwin

### ISSUE THREAD

**Issue by minhyeok4dev** [trufflesuite/ganache#1248]
Unfortunately, The error has not been fixed :(
I just set a new workspace importing my truffle project and typed `truffle migrate --reset`

PLATFORM: darwin
GANACHE VERSION: 2.0.1-beta.0

EXCEPTION:
```
TypeError: Cannot read property 'nodes' of undefined
    at getStateVariables (/node_modules/truffle-decoder/dist/allocate/storage.js:146:24)
    at vars.concat.linearizedBaseContractsFromBase.map (/node_modules/truffle-decoder/dist/allocate/storage.js:154:73)
    at Array.map (native)
    at allocateContract (/node_modules/truffle-decoder/dist/allocate/storage.js:154:61)
    at Object.getStorageAllocations (/node_modules/truffle-decoder/dist/allocate/storage.js:28:23)
    at TruffleContractDecoder.init (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:87:43)
    at Object.getDecodedEvent (/src/truffle-integration/decode.js:42:11)
    at process.<anonymous> (/src/truffle-integration/index.js:92:31)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:768:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: eth_unsubscribe
T+0ms: eth_unsubscribe
T+6ms: eth_unsubscribe
T+6ms: eth_unsubscribe
T+213ms: Starting server (version 2.0.1-beta.0) with initial configuration: {"gasLimit":6721975,"gasPrice":20000000000,"hardfork":"petersburg","db_path":"/Users/minhyeok4dev/Library/Application Support/Ganache/workspaces/vast-book/chaindata","default_balance_ether":100,"hostname":"127.0.0.1","locked":false,"network_id":5777,"port":7545,"total_accounts":10,"unlocked_accounts":[],"verbose":false,"vmErrorsOnRPCResponse":true}
T+299ms: Ganache started successfully!
T+299ms: Waiting for requests...
T+306ms: eth_getCode
T+313ms: eth_subscribe
T+313ms: eth_getLogs
T+323ms: eth_subscribe
T+329ms: eth_getCode
T+336ms: eth_getCode
T+8577ms: net_version
T+8587ms: eth_accounts
T+8601ms: eth_getBlockByNumber
T+8614ms: eth_accounts
T+8623ms: eth_getBlockByNumber
T+8639ms: eth_getBlockByNumber
T+8647ms: eth_getBlockByNumber
T+8658ms: eth_estimateGas
T+8674ms: eth_getBlockByNumber
T+8684ms: eth_blockNumber
T+8704ms: eth_sendTransaction
T+12329ms:   Transaction: 0x13c3647ed431bc24b08c6b229485b3fb0f518603a877cdcea8d845c62741c44e
T+12329ms:   Contract created: 0xdc03466f56916b0540725e23bff8365688301ffb
T+12343ms:   Gas usage: 273162
T+12343ms:   Block Number: 1
T+12343ms:   Block Time: Sat Apr 13 2019 23:30:30 GMT+0900 (KST)
T+12351ms: eth_getBlockByNumber
T+12360ms: eth_getTransactionReceipt
T+12374ms: eth_getCode
T+12384ms: eth_getTransactionByHash
T+12400ms: eth_getBlockByNumber
T+12408ms: eth_getBalance
T+12417ms: eth_getBlockByNumber
T+12431ms: eth_getBlockByNumber
T+12443ms: eth_sendTransaction
T+12459ms:   Transaction: 0xcff0b83aaa3c0ef837714a344efeb9810cecaa1ccd6cb0c04c14b0499463274f
T+12459ms:   Gas usage: 42028
T+12459ms:   Block Number: 2
T+12468ms:   Block Time: Sat Apr 13 2019 23:30:30 GMT+0900 (KST)
T+12483ms: eth_getBlockByNumber
T+12491ms: eth_getTransactionReceipt
T+12500ms: eth_getBlockByNumber
T+12515ms: eth_accounts
T+12525ms: eth_getBlockByNumber
T+12541ms: eth_getBlockByNumber
T+12550ms: eth_getBlockByNumber
T+12599ms: eth_estimateGas
T+12644ms: eth_getBlockByNumber
T+12644ms: eth_blockNumber
T+12644ms: eth_sendTransaction
T+12658ms:   Transaction: 0x77457fe7bc43e67643a4dc031093202f27a8be0f2dd42c36dd8c3a9ad2e84440
T+12658ms:   Contract created: 0x8ab43f2e5610288a8b44815a921cfa4b30985c00
T+12658ms:   Gas usage: 1516857
T+12658ms:   Block Number: 3
T+12658ms:   Block Time: Sat Apr 13 2019 23:30:31 GMT+0900 (KST)
T+12681ms: eth_getBlockByNumber
T+12681ms: eth_getTransactionReceipt
T+12681ms: eth_getCode
T+12681ms: eth_getTransactionByHash
T+12681ms: eth_getBlockByNumber
T+12689ms: eth_getBalance
T+12710ms: eth_getBlockByNumber
T+12718ms: eth_getBlockByNumber
T+12728ms: eth_getBlockByNumber
T+12742ms: eth_estimateGas
T+12752ms: eth_getBlockByNumber
T+12768ms: eth_blockNumber
T+12776ms: eth_sendTransaction
T+12785ms:   Transaction: 0xe34738323a86d1eceb5a33a47926ff73c48f6ecddb83969fc56416b487d1b1c8
T+12785ms:   Contract created: 0x2f42e557deeb9d3785028898db7fd63315f2b36c
T+12785ms:   Gas usage: 1294407
T+12785ms:   Block Number: 4
T+12800ms:   Block Time: Sat Apr 13 2019 23:30:31 GMT+0900 (KST)
T+12809ms: eth_getBlockByNumber
T+12833ms: eth_getTransactionReceipt
T+12833ms: eth_getCode
T+12833ms: eth_getTransactionByHash
T+12833ms: eth_getBlockByNumber
T+12833ms: eth_getBalance
T+12833ms: eth_getBlockByNumber
T+12833ms: eth_getBlockByNumber
T+12833ms: eth_sendTransaction
T+12842ms:   Transaction: 0x3dc9be30bd7f6bc3126dbb839280fadafc6da80b7cb15b7026c1eeb83349a70d
T+12842ms:   Gas usage: 27028
T+12842ms:   Block Number: 5
T+12842ms:   Block Time: Sat Apr 13 2019 23:30:31 GMT+0900 (KST)
T+12857ms: eth_getBlockByNumber
T+12866ms: eth_getTransactionReceipt
T+14999ms: eth_unsubscribe
T+14999ms: eth_unsubscribe
T+15009ms: eth_unsubscribe
T+15009ms: eth_unsubscribe
T+15009ms: eth_unsubscribe
```

**Comment by amorriscode** [comment]
Same issue for me. 😢

**Comment by davidmurdoch** [comment]
Related to https://github.com/trufflesuite/ganache/issues/1169

**Comment by haltman-at** [comment]
Hi! Do you by any chance have an example project we could reproduce this with? Thank you!

**Comment by haltman-at** [comment]
So, we're currently looking into the problem, but I wanted to suggest a workaround until such time as we have a fix.  Would you mind trying this and letting us know if it works?  Try recompling your Truffle project with `truffle compile --all`, or, if necessary, recompiling and redeploying the whole thing with `truffle migrate --compile-all --reset`.

See if that fixes the problem for now; let us know if it works.  Meanwhile, we are, as I said, looking into a more proper fix.  Thank you!

**Comment by davidmurdoch** [comment]
This issue should be fixed in the latest beta! https://github.com/trufflesuite/ganache/releases/tag/v2.0.2-beta.0
