### ISSUE TITLE
System Error when running Ganache 2.0.0 on win32

### ISSUE THREAD

**Issue by Ron-Zhong** [trufflesuite/ganache#1249]
PLATFORM: win32
GANACHE VERSION: 2.0.0

EXCEPTION:
```
TypeError: Cannot read property 'nodes' of undefined
    at getStateVariables (C:\Program Files\WindowsApps\Ganache_2.0.0.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\allocate\storage.js:146:24)
    at vars.concat.linearizedBaseContractsFromBase.map (C:\Program Files\WindowsApps\Ganache_2.0.0.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\allocate\storage.js:154:73)
    at Array.map (native)
    at allocateContract (C:\Program Files\WindowsApps\Ganache_2.0.0.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\allocate\storage.js:154:61)
    at Object.getStorageAllocations (C:\Program Files\WindowsApps\Ganache_2.0.0.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\allocate\storage.js:28:23)
    at TruffleContractDecoder.init (C:\Program Files\WindowsApps\Ganache_2.0.0.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\interface\contract-decoder.js:87:43)
    at Object.getContractState (C:\Program Files\WindowsApps\Ganache_2.0.0.0_x64__zh355ej5cj694\app\resources\app.asar\src\truffle-integration\decode.js:18:11)
    at process.<anonymous> (C:\Program Files\WindowsApps\Ganache_2.0.0.0_x64__zh355ej5cj694\app\resources\app.asar\src\truffle-integration\index.js:76:31)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:768:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+7850637ms: net_version
T+7850764ms: eth_accounts
T+7850863ms: eth_getBlockByNumber
T+7850956ms: eth_accounts
T+7851005ms: eth_getBlockByNumber
T+7851061ms: eth_getBlockByNumber
T+7851107ms: eth_getBlockByNumber
T+7851145ms: eth_estimateGas
T+7851226ms: eth_getBlockByNumber
T+7851303ms: eth_blockNumber
T+7851411ms: eth_sendTransaction
T+7864217ms:   Transaction: 0xf10a8274d800574e6f4a76e13a2a7ebaecce3b1ca3ffbfbc6b4cbe420fbc7685
T+7864253ms:   Contract created: 0x185c78166088429b23481898cc09da024666264e
T+7864253ms:   Gas usage: 232981
T+7864382ms:   Block Number: 62
T+7864580ms:   Block Time: Sun Apr 14 2019 02:28:28 GMT+0800 (Malay Peninsula Standard Time)
T+7864686ms: eth_getBlockByNumber
T+7865082ms: eth_getTransactionReceipt
T+7865149ms: eth_getCode
T+7865211ms: eth_getTransactionByHash
T+7865280ms: eth_getBlockByNumber
T+7865381ms: eth_getBalance
T+7865423ms: eth_getBlockByNumber
T+7865456ms: eth_getBlockByNumber
T+7865500ms: eth_sendTransaction
T+7865531ms:   Transaction: 0xa7c2fd3af60dec930c80651258649813e9bf14cc97fc5e8491129326be9d7b01
T+7865531ms:   Gas usage: 41935
T+7865531ms:   Block Number: 63
T+7865564ms:   Block Time: Sun Apr 14 2019 02:28:29 GMT+0800 (Malay Peninsula Standard Time)
T+7865600ms: eth_getBlockByNumber
T+7865631ms: eth_blockNumber
T+7865663ms: eth_getBlockByNumber
T+7865699ms: eth_getBalance
T+7865730ms: eth_getBalance
T+7865764ms: eth_getBalance
T+7865802ms: eth_getBalance
T+7865833ms: eth_getBalance
T+7865870ms: eth_getBalance
T+7865906ms: eth_getBalance
T+7865936ms: eth_getTransactionReceipt
T+7866375ms: eth_getBlockByNumber
T+7866491ms: eth_accounts
T+7866531ms: eth_getBlockByNumber
T+7866564ms: eth_getBlockByNumber
T+7866597ms: eth_getBlockByNumber
T+7866636ms: eth_estimateGas
T+7866668ms: eth_getBlockByNumber
T+7866701ms: eth_blockNumber
T+7866739ms: eth_sendTransaction
T+7866773ms:   Transaction: 0x3ed6733f8a31c957d3d3707cd5bef6a70390953518a1e411d8ee9fe69e377177
T+7866773ms:   Contract created: 0x2052a14cebc73f404b1ce1cacf1fb00d818a6d40
T+7866811ms:   Gas usage: 726964
T+7866811ms:   Block Number: 64
T+7866842ms:   Block Time: Sun Apr 14 2019 02:28:30 GMT+0800 (Malay Peninsula Standard Time)
T+7866913ms: eth_getBlockByNumber
T+7866913ms: eth_getTransactionReceipt
T+7866913ms: eth_getCode
T+7866913ms: eth_getTransactionByHash
T+7866913ms: eth_getBlockByNumber
T+7866944ms: eth_getBalance
T+7866978ms: eth_getBlockByNumber
T+7867016ms: net_version
T+7867047ms: eth_getBlockByNumber
T+7867077ms: eth_getBlockByNumber
T+7867113ms: net_version
T+7867145ms: eth_estimateGas
T+7867182ms: eth_getBlockByNumber
T+7867213ms: eth_blockNumber
T+7867245ms: net_version
T+7867285ms: eth_sendTransaction
T+7867317ms:   Transaction: 0x720123cb2af68daf1cf1b1283d5dd2829a9a9ac4cfc6f91d9d8038550050b2f2
T+7867317ms:   Contract created: 0xfbb2db0c7b32e36abae59c75a3b4d371da7b93f9
T+7867317ms:   Gas usage: 625343
T+7867348ms:   Block Number: 65
T+7867348ms:   Block Time: Sun Apr 14 2019 02:28:31 GMT+0800 (Malay Peninsula Standard Time)
T+7867384ms: eth_getBlockByNumber
T+7867414ms: eth_getTransactionReceipt
T+7867446ms: eth_getCode
T+7867485ms: eth_getTransactionByHash
T+7867518ms: eth_getBlockByNumber
T+7867557ms: eth_getBalance
T+7867590ms: eth_getBlockByNumber
T+7867623ms: eth_getBlockByNumber
T+7867665ms: eth_sendTransaction
T+7867697ms:   Transaction: 0xb21cc61d73ad6b057a8c129902df4303867506ce1bf4cc5cbf3a2fbedfeada0d
T+7867697ms:   Gas usage: 26935
T+7867697ms:   Block Number: 66
T+7867731ms:   Block Time: Sun Apr 14 2019 02:28:31 GMT+0800 (Malay Peninsula Standard Time)
T+7867771ms: eth_getBlockByNumber
T+7867806ms: eth_getTransactionReceipt
T+7872113ms: eth_blockNumber
T+7872181ms: eth_getBlockByNumber
T+7872249ms: eth_getBalance
T+7872294ms: eth_getBalance
T+7872329ms: eth_getBalance
T+7872364ms: eth_getBalance
T+7872409ms: eth_getBalance
T+7872448ms: eth_getBalance
T+7872492ms: eth_getBalance
T+7880304ms: eth_unsubscribe
T+7880351ms: eth_unsubscribe
T+7880395ms: eth_unsubscribe
```

**Comment by davidmurdoch** [comment]
Related to https://github.com/trufflesuite/ganache/issues/1169

**Comment by haltman-at** [comment]
Hi! Do you by any chance have an example project we could reproduce this with? Thank you!

**Comment by haltman-at** [comment]
So, we're currently looking into the problem, but I wanted to suggest a workaround until such time as we have a fix.  Would you mind trying this and letting us know if it works?  Try recompling your Truffle project with `truffle compile --all`, or, if necessary, recompiling and redeploying the whole thing with `truffle migrate --compile-all --reset`.

See if that fixes the problem for now; let us know if it works.  Meanwhile, we are, as I said, looking into a more proper fix.  Thank you!

**Comment by davidmurdoch** [comment]
This issue should be fixed in the latest beta! https://github.com/trufflesuite/ganache/releases/tag/v2.0.2-beta.0
