### ISSUE TITLE
System Error when running Ganache 2.0.0 on linux

### ISSUE THREAD

**Issue by kYem** [trufflesuite/ganache#1253]
Trying to save a project with truffle.config.js added to truffle projects. Works fine without.

PLATFORM: linux
GANACHE VERSION: 2.0.0

EXCEPTION:
```
Error: /tmp/ganache119314-9180-94gocc.49psp/index.js:9
  );
  ^

SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3

    at Socket.child.stderr.on.data (/src/truffle-integration/projectDetails.js:73:15)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at Socket.Readable.push (_stream_readable.js:197:10)
    at Pipe.onread (net.js:589:20)
```

Temp file content

```
const fs = require("fs");
const path = require("path");

if (process.argv.length < 3) {
  throw new Error(
    `The truffle-project-loader process requires atleast 3 arguments, received ${
      process.argv.length
    }.`,
  );
}

const projectFile = process.argv[2];

const configFileDirectory = path.dirname(projectFile);
const name = path.basename(configFileDirectory);
if (!fs.existsSync(projectFile)) {
  process.send({
    name,
    configFile: projectFile,
    error: "project-does-not-exist",
  });
} else if (
  path.basename(projectFile).match(/^truffle(-config)?.js$/) === null
) {
  process.send({
    name,
    configFile: projectFile,
    error: "invalid-project-file",
  });
} else {
  const output = require(projectFile);

  process.send(output);
}
```

```
node -v 
v10.15.3
```

**Comment by davidmurdoch** [comment]
Thanks for opening the issue, @kYem . This should be fixed in our latest release, [v2.0.1](https://github.com/trufflesuite/ganache/releases/tag/v2.0.1). Can you try it and let me know if this fixes your issue?
