### ISSUE TITLE
System Error when running Ganache 2.0.1 on darwin

### ISSUE THREAD

**Issue by CodeFuriate** [trufflesuite/ganache#1256]
PLATFORM: darwin
GANACHE VERSION: 2.0.1

EXCEPTION:
```
TypeError: Cannot read property 'nodes' of undefined
    at getStateVariables (/node_modules/truffle-decoder/dist/allocate/storage.js:146:24)
    at vars.concat.linearizedBaseContractsFromBase.map (/node_modules/truffle-decoder/dist/allocate/storage.js:154:73)
    at Array.map (native)
    at allocateContract (/node_modules/truffle-decoder/dist/allocate/storage.js:154:61)
    at Object.getStorageAllocations (/node_modules/truffle-decoder/dist/allocate/storage.js:28:23)
    at TruffleContractDecoder.init (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:85:43)
    at Object.getDecodedEvent (/src/truffle-integration/decode.js:42:11)
    at process.<anonymous> (/src/truffle-integration/index.js:92:31)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:768:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: eth_unsubscribe
T+0ms: eth_unsubscribe
T+5ms: eth_unsubscribe
T+5ms: eth_unsubscribe
T+5ms: eth_unsubscribe
T+1344ms: Starting server (version 2.0.1) with initial configuration: {"gasLimit":8000000,"gasPrice":20000000000,"hardfork":"petersburg","db_path":"/Users/mmachg2a/Library/Application Support/Ganache/workspaces/nosy-pigs/chaindata","default_balance_ether":100,"hostname":"127.0.0.1","locked":false,"network_id":5777,"port":7545,"total_accounts":10,"unlocked_accounts":[],"verbose":false,"vmErrorsOnRPCResponse":true}
T+1803ms: Ganache started successfully!
T+1803ms: Waiting for requests...
T+1840ms: eth_getCode
T+1898ms: eth_subscribe
T+1934ms: eth_getLogs
T+1966ms: eth_subscribe
T+1997ms: eth_getCode
T+2096ms: eth_getCode
T+2130ms: eth_getCode
T+15004ms: eth_unsubscribe
T+15032ms: eth_unsubscribe
T+15066ms: eth_unsubscribe
T+15100ms: eth_unsubscribe
```

**Comment by davidmurdoch** [comment]
Closing this one as we're still tracking it at https://github.com/trufflesuite/ganache/issues/1169
