### ISSUE TITLE
System Error when running Ganache 2.0.0 on darwin

### ISSUE THREAD

**Issue by fellipetenorio** [trufflesuite/ganache#1257]
PLATFORM: darwin
GANACHE VERSION: 2.0.0

EXCEPTION:
```
TypeError: Cannot read property 'subscriptions' of undefined
    at /node_modules/ganache-core/lib/webSocketServer.js:87:42
    at process.nextTick (/node_modules/ganache-core/lib/provider.js:114:28)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+1685853ms:   Contract created: 0x02a742d70ec515f556253b97012bd3764c124e3a
T+1685853ms:   Gas usage: 3329677
T+1685853ms:   Block Number: 674
T+1685854ms:   Block Time: Tue Apr 16 2019 17:05:00 GMT-0300 (-03)
T+1685855ms: eth_getBlockByNumber
T+1686119ms: eth_getBlockByNumber
T+1686126ms: eth_getBlockByNumber
T+1686135ms: eth_getBlockByNumber
T+1687303ms: eth_getBlockByNumber
T+1687303ms: eth_getBlockByNumber
T+1687311ms: eth_getBlockByNumber
T+1687316ms: eth_getBlockByNumber
T+1687318ms: eth_getBlockByNumber
T+1687327ms: eth_getBlockByNumber
T+1687430ms: eth_getBlockByNumber
T+1687436ms: eth_getBlockByNumber
T+1687449ms: eth_getBlockByNumber
T+1687455ms: eth_getBlockByNumber
T+1687464ms: eth_getBlockByNumber
T+1687498ms: eth_getBlockByNumber
T+1688600ms: eth_getBlockByNumber
T+1688601ms: eth_getBlockByNumber
T+1688605ms: eth_getBlockByNumber
T+1688610ms: eth_getBlockByNumber
T+1688615ms: eth_getBlockByNumber
T+1688616ms: eth_getBlockByNumber
T+1689342ms: eth_getBlockByNumber
T+1689347ms: eth_getBlockByNumber
T+1689351ms: eth_getBlockByNumber
T+1689353ms: eth_getBlockByNumber
T+1689374ms: eth_getBlockByNumber
T+1689376ms: eth_getBlockByNumber
T+1689377ms: eth_getBlockByNumber
T+1689381ms: eth_getBlockByNumber
T+1689382ms: eth_getBlockByNumber
T+1689386ms: eth_getBlockByNumber
T+1689392ms: eth_getBlockByNumber
T+1689397ms: eth_getBlockByNumber
T+1689402ms: eth_getBlockByNumber
T+1689403ms: eth_getBlockByNumber
T+1689546ms: eth_getTransactionReceipt
T+1689555ms: eth_getCode
T+1690768ms: eth_getBlockByNumber
T+1690776ms: eth_getBlockByNumber
T+1690783ms: eth_getBlockByNumber
T+1690844ms: eth_getBlockByNumber
T+1690844ms: eth_getBlockByNumber
T+1693264ms: eth_accounts
T+1694852ms: eth_gasPrice
T+1694852ms: eth_sendTransaction
T+1694852ms:   Transaction: 0x03ff0e1209cd8461bcc34ae9ea04c4aa0247150ccc177bc107498cd1767979c4
T+1694852ms:   Gas usage: 43698
T+1694852ms:   Block Number: 675
T+1694852ms:   Block Time: Tue Apr 16 2019 17:05:08 GMT-0300 (-03)
T+1694852ms: eth_getBlockByNumber
T+1694852ms: eth_getTransactionReceipt
T+1694852ms: eth_call
T+1694852ms: eth_accounts
T+1694856ms: eth_gasPrice
T+1694858ms: eth_sendTransaction
T+1694860ms:   Transaction: 0x3369f42664e90216ed514b9b8ac75d72a714305650c80cbd10dcee7a0b769b41
T+1694860ms:   Gas usage: 28698
T+1694860ms:   Block Number: 676
T+1694860ms:   Block Time: Tue Apr 16 2019 17:05:09 GMT-0300 (-03)
T+1694860ms: eth_getBlockByNumber
T+1694860ms: eth_getTransactionReceipt
T+1694861ms: eth_call
T+1695685ms: eth_call
T+1695704ms: eth_subscribe
T+1763486ms: eth_unsubscribe
T+1765141ms: eth_accounts
T+1765260ms: eth_gasPrice
T+1765308ms: eth_sendTransaction
T+1766242ms:   Transaction: 0x885e2e2b3aa56d3d138b39e97b050f003c43590dd7558c6b68263ecea1871dd7
T+1766242ms:   Gas usage: 28698
T+1766242ms:   Block Number: 677
T+1766242ms:   Block Time: Tue Apr 16 2019 17:06:20 GMT-0300 (-03)
T+1766242ms: eth_getBlockByNumber
T+1766242ms: eth_getTransactionReceipt
T+1766242ms: eth_call
T+1767749ms: eth_call
T+1767749ms: eth_subscribe
T+1777203ms: eth_unsubscribe
T+1779091ms: eth_accounts
T+1779867ms: eth_gasPrice
T+1779867ms: eth_sendTransaction
T+1779867ms:   Transaction: 0x74b00520f59b20addae1cb5b6b78d1fd98c6aa7446eb8724ec12b29de7a48222
T+1779867ms:   Gas usage: 28698
T+1779867ms:   Block Number: 678
T+1779867ms:   Block Time: Tue Apr 16 2019 17:06:34 GMT-0300 (-03)
T+1779867ms: eth_getBlockByNumber
T+1779867ms: eth_getTransactionReceipt
T+1779867ms: eth_call
T+1781658ms: eth_call
T+1781663ms: eth_subscribe
T+1781663ms: eth_subscribe
T+1825452ms: eth_unsubscribe
T+1825452ms: eth_unsubscribe
T+1826832ms: eth_accounts
T+1827002ms: eth_gasPrice
T+1827023ms: eth_sendTransaction
T+1828092ms:   Transaction: 0xc12a168becd877fe22e2c740053c9520ce64856a07a8588c296375ab7a54c6ff
T+1828092ms:   Gas usage: 28698
T+1828092ms:   Block Number: 679
T+1828092ms:   Block Time: Tue Apr 16 2019 17:07:22 GMT-0300 (-03)
T+1828092ms: eth_getBlockByNumber
T+1828092ms: eth_getTransactionReceipt
T+1828092ms: eth_call
T+1828964ms: eth_call
T+1828964ms: eth_subscribe
T+1828964ms: eth_subscribe
T+1835928ms: eth_gasPrice
T+1835931ms: eth_sendTransaction
T+1836455ms:   Transaction: 0x006b9496018133f6fb44c425a6c31d9030a041e47e5adadf179efff5176a1cde
T+1836455ms:   Gas usage: 59764
T+1836455ms:   Block Number: 680
T+1836455ms:   Block Time: Tue Apr 16 2019 17:07:31 GMT-0300 (-03)
T+1836455ms: eth_getBlockByNumber
T+1839547ms: eth_getTransactionReceipt
T+2076934ms: eth_call
T+2076960ms: eth_subscribe
T+2079346ms: eth_unsubscribe
T+2169180ms: eth_unsubscribe
T+2169180ms: eth_unsubscribe
T+2171353ms: eth_accounts
T+2171452ms: eth_gasPrice
T+2171464ms: eth_sendTransaction
T+2172593ms:   Transaction: 0xfe0a74236ca2131f77e1c3821037948ec68bb39f58ec8563e180745a1a114dfa
T+2172593ms:   Gas usage: 28698
T+2172593ms:   Block Number: 681
T+2172593ms:   Block Time: Tue Apr 16 2019 17:13:06 GMT-0300 (-03)
T+2172593ms: eth_getBlockByNumber
T+2172593ms: eth_getTransactionReceipt
T+2172593ms: eth_call
T+2173510ms: eth_call
T+2173675ms: eth_subscribe
T+2173675ms: eth_subscribe
T+2173807ms: eth_unsubscribe
T+2173810ms: eth_unsubscribe
T+2173823ms: eth_unsubscribe
```

**Comment by davidmurdoch** [comment]
Thanks for opening the issue, @fellipetenorio! This bug has been fixed in the latest version of Ganache. Can you try updating and letting me know if you still have issues? [Ganache v2.0.1](https://github.com/trufflesuite/ganache/releases/tag/v2.0.1)

**Comment by fellipetenorio** [comment]
Will try it!
Ty
