### ISSUE TITLE
Couldn't connect to node on WS.

### ISSUE THREAD

**Issue by dulcedu** [trufflesuite/ganache#1265]
### Unexplainable BOOM after good ol' simple migration
This only happens when using a Workspace. Quickstart does not explode unexpectedly.

PLATFORM: win32
GANACHE VERSION: **2.0.1**

EXCEPTION:
```
Error: CONNECTION ERROR: Couldn't connect to node on WS.
    at Object.InvalidConnection (C:\Program Files\Ganache\resources\app.asar\node_modules\web3-core-helpers\src\errors.js:35:16)
    at WebsocketProvider._timeout (C:\Program Files\Ganache\resources\app.asar\node_modules\web3-providers-ws\src\index.js:249:48)
    at W3CWebSocket.connection.onclose (C:\Program Files\Ganache\resources\app.asar\node_modules\web3-providers-ws\src\index.js:149:15)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (C:\Program Files\Ganache\resources\app.asar\node_modules\yaeti\lib\EventTarget.js:107:17)
    at W3CWebSocket.onClose (C:\Program Files\Ganache\resources\app.asar\node_modules\websocket\lib\W3CWebSocket.js:228:10)
    at WebSocketConnection.<anonymous> (C:\Program Files\Ganache\resources\app.asar\node_modules\websocket\lib\W3CWebSocket.js:201:17)
    at emitTwo (events.js:125:13)
    at WebSocketConnection.emit (events.js:213:7)
    at WebSocketConnection.handleSocketClose (C:\Program Files\Ganache\resources\app.asar\node_modules\websocket\lib\WebSocketConnection.js:387:14)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at TCP._handle.close [as _onclose] (net.js:549:12)
```

APPLICATION LOG:
```
T+1348ms: eth_subscribe
T+17247ms: net_version
T+20276ms: eth_getBlockByNumber
T+20276ms: eth_accounts
T+21485ms: eth_getBlockByNumber
T+21485ms: net_version
T+21485ms: eth_getBlockByNumber
T+21485ms: eth_getBlockByNumber
T+21485ms: net_version
T+21485ms: eth_estimateGas
T+24392ms: eth_getBlockByNumber
T+24499ms: eth_blockNumber
T+24633ms: net_version
T+24753ms: eth_sendTransaction
T+53502ms:   Transaction: 0xc717432f61677583fd0787d0a6a1a63f50f674fa16c708d8e7b16f1ceb4ae149
T+53502ms:   Contract created: 0x6738684d27e2dd4dadea2853c6ca8f1891779a80
T+53502ms:   Gas usage: 189827
T+53502ms:   Block Number: 8
T+53502ms:   Block Time: Sat Apr 20 2019 22:14:42 GMT-0500 (Central Daylight Time (Mexico))
T+53502ms: eth_getTransactionReceipt
T+53502ms: eth_getCode
T+53502ms: eth_getTransactionByHash
T+53502ms: eth_getBalance
T+53764ms: eth_getBlockByNumber
T+53764ms: eth_accounts
T+53764ms: eth_getBlockByNumber
T+53764ms: net_version
T+53764ms: eth_getBlockByNumber
T+53764ms: eth_getBlockByNumber
T+53764ms: net_version
T+53764ms: eth_estimateGas
T+54121ms: eth_getBlockByNumber
T+54121ms: eth_blockNumber
T+54121ms: net_version
T+54121ms: eth_sendTransaction
T+54957ms:   Transaction: 0x368f19695a611122f8822dc1a7414d5b40e13d9f2f44d61fce9e90659390c98c
T+54957ms:   Contract created: 0xef98ff2142ee201555f0802678912bf7f908cfe0
T+54957ms:   Gas usage: 1879532
T+54957ms:   Block Number: 9
T+54957ms:   Block Time: Sat Apr 20 2019 22:14:44 GMT-0500 (Central Daylight Time (Mexico))
T+54957ms: eth_getTransactionReceipt
T+54957ms: eth_getCode
T+54957ms: eth_getTransactionByHash
T+54957ms: eth_getBalance
T+54957ms: eth_getBlockByNumber
T+54957ms: eth_getBlockByNumber
T+54957ms: net_version
T+54957ms: eth_getBlockByNumber
T+54957ms: eth_getBlockByNumber
T+54957ms: net_version
T+54957ms: eth_estimateGas
T+55216ms: eth_getBlockByNumber
T+55216ms: eth_blockNumber
T+55216ms: net_version
T+55216ms: eth_sendTransaction
T+55216ms:   Transaction: 0x88bd911580a803d9c48b8841afa2be0a2ff5afc3cc9038f65bbf4687c3badb6d
T+55216ms:   Contract created: 0x7d1aba4967cc76f909a2b984ed8304208676f560
T+55216ms:   Gas usage: 770064
T+55216ms:   Block Number: 10
T+55216ms:   Block Time: Sat Apr 20 2019 22:14:45 GMT-0500 (Central Daylight Time (Mexico))
T+55216ms: eth_getTransactionReceipt
T+55216ms: eth_getCode
T+55216ms: eth_getTransactionByHash
T+55216ms: eth_getBalance
T+55216ms: eth_getBlockByNumber
T+55216ms: eth_getBlockByNumber
T+55216ms: eth_sendTransaction
T+55501ms:   Transaction: 0x8bca2c36039305c4475180a8f26c3727ea118baf7a06305ab6943e47b16d52bd
T+55501ms:   Gas usage: 45902
T+55501ms:   Block Number: 11
T+55501ms:   Block Time: Sat Apr 20 2019 22:14:46 GMT-0500 (Central Daylight Time (Mexico))
T+55501ms: eth_getTransactionReceipt
T+55501ms: eth_getBlockByNumber
T+55501ms: eth_getBlockByNumber
T+55501ms: eth_sendTransaction
T+57347ms:   Transaction: 0x20a5b53857064a22beb59ac2f8cc102f8086ef41c61891bd2c13eb04919aa9f6
T+57347ms:   Gas usage: 1294412
T+57347ms:   Block Number: 12
T+57347ms:   Block Time: Sat Apr 20 2019 22:14:46 GMT-0500 (Central Daylight Time (Mexico))
T+57347ms: eth_getTransactionReceipt
T+57695ms: eth_getBlockByNumber
T+57695ms: eth_sendTransaction
T+58470ms: eth_unsubscribe
T+58470ms: eth_unsubscribe
T+59057ms:   Transaction: 0x6a12f92c531ef77490fee3504911eceb268ad92383f3dc8f8f3414ece616c97e
T+59057ms:   Gas usage: 1249156
T+59057ms:   Block Number: 13
T+59057ms:   Block Time: Sat Apr 20 2019 22:14:51 GMT-0500 (Central Daylight Time (Mexico))
T+59057ms: eth_getTransactionReceipt
T+59057ms: eth_getBlockByNumber
T+59057ms: eth_sendTransaction
T+60012ms:   Transaction: 0x4aba2678f3d166747d4446537b0b016da1f9ae514c4e7b27f64b03969401e3be
T+60012ms:   Gas usage: 1249284
T+60012ms:   Block Number: 14
T+60012ms:   Block Time: Sat Apr 20 2019 22:14:54 GMT-0500 (Central Daylight Time (Mexico))
T+60012ms: eth_getTransactionReceipt
T+60012ms: eth_getBlockByNumber
T+60012ms: eth_sendTransaction
T+60648ms: eth_unsubscribe
T+60738ms:   Transaction: 0x64fa331d5455baaa0a77ea897d5fd712f1aa4d4e3b9415dac8fd446a6540d2e5
T+60738ms:   Gas usage: 1248580
T+60738ms:   Block Number: 15
T+60794ms:   Block Time: Sat Apr 20 2019 22:14:57 GMT-0500 (Central Daylight Time (Mexico))
```

**Comment by davidmurdoch** [comment]
Closing in favor of #1497.
