### ISSUE TITLE
System Error when running Ganache 2.0.1 on linux

### ISSUE THREAD

**Issue by obernardovieira** [trufflesuite/ganache#1268]
PLATFORM: linux
GANACHE VERSION: 2.0.1

EXCEPTION:
```
TypeError: Cannot read property '0' of undefined
    at findRootScope (/node_modules/ganache-core/lib/utils/gasEstimation.js:88:40)
    at getTotal (/node_modules/ganache-core/lib/utils/gasEstimation.js:155:36)
    at getTotal (/node_modules/ganache-core/lib/utils/gasEstimation.js:221:23)
    at getTotal (/node_modules/ganache-core/lib/utils/gasEstimation.js:192:25)
    at /node_modules/ganache-core/lib/utils/gasEstimation.js:42:21
    at /node_modules/ganache-core/node_modules/ethereumjs-vm/dist/runTx.js:70:9
    at /node_modules/ganache-core/node_modules/async/dist/async.js:969:16
    at next (/node_modules/ganache-core/node_modules/async/dist/async.js:5225:18)
    at /node_modules/ganache-core/node_modules/async/dist/async.js:119:16
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+11386916ms: net_version
T+11387034ms: eth_blockNumber
T+11387072ms: eth_getBlockByNumber
T+11387153ms: net_version
T+11387187ms: eth_getBlockByNumber
T+11387217ms: net_version
T+11387255ms: eth_getBlockByNumber
T+11387284ms: eth_call
T+11387335ms: eth_getBlockByNumber
T+11387362ms: eth_call
T+11387407ms: eth_getBlockByNumber
T+11387431ms: eth_call
T+11387480ms: eth_getBlockByNumber
T+11387504ms: eth_call
T+11387544ms: eth_getBlockByNumber
T+11387569ms: eth_call
T+11387722ms: eth_getBlockByNumber
T+11387746ms: eth_call
T+11387791ms: eth_getBlockByNumber
T+11387818ms: eth_call
T+11388045ms: eth_blockNumber
T+11389056ms: eth_blockNumber
T+11390067ms: eth_blockNumber
T+11390412ms: eth_getBlockByNumber
T+11390435ms: eth_call
T+11391076ms: eth_blockNumber
T+11392085ms: eth_blockNumber
T+11393096ms: eth_blockNumber
T+11394106ms: eth_blockNumber
T+11395117ms: eth_blockNumber
T+11396129ms: eth_blockNumber
T+11397139ms: eth_blockNumber
T+11398150ms: eth_blockNumber
T+11399160ms: eth_blockNumber
T+11400171ms: eth_blockNumber
T+11401182ms: eth_blockNumber
T+11402193ms: eth_blockNumber
T+11403205ms: eth_blockNumber
T+11404212ms: eth_blockNumber
T+11405223ms: eth_blockNumber
T+11405906ms: eth_getBlockByNumber
T+11405928ms: eth_call
T+11406230ms: eth_blockNumber
T+11407236ms: eth_blockNumber
T+11408244ms: eth_blockNumber
T+11409254ms: eth_blockNumber
T+11410264ms: eth_blockNumber
T+11411272ms: eth_blockNumber
T+11412283ms: eth_blockNumber
T+11413294ms: eth_blockNumber
T+11414304ms: eth_blockNumber
T+11415313ms: eth_blockNumber
T+11416321ms: eth_blockNumber
T+11417332ms: eth_blockNumber
T+11417439ms: eth_getBlockByNumber
T+11417463ms: eth_call
T+11417731ms: eth_getBlockByNumber
T+11417754ms: eth_call
T+11418297ms: eth_getBlockByNumber
T+11418321ms: eth_call
T+11418340ms: eth_blockNumber
T+11418505ms: eth_getBlockByNumber
T+11418527ms: eth_call
T+11418722ms: eth_getBlockByNumber
T+11418746ms: eth_call
T+11419020ms: eth_getBlockByNumber
T+11419043ms: eth_call
T+11419414ms: eth_blockNumber
T+11420425ms: eth_blockNumber
T+11420573ms: eth_getBlockByNumber
T+11420605ms: eth_call
T+11420694ms: eth_getBlockByNumber
T+11420717ms: eth_call
T+11420880ms: eth_getBlockByNumber
T+11420905ms: eth_call
T+11421109ms: eth_getBlockByNumber
T+11421133ms: eth_call
T+11421436ms: eth_blockNumber
T+11422185ms: eth_getBlockByNumber
T+11422209ms: eth_call
T+11422317ms: eth_getBlockByNumber
T+11422350ms: eth_call
T+11422444ms: eth_blockNumber
T+11423455ms: eth_blockNumber
T+11423816ms: eth_getBlockByNumber
T+11423842ms: eth_estimateGas
T+11424021ms: eth_gasPrice
T+11424056ms: eth_getBlockByNumber
T+11424393ms: eth_getTransactionCount
T+11424465ms: eth_blockNumber
T+11424548ms: eth_getCode
T+11425474ms: eth_blockNumber
T+11426417ms: eth_getBalance
T+11426427ms: eth_getBalance
T+11426430ms: eth_getBalance
T+11426508ms: eth_blockNumber
T+11426817ms: eth_getTransactionCount
T+11426938ms: eth_getCode
T+11427242ms: eth_call
T+11427473ms: eth_call
T+11427562ms: eth_blockNumber
T+11428572ms: eth_blockNumber
T+11429170ms: eth_getTransactionCount
T+11429221ms: eth_sendRawTransaction
T+11429425ms:   Transaction: 0x7089f68b0af8fff180b647e335459a2d62cb5e3df659fdb513df4d68608814ea
T+11429425ms:   Gas usage: 148991
T+11429425ms:   Block Number: 34
T+11429426ms:   Block Time: Mon Apr 22 2019 15:11:45 GMT+0100 (WEST)
T+11429428ms: eth_getBlockByNumber
T+11429433ms: eth_getTransactionByHash
T+11429524ms: eth_getTransactionReceipt
T+11429535ms: eth_blockNumber
T+11429540ms: eth_blockNumber
T+11429996ms: eth_blockNumber
T+11430001ms: eth_getTransactionCount
T+11430009ms: eth_getBlockByNumber
T+11430073ms: eth_getTransactionReceipt
T+11430077ms: eth_getTransactionByHash
T+11430082ms: eth_getBalance
T+11430084ms: eth_getBalance
T+11430086ms: eth_getBalance
T+11430125ms: eth_getTransactionReceipt
T+11430131ms: eth_getTransactionByHash
T+11430141ms: eth_getCode
T+11430169ms: eth_getTransactionReceipt
T+11430616ms: eth_getCode
T+11431047ms: eth_blockNumber
T+11432058ms: eth_blockNumber
T+11433067ms: eth_blockNumber
T+11434077ms: eth_blockNumber
T+11434621ms: eth_getBlockByNumber
T+11434645ms: eth_call
T+11434711ms: eth_getBlockByNumber
T+11434737ms: eth_call
T+11434777ms: eth_getBlockByNumber
T+11434806ms: eth_call
T+11434882ms: eth_getBlockByNumber
T+11434912ms: eth_call
T+11435086ms: eth_blockNumber
T+11436097ms: eth_blockNumber
T+11437107ms: eth_blockNumber
T+11438118ms: eth_blockNumber
T+11438439ms: eth_getBlockByNumber
T+11438462ms: eth_call
T+11438571ms: eth_getBlockByNumber
T+11438600ms: eth_estimateGas
T+11438719ms: eth_unsubscribe
T+11438722ms: eth_unsubscribe
T+11438724ms: eth_unsubscribe
T+11438726ms: eth_unsubscribe
T+11438726ms: eth_unsubscribe
```

**Comment by davidmurdoch** [comment]
Thank you, @obernardovieira for opening the issue! This is related to a new gas estimation bug and we're trying to find the root cause.

Are you able to provide a minimum reproduction of the contract(s) that caused the crash?

**Comment by obernardovieira** [comment]
Hi, @davidmurdoch 
Thank you so much :pray: 
Unfortunately no. The project is not public yet.
But it does some heavy math calculations. I'll try to find more specifically where it fails. Whenever I get something, I'll get back.

**Comment by jessedionoppchain** [comment]
Hi @davidmurdoch ,

Same issue here. Using the same method on my contract with different parameters:
On a particular parameter the contract make a subcall to another contract => estimateGas is working
On another parameter, the contract make a subcall to another contract, which make another subcall => ganache crash.

To be more precise first contract is an ERC777 token, second is a service contract and third a reward contract.

If I bypass the estimation and give a high estimation the transaction works well.

Hope this can help to understand the problem
