### ISSUE TITLE
System Error when running Ganache 2.0.0 on darwin

### ISSUE THREAD

**Issue by brittneyhill** [trufflesuite/ganache#1271]
I am unable to load my contract address because of this error. Please someone look at this

PLATFORM: darwin
GANACHE VERSION: 2.0.0

EXCEPTION:
```
Error: /Users/brittneyhill/Desktop/SchoolDownloads/Blockchain/Project/chromastake-dev/truffle-config.js:7
      host: "127.0.0.1",
          ^

SyntaxError: Unexpected token :
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)

    at Socket.child.stderr.on.data (/src/truffle-integration/projectDetails.js:73:15)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at Socket.Readable.push (_stream_readable.js:197:10)
    at Pipe.onread (net.js:589:20)
```

**Comment by brittneyhill** [comment]
i was trying to add a truffle-config file to my ganache workspace and when i saved it i would get this error

**Comment by davidmurdoch** [comment]
Hey there @brittneyhill. Sorry you are have issues. Can you share your full truffle-config here?
