### ISSUE TITLE
System Error when running Ganache 2.0.1 on darwin

### ISSUE THREAD

**Issue by murich** [trufflesuite/ganache#1272]
This happens when I am clicking on one of my deployed contracts. 

PLATFORM: darwin
GANACHE VERSION: 2.0.1

EXCEPTION:
```
TypeError: Cannot read property 'nodes' of undefined
    at getStateVariables (/node_modules/truffle-decoder/dist/allocate/storage.js:146:24)
    at vars.concat.linearizedBaseContractsFromBase.map (/node_modules/truffle-decoder/dist/allocate/storage.js:154:73)
    at Array.map (native)
    at allocateContract (/node_modules/truffle-decoder/dist/allocate/storage.js:154:61)
    at Object.getStorageAllocations (/node_modules/truffle-decoder/dist/allocate/storage.js:28:23)
    at TruffleContractDecoder.init (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:85:43)
    at Object.getContractState (/src/truffle-integration/decode.js:18:11)
    at process.<anonymous> (/src/truffle-integration/index.js:76:31)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:768:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+39957526ms: net_version
T+39957697ms: eth_sendTransaction
T+39957823ms:   Transaction: 0x7a6fb1fd07eece85737553d247a6d373b746df178f77c1cf7ed14a6b3ae18a02
T+39957823ms:   Contract created: 0x9db9528836587517cd6b90026b430f6e58063f64
T+39957823ms:   Gas usage: 1250492
T+39957823ms:   Block Number: 12
T+39957823ms:   Block Time: Wed Apr 24 2019 09:20:34 GMT+0300 (EEST)
T+39957823ms:   Runtime Error: revert
T+39957823ms: eth_call
T+39957925ms: eth_getBlockByNumber
T+39957925ms: eth_getBlockByNumber
T+39958030ms: eth_getBlockByNumber
T+39958191ms: eth_getBlockByNumber
T+39958191ms: eth_getBlockByNumber
T+40053858ms: net_version
T+40054236ms: eth_accounts
T+40054826ms: eth_getBlockByNumber
T+40054826ms: eth_accounts
T+40055240ms: eth_getBlockByNumber
T+40055240ms: eth_getBlockByNumber
T+40055785ms: eth_getBlockByNumber
T+40055785ms: eth_estimateGas
T+40056099ms: eth_getBlockByNumber
T+40056099ms: eth_blockNumber
T+40056500ms: eth_sendTransaction
T+40121694ms:   Transaction: 0x6d3674c82a35d941f4a49ff409d2d1dc1c28a1f016283a6a592fd8914d6538df
T+40121694ms:   Contract created: 0x9f2b851d683abe6d66bb552a50014ffbb94c60e7
T+40121694ms:   Gas usage: 277462
T+40121694ms:   Block Number: 13
T+40121694ms:   Block Time: Wed Apr 24 2019 09:23:06 GMT+0300 (EEST)
T+40121694ms: eth_getTransactionReceipt
T+40121694ms: eth_getCode
T+40121694ms: eth_getTransactionByHash
T+40121878ms: eth_getBlockByNumber
T+40121878ms: eth_getBalance
T+40121878ms: eth_getBlockByNumber
T+40122016ms: eth_getBlockByNumber
T+40122150ms: eth_sendTransaction
T+40122352ms:   Transaction: 0xa903f8b1bfac5ddc702356a9eb001fd7a5b6a87826151fbe114b25471cfff478
T+40122352ms:   Gas usage: 42008
T+40122352ms:   Block Number: 14
T+40122352ms:   Block Time: Wed Apr 24 2019 09:23:06 GMT+0300 (EEST)
T+40122465ms: eth_getTransactionReceipt
T+40122575ms: eth_getBlockByNumber
T+40122705ms: eth_accounts
T+40122933ms: eth_getBlockByNumber
T+40123046ms: eth_getBlockByNumber
T+40123172ms: eth_getBlockByNumber
T+40123317ms: eth_estimateGas
T+40123502ms: eth_getBlockByNumber
T+40123502ms: eth_blockNumber
T+40123502ms: eth_sendTransaction
T+40123625ms:   Transaction: 0x2fac23f33da86c7506a4d8539efd29a88baae0222f43b88f8b7c022cb1259d5c
T+40123625ms:   Contract created: 0xc93fc6808cff5dddf88e46b78a5119b3db1d24e1
T+40123625ms:   Gas usage: 953902
T+40123625ms:   Block Number: 15
T+40123625ms:   Block Time: Wed Apr 24 2019 09:23:07 GMT+0300 (EEST)
T+40123625ms: eth_getTransactionReceipt
T+40123625ms: eth_getCode
T+40123729ms: eth_getTransactionByHash
T+40123729ms: eth_getBlockByNumber
T+40123864ms: eth_getBalance
T+40124081ms: eth_getBlockByNumber
T+40124081ms: eth_getBlockByNumber
T+40124081ms: eth_sendTransaction
T+40124203ms:   Transaction: 0x5ea3bcec61d6dd35b94b6a4da55e6459770985313719b955f50c88492a00d370
T+40124203ms:   Gas usage: 27008
T+40124203ms:   Block Number: 16
T+40124203ms:   Block Time: Wed Apr 24 2019 09:23:07 GMT+0300 (EEST)
T+40124357ms: eth_getTransactionReceipt
T+40124486ms: eth_getBlockByNumber
T+40124668ms: eth_accounts
T+40124790ms: eth_getBlockByNumber
T+40124790ms: net_version
T+40124790ms: eth_getBlockByNumber
T+40124790ms: eth_getBlockByNumber
T+40124927ms: net_version
T+40125108ms: eth_estimateGas
T+40125294ms: eth_getBlockByNumber
T+40125410ms: eth_blockNumber
T+40125549ms: net_version
T+40125664ms: eth_sendTransaction
T+40125914ms:   Transaction: 0xe20dd446b22263db722723767505115a1ce3f80fd516de00c068086d6fd08e11
T+40125914ms:   Contract created: 0x4c6bafda49317d7451f00f11d5420a5d954e68c5
T+40125914ms:   Gas usage: 4573266
T+40125914ms:   Block Number: 17
T+40125914ms:   Block Time: Wed Apr 24 2019 09:23:08 GMT+0300 (EEST)
T+40125914ms: eth_getTransactionReceipt
T+40125914ms: eth_getCode
T+40125914ms: eth_getTransactionByHash
T+40125914ms: eth_getBlockByNumber
T+40125914ms: eth_getBalance
T+40126054ms: eth_getBlockByNumber
T+40126245ms: eth_getBlockByNumber
T+40126449ms: eth_sendTransaction
T+40126647ms:   Transaction: 0xe4b2bd6d6957c2c0bfbeb725f30a2f83bca66a3db320a943b5caa642bcbe93e4
T+40126647ms:   Gas usage: 27008
T+40126647ms:   Block Number: 18
T+40126647ms:   Block Time: Wed Apr 24 2019 09:23:08 GMT+0300 (EEST)
T+40126780ms: eth_getTransactionReceipt
T+40126905ms: eth_getBlockByNumber
T+40126905ms: eth_getBlockByNumber
T+40127067ms: eth_getBlockByNumber
T+40127067ms: eth_getBlockByNumber
T+40127067ms: eth_getBlockByNumber
T+40127067ms: eth_getBlockByNumber
T+40160025ms: eth_unsubscribe
T+40160025ms: eth_unsubscribe
T+40160190ms: eth_unsubscribe
T+40160190ms: eth_unsubscribe
```

**Comment by davidmurdoch** [comment]
This issue should be fixed in the latest beta! https://github.com/trufflesuite/ganache/releases/tag/v2.0.2-beta.0
