### ISSUE TITLE
System Error when running Ganache 2.0.1 on win32

### ISSUE THREAD

**Issue by francomidence** [trufflesuite/ganache#1278]
PLATFORM: win32
GANACHE VERSION: 2.0.1

EXCEPTION:
```
TypeError: Cannot read property 'nodes' of undefined
    at getStateVariables (C:\Program Files\WindowsApps\Ganache_2.0.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\allocate\storage.js:146:24)
    at vars.concat.linearizedBaseContractsFromBase.map (C:\Program Files\WindowsApps\Ganache_2.0.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\allocate\storage.js:154:73)
    at Array.map (native)
    at allocateContract (C:\Program Files\WindowsApps\Ganache_2.0.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\allocate\storage.js:154:61)
    at Object.getStorageAllocations (C:\Program Files\WindowsApps\Ganache_2.0.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\allocate\storage.js:28:23)
    at TruffleContractDecoder.init (C:\Program Files\WindowsApps\Ganache_2.0.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\interface\contract-decoder.js:85:43)
    at Object.getDecodedEvent (C:\Program Files\WindowsApps\Ganache_2.0.1.0_x64__zh355ej5cj694\app\resources\app.asar\src\truffle-integration\decode.js:42:11)
    at process.<anonymous> (C:\Program Files\WindowsApps\Ganache_2.0.1.0_x64__zh355ej5cj694\app\resources\app.asar\src\truffle-integration\index.js:92:31)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:768:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: Starting server (version 2.0.1) with initial configuration: {"gasLimit":6721975,"gasPrice":20000000000,"hardfork":"petersburg","hostname":"127.0.0.1","port":7545,"network_id":5777,"default_balance_ether":100,"total_accounts":10,"unlocked_accounts":[],"locked":false,"vmErrorsOnRPCResponse":true,"verbose":false,"db_path":"C:\\Users\\srssd\\AppData\\Roaming\\Ganache\\workspaces\\smmdemo\\chaindata"}
T+317ms: Ganache started successfully!
T+317ms: Waiting for requests...
T+328ms: eth_getCode
T+342ms: eth_subscribe
T+348ms: eth_getLogs
T+355ms: eth_subscribe
T+364ms: eth_blockNumber
T+18372ms: net_version
T+18428ms: eth_accounts
T+19093ms: eth_getBlockByNumber
T+19119ms: eth_accounts
T+19136ms: eth_getBlockByNumber
T+19162ms: net_version
T+19196ms: eth_getBlockByNumber
T+19207ms: eth_getBlockByNumber
T+19220ms: net_version
T+19234ms: eth_estimateGas
T+19247ms: eth_getBlockByNumber
T+19258ms: eth_blockNumber
T+19273ms: net_version
T+19283ms: eth_sendTransaction
T+20390ms:   Transaction: 0x3b68e3ace0c7bcd5cddc205bbd5a06bf11367e180ba7ea957642fca346c07d7c
T+20390ms:   Contract created: 0x76d6920a46c1b6dd489dd0746585a6dde445b4b3
T+20401ms:   Gas usage: 284908
T+20401ms:   Block Number: 5
T+20405ms:   Block Time: Mon Apr 29 2019 14:59:45 GMT-0600 (Central America Standard Time)
T+20410ms: eth_getBlockByNumber
T+20415ms: eth_getTransactionReceipt
T+20420ms: eth_getCode
T+20425ms: eth_getTransactionByHash
T+20437ms: eth_getBalance
T+20443ms: eth_getBlockByNumber
T+20449ms: eth_accounts
T+20455ms: eth_getBlockByNumber
T+20461ms: eth_getBlockByNumber
T+20468ms: eth_getBlockByNumber
T+20514ms: eth_estimateGas
T+20547ms: eth_getBlockByNumber
T+20561ms: eth_blockNumber
T+20567ms: eth_sendTransaction
T+20573ms:   Transaction: 0xec44139e4c47835f144bb71b1c934e806dc059b0d7522863babee542db7c75f3
T+20580ms:   Contract created: 0x8611399f3ea9ab74efb9149302c7bffafde6a949
T+20580ms:   Gas usage: 872426
T+20580ms:   Block Number: 6
T+20580ms:   Block Time: Mon Apr 29 2019 14:59:45 GMT-0600 (Central America Standard Time)
T+20587ms: eth_getBlockByNumber
T+20607ms: eth_getTransactionReceipt
T+20607ms: eth_getCode
T+20607ms: eth_getTransactionByHash
T+20607ms: eth_getBalance
T+20760ms: eth_blockNumber
T+20781ms: eth_getBlockByNumber
T+27250ms: eth_unsubscribe
T+27270ms: eth_unsubscribe
T+27281ms: eth_unsubscribe
```

**Comment by davidmurdoch** [comment]
This issue should be fixed in the latest beta! https://github.com/trufflesuite/ganache/releases/tag/v2.0.2-beta.0
