### ISSUE TITLE
System Error when running Ganache 2.0.1 on Ubuntu 18.04.2 LTS

### ISSUE THREAD

**Issue by rviano96** [trufflesuite/ganache#1280]
PLATFORM: Ubuntu 18.04.2 LTS
MEMORY: 7,6 GiB
PROCESSOR: Intel Core i7-8750H CPU @ 2.20Ghz x 12
GRAPHICS: GeForce GTX 1052/PCIe/SSE2
GNOME: 3.28.2
OS Type: 64-bit
Disk: 51.9 GB (SSD)

GANACHE VERSION: 2.0.1

EXCEPTION:
```
Error: Unknown error.
    at LocalStorage.setItem (/node_modules/node-localstorage/LocalStorage.js:186:15)
    at JsonStorage.setToStorage (/src/main/types/json/JsonStorage.js:72:20)
    at JsonStorage.setAll (/src/main/types/json/JsonStorage.js:84:12)
    at WorkspaceSettings.setAll (/src/main/types/settings/Settings.js:84:21)
    at WorkspaceSettings.bootstrap (/src/main/types/settings/Settings.js:122:12)
    at Workspace.bootstrap (/src/main/types/workspaces/Workspace.js:79:21)
    at WorkspaceManager.bootstrap (/src/main/types/workspaces/WorkspaceManager.js:65:28)
    at EventEmitter.<anonymous> (/src/main/main.js:439:24)
    at Generator.next (<anonymous>)
    at step (/src/main/main.js:71:191)
    at /src/main/main.js:71:361
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by davidmurdoch** [comment]
Thanks for opening the issue @rviano96. I believe this happens when the LocalStorage of the Electron instance Ganache usage has exceeded the quota we've allotted. Were there a lot of Contracts in the workspace that triggered this error?
