### ISSUE TITLE
System Error when running Ganache 2.0.1 on linux

### ISSUE THREAD

**Issue by batuhanozkan** [trufflesuite/ganache#1281]
PLATFORM: linux
GANACHE VERSION: 2.0.1

EXCEPTION:
```
Error: watch /src/common/redux/core/actions.js ENOSPC
    at exports._errnoException (util.js:1024:11)
    at FSWatcher.start (fs.js:1394:19)
    at Object.fs.watch (fs.js:1420:11)
    at Observable._Observable.Observable.create.subj [as _subscribe] (/node_modules/electron-compile/lib/pathwatcher-rx.js:29:34)
    at Observable._trySubscribe (/node_modules/rxjs/Observable.js:172:25)
    at Observable.subscribe (/node_modules/rxjs/Observable.js:160:93)
    at Observable.ConnectableObservable.connect (/node_modules/rxjs/observable/ConnectableObservable.js:41:18)
    at RefCountOperator.call (/node_modules/rxjs/operators/refCount.js:24:49)
    at Observable.subscribe (/node_modules/rxjs/Observable.js:157:22)
    at MapOperator.call (/node_modules/rxjs/operators/map.js:56:23)
```

APPLICATION LOG:
```
T+0ms: Starting server (version 2.0.1) with initial configuration: {"gasLimit":6721975,"gasPrice":20000000000,"hardfork":"petersburg","hostname":"127.0.0.1","port":7545,"network_id":5777,"default_balance_ether":100,"total_accounts":10,"unlocked_accounts":[],"locked":false,"vmErrorsOnRPCResponse":true,"verbose":false}
T+163ms: Ganache started successfully!
T+163ms: Waiting for requests...
T+197ms: eth_subscribe
T+210ms: eth_getLogs
T+226ms: eth_subscribe
```

**Comment by davidmurdoch** [comment]
Closing in favor of #579.
