### ISSUE TITLE
Decoding Error when running Ganache 2.0.2-beta.0 on darwin

### ISSUE THREAD

**Issue by ajaco56** [trufflesuite/ganache#1286]
PLATFORM: darwin
GANACHE VERSION: 2.0.2-beta.0

EXCEPTION:
```
UnknownBaseContractIdError: Cannot locate base contract ID 147$ of contract$ CryptoPoem (ID 779)
    at vars.concat.linearizedBaseContractsFromBase.map (/node_modules/truffle-decoder/dist/allocate/storage.js:158:19)
    at Array.map (native)
    at allocateContract (/node_modules/truffle-decoder/dist/allocate/storage.js:155:61)
    at Object.getStorageAllocations (/node_modules/truffle-decoder/dist/allocate/storage.js:29:23)
    at TruffleContractDecoder.<anonymous> (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:113:47)
    at Generator.next (<anonymous>)
    at fulfilled (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by ajaco56** [comment]
I am rather new to this , but really like to know what I ? did wrong

--AA

**Comment by nicholasjpaterno** [comment]
@ajaco56 Apologies for the late response.  This is a known issue in ganache and likely not a result of user error on your part.  We are a little backlogged at the moment but will try to address this asap!!  Closing this issue in favor of #1470 as it has the most information for us to reproduce the issue.
