### ISSUE TITLE
Decoding Error when running Ganache 2.0.2-beta.0 on darwin

### ISSUE THREAD

**Issue by ddalcero** [trufflesuite/ganache#1296]
I see this error on the detail page of any contract.

"There was an issue decoding your contract. Please file a GitHub Issue by clicking the button below."

PLATFORM: darwin
GANACHE VERSION: 2.0.2-beta.0

EXCEPTION:
```
UnknownBaseContractIdError: Cannot locate base contract ID 1734$ of contract$ XXXXXXX (ID 471)
    at vars.concat.linearizedBaseContractsFromBase.map (/node_modules/truffle-decoder/dist/allocate/storage.js:158:19)
    at Array.map (native)
    at allocateContract (/node_modules/truffle-decoder/dist/allocate/storage.js:155:61)
    at Object.getStorageAllocations (/node_modules/truffle-decoder/dist/allocate/storage.js:29:23)
    at TruffleContractDecoder.<anonymous> (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:113:47)
    at Generator.next (<anonymous>)
    at fulfilled (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by nicholasjpaterno** [comment]
Thanks for opening this issue!  Closing in favor of #1470.
