### ISSUE TITLE
System Error when running Ganache 2.0.1 on darwin

### ISSUE THREAD

**Issue by pblin** [trufflesuite/ganache#1305]
PLATFORM: darwin
GANACHE VERSION: 2.0.1

EXCEPTION:
```
Error: CONNECTION ERROR: Couldn't connect to node on WS.
    at Object.InvalidConnection (/node_modules/web3-core-helpers/src/errors.js:35:16)
    at WebsocketProvider._timeout (/node_modules/web3-providers-ws/src/index.js:249:48)
    at W3CWebSocket.connection.onclose (/node_modules/web3-providers-ws/src/index.js:149:15)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onClose (/node_modules/websocket/lib/W3CWebSocket.js:228:10)
    at WebSocketConnection.<anonymous> (/node_modules/websocket/lib/W3CWebSocket.js:201:17)
    at emitTwo (events.js:125:13)
    at WebSocketConnection.emit (events.js:213:7)
    at WebSocketConnection.handleSocketClose (/node_modules/websocket/lib/WebSocketConnection.js:387:14)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at TCP._handle.close [as _onclose] (net.js:549:12)
```

APPLICATION LOG:
```
T+35030535ms: eth_blockNumber
T+35049797ms: eth_blockNumber
T+35050410ms: eth_blockNumber
T+35069825ms: eth_blockNumber
T+35070421ms: eth_blockNumber
T+35089857ms: eth_blockNumber
T+35089857ms: eth_blockNumber
T+35111070ms: eth_blockNumber
T+35111070ms: eth_blockNumber
T+35130105ms: eth_blockNumber
T+35130105ms: eth_blockNumber
T+35150115ms: eth_blockNumber
T+35150822ms: eth_blockNumber
T+35170165ms: eth_blockNumber
T+35170674ms: eth_blockNumber
T+35190205ms: eth_blockNumber
T+35190205ms: eth_blockNumber
T+35210222ms: eth_blockNumber
T+35210753ms: eth_blockNumber
T+35230814ms: eth_blockNumber
T+35230814ms: eth_blockNumber
T+35250268ms: eth_blockNumber
T+35250820ms: eth_blockNumber
T+35270306ms: eth_blockNumber
T+35270306ms: eth_blockNumber
T+35290312ms: eth_blockNumber
T+35291024ms: eth_blockNumber
T+35310356ms: eth_blockNumber
T+35310356ms: eth_blockNumber
T+35330369ms: eth_blockNumber
T+35331019ms: eth_blockNumber
T+35350879ms: eth_blockNumber
T+35351331ms: eth_blockNumber
T+35370448ms: eth_blockNumber
T+35370448ms: eth_blockNumber
T+35390464ms: eth_blockNumber
T+35390946ms: eth_blockNumber
T+35410499ms: eth_blockNumber
T+35410991ms: eth_blockNumber
T+35430531ms: eth_blockNumber
T+35431052ms: eth_blockNumber
T+35450559ms: eth_blockNumber
T+35451182ms: eth_blockNumber
T+35470871ms: eth_blockNumber
T+35471298ms: eth_blockNumber
T+35490615ms: eth_blockNumber
T+35491126ms: eth_blockNumber
T+35510649ms: eth_blockNumber
T+35511144ms: eth_blockNumber
T+35530715ms: eth_blockNumber
T+35530715ms: eth_blockNumber
T+35550751ms: eth_blockNumber
T+35551284ms: eth_blockNumber
T+35570777ms: eth_blockNumber
T+35571251ms: eth_blockNumber
T+35590915ms: eth_blockNumber
T+35591383ms: eth_blockNumber
T+35610830ms: eth_blockNumber
T+35611362ms: eth_blockNumber
T+35630857ms: eth_blockNumber
T+35631360ms: eth_blockNumber
T+35650886ms: eth_blockNumber
T+35651375ms: eth_blockNumber
T+35670914ms: eth_blockNumber
T+35671564ms: eth_blockNumber
T+35691039ms: eth_blockNumber
T+35692958ms: eth_blockNumber
T+35711080ms: eth_blockNumber
T+35711080ms: eth_blockNumber
T+35731102ms: eth_blockNumber
T+35731641ms: eth_blockNumber
T+35751130ms: eth_blockNumber
T+35751698ms: eth_blockNumber
T+35771156ms: eth_blockNumber
T+35771719ms: eth_blockNumber
T+35791214ms: eth_blockNumber
T+35792048ms: eth_blockNumber
T+35811232ms: eth_blockNumber
T+35811777ms: eth_blockNumber
T+35831274ms: eth_blockNumber
T+35831863ms: eth_blockNumber
T+35851323ms: eth_blockNumber
T+35851323ms: eth_blockNumber
T+35871335ms: eth_blockNumber
T+35871933ms: eth_blockNumber
T+35891374ms: eth_blockNumber
T+35891374ms: eth_blockNumber
T+35911386ms: eth_blockNumber
T+35911959ms: eth_blockNumber
T+35931424ms: eth_blockNumber
T+35931424ms: eth_blockNumber
T+35951473ms: eth_blockNumber
T+35951473ms: eth_blockNumber
T+35971473ms: eth_blockNumber
T+35971473ms: eth_blockNumber
T+35991523ms: eth_blockNumber
T+35991523ms: eth_blockNumber
T+35993180ms: net_version
T+35994628ms: eth_accounts
T+35996296ms: eth_getBlockByNumber
T+35996296ms: eth_getCode
T+35997493ms: eth_getBlockByNumber
T+35997493ms: eth_getCode
T+35997493ms: eth_getBlockByNumber
T+35998329ms: eth_accounts
T+35999095ms: eth_getBlockByNumber
T+35999095ms: eth_getBlockByNumber
T+35999095ms: eth_getBlockByNumber
T+35999623ms: eth_estimateGas
T+36162601ms: eth_getBlockByNumber
T+36162601ms: eth_blockNumber
T+36162601ms: eth_sendTransaction
T+36162601ms: eth_getTransactionReceipt
T+36162601ms: eth_getCode
T+36162601ms: eth_getTransactionByHash
T+36162601ms: eth_getBlockByNumber
T+36162601ms: eth_getBalance
T+36162601ms: eth_getBlockByNumber
T+36162601ms: eth_getBlockByNumber
T+36162601ms: eth_sendTransaction
T+36163275ms: eth_getTransactionReceipt
T+36163275ms: eth_getBlockByNumber
T+36163275ms: eth_accounts
T+36163756ms: eth_getBlockByNumber
T+36163756ms: eth_getBlockByNumber
T+36163756ms: eth_getBlockByNumber
T+36163756ms: eth_estimateGas
T+36164228ms: eth_getBlockByNumber
T+36164228ms: eth_blockNumber
T+36164228ms: eth_sendTransaction
T+36164733ms: eth_getTransactionReceipt
T+36165232ms: eth_getCode
T+36165232ms: eth_getTransactionByHash
T+36165232ms: eth_getBlockByNumber
T+36165232ms: eth_getBalance
T+36165751ms: eth_getBlockByNumber
T+36165751ms: eth_getBlockByNumber
T+36165751ms: eth_sendTransaction
T+36166255ms: eth_getTransactionReceipt
T+36166764ms: eth_blockNumber
T+36166764ms: eth_blockNumber
T+36167256ms: eth_getLogs
T+36167256ms: eth_getLogs
T+36167797ms: eth_unsubscribe
T+36168285ms: eth_unsubscribe
T+36181542ms: eth_blockNumber
T+36181542ms: eth_blockNumber
T+36202291ms: eth_blockNumber
T+36202835ms: eth_blockNumber
T+36228511ms: eth_blockNumber
T+36228511ms: eth_blockNumber
T+36247427ms: eth_unsubscribe
```

**Comment by davidmurdoch** [comment]
Closing in favor of #1497.
