### ISSUE TITLE
System Error when running Ganache 2.0.0 on win32

### ISSUE THREAD

**Issue by nicoviola** [trufflesuite/ganache#1312]
PLATFORM: win32
GANACHE VERSION: 2.0.0

EXCEPTION:
```
Error: connection not open
    at WebsocketProvider.send (C:\Program Files\Ganache\resources\app.asar\node_modules\web3-providers-ws\src\index.js:276:18)
    at Timeout._onTimeout (C:\Program Files\Ganache\resources\app.asar\node_modules\web3-providers-ws\src\index.js:261:19)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
    at listOnTimeoutNT (timers.js:340:26)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: Starting server (version 2.0.0) with initial configuration: {"gasLimit":6721975,"gasPrice":20000000000,"hardfork":"petersburg","hostname":"0.0.0.0","port":8545,"network_id":4447,"default_balance_ether":100,"total_accounts":10,"unlocked_accounts":[],"locked":false,"vmErrorsOnRPCResponse":true,"verbose":false,"db_path":"C:\\Users\\nicol\\AppData\\Roaming\\Ganache\\workspaces\\laughable-value\\chaindata"}
T+75ms: Ganache started successfully!
T+75ms: Waiting for requests...
```

**Comment by davidmurdoch** [comment]
Closing in favor of #1238.
