### ISSUE TITLE
System Error when running Ganache 2.0.2-beta.0 on linux

### ISSUE THREAD

**Issue by FabioBonfiglio** [trufflesuite/ganache#1321]
Trying to deploy a smart contract from an aragon app deployment script (`npx aragon run`) :
![image](https://user-images.githubusercontent.com/48284219/59158344-51f36800-8ab9-11e9-8603-b649977e8296.png)

This bug message raised in Ganache :

PLATFORM: linux
GANACHE VERSION: 2.0.2-beta.0

EXCEPTION:
```
Error: watch /home/path/to/my/build ENOSPC
    at exports._errnoException (util.js:1024:11)
    at FSWatcher.start (fs.js:1394:19)
    at Object.fs.watch (fs.js:1420:11)
    at ProjectFsWatcher.startWatchingDirs (/src/truffle-integration/projectFsWatcher.js:92:26)
    at FSWatcher.fs.watch (/src/truffle-integration/projectFsWatcher.js:104:18)
    at emitTwo (events.js:125:13)
    at FSWatcher.emit (events.js:213:7)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1376:12)
```

APPLICATION LOG:
```
T+0ms: Starting server (version 2.0.2-beta.0) with initial configuration: {"gasLimit":6721975,"gasPrice":20000000000,"hardfork":"petersburg","hostname":"127.0.0.1","port":7545,"network_id":5777,"default_balance_ether":100,"total_accounts":10,"unlocked_accounts":[],"locked":false,"vmErrorsOnRPCResponse":true,"verbose":false,"db_path":"/home/myhome/.config/Ganache/workspaces/myworkspace/chaindata"}
T+66ms: Ganache started successfully!
T+66ms: Waiting for requests...
T+92ms: eth_subscribe
T+92ms: eth_getLogs
T+92ms: eth_subscribe
T+103182ms: eth_accounts
T+106968ms: eth_call
T+107018ms: eth_call
T+294056ms: eth_subscribe
T+294059ms: eth_subscribe
T+294066ms: eth_accounts
T+294432ms: eth_getBalance
T+303315ms: eth_getBlockByNumber
T+320960ms: eth_accounts
T+323635ms: eth_call
T+323655ms: eth_call
T+328436ms: eth_unsubscribe
T+328438ms: eth_unsubscribe
T+328460ms: eth_unsubscribe
T+328463ms: eth_unsubscribe
T+328465ms: eth_unsubscribe
T+328472ms: eth_unsubscribe
```

Then after that, **all my existing ganache workspaces were broken** and raised the same message at loading.
Had to restart a new workspace, but same bug raised again.

Here is a copy of `truffle.js` config file :
```js
const homedir = require('homedir')
const path = require('path')

const HDWalletProvider = require('truffle-hdwallet-provider')
const HDWalletProviderPrivkey = require('truffle-hdwallet-provider-privkey')

const DEFAULT_MNEMONIC = 'explain tackle mirror kit van hammer degree position ginger unfair soup bonus'

const defaultRPC = (network) =>
  `https://${network}.infura.io`

const configFilePath = (filename) =>
  path.join(homedir(), `.aragon/${filename}`)

const mnemonic = () => {
  try {
    return require(configFilePath('mnemonic.json')).mnemonic
  } catch (e) {
    return DEFAULT_MNEMONIC
  }
}

const settingsForNetwork = (network) => {
  try {
    return require(configFilePath(`${network}_key.json`))
  } catch (e) {
    return { }
  }
}

// Lazily loaded provider
const providerForNetwork = (network) => (
  () => {
    let { rpc, keys } = settingsForNetwork(network)
    rpc = rpc || defaultRPC(network)

    if (!keys || keys.length == 0) {
      return new HDWalletProvider(mnemonic(), rpc)
    }

    return new HDWalletProviderPrivkey(keys, rpc)
  }
)
module.exports = {
  networks: {
    development: {
      host: 'localhost',
      port: 7545,
      network_id: '5777'
    },
    mainnet: {
      network_id: 1,
      provider: providerForNetwork('mainnet')
    },
    rinkeby: {
      network_id: 4,
      provider: providerForNetwork('rinkeby')
    }
  }
}

```

**Comment by davidmurdoch** [comment]
Closing in favor of #579.
