### ISSUE TITLE
Decoding Error when running Ganache 2.0.3-beta.0 on linux

### ISSUE THREAD

**Issue by khssnv** [trufflesuite/ganache#1345]
Hello. I tested my dapp with Ganache several times, but in another try I've find an issue with contract storage displaying. Please find details below.

PLATFORM: linux
GANACHE VERSION: 2.0.3-beta.0

EXCEPTION:
```
UnknownBaseContractIdError: Cannot locate base contract ID 763$ of contract$ Game (ID 462)
    at vars.concat.linearizedBaseContractsFromBase.map (/node_modules/truffle-decoder/dist/allocate/storage.js:158:19)
    at Array.map (native)
    at allocateContract (/node_modules/truffle-decoder/dist/allocate/storage.js:155:61)
    at Object.getStorageAllocations (/node_modules/truffle-decoder/dist/allocate/storage.js:29:23)
    at TruffleContractDecoder.<anonymous> (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:113:47)
    at Generator.next (<anonymous>)
    at fulfilled (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by nicholasjpaterno** [comment]
Thanks for opening this issue!  Closing in favor of #1470.
