### ISSUE TITLE
System Error when running Ganache 2.0.2 on win32

### ISSUE THREAD

**Issue by gleb-urvanov** [trufflesuite/ganache#1346]
PLATFORM: win32
GANACHE VERSION: 2.0.2

EXCEPTION:
```
Error: CONNECTION ERROR: Couldn't connect to node on WS.
    at Object.InvalidConnection (C:\Program Files\WindowsApps\Ganache_2.0.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\web3-core-helpers\src\errors.js:35:16)
    at WebsocketProvider._timeout (C:\Program Files\WindowsApps\Ganache_2.0.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\web3-providers-ws\src\index.js:249:48)
    at W3CWebSocket.connection.onclose (C:\Program Files\WindowsApps\Ganache_2.0.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\web3-providers-ws\src\index.js:149:15)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (C:\Program Files\WindowsApps\Ganache_2.0.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\yaeti\lib\EventTarget.js:107:17)
    at W3CWebSocket.onClose (C:\Program Files\WindowsApps\Ganache_2.0.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\websocket\lib\W3CWebSocket.js:228:10)
    at WebSocketConnection.<anonymous> (C:\Program Files\WindowsApps\Ganache_2.0.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\websocket\lib\W3CWebSocket.js:201:17)
    at emitTwo (events.js:125:13)
    at WebSocketConnection.emit (events.js:213:7)
    at WebSocketConnection.handleSocketClose (C:\Program Files\WindowsApps\Ganache_2.0.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\websocket\lib\WebSocketConnection.js:387:14)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at TCP._handle.close [as _onclose] (net.js:549:12)
```

APPLICATION LOG:
```
T+0ms: eth_unsubscribe
T+0ms: eth_unsubscribe
T+1ms: eth_unsubscribe
T+1ms: eth_unsubscribe
T+1ms: eth_unsubscribe
T+9487ms: Starting server (version 2.0.2) with initial configuration: {"gasLimit":6721975,"gasPrice":20000000000,"hardfork":"petersburg","default_balance_ether":100,"hostname":"127.0.0.1","locked":false,"network_id":5777,"port":7545,"total_accounts":10,"unlocked_accounts":[],"verbose":false,"vmErrorsOnRPCResponse":true}
T+16412ms: Ganache started successfully!
T+16412ms: Waiting for requests...
T+17023ms: eth_getCode
T+17596ms: eth_subscribe
T+17596ms: eth_getLogs
T+17596ms: eth_subscribe
T+18174ms: eth_getCode
T+141141ms: net_version
T+141836ms: eth_accounts
T+314220ms: eth_getBlockByNumber
T+314220ms: eth_getCode
T+314220ms: eth_getBlockByNumber
T+314220ms: eth_getCode
T+314220ms: eth_getBlockByNumber
T+314220ms: eth_accounts
T+314220ms: eth_getBlockByNumber
T+314220ms: eth_getBlockByNumber
T+314220ms: eth_getBlockByNumber
T+314220ms: eth_estimateGas
T+314220ms: eth_getBlockByNumber
T+314220ms: eth_blockNumber
T+314220ms: eth_sendTransaction
T+314220ms:   Transaction: 0xe9336a5c91e90081e1abd3e928b65838924a4c9cfbc1f00c89e91132003f16e7
T+314220ms:   Contract created: 0x3a32732c4fe01cfe9da3abd6339cfbf538b13fc0
T+314220ms:   Gas usage: 269543
T+314220ms:   Block Number: 1
T+314220ms:   Block Time: Mon Jul 08 2019 15:07:22 GMT+0200 (Central Europe Daylight Time)
T+314220ms: eth_getTransactionReceipt
T+314220ms: eth_getCode
T+314220ms: eth_getTransactionByHash
T+314220ms: eth_getBlockByNumber
T+314220ms: eth_getBalance
T+314220ms: eth_getBlockByNumber
T+314220ms: eth_getBlockByNumber
T+314220ms: eth_sendTransaction
T+314220ms:   Transaction: 0x9a2c6aed972449feafaacfa5db4d55d9cbea00cd84675ef7febb6590d273a936
T+314220ms:   Gas usage: 41981
T+314220ms:   Block Number: 2
T+314220ms:   Block Time: Mon Jul 08 2019 15:07:22 GMT+0200 (Central Europe Daylight Time)
T+314220ms: eth_getTransactionReceipt
T+314220ms: eth_getBlockByNumber
T+314220ms: eth_accounts
T+318270ms: net_version
T+318270ms: eth_getBlockByNumber
T+318270ms: eth_getBlockByNumber
T+318270ms: net_version
T+318270ms: eth_getBlockByNumber
T+318270ms: eth_estimateGas
T+318270ms: net_version
T+318270ms: eth_blockNumber
T+318270ms: eth_getBlockByNumber
T+318270ms: eth_sendTransaction
T+318270ms:   Transaction: 0x9ce47975de4b9fd7d6ed97f91822c00fc1356467c01379fb89e533f9b8e204f6
T+318270ms:   Contract created: 0xcf6adb23774ccff52a5a3d377b72db8ec362833d
T+318270ms:   Gas usage: 3565597
T+318270ms:   Block Number: 3
T+318270ms:   Block Time: Mon Jul 08 2019 15:07:24 GMT+0200 (Central Europe Daylight Time)
T+318270ms: eth_getTransactionReceipt
T+318270ms: eth_getCode
T+318270ms: eth_getTransactionByHash
T+318270ms: eth_getBlockByNumber
T+318270ms: eth_getBalance
T+318270ms: net_version
T+318270ms: eth_getBlockByNumber
T+318270ms: eth_getBlockByNumber
T+318270ms: eth_getBlockByNumber
T+318270ms: eth_getBlockByNumber
T+318270ms: eth_sendTransaction
T+318270ms: net_version
T+318270ms:   Transaction: 0xfa29d377e535496d3f83f34de422ac043141a63e6c25b553f216bf428875a844
T+318270ms:   Gas usage: 26981
T+318270ms:   Block Number: 4
T+318270ms:   Block Time: Mon Jul 08 2019 15:07:24 GMT+0200 (Central Europe Daylight Time)
T+318270ms: eth_getTransactionReceipt
T+318270ms: eth_getBlockByNumber
T+334924ms: eth_unsubscribe
T+334924ms: eth_unsubscribe
T+445976ms: net_version
T+445976ms: eth_accounts
T+450023ms: eth_getBlockByNumber
T+450023ms: eth_getCode
T+450023ms: eth_getBlockByNumber
T+450023ms: eth_call
T+477713ms: net_version
T+477713ms: eth_accounts
T+477713ms: eth_getBlockByNumber
T+477713ms: eth_getCode
T+477713ms: eth_getBlockByNumber
T+477713ms: eth_call
T+477713ms: eth_getBlockByNumber
T+477713ms: eth_getCode
T+477713ms: eth_getBlockByNumber
T+477713ms: eth_call
T+477713ms: eth_getBlockByNumber
T+477713ms: eth_accounts
T+658411ms: eth_unsubscribe
```

**Comment by davidmurdoch** [comment]
Closing in favor of #1497.
