### ISSUE TITLE
Decoding Error when running Ganache 2.0.3 on darwin

### ISSUE THREAD

**Issue by le4ker** [trufflesuite/ganache#1350]
PLATFORM: darwin
GANACHE VERSION: 2.0.3

EXCEPTION:
```
UnknownBaseContractIdError: Cannot locate base contract ID 205$ of contract$ CryptoDeities (ID 37)
    at vars.concat.linearizedBaseContractsFromBase.map (/node_modules/truffle-decoder/dist/allocate/storage.js:158:19)
    at Array.map (native)
    at allocateContract (/node_modules/truffle-decoder/dist/allocate/storage.js:155:61)
    at Object.getStorageAllocations (/node_modules/truffle-decoder/dist/allocate/storage.js:29:23)
    at TruffleContractDecoder.<anonymous> (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:113:47)
    at Generator.next (<anonymous>)
    at fulfilled (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by nicholasjpaterno** [comment]
Thanks for opening this issue!  Closing in favor of #1470.
