### ISSUE TITLE
System Error when running Ganache 2.0.3 on win32

### ISSUE THREAD

**Issue by renjithpta** [trufflesuite/ganache#1356]
PLATFORM: win32
GANACHE VERSION: 2.0.3

EXCEPTION:
```
Error: connection not open
    at WebsocketProvider.send (D:\GanacheUI\resources\app.asar\node_modules\web3-providers-ws\src\index.js:276:18)
    at Timeout._onTimeout (D:\GanacheUI\resources\app.asar\node_modules\web3-providers-ws\src\index.js:261:19)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
    at listOnTimeoutNT (timers.js:340:26)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: Starting server (version 2.0.3) with initial configuration: {"gasLimit":6721975,"gasPrice":20000000000,"hardfork":"petersburg","hostname":"127.0.0.1","port":7545,"network_id":5777,"default_balance_ether":100,"total_accounts":10,"unlocked_accounts":[],"locked":false,"vmErrorsOnRPCResponse":true,"verbose":false}
T+1320ms: Ganache started successfully!
T+1320ms: Waiting for requests...
```

**Comment by davidmurdoch** [comment]
Closing in favor of #1238.
