### ISSUE TITLE
System Error when running Ganache 1.0.0 on win32

### ISSUE THREAD

**Issue by wighawag** [trufflesuite/ganache#136]
Just started ganache (had used it before, few weeks ago) and got an error, asking me to submit to github, here is the details :

PLATFORM: win32
GANACHE VERSION: 1.0.0

EXCEPTION:
Error: Lost heartbeat from server process!
    at Timeout.setInterval [as _onTimeout] (/src/Services/Chain.js:86:30)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

**Comment by benjamincburns** [comment]
Thanks for reporting this. This should be fixed as of our latest release, v1.0.2, which is out just now!
