### ISSUE TITLE
System Error when running Ganache 2.0.2-beta.0 on win32

### ISSUE THREAD

**Issue by hasanShaddad** [trufflesuite/ganache#1360]
PLATFORM: win32
GANACHE VERSION: 2.0.2-beta.0

EXCEPTION:
```
TypeError: Cannot read property 'stack' of undefined
    at EventEmitter.<anonymous> (C:\Program Files\Ganache\resources\app.asar\src\main\main.js:259:30)
    at Generator.throw (<anonymous>)
    at step (C:\Program Files\Ganache\resources\app.asar\src\main\main.js:71:191)
    at C:\Program Files\Ganache\resources\app.asar\src\main\main.js:71:402
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

APPLICATION LOG:
```
T+0ms: eth_getTransactionReceipt
T+26ms: eth_getTransactionReceipt
T+26ms: eth_getTransactionReceipt
T+55ms: eth_getTransactionReceipt
T+82ms: eth_getTransactionReceipt
T+109ms: eth_getTransactionReceipt
T+3050ms: eth_getTransactionReceipt
T+3079ms: eth_getTransactionReceipt
T+3100ms: eth_getTransactionReceipt
T+3127ms: eth_getTransactionReceipt
T+3155ms: eth_getTransactionReceipt
T+3183ms: eth_getTransactionReceipt
T+6003ms: eth_getTransactionReceipt
T+6032ms: eth_getTransactionReceipt
T+6065ms: eth_getTransactionReceipt
T+6091ms: eth_getTransactionReceipt
T+6119ms: eth_getTransactionReceipt
T+6148ms: eth_getTransactionReceipt
T+8785ms: eth_getTransactionCount
T+8833ms: eth_sendRawTransaction
T+10970ms:   Transaction: 0x0ca45d687452ba1dff2c18439cb739c3f098ee359ffbf3effd6f914954c02789
T+10970ms:   Gas usage: 48125
T+10970ms:   Block Number: 83
T+10970ms:   Block Time: Tue Jul 16 2019 20:50:29 GMT+0200 (Egypt Standard Time)
T+10970ms:   Runtime Error: revert
T+10995ms: eth_getBlockByNumber
T+11056ms: eth_getTransactionReceipt
T+11090ms: eth_getTransactionReceipt
T+11160ms: eth_getTransactionReceipt
T+11188ms: eth_getTransactionReceipt
T+11246ms: eth_getTransactionReceipt
T+11274ms: eth_getTransactionReceipt
T+12009ms: eth_getTransactionReceipt
T+12052ms: eth_getTransactionReceipt
T+12081ms: eth_getTransactionReceipt
T+12109ms: eth_getTransactionReceipt
T+12134ms: eth_getTransactionReceipt
T+12163ms: eth_getTransactionReceipt
T+15009ms: eth_getTransactionReceipt
T+15053ms: eth_getTransactionReceipt
T+15075ms: eth_getTransactionReceipt
T+15100ms: eth_getTransactionReceipt
T+15126ms: eth_getTransactionReceipt
T+15152ms: eth_getTransactionReceipt
T+15902ms: net_version
T+15926ms: eth_getCode
T+18012ms: eth_getTransactionReceipt
T+18050ms: eth_getTransactionReceipt
T+18078ms: eth_getTransactionReceipt
T+18106ms: eth_getTransactionReceipt
T+18132ms: eth_getTransactionReceipt
T+18157ms: eth_getTransactionReceipt
T+21003ms: eth_getTransactionReceipt
T+21033ms: eth_getTransactionReceipt
T+21070ms: eth_getTransactionReceipt
T+21097ms: eth_getTransactionReceipt
T+21124ms: eth_getTransactionReceipt
T+21150ms: eth_getTransactionReceipt
T+24005ms: eth_getTransactionReceipt
T+24040ms: eth_getTransactionReceipt
T+24067ms: eth_getTransactionReceipt
T+24095ms: eth_getTransactionReceipt
T+24120ms: eth_getTransactionReceipt
T+24145ms: eth_getTransactionReceipt
T+27008ms: eth_getTransactionReceipt
T+27052ms: eth_getTransactionReceipt
T+27079ms: eth_getTransactionReceipt
T+27105ms: eth_getTransactionReceipt
T+27129ms: eth_getTransactionReceipt
T+27154ms: eth_getTransactionReceipt
T+30011ms: eth_getTransactionReceipt
T+30047ms: eth_getTransactionReceipt
T+30077ms: eth_getTransactionReceipt
T+30104ms: eth_getTransactionReceipt
T+30129ms: eth_getTransactionReceipt
T+30155ms: eth_getTransactionReceipt
T+33006ms: eth_getTransactionReceipt
T+33045ms: eth_getTransactionReceipt
T+33086ms: eth_getTransactionReceipt
T+33112ms: eth_getTransactionReceipt
T+33136ms: eth_getTransactionReceipt
T+33161ms: eth_getTransactionReceipt
T+36026ms: eth_getTransactionReceipt
T+36067ms: eth_getTransactionReceipt
T+36112ms: eth_getTransactionReceipt
T+36148ms: eth_getTransactionReceipt
T+36186ms: eth_getTransactionReceipt
T+36213ms: eth_getTransactionReceipt
T+39004ms: eth_getTransactionReceipt
T+39031ms: eth_getTransactionReceipt
T+39062ms: eth_getTransactionReceipt
T+39088ms: eth_getTransactionReceipt
T+39114ms: eth_getTransactionReceipt
T+39139ms: eth_getTransactionReceipt
T+42014ms: eth_getTransactionReceipt
T+42053ms: eth_getTransactionReceipt
T+42082ms: eth_getTransactionReceipt
T+42108ms: eth_getTransactionReceipt
T+42135ms: eth_getTransactionReceipt
T+42161ms: eth_getTransactionReceipt
```

**Comment by aeselcuk** [comment]
Hi, 

Solution provided on this issue yet? I am having the same issue...
