### ISSUE TITLE
System Error when running Ganache 2.0.1 on win32

### ISSUE THREAD

**Issue by andreataglia** [trufflesuite/ganache#1363]
PLATFORM: win32
GANACHE VERSION: 2.0.1

EXCEPTION:
```
Error: CONNECTION ERROR: Couldn't connect to node on WS.
    at Object.InvalidConnection (C:\Program Files\WindowsApps\Ganache_2.0.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\web3-core-helpers\src\errors.js:35:16)
    at WebsocketProvider._timeout (C:\Program Files\WindowsApps\Ganache_2.0.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\web3-providers-ws\src\index.js:249:48)
    at W3CWebSocket.connection.onclose (C:\Program Files\WindowsApps\Ganache_2.0.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\web3-providers-ws\src\index.js:149:15)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (C:\Program Files\WindowsApps\Ganache_2.0.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\yaeti\lib\EventTarget.js:107:17)
    at W3CWebSocket.onClose (C:\Program Files\WindowsApps\Ganache_2.0.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\websocket\lib\W3CWebSocket.js:228:10)
    at WebSocketConnection.<anonymous> (C:\Program Files\WindowsApps\Ganache_2.0.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\websocket\lib\W3CWebSocket.js:201:17)
    at emitTwo (events.js:125:13)
    at WebSocketConnection.emit (events.js:213:7)
    at WebSocketConnection.handleSocketClose (C:\Program Files\WindowsApps\Ganache_2.0.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\websocket\lib\WebSocketConnection.js:387:14)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at TCP._handle.close [as _onclose] (net.js:549:12)
```

APPLICATION LOG:
```
T+100128ms: eth_blockNumber
T+120144ms: eth_blockNumber
T+140159ms: eth_blockNumber
T+160173ms: eth_blockNumber
T+161965ms: eth_getCode
T+162032ms: eth_getTransactionByHash
T+162077ms: eth_getTransactionByHash
T+162935ms: eth_getTransactionByHash
T+163215ms: eth_getTransactionByHash
T+163281ms: eth_getTransactionByHash
T+163330ms: eth_getTransactionByHash
T+165246ms: eth_getTransactionByHash
T+165300ms: eth_getTransactionByHash
T+165362ms: eth_getTransactionByHash
T+165410ms: eth_getTransactionByHash
T+165499ms: eth_getTransactionCount
T+165528ms: eth_getTransactionByHash
T+165614ms: eth_getTransactionByHash
T+165684ms: eth_getTransactionByHash
T+165729ms: eth_getTransactionByHash
T+165817ms: eth_getTransactionByHash
T+165862ms: eth_getTransactionByHash
T+180189ms: eth_blockNumber
T+200205ms: eth_blockNumber
T+216290ms: eth_call
T+216292ms: eth_call
T+216320ms: eth_getLogs
T+216335ms: eth_call
T+216336ms: eth_call
T+216379ms: eth_getLogs
T+216386ms: eth_call
T+216433ms: eth_getLogs
T+220220ms: eth_blockNumber
T+240236ms: eth_blockNumber
T+260252ms: eth_blockNumber
T+280267ms: eth_blockNumber
T+300283ms: eth_blockNumber
T+317696ms: eth_unsubscribe
T+320297ms: eth_blockNumber
T+325155ms: eth_subscribe
T+325445ms: eth_call
T+325448ms: eth_call
T+325480ms: eth_getLogs
T+325492ms: eth_call
T+325498ms: eth_call
T+325544ms: eth_getLogs
T+325554ms: eth_call
T+325583ms: eth_getLogs
T+337142ms: eth_call
T+337143ms: eth_call
T+337169ms: eth_getLogs
T+337190ms: eth_call
T+337201ms: eth_call
T+337264ms: eth_getLogs
T+337274ms: eth_call
T+337297ms: eth_getLogs
T+340314ms: eth_blockNumber
T+347066ms: eth_getCode
T+347134ms: eth_getTransactionByHash
T+347184ms: eth_getTransactionByHash
T+348004ms: eth_getTransactionByHash
T+348228ms: eth_getTransactionByHash
T+348298ms: eth_getTransactionByHash
T+348343ms: eth_getTransactionByHash
T+349817ms: eth_getTransactionByHash
T+349863ms: eth_getTransactionByHash
T+349938ms: eth_getTransactionByHash
T+349983ms: eth_getTransactionByHash
T+350065ms: eth_getTransactionCount
T+350095ms: eth_getTransactionByHash
T+350183ms: eth_getTransactionByHash
T+350253ms: eth_getTransactionByHash
T+350304ms: eth_getTransactionByHash
T+350392ms: eth_getTransactionByHash
T+350448ms: eth_getTransactionByHash
T+360333ms: eth_blockNumber
T+367920ms: eth_call
T+367921ms: eth_call
T+367947ms: eth_getLogs
T+367965ms: eth_call
T+367971ms: eth_call
T+368007ms: eth_getLogs
T+368009ms: eth_call
T+368036ms: eth_getLogs
T+380350ms: eth_blockNumber
T+400365ms: eth_blockNumber
T+420380ms: eth_blockNumber
T+440395ms: eth_blockNumber
T+460410ms: eth_blockNumber
T+480428ms: eth_blockNumber
T+500442ms: eth_blockNumber
T+520456ms: eth_blockNumber
T+533970ms: eth_getTransactionCount
T+540473ms: eth_blockNumber
T+546836ms: eth_blockNumber
T+546838ms: net_version
T+546863ms: eth_getBlockByNumber
T+546865ms: eth_getBlockByNumber
T+546869ms: eth_getBalance
T+546874ms: eth_getBalance
T+546914ms: eth_getTransactionCount
T+546973ms: eth_getTransactionByHash
T+547019ms: eth_getTransactionByHash
T+549984ms: eth_getTransactionCount
T+555362ms: eth_gasPrice
T+555422ms: eth_getCode
T+555493ms: eth_getTransactionByHash
T+555496ms: eth_estimateGas
T+555549ms: eth_getTransactionByHash
T+556656ms: eth_getTransactionByHash
T+556709ms: eth_getTransactionByHash
T+556776ms: eth_getTransactionByHash
T+556840ms: eth_getTransactionByHash
T+557909ms: eth_getTransactionByHash
T+557961ms: eth_getTransactionByHash
T+558023ms: eth_getTransactionByHash
T+558069ms: eth_getTransactionByHash
T+558168ms: eth_getTransactionByHash
T+558216ms: eth_sendRawTransaction
T+558263ms: eth_getTransactionByHash
T+558406ms:   Transaction: 0x99cace5c40012c94d04f2fd369f0ebab60c35551d4c227a7d126c2d06180835c
T+558406ms:   Gas usage: 366596
T+558406ms:   Block Number: 8
T+558406ms:   Block Time: Fri Jul 19 2019 15:53:03 GMT+0200 (Central Europe Daylight Time)
T+558418ms: eth_getBlockByNumber
T+558421ms: eth_unsubscribe
T+558423ms: eth_unsubscribe
T+558425ms: eth_unsubscribe
T+558425ms: eth_unsubscribe
T+558425ms: eth_unsubscribe
T+558427ms: eth_unsubscribe
```

**Comment by davidmurdoch** [comment]
Closing in favor of #1497.
