### ISSUE TITLE
System Error when running Ganache 2.1.0 on darwin

### ISSUE THREAD

**Issue by CQBinh** [trufflesuite/ganache#1366]
PLATFORM: darwin
GANACHE VERSION: 2.1.0

EXCEPTION:
```
TypeError: Cannot read property 'address' of null
    at ProjectsWatcher.handleBlock (/src/truffle-integration/projectsWatcher.js:208:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

APPLICATION LOG:
```
T+0ms: eth_unsubscribe
T+0ms: eth_unsubscribe
T+2ms: eth_unsubscribe
T+2ms: eth_unsubscribe
T+2ms: eth_unsubscribe
T+1612ms: Starting server (version 2.1.0) with initial configuration: {"gasLimit":6721975,"gasPrice":20000000000,"hardfork":"petersburg","db_path":"/Users/binh/Library/Application Support/Ganache/workspaces/100-accc/chaindata","default_balance_ether":100,"hostname":"127.0.0.1","locked":false,"network_id":5777,"port":7545,"total_accounts":100,"unlocked_accounts":[],"verbose":false,"vmErrorsOnRPCResponse":true}
T+1679ms: Ganache started successfully!
T+1679ms: Waiting for requests...
T+2496ms: eth_getCode
T+2560ms: eth_subscribe
T+2560ms: eth_getLogs
T+2631ms: eth_subscribe
T+2702ms: eth_getCode
T+2769ms: eth_getCode
T+2830ms: eth_getCode
T+2897ms: eth_getCode
T+375514ms: net_version
T+375575ms: eth_accounts
T+526180ms: eth_getBlockByNumber
T+526243ms: eth_accounts
T+528945ms: eth_getBlockByNumber
T+529003ms: eth_sendTransaction
T+643147ms:   Transaction: 0x61557143a19f512c67a3496a83d0ab870e1f0ca52d54902bf3b9b1b74781953f
T+643147ms:   Gas usage: 44382
T+643147ms:   Block Number: 6368
T+643147ms:   Block Time: Wed Jul 24 2019 17:29:17 GMT+0700 (+07)
T+643147ms:   Runtime Error: revert
T+643147ms:   Revert reason: Already an citizen
T+643195ms: eth_getBlockByNumber
T+643242ms: eth_call
T+643410ms: eth_getBlockByNumber
T+643460ms: eth_sendTransaction
T+643503ms:   Transaction: 0xfa5d9ba950c5bf313b890319b6a01c4e3536d5d0076f62569f27f16a50bd312e
T+643503ms:   Gas usage: 32847
T+643503ms:   Block Number: 6369
T+643503ms:   Block Time: Wed Jul 24 2019 17:29:29 GMT+0700 (+07)
T+643503ms:   Runtime Error: revert
T+643503ms:   Revert reason: Invalid username
T+643550ms: eth_getBlockByNumber
T+643598ms: eth_call
T+643734ms: eth_getBlockByNumber
T+643786ms: eth_sendTransaction
T+643831ms:   Transaction: 0x10c836dcccd2671181b4aefbcfa57f0bc032a7919f99c42b1cf81a0154579d59
T+643831ms:   Gas usage: 185628
T+643831ms:   Block Number: 6370
T+643831ms:   Block Time: Wed Jul 24 2019 17:29:37 GMT+0700 (+07)
T+643880ms: eth_getBlockByNumber
T+643928ms: eth_getTransactionReceipt
T+644021ms: eth_getBlockByNumber
T+644071ms: eth_sendTransaction
T+644120ms:   Transaction: 0xf53e50290f12c8a34a1a2a806eb839e4fd15d9acf355dbe630dfcdf1447904a8
T+644120ms:   Gas usage: 239027
T+644120ms:   Block Number: 6371
T+644120ms:   Block Time: Wed Jul 24 2019 17:29:58 GMT+0700 (+07)
T+644168ms: eth_getBlockByNumber
T+644210ms: eth_getTransactionReceipt
T+1532268ms: net_version
T+1532315ms: eth_getCode
T+1532368ms: eth_getBlockByNumber
T+1532420ms: eth_getBalance
T+1532471ms: eth_getTransactionCount
T+1532544ms: eth_getStorageAt
T+1532597ms: eth_getStorageAt
T+1532648ms: eth_getStorageAt
T+1532699ms: eth_getStorageAt
T+1532749ms: eth_getStorageAt
T+1532793ms: eth_getStorageAt
T+1532842ms: eth_getStorageAt
T+1532890ms: eth_getStorageAt
T+1532938ms: eth_getStorageAt
T+1532986ms: eth_getStorageAt
T+1533028ms: eth_getStorageAt
T+1533076ms: eth_getStorageAt
T+1533123ms: eth_getStorageAt
T+1533171ms: eth_getStorageAt
T+1533214ms: eth_getStorageAt
T+1533264ms: eth_getStorageAt
T+1533315ms: eth_getStorageAt
T+1533365ms: eth_getCode
T+1533417ms: eth_getStorageAt
T+1533460ms: eth_getCode
T+1533510ms: eth_getStorageAt
T+1533562ms: eth_getCode
T+1533613ms: eth_getStorageAt
T+1533656ms: eth_getStorageAt
T+1533706ms: eth_getStorageAt
T+1533756ms: eth_getStorageAt
T+1533808ms: eth_getStorageAt
T+1533861ms: eth_getStorageAt
T+1533905ms: eth_getStorageAt
T+2195008ms: net_version
T+2195243ms: eth_accounts
T+2195505ms: eth_getBlockByNumber
T+2195734ms: eth_accounts
T+2195885ms: net_version
T+2196087ms: eth_getBlockByNumber
T+2196235ms: eth_getBlockByNumber
T+2196386ms: net_version
T+2196585ms: eth_getBlockByNumber
T+2196741ms: eth_estimateGas
T+2196939ms: net_version
T+2197103ms: eth_blockNumber
T+2197255ms: eth_getBlockByNumber
T+2197454ms: eth_sendTransaction
T+2266950ms:   Transaction: 0xebeb9969251a41dd303d6813bb43d9abbaf8d64cd9cca9af2278ecadbfd66e32
T+2266950ms:   Contract created: 0xa4df44be6560927c902d78ee94b1ebe03d0ff70b
T+2266950ms:   Gas usage: 224195
T+2266950ms:   Block Number: 6372
T+2266950ms:   Block Time: Wed Jul 24 2019 17:57:03 GMT+0700 (+07)
T+2267175ms: eth_getBlockByNumber
T+2267338ms: eth_getTransactionReceipt
T+2267733ms: eth_unsubscribe
T+2267733ms: eth_unsubscribe
T+2267933ms: eth_unsubscribe
T+2268096ms: eth_unsubscribe
T+2268096ms: eth_unsubscribe
```

**Comment by davidmurdoch** [comment]
Closing in favor of #1227.
