### ISSUE TITLE
System Error when running Ganache 1.0.1 on linux

### ISSUE THREAD

**Issue by iinstances** [trufflesuite/ganache#137]
PLATFORM: linux
GANACHE VERSION: 1.0.1

I was inspecting elements and I got this exception.

EXCEPTION:
Error: Lost heartbeat from server process!
    at Timeout.setInterval [as _onTimeout] (/src/Services/Chain.js:86:30)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
    at Menu.popup (/tmp/.mount_ganachF5RNMX/app/resources/electron.asar/browser/api/menu.js:180:8)
    at callFunction (/tmp/.mount_ganachF5RNMX/app/resources/electron.asar/browser/rpc-server.js:249:18)
    at EventEmitter.<anonymous> (/tmp/.mount_ganachF5RNMX/app/resources/electron.asar/browser/rpc-server.js:357:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/tmp/.mount_ganachF5RNMX/app/resources/electron.asar/browser/api/web-contents.js:256:37)

I forced the shutdown of the app and when I started it again it shown only the initial window and got stuck there.

The only way I could solve the problem was restarting my laptop.

**Comment by benjamincburns** [comment]
Thanks for reporting this. This should be fixed as of our latest release, v1.0.2, which is out just now!
