### ISSUE TITLE
System Error when running Ganache 2.1.0 on linux

### ISSUE THREAD

**Issue by ExperimentsWithCode** [trufflesuite/ganache#1371]
I just unboxed truffle drizzle box with `npx truffle unbox drizzle`. I then downloaded the Ganache GUI from [here](https://www.trufflesuite.com/ganache). I can create a new workspace but cannot add a project. When adding the truffle drizzle box I get the following error

PLATFORM: linux Pop OS 18.10 (64 bit)
GANACHE VERSION: 2.1.0

EXCEPTION:
```
Error: watch ~/FRT/truffle-config.js ENOSPC
    at exports._errnoException (util.js:1024:11)
    at FSWatcher.start (fs.js:1394:19)
    at Object.fs.watch (fs.js:1420:11)
    at ProjectFsWatcher.start (/src/truffle-integration/projectFsWatcher.js:40:29)
    at new ProjectFsWatcher (/src/truffle-integration/projectFsWatcher.js:25:10)
    at ProjectsWatcher.add (/src/truffle-integration/projectsWatcher.js:130:23)
    at process.<anonymous> (/src/truffle-integration/index.js:59:34)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by ExperimentsWithCode** [comment]
Turned out to just need a restart. Was running into this issue:

[Error: ENOSPC: System limit for number of file watchers reached, watch ... #11406](https://github.com/gatsbyjs/gatsby/issues/11406)
