### ISSUE TITLE
System Error when running Ganache 2.1.0 on win32

### ISSUE THREAD

**Issue by Donaldhan** [trufflesuite/ganache#1384]
PLATFORM: win32
GANACHE VERSION: 2.1.0

EXCEPTION:
```
Error: EPERM: operation not permitted, rename 'C:\Users\hanshaoqing\AppData\Roaming\Ganache\workspaces\healthy-selection\Settings.1912013628' -> 'C:\Users\hanshaoqing\AppData\Roaming\Ganache\workspaces\healthy-selection\Settings'
    at Object.fs.renameSync (fs.js:772:18)
    at writeFileSync (C:\Program Files\WindowsApps\Ganache_2.1.0.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\write-file-atomic\index.js:124:8)
    at LocalStorage.setItem (C:\Program Files\WindowsApps\Ganache_2.1.0.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\node-localstorage\LocalStorage.js:188:7)
    at JsonStorage.setToStorage (C:\Program Files\WindowsApps\Ganache_2.1.0.0_x64__zh355ej5cj694\app\resources\app.asar\src\main\types\json\JsonStorage.js:72:20)
    at JsonStorage.set (C:\Program Files\WindowsApps\Ganache_2.1.0.0_x64__zh355ej5cj694\app\resources\app.asar\src\main\types\json\JsonStorage.js:78:12)
    at WorkspaceSettings.set (C:\Program Files\WindowsApps\Ganache_2.1.0.0_x64__zh355ej5cj694\app\resources\app.asar\src\main\types\settings\Settings.js:89:21)
    at Workspace.saveAs (C:\Program Files\WindowsApps\Ganache_2.1.0.0_x64__zh355ej5cj694\app\resources\app.asar\src\main\types\workspaces\Workspace.js:90:21)
    at EventEmitter.<anonymous> (C:\Program Files\WindowsApps\Ganache_2.1.0.0_x64__zh355ej5cj694\app\resources\app.asar\src\main\main.js:532:24)
    at Generator.next (<anonymous>)
    at step (C:\Program Files\WindowsApps\Ganache_2.1.0.0_x64__zh355ej5cj694\app\resources\app.asar\src\main\main.js:71:191)
    at C:\Program Files\WindowsApps\Ganache_2.1.0.0_x64__zh355ej5cj694\app\resources\app.asar\src\main\main.js:71:361
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by wbt** [comment]
This seems to be the same issue as reported in v2.1.1 on [#1466](https://github.com/trufflesuite/ganache/issues/1466).
