### ISSUE TITLE
System Error when running Ganache 1.2.2 on darwin

### ISSUE THREAD

**Issue by njwest** [trufflesuite/ganache#1385]
PLATFORM: darwin
GANACHE VERSION: 1.2.2

EXCEPTION:
```
Error: ENOENT: no such file or directory, mkdir '/Users/nick/Desktop/appname/logs'
    at Object.fs.mkdirSync (fs.js:891:18)
    at Object.module.exports.generateLogFilePath (/src/chain/logging.js:68:8)
    at /src/chain/chain.js:54:17
    at stopServer (/src/chain/chain.js:41:5)
    at startServer (/src/chain/chain.js:46:3)
    at process.<anonymous> (/src/chain/chain.js:158:7)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:768:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: The Log Directory '/Users/nick/Desktop/appname/logs' doesn't exist; attempting to create it now
```

**Comment by davidmurdoch** [comment]
Closing in favor of #1300.
