### ISSUE TITLE
System Error when running Ganache 2.1.0 on darwin

### ISSUE THREAD

**Issue by alessandroponzo** [trufflesuite/ganache#1388]
Got this crash error, maybe related to  gas estimation by metamask + remiz
PLATFORM: darwin
GANACHE VERSION: 2.1.0

EXCEPTION:
```
TypeError: Cannot read property 'pop' of undefined
    at CheckpointTrie.Trie._updateNode (/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:360:23)
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:107:16
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:461:14
    at processNode (/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:471:23)
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:516:13
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:180:7
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/util.js:75:7
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:52:16
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:269:32
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:44:16
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/util.js:71:7
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:157:9
    at /node_modules/ganache-core/lib/database/levelupobjectadapter.js:41:16
    at /node_modules/ganache-core/node_modules/level-sublevel/shell.js:101:15
    at /node_modules/ganache-core/node_modules/level-sublevel/nut.js:121:19
    at /node_modules/ganache-core/node_modules/encoding-down/index.js:51:21
    at /node_modules/ganache-core/node_modules/cachedown/index.js:58:21
    at ReadFileContext.callback (/node_modules/ganache-core/lib/database/filedown.js:26:14)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
```

APPLICATION LOG:
```
T+0ms: eth_unsubscribe
T+0ms: eth_unsubscribe
T+447ms: eth_unsubscribe
T+5011ms: Starting server (version 2.1.0) with initial configuration: {"gasLimit":6721975,"gasPrice":20000000000,"hardfork":"petersburg","hostname":"127.0.0.1","port":7545,"network_id":5777,"default_balance_ether":100,"total_accounts":10,"unlocked_accounts":[],"locked":false,"vmErrorsOnRPCResponse":true,"verbose":false,"db_path":"/Users/white/Library/Application Support/Ganache/workspaces/quaint-driving/chaindata"}
T+5186ms: Ganache started successfully!
T+5186ms: Waiting for requests...
T+5206ms: eth_subscribe
T+5208ms: eth_getLogs
T+5211ms: eth_subscribe
T+14321ms: eth_blockNumber
T+15347ms: net_version
T+15350ms: net_version
T+22879ms: net_version
T+24997ms: net_version
T+30010ms: net_version
T+34358ms: eth_blockNumber
T+34997ms: net_version
T+37630ms: net_version
T+37704ms: eth_estimateGas
T+38269ms: eth_unsubscribe
T+38269ms: eth_unsubscribe
T+38274ms: eth_unsubscribe
T+38274ms: eth_unsubscribe
T+38274ms: eth_unsubscribe
```

**Comment by wbt** [comment]
I don't think this is related to gas estimation, as I got the same error on the same line just on starting up Ganache immediately after selecting the Quickstart workspace. (Notes at [#1320](https://github.com/trufflesuite/ganache/issues/1320)).
