### ISSUE TITLE
System Error when running Ganache 2.1.0 on darwin

### ISSUE THREAD

**Issue by jaxmef** [trufflesuite/ganache#1390]
The bug occurred when calling `etherBalance()`:
```
function etherBalance() public view onlyManager returns (uint256) {
	return address(this).balance;
}

modifier onlyManager {
	require(isManager(msg.sender));
	_;
}

function isManager(address _address) public view returns (bool) {
	return _address == manager;
}	
```

PLATFORM: darwin
GANACHE VERSION: 2.1.0

EXCEPTION:
```
Error: CONNECTION ERROR: Couldn't connect to node on WS.
    at Object.InvalidConnection (/node_modules/web3-core-helpers/src/errors.js:35:16)
    at WebsocketProvider._timeout (/node_modules/web3-providers-ws/src/index.js:249:48)
    at W3CWebSocket.connection.onclose (/node_modules/web3-providers-ws/src/index.js:149:15)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onClose (/node_modules/websocket/lib/W3CWebSocket.js:228:10)
    at WebSocketConnection.<anonymous> (/node_modules/websocket/lib/W3CWebSocket.js:201:17)
    at emitTwo (events.js:125:13)
    at WebSocketConnection.emit (events.js:213:7)
    at WebSocketConnection.handleSocketClose (/node_modules/websocket/lib/WebSocketConnection.js:387:14)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at TCP._handle.close [as _onclose] (net.js:549:12)
```

APPLICATION LOG:
```
T+8293ms:   Transaction: 0x44a7966662ce87588fb4d034386dd383b2a01f02e3924c4ad84292bcffd92434
T+8293ms:   Contract created: 0xaba7902442c5739c6f0c182691d48d63d06a212e
T+8293ms:   Gas usage: 830470
T+8293ms:   Block Number: 65
T+8293ms:   Block Time: Thu Aug 15 2019 12:56:48 GMT+0300 (EEST)
T+8296ms: eth_getCode
T+8298ms: eth_getBlockByNumber
T+8300ms: eth_getTransactionCount
T+8301ms: eth_gasPrice
T+8303ms: eth_getCode
T+8304ms: eth_estimateGas
T+8306ms: eth_sendRawTransaction
T+8307ms:   Transaction: 0x0cfec4234215291d29e577928919ea744b2c4a0167563f778880c04959b9a3a9
T+8307ms:   Gas usage: 41908
T+8307ms:   Block Number: 66
T+8309ms:   Block Time: Thu Aug 15 2019 12:56:49 GMT+0300 (EEST)
T+8311ms: eth_getTransactionReceipt
T+8312ms: eth_getBlockByNumber
T+8314ms: eth_getTransactionCount
T+8315ms: net_version
T+8317ms: eth_sendRawTransaction
T+8319ms:   Transaction: 0xa6f8b3578cb66503d473b3e013ee86c48f1a3e45d6d70506c9351d7d767f1e06
T+8319ms:   Gas usage: 23573
T+8319ms:   Block Number: 67
T+8319ms:   Block Time: Thu Aug 15 2019 12:56:49 GMT+0300 (EEST)
T+8321ms: eth_getBlockByNumber
T+8324ms: eth_getTransactionCount
T+8327ms: eth_gasPrice
T+8329ms: eth_getCode
T+8331ms: eth_estimateGas
T+8333ms: eth_sendRawTransaction
T+8335ms:   Transaction: 0x542120b8c4a0a3c92652d58bb6a0a932f66b16bc3ff4e9ed7cd5c5e4e6520841
T+8335ms:   Gas usage: 28043
T+8335ms:   Block Number: 68
T+8337ms:   Block Time: Thu Aug 15 2019 12:56:49 GMT+0300 (EEST)
T+8340ms: eth_getTransactionCount
T+8342ms: eth_getBlockByNumber
T+8344ms: net_version
T+8346ms: eth_sendRawTransaction
T+8347ms:   Transaction: 0xcfd9fd40e4aed350ba7adf26f21baef4aa2b770f2d53cf953b0ce5f6e509f8f7
T+8347ms:   Gas usage: 21558
T+8347ms:   Block Number: 69
T+8347ms:   Block Time: Thu Aug 15 2019 12:56:49 GMT+0300 (EEST)
T+8347ms:   Runtime Error: revert
T+8348ms: eth_getBlockByNumber
T+8350ms: eth_getTransactionCount
T+8351ms: eth_gasPrice
T+8352ms: eth_getCode
T+8354ms: eth_estimateGas
T+8356ms: eth_sendRawTransaction
T+8357ms:   Transaction: 0x488a31eac84f8586547378fe9bcf4abfe71df93c347bf6c0edcee80cb816931f
T+8357ms:   Gas usage: 28070
T+8357ms:   Block Number: 70
T+8359ms:   Block Time: Thu Aug 15 2019 12:56:49 GMT+0300 (EEST)
T+8360ms: eth_getBlockByNumber
T+8361ms: eth_getTransactionCount
T+8363ms: net_version
T+8364ms: eth_sendRawTransaction
T+8365ms:   Transaction: 0xfc4e38d3bcbe020baec5c503c5c79fa2e38514d4a3349b2e34e7294ba016d3c3
T+8365ms:   Gas usage: 23573
T+8365ms:   Block Number: 71
T+8365ms:   Block Time: Thu Aug 15 2019 12:56:49 GMT+0300 (EEST)
T+8367ms: eth_getBlockByNumber
T+8368ms: eth_getTransactionCount
T+8370ms: eth_gasPrice
T+8372ms: eth_estimateGas
T+8374ms: eth_sendRawTransaction
T+8376ms:   Transaction: 0x1a8ddc65658cba9d9a38f2c110d8e6ceabc96a0b02815b4e0d75c3d4e4dd9e10
T+8376ms:   Contract created: 0x7153ccd1a20bbb2f6dc89c1024de368326ec6b4f
T+8376ms:   Gas usage: 224195
T+8376ms:   Block Number: 72
T+8378ms:   Block Time: Thu Aug 15 2019 12:56:49 GMT+0300 (EEST)
T+8381ms: eth_getBlockByNumber
T+8382ms: eth_getCode
T+8385ms: eth_getTransactionCount
T+8386ms: eth_gasPrice
T+8389ms: eth_estimateGas
T+8391ms: eth_sendRawTransaction
T+8393ms:   Transaction: 0x5d6b9b0465a00495d235409b0b1fd6b3f3890ac7237dc0b53cf5ffd5fd36c3bc
T+8393ms:   Contract created: 0x3ba7c2578b59e0e1ccfee9a20d92f043c0e0b3e6
T+8393ms:   Gas usage: 830470
T+8393ms:   Block Number: 73
T+8393ms:   Block Time: Thu Aug 15 2019 12:56:49 GMT+0300 (EEST)
T+8395ms: eth_getBlockByNumber
T+8396ms: eth_getCode
T+8398ms: eth_getTransactionCount
T+8399ms: eth_gasPrice
T+8401ms: eth_getCode
T+8402ms: eth_estimateGas
T+8403ms: eth_sendRawTransaction
T+8405ms:   Transaction: 0x347d4af9b0ce23eba349301386d7d157ada80e14739dc589d409f34ffaa553bf
T+8405ms:   Gas usage: 41908
T+8405ms:   Block Number: 74
T+8405ms:   Block Time: Thu Aug 15 2019 12:56:49 GMT+0300 (EEST)
T+8406ms: eth_getTransactionReceipt
T+8407ms: eth_getBlockByNumber
T+8409ms: eth_getTransactionCount
T+8410ms: net_version
T+8411ms: eth_sendRawTransaction
T+8412ms:   Transaction: 0x23a8858e64e58b6aa726e2a944626e0e0ab0c59a59defdce795fed3b69673f23
T+8412ms:   Gas usage: 23573
T+8412ms:   Block Number: 75
T+8412ms:   Block Time: Thu Aug 15 2019 12:56:49 GMT+0300 (EEST)
T+8414ms: eth_call
T+8416ms: eth_getBlockByNumber
T+8428ms: eth_unsubscribe
T+8428ms: eth_unsubscribe
T+8436ms: eth_unsubscribe
T+8441ms: eth_unsubscribe
T+8445ms: eth_unsubscribe
```

**Comment by jaxmef** [comment]
If I remove `onlyManager` modifier everything works well otherwise, it fails every time

**Comment by davidmurdoch** [comment]
Closing in favor of #1497.
