### ISSUE TITLE
Ganache GUI installation error

### ISSUE THREAD

**Issue by NithinTD** [trufflesuite/ganache#1391]
node version v12.8.0,npm version 6.10.2

I followed the below steps to install the ganache GUI but I got the error

    $mkdir ~/ganache
    $git clone https://github.com/trufflesuite/ganache.git
    $npm install
    $npm start

after running the npm start I got below error
error:
    > ganache@2.1.1-beta.0 start /home/nithin/ganache
    > electron-forge start

    ✔ Checking your system
    ✔ Locating Application

    An unhandled rejection has occurred inside Forge:
    Could not determine Electron version. Make sure that 'npm install' (or 'yarn') has been run before invoking electron-forge.
    Error: Could not determine Electron version. Make sure that 'npm install' (or 'yarn') has been run before invoking electron-forge.
    at /usr/lib/node_modules/electron-forge/dist/util/rebuild.js:26:13
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/usr/lib/node_modules/electron-forge/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/usr/lib/node_modules/electron-forge/node_modules/bluebird/js/release/generators.js:97:49)
    at /usr/lib/node_modules/electron-forge/node_modules/bluebird/js/release/generators.js:201:15
    at /usr/lib/node_modules/electron-forge/dist/util/rebuild.js:63:17
    at /usr/lib/node_modules/electron-forge/dist/api/start.js:105:33
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/usr/lib/node_modules/electron-forge/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/usr/lib/node_modules/electron-forge/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (/usr/lib/node_modules/electron-forge/node_modules/bluebird/js/release/promise.js:579:26)
    at Promise._settlePromise0 (/usr/lib/node_modules/electron-forge/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/usr/lib/node_modules/electron-forge/node_modules/bluebird/js/release/promise.js:699:18)
    at _drainQueueStep (/usr/lib/node_modules/electron-forge/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/usr/lib/node_modules/electron-forge/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/usr/lib/node_modules/electron-forge/node_modules/bluebird/js/release/async.js:147:5)
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! ganache@2.1.1-beta.0 start: `electron-forge start`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the ganache@2.1.1-beta.0 start script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/nithin/.npm/_logs/2019-08-14T11_24_08_546m start
error:
    > ganache@2.1.1-beta.0 start /home/nithin/ganache
    > electron-forge start

    ✔ Checking your system
    ✔ Locating Application

    An unhandled rejection has occurred inside Forge:
    Could not determine Electron version. Make sure that 'npm install' (or 'yarn') has been run before invoking electron-forge.
    Error: Could not determine Electron version. Make sure that 'npm install' (or 'yarn') has been run before invoking electron-forge.
    at /usr/lib/node_modules/electron-forge/dist/util/rebuild.js:26:13
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/usr/lib/node_modules/electron-forge/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/usr/lib/node_modules/electron-forge/node_modules/bluebird/js/release/generators.js:97:49)
    at /usr/lib/node_modules/electron-forge/node_modules/bluebird/js/release/generators.js:201:15
    at /usr/lib/node_modules/electron-forge/dist/util/rebuild.js:63:17
    at /usr/lib/node_modules/electron-forge/dist/api/start.js:105:33
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/usr/lib/node_modules/electron-forge/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/usr/lib/node_modules/electron-forge/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (/usr/lib/node_modules/electron-forge/node_modules/bluebird/js/release/promise.js:579:26)
    at Promise._settlePromise0 (/usr/lib/node_modules/electron-forge/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/usr/lib/node_modules/electron-forge/node_modules/bluebird/js/release/promise.js:699:18)
    at _drainQueueStep (/usr/lib/node_modules/electron-forge/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/usr/lib/node_modules/electron-forge/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/usr/lib/node_modules/electron-forge/node_modules/bluebird/js/release/async.js:147:5)
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! ganache@2.1.1-beta.0 start: `electron-forge start`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the ganache@2.1.1-beta.0 start script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/nithin/.npm/_logs/2019-08-14T11_24_08_546

**Comment by davidmurdoch** [comment]
Thanks for taking the time to open this issue!

Can you try again node v8.15+ and let me know if it works for you?
