### ISSUE TITLE
System Error when running Ganache 2.1.0 on darwin

### ISSUE THREAD

**Issue by Ma-chan** [trufflesuite/ganache#1393]
PLATFORM: darwin
GANACHE VERSION: 2.1.0

EXCEPTION:
```
TypeError: Cannot read property 'filter' of undefined
    at ProjectsWatcher.subscribeToEvents (/src/truffle-integration/projectsWatcher.js:118:37)
    at ProjectsWatcher.add (/src/truffle-integration/projectsWatcher.js:152:16)
    at process.<anonymous> (/src/truffle-integration/index.js:59:34)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by davidmurdoch** [comment]
This issue should now be handled properly in the latest beta, https://github.com/trufflesuite/ganache/releases/tag/v2.1.1-beta.3. Can you try it out and let me know if it works for you?
