### ISSUE TITLE
System Error when running Ganache 2.1.0 on darwin

### ISSUE THREAD

**Issue by tonybka** [trufflesuite/ganache#1399]
**Getting errors while running test cases with truffle test:**

PLATFORM: darwin
GANACHE VERSION: 2.1.0

EXCEPTION:
```
TypeError: Cannot read property 'transactions' of null
    at ProjectsWatcher.handleBlock (/src/truffle-integration/projectsWatcher.js:180:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

APPLICATION LOG:
```
T+210340ms:   Block Number: 203
T+210340ms:   Block Time: Wed Aug 21 2019 11:48:38 GMT+0700 (+07)
T+210340ms: eth_getBlockByNumber
T+210340ms: eth_getTransactionReceipt
T+210374ms: eth_getBlockByNumber
T+210374ms: net_version
T+210422ms: eth_sendTransaction
T+210423ms: eth_getBlockByNumber
T+210731ms:   Transaction: 0x6b12f3ff5b74b99c90e4cb0a065801bd82b0005f481520c203476262be10c46c
T+210731ms:   Gas usage: 951121
T+210731ms:   Block Number: 204
T+210731ms:   Block Time: Wed Aug 21 2019 11:48:38 GMT+0700 (+07)
T+210731ms: eth_getBlockByNumber
T+210731ms: eth_getTransactionReceipt
T+210731ms: eth_sendTransaction
T+210731ms: eth_getBlockByNumber
T+210732ms:   Transaction: 0xde252c62567ab32df841eae7517688082713f025fa943a8c40b1c12e435d1b2b
T+210732ms:   Gas usage: 45447
T+210732ms:   Block Number: 205
T+210732ms:   Block Time: Wed Aug 21 2019 11:48:38 GMT+0700 (+07)
T+210732ms: eth_getBlockByNumber
T+210733ms: eth_getTransactionReceipt
T+210733ms: eth_sendTransaction
T+210734ms: net_version
T+210827ms:   Transaction: 0xdd02c72ccf18f14833182fc9b228ea558c88cc762b84f74bf8c93703eda2a277
T+210827ms:   Gas usage: 116685
T+210827ms:   Block Number: 206
T+210827ms:   Block Time: Wed Aug 21 2019 11:48:38 GMT+0700 (+07)
T+210828ms: eth_getBlockByNumber
T+210828ms: eth_getTransactionReceipt
T+210875ms: eth_getBlockByNumber
T+210922ms: eth_getBlockByNumber
T+210922ms: eth_blockNumber
T+210969ms: eth_sendTransaction
T+210969ms: eth_call
T+210969ms: eth_sign
T+210969ms:   Transaction: 0xdc8e0aed081a025438e52b93deb460d9f0b3086596eba14a0c6a80984281190f
T+210969ms:   Gas usage: 45383
T+210969ms:   Block Number: 207
T+210969ms:   Block Time: Wed Aug 21 2019 11:48:38 GMT+0700 (+07)
T+210969ms: eth_getBlockByNumber
T+210969ms: eth_getTransactionReceipt
T+210969ms: eth_sign
T+210970ms: eth_getBlockByNumber
T+210970ms: net_version
T+210971ms: eth_sendTransaction
T+210971ms: eth_getBlockByNumber
T+211034ms:   Transaction: 0x101e232856775441699220d4a1423f36a481fdb49e575c3c8c361d7b5d20ddd7
T+211034ms:   Gas usage: 56004
T+211034ms:   Block Number: 208
T+211034ms:   Block Time: Wed Aug 21 2019 11:48:38 GMT+0700 (+07)
T+211034ms: eth_getBlockByNumber
T+211034ms: eth_getTransactionReceipt
T+211034ms: eth_sendTransaction
T+211081ms: evm_increaseTime
T+211081ms:   Transaction: 0x0db80f1dd1d66c4312a8f22825eb45e1a01eff21421ecdc0bf36f1989f98feac
T+211081ms:   Gas usage: 49913
T+211081ms:   Block Number: 209
T+211081ms:   Block Time: Wed Aug 21 2019 11:48:38 GMT+0700 (+07)
T+211081ms: eth_getBlockByNumber
T+211081ms: eth_getTransactionReceipt
T+211125ms: evm_mine
T+211125ms: net_version
T+211169ms: eth_getBlockByNumber
T+211169ms: eth_getBlockByNumber
T+211169ms: eth_getBlockByNumber
T+211169ms: eth_call
T+211169ms: eth_sendTransaction
T+211225ms: eth_getBlockByNumber
T+211225ms:   Transaction: 0x4089e18c111b9c5ca8409e6c8791c7f8bf02ced541c02049a47fe4f0860c9857
T+211225ms:   Gas usage: 30447
T+211225ms:   Block Number: 211
T+211225ms:   Block Time: Fri Sep 13 2019 11:48:39 GMT+0700 (+07)
T+211226ms: eth_getBlockByNumber
T+211227ms: eth_getTransactionReceipt
T+211275ms: eth_call
T+211275ms: net_version
T+211363ms: eth_getBlockByNumber
T+211363ms: eth_getBlockByNumber
T+211363ms: eth_getBlockByNumber
T+211363ms: eth_sendTransaction
T+211363ms: eth_getBlockByNumber
T+211363ms:   Transaction: 0xc7edc1ffa9b1b49a16e4e8abc2873a9e8863964faf4bc3ca1dbe9cf4e9ec9410
T+211363ms:   Gas usage: 30383
T+211363ms:   Block Number: 212
T+211363ms:   Block Time: Fri Sep 13 2019 11:48:39 GMT+0700 (+07)
T+211363ms: eth_getBlockByNumber
T+211363ms: eth_getTransactionReceipt
T+211363ms: eth_call
T+211364ms: eth_getBlockByNumber
T+211409ms: eth_blockNumber
T+211470ms: eth_sendTransaction
T+211470ms: eth_sign
T+211767ms:   Transaction: 0x79e565c20d30f8081d0f6f18191a513aaa586733a92d667a831b714a722ef520
T+211767ms:   Gas usage: 951121
T+211767ms:   Block Number: 213
T+211767ms:   Block Time: Fri Sep 13 2019 11:48:39 GMT+0700 (+07)
T+211767ms: eth_getBlockByNumber
T+211768ms: eth_getTransactionReceipt
T+211768ms: eth_sign
T+211769ms: eth_getBlockByNumber
T+211769ms: web3_clientVersion
T+211770ms: net_version
T+211827ms: eth_sendTransaction
T+211828ms: eth_getBlockByNumber
T+211864ms:   Transaction: 0xc01722e64c7bcb95396892aae67c52a4a8a8f2a8b82cf6d4119edfa32e016113
T+211864ms:   Gas usage: 36853
T+211864ms:   Block Number: 214
T+211864ms:   Block Time: Fri Sep 13 2019 11:48:39 GMT+0700 (+07)
T+211864ms:   Runtime Error: revert
T+211864ms:   Revert reason: LAT: Transfer request is not allowed
T+211864ms: eth_getBlockByNumber
T+211864ms: eth_call
T+211864ms: eth_sendTransaction
T+211939ms: evm_revert
T+211939ms:   Transaction: 0x132fa7553180259d6d58f90461577582ca7e59809a6cd8395ffd74f8abdc30d4
T+211939ms:   Gas usage: 49913
T+211939ms:   Block Number: 215
T+211939ms:   Block Time: Fri Sep 13 2019 11:48:39 GMT+0700 (+07)
T+211939ms: eth_getBlockByNumber
T+211939ms: eth_getTransactionReceipt
T+212369ms: evm_snapshot
T+212401ms: eth_unsubscribe
T+212407ms: eth_unsubscribe
T+212409ms: eth_unsubscribe
T+212409ms: eth_unsubscribe
T+212410ms: eth_unsubscribe
```

**Comment by tonybka** [comment]
Truffle v5.0.32 (core: 5.0.32)
Solidity - 0.5.2 (solc-js)
Node v11.10.0
Web3.js v1.2.1

**Comment by tonybka** [comment]
**Truffle version:**

Truffle v5.0.32 (core: 5.0.32)
Solidity - 0.5.2 (solc-js)
Node v11.10.0
Web3.js v1.2.1
