### ISSUE TITLE
System Error when running Ganache 1.0.1 on win32

### ISSUE THREAD

**Issue by mxmauro** [trufflesuite/ganache#140]
Hi, I just right-clicked an account and the inspect element menu was active when the crash happened.

PLATFORM: win32
GANACHE VERSION: 1.0.1

EXCEPTION:
Error: Lost heartbeat from server process!
    at Timeout.setInterval [as _onTimeout] (/src/Services/Chain.js:86:30)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
    at Menu.popup (C:/Program Files/WindowsApps/Ganache_1.0.1.0_x64__zh355ej5cj694/app/resources/electron.asar/browser/api/menu.js:180:8)
    at WebContents.<anonymous> (/src/main.js:174:9)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)

**Comment by benjamincburns** [comment]
Sorry you're having this issue, @mxmauro - unfortunately we're tracking this over on #83. Can you please catch up with the thread there?

**Comment by mxmauro** [comment]
No problem @benjamincburns. Just reported the issue when happened. If it happens again and have more info, I'll advise you. Kind regards.
