### ISSUE TITLE
System Error when running Ganache 2.1.0 on darwin

### ISSUE THREAD

**Issue by Neo-Wilson-01** [trufflesuite/ganache#1416]
PLATFORM: darwin
GANACHE VERSION: 2.1.0

EXCEPTION:
```
Error: CONNECTION ERROR: Couldn't connect to node on WS.
    at Object.InvalidConnection (/node_modules/web3-core-helpers/src/errors.js:35:16)
    at WebsocketProvider._timeout (/node_modules/web3-providers-ws/src/index.js:249:48)
    at W3CWebSocket.connection.onclose (/node_modules/web3-providers-ws/src/index.js:149:15)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onClose (/node_modules/websocket/lib/W3CWebSocket.js:228:10)
    at WebSocketConnection.<anonymous> (/node_modules/websocket/lib/W3CWebSocket.js:201:17)
    at emitTwo (events.js:125:13)
    at WebSocketConnection.emit (events.js:213:7)
    at WebSocketConnection.handleSocketClose (/node_modules/websocket/lib/WebSocketConnection.js:387:14)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at TCP._handle.close [as _onclose] (net.js:549:12)
```

APPLICATION LOG:
```
T+413930978ms: eth_getTransactionReceipt
T+413931009ms: eth_getTransactionReceipt
T+413931010ms: eth_getTransactionReceipt
T+413931044ms: eth_getTransactionReceipt
T+413931045ms: eth_getTransactionReceipt
T+413931047ms: eth_getTransactionReceipt
T+413931093ms: eth_getTransactionReceipt
T+413931095ms: eth_getTransactionReceipt
T+413931096ms: eth_getTransactionReceipt
T+413931142ms: eth_getTransactionReceipt
T+413931167ms: eth_getTransactionReceipt
T+413931168ms: eth_getTransactionReceipt
T+413931263ms: eth_getTransactionReceipt
T+413931282ms: eth_getTransactionReceipt
T+413931283ms: eth_getTransactionReceipt
T+413931394ms: eth_getTransactionReceipt
T+413931396ms: eth_getTransactionReceipt
T+413931432ms: eth_getTransactionReceipt
T+413931433ms: eth_getTransactionReceipt
T+413931433ms: eth_getTransactionReceipt
T+413931434ms: eth_getTransactionReceipt
T+413931512ms: eth_getTransactionReceipt
T+413931514ms: eth_getTransactionReceipt
T+413931514ms: eth_getTransactionReceipt
T+413931515ms: eth_getTransactionReceipt
T+413931548ms: eth_getTransactionReceipt
T+413931589ms: eth_getTransactionReceipt
T+413931589ms: eth_getTransactionReceipt
T+413931591ms: eth_getTransactionReceipt
T+413931591ms: eth_getTransactionReceipt
T+413931649ms: eth_getTransactionReceipt
T+413931650ms: eth_getTransactionReceipt
T+413931650ms: eth_getTransactionReceipt
T+413931651ms: eth_getTransactionReceipt
T+413931651ms: eth_getTransactionReceipt
T+413931681ms: eth_getTransactionReceipt
T+413931683ms: eth_getTransactionReceipt
T+413931715ms: eth_getTransactionReceipt
T+413931716ms: eth_getTransactionReceipt
T+413931716ms: eth_getTransactionReceipt
T+413931716ms: eth_getTransactionReceipt
T+413931767ms:   Transaction: 0x1f000c8a58473c67a402a1d21832bc39f81d9a76b281d7c6d10e9f9abd39c476
T+413931767ms:   Gas usage: 5189122
T+413931767ms:   Block Number: 2320
T+413931767ms:   Block Time: Tue Aug 27 2019 09:45:37 GMT+0800 (CST)
T+413931769ms: eth_getBlockByNumber
T+413931771ms: eth_getTransactionReceipt
T+413931772ms: eth_getTransactionReceipt
T+413931850ms: eth_getTransactionReceipt
T+413931852ms: eth_getTransactionReceipt
T+413931852ms: eth_getTransactionReceipt
T+413931879ms: eth_getTransactionReceipt
T+413931880ms: eth_getTransactionReceipt
T+413931916ms: eth_getTransactionReceipt
T+413931917ms: eth_getTransactionReceipt
T+413931917ms: eth_getTransactionReceipt
T+413931918ms: eth_getTransactionReceipt
T+413931964ms: eth_getTransactionReceipt
T+413931980ms: eth_getTransactionReceipt
T+413931981ms: eth_getTransactionReceipt
T+413932008ms: eth_getTransactionReceipt
T+413932008ms: eth_getTransactionReceipt
T+413932046ms: eth_getTransactionReceipt
T+413932048ms: eth_getTransactionReceipt
T+413932048ms: eth_getTransactionReceipt
T+413932096ms: eth_getTransactionReceipt
T+413932097ms: eth_getTransactionReceipt
T+413932098ms: eth_getTransactionReceipt
T+413932141ms: eth_getTransactionReceipt
T+413932173ms: eth_getTransactionReceipt
T+413932174ms: eth_getTransactionReceipt
T+413932269ms: eth_getTransactionReceipt
T+413932283ms: eth_getTransactionReceipt
T+413932284ms: eth_getTransactionReceipt
T+413932391ms: eth_getTransactionReceipt
T+413932392ms: eth_getTransactionReceipt
T+413932398ms: eth_getTransactionReceipt
T+413932432ms: eth_getTransactionReceipt
T+413932434ms: eth_getTransactionReceipt
T+413932434ms: eth_getTransactionReceipt
T+413932435ms: eth_getTransactionReceipt
T+413932515ms: eth_getTransactionReceipt
T+413932516ms: eth_getTransactionReceipt
T+413932517ms: eth_getTransactionReceipt
T+413932517ms: eth_getTransactionReceipt
T+413932549ms: eth_getTransactionReceipt
T+413932650ms: eth_getTransactionReceipt
T+413932650ms: eth_getTransactionReceipt
T+413932650ms: eth_getTransactionReceipt
T+413932650ms: eth_getTransactionReceipt
T+413932652ms: eth_getTransactionReceipt
T+413932653ms: eth_getTransactionReceipt
T+413932653ms: eth_getTransactionReceipt
T+413932654ms: eth_getTransactionReceipt
T+413932654ms: eth_getTransactionReceipt
T+413932686ms: eth_getTransactionReceipt
T+413932687ms: eth_getTransactionReceipt
T+413932717ms: eth_getTransactionReceipt
T+413932719ms: eth_getTransactionReceipt
T+413932719ms: eth_getTransactionReceipt
T+413932720ms: eth_getTransactionReceipt
T+413932758ms: eth_getTransactionReceipt
T+413932761ms: eth_getTransactionReceipt
T+413932854ms: eth_getTransactionReceipt
T+413932855ms: eth_getTransactionReceipt
T+413932856ms: eth_getTransactionReceipt
T+413932883ms: eth_getTransactionReceipt
T+413932883ms: eth_getTransactionReceipt
T+413932920ms: eth_getTransactionReceipt
T+413932921ms: eth_getTransactionReceipt
T+413932921ms: eth_getTransactionReceipt
T+413932922ms: eth_getTransactionReceipt
T+413932965ms: eth_getTransactionReceipt
T+413932985ms: eth_getTransactionReceipt
T+413933328ms: eth_unsubscribe
T+413935045ms: eth_unsubscribe
T+413935047ms: eth_unsubscribe
T+413935047ms: eth_unsubscribe
T+413935049ms: eth_unsubscribe
```

**Comment by davidmurdoch** [comment]
Closing in favor of #1497.
