### ISSUE TITLE
System Error when running Ganache 1.0.1 on win32

### ISSUE THREAD

**Issue by hrroga** [trufflesuite/ganache#144]
I tried deploying a contract on the local MyEtherWallet and this crash happened.

PLATFORM: win32
GANACHE VERSION: 1.0.1

EXCEPTION:
Error: Lost heartbeat from server process!
    at Timeout.setInterval [as _onTimeout] (/src/Services/Chain.js:86:30)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

**Comment by benjamincburns** [comment]
Sorry you're having this issue, @hrroga - unfortunately we're tracking this over on #83. Can you please catch up with the thread there?
