### ISSUE TITLE
System Error when running Ganache 2.1.1 on win32

### ISSUE THREAD

**Issue by oppenheimer5** [trufflesuite/ganache#1440]
PLATFORM: win32
GANACHE VERSION: 2.1.1

EXCEPTION:
```
Error: CONNECTION ERROR: Couldn't connect to node on WS.
    at Object.InvalidConnection (C:\Program Files\WindowsApps\Ganache_2.1.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\web3-core-helpers\src\errors.js:35:16)
    at WebsocketProvider._timeout (C:\Program Files\WindowsApps\Ganache_2.1.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\web3-providers-ws\src\index.js:255:48)
    at W3CWebSocket.connection.onclose (C:\Program Files\WindowsApps\Ganache_2.1.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\web3-providers-ws\src\index.js:155:15)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (C:\Program Files\WindowsApps\Ganache_2.1.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\yaeti\lib\EventTarget.js:107:17)
    at W3CWebSocket.onClose (C:\Program Files\WindowsApps\Ganache_2.1.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\websocket\lib\W3CWebSocket.js:228:10)
    at WebSocketConnection.<anonymous> (C:\Program Files\WindowsApps\Ganache_2.1.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\websocket\lib\W3CWebSocket.js:201:17)
    at emitTwo (events.js:125:13)
    at WebSocketConnection.emit (events.js:213:7)
    at WebSocketConnection.handleSocketClose (C:\Program Files\WindowsApps\Ganache_2.1.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\websocket\lib\WebSocketConnection.js:389:14)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at TCP._handle.close [as _onclose] (net.js:549:12)
```

APPLICATION LOG:
```
T+279686ms:   Gas usage: 47284
T+279686ms:   Block Number: 30
T+279686ms:   Block Time: Tue Sep 24 2019 04:30:59 GMT-0400 (Eastern Daylight Time)
T+279686ms: eth_getTransactionReceipt
T+279686ms: eth_getBlockByNumber
T+280757ms: eth_sendTransaction
T+280757ms:   Transaction: 0x6d0a06cf9840078963734d7dfe99efbdba39a0de0deb4eacbfdf5b3cbf7e2d2a
T+280757ms:   Gas usage: 47284
T+280757ms:   Block Number: 31
T+280757ms:   Block Time: Tue Sep 24 2019 04:30:59 GMT-0400 (Eastern Daylight Time)
T+280757ms: eth_getTransactionReceipt
T+280757ms: eth_getBlockByNumber
T+280757ms: eth_sendTransaction
T+280757ms:   Transaction: 0x3637c399939ee36e11bf519b8d8baa260b67a2fa908cad141baa47f9b611aa5e
T+280757ms:   Gas usage: 47284
T+280757ms:   Block Number: 32
T+280757ms:   Block Time: Tue Sep 24 2019 04:30:59 GMT-0400 (Eastern Daylight Time)
T+280757ms: eth_getTransactionReceipt
T+280757ms: eth_getBlockByNumber
T+280757ms: eth_sendTransaction
T+280757ms:   Transaction: 0xba094fb17af06f2bf9f8338884607bd4310727b49a89c3fdfc60690a2c944d22
T+280757ms:   Gas usage: 47284
T+280757ms:   Block Number: 33
T+280757ms:   Block Time: Tue Sep 24 2019 04:30:59 GMT-0400 (Eastern Daylight Time)
T+280757ms: eth_getTransactionReceipt
T+280757ms: eth_getBlockByNumber
T+280757ms: eth_getBlockByNumber
T+280757ms: eth_sendTransaction
T+280757ms:   Transaction: 0x6c4a231f2020917fc2ed66fdce2db511ff56650cd4157f1a0716c992f4feb465
T+280757ms:   Gas usage: 26927
T+280757ms:   Block Number: 34
T+280757ms:   Block Time: Tue Sep 24 2019 04:31:00 GMT-0400 (Eastern Daylight Time)
T+280757ms: eth_getTransactionReceipt
T+280757ms: eth_getBlockByNumber
T+280757ms: eth_accounts
T+281451ms: eth_getBlockByNumber
T+281451ms: eth_getBlockByNumber
T+281451ms: eth_getBlockByNumber
T+281451ms: eth_estimateGas
T+281451ms: eth_getBlockByNumber
T+281451ms: eth_blockNumber
T+281451ms: eth_sendTransaction
T+281451ms:   Transaction: 0x1bbf0746060d3a7e16bcdb428ff1780188e2e813d4f951a5b181d34601583975
T+281451ms:   Contract created: 0xbcbbd530ff8f146ee2f077a798f9fd8e6da35f9b
T+281451ms:   Gas usage: 629044
T+281451ms:   Block Number: 35
T+281451ms:   Block Time: Tue Sep 24 2019 04:31:01 GMT-0400 (Eastern Daylight Time)
T+281451ms: eth_getTransactionReceipt
T+281451ms: eth_getCode
T+281451ms: eth_getBlockByNumber
T+281451ms: eth_getBlockByNumber
T+281451ms: eth_getBlockByNumber
T+281451ms: eth_getBlockByNumber
T+281451ms: eth_getBlockByNumber
T+281451ms: eth_estimateGas
T+282329ms: eth_getBlockByNumber
T+282329ms: eth_blockNumber
T+282329ms: eth_sendTransaction
T+282329ms:   Transaction: 0x0bf0dfcc854bdc388e4506abd6c123338b954b887ccd056fc82a9721dc2e8f56
T+282329ms:   Contract created: 0x3c0d07169cf8782420ddf5761067ba665a79b165
T+282329ms:   Gas usage: 1858441
T+282329ms:   Block Number: 36
T+282329ms:   Block Time: Tue Sep 24 2019 04:31:02 GMT-0400 (Eastern Daylight Time)
T+282329ms: eth_getTransactionReceipt
T+282329ms: eth_getCode
T+282329ms: eth_getBlockByNumber
T+282329ms: eth_getBlockByNumber
T+282329ms: eth_getBlockByNumber
T+282329ms: eth_estimateGas
T+282329ms: eth_getBlockByNumber
T+282329ms: eth_blockNumber
T+282329ms: eth_sendTransaction
T+283008ms:   Transaction: 0x7555c0f0376427a7457a1cc811872159d7d90ca08eab51116b39be85812d79c1
T+283008ms:   Contract created: 0xde29eaba6032328b9e56a496d6f72b8e5f271a53
T+283008ms:   Gas usage: 2863730
T+283008ms:   Block Number: 37
T+283008ms:   Block Time: Tue Sep 24 2019 04:31:03 GMT-0400 (Eastern Daylight Time)
T+283008ms: eth_getTransactionReceipt
T+283008ms: eth_getCode
T+283008ms: eth_getBlockByNumber
T+283008ms: eth_getBlockByNumber
T+283008ms: eth_sendTransaction
T+283008ms:   Transaction: 0xf8898665be4b768793e1cd087a8ec72126734208a12736a3b9936e3336a9fce9
T+283008ms:   Gas usage: 26927
T+283008ms:   Block Number: 38
T+283008ms:   Block Time: Tue Sep 24 2019 04:31:04 GMT-0400 (Eastern Daylight Time)
T+283008ms: eth_getTransactionReceipt
```

**Comment by davidmurdoch** [comment]
Closing in favor of #1497.
