### ISSUE TITLE
Websocket connection not open

### ISSUE THREAD

**Issue by bguiz** [trufflesuite/ganache#1460]
This occurs when I try to create a new workspace, or use an existing one.

PLATFORM: linux
GANACHE VERSION: 2.0.3-beta.0

EXCEPTION:
```
Error: connection not open
    at WebsocketProvider.send (/node_modules/web3-providers-ws/src/index.js:282:18)
    at Timeout._onTimeout (/node_modules/web3-providers-ws/src/index.js:267:19)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
```

**Comment by davidmurdoch** [comment]
Closing in favor of #1238.
