### ISSUE TITLE
System Error when running Ganache 2.1.1 on win32

### ISSUE THREAD

**Issue by matthewvella90** [trufflesuite/ganache#1462]
PLATFORM: win32
GANACHE VERSION: 2.1.1

EXCEPTION:
```
Error: connection not open
    at WebsocketProvider.send (C:\Program Files\WindowsApps\Ganache_2.1.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\web3-providers-ws\src\index.js:282:18)
    at Timeout._onTimeout (C:\Program Files\WindowsApps\Ganache_2.1.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\web3-providers-ws\src\index.js:267:19)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
    at listOnTimeoutNT (timers.js:340:26)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: [33mYou can improve web3's peformance when running Node.js versions older than 10.5.0 by installing the (deprecated) scrypt package in your project[0m
T+637ms: Starting server (version 2.1.1) with initial configuration: {"gasLimit":6721975,"gasPrice":20000000000,"hardfork":"petersburg","hostname":"127.0.0.1","port":7545,"network_id":5777,"default_balance_ether":100,"total_accounts":10,"unlocked_accounts":[],"locked":false,"vmErrorsOnRPCResponse":true,"verbose":false}
T+2098ms: Ganache started successfully!
T+2098ms: Waiting for requests...
```

**Comment by davidmurdoch** [comment]
Closing in favor of #1238.
