### ISSUE TITLE
System Error when running Ganache 2.1.2 on darwin

### ISSUE THREAD

**Issue by noif** [trufflesuite/ganache#1493]
PLATFORM: darwin
GANACHE VERSION: 2.1.2

EXCEPTION:
```
Error: A file exists at the location '/Users/leixianting/Library/Application Support/Ganache/workspaces/ContractCache' when trying to create/open localStorage
    at LocalStorage._init (/node_modules/node-localstorage/LocalStorage.js:132:17)
    at new LocalStorage (/node_modules/node-localstorage/LocalStorage.js:121:12)
    at JsonStorage.setStorageDirectory (/src/main/types/json/JsonStorage.js:32:22)
    at new JsonStorage (/src/main/types/json/JsonStorage.js:25:10)
    at WorkspaceSettings.Settings (/src/main/types/settings/Settings.js:30:21)
    at new WorkspaceSettings (/src/main/types/settings/WorkspaceSettings.js:57:124)
    at workspaces._fsExtra2.default.readdirSync.filter.map.file (/src/main/types/workspaces/WorkspaceManager.js:45:26)
    at Array.map (native)
    at WorkspaceManager.enumerateWorkspaces (/src/main/types/workspaces/WorkspaceManager.js:44:12)
    at WorkspaceManager.bootstrap (/src/main/types/workspaces/WorkspaceManager.js:63:12)
    at EventEmitter.<anonymous> (/src/main/main.js:466:24)
    at Generator.next (<anonymous>)
    at step (/src/main/main.js:71:191)
    at /src/main/main.js:71:361
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by davidmurdoch** [comment]
This can happen if you've navigated to `~/Library/Application Support/Ganache/workspaces`, or it's sub directories, using Finder, as navigating via Finder has file-system side effects. You may need to delete the hidden `.DS_Store` directories in these folders.

If that isn't causing this specific error, most other file creation errors like this have been fixed in https://github.com/trufflesuite/ganache/releases/tag/v2.3.0! Please let me know if you are still experiencing problems!
