### ISSUE TITLE
System Error when running Ganache 2.0.1 on win32

### ISSUE THREAD

**Issue by JafCR** [trufflesuite/ganache#1505]
PLATFORM: win32
GANACHE VERSION: 2.0.1

EXCEPTION:
```
Error: CONNECTION ERROR: Couldn't connect to node on WS.
    at Object.InvalidConnection (C:\Program Files\WindowsApps\Ganache_2.0.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\web3-core-helpers\src\errors.js:35:16)
    at WebsocketProvider._timeout (C:\Program Files\WindowsApps\Ganache_2.0.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\web3-providers-ws\src\index.js:249:48)
    at W3CWebSocket.connection.onclose (C:\Program Files\WindowsApps\Ganache_2.0.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\web3-providers-ws\src\index.js:149:15)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (C:\Program Files\WindowsApps\Ganache_2.0.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\yaeti\lib\EventTarget.js:107:17)
    at W3CWebSocket.onClose (C:\Program Files\WindowsApps\Ganache_2.0.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\websocket\lib\W3CWebSocket.js:228:10)
    at WebSocketConnection.<anonymous> (C:\Program Files\WindowsApps\Ganache_2.0.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\websocket\lib\W3CWebSocket.js:201:17)
    at emitTwo (events.js:125:13)
    at WebSocketConnection.emit (events.js:213:7)
    at WebSocketConnection.handleSocketClose (C:\Program Files\WindowsApps\Ganache_2.0.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\websocket\lib\WebSocketConnection.js:387:14)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at TCP._handle.close [as _onclose] (net.js:549:12)
```

APPLICATION LOG:
```
T+144172ms:   Block Number: 2
T+144172ms:   Block Time: Mon Dec 02 2019 22:51:41 GMT-0600 (Central America Standard Time)
T+144172ms: eth_getTransactionReceipt
T+144172ms: eth_getBlockByNumber
T+144172ms: eth_accounts
T+144172ms: eth_getBlockByNumber
T+144172ms: eth_getBlockByNumber
T+144172ms: eth_getBlockByNumber
T+144390ms: eth_estimateGas
T+144390ms: eth_getBlockByNumber
T+144390ms: eth_blockNumber
T+144390ms: eth_sendTransaction
T+144390ms: eth_blockNumber
T+144390ms:   Transaction: 0xd6517863963df444836b43f48527ddfe0a29255a4d0f9798bf49ebdd57c823d0
T+144390ms:   Contract created: 0x4146b84e23496182e71165e4aa59d8a73b068ff7
T+144390ms:   Gas usage: 107305
T+144390ms:   Block Number: 3
T+144390ms:   Block Time: Mon Dec 02 2019 22:51:41 GMT-0600 (Central America Standard Time)
T+144390ms: eth_getTransactionReceipt
T+144390ms: eth_getBlockByNumber
T+144390ms: eth_getCode
T+144390ms: eth_getTransactionByHash
T+144390ms: eth_getBlockByNumber
T+144390ms: eth_getBalance
T+144579ms: eth_getBlockByNumber
T+144579ms: eth_getBalance
T+144579ms: eth_getBlockByNumber
T+144579ms: eth_getBalance
T+144579ms: eth_getBlockByNumber
T+144579ms: eth_getBalance
T+144579ms: eth_estimateGas
T+144579ms: eth_getBalance
T+144579ms: eth_getBalance
T+144878ms: eth_getBlockByNumber
T+144878ms: eth_blockNumber
T+144878ms: eth_getBalance
T+144878ms: eth_getBalance
T+144878ms: eth_sendTransaction
T+144878ms: eth_getBalance
T+144878ms:   Transaction: 0x570100979ab918436a0e6230fc6b08907acb548cad0163542f312933c22decc6
T+144878ms:   Contract created: 0xc92dd80a7136dce69746313d2d5fb3c1dc3466e6
T+144878ms:   Gas usage: 3100739
T+144878ms:   Block Number: 4
T+144878ms:   Block Time: Mon Dec 02 2019 22:51:41 GMT-0600 (Central America Standard Time)
T+144878ms: eth_getBalance
T+144878ms: eth_getBalance
T+144878ms: eth_getBalance
T+144878ms: eth_getTransactionReceipt
T+144878ms: eth_getCode
T+144878ms: eth_getTransactionByHash
T+144878ms: eth_getBlockByNumber
T+144878ms: eth_getBlockByNumber
T+144878ms: eth_getBalance
T+145050ms: eth_getBlockByNumber
T+145050ms: eth_getBlockByNumber
T+145050ms: eth_sendTransaction
T+145050ms:   Transaction: 0xc523fce4dd22c653b5d2325ac861685b277ae924d9be25996834c4838d0dd754
T+145050ms:   Gas usage: 27023
T+145050ms:   Block Number: 5
T+145050ms:   Block Time: Mon Dec 02 2019 22:51:42 GMT-0600 (Central America Standard Time)
T+145050ms: eth_getTransactionReceipt
T+145435ms: eth_blockNumber
T+145435ms: eth_getBlockByNumber
T+145435ms: eth_getBalance
T+145435ms: eth_getBalance
T+145435ms: eth_getBalance
T+145435ms: eth_getBalance
T+145435ms: eth_getBalance
T+145435ms: eth_getBalance
T+145435ms: eth_getBalance
T+145435ms: eth_getBalance
T+145435ms: eth_getBalance
T+145435ms: eth_getBalance
T+145435ms: eth_getBalance
T+145915ms: eth_blockNumber
T+146761ms: eth_unsubscribe
T+146761ms: eth_unsubscribe
T+147039ms: eth_blockNumber
T+147496ms: net_version
T+147865ms: eth_gasPrice
T+147865ms: eth_blockNumber
T+147865ms: eth_getCode
T+147865ms: eth_getBlockByNumber
T+148111ms: eth_estimateGas
T+148442ms: eth_getTransactionCount
T+148442ms: eth_getTransactionCount
T+148734ms: eth_blockNumber
T+149630ms: eth_blockNumber
T+150755ms: eth_blockNumber
T+152544ms: eth_blockNumber
T+154362ms: eth_blockNumber
T+155750ms: eth_blockNumber
T+156935ms: eth_blockNumber
T+158563ms: eth_blockNumber
T+159458ms: eth_blockNumber
T+159458ms: eth_getBalance
T+159703ms: eth_getBalance
T+159703ms: eth_getBalance
T+159703ms: eth_getBalance
T+159703ms: eth_getBalance
T+159703ms: eth_getBalance
T+159703ms: eth_getBalance
T+159703ms: eth_getBalance
T+159703ms: eth_getBalance
T+159703ms: eth_getBalance
T+159703ms: eth_getBalance
T+159703ms: eth_blockNumber
T+160350ms: eth_blockNumber
T+160350ms: eth_blockNumber
T+162233ms: eth_blockNumber
T+162233ms: eth_blockNumber
T+163467ms: eth_blockNumber
T+163467ms: eth_blockNumber
T+165028ms: eth_blockNumber
T+165028ms: eth_blockNumber
T+166646ms: eth_blockNumber
T+166646ms: eth_blockNumber
T+167351ms: eth_unsubscribe
```

**Comment by nicholasjpaterno** [comment]
@JafCR Thanks for opening this issue.  It looks like you're using an outdated version of Ganache UI.  I believe this issue has been fixed.  Try https://github.com/trufflesuite/ganache/releases/latest and let us know if this issue persists!

I'm going to close this for now.  Please reopen if this isn't resolved!
