### ISSUE TITLE
System Error when running Ganache 2.1.2 on win32

### ISSUE THREAD

**Issue by vteja711** [trufflesuite/ganache#1508]
PLATFORM: win32
GANACHE VERSION: 2.1.2

EXCEPTION:
```
Error: EEXIST: file already exists, mkdir 'C:\Users\Vishnu.Siripuram\OneDrive - Shell\Documents\Ganache'
    at fs.mkdirSync (fs.js:891:18)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:672:16)
    at Object.mkdirsSync (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\fs-extra\lib\mkdirs\mkdirs-sync.js:31:9)
    at Object.module.exports.generateLogFilePath (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\src\chain\logging.js:50:9)
    at C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\src\chain\chain.js:52:17
    at Server.close (net.js:1596:9)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at Server.emit (events.js:207:7)
    at emitCloseNT (net.js:1647:8)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by davidmurdoch** [comment]
Fixed in https://github.com/trufflesuite/ganache/releases/tag/v2.3.0! Please let me know if you are still experiencing problems!
