### ISSUE TITLE
System Error when running Ganache 2.1.2 on win32

### ISSUE THREAD

**Issue by halimess** [trufflesuite/ganache#1509]
PLATFORM: win32
GANACHE VERSION: 2.1.2

EXCEPTION:
```
TypeError: Cannot read property 'stack' of undefined
    at EventEmitter.<anonymous> (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\src\main\main.js:264:30)
    at Generator.throw (<anonymous>)
    at step (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\src\main\main.js:71:191)
    at C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\src\main\main.js:71:402
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

APPLICATION LOG:
```
T+0ms: eth_unsubscribe
T+0ms: eth_unsubscribe
T+54ms: eth_unsubscribe
T+54ms: eth_unsubscribe
T+3689ms: Starting server (version 2.1.2) with initial configuration: {"gasLimit":6721975,"gasPrice":20000000000,"hardfork":"petersburg","hostname":"127.0.0.1","port":8545,"network_id":5777,"default_balance_ether":1000,"total_accounts":3,"unlocked_accounts":[],"locked":false,"vmErrorsOnRPCResponse":true,"verbose":false,"db_path":"C:\\Users\\yousoung\\AppData\\Roaming\\Ganache\\workspaces\\complex-grandmother\\chaindata"}
T+3760ms: Ganache started successfully!
T+3760ms: Waiting for requests...
T+3772ms: eth_getCode
T+3772ms: eth_subscribe
T+3781ms: eth_getLogs
T+3781ms: eth_subscribe
T+3787ms: eth_getCode
T+3793ms: eth_getCode
T+7579ms: net_version
T+7586ms: eth_getCode
T+7593ms: eth_getBlockByNumber
T+7605ms: eth_getBalance
T+7611ms: eth_getTransactionCount
T+7618ms: eth_getStorageAt
T+7627ms: eth_getStorageAt
T+7636ms: eth_getStorageAt
T+7642ms: eth_getStorageAt
T+7648ms: eth_getStorageAt
T+7655ms: eth_getStorageAt
T+7661ms: eth_getCode
T+7672ms: eth_getStorageAt
T+14307ms: net_version
T+14313ms: eth_getCode
```

**Comment by iBigQ** [comment]
same here on ganache 2.1.2 on linux (AppImage)

It happens to me when clicking on a failed transaction.
