### ISSUE TITLE
System Error when running Ganache 2.1.2 on darwin

### ISSUE THREAD

**Issue by brennanfife** [trufflesuite/ganache#1510]
PLATFORM: darwin
GANACHE VERSION: 2.1.2

EXCEPTION:
```
TypeError: Cannot read property 'address' of null
    at ProjectsWatcher.handleBlock (/src/truffle-integration/projectsWatcher.js:208:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

APPLICATION LOG:
```
T+0ms: Starting server (version 2.1.2) with initial configuration: {"gasLimit":6721975,"gasPrice":20000000000,"hardfork":"petersburg","hostname":"127.0.0.1","port":7545,"network_id":5777,"default_balance_ether":100,"total_accounts":10,"unlocked_accounts":[],"locked":false,"vmErrorsOnRPCResponse":true,"verbose":false,"db_path":"/Users/brenfife/Library/Application Support/Ganache/workspaces/portal/chaindata"}
T+220ms: Ganache started successfully!
T+220ms: Waiting for requests...
T+249ms: eth_getCode
T+274ms: eth_subscribe
T+285ms: eth_getLogs
T+303ms: eth_subscribe
T+318ms: eth_getCode
T+851ms: eth_blockNumber
T+20549ms: eth_blockNumber
T+40570ms: eth_blockNumber
T+60590ms: eth_blockNumber
T+80610ms: eth_blockNumber
T+100629ms: eth_blockNumber
T+120671ms: eth_blockNumber
T+140676ms: eth_blockNumber
T+160701ms: eth_blockNumber
T+180726ms: eth_blockNumber
T+200748ms: eth_blockNumber
T+220771ms: eth_blockNumber
T+240814ms: eth_blockNumber
T+260819ms: eth_blockNumber
T+280833ms: eth_blockNumber
T+300858ms: eth_blockNumber
T+320884ms: eth_blockNumber
T+340914ms: eth_blockNumber
T+360960ms: eth_blockNumber
T+380961ms: eth_blockNumber
T+400984ms: eth_blockNumber
T+421015ms: eth_blockNumber
T+441039ms: eth_blockNumber
T+461063ms: eth_blockNumber
T+481083ms: eth_blockNumber
T+501108ms: eth_blockNumber
T+521151ms: eth_blockNumber
T+541179ms: eth_blockNumber
T+561204ms: eth_blockNumber
T+581230ms: eth_blockNumber
T+601256ms: eth_blockNumber
T+621280ms: eth_blockNumber
T+641306ms: eth_blockNumber
T+661328ms: eth_blockNumber
T+681352ms: eth_blockNumber
T+701378ms: eth_blockNumber
T+721420ms: eth_blockNumber
T+741425ms: eth_blockNumber
T+761449ms: eth_blockNumber
T+781473ms: eth_blockNumber
T+801499ms: eth_blockNumber
T+821525ms: eth_blockNumber
T+841571ms: eth_blockNumber
T+862083ms: eth_blockNumber
T+871982ms: eth_blockNumber
T+871982ms: net_version
T+871982ms: eth_accounts
T+871982ms: eth_getBlockByNumber
T+871982ms: eth_accounts
T+871982ms: eth_getBlockByNumber
T+871982ms: eth_getBlockByNumber
T+871982ms: eth_getBlockByNumber
T+871982ms: eth_estimateGas
T+872567ms: eth_getBlockByNumber
T+872617ms: eth_blockNumber
T+872763ms: eth_sendTransaction
T+874774ms:   Transaction: 0x716a1737725ab49a638e47610ae70de920212cc33971492cc1539612b159294f
T+874774ms:   Contract created: 0xf31dc8800f7e6578054ecdb3f62c7345f452160b
T+874774ms:   Gas usage: 263741
T+874774ms:   Block Number: 37
T+874774ms:   Block Time: Wed Dec 04 2019 16:41:26 GMT-0600 (CST)
T+874774ms: eth_getBlockByNumber
T+874774ms: eth_getTransactionReceipt
T+874774ms: eth_getCode
T+874774ms: eth_getTransactionByHash
T+874774ms: eth_getBlockByNumber
T+874774ms: eth_getBalance
T+874774ms: eth_getBlockByNumber
T+874774ms: eth_getBlockByNumber
T+874774ms: eth_sendTransaction
T+874798ms: eth_unsubscribe
T+874798ms: eth_unsubscribe
T+874798ms:   Transaction: 0xc95d2fda85f015a929644e91d36cef3c66b9b400472324b78bb057696d1b1d07
T+874798ms:   Gas usage: 42023
T+874798ms:   Block Number: 38
T+874798ms:   Block Time: Wed Dec 04 2019 16:41:26 GMT-0600 (CST)
T+874798ms: eth_getTransactionReceipt
T+874798ms: eth_getBlockByNumber
T+874798ms: eth_accounts
T+874912ms: eth_unsubscribe
```

**Comment by davidmurdoch** [comment]
Closing in favor of #1227.
