### ISSUE TITLE
System Error when running Ganache 2.1.2 on darwin

### ISSUE THREAD

**Issue by Ossip** [trufflesuite/ganache#1516]
PLATFORM: darwin
GANACHE VERSION: 2.1.2

EXCEPTION:
```
Error: Number can only safely store up to 53 bits
    at assert (/node_modules/number-to-bn/node_modules/bn.js/lib/bn.js:6:21)
    at BN.toNumber (/node_modules/number-to-bn/node_modules/bn.js/lib/bn.js:506:7)
    at Object.hexToNumber (/node_modules/web3-utils/src/utils.js:234:24)
    at Object.outputBlockFormatter [as outputFormatter] (/node_modules/web3-core-helpers/src/formatters.js:239:29)
    at Subscription._formatOutput (/node_modules/web3-core-subscriptions/src/subscription.js:122:84)
    at /node_modules/web3-core-subscriptions/src/subscription.js:262:44
    at Array.forEach (<anonymous>)
    at Object.callback (/node_modules/web3-core-subscriptions/src/subscription.js:261:28)
    at requestManagerNotification (/node_modules/web3-core-requestmanager/src/index.js:103:65)
    at /node_modules/web3-providers-ws/src/index.js:122:25
    at Array.forEach (<anonymous>)
    at /node_modules/web3-providers-ws/src/index.js:120:45
    at Array.forEach (<anonymous>)
    at W3CWebSocket.WebsocketProvider.connection.onmessage (/node_modules/web3-providers-ws/src/index.js:104:36)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onMessage (/node_modules/websocket/lib/W3CWebSocket.js:234:14)
```

APPLICATION LOG:
```
T+171882ms:   Gas usage: 1993000
T+171882ms:   Block Number: 43
T+171998ms:   Block Time: Invalid Date
T+172107ms: eth_getBlockByNumber
T+172334ms: eth_getTransactionReceipt
T+172334ms: eth_getCode
T+172451ms: eth_getBlockByNumber
T+172586ms: eth_getBlockByNumber
T+172790ms: eth_sendTransaction
T+172910ms:   Transaction: 0x90f0afbea6372a281f7dd8d74f40d3c74e3961b56152e193eb36911eecccc056
T+172910ms:   Gas usage: 27023
T+172910ms:   Block Number: 44
T+173038ms:   Block Time: Invalid Date
T+173171ms: eth_getBlockByNumber
T+173280ms: eth_getTransactionReceipt
T+173386ms: eth_getBlockByNumber
T+173487ms: eth_getBlockByNumber
T+173602ms: eth_getBlockByNumber
T+173710ms: eth_getBlockByNumber
T+173815ms: evm_snapshot
T+173923ms: eth_getBlockByNumber
T+174033ms: eth_blockNumber
T+174141ms: eth_getBlockByNumber
T+174249ms: eth_getBlockByNumber
T+174355ms: eth_getBlockByNumber
T+174467ms: eth_call
T+174582ms: eth_blockNumber
T+174689ms: eth_getBlockByNumber
T+174799ms: eth_getBlockByNumber
T+174908ms: eth_getBlockByNumber
T+175008ms: eth_call
T+175123ms: eth_getBlockByNumber
T+175248ms: eth_sendTransaction
T+175410ms:   Transaction: 0x85ad7f371748f194205c4acb667308f3ee669eaaacb2d739f52d4b378b615ba8
T+175410ms:   Gas usage: 51992
T+175410ms:   Block Number: 45
T+175532ms:   Block Time: Invalid Date
T+175647ms: eth_getBlockByNumber
T+175861ms: eth_getTransactionReceipt
T+175974ms: eth_getBlockByNumber
T+176102ms: eth_call
T+176219ms: eth_getBlockByNumber
T+176325ms: eth_call
T+176434ms: eth_getBlockByNumber
T+176547ms: eth_sendTransaction
T+176653ms:   Transaction: 0xd86b9cdf6df9f007b55e193ea97be8c1f1d1808fc28ea9c443811be8fc3515e1
T+176653ms:   Gas usage: 109893
T+176653ms:   Block Number: 46
T+176855ms:   Block Time: Invalid Date
T+176975ms: eth_getBlockByNumber
T+177200ms: eth_getTransactionReceipt
T+177307ms: eth_getBlockByNumber
T+177414ms: eth_sendTransaction
T+177558ms:   Transaction: 0xddc04a6469da7be136bf714e4f45f068cd7403b3da9a787a1730dd0381ad1f22
T+177558ms:   Gas usage: 79893
T+177558ms:   Block Number: 47
T+177670ms:   Block Time: Invalid Date
T+177780ms: eth_getBlockByNumber
T+178006ms: eth_getTransactionReceipt
T+178006ms: eth_getBlockByNumber
T+178117ms: eth_call
T+178236ms: eth_getBlockByNumber
T+178341ms: eth_call
T+178451ms: eth_getBlockByNumber
T+178565ms: eth_call
T+178675ms: eth_getBlockByNumber
T+178788ms: eth_call
T+178895ms: eth_blockNumber
T+179003ms: eth_getBlockByNumber
T+179145ms: eth_getBlockByNumber
T+179265ms: eth_getBlockByNumber
T+179371ms: eth_call
T+179493ms: eth_getBlockByNumber
T+179607ms: eth_getBlockByNumber
T+179712ms: eth_getBlockByNumber
T+179821ms: eth_getBlockByNumber
T+179929ms: eth_getBlockByNumber
T+180046ms: eth_getBlockByNumber
T+180157ms: eth_sendTransaction
T+180269ms:   Transaction: 0xf93290fbfab6bd6529f7fd9b6139fda89027581525e3130dd2c6973c7a953531
T+180269ms:   Gas usage: 26827
T+180269ms:   Block Number: 48
T+180375ms:   Block Time: Invalid Date
T+180375ms:   Runtime Error: revert
T+180375ms:   Revert reason: revert issue: not enough tokens available
T+180488ms: eth_getBlockByNumber
T+180594ms: eth_call
T+180713ms: eth_blockNumber
T+180910ms: eth_getBlockByNumber
T+181024ms: eth_getBlockByNumber
T+181132ms: eth_getBlockByNumber
T+181243ms: eth_call
T+181350ms: eth_getBlockByNumber
T+181449ms: eth_sendTransaction
T+181580ms:   Transaction: 0xa73cbb9c17322b665cba39cf317c88bdff0d9684bc160f4f94e1b97552a1344e
T+181580ms:   Gas usage: 23261
T+181580ms:   Block Number: 49
T+181691ms:   Block Time: Invalid Date
T+181691ms:   Runtime Error: revert
T+181691ms:   Revert reason: TokenTimelock: current time is before release time
T+181805ms: eth_getBlockByNumber
T+181912ms: eth_call
T+182018ms: eth_blockNumber
T+182125ms: eth_getBlockByNumber
T+182273ms: eth_getBlockByNumber
T+182391ms: eth_getBlockByNumber
T+182517ms: eth_call
T+182633ms: eth_getBlockByNumber
T+182748ms: eth_getBlockByNumber
T+182863ms: eth_call
T+182987ms: eth_getBlockByNumber
T+183084ms: evm_increaseTime
T+183195ms: evm_mine
T+183419ms: eth_unsubscribe
T+183537ms: eth_unsubscribe
T+183646ms: eth_unsubscribe
T+183754ms: eth_unsubscribe
```

**Comment by Ossip** [comment]
I see there is a "Invalid Date" , assume that's the reason.
