### ISSUE TITLE
System Error when running Ganache 2.1.2 on linux

### ISSUE THREAD

**Issue by Mustafa-Refaey** [trufflesuite/ganache#1518]
When I migrate the default `migrations` contract of truffle and then try to view it in Ganache, it encounters this error.

PLATFORM: linux
GANACHE VERSION: 2.1.2

EXCEPTION:
```
TypeError: Cannot read property 'address' of null
    at ProjectsWatcher.handleBlock (/src/truffle-integration/projectsWatcher.js:208:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

APPLICATION LOG:
```
T+0ms: eth_unsubscribe
T+0ms: eth_unsubscribe
T+6ms: eth_unsubscribe
T+119ms: Starting server (version 2.1.2) with initial configuration: {"gasLimit":6721975,"gasPrice":20000000000,"hardfork":"petersburg","default_balance_ether":100,"hostname":"127.0.0.1","locked":false,"network_id":5777,"port":7545,"total_accounts":10,"unlocked_accounts":[],"verbose":false,"vmErrorsOnRPCResponse":true}
T+245ms: Ganache started successfully!
T+245ms: Waiting for requests...
T+268ms: eth_getCode
T+276ms: eth_subscribe
T+280ms: eth_getLogs
T+280ms: eth_subscribe
T+33400ms: eth_blockNumber
T+33414ms: net_version
T+33418ms: eth_accounts
T+33436ms: eth_getBlockByNumber
T+33446ms: eth_getCode
T+33459ms: eth_getBlockByNumber
T+33464ms: eth_getCode
T+33472ms: eth_getBlockByNumber
T+33481ms: eth_accounts
T+33505ms: eth_getBlockByNumber
T+33514ms: eth_getBlockByNumber
T+33520ms: eth_getBlockByNumber
T+33529ms: eth_estimateGas
T+35081ms: eth_getBlockByNumber
T+35086ms: eth_blockNumber
T+35090ms: eth_sendTransaction
T+35253ms:   Transaction: 0xd38eb0bd59a3de05875590733a9e91871e9a7ad81fc90e35a11745d017aec6dc
T+35253ms:   Contract created: 0x07e4f9b9c77eda929b289c8815a42aa3bfed815a
T+35261ms:   Gas usage: 263741
T+35261ms:   Block Number: 1
T+35261ms:   Block Time: Wed Dec 11 2019 01:09:29 GMT+0200 (EET)
T+35263ms: eth_getBlockByNumber
T+35266ms: eth_getTransactionReceipt
T+35271ms: eth_getCode
T+35275ms: eth_getTransactionByHash
T+35279ms: eth_getBlockByNumber
T+35284ms: eth_getBalance
T+35288ms: eth_getBlockByNumber
T+35292ms: eth_getBlockByNumber
T+35297ms: eth_sendTransaction
T+35300ms:   Transaction: 0xc2a91ca18329276bcc99bd9513627db8b3c4b07f6bdd3f594b3734ee84c2e044
T+35300ms:   Gas usage: 42023
T+35304ms:   Block Number: 2
T+35304ms:   Block Time: Wed Dec 11 2019 01:09:29 GMT+0200 (EET)
T+35312ms: eth_getTransactionReceipt
T+35316ms: eth_getBlockByNumber
T+35373ms: eth_unsubscribe
T+35373ms: eth_unsubscribe
T+35377ms: eth_unsubscribe
```

**Comment by davidmurdoch** [comment]
Closing in favor of #1227.
