### ISSUE TITLE
Unzip patch sometimes errors on chmod

### ISSUE THREAD

**Issue by nicholasjpaterno** [trufflesuite/ganache#1531]
```javascript
  Error: ENOENT: no such file or directory, chmod '/home/cashlion/.config/Electron/extras/OpenJDK8U-jre_x64_linux_hotspot_8u232b09.downloading/THIRD_PARTY_README'
      at chmodSync (fs.js:1045:3)
      at UnzipStream.extractor.unzipStream.processDataChunk (webpack-internal:///./src/common/utils/patch-unzip-stream.js:65:13)
      at UnzipStream._parseOrOutput (/home/cashlion/Work/ganache/node_modules/unzip-stream/lib/unzip-stream.js:651:28)
      at PassThrough.done (/home/cashlion/Work/ganache/node_modules/unzip-stream/lib/unzip-stream.js:713:18)
      at Object.onceWrapper (events.js:288:20)
      at PassThrough.emit (events.js:200:13)
      at finishMaybe (_stream_writable.js:644:14)
      at afterWrite (_stream_writable.js:484:3)
      at processTicksAndRejections (internal/process/task_queues.js:84:9) {
    errno: -2,
    syscall: 'chmod',
    code: 'ENOENT',
    path: '/home/cashlion/.config/Electron/extras/OpenJDK8U-jre_x64_linux_hotspot_8u232b09.downloading/THIRD_PARTY_README'
  }
```

**Comment by davidmurdoch** [comment]
note: we may get rid of the streaming unzip process all together because it is slow. We might not need this fix.

**Comment by davidmurdoch** [comment]
Fixed
