### ISSUE TITLE
Handle cordapp deletion logic properly

### ISSUE THREAD

**Issue by davidmurdoch** [trufflesuite/ganache#1547]
When a cordapp is removed from a node via the config what should happen? Right now the cordapp isn't removed from the node's cordapps folder, so it keeps getting added. Obviously a bit strange.

So I think we need to delete the cordapp completely? Or maybe we want to keep it around so we can link old transactions to this cordapp more easily (we can kind of do this with transaction/state data only)

**Comment by nicholasjpaterno** [comment]
This may not be possible.  Im going to table this for now until we can discuss whether this is a desired feature.

**Comment by nicholasjpaterno** [comment]
```bash 
 03:49:37.250 [vert.x-eventloop-thread-0] WARN  io.bluebank.braid.corda.rest.Router - Unable to call: /api/rest/vault/vaultQueryBy
  java.lang.AbstractMethodError: com.example.state.IOUState.getParticipants()Ljava/util/List;
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_232]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_232]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_232]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_232]
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:688) ~[braid-server.jar:?]
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719) ~[braid-server.jar:?]
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeWithType(BeanSerializerBase.java:604) ~[braid-server.jar:?]
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:729) ~[braid-server.jar:?]
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719) ~[braid-server.jar:?]
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155) ~[braid-server.jar:?]
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727) ~[braid-server.jar:?]
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719) ~[braid-server.jar:?]
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155) ~[braid-server.jar:?]
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContentsUsing(IndexedListSerializer.java:142) ~[braid-server.jar:?]
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:88) ~[braid-server.jar:?]
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79) ~[braid-server.jar:?]
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18) ~[braid-server.jar:?]
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727) ~[braid-server.jar:?]
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719) ~[braid-server.jar:?]
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155) ~[braid-server.jar:?]
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480) ~[braid-server.jar:?]
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319) ~[braid-server.jar:?]
        at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3893) ~[braid-server.jar:?]
        at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3207) ~[braid-server.jar:?]
        at io.vertx.core.json.Json.encode(Json.java:76) ~[braid-server.jar:?]
        at io.bluebank.braid.core.http.RouterKt.end(Router.kt:102) ~[braid-server.jar:?]
        at io.bluebank.braid.corda.rest.RouterKt$bind$1.handle(Router.kt:56) ~[braid-server.jar:?]
        at io.bluebank.braid.corda.rest.RouterKt$bind$1.handle(Router.kt) ~[braid-server.jar:?]
        at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:232) ~[braid-server.jar:?]
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:121) ~[braid-server.jar:?]
        at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:154) ~[braid-server.jar:?]
        at io.vertx.ext.web.impl.RouterImpl.handleContext(RouterImpl.java:256) ~[braid-server.jar:?]
        at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:232) ~[braid-server.jar:?]
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:121) ~[braid-server.jar:?]
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:134) ~[braid-server.jar:?]
        at io.bluebank.braid.core.http.RouterKt$setupAllowAnyCORS$1.handle(Router.kt:48) ~[braid-server.jar:?]
        at io.bluebank.braid.core.http.RouterKt$setupAllowAnyCORS$1.handle(Router.kt) ~[braid-server.jar:?]
        at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:232) ~[braid-server.jar:?]
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:121) ~[braid-server.jar:?]
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:134) ~[braid-server.jar:?]
        at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.doEnd(BodyHandlerImpl.java:296) ~[braid-server.jar:?]
        at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.end(BodyHandlerImpl.java:276) ~[braid-server.jar:?]
        at io.vertx.ext.web.handler.impl.BodyHandlerImpl.lambda$handle$0(BodyHandlerImpl.java:87) ~[braid-server.jar:?]
        at io.vertx.core.http.impl.HttpServerRequestImpl.onEnd(HttpServerRequestImpl.java:529) ~[braid-server.jar:?]
        at io.vertx.core.http.impl.HttpServerRequestImpl.handleEnd(HttpServerRequestImpl.java:515) ~[braid-server.jar:?]
        at io.vertx.core.http.impl.Http1xServerConnection.handleEnd(Http1xServerConnection.java:172) ~[braid-server.jar:?]
        at io.vertx.core.http.impl.Http1xServerConnection.handleContent(Http1xServerConnection.java:159) ~[braid-server.jar:?]
        at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:136) ~[braid-server.jar:?]
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320) [braid-server.jar:?]
        at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43) [braid-server.jar:?]
        at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:188) [braid-server.jar:?]
        at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:173) [braid-server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [braid-server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [braid-server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [braid-server.jar:?]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [braid-server.jar:?]
        at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:102) [braid-server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [braid-server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [braid-server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [braid-server.jar:?]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [braid-server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [braid-server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [braid-server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [braid-server.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [braid-server.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [braid-server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [braid-server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [braid-server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [braid-server.jar:?]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1
  407) [braid-server.jar:?]
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1177) [braid-server.jar:?]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1221) [braid-server.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) [braid-server.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) [braid-server.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [braid-server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [braid-server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [braid-server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [braid-server.jar:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [braid-server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [braid-server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [braid-server.jar:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [braid-server.jar:?]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [braid-server.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) [braid-server.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) [braid-server.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) [braid-server.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) [braid-server.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [braid-server.jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [braid-server.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
```
