### ISSUE TITLE
System Error when running Ganache 2.2.1-alpha.0 on win32

### ISSUE THREAD

**Issue by marcovasapollo** [trufflesuite/ganache#1556]
PLATFORM: win32
GANACHE VERSION: 2.2.1-alpha.0

EXCEPTION:
```
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at ChildProcess.target.send (internal/child_process.js:678:16)
    at send (C:\Program Files\WindowsApps\Ganache_2.2.1.0_x64__zh355ej5cj694\app\resources\app.asar\webpack:\src\common\services\ChainService.js:87:20)
    at new Promise (<anonymous>)
    at ee.stopServer (C:\Program Files\WindowsApps\Ganache_2.2.1.0_x64__zh355ej5cj694\app\resources\app.asar\webpack:\src\common\services\ChainService.js:82:12)
    at ee.stopServer (C:\Program Files\WindowsApps\Ganache_2.2.1.0_x64__zh355ej5cj694\app\resources\app.asar\webpack:\src\main\index.js:411:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

APPLICATION LOG:
```
T+29341ms: net_version
T+29344ms: eth_getTransactionReceipt
T+29346ms: eth_getTransactionByHash
T+29378ms: eth_getTransactionByHash
T+29382ms: eth_getBalance
T+29388ms: eth_getBalance
T+29392ms: eth_getBalance
T+29395ms: eth_getBalance
T+29404ms: eth_getBalance
T+29441ms: eth_getBalance
T+29444ms: eth_getBalance
T+29447ms: eth_getBalance
T+29449ms: eth_getBalance
T+29452ms: eth_getBalance
T+29463ms: eth_getTransactionReceipt
T+31022ms: eth_getBalance
T+31024ms: eth_getBalance
T+31027ms: eth_getBalance
T+31030ms: eth_getBalance
T+31032ms: eth_getBalance
T+31035ms: eth_getBalance
T+31039ms: eth_getBalance
T+31044ms: eth_getBalance
T+31044ms: eth_getBalance
T+31049ms: eth_getBalance
T+31052ms: net_version
T+31056ms: eth_accounts
T+31991ms: eth_call
T+32033ms: eth_getCode
T+36023ms: net_version
T+36023ms: eth_accounts
T+36674ms: net_version
T+36701ms: eth_accounts
T+36703ms: eth_estimateGas
T+36752ms: net_version
T+36759ms: eth_sendTransaction
T+36879ms:   Transaction: 0x80a7423740282d40b140f9f1c799952259119a508f96181b9a09c6ec2c77fb79
T+36879ms:   Contract created: 0x19999aa0096ae95637e24d4ec70883bb7dfd0291
T+36879ms:   Gas usage: 362847
T+36879ms:   Block Number: 4
T+36879ms:   Block Time: Sat Dec 21 2019 15:40:21 GMT+0100 (Central European Standard Time)
T+36880ms: eth_getBlockByNumber
T+36880ms: net_version
T+36880ms: eth_getTransactionReceipt
T+36883ms: eth_getTransactionByHash
T+36921ms: eth_getTransactionByHash
T+36924ms: eth_getBalance
T+36971ms: eth_getBalance
T+36974ms: eth_getBalance
T+36978ms: eth_getBalance
T+36981ms: eth_getBalance
T+36984ms: eth_getBalance
T+36987ms: eth_getBalance
T+37004ms: eth_getBalance
T+37005ms: eth_getBalance
T+37007ms: eth_getBalance
T+37009ms: eth_getTransactionReceipt
T+40959ms: eth_getBlockByNumber
T+41022ms: eth_getBalance
T+41025ms: eth_getBalance
T+41029ms: eth_getBalance
T+41032ms: eth_getBalance
T+41032ms: eth_getBalance
T+41035ms: eth_getBalance
T+41038ms: eth_getBalance
T+41041ms: eth_getBalance
T+41044ms: eth_getBalance
T+41047ms: eth_getBalance
T+41049ms: net_version
T+41050ms: eth_accounts
T+43973ms: eth_accounts
T+43975ms: eth_estimateGas
T+47860ms: FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
T+47946ms:  1: 00007FF6F97157A2 node::EmitAsyncDestroy+11834386
T+47946ms:  2: 00007FF6F8BA3DB6 node::Abort+22
T+47946ms:  3: 00007FF6F8BA4393 node::Abort+1523
T+47946ms:  4: 00007FF6F671CB08 v8::V8::GetVersion+792
T+47946ms:  5: 00007FF6F671CAAA v8::V8::GetVersion+698
T+47946ms:  6: 00007FF6F67
T+47948ms: 65DC3 std::_Vector_alloc<std::_Vec_base_types<v8::CpuProfileDeoptInfo,std::allocator<v8::CpuProfileDeoptInfo> > >::_Make_iterator+61731
T+47948ms:  7: 00007FF6F6767493 std::_Vector_alloc<std::_Vec_base_types<v8::CpuProfileDeoptInfo,std::allocator<v8::CpuProfileDeoptInfo>
T+47949ms:  > >::_Make_iterator+67571
T+47949ms:  8: 00007FF6F67641B7 std::_Vector_alloc<std::_Vec_base_types<v8::CpuProfileDeoptInfo,std::allocator<v8::Cpu
T+47952ms: ProfileDeoptInfo> > >::_Make_iterator+54551
T+47952ms:  9: 00007FF6F67620AA std::_Vector_alloc<std::_Vec_base_types<v8::CpuProfileDeoptInfo,std::allocator<v8::Cp
T+47955ms: uProfileDeoptInfo> > >::_Make_iterator+46090
T+47955ms: 10: 00007FF6F6762613 std::_Vector_alloc<std::_Vec_base_types<v8::CpuProfileDeoptInfo,std::al
T+47957ms: locator<v8::CpuProfileDeoptInfo> > >::_Make_iterator+47475
T+47957ms: 11: 00007FF6F676CEB4 std::_Vector_alloc<std::_Vec_base_types<v8::CpuProfileDeopt
T+47958ms: Info,std::allocator<v8::CpuProfileDeoptInfo> > >::_Make_iterator+90644
T+47958ms: 12: 00007FF6F6944761 v8::Unlocker::~Unlocker+55345
T+47958ms: 13: 00007FF6F69523FB v8::Unlocker::~
T+47960ms: Unlocker+111819
T+47960ms: 14: 00007FF6F6952224 v8::Unlocker::~Unlocker+111348
T+47960ms: 15: 00007FF6F6783837 std::_Vector_alloc<std::_Vec_base_types<v8::CpuProfileDe
T+47961ms: optInfo,std::allocator<v8::CpuProfileDeoptInfo> > >::_Make_iterator+183191
T+47961ms: 16: 00007FF6F689324A std::_Vector_alloc<std::_Vec_base_types<v8:
T+47963ms: :CpuProfileDeoptInfo,std::allocator<v8::CpuProfileDeoptInfo> > >::_Make_iterator+1295786
T+47963ms: 17: 00007FF6F6847505 std::_Vector_alloc<std::_
T+47964ms: Vec_base_types<v8::CpuProfileDeoptInfo,std::allocator<v8::CpuProfileDeoptInfo> > >::_Make_iterator+985189
T+47964ms: 18: 00007FF6F68470E7 std::_Vector_alloc<std::_Vec_base_types<v8::CpuProfi
T+47967ms: leDeoptInfo,std::allocator<v8::CpuProfileDeoptInfo> > >::_Make_iterator+984135
T+47967ms: 19: 00007FF6F70E903D v8_inspector::V8ContextInfo::executionConte
T+47968ms: xtId+3107357
T+47968ms: 20: 000002AF1EC1033B 
```

**Comment by davidmurdoch** [comment]
Should be fixed in https://github.com/trufflesuite/ganache/releases/tag/v2.3.0! Please let me know if you are still experiencing problems!
