### ISSUE TITLE
System Error when running Ganache 2.1.1-beta.2 on linux

### ISSUE THREAD

**Issue by dngani** [trufflesuite/ganache#1557]
PLATFORM: linux
GANACHE VERSION: 2.1.1-beta.2

EXCEPTION:
```
TypeError: Cannot read property 'stack' of undefined
    at EventEmitter.<anonymous> (/src/main/main.js:259:30)
    at Generator.throw (<anonymous>)
    at step (/src/main/main.js:71:191)
    at /src/main/main.js:71:402
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

APPLICATION LOG:
```
T+27547ms:  <   }
```

**Comment by davidmurdoch** [comment]
Thanks for opening this issue @dngani. My hunch is that there is a bug in ganache-core that causes the chaindata database to grow by one additional entry for every individual state change, instead of once for each mined block. This is just a hunch but we are working on refactoring some of ganache-core and this Issue will be fixed in the process.

As a workaround, you can go to ~/.config/Ganache/workspaces directory and then locate your worksapce by name and then delete the chaindata directory within it which should allow ganache to open again.
