### ISSUE TITLE
CAPSULE EXCEPTION: System Error when running Ganache 2.3.0-beta.1 on darwin

### ISSUE THREAD

**Issue by guyho** [trufflesuite/ganache#1580]
PLATFORM: darwin
GANACHE VERSION: 2.3.0-beta.1

EXCEPTION:
```
Error: child process exited with code 1.

Stderr:
#### Error while generating node info file /Users/guyhochstetler/Library/Application Support/Ganache/workspaces/mindless-grass/partyc/logs ####
CAPSULE EXCEPTION: Capsule not extracted. while processing attribute Java-Agents: {quasar-core-0.7.10-jdk8.jar=x(antlr**;bftsmart**;co.paralleluniverse**;com.codahale**;com.esotericsoftware**;com.fasterxml**;com.google**;com.ibm**;com.intellij**;com.jcabi**;com.nhaarman**;com.opengamma**;com.typesafe**;com.zaxxer**;de.javakaffee**;groovy**;groovyjarjarantlr**;groovyjarjarasm**;io.atomix**;io.github**;io.netty**;jdk**;junit**;kotlin**;net.bytebuddy**;net.i2p**;org.apache**;org.assertj**;org.bouncycastle**;org.codehaus**;org.crsh**;org.dom4j**;org.fusesource**;org.h2**;org.hamcrest**;org.hibernate**;org.jboss**;org.jcp**;org.joda**;org.junit**;org.mockito**;org.objectweb**;org.objenesis**;org.slf4j**;org.w3c**;org.xml**;org.yaml**;reflectasm**;rx**;org.jolokia**;com.lmax**;picocli**;liquibase**;com.github.benmanes**;org.json**;org.postgresql**;nonapi.io.github.classgraph**)} (for stack trace, run with -Dcapsule.log=verbose)
picocli.CommandLine$ExecutionException: Error while calling command (net.corda.bootstrapper.NetworkBootstrapperRunner@285c08c8): java.lang.IllegalStateException: Error while generating node info file. Please check the logs in /Users/guyhochstetler/Library/Application Support/Ganache/workspaces/mindless-grass/partyc/logs.
at picocli.CommandLine.execute(CommandLine.java:1180)
at picocli.CommandLine.access$800(CommandLine.java:141)
at picocli.CommandLine$RunLast.handle(CommandLine.java:1367)
at picocli.CommandLine$RunLast.handle(CommandLine.java:1335)
at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1243)
at picocli.CommandLine.parseWithHandlers(CommandLine.java:1526)
at net.corda.cliutils.CordaCliWrapperKt.start(CordaCliWrapper.kt:73)
at net.corda.bootstrapper.MainKt.main(Main.kt:19)
Caused by: java.lang.IllegalStateException: Error while generating node info file. Please check the logs in /Users/guyhochstetler/Library/Application Support/Ganache/workspaces/mindless-grass/partyc/logs.
at net.corda.nodeapi.internal.network.NetworkBootstrapper$Companion.printNodeInfoGenLogToConsole(NetworkBootstrapper.kt:137)
at net.corda.nodeapi.internal.network.NetworkBootstrapper$Companion.generateNodeInfo(NetworkBootstrapper.kt:116)
at net.corda.nodeapi.internal.network.NetworkBootstrapper$Companion.access$generateNodeInfo(NetworkBootstrapper.kt:69)
at net.corda.nodeapi.internal.network.NetworkBootstrapper$Companion$generateNodeInfos$1$1.invoke(NetworkBootstrapper.kt:95)
at net.corda.nodeapi.internal.network.NetworkBootstrapper$Companion$generateNodeInfos$1$1.invoke(NetworkBootstrapper.kt:69)
at net.corda.core.internal.concurrent.ValueOrException$DefaultImpls.capture(CordaFutureImpl.kt:130)
at net.corda.core.internal.concurrent.OpenFuture$DefaultImpls.capture(CordaFutureImpl.kt)
at net.corda.core.internal.concurrent.CordaFutureImpl.capture(CordaFutureImpl.kt:142)
at net.corda.core.internal.concurrent.CordaFutureImplKt$fork$$inlined$also$lambda$1.run(CordaFutureImpl.kt:22)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)


Stdout:
Bootstrapping local test network in /Users/guyhochstetler/Library/Application Support/Ganache/workspaces/mindless-grass
Generating node directory for notary
Generating node directory for partya
Generating node directory for partyb
Generating node directory for partyc
Nodes found in the following sub-directories: [notary, partya, partyb, partyc]
Found the following CorDapps: []
Not copying CorDapp JARs as --copy-cordapps is set to FirstRunOnly, and it looks like this network has already been bootstrapped.
Waiting for all nodes to generate their node-info files...


Error:


config:{"env":{"PATH":"/Users/guyhochstetler/Library/Application Support/Ganache/extras/OpenJDK8U-jre_x64_mac_hotspot_8u232b09/bin","CAPSULE_CACHE_DIR":"./capsule"},"cwd":"/Users/guyhochstetler/Library/Application Support/Ganache/workspaces/mindless-grass"}
    at ChildProcess.<anonymous> (/webpack:/src/integrations/corda/main/utils/network/bootstrap.js:97:18)
    at ChildProcess.emit (events.js:200:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

**Comment by nicholasjpaterno** [comment]
@guyho Thanks for raising this issue.  This is a known issue with the corda network bootstrapper utility we rely on.  The corda team is aware of the issue and will hopefully address this asap.  I'm going to keep the issue open for now to track this but unfortunately there isn't much we can do aside from a work around of detecting this error and retrying.

**Comment by davidmurdoch** [comment]
We may need to just implement automatic retry logic for the bootstrapper (which is already a slow process -- but should be mitigated by only bootstrapping when we detect the config has been changed by the user) or generate the node info files ourselves, without the aid of the bootstrapper itself, unfortunately. This would allow us to automatically retry failed node-info generation caused failed capsule extractions (like we do on actual node start up).

**Comment by davidmurdoch** [comment]
Fixed!
