### ISSUE TITLE
System Error when running Ganache 2.3.0-beta.1 on darwin

### ISSUE THREAD

**Issue by programmerkgit** [trufflesuite/ganache#1582]
PLATFORM: darwin
GANACHE VERSION: 2.3.0-beta.1

EXCEPTION:
```
Error: Can't get db-location. Server not started.
    at Ce.getDbLocation (/webpack:/src/integrations/ethereum/common/services/EthereumChainService.js:98:15)
    at nt._saveWorkspace (/webpack:/src/integrations/index.js:67:84)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

**Comment by davidmurdoch** [comment]
Does this issue happen reliably for you? Or is it just an occasional occurrence in this beta version?

**Comment by davidmurdoch** [comment]
Fixed in commit https://github.com/trufflesuite/ganache/commit/70e7141a3774d9c2e0d27ba60ac5f82f7657c720
