### ISSUE TITLE
System Error when running Ganache 2.2.1-alpha.0 on linux

### ISSUE THREAD

**Issue by shubham4007** [trufflesuite/ganache#1601]
PLATFORM: linux
GANACHE VERSION: 2.2.1-alpha.0

EXCEPTION:
```
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at ChildProcess.target.send (internal/child_process.js:678:16)
    at ChainService.startServer (webpack-internal:///./src/common/services/ChainService.js:74:18)
    at ChainService.eval (webpack-internal:///./src/main/index.js:271:17)
    at ChainService.emit (events.js:200:13)
    at ChainService.start (webpack-internal:///./src/common/services/ChainService.js:66:12)
    at EventEmitter.eval (webpack-internal:///./src/main/index.js:445:15)
```

**Comment by davidmurdoch** [comment]
Closing as this is from an old alpha version that is know to not be stable. For ethereum development the best version is the latest stable release (the latest 2.3.0-beta.1 has some know bugs that will be fixed in the next beta release). You can download the latest stable release at https://www.trufflesuite.com/ganache
