### ISSUE TITLE
System Error when running Ganache 2.1.2 on win32

### ISSUE THREAD

**Issue by carlosescom** [trufflesuite/ganache#1611]
PLATFORM: win32
GANACHE VERSION: 2.1.2

EXCEPTION:
```
Error: CONNECTION ERROR: Couldn't connect to node on WS.
    at Object.InvalidConnection (C:\Program Files\Ganache\resources\app.asar\node_modules\web3-core-helpers\src\errors.js:35:16)
    at WebsocketProvider._timeout (C:\Program Files\Ganache\resources\app.asar\node_modules\web3-providers-ws\src\index.js:255:48)
    at W3CWebSocket.connection.onclose (C:\Program Files\Ganache\resources\app.asar\node_modules\web3-providers-ws\src\index.js:155:15)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (C:\Program Files\Ganache\resources\app.asar\node_modules\yaeti\lib\EventTarget.js:107:17)
    at W3CWebSocket.onClose (C:\Program Files\Ganache\resources\app.asar\node_modules\websocket\lib\W3CWebSocket.js:228:10)
    at WebSocketConnection.<anonymous> (C:\Program Files\Ganache\resources\app.asar\node_modules\websocket\lib\W3CWebSocket.js:201:17)
    at emitTwo (events.js:125:13)
    at WebSocketConnection.emit (events.js:213:7)
    at WebSocketConnection.handleSocketClose (C:\Program Files\Ganache\resources\app.asar\node_modules\websocket\lib\WebSocketConnection.js:389:14)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at TCP._handle.close [as _onclose] (net.js:549:12)
```

APPLICATION LOG:
```
T+462026ms: eth_getBalance
T+462026ms: eth_getBalance
T+462026ms: eth_blockNumber
T+463033ms: eth_getBalance
T+463033ms: eth_getBalance
T+463033ms: eth_getBalance
T+463033ms: eth_getBalance
T+463033ms: eth_getBalance
T+463033ms: eth_getBalance
T+463033ms: eth_getBalance
T+463472ms: eth_accounts
T+463472ms: eth_getBalance
T+463472ms: eth_getBalance
T+463472ms: eth_getBalance
T+463472ms: eth_getBalance
T+463472ms: eth_getBalance
T+463472ms: eth_getBalance
T+463472ms: eth_getBalance
T+463472ms: eth_getBalance
T+463472ms: eth_getBalance
T+463472ms: eth_getBalance
T+464804ms: eth_blockNumber
T+465839ms: eth_accounts
T+465839ms: eth_getBalance
T+465839ms: eth_getBalance
T+465839ms: eth_getBalance
T+465839ms: eth_getBalance
T+465839ms: eth_getBalance
T+466211ms: eth_getBalance
T+466211ms: eth_getBalance
T+466211ms: eth_getBalance
T+466211ms: eth_getBalance
T+466211ms: eth_getBalance
T+466211ms: eth_blockNumber
T+467395ms: eth_accounts
T+467395ms: eth_getBalance
T+467395ms: eth_getBalance
T+467395ms: eth_getBalance
T+467395ms: eth_getBalance
T+467395ms: eth_getBalance
T+467395ms: eth_getBalance
T+467395ms: eth_getBalance
T+467395ms: eth_getBalance
T+467395ms: eth_getBalance
T+467395ms: eth_getBalance
T+467963ms: eth_blockNumber
T+468603ms: eth_blockNumber
T+468915ms: eth_accounts
T+468915ms: eth_getBalance
T+468915ms: eth_getBalance
T+468915ms: eth_getBalance
T+468915ms: eth_getBalance
T+468915ms: eth_getBalance
T+468915ms: eth_getBalance
T+468915ms: eth_getBalance
T+468915ms: eth_getBalance
T+468915ms: eth_getBalance
T+468915ms: eth_getBalance
T+469815ms: eth_blockNumber
T+470131ms: eth_accounts
T+470131ms: eth_getBalance
T+470131ms: eth_getBalance
T+470131ms: eth_getBalance
T+470131ms: eth_getBalance
T+470131ms: eth_getBalance
T+470131ms: eth_getBalance
T+470131ms: eth_getBalance
T+470131ms: eth_getBalance
T+470131ms: eth_getBalance
T+470131ms: eth_getBalance
T+470323ms: eth_blockNumber
T+471359ms: eth_blockNumber
T+471359ms: eth_accounts
T+471359ms: eth_getBalance
T+471359ms: eth_getBalance
T+471359ms: eth_getBalance
T+471359ms: eth_getBalance
T+471359ms: eth_getBalance
T+471359ms: eth_getBalance
T+471359ms: eth_getBalance
T+471359ms: eth_getBalance
T+471359ms: eth_getBalance
T+471359ms: eth_getBalance
T+472475ms: eth_blockNumber
T+473079ms: eth_accounts
T+473079ms: eth_getBalance
T+473079ms: eth_getBalance
T+473079ms: eth_getBalance
T+473079ms: eth_getBalance
T+473079ms: eth_getBalance
T+473079ms: eth_getBalance
T+473079ms: eth_getBalance
T+473079ms: eth_getBalance
T+473079ms: eth_getBalance
T+473079ms: eth_getBalance
T+473623ms: eth_blockNumber
T+474635ms: eth_accounts
T+474635ms: eth_getBalance
T+474635ms: eth_getBalance
T+474635ms: eth_getBalance
T+474635ms: eth_getBalance
T+474635ms: eth_getBalance
T+474635ms: eth_getBalance
T+474635ms: eth_getBalance
T+474635ms: eth_blockNumber
T+474635ms: eth_getBalance
T+474635ms: eth_getBalance
T+474635ms: eth_getBalance
T+475723ms: eth_blockNumber
T+476187ms: eth_accounts
T+476187ms: eth_getBalance
T+476187ms: eth_getBalance
T+476187ms: eth_getBalance
T+476187ms: eth_getBalance
T+476187ms: eth_getBalance
T+476187ms: eth_getBalance
T+476187ms: eth_getBalance
T+476187ms: eth_getBalance
T+476187ms: eth_getBalance
T+476187ms: eth_getBalance
T+476655ms: eth_blockNumber
T+477503ms: eth_accounts
T+477503ms: eth_getBalance
T+477503ms: eth_getBalance
T+477503ms: eth_getBalance
T+477503ms: eth_getBalance
T+477503ms: eth_getBalance
T+477503ms: eth_getBalance
T+477503ms: eth_getBalance
T+477503ms: eth_getBalance
T+477503ms: eth_getBalance
T+477503ms: eth_getBalance
T+477503ms: eth_blockNumber
T+479075ms: eth_blockNumber
T+479931ms: eth_accounts
T+479931ms: eth_getBalance
T+479931ms: eth_getBalance
T+479931ms: eth_getBalance
T+479931ms: eth_getBalance
T+479931ms: eth_getBalance
T+479931ms: eth_getBalance
T+479931ms: eth_getBalance
T+479931ms: eth_getBalance
T+479931ms: eth_getBalance
T+479931ms: eth_getBalance
T+481219ms: eth_blockNumber
T+482031ms: eth_accounts
T+482031ms: eth_getBalance
T+482031ms: eth_getBalance
T+482031ms: eth_getBalance
T+482031ms: eth_getBalance
T+482031ms: eth_getBalance
T+482031ms: eth_getBalance
T+482031ms: eth_getBalance
T+482275ms: eth_getBalance
T+482307ms: eth_unsubscribe
T+482307ms: eth_unsubscribe
T+482307ms: eth_unsubscribe
```

**Comment by davidmurdoch** [comment]
Fixed in https://github.com/trufflesuite/ganache/releases/tag/v2.3.0! Please let me know if you are still experiencing problems!
