### ISSUE TITLE
2.2.1-alpha.0 - timeout while attempting to connect to the network.

### ISSUE THREAD

**Issue by SvenMeyer** [trufflesuite/ganache#1615]
Error description : 

truffle migrate fails to connect to ganache GUI v2.2.1-alpha.0 , although it worked with other current releases, like `2.1.2-linux-x86_64.AppImage`

```
$ npm run dev

> ganache@2.2.1-alpha.0 dev /home/sum/DEV/ETH/ganache
> electron-webpack dev
...
```

truffle-config.js :
```
const mnemonic_candy = "candy grid episode twelve survey average space piano puzzle tourist hero upon"

  networks: {
    gui_HD: {
      // must be a thunk, otherwise truffle commands may hang in CI
      provider: () => new HDWalletProvider(mnemonic_candy, 'http://127.0.0.1:7545'),
      network_id: '5777',
      // shareNonce:false,
      // websockets: true,	// enabled to use the confirmations listener or to hear Events using .on or .once
      // production: true,	// Treats this network as if it was a public net. (default: false)
    },

```

```
$ truffle migrate --network gui_HD  --reset
Warning: Both truffle-config.js and truffle.js were found. Using truffle-config.js.

Compiling your contracts...
===========================
> Compiling ./contracts/ProofOfAsset.sol
> Compilation warnings encountered:

    /home/sum/DEV/IronOre/Proof-of-Asset-Eth/contracts/ProofOfAsset.sol:2:1: Warning: Experimental features are turned on. Do not use experimental features on live deployments.
pragma experimental ABIEncoderV2;   // required to pass structs as function parameter and return values
^-------------------------------^

> Artifacts written to /home/sum/DEV/IronOre/Proof-of-Asset-Eth/client/src/contracts
> Compiled successfully using:
   - solc: 0.5.16+commit.9c3226ce.Emscripten.clang


/home/sum/.nvm/versions/node/v12.14.1/lib/node_modules/truffle/build/webpack:/packages/provider/index.js:56
        throw new Error(errorMessage);
^
Error: There was a timeout while attempting to connect to the network.
       Check to see that your provider is valid.
       If you have a slow internet connection, try configuring a longer timeout in your Truffle config. Use the networks[networkName].networkCheckTimeout property to do this.
    at Timeout._onTimeout (/home/sum/.nvm/versions/node/v12.14.1/lib/node_modules/truffle/build/webpack:/packages/provider/index.js:56:1)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

## Your Environment
OS : Linux - Arch Linux / Manjaro
$ truffle version
Warning: Both truffle-config.js and truffle.js were found. Using truffle-config.js.
Truffle v5.1.13-nodeLTS.0 (core: 5.1.12)
Solidity v0.5.16 (solc-js)
Node v12.14.1
Web3.js v1.2.1

**Comment by davidmurdoch** [comment]
Closing this as this alpha version was very buggy (I don't think the ethereum worked correctly most of the time due to some race conditions)
