### ISSUE TITLE
2.3.0-beta.2-linux-x86_64.AppImage - NO PROJECTS IN WORKSPACE - Migrations" -- EXDEV: cross-device link not permitted

### ISSUE THREAD

**Issue by SvenMeyer** [trufflesuite/ganache#1617]
OS : Linux Manjaro
Truffle v5.1.13-nodeLTS.0 (core: 5.1.12)
Solidity v0.5.16 (solc-js)
Node v12.14.1
Web3.js v1.2.1

ganache-2.1.2-linux-x86_64.AppImage

- created anew workspace with 'Quickstart'
- added truffle-config.js to projects
- [save and restart]
- deployed contract with truffle (`truffle migrate --network gg  --reset`)

ganache GUI Interface : 
CONTRACTS

![ganache-2 3 0-beta 2-linux-x86_64 AppImage_No-Projects-in-Workspace_Screenshot](https://user-images.githubusercontent.com/25609/74079084-a440ba80-4a86-11ea-8207-0258d94cc9ce.png)

- clicking button [Link Truffle Projects]
truffle-config.js is in the list of Truffle Projects

clicked [Save] button on Homescreen > Workspace gets a random name

kicking of migration again : 

```
$ truffle migrate --network gg  --reset

...

Starting migrations...
======================
> Network name:    'gg'
> Network id:      5777
> Block gas limit: 0x6691b7


1_initial_migration.js
======================

   Replacing 'Migrations'
   ----------------------

Error:  *** Deployment Failed ***

"Migrations" -- EXDEV: cross-device link not permitted, rename '/tmp/tmp-24894lQYEa1iy5MiF' -> '/home/sum/.config/Ganache/workspaces/entertaining-house/chaindata/!trie_db!0x654a8ed8ffc3092e28e9dc5ecbfd7cce485f7a1043e93d3f55d0c4eca58c68c2'.

    at /home/sum/.nvm/versions/node/v12.14.1/lib/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:364:1
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Migration._deploy (/home/sum/.nvm/versions/node/v12.14.1/lib/node_modules/truffle/build/webpack:/packages/migrate/migration.js:70:1)
    at Migration._load (/home/sum/.nvm/versions/node/v12.14.1/lib/node_modules/truffle/build/webpack:/packages/migrate/migration.js:57:1)
    at Migration.run (/home/sum/.nvm/versions/node/v12.14.1/lib/node_modules/truffle/build/webpack:/packages/migrate/migration.js:167:1)
    at Object.runMigrations (/home/sum/.nvm/versions/node/v12.14.1/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:148:1)
    at Object.runFrom (/home/sum/.nvm/versions/node/v12.14.1/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:110:1)
    at Object.runAll (/home/sum/.nvm/versions/node/v12.14.1/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:114:1)
    at Object.run (/home/sum/.nvm/versions/node/v12.14.1/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:79:1)
    at runMigrations (/home/sum/.nvm/versions/node/v12.14.1/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:253:1)
    at /home/sum/.nvm/versions/node/v12.14.1/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:218:1
Truffle v5.1.13-nodeLTS.0 (core: 5.1.12)
Node v12.14.1
```

**Comment by davidmurdoch** [comment]
I suspect some of the issues you are experiencing are related to your tmp folder being on a separate partition from your home dir. This bug should be fixed by https://github.com/trufflesuite/ganache-core/pull/548 which we hope to release soon!
