### ISSUE TITLE
System Error when running Ganache 2.1.2 on darwin

### ISSUE THREAD

**Issue by edsphinx** [trufflesuite/ganache#1624]
I was trying to compile the source from:
https://github.com/mcortesi/poap
and got this error.

PLATFORM: darwin
GANACHE VERSION: 2.1.2

EXCEPTION:
```
TypeError: Cannot read property 'pop' of undefined
    at CheckpointTrie.Trie._updateNode (/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:360:23)
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:107:16
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:461:14
    at processNode (/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:471:23)
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:516:13
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:180:7
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/util.js:75:7
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:52:16
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:269:32
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:44:16
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/util.js:71:7
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:157:9
    at /node_modules/ganache-core/lib/database/levelupobjectadapter.js:41:16
    at /node_modules/ganache-core/node_modules/level-sublevel/shell.js:101:15
    at /node_modules/ganache-core/node_modules/level-sublevel/nut.js:121:19
    at /node_modules/ganache-core/node_modules/encoding-down/index.js:51:21
```

APPLICATION LOG:
```
T+397841851ms: eth_getBalance
T+397841854ms: eth_getBalance
T+397841857ms: eth_getBalance
T+397841859ms: eth_getBalance
T+397841861ms: eth_getBalance
T+397841865ms: eth_getBalance
T+397844807ms: eth_accounts
T+397844809ms: eth_getBalance
T+397844812ms: eth_getBalance
T+397844814ms: eth_getBalance
T+397844817ms: eth_getBalance
T+397844820ms: eth_getBalance
T+397844822ms: eth_getBalance
T+397844836ms: eth_getBalance
T+397844836ms: eth_getBalance
T+397844836ms: eth_getBalance
T+397844836ms: eth_getBalance
T+397847065ms: eth_accounts
T+397847068ms: eth_getBalance
T+397847071ms: eth_getBalance
T+397847074ms: eth_getBalance
T+397847086ms: eth_getBalance
T+397847086ms: eth_getBalance
T+397847086ms: eth_getBalance
T+397847087ms: eth_getBalance
T+397847091ms: eth_getBalance
T+397847094ms: eth_getBalance
T+397847097ms: eth_getBalance
T+397848188ms: eth_accounts
T+397848192ms: eth_getBalance
T+397848194ms: eth_getBalance
T+397848197ms: eth_getBalance
T+397848200ms: eth_getBalance
T+397848204ms: eth_getBalance
T+397848206ms: eth_getBalance
T+397848209ms: eth_getBalance
T+397848211ms: eth_getBalance
T+397848215ms: eth_getBalance
T+397848218ms: eth_getBalance
T+397850636ms: eth_accounts
T+397850636ms: eth_getBalance
T+397850638ms: eth_getBalance
T+397850642ms: eth_getBalance
T+397850644ms: eth_getBalance
T+397850647ms: eth_getBalance
T+397850651ms: eth_getBalance
T+397850653ms: eth_getBalance
T+397850655ms: eth_getBalance
T+397850657ms: eth_getBalance
T+397850660ms: eth_getBalance
T+397853913ms: eth_accounts
T+397853972ms: eth_getBalance
T+397853972ms: eth_getBalance
T+397853972ms: eth_getBalance
T+397853972ms: eth_getBalance
T+397853972ms: eth_getBalance
T+397853972ms: eth_getBalance
T+397853972ms: eth_getBalance
T+397853972ms: eth_getBalance
T+397853972ms: eth_getBalance
T+397853972ms: eth_getBalance
T+397855944ms: eth_accounts
T+397855946ms: eth_getBalance
T+397855948ms: eth_getBalance
T+397855951ms: eth_getBalance
T+397855953ms: eth_getBalance
T+397855956ms: eth_getBalance
T+397855958ms: eth_getBalance
T+397855962ms: eth_getBalance
T+397855965ms: eth_getBalance
T+397855968ms: eth_getBalance
T+397855970ms: eth_getBalance
T+397857146ms: eth_accounts
T+397857149ms: eth_getBalance
T+397857153ms: eth_getBalance
T+397857155ms: eth_getBalance
T+397857160ms: eth_getBalance
T+397857163ms: eth_getBalance
T+397857165ms: eth_getBalance
T+397857168ms: eth_getBalance
T+397857171ms: eth_getBalance
T+397857173ms: eth_getBalance
T+397857185ms: eth_getBalance
T+397859645ms: eth_accounts
T+397859649ms: eth_getBalance
T+397859653ms: eth_getBalance
T+397859656ms: eth_getBalance
T+397859659ms: eth_getBalance
T+397859662ms: eth_getBalance
T+397859665ms: eth_getBalance
T+397859669ms: eth_getBalance
T+397859673ms: eth_getBalance
T+397859685ms: eth_getBalance
T+397859685ms: eth_getBalance
T+397862896ms: eth_accounts
T+397862899ms: eth_getBalance
T+397862903ms: eth_getBalance
T+397862906ms: eth_getBalance
T+397862909ms: eth_getBalance
T+397862912ms: eth_getBalance
T+397862917ms: eth_getBalance
T+397862920ms: eth_getBalance
T+397862922ms: eth_getBalance
T+397862935ms: eth_getBalance
T+397862935ms: eth_getBalance
T+397865785ms: eth_accounts
T+397865785ms: eth_getBalance
T+397865785ms: eth_getBalance
T+397865788ms: eth_getBalance
T+397865791ms: eth_getBalance
T+397865794ms: eth_getBalance
T+397865797ms: eth_getBalance
T+397865798ms: eth_getBalance
T+397865801ms: eth_getBalance
T+397865804ms: eth_getBalance
T+397865835ms: eth_getBalance
T+397868806ms: eth_accounts
T+397868809ms: eth_getBalance
T+397868812ms: eth_getBalance
T+397868815ms: eth_getBalance
T+397868818ms: eth_getBalance
T+397868821ms: eth_getBalance
T+397868824ms: eth_getBalance
T+397868833ms: eth_getBalance
T+397868833ms: eth_getBalance
T+397868833ms: eth_getBalance
T+397868835ms: eth_getBalance
T+397869890ms: eth_unsubscribe
T+397869890ms: eth_unsubscribe
T+518209190ms: net_version
T+518209318ms: eth_accounts
T+518209332ms: eth_sendTransaction
T+518209476ms: eth_unsubscribe
T+518209480ms: eth_unsubscribe
T+518209496ms: eth_unsubscribe
T+518209496ms: eth_unsubscribe
T+518209499ms: eth_unsubscribe
```

**Comment by wbt** [comment]
Apparent duplicate of #1320
