### ISSUE TITLE
System Error when running Ganache 2.3.0-beta.2 on linux

### ISSUE THREAD

**Issue by munivk** [trufflesuite/ganache#1638]
PLATFORM: linux
GANACHE VERSION: 2.3.0-beta.2

EXCEPTION:
```
Error: Couldn't stop corda process chain with PID 30314. This like means you'll need to end processes manual or restart your computer. Please report this issue!
    at Timeout._onTimeout (/webpack:/src/integrations/corda/main/utils/network/corda.js:125:16)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

**Comment by davidmurdoch** [comment]
Should be fixed in https://github.com/trufflesuite/ganache/releases/tag/v2.3.0! Please let me know if you are still experiencing problems!
