### ISSUE TITLE
System Error when running Ganache 2.3.0-beta.2 on linux

### ISSUE THREAD

**Issue by 5798manishkumawat** [trufflesuite/ganache#1641]
PLATFORM: linux
GANACHE VERSION: 2.3.0-beta.2

EXCEPTION:
```
Error [ERR_SERVER_NOT_RUNNING]: Server is not running.
    at Server.close (net.js:1517:12)
    at Object.onceWrapper (events.js:288:20)
    at Server.emit (events.js:205:15)
    at emitCloseNT (net.js:1570:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
```

**Comment by davidmurdoch** [comment]
Should be fixed in https://github.com/trufflesuite/ganache/releases/tag/v2.3.0! Please let me know if you are still experiencing problems!
