### ISSUE TITLE
System Error when running Ganache 2.1.2 on darwin

### ISSUE THREAD

**Issue by Suiyu-Yang** [trufflesuite/ganache#1645]
PLATFORM: darwin
GANACHE VERSION: 2.1.2

EXCEPTION:
```
Error: CONNECTION ERROR: Couldn't connect to node on WS.
    at Object.InvalidConnection (/node_modules/web3-core-helpers/src/errors.js:35:16)
    at WebsocketProvider._timeout (/node_modules/web3-providers-ws/src/index.js:255:48)
    at W3CWebSocket.connection.onclose (/node_modules/web3-providers-ws/src/index.js:155:15)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onClose (/node_modules/websocket/lib/W3CWebSocket.js:228:10)
    at WebSocketConnection.<anonymous> (/node_modules/websocket/lib/W3CWebSocket.js:201:17)
    at emitTwo (events.js:125:13)
    at WebSocketConnection.emit (events.js:213:7)
    at WebSocketConnection.handleSocketClose (/node_modules/websocket/lib/WebSocketConnection.js:389:14)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at TCP._handle.close [as _onclose] (net.js:549:12)
```

APPLICATION LOG:
```
T+0ms: Starting server (version 2.1.2) with initial configuration: {"gasLimit":6721975,"gasPrice":20000000000,"hardfork":"petersburg","hostname":"127.0.0.1","port":7545,"network_id":5777,"default_balance_ether":100,"total_accounts":10,"unlocked_accounts":[],"locked":false,"vmErrorsOnRPCResponse":true,"verbose":false,"db_path":"/Users/suisui/Library/Application Support/Ganache/workspaces/nps-project/chaindata"}
T+112ms: Ganache started successfully!
T+112ms: Waiting for requests...
T+191ms: eth_subscribe
T+191ms: eth_getLogs
T+191ms: eth_subscribe
```

**Comment by davidmurdoch** [comment]
Should be fixed in https://github.com/trufflesuite/ganache/releases/tag/v2.3.0! Please let me know if you are still experiencing problems!
