### ISSUE TITLE
System Error when running Ganache 2.1.2 on win32

### ISSUE THREAD

**Issue by ashawinm** [trufflesuite/ganache#1647]
PLATFORM: win32
GANACHE VERSION: 2.1.2

EXCEPTION:
```
Error: CONNECTION ERROR: Couldn't connect to node on WS.
    at Object.InvalidConnection (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\web3-core-helpers\src\errors.js:35:16)
    at WebsocketProvider._timeout (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\web3-providers-ws\src\index.js:255:48)
    at W3CWebSocket.connection.onclose (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\web3-providers-ws\src\index.js:155:15)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\yaeti\lib\EventTarget.js:107:17)
    at W3CWebSocket.onClose (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\websocket\lib\W3CWebSocket.js:228:10)
    at WebSocketConnection.<anonymous> (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\websocket\lib\W3CWebSocket.js:201:17)
    at emitTwo (events.js:125:13)
    at WebSocketConnection.emit (events.js:213:7)
    at WebSocketConnection.handleSocketClose (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\websocket\lib\WebSocketConnection.js:389:14)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at TCP._handle.close [as _onclose] (net.js:549:12)
```

APPLICATION LOG:
```
T+0ms: Starting server (version 2.1.2) with initial configuration: {"gasLimit":6721975,"gasPrice":20000000000,"hardfork":"petersburg","db_path":"C:\\Users\\ashWIN\\AppData\\Roaming\\Ganache\\workspaces\\reminiscent-shame\\chaindata","default_balance_ether":100,"hostname":"127.0.0.1","locked":false,"network_id":5777,"port":7545,"total_accounts":10,"unlocked_accounts":[],"verbose":false,"vmErrorsOnRPCResponse":true}
T+887ms: Ganache started successfully!
T+887ms: Waiting for requests...
T+887ms: eth_blockNumber
T+887ms: eth_getBlockByNumber
T+1003ms: eth_getBlockByNumber
T+1063ms: eth_getBlockByNumber
T+1119ms: eth_getBlockByNumber
T+1203ms: eth_getBlockByNumber
T+1247ms: eth_getBlockByNumber
T+1351ms: eth_getBlockByNumber
T+1487ms: eth_getBlockByNumber
T+1563ms: eth_getCode
T+1623ms: eth_subscribe
T+1663ms: eth_getLogs
T+1707ms: eth_subscribe
T+1755ms: eth_getCode
T+19924ms: eth_blockNumber
T+39945ms: eth_blockNumber
T+53658ms: eth_blockNumber
T+53794ms: net_version
T+54662ms: eth_accounts
T+54662ms: eth_getBlockByNumber
T+54662ms: eth_accounts
T+54662ms: eth_getBlockByNumber
T+54662ms: eth_getBlockByNumber
T+54662ms: eth_getBlockByNumber
T+54662ms: eth_estimateGas
T+57604ms: eth_getBlockByNumber
T+57604ms: eth_blockNumber
T+57604ms: eth_sendTransaction
T+58216ms:   Transaction: 0x3759b2596d6ad732ab76badfd78306b7c3710bb3fff70a31d8a7c3f6342b18b8
T+58216ms:   Contract created: 0x0e38aaffc3d06f414dbb60a261f3b36b2d0ff532
T+58216ms:   Gas usage: 263741
T+58216ms:   Block Number: 8
T+58216ms:   Block Time: Fri Feb 28 2020 00:22:38 GMT-0800 (Pacific Standard Time)
T+58216ms: eth_getTransactionReceipt
T+58216ms: eth_getCode
T+58216ms: eth_getTransactionByHash
T+58216ms: eth_getBlockByNumber
T+58216ms: eth_getBalance
T+58216ms: eth_getBlockByNumber
T+58216ms: eth_getBlockByNumber
T+58216ms: eth_sendTransaction
T+58216ms:   Transaction: 0x68b29cce7dc71e70f8953138354371233370744be83d090affef75f36ffae800
T+58216ms:   Gas usage: 42023
T+58216ms:   Block Number: 9
T+58216ms:   Block Time: Fri Feb 28 2020 00:22:38 GMT-0800 (Pacific Standard Time)
T+58216ms: eth_getTransactionReceipt
T+58216ms: eth_getBlockByNumber
T+58216ms: eth_accounts
T+58216ms: eth_getBlockByNumber
T+58216ms: eth_getBlockByNumber
T+58216ms: eth_getBlockByNumber
T+58216ms: eth_estimateGas
T+58653ms: eth_getBlockByNumber
T+58653ms: eth_blockNumber
T+58653ms: eth_sendTransaction
T+58653ms:   Transaction: 0x9e0927bf480c48bf19fd02347557ac4678535aa7816ee5679d5a220bdd384cf2
T+58653ms:   Contract created: 0x6318071286a51ff1031eaebf2604a8eb43676475
T+58653ms:   Gas usage: 2276914
T+58653ms:   Block Number: 10
T+58653ms:   Block Time: Fri Feb 28 2020 00:22:39 GMT-0800 (Pacific Standard Time)
T+58653ms: eth_getTransactionReceipt
T+58653ms: eth_getCode
T+58653ms: eth_getTransactionByHash
T+58653ms: eth_getBlockByNumber
T+58653ms: eth_getBalance
T+58653ms: eth_getBlockByNumber
T+58653ms: eth_getBlockByNumber
T+58653ms: eth_sendTransaction
T+58653ms:   Transaction: 0x63c3b093d8dd9f7e22c24b067f10b2db1956b9162c5b7635a90a90778eabbd12
T+58653ms:   Gas usage: 27023
T+58653ms:   Block Number: 11
T+58653ms:   Block Time: Fri Feb 28 2020 00:22:39 GMT-0800 (Pacific Standard Time)
T+58653ms: eth_getTransactionReceipt
T+63682ms: eth_blockNumber
T+63682ms: eth_getBlockByNumber
T+78332ms: eth_unsubscribe
T+78332ms: eth_unsubscribe
T+87012ms: eth_blockNumber
T+89519ms: eth_unsubscribe
```

**Comment by davidmurdoch** [comment]
Should be fixed in https://github.com/trufflesuite/ganache/releases/tag/v2.3.0! Please let me know if you are still experiencing problems!
