### ISSUE TITLE
System Error when running Ganache 2.1.2 on win32

### ISSUE THREAD

**Issue by Pwnanand** [trufflesuite/ganache#1649]
PLATFORM: win32
GANACHE VERSION: 2.1.2

EXCEPTION:
```
Error: Hardfork muirGlacier not set as supported in supportedHardforks
    at Common.setHardfork (C:\Users\pawanand\Downloads\app\resources\app.asar\node_modules\ganache-core\node_modules\ethereumjs-common\src\index.ts:112:13)
    at new Common (C:\Users\pawanand\Downloads\app\resources\app.asar\node_modules\ganache-core\node_modules\ethereumjs-common\src\index.ts:79:12)
    at new VM (C:\Users\pawanand\Downloads\app\resources\app.asar\node_modules\ganache-core\node_modules\ethereumjs-vm\dist\index.js:62:21)
    at BlockchainDouble.createVMFromStateTrie (C:\Users\pawanand\Downloads\app\resources\app.asar\node_modules\ganache-core\lib\blockchain_double.js:130:14)
    at C:\Users\pawanand\Downloads\app\resources\app.asar\node_modules\ganache-core\lib\blockchain_double.js:85:36
    at C:\Users\pawanand\Downloads\app\resources\app.asar\node_modules\ganache-core\lib\blockchain_double.js:191:5
    at C:\Users\pawanand\Downloads\app\resources\app.asar\node_modules\ganache-core\lib\database\leveluparrayadapter.js:129:14
    at C:\Users\pawanand\Downloads\app\resources\app.asar\node_modules\ganache-core\lib\database\leveluparrayadapter.js:24:16
    at C:\Users\pawanand\Downloads\app\resources\app.asar\node_modules\ganache-core\node_modules\level-sublevel\shell.js:101:15
    at C:\Users\pawanand\Downloads\app\resources\app.asar\node_modules\ganache-core\node_modules\level-sublevel\nut.js:121:19
    at C:\Users\pawanand\Downloads\app\resources\app.asar\node_modules\ganache-core\node_modules\encoding-down\index.js:51:21
    at C:\Users\pawanand\Downloads\app\resources\app.asar\node_modules\ganache-core\node_modules\cachedown\index.js:58:21
    at ReadFileContext.callback (C:\Users\pawanand\Downloads\app\resources\app.asar\node_modules\ganache-core\lib\database\filedown.js:26:14)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
```

**Comment by davidmurdoch** [comment]
Fixed in https://github.com/trufflesuite/ganache/releases/tag/v2.3.0! Please let me know if you are still experiencing problems!

**Comment by Pwnanand** [comment]
thanks.. its working..
