### ISSUE TITLE
System Error when running Ganache 2.3.0-beta.2 on linux

### ISSUE THREAD

**Issue by kgcdream2019** [trufflesuite/ganache#1652]
PLATFORM: linux
GANACHE VERSION: 2.3.0-beta.2

EXCEPTION:
```
Error: Returned error: Returned error: project ID does not have access to archive state
    at Object.ErrorResponse (/tmp/.mount_ganachpEOzQI/resources/static/node/node_modules/web3-core-helpers/src/errors.js:29:16)
    at Object.<anonymous> (/tmp/.mount_ganachpEOzQI/resources/static/node/node_modules/web3-core-requestmanager/src/index.js:140:36)
    at /tmp/.mount_ganachpEOzQI/resources/static/node/node_modules/web3-providers-ws/src/index.js:127:44
    at Array.forEach (<anonymous>)
    at W3CWebSocket.WebsocketProvider.connection.onmessage (/tmp/.mount_ganachpEOzQI/resources/static/node/node_modules/web3-providers-ws/src/index.js:104:36)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/tmp/.mount_ganachpEOzQI/resources/static/node/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onMessage (/tmp/.mount_ganachpEOzQI/resources/static/node/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/tmp/.mount_ganachpEOzQI/resources/static/node/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at WebSocketConnection.emit (events.js:200:13)
    at WebSocketConnection.processFrame (/tmp/.mount_ganachpEOzQI/resources/static/node/node_modules/websocket/lib/WebSocketConnection.js:554:26)
    at /tmp/.mount_ganachpEOzQI/resources/static/node/node_modules/websocket/lib/WebSocketConnection.js:323:40
    at processTicksAndRejections (internal/process/task_queues.js:82:9)
```

**Comment by sterlu** [comment]
Experiencing this as well. Were you able to get it working?
