### ISSUE TITLE
System Error when running Ganache 2.1.2 on win32

### ISSUE THREAD

**Issue by LordOfTheBees** [trufflesuite/ganache#1660]
Within the contract, there is a limit on the creation of items (their number). To check this limitation a loop was started

`for (let i = 0; i < 10; ++i) {
       await testHelper.createItem(instance, dataToCreateItem, {from: owner});
}`

`async function createItem(instance, data, from){
    let result = await instance.createItem(data.oneData, data.anotherData, {from: from});
    try {
        await truffleAssert.eventEmitted(result , 'ItemCreated', async (res) => {
        });
    }
    catch(exception){
        console.log(exception);
    }
}`

PLATFORM: win32
GANACHE VERSION: 2.1.2

EXCEPTION:
```
RangeError: private key length is invalid
    at Object.exports.isBufferLength (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\ganache-core\node_modules\secp256k1\lib\assert.js:31:39)
    at Object.sign (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\ganache-core\node_modules\secp256k1\lib\index.js:173:14)
    at Object.exports.ecsign (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\ganache-core\node_modules\ethereumjs-tx\node_modules\ethereumjs-util\dist\index.js:369:23)
    at Transaction.sign (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\ganache-core\node_modules\ethereumjs-tx\es5\index.js:252:23)
    at Transaction.sign (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\ganache-core\lib\utils\transaction.js:270:10)
    at Transaction.hash (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\ganache-core\node_modules\ethereumjs-tx\fake.js:66:12)
    at Transaction.fakeHash [as hash] (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\ganache-core\lib\utils\transaction.js:17:51)
    at RuntimeError.combine (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\ganache-core\lib\utils\runtimeerror.js:42:30)
    at new RuntimeError (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\ganache-core\lib\utils\runtimeerror.js:19:8)
    at Function.RuntimeError.fromResults (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\ganache-core\lib\utils\runtimeerror.js:89:13)
    at C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\ganache-core\lib\blockchain_double.js:548:28
    at C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\ganache-core\node_modules\ethereumjs-vm\dist\runTx.js:74:9
    at C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\ganache-core\node_modules\async\dist\async.js:969:16
    at next (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\ganache-core\node_modules\async\dist\async.js:5225:18)
    at C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\ganache-core\node_modules\ethereumjs-vm\dist\state\cache.js:160:13
    at C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\ganache-core\node_modules\merkle-patricia-tree\util.js:51:36
```

APPLICATION LOG:
```
T+9745714ms: eth_sendTransaction
T+9745733ms:   Transaction: 0xaec325ad6fed9c8cd89a849036a22db6b86f1405f8199a2ae8a1747dc0d40159
T+9745733ms:   Gas usage: 22625
T+9745733ms:   Block Number: 1279
T+9745733ms:   Block Time: Fri Mar 06 2020 10:44:16 GMT+0300 (RTZ 2 (зима))
T+9745760ms:   Runtime Error: revert
T+9745760ms:   Revert reason: Market does not exist
T+9745779ms: eth_getBlockByNumber
T+9745806ms: eth_call
T+9745833ms: eth_getBlockByNumber
T+9745852ms: eth_sendTransaction
T+9745879ms:   Transaction: 0xd99347a554ae2f818ea4883261f2c3b9d45038e3569c999eb77cdcc4d10c8862
T+9745879ms:   Gas usage: 22625
T+9745879ms:   Block Number: 1280
T+9745898ms:   Block Time: Fri Mar 06 2020 10:44:16 GMT+0300 (RTZ 2 (зима))
T+9745898ms:   Runtime Error: revert
T+9745898ms:   Revert reason: Market does not exist
T+9745924ms: eth_getBlockByNumber
T+9745943ms: eth_call
T+9745969ms: eth_blockNumber
T+9745997ms: eth_getBlockByNumber
T+9746016ms: eth_sendTransaction
T+9746043ms:   Transaction: 0x5137ecbef9c91ffe7debfcfee99ca7e606f5ce9163235044597d44b8d7223744
T+9746043ms:   Gas usage: 130072
T+9746043ms:   Block Number: 1281
T+9746043ms:   Block Time: Fri Mar 06 2020 10:44:16 GMT+0300 (RTZ 2 (зима))
T+9746062ms: eth_getBlockByNumber
T+9746107ms: eth_getTransactionReceipt
T+9746134ms: eth_getBlockByNumber
T+9746161ms: eth_call
T+9746180ms: eth_getBlockByNumber
T+9746206ms: eth_sendTransaction
T+9746225ms:   Transaction: 0x3992ed377380801368c49709b22cb04230a25a25072d6811fefca679ca7e2057
T+9746225ms:   Gas usage: 83678
T+9746225ms:   Block Number: 1282
T+9746252ms:   Block Time: Fri Mar 06 2020 10:44:16 GMT+0300 (RTZ 2 (зима))
T+9746271ms: eth_getBlockByNumber
T+9746297ms: eth_getTransactionReceipt
T+9746324ms: eth_getBlockByNumber
T+9746343ms: eth_call
T+9746371ms: eth_getBlockByNumber
T+9746390ms: eth_call
T+9746416ms: eth_blockNumber
T+9746435ms: eth_getBlockByNumber
T+9746462ms: eth_call
T+9746490ms: eth_blockNumber
T+9746508ms: eth_getBlockByNumber
T+9746535ms: eth_sendTransaction
T+9746555ms:   Transaction: 0xef4605c3857560fa8e9efb24fe7a92e7f79d4b2c9aee80d90850f0e27b5d5828
T+9746555ms:   Gas usage: 130072
T+9746555ms:   Block Number: 1283
T+9746555ms:   Block Time: Fri Mar 06 2020 10:44:16 GMT+0300 (RTZ 2 (зима))
T+9746582ms: eth_getBlockByNumber
T+9746627ms: eth_getTransactionReceipt
T+9746655ms: eth_getBlockByNumber
T+9746674ms: eth_call
T+9746705ms: eth_getBlockByNumber
T+9746726ms: eth_sendTransaction
T+9746763ms: eth_call
T+9746841ms: eth_unsubscribe
T+9746930ms: eth_unsubscribe
T+9746953ms: eth_unsubscribe
T+9746953ms: eth_unsubscribe
```

**Comment by LordOfTheBees** [comment]
I found my mistake. Error right in the loop. However, the fact that ganache crashed after that looks like a bug
