### ISSUE TITLE
System Error when running Ganache 2.1.2 on win32

### ISSUE THREAD

**Issue by jschmiede** [trufflesuite/ganache#1673]
PLATFORM: win32
GANACHE VERSION: 2.1.2

EXCEPTION:
```
Error: CONNECTION ERROR: Couldn't connect to node on WS.
    at Object.InvalidConnection (C:\Users\jschm\AppData\Local\Programs\Ganache\resources\app.asar\node_modules\web3-core-helpers\src\errors.js:35:16)
    at WebsocketProvider._timeout (C:\Users\jschm\AppData\Local\Programs\Ganache\resources\app.asar\node_modules\web3-providers-ws\src\index.js:255:48)
    at W3CWebSocket.connection.onclose (C:\Users\jschm\AppData\Local\Programs\Ganache\resources\app.asar\node_modules\web3-providers-ws\src\index.js:155:15)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (C:\Users\jschm\AppData\Local\Programs\Ganache\resources\app.asar\node_modules\yaeti\lib\EventTarget.js:107:17)
    at W3CWebSocket.onClose (C:\Users\jschm\AppData\Local\Programs\Ganache\resources\app.asar\node_modules\websocket\lib\W3CWebSocket.js:228:10)
    at WebSocketConnection.<anonymous> (C:\Users\jschm\AppData\Local\Programs\Ganache\resources\app.asar\node_modules\websocket\lib\W3CWebSocket.js:201:17)
    at emitTwo (events.js:125:13)
    at WebSocketConnection.emit (events.js:213:7)
    at WebSocketConnection.handleSocketClose (C:\Users\jschm\AppData\Local\Programs\Ganache\resources\app.asar\node_modules\websocket\lib\WebSocketConnection.js:389:14)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at TCP._handle.close [as _onclose] (net.js:549:12)
```

APPLICATION LOG:
```
T+0ms: eth_unsubscribe
T+0ms: eth_unsubscribe
T+65ms: eth_unsubscribe
T+65ms: eth_unsubscribe
T+3687ms: Starting server (version 2.1.2) with initial configuration: {"gasLimit":6721975,"gasPrice":20000000000,"hardfork":"petersburg","db_path":"C:\\Users\\jschm\\AppData\\Roaming\\Ganache\\workspaces\\faithful-brain\\chaindata","default_balance_ether":100,"hostname":"127.0.0.1","locked":false,"network_id":5777,"port":8545,"total_accounts":10,"unlocked_accounts":[],"verbose":false,"vmErrorsOnRPCResponse":true}
T+4866ms: Ganache started successfully!
T+4866ms: Waiting for requests...
T+5015ms: eth_getCode
T+5130ms: eth_subscribe
T+5205ms: eth_getLogs
T+5262ms: eth_subscribe
T+5334ms: eth_getCode
T+60149ms: eth_blockNumber
T+60149ms: net_version
T+60149ms: eth_accounts
T+60703ms: eth_getBlockByNumber
T+60703ms: eth_accounts
T+60703ms: eth_getBlockByNumber
T+60703ms: eth_getBlockByNumber
T+60703ms: eth_getBlockByNumber
T+60703ms: eth_estimateGas
T+66059ms: eth_getBlockByNumber
T+66059ms: eth_blockNumber
T+66059ms: eth_sendTransaction
T+66059ms:   Transaction: 0x62b9bbda95d4a05afea3241cef597b69dcf8a05a2981e6149f6ba8228e5deb64
T+66059ms:   Contract created: 0xd612cd13445d349ecef692fb5d9603ea5b5b9dd1
T+66059ms:   Gas usage: 263741
T+66059ms:   Block Number: 1
T+66059ms:   Block Time: Mon Mar 16 2020 19:28:02 GMT-0300 (Hora verano Sudamérica Pacífico)
T+66059ms: eth_getTransactionReceipt
T+66512ms: eth_getCode
T+66512ms: eth_getTransactionByHash
T+66512ms: eth_getBlockByNumber
T+66512ms: eth_getBalance
T+66512ms: eth_getBlockByNumber
T+66512ms: eth_getBlockByNumber
T+66512ms: eth_sendTransaction
T+66955ms:   Transaction: 0x91adad1e45064d17f7a3a1b27e93330cac362a917c1f49a5acd5948baa942466
T+66955ms:   Gas usage: 42023
T+66955ms:   Block Number: 2
T+66955ms:   Block Time: Mon Mar 16 2020 19:28:03 GMT-0300 (Hora verano Sudamérica Pacífico)
T+66955ms: eth_getTransactionReceipt
T+66955ms: eth_getBlockByNumber
T+66955ms: eth_accounts
T+66955ms: eth_getBlockByNumber
T+66955ms: eth_getBlockByNumber
T+66955ms: eth_getBlockByNumber
T+66955ms: eth_estimateGas
T+67497ms: eth_getBlockByNumber
T+67497ms: eth_blockNumber
T+67497ms: eth_sendTransaction
T+68026ms:   Transaction: 0x4578abb9fcc254240d002f7a724b1fe84fe3aaf36050347c472e5272f01dddab
T+68026ms:   Contract created: 0x41eb10619c3e101724d3c2019247b5fcb993138d
T+68026ms:   Gas usage: 3224740
T+68026ms:   Block Number: 3
T+68026ms:   Block Time: Mon Mar 16 2020 19:28:04 GMT-0300 (Hora verano Sudamérica Pacífico)
T+68026ms: eth_getTransactionReceipt
T+68026ms: eth_getCode
T+68026ms: eth_getTransactionByHash
T+68026ms: eth_getBlockByNumber
T+68026ms: eth_getBalance
T+68771ms: eth_getBlockByNumber
T+68771ms: eth_getBlockByNumber
T+68771ms: eth_sendTransaction
T+69277ms:   Transaction: 0x5598a162be25d37e8b939ca5455a905cd132eb184ff1c2ecefd4fa9072ef56f0
T+69277ms:   Gas usage: 27023
T+69277ms:   Block Number: 4
T+69277ms:   Block Time: Mon Mar 16 2020 19:28:05 GMT-0300 (Hora verano Sudamérica Pacífico)
T+69277ms: eth_getTransactionReceipt
T+80063ms: eth_unsubscribe
T+80063ms: eth_unsubscribe
T+134881ms: eth_unsubscribe
```

**Comment by davidmurdoch** [comment]
Should be fixed in https://github.com/trufflesuite/ganache/releases/tag/v2.3.0! Please let me know if you are still experiencing problems!
