### ISSUE TITLE
System Error when running Ganache 2.1.2 on darwin

### ISSUE THREAD

**Issue by mmilliss** [trufflesuite/ganache#1675]
I've just downloaded Ganache and when I try to create a new workspace or view one of the pre-created ones I get the error below. I can delete the pre-created ones without seeing any errors.
While clicking the "new workspace" button does cause the error it does appear that a new workspace has been created after the relaunch. But clicking on the newly created workspace also generates the error.

The quickstart button generates the same error.

PLATFORM: darwin
GANACHE VERSION: 2.1.2

EXCEPTION:
```
Error: Hardfork muirGlacier not set as supported in supportedHardforks
    at Common.setHardfork (/node_modules/ganache-core/node_modules/ethereumjs-common/src/index.ts:112:13)
    at new Common (/node_modules/ganache-core/node_modules/ethereumjs-common/src/index.ts:79:12)
    at new VM (/node_modules/ganache-core/node_modules/ethereumjs-vm/dist/index.js:62:21)
    at BlockchainDouble.createVMFromStateTrie (/node_modules/ganache-core/lib/blockchain_double.js:130:14)
    at /node_modules/ganache-core/lib/blockchain_double.js:85:36
    at /node_modules/ganache-core/lib/blockchain_double.js:191:5
    at /node_modules/ganache-core/lib/database/leveluparrayadapter.js:129:14
    at /node_modules/ganache-core/lib/database/leveluparrayadapter.js:24:16
    at /node_modules/ganache-core/node_modules/level-sublevel/shell.js:101:15
    at /node_modules/ganache-core/node_modules/level-sublevel/nut.js:121:19
    at /node_modules/ganache-core/node_modules/encoding-down/index.js:51:21
    at /node_modules/ganache-core/node_modules/cachedown/index.js:58:21
    at ReadFileContext.callback (/node_modules/ganache-core/lib/database/filedown.js:26:14)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
```

**Comment by davidmurdoch** [comment]
Fixed in https://github.com/trufflesuite/ganache/releases/tag/v2.3.0! Please let me know if you are still experiencing problems!
