### ISSUE TITLE
System Error when running Ganache 2.1.2 on win32

### ISSUE THREAD

**Issue by HakanSahan** [trufflesuite/ganache#1697]
PLATFORM: win32
GANACHE VERSION: 2.1.2

EXCEPTION:
```
Error: CONNECTION ERROR: Couldn't connect to node on WS.
    at Object.InvalidConnection (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\web3-core-helpers\src\errors.js:35:16)
    at WebsocketProvider._timeout (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\web3-providers-ws\src\index.js:255:48)
    at W3CWebSocket.connection.onclose (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\web3-providers-ws\src\index.js:155:15)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\yaeti\lib\EventTarget.js:107:17)
    at W3CWebSocket.onClose (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\websocket\lib\W3CWebSocket.js:228:10)
    at WebSocketConnection.<anonymous> (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\websocket\lib\W3CWebSocket.js:201:17)
    at emitTwo (events.js:125:13)
    at WebSocketConnection.emit (events.js:213:7)
    at WebSocketConnection.handleSocketClose (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\websocket\lib\WebSocketConnection.js:389:14)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at TCP._handle.close [as _onclose] (net.js:549:12)
```

APPLICATION LOG:
```
T+0ms: eth_unsubscribe
T+0ms: eth_unsubscribe
T+2ms: eth_unsubscribe
T+2ms: eth_unsubscribe
T+2008ms: Starting server (version 2.1.2) with initial configuration: {"gasLimit":6721975,"gasPrice":0,"hardfork":"petersburg","db_path":"C:\\Users\\hakan\\AppData\\Roaming\\Ganache\\workspaces\\unkempt-eggs\\chaindata","default_balance_ether":100,"hostname":"127.0.0.1","locked":false,"network_id":5777,"port":7545,"total_accounts":10,"unlocked_accounts":[],"verbose":false,"vmErrorsOnRPCResponse":true}
T+2518ms: Ganache started successfully!
T+2518ms: Waiting for requests...
T+2568ms: eth_getCode
T+2698ms: eth_subscribe
T+2747ms: eth_getLogs
T+2788ms: eth_subscribe
T+2829ms: eth_getCode
T+2867ms: eth_getCode
T+2903ms: eth_getCode
T+2945ms: eth_getCode
T+2977ms: eth_getCode
T+3011ms: eth_getCode
T+3045ms: eth_getCode
T+25355ms: net_listening
T+37589ms: eth_blockNumber
T+37589ms: net_version
T+37589ms: eth_accounts
T+37589ms: eth_getBlockByNumber
T+37589ms: eth_accounts
T+37589ms: eth_getBlockByNumber
T+37589ms: eth_getBlockByNumber
T+37589ms: eth_getBlockByNumber
T+37589ms: eth_estimateGas
T+41104ms: eth_getBlockByNumber
T+41104ms: eth_blockNumber
T+41104ms: eth_sendTransaction
T+41104ms:   Transaction: 0x0722ee62e7efb7d6cf96f8226926283663420c5a7496274877206fdb8de6a40f
T+41104ms:   Contract created: 0x4c00f77eb6731a27776562997873ed578e97a2d3
T+41104ms:   Gas usage: 188419
T+41104ms:   Block Number: 16
T+41104ms:   Block Time: Mon Apr 06 2020 10:08:58 GMT+0200 (Romance Summer Time)
T+41104ms: eth_getTransactionReceipt
T+41104ms: eth_getCode
T+41104ms: eth_getTransactionByHash
T+41104ms: eth_getBlockByNumber
T+41104ms: eth_getBalance
T+41104ms: eth_getBlockByNumber
T+41104ms: eth_getBlockByNumber
T+41104ms: eth_sendTransaction
T+41104ms:   Transaction: 0x1f3d8b16e15983a06acf853af3f47c075ce2c1889f33c2c49ba0b71c06f29cc7
T+41104ms:   Gas usage: 42001
T+41104ms:   Block Number: 17
T+41104ms:   Block Time: Mon Apr 06 2020 10:08:59 GMT+0200 (Romance Summer Time)
T+41104ms: eth_getTransactionReceipt
T+41104ms: eth_getBlockByNumber
T+41104ms: eth_accounts
T+60590ms: eth_unsubscribe
T+60590ms: eth_unsubscribe
T+69049ms: eth_unsubscribe
```

**Comment by davidmurdoch** [comment]
Fixed in https://github.com/trufflesuite/ganache/releases/tag/v2.3.0! Please let me know if you are still experiencing problems!
