### ISSUE TITLE
Cancelling an Ethereum "New Workspace" creation followed by a "Quickstart" causes an Error modal

### ISSUE THREAD

**Issue by davidmurdoch** [trufflesuite/ganache#1699]
```bash
Error [ERR_SERVER_NOT_RUNNING]: Server is not running.
    at Server.close (net.js:1591:12)
    at Object.onceWrapper (events.js:299:28)
    at Server.emit (events.js:215:7)
    at emitCloseNT (net.js:1644:8)
    at processTicksAndRejections (internal/process/task_queues.js:79:21)
```

**Comment by davidmurdoch** [comment]
Fixed
