### ISSUE TITLE
System Error when running Ganache 2.3.0 on win32

### ISSUE THREAD

**Issue by Jeeth7** [trufflesuite/ganache#1709]
PLATFORM: win32
GANACHE VERSION: 2.3.0

EXCEPTION:
```
TypeError: Cannot read property 'provider' of null
    at C:\Program Files\WindowsApps\GanacheUI_2.3.0.0_x64__5dg5pnz03psnj\app\resources\static\node\chain\chain.js:141:43
    at Immediate.<anonymous> (C:\Program Files\WindowsApps\GanacheUI_2.3.0.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\ganache-core\lib\subproviders\geth_api_double.js:39:9)
    at processImmediate (internal/timers.js:439:21)
```

**Comment by davidmurdoch** [comment]
Heey @Jeeth7, can you provide any information as to what was happening at the time of this crash? From what I can tell, this error can only happen if the server is closed while it is still initializing.
