### ISSUE TITLE
System Error when running Ganache 2.2.1-alpha.0 on darwin

### ISSUE THREAD

**Issue by alexytlee** [trufflesuite/ganache#1713]
Updated only!

PLATFORM: darwin
GANACHE VERSION: 2.2.1-alpha.0

EXCEPTION:
```
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at ChildProcess.target.send (internal/child_process.js:678:16)
    at ee.send [as startServer] (/webpack:/src/common/services/ChainService.js:74:18)
    at ee.startServer (/webpack:/src/main/index.js:335:17)
    at ee.emit (events.js:200:13)
    at ee.emit [as start] (/webpack:/src/common/services/ChainService.js:67:12)
    at EventEmitter.start (/webpack:/src/main/index.js:584:15)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

**Comment by davidmurdoch** [comment]
Should be fixed in v2.3.0. Please update and let me know if this is still an issue for you: https://github.com/trufflesuite/ganache/releases/tag/v2.3.0
