### ISSUE TITLE
System Error when running Ganache 2.3.0 on win32

### ISSUE THREAD

**Issue by owari-taro** [trufflesuite/ganache#1721]
PLATFORM: win32
GANACHE VERSION: 2.3.0

EXCEPTION:
```
Error: EPERM: operation not permitted, rename 'C:\Users\shibaken\AppData\Roaming\Ganache\default\Settings.2587725031' -> 'C:\Users\shibaken\AppData\Roaming\Ganache\default\Settings'
    at Object.renameSync (fs.js:643:3)
    at writeFileSync (C:\Program Files\WindowsApps\GanacheUI_2.3.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\node_modules\write-file-atomic\index.js:124:8)
    at LocalStorage.setItem (C:\Program Files\WindowsApps\GanacheUI_2.3.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\node_modules\node-localstorage\LocalStorage.js:188:7)
    at JsonStorage_JsonStorage.setToStorage (C:\Program Files\WindowsApps\GanacheUI_2.3.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\json\JsonStorage.js:48:18)
    at JsonStorage_JsonStorage.setAll (C:\Program Files\WindowsApps\GanacheUI_2.3.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\json\JsonStorage.js:58:10)
    at WorkspaceSettings_WorkspaceSettings.setAll (C:\Program Files\WindowsApps\GanacheUI_2.3.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\settings\Settings.js:55:19)
    at WorkspaceSettings_WorkspaceSettings.bootstrap (C:\Program Files\WindowsApps\GanacheUI_2.3.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\settings\Settings.js:87:10)
    at Workspace_Workspace.bootstrap (C:\Program Files\WindowsApps\GanacheUI_2.3.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\workspaces\Workspace.js:83:19)
    at WorkspaceManager_WorkspaceManager.bootstrap (C:\Program Files\WindowsApps\GanacheUI_2.3.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\workspaces\WorkspaceManager.js:55:26)
    at C:\Program Files\WindowsApps\GanacheUI_2.3.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\index.js:211:22
```

**Comment by owari-taro** [comment]
it seems no problem after relaunch

**Comment by wbt** [comment]
I don't think this issue was actually fixed in the next release, per [this report](https://github.com/trufflesuite/ganache/issues/1768) and the several duplicates linked from there.
