### ISSUE TITLE
System Error when running Ganache 2.3.0 on darwin

### ISSUE THREAD

**Issue by eduardopezzi** [trufflesuite/ganache#1724]
PLATFORM: darwin
GANACHE VERSION: 2.3.0

EXCEPTION:
```
Error: dest already exists.
    at doRename (/node_modules/fs-extra/lib/move-sync/move-sync.js:25:34)
    at Object.moveSync (/node_modules/fs-extra/lib/move-sync/move-sync.js:17:10)
    at new Workspace_Workspace (/webpack:/src/main/types/workspaces/Workspace.js:27:11)
    at map (/webpack:/src/main/types/workspaces/WorkspaceManager.js:44:18)
    at Array.map (<anonymous>)
    at WorkspaceManager_WorkspaceManager.enumerateWorkspaces (/webpack:/src/main/types/workspaces/WorkspaceManager.js:21:10)
    at WorkspaceManager_WorkspaceManager.bootstrap (/webpack:/src/main/types/workspaces/WorkspaceManager.js:53:10)
    at /webpack:/src/main/index.js:211:22
```

**Comment by davidmurdoch** [comment]
Thanks for filing this issue! This issue has been fixed and will be released soon!
