### ISSUE TITLE
System Error when running Ganache 2.3.1 on win32 - NOT OPENING

### ISSUE THREAD

**Issue by AR-UNIT** [trufflesuite/ganache#1739]
PLATFORM: win32
GANACHE VERSION: 2.3.1

EXCEPTION:
```
Error: ENOENT: no such file or directory, rename 'C:\Users\ARBAIDYA\AppData\Roaming\Ganache\global\Settings.1137181279' -> 'C:\Users\ARBAIDYA\AppData\Roaming\Ganache\global\Settings'
    at Object.renameSync (fs.js:643:3)
    at writeFileSync (D:\WindowsApps\GanacheUI_2.3.1.0_x64__5dg5pnz03psnj\app\resources\app.asar\node_modules\write-file-atomic\index.js:124:8)
    at LocalStorage.setItem (D:\WindowsApps\GanacheUI_2.3.1.0_x64__5dg5pnz03psnj\app\resources\app.asar\node_modules\node-localstorage\LocalStorage.js:188:7)
    at JsonStorage_JsonStorage.setToStorage (D:\WindowsApps\GanacheUI_2.3.1.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\json\JsonStorage.js:48:18)
    at JsonStorage_JsonStorage.setAll (D:\WindowsApps\GanacheUI_2.3.1.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\json\JsonStorage.js:58:10)
    at GlobalSettings_GlobalSettings.setAll (D:\WindowsApps\GanacheUI_2.3.1.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\settings\Settings.js:55:19)
    at GlobalSettings_GlobalSettings.bootstrap (D:\WindowsApps\GanacheUI_2.3.1.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\settings\Settings.js:87:10)
    at GlobalSettings_GlobalSettings.bootstrap (D:\WindowsApps\GanacheUI_2.3.1.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\settings\GlobalSettings.js:15:11)
    at D:\WindowsApps\GanacheUI_2.3.1.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\index.js:210:12
```

**Comment by davidmurdoch** [comment]
Is this issue recurring every time you try to open Ganache?

**Comment by AR-UNIT** [comment]
Yes, every time. Even after I restart my computer and try to open Ganache this error still occurs. I am currently running an older version of Ganache instead(candy apple) and that works perfectly fine!
