### ISSUE TITLE
System Error when running Ganache 1.0.1 on linux

### ISSUE THREAD

**Issue by nicosquare** [trufflesuite/ganache#174]
Hi,

I'm trying to use Ganache in the tutorial of the Pet Shop. While migrating the contract i receive a terminal error:

`Using network 'development'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... 0xc3b0519c7fb4f4d7d05a4714f4e1ec3ae41ca700afba25654991a338d6e3dc83
  Migrations: 0x8cdaf0cd259887258bc13a92c0a6da92698644c0
Saving successful migration to network...
  ... 0xd7bc86d31bee32fa3988f1c1eabce403a1b5d570340a3a9cdba53a472ee8c956
Saving artifacts...
Running migration: 2_deploy_contracts.js
  Deploying Adoption...
  ... 0xbc23135362a8c1a34208a608f26b61d884b5785256f075648d35d180ab60072d
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: The contract code couldn't be stored, please check your gas amount.
    at Object.callback (/home/madog/.nvm/versions/node/v6.11.4/lib/node_modules/truffle/build/cli.bundled.js:326931:46)
    at /home/madog/.nvm/versions/node/v6.11.4/lib/node_modules/truffle/build/cli.bundled.js:37985:25
    at /home/madog/.nvm/versions/node/v6.11.4/lib/node_modules/truffle/build/cli.bundled.js:328869:9
    at /home/madog/.nvm/versions/node/v6.11.4/lib/node_modules/truffle/build/cli.bundled.js:176178:11
    at /home/madog/.nvm/versions/node/v6.11.4/lib/node_modules/truffle/build/cli.bundled.js:324536:9
    at XMLHttpRequest.request.onreadystatechange (/home/madog/.nvm/versions/node/v6.11.4/lib/node_modules/truffle/build/cli.bundled.js:327565:7)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/madog/.nvm/versions/node/v6.11.4/lib/node_modules/truffle/build/cli.bundled.js:176407:18)
    at XMLHttpRequest._setReadyState (/home/madog/.nvm/versions/node/v6.11.4/lib/node_modules/truffle/build/cli.bundled.js:176697:12)
    at XMLHttpRequest._onHttpResponseEnd (/home/madog/.nvm/versions/node/v6.11.4/lib/node_modules/truffle/build/cli.bundled.js:176852:12)
    at IncomingMessage.<anonymous> (/home/madog/.nvm/versions/node/v6.11.4/lib/node_modules/truffle/build/cli.bundled.js:176812:24)
`

And Ganache crashed.

Thanks!

PLATFORM: linux
GANACHE VERSION: 1.0.1

EXCEPTION:
Error: Lost heartbeat from server process!
    at Timeout.setInterval [as _onTimeout] (/src/Services/Chain.js:86:30)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

**Comment by benjamincburns** [comment]
Thanks for reporting this. The lost heartbeat crash should be fixed as of our latest release, v1.0.2, which is out just now!

Unfortunately, you may also be running afoul of trufflesuite/ganache-core#417. I'd suggest subscribing to that case for updates.
