### ISSUE TITLE
System Error when running Ganache 2.1.2 on linux

### ISSUE THREAD

**Issue by naszam** [trufflesuite/ganache#1745]
PLATFORM: linux
GANACHE VERSION: 2.1.2

EXCEPTION:
```
Error: Hardfork muirGlacier not set as supported in supportedHardforks
    at Common.setHardfork (/node_modules/ganache-core/node_modules/ethereumjs-common/src/index.ts:112:13)
    at new Common (/node_modules/ganache-core/node_modules/ethereumjs-common/src/index.ts:79:12)
    at new VM (/node_modules/ganache-core/node_modules/ethereumjs-vm/dist/index.js:62:21)
    at BlockchainDouble.createVMFromStateTrie (/node_modules/ganache-core/lib/blockchain_double.js:130:14)
    at /node_modules/ganache-core/lib/blockchain_double.js:85:36
    at /node_modules/ganache-core/lib/blockchain_double.js:191:5
    at /node_modules/ganache-core/lib/database/blockserializer.js:45:9
    at /node_modules/ganache-core/node_modules/async/dist/async.js:473:16
    at replenish (/node_modules/ganache-core/node_modules/async/dist/async.js:1006:25)
    at /node_modules/ganache-core/node_modules/async/dist/async.js:1016:9
    at eachLimit$1 (/node_modules/ganache-core/node_modules/async/dist/async.js:3196:24)
    at Object.<anonymous> (/node_modules/ganache-core/node_modules/async/dist/async.js:1046:16)
    at Object.decode (/node_modules/ganache-core/lib/database/blockserializer.js:29:11)
    at /node_modules/ganache-core/lib/database/leveluparrayadapter.js:40:21
    at /node_modules/ganache-core/node_modules/level-sublevel/shell.js:102:12
    at /node_modules/ganache-core/node_modules/level-sublevel/nut.js:122:19
```

**Comment by nicholasjpaterno** [comment]
Fixed in the latest release. Please update by downloading the release for your OS at https://www.trufflesuite.com/ganache

**Comment by naszam** [comment]
Just updated, Thanks!
