### ISSUE TITLE
System Error when running Ganache 2.3.2 on win32

### ISSUE THREAD

**Issue by mraxxi** [trufflesuite/ganache#1754]
PLATFORM: win32
GANACHE VERSION: 2.3.2

EXCEPTION:
```
Error: ENOENT: no such file or directory, open 'C:\Users\rofii\AppData\Roaming\Ganache\workspaces\Quickstart\Settings'
    at Object.openSync (fs.js:440:3)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.readFileSync (fs.js:342:35)
    at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
    at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
    at LocalStorage.getItem (C:\Program Files\WindowsApps\GanacheUI_2.3.2.0_x64__5dg5pnz03psnj\app\resources\app.asar\node_modules\node-localstorage\LocalStorage.js:208:19)
    at JsonStorage_JsonStorage.getFromStorage (C:\Program Files\WindowsApps\GanacheUI_2.3.2.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\json\JsonStorage.js:18:42)
    at JsonStorage_JsonStorage.get (C:\Program Files\WindowsApps\GanacheUI_2.3.2.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\json\JsonStorage.js:30:12)
    at WorkspaceSettings_WorkspaceSettings._getRaw (C:\Program Files\WindowsApps\GanacheUI_2.3.2.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\settings\Settings.js:23:26)
```

**Comment by mraxxi** [comment]
does the "PLATFORM: win32" mean my windows is 32 bit?
Just to clarify, I run 64-bit Windows on a 64-bit machine.
