### ISSUE TITLE
System Error when running Ganache 2.4.0 on win32

### ISSUE THREAD

**Issue by Git-Ashwin** [trufflesuite/ganache#1756]
PLATFORM: win32
GANACHE VERSION: 2.4.0

EXCEPTION:
```
Error: EXDEV: cross-device link not permitted, rename 'C:\Users\2017a\AppData\Roaming\Ganache\default\chaindata\ContractCache.3165518849' -> 'C:\Users\2017a\AppData\Roaming\Ganache\default\chaindata\ContractCache'
    at Object.renameSync (fs.js:643:3)
    at writeFileSync (D:\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\node_modules\write-file-atomic\index.js:124:8)
    at LocalStorage.setItem (D:\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\node_modules\node-localstorage\LocalStorage.js:188:7)
    at JsonStorage_JsonStorage.setToStorage (D:\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\json\JsonStorage.js:48:18)
    at JsonStorage_JsonStorage.setAll (D:\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\json\JsonStorage.js:58:10)
    at new ContractCache_ContractCache (D:\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\integrations\ethereum\main\types\contracts\ContractCache.js:12:20)
    at new Workspace_Workspace (D:\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\workspaces\Workspace.js:29:26)
    at WorkspaceManager_WorkspaceManager.enumerateWorkspaces (D:\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\workspaces\WorkspaceManager.js:56:26)
    at WorkspaceManager_WorkspaceManager.bootstrap (D:\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\workspaces\WorkspaceManager.js:61:10)
    at IpcMainImpl.<anonymous> (D:\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\index.js:398:22)
```

**Comment by davidmurdoch** [comment]
Thanks for opening this issue! Closing in favor of #1943.
