### ISSUE TITLE
System Error when running Ganache 2.3.2 on darwin

### ISSUE THREAD

**Issue by treyhunold** [trufflesuite/ganache#1758]
PLATFORM: darwin
GANACHE VERSION: 2.3.2

EXCEPTION:
```
Error: A file exists at the location '/Users/treyhunold/Library/Application Support/Ganache/workspaces/.DS_Store' when trying to create/open localStorage
    at LocalStorage._init (/node_modules/node-localstorage/LocalStorage.js:132:17)
    at new LocalStorage (/node_modules/node-localstorage/LocalStorage.js:121:12)
    at JsonStorage_JsonStorage.setStorageDirectory (/webpack:/src/main/types/json/JsonStorage.js:14:20)
    at new JsonStorage_JsonStorage (/webpack:/src/main/types/json/JsonStorage.js:9:10)
    at new super (/webpack:/src/main/types/settings/Settings.js:9:21)
    at new WorkspaceSettings_WorkspaceSettings (/webpack:/src/main/types/settings/WorkspaceSettings.js:22:5)
    at flatMap (/webpack:/src/main/types/workspaces/WorkspaceManager.js:21:26)
    at Array.flatMap (<anonymous>)
    at WorkspaceManager_WorkspaceManager.enumerateWorkspaces (/webpack:/src/main/types/workspaces/WorkspaceManager.js:17:10)
    at WorkspaceManager_WorkspaceManager.bootstrap (/webpack:/src/main/types/workspaces/WorkspaceManager.js:61:10)
```

**Comment by davidmurdoch** [comment]
Hi! Looks like you've navigated to Ganache's internal file directory. Mac's Finder leaves a file behind just by navigating there that Ganache doesn't expect. I hope to fix this issue soon, but for now, you'll need to delete the .DS_Store file at the described location manually via the terminal. Let me know if you need help. So sorry about this issue!
