### ISSUE TITLE
System Error when running Ganache 2.4.0 on win32

### ISSUE THREAD

**Issue by rlwns012** [trufflesuite/ganache#1768]
PLATFORM: win32
GANACHE VERSION: 2.4.0

EXCEPTION:
```
Error: EPERM: operation not permitted, rename 'C:\Users\rlwns\AppData\Roaming\Ganache\workspaces\Quickstart\Settings.299184470' -> 'C:\Users\rlwns\AppData\Roaming\Ganache\workspaces\Quickstart\Settings'
    at Object.renameSync (fs.js:643:3)
    at writeFileSync (C:\Users\rlwns\AppData\Local\Programs\Ganache\resources\app.asar\node_modules\write-file-atomic\index.js:124:8)
    at LocalStorage.setItem (C:\Users\rlwns\AppData\Local\Programs\Ganache\resources\app.asar\node_modules\node-localstorage\LocalStorage.js:188:7)
    at JsonStorage_JsonStorage.setToStorage (C:\Users\rlwns\AppData\Local\Programs\Ganache\resources\app.asar\webpack:\src\main\types\json\JsonStorage.js:48:18)
    at JsonStorage_JsonStorage.set (C:\Users\rlwns\AppData\Local\Programs\Ganache\resources\app.asar\webpack:\src\main\types\json\JsonStorage.js:53:10)
    at WorkspaceSettings_WorkspaceSettings.set (C:\Users\rlwns\AppData\Local\Programs\Ganache\resources\app.asar\webpack:\src\main\types\settings\Settings.js:59:19)
    at IpcMainImpl.<anonymous> (C:\Users\rlwns\AppData\Local\Programs\Ganache\resources\app.asar\webpack:\src\main\index.js:446:26)
```

**Comment by wbt** [comment]
This may be a duplicate of the issue reported in [#1466](https://github.com/trufflesuite/ganache/issues/1466).

**Comment by amitdubey26** [comment]
Is this issue solved in some build. I am facing same issue with latest build on windows 10. Is there any workaround for it

**Comment by wbt** [comment]
@amitdubey26 Are you getting the issue frequently or occasionally?

**Comment by amitdubey26** [comment]
Every single time.

**Comment by wbt** [comment]
Try these workaround steps independently and please report if any help:

- Exclude C:\Users\rlwns\AppData\Roaming\Ganache\workspaces from any automated backup system you might have running
- Create a new workspace instead of using quickstart
- Restart the machine (there may be some old handle to that directory/file hanging out somewhere that restarting would clear)
- Uninstall and verify C:\Users\rlwns\AppData\Roaming\Ganache\workspaces is gone; delete it if not; then reinstall
