### ISSUE TITLE
System Error when running Ganache 2.4.0 on win 10

### ISSUE THREAD

**Issue by aidaghergus** [trufflesuite/ganache#1779]
Ideas? 

GANACHE VERSION: 2.4.0

EXCEPTION:
```
Error: EPERM: operation not permitted, rename 'C:\Users\a-g.ghergus\AppData\Roaming\Ganache\workspaces\Quickstart\Settings.1043779722' -> 'C:\Users\a-g.ghergus\AppData\Roaming\Ganache\workspaces\Quickstart\Settings'
    at Object.renameSync (fs.js:643:3)
    at writeFileSync (C:\Program Files\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\node_modules\write-file-atomic\index.js:124:8)
    at LocalStorage.setItem (C:\Program Files\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\node_modules\node-localstorage\LocalStorage.js:188:7)
    at JsonStorage_JsonStorage.setToStorage (C:\Program Files\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\json\JsonStorage.js:48:18)
    at JsonStorage_JsonStorage.set (C:\Program Files\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\json\JsonStorage.js:53:10)
    at WorkspaceSettings_WorkspaceSettings.set (C:\Program Files\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\settings\Settings.js:59:19)
    at WorkspaceSettings_WorkspaceSettings.handleNewForkBlockNumber (C:\Program Files\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\settings\WorkspaceSettings.js:59:10)
    at EthereumChainService_EthereumChainService.<anonymous> (C:\Program Files\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\integrations\ethereum\index.js:34:26)
    at EthereumChainService_EthereumChainService.emit (events.js:215:7)
    at ChildProcess.<anonymous> (C:\Program Files\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\integrations\ethereum\common\services\EthereumChainService.js:44:18)
```

**Comment by wbt** [comment]
This issue seems to be a duplicate of [#1768](https://github.com/trufflesuite/ganache/issues/1768).

**Comment by Ganesh0412** [comment]
This error steps appears in version 2.5.4. Is there any solution to it? During the installation phase there is no error. But this errors appears when we click "Quickstart" or "New workspace" option.

**Comment by wbt** [comment]
Please check https://github.com/trufflesuite/ganache/issues/1768#issuecomment-649714882 and report if any of those steps help.
