### ISSUE TITLE
System Error when running Ganache 2.3.2 on win32

### ISSUE THREAD

**Issue by Mutekeri** [trufflesuite/ganache#1786]
PLATFORM: win32
GANACHE VERSION: 2.3.2

EXCEPTION:
```
Error: EPERM: operation not permitted, rename 'C:\Users\Michael\AppData\Roaming\Ganache\global\Settings.3142498300' -> 'C:\Users\Michael\AppData\Roaming\Ganache\global\Settings'
    at Object.renameSync (fs.js:643:3)
    at writeFileSync (C:\Program Files\WindowsApps\GanacheUI_2.3.2.0_x64__5dg5pnz03psnj\app\resources\app.asar\node_modules\write-file-atomic\index.js:124:8)
    at LocalStorage.setItem (C:\Program Files\WindowsApps\GanacheUI_2.3.2.0_x64__5dg5pnz03psnj\app\resources\app.asar\node_modules\node-localstorage\LocalStorage.js:188:7)
    at JsonStorage_JsonStorage.setToStorage (C:\Program Files\WindowsApps\GanacheUI_2.3.2.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\json\JsonStorage.js:48:18)
    at JsonStorage_JsonStorage.setAll (C:\Program Files\WindowsApps\GanacheUI_2.3.2.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\json\JsonStorage.js:58:10)
    at GlobalSettings_GlobalSettings.setAll (C:\Program Files\WindowsApps\GanacheUI_2.3.2.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\settings\Settings.js:55:19)
    at GlobalSettings_GlobalSettings.bootstrap (C:\Program Files\WindowsApps\GanacheUI_2.3.2.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\settings\Settings.js:87:10)
    at GlobalSettings_GlobalSettings.bootstrap (C:\Program Files\WindowsApps\GanacheUI_2.3.2.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\settings\GlobalSettings.js:15:11)
    at C:\Program Files\WindowsApps\GanacheUI_2.3.2.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\index.js:217:12
```

**Comment by wbt** [comment]
This issue seems to be a duplicate of [#1768](https://github.com/trufflesuite/ganache/issues/1768).
