### ISSUE TITLE
System Error when running Ganache 2.4.0 on win32

### ISSUE THREAD

**Issue by koumouts** [trufflesuite/ganache#1787]
Maybe I should install on C drive?

PLATFORM: win32
GANACHE VERSION: 2.4.0

EXCEPTION:
```
Error: EXDEV: cross-device link not permitted, rename 'C:\Users\Nick\AppData\Roaming\Ganache\default\chaindata\ContractCache.1285292312' -> 'C:\Users\Nick\AppData\Roaming\Ganache\default\chaindata\ContractCache'
    at Object.renameSync (fs.js:643:3)
    at writeFileSync (F:\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\node_modules\write-file-atomic\index.js:124:8)
    at LocalStorage.setItem (F:\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\node_modules\node-localstorage\LocalStorage.js:188:7)
    at JsonStorage_JsonStorage.setToStorage (F:\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\json\JsonStorage.js:48:18)
    at JsonStorage_JsonStorage.setAll (F:\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\json\JsonStorage.js:58:10)
    at new ContractCache_ContractCache (F:\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\integrations\ethereum\main\types\contracts\ContractCache.js:12:20)
    at new Workspace_Workspace (F:\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\workspaces\Workspace.js:29:26)
    at WorkspaceManager_WorkspaceManager.enumerateWorkspaces (F:\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\workspaces\WorkspaceManager.js:56:26)
    at WorkspaceManager_WorkspaceManager.bootstrap (F:\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\workspaces\WorkspaceManager.js:61:10)
    at IpcMainImpl.<anonymous> (F:\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\index.js:398:22)
```

**Comment by davidmurdoch** [comment]
Thanks for opening this issue! Closing in favor of #1943.
