### ISSUE TITLE
System Error when running Ganache 2.1.2 on win32

### ISSUE THREAD

**Issue by Shovon01** [trufflesuite/ganache#1810]
PLATFORM: win32
GANACHE VERSION: 2.1.2

EXCEPTION:
```
Error: EBUSY: resource busy or locked, rename 'C:\Users\Hp\AppData\Roaming\Ganache\default\Settings.445207931' -> 'C:\Users\Hp\AppData\Roaming\Ganache\default\Settings'
    at Object.fs.renameSync (fs.js:772:18)
    at writeFileSync (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\write-file-atomic\index.js:124:8)
    at LocalStorage.setItem (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\node-localstorage\LocalStorage.js:188:7)
    at JsonStorage.setToStorage (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\src\main\types\json\JsonStorage.js:72:20)
    at JsonStorage.set (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\src\main\types\json\JsonStorage.js:78:12)
    at WorkspaceSettings.set (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\src\main\types\settings\Settings.js:89:21)
    at EventEmitter.<anonymous> (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\src\main\main.js:505:32)
    at Generator.next (<anonymous>)
    at step (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\src\main\main.js:71:191)
    at C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\src\main\main.js:71:437
    at Promise (<anonymous>)
    at EventEmitter.<anonymous> (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\src\main\main.js:71:99)
    at EventEmitter.<anonymous> (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\src\main\main.js:531:23)
    at emitTwo (events.js:125:13)
    at EventEmitter.emit (events.js:213:7)
    at WebContents.<anonymous> (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\electron.asar\browser\api\web-contents.js:266:13)
```

**Comment by wbt** [comment]
Do you have an automated backup software or other software which might be accessing C:\Users\Hp\AppData\Roaming\Ganache\default\Settings.445207931 ?
