### ISSUE TITLE
System Error when running Ganache 2.4.0 on win32

### ISSUE THREAD

**Issue by Leonardo767** [trufflesuite/ganache#1813]
PLATFORM: win32
GANACHE VERSION: 2.4.0

EXCEPTION:
```
Error: EXDEV: cross-device link not permitted, rename 'C:\Users\Leonardo\AppData\Roaming\Ganache\global\Settings.3035734268' -> 'C:\Users\Leonardo\AppData\Roaming\Ganache\global\Settings'
    at Object.renameSync (fs.js:643:3)
    at writeFileSync (F:\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\node_modules\write-file-atomic\index.js:124:8)
    at LocalStorage.setItem (F:\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\node_modules\node-localstorage\LocalStorage.js:188:7)
    at JsonStorage_JsonStorage.setToStorage (F:\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\json\JsonStorage.js:48:18)
    at JsonStorage_JsonStorage.setAll (F:\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\json\JsonStorage.js:58:10)
    at GlobalSettings_GlobalSettings.setAll (F:\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\settings\Settings.js:55:19)
    at GlobalSettings_GlobalSettings.bootstrap (F:\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\settings\Settings.js:87:10)
    at GlobalSettings_GlobalSettings.bootstrap (F:\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\settings\GlobalSettings.js:15:11)
    at F:\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\index.js:229:12
```

**Comment by Leonardo767** [comment]
Looking in 'C:\Users\Leonardo\AppData\Roaming\Ganache', the 'global' folder, which should contain the settings, does not exist.

**Comment by Leonardo767** [comment]
PLATFORM: win32
GANACHE VERSION: 2.4.0

EXCEPTION:
```
Error: EXDEV: cross-device link not permitted, rename 'C:\Users\Leonardo\AppData\Roaming\Ganache\default\chaindata\ContractCache.1108457198' -> 'C:\Users\Leonardo\AppData\Roaming\Ganache\default\chaindata\ContractCache'
    at Object.renameSync (fs.js:643:3)
    at writeFileSync (F:\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\node_modules\write-file-atomic\index.js:124:8)
    at LocalStorage.setItem (F:\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\node_modules\node-localstorage\LocalStorage.js:188:7)
    at JsonStorage_JsonStorage.setToStorage (F:\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\json\JsonStorage.js:48:18)
    at JsonStorage_JsonStorage.setAll (F:\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\json\JsonStorage.js:58:10)
    at new ContractCache_ContractCache (F:\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\integrations\ethereum\main\types\contracts\ContractCache.js:12:20)
    at new Workspace_Workspace (F:\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\workspaces\Workspace.js:29:26)
    at WorkspaceManager_WorkspaceManager.enumerateWorkspaces (F:\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\workspaces\WorkspaceManager.js:56:26)
    at WorkspaceManager_WorkspaceManager.bootstrap (F:\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\workspaces\WorkspaceManager.js:61:10)
    at IpcMainImpl.<anonymous> (F:\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\index.js:398:22)
```

**Comment by Leonardo767** [comment]
The above error message is given when I relaunch Ganache. It's referring to something other than Settings.

**Comment by Leonardo767** [comment]
Sorry, I just realized that I needed to update my Node dependency (it was at v6).
