### ISSUE TITLE
System Error when running Ganache 2.3.0 on darwin

### ISSUE THREAD

**Issue by dsnathan6** [trufflesuite/ganache#1862]
PLATFORM: darwin
GANACHE VERSION: 2.3.0

EXCEPTION:
```
TypeError: Cannot read property 'address' of null
    at ProjectsWatcher.handleBlock (/Applications/Ganache.app/Contents/Resources/static/node/truffle-integration/projectsWatcher.js:208:24)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Subscription.<anonymous> (/Applications/Ganache.app/Contents/Resources/static/node/truffle-integration/projectsWatcher.js:57:9)
```

**Comment by davidmurdoch** [comment]
Duplicate of #8161
