### ISSUE TITLE
System Error when running Ganache 2.0.3-beta.0 on linux

### ISSUE THREAD

**Issue by Teban18** [trufflesuite/ganache#1871]
PLATFORM: linux
GANACHE VERSION: 2.0.3-beta.0

EXCEPTION:
```
Error: connection not open
    at WebsocketProvider.send (/node_modules/web3-providers-ws/src/index.js:282:18)
    at Timeout._onTimeout (/node_modules/web3-providers-ws/src/index.js:267:19)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
```

**Comment by Teban18** [comment]
The solution is here []( https://github.com/trufflesuite/ganache/releases/tag/v2.3.0), try installing the  appImage on ubuntu 
![imagen](https://user-images.githubusercontent.com/44687875/86844948-687a4300-c06e-11ea-9450-517e481ab2a6.png), then configure this file to be an executable in the properties.

**Comment by davidmurdoch** [comment]
Have you tried the latest version? https://github.com/trufflesuite/ganache/releases/tag/v2.4.0

**Comment by Teban18** [comment]
I'm going to trie it 👍
