### ISSUE TITLE
EPERM rename chaindata_tmp file error while running migration

### ISSUE THREAD

**Issue by wbt** [trufflesuite/ganache#1895]
## Expected Behavior
While running a Truffle migration, I expect output like this due to logging statements in the migration

>5_do_tasks_with_items.js
>\==============================
> Successfully did task 1 with item 1
> Successfully did task 1 with item 2
> Successfully did task 1 with item 3
> ...

with no errors.

## Current Behavior
Migration output includes:
>5_do_tasks_with_items.js
>\==============================
> Successfully did task 1 with item 1
> Successfully did task 1 with item 2
> Error when trying to do task 1 with item 3: { Error: Returned error: EPERM: operation not permitted, rename 'my\ganache\install\dir\workspaces\observant-spade\chaindata\_tmp\tmp-115964bHbHdiWvieLZ' -> 'my\ganache\install\dir\workspaces\observant-spade\chaindata\!blocks!length'
    at myFunction (my\project\dir\migrations\5_do_tasks_with_items.js:35:31)
    at my\project\dir\migrations\5_do_tasks_with_items.js:52:20
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
  hijackedStack: 'Error: Returned error: EPERM: operation not permitted, rename \'my\\ganache\\install\\dir\\workspaces\\observant-spade\\chaindata\\_tmp\\tmp-115964bHbHdiWvieLZ\' -> \'my\\ganache\\install\\dir\\workspaces\\observant-spade\\chaindata\\!blocks!length\'\n    at Object.ErrorResponse (globally\\installed\\node_modules\\truffle\\build\\webpack:\\node_modules\\web3-core-helpers\\src\\errors.js:29:1)\n    at globally\\installed\\node_modules\\truffle\\build\\webpack:\\node_modules\\web3-core-requestmanager\\src\\index.js:140:1\n    at globally\\installed\\node_modules\\truffle\\build\\webpack:\\packages\\provider\\wrapper.js:112:1\n    at XMLHttpRequest.request.onreadystatechange (globally\\installed\\node_modules\\truffle\\build\\webpack:\\node_modules\\web3-providers-http\\src\\index.js:96:1)\n    at XMLHttpRequestEventTarget.dispatchEvent (globally\\installed\\node_modules\\truffle\\build\\webpack:\\node_modules\\xhr2-cookies\\dist\\xml-http-request-event-target.js:34:1)\n    at XMLHttpRequest._setReadyState (globally\\installed\\node_modules\\truffle\\build\\webpack:\\node_modules\\xhr2-cookies\\dist\\xml-http-request.js:208:1)\n    at XMLHttpRequest._onHttpResponseEnd (globally\\installed\\node_modules\\truffle\\build\\webpack:\\node_modules\\xhr2-cookies\\dist\\xml-http-request.js:318:1)\n    at IncomingMessage.<anonymous> (globally\\installed\\node_modules\\truffle\\build\\webpack:\\node_modules\\xhr2-cookies\\dist\\xml-http-request.js:289:47)\n    at IncomingMessage.emit (events.js:164:20)\n    at endReadableNT (_stream_readable.js:1062:12)\n    at process._tickCallback (internal/process/next_tick.js:152:19)' }
>
>Error: Returned error: EPERM: operation not permitted, rename 'my\ganache\install\dir\workspaces\observant-spade\chaindata\_tmp\tmp-115964bHbHdiWvieLZ' -> 'my\ganache\install\dir\workspaces\observant-spade\chaindata\!blocks!length'
    at myFunction (my\project\dir\migrations\5_do_tasks_with_items.js:35:31)
    at my\project\dir\migrations\5_do_tasks_with_items.js:52:20
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)

The error is printed by code that basically looks like this:

    console.log("Error when trying to do task 1 with item "+itemNumber+":",error);
    reject(error);

accompanied by  

    }).catch(function(err) {
        console.log(err.message);
    });

in the calling context, so as to explain why the error prints twice with the formatting it has.  Some paths have been set to a description of the path instead of the path itself.

## Steps to Reproduce (for bugs)
Unfortunately, I don't have any reliable reproduction steps at present.  However, I can eliminate a few options:

- I wasn't doing anything in the Ganache interface at the time of the issue, nor had I done anything there other than create and save the workspace prior to starting the migration.
- my\ganache\install\dir\workspaces is excluded from automated backup
- I do not have third-party antivirus scanners running.

While I have seen Ganache errors pop up in the Ganache interface before, seeing one come out in the migrations command-line interface was new for me. 

## Your Environment
* Version used: 2.4.0
* Truffle v5.1.33 (core: 5.1.33)
* Node v9.3.0
* npm 6.14.5
* Operating System and version:  Windows 10

**Comment by davidmurdoch** [comment]
I believe this is related to https://github.com/trufflesuite/ganache-cli/issues/760#issuecomment-653553875
