### ISSUE TITLE
System Error when running Ganache 2.1.1 on win32

### ISSUE THREAD

**Issue by shailendrakumaromkar** [trufflesuite/ganache#1930]
I have Ganache 2.1.1 installed in my local system having Windows 10 OS.
After launching Ganache and clicking on New WorkSpace, got the error mentioned.
I tried Relaunch option as well but got same error.

Hence I am unable to create New Workspace.

Can you please look into this issue.

PLATFORM: win32
GANACHE VERSION: 2.1.1

EXCEPTION:
```
Error: EPERM: operation not permitted, rename 'C:\Users\om\AppData\Roaming\Ganache\workspaces\smelly-flight\Settings.2754183296' -> 'C:\Users\om\AppData\Roaming\Ganache\workspaces\smelly-flight\Settings'
    at Object.fs.renameSync (fs.js:772:18)
    at writeFileSync (C:\Program Files\Ganache\resources\app.asar\node_modules\write-file-atomic\index.js:124:8)
    at LocalStorage.setItem (C:\Program Files\Ganache\resources\app.asar\node_modules\node-localstorage\LocalStorage.js:188:7)
    at JsonStorage.setToStorage (C:\Program Files\Ganache\resources\app.asar\src\main\types\json\JsonStorage.js:72:20)
    at JsonStorage.set (C:\Program Files\Ganache\resources\app.asar\src\main\types\json\JsonStorage.js:78:12)
    at WorkspaceSettings.set (C:\Program Files\Ganache\resources\app.asar\src\main\types\settings\Settings.js:89:21)
    at Workspace.saveAs (C:\Program Files\Ganache\resources\app.asar\src\main\types\workspaces\Workspace.js:90:21)
    at EventEmitter.<anonymous> (C:\Program Files\Ganache\resources\app.asar\src\main\main.js:547:24)
    at Generator.next (<anonymous>)
    at step (C:\Program Files\Ganache\resources\app.asar\src\main\main.js:71:191)
    at C:\Program Files\Ganache\resources\app.asar\src\main\main.js:71:361
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by davidmurdoch** [comment]
Have you tried updating to 2.4.0?

**Comment by shailendrakumaromkar** [comment]
Yes, I tried in 2.4.0 as well, please refer below logs



System Error when running Ganache 2.4.0 on win32

PLATFORM: win32
GANACHE VERSION: 2.4.0

EXCEPTION:
```
TypeError: Cannot read property 'provider' of null
    at C:\Program Files\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\static\node\chain\chain.js:141:43
    at Immediate.<anonymous> (C:\Program Files\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\ganache-core\lib\subproviders\geth_api_double.js:39:9)
    at processImmediate (internal/timers.js:439:21)
```
