### ISSUE TITLE
System Error when running Ganache 2.4.0 on win32

### ISSUE THREAD

**Issue by miguelo12** [trufflesuite/ganache#1943]
PLATFORM: win32
GANACHE VERSION: 2.4.0

EXCEPTION:
```
Error: EXDEV: cross-device link not permitted, rename 'C:\Users\darkg\AppData\Roaming\Ganache\default\chaindata\ContractCache.3451224642' -> 'C:\Users\darkg\AppData\Roaming\Ganache\default\chaindata\ContractCache'
    at Object.renameSync (fs.js:643:3)
    at writeFileSync (G:\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\node_modules\write-file-atomic\index.js:124:8)
    at LocalStorage.setItem (G:\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\node_modules\node-localstorage\LocalStorage.js:188:7)
    at JsonStorage_JsonStorage.setToStorage (G:\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\json\JsonStorage.js:48:18)
    at JsonStorage_JsonStorage.setAll (G:\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\json\JsonStorage.js:58:10)
    at new ContractCache_ContractCache (G:\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\integrations\ethereum\main\types\contracts\ContractCache.js:12:20)
    at new Workspace_Workspace (G:\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\workspaces\Workspace.js:29:26)
    at WorkspaceManager_WorkspaceManager.enumerateWorkspaces (G:\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\workspaces\WorkspaceManager.js:56:26)
    at WorkspaceManager_WorkspaceManager.bootstrap (G:\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\workspaces\WorkspaceManager.js:61:10)
    at IpcMainImpl.<anonymous> (G:\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\index.js:398:22)
```

**Comment by davidmurdoch** [comment]
I'm unable to reproduce this specific stack trace locally. But this has likely already been fixed by https://github.com/trufflesuite/ganache/pull/2062, which will go into the next release.
