### ISSUE TITLE
System Error when running Ganache 2.4.0 on linux

### ISSUE THREAD

**Issue by rafinkarki** [trufflesuite/ganache#1959]
In Go I am using **go-ethereum** to read data from the ethereum smart contract. My smart contract is maintained with truffle.

I am trying to fetch candidate information based on candidate id. I have a modifier in the solidity that checks if given id exists or not as

```/**
     *  Check if candidate exists
     */
    modifier candidateExists(uint256 candidateId) {
        require(candidates[candidateId].exists, "No Candidate.");

        _;
    }```

Everything works perfectly fine if I pass valid candidateId. But exception occurs if candidates don't exist and revert. Following is the error recorded in ganache-cli console

PLATFORM: linux
GANACHE VERSION: 2.4.0

EXCEPTION:
```
Error: nonce generation function failed or private key is invalid
    at Object.exports.sign (/tmp/appimage_extracted_787ca113667850e6fc19b61f89882882/resources/static/node/node_modules/ganache-core/node_modules/secp256k1/lib/elliptic/index.js:207:51)
    at Object.sign (/tmp/appimage_extracted_787ca113667850e6fc19b61f89882882/resources/static/node/node_modules/ganache-core/node_modules/secp256k1/lib/index.js:192:24)
    at Object.exports.ecsign (/tmp/appimage_extracted_787ca113667850e6fc19b61f89882882/resources/static/node/node_modules/ganache-core/node_modules/ethereumjs-util/src/signature.ts:20:25)
    at Transaction.sign (/tmp/appimage_extracted_787ca113667850e6fc19b61f89882882/resources/static/node/node_modules/ganache-core/node_modules/ethereumjs-tx/src/transaction.ts:270:17)
    at Transaction.sign (/tmp/appimage_extracted_787ca113667850e6fc19b61f89882882/resources/static/node/node_modules/ganache-core/lib/utils/transaction.js:292:10)
    at Transaction.FakeTransaction.hash (/tmp/appimage_extracted_787ca113667850e6fc19b61f89882882/resources/static/node/node_modules/ganache-core/node_modules/ethereumjs-tx/src/fake.ts:57:12)
    at Transaction.fakeHash [as hash] (/tmp/appimage_extracted_787ca113667850e6fc19b61f89882882/resources/static/node/node_modules/ganache-core/lib/utils/transaction.js:18:51)
    at RuntimeError.combine (/tmp/appimage_extracted_787ca113667850e6fc19b61f89882882/resources/static/node/node_modules/ganache-core/lib/utils/runtimeerror.js:42:30)
    at new RuntimeError (/tmp/appimage_extracted_787ca113667850e6fc19b61f89882882/resources/static/node/node_modules/ganache-core/lib/utils/runtimeerror.js:19:8)
    at Function.RuntimeError.fromResults (/tmp/appimage_extracted_787ca113667850e6fc19b61f89882882/resources/static/node/node_modules/ganache-core/lib/utils/runtimeerror.js:89:13)
    at /tmp/appimage_extracted_787ca113667850e6fc19b61f89882882/resources/static/node/node_modules/ganache-core/lib/blockchain_double.js:573:26
```

**Comment by rafinkarki** [comment]
Is nobody interested in solving such issues? Pathetic :(
