### ISSUE TITLE
System Error when running Ganache 2.4.0 on linux

### ISSUE THREAD

**Issue by iliyabavar** [trufflesuite/ganache#1995]
PLATFORM: linux
GANACHE VERSION: 2.4.0

EXCEPTION:
```
Error: write EPIPE
    at ChildProcess.target._send (internal/child_process.js:806:20)
    at ChildProcess.target.send (internal/child_process.js:676:19)
    at eval (webpack-internal:///./src/integrations/ethereum/common/services/EthereumChainService.js:100:21)
    at new Promise (<anonymous>)
    at EthereumChainService.startServer (webpack-internal:///./src/integrations/ethereum/common/services/EthereumChainService.js:86:14)
    at Ethereum.startServer (webpack-internal:///./src/integrations/ethereum/index.js:146:23)
    at IntegrationManager.startServer (webpack-internal:///./src/integrations/index.js:101:27)
    at IpcMainImpl.eval (webpack-internal:///./src/main/index.js:422:28)
```

**Comment by iliyabavar** [comment]
hello . please help me . i try to install ganache on linux but it show me error . how can i fix it . 
Error: write EPIPE
    at ChildProcess.target._send (internal/child_process.js:806:20)
    at ChildProcess.target.send (internal/child_process.js:676:19)
    at eval (webpack-internal:///./src/integrations/ethereum/common/services/EthereumChainService.js:100:21)
    at new Promise (<anonymous>)
    at EthereumChainService.startServer (webpack-internal:///./src/integrations/ethereum/common/services/EthereumChainService.js:86:14)
    at Ethereum.startServer (webpack-internal:///./src/integrations/ethereum/index.js:146:23)
    at IntegrationManager.startServer (webpack-internal:///./src/integrations/index.js:101:27)
    at IpcMainImpl.eval (webpack-internal:///./src/main/index.js:422:28)     
thanks
