### ISSUE TITLE
System Error when running Ganache 2.4.0 on win32

### ISSUE THREAD

**Issue by sookylee** [trufflesuite/ganache#1997]
PLATFORM: win32
GANACHE VERSION: 2.4.0

EXCEPTION:
```
BigNumber Error: new BigNumber() not a base 16 number: 
    at raise (C:\Program Files\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\bignumber.js\bignumber.js:1177:25)
    at C:\Program Files\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\bignumber.js\bignumber.js:1165:33
    at new BigNumber (C:\Program Files\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\bignumber.js\bignumber.js:212:28)
    at SolidityTypeString.formatOutputString [as _outputFormatter] (C:\Program Files\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\abi-decoder\node_modules\web3\lib\solidity\formatters.js:220:19)
    at C:\Program Files\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\abi-decoder\node_modules\web3\lib\solidity\type.js:246:25
    at SolidityTypeString.SolidityType.decode (C:\Program Files\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\abi-decoder\node_modules\web3\lib\solidity\type.js:247:11)
    at C:\Program Files\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\abi-decoder\node_modules\web3\lib\solidity\type.js:216:34
    at SolidityTypeString.SolidityType.decode (C:\Program Files\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\abi-decoder\node_modules\web3\lib\solidity\type.js:220:11)
    at C:\Program Files\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\abi-decoder\node_modules\web3\lib\solidity\coder.js:223:29
    at Array.map (<anonymous>)
    at SolidityCoder.decodeParams (C:\Program Files\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\abi-decoder\node_modules\web3\lib\solidity\coder.js:222:26)
    at Object._decodeMethod [as decodeMethod] (C:\Program Files\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\abi-decoder\index.js:70:33)
    at TruffleContractDecoder.decodeTransaction (C:\Program Files\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\@truffle\decoder\lib\interface\contract-decoder.ts:448:36)
    at Object.getDecodedTransaction (C:\Program Files\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\static\node\truffle-integration\decode.js:62:37)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at process.<anonymous> (C:\Program Files\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\static\node\truffle-integration\index.js:122:11)
```

**Comment by sookylee** [comment]
I've solved this error.
The reason was in solidity function.
I sent string array as parameter, and that was the point. 
I'll close this issue.
Thanks,
