### ISSUE TITLE
System Error when running Ganache 2.3.0 on darwin

### ISSUE THREAD

**Issue by chrc** [trufflesuite/ganache#2032]
PLATFORM: darwin
GANACHE VERSION: 2.3.0

EXCEPTION:
```
Error: dest already exists.
    at doRename (/Users/christophe.charles/dev/blockchain/ethereum/tools/truffle/pullRequests/ganache/oldVersions/ganache/node_modules/fs-extra/lib/move-sync/move-sync.js:25:34)
    at Object.moveSync (/Users/christophe.charles/dev/blockchain/ethereum/tools/truffle/pullRequests/ganache/oldVersions/ganache/node_modules/fs-extra/lib/move-sync/move-sync.js:17:10)
    at new Workspace (webpack-internal:///./src/main/types/workspaces/Workspace.js:31:55)
    at eval (webpack-internal:///./src/main/types/workspaces/WorkspaceManager.js:44:16)
    at Array.map (<anonymous>)
    at WorkspaceManager.enumerateWorkspaces (webpack-internal:///./src/main/types/workspaces/WorkspaceManager.js:25:10)
    at WorkspaceManager.bootstrap (webpack-internal:///./src/main/types/workspaces/WorkspaceManager.js:53:10)
    at IpcMainImpl.eval (webpack-internal:///./src/main/index.js:393:22)
```

**Comment by davidmurdoch** [comment]
Please update to version 2.4.0 and try again (https://www.trufflesuite.com/ganache). Let me know if it's still a problem and I'll reopen the issue. Thanks!

**Comment by davidmurdoch** [comment]
Please update to version 2.4.0 and try again (https://www.trufflesuite.com/ganache). Let me know if it's still a problem and I'll reopen the issue. Thanks!
