### ISSUE TITLE
System Error when running Ganache 2.5.4 on win32

### ISSUE THREAD

**Issue by SarahSeif** [trufflesuite/ganache#2090]
PLATFORM: win32
GANACHE VERSION: 2.5.4

EXCEPTION:
```
Error: EXDEV: cross-device link not permitted, rename 'C:\Users\Asus\AppData\Roaming\Ganache\default_corda\chaindata\ContractCache.2054273396' -> 'C:\Users\Asus\AppData\Roaming\Ganache\default_corda\chaindata\ContractCache'
    at Object.renameSync (fs.js:643:3)
    at writeFileSync (D:\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\app.asar\node_modules\write-file-atomic\index.js:124:8)
    at Proxy.setItem (D:\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\app.asar\node_modules\node-localstorage\LocalStorage.js:217:7)
    at JsonStorage_JsonStorage.setToStorage (D:\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\json\JsonStorage.js:48:18)
    at JsonStorage_JsonStorage.setAll (D:\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\json\JsonStorage.js:58:10)
    at new ContractCache_ContractCache (D:\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\integrations\ethereum\main\types\contracts\ContractCache.js:12:20)
    at new Workspace_Workspace (D:\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\workspaces\Workspace.js:29:26)
    at WorkspaceManager_WorkspaceManager.enumerateWorkspaces (D:\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\workspaces\WorkspaceManager.js:72:26)
    at WorkspaceManager_WorkspaceManager.bootstrap (D:\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\workspaces\WorkspaceManager.js:76:10)
    at IpcMainImpl.<anonymous> (D:\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\index.js:404:22)
```

**Comment by davidmurdoch** [comment]
Thanks for opening this issue @SarahSeif, does this happen on every start of the corda chain or just the one time?

**Comment by SarahSeif** [comment]
it happens every time when i start the app but I found out its solution
I installed it in the D drive which is not the system drive
fixed when I reinstalled it in the C drive
