### ISSUE TITLE
Decoding Error when running Ganache 2.5.4 on linux

### ISSUE THREAD

**Issue by anas40** [trufflesuite/ganache#2115]
PLATFORM: linux
GANACHE VERSION: 2.5.4

EXCEPTION:
```
UnknownBaseContractIdError: Cannot locate base contract ID 822$ of contract$ Counterfeit (ID 680)
    at /tmp/.mount_ganachJhprfn/resources/static/node/node_modules/@truffle/decoder/lib/allocate/storage.ts:181:13
    at Array.map (<anonymous>)
    at allocateContract (/tmp/.mount_ganachJhprfn/resources/static/node/node_modules/@truffle/decoder/lib/allocate/storage.ts:178:59)
    at Object.getStorageAllocations (/tmp/.mount_ganachJhprfn/resources/static/node/node_modules/@truffle/decoder/lib/allocate/storage.ts:23:19)
    at TruffleContractDecoder.<anonymous> (/tmp/.mount_ganachJhprfn/resources/static/node/node_modules/@truffle/decoder/lib/interface/contract-decoder.ts:237:39)
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/.mount_ganachJhprfn/resources/static/node/node_modules/@truffle/decoder/dist/interface/contract-decoder.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by dievardump** [comment]
Hi @anas40 , did you happen to fix this? 

all my contracts on Linux have the same error which is very annoying to debug things.

**Comment by anas40** [comment]
@dievardump no luck, it is also crashing whenever i click to see a transaction's details.
