### ISSUE TITLE
eth_call crashes Ganache 2.5.4 on linux

### ISSUE THREAD

**Issue by donpdonp** [trufflesuite/ganache#2136]
Ganache crashes when `balance` is called in this contract using the web3 cli from https://github.com/gochain/web3
`web3 --rpc-url http://localhost:7545 contract call --address <deployed address> --abi TokenBank.abi --function balance <my address> <erc20 address>`

"Error: The nonce generation function failed, or the private key was invalid" since this is a `eth_call` RPC, the web3 tool sets the `from` parameter is set to all 0s in the transaction, not sure if thats part of the problem or not.

```json
{"jsonrpc":"2.0","id":1,"method":"eth_call","params":[{"data":"0xb203bb9900000000000000000000000079a27f42e11050d320cbb2669ad4e167fb4e957900000000000000000000000062ea3b746e8fad86de221e4ee94a61b644649cd1","from":"0x0000000000000000000000000000000000000000","to":"0x5f00c8a4dd8f0c5a656937c9d0356778efe9373e"},"latest"]}
```

```
// SPDX-License-Identifier: GPL-3.0
pragma solidity >=0.7.4 <0.8.0;

contract TokenBank {

  mapping (address => mapping (address => uint)) public balances;

  function addCoin(address erc20, uint256 amount) public {
    balances[msg.sender][erc20] += amount;
  }

  function takeCoin(address erc20, uint256 amount) public {
    require(amount <= balances[msg.sender][erc20], "insufficient balance for erc20 token");
    balances[msg.sender][erc20] -= amount;
  }

  function balance(address user, address erc20) external view returns (uint256) {
    return balances[user][erc20];
  }
}

```

PLATFORM: linux
GANACHE VERSION: 2.5.4

EXCEPTION:
```
Error: The nonce generation function failed, or the private key was invalid
    at Object.ecdsaSign (/tmp/.mount_ganachsd8b8J/resources/static/node/node_modules/ganache-core/node_modules/secp256k1/lib/index.js:265:17)
    at Object.exports.sign (/tmp/.mount_ganachsd8b8J/resources/static/node/node_modules/ganache-core/node_modules/ethereumjs-util/src/secp256k1v3-adapter.ts:334:25)
    at Object.exports.ecsign (/tmp/.mount_ganachsd8b8J/resources/static/node/node_modules/ganache-core/node_modules/ethereumjs-util/src/signature.ts:20:25)
    at Transaction.sign (/tmp/.mount_ganachsd8b8J/resources/static/node/node_modules/ganache-core/node_modules/ethereumjs-tx/src/transaction.ts:270:17)
    at Transaction.sign (/tmp/.mount_ganachsd8b8J/resources/static/node/node_modules/ganache-core/lib/utils/transaction.js:292:10)
    at Transaction.FakeTransaction.hash (/tmp/.mount_ganachsd8b8J/resources/static/node/node_modules/ganache-core/node_modules/ethereumjs-tx/src/fake.ts:57:12)
    at Transaction.fakeHash [as hash] (/tmp/.mount_ganachsd8b8J/resources/static/node/node_modules/ganache-core/lib/utils/transaction.js:18:51)
    at RuntimeError.combine (/tmp/.mount_ganachsd8b8J/resources/static/node/node_modules/ganache-core/lib/utils/runtimeerror.js:42:30)
    at new RuntimeError (/tmp/.mount_ganachsd8b8J/resources/static/node/node_modules/ganache-core/lib/utils/runtimeerror.js:19:8)
    at Function.RuntimeError.fromResults (/tmp/.mount_ganachsd8b8J/resources/static/node/node_modules/ganache-core/lib/utils/runtimeerror.js:94:13)
    at /tmp/.mount_ganachsd8b8J/resources/static/node/node_modules/ganache-core/lib/blockchain_double.js:568:26
```

**Comment by davidmurdoch** [comment]
Thanks for opening the issue. This is indeed because of the 0x0 address in the from parameter, which is an error itself (you should configure web3 so it doesn't send that address). This crash is caused by to this issue at etheremjs-vm: https://github.com/ethereumjs/ethereumjs-vm/issues/829.

**Comment by donpdonp** [comment]
with the From field missing from the RPC call, it no longer crashes. there is an VM exception but ganache stays running.

```json
{"id":1,"jsonrpc":"2.0","error":{"message":"VM Exception while processing transaction: revert","code":-32000,"data":{"0x98bb0e9aadd7f35e1319a925e550304f830003e19843f2382603d294602effac":{"error":"revert","program_counter":81,"return":"0x"},"stack":"RuntimeError: VM Exception while processing transaction: revert\n    at Function.RuntimeError.fromResults (/tmp/.mount_ganachs35qmB/resources/static/node/node_modules/ganache-core/lib/utils/runtimeerror.js:94:13)\n    at /tmp/.mount_ganachs35qmB/resources/static/node/node_modules/ganache-core/lib/blockchain_double.js:568:26","name":"RuntimeError"}}}
```
