### ISSUE TITLE
Ganache throws on calculation w/ >53 bits

### ISSUE THREAD

**Issue by fubuloubu** [trufflesuite/ganache#2154]
## Expected Behavior
Test cases pass!

## Current Behavior
During test execution, ganache throws and error and spoils the test run:
```
...
eth_sendTransaction

  Transaction: 0xf7d661285d3b1a577fcfc4cbcade805ae0d21c4eaca75699dace0312aca8dd30
  Gas usage: 61894
  Block Number: 10
Error: Number can only safely store up to 53 bits
    at assert (~/.nvm/versions/node/v12.19.0/lib/node_modules/ganache-cli/node_modules/bn.js/lib/bn.js:6:21)
    at BN.toNumber (~/.nvm/versions/node/v12.19.0/lib/node_modules/ganache-cli/node_modules/bn.js/lib/bn.js:506:7)
    at Object.t.bufferToInt (~/.nvm/versions/node/v12.19.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:4:148279)
    at Object.number (~/.nvm/versions/node/v12.19.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:4:67837)
    at ~/.nvm/versions/node/v12.19.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:219900
    at ~/.nvm/versions/node/v12.19.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:42:48553
    at ~/.nvm/versions/node/v12.19.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:2092107
    at ~/.nvm/versions/node/v12.19.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:4:21088
    at s (~/.nvm/versions/node/v12.19.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:4:24209)
    at ~/.nvm/versions/node/v12.19.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:4:24251
    at Bt (~/.nvm/versions/node/v12.19.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:4:33684)
    at Object.<anonymous> (~/.nvm/versions/node/v12.19.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:4:24340)
    at Object.decode (~/.nvm/versions/node/v12.19.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:2091974)
    at ~/.nvm/versions/node/v12.19.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:2057355
    at ~/.nvm/versions/node/v12.19.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:2062165
    at ~/.nvm/versions/node/v12.19.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:2059465
```

## Possible Solution
Add actual integers to JS

## Steps to Reproduce (for bugs)
1. clone branch from PR (below)
2. `brownie test test/integration`
3. ...profit!

## Context
It makes me sad

## Your Environment
* Ganache version: 6.12.1
* Node version: 12.19.0
* Operating System and version: ubuntu 20.04
* Brownie version: 1.11.12 (not using Truffle)
* Link to your project: https://github.com/iearn-finance/yearn-vaults/pull/69

**Comment by davidmurdoch** [comment]
Are you able to pin-point which test call is failing? Usually this error occurs when you accidentally pass in an ethereum address where a number is expected.

**Comment by davidmurdoch** [comment]
p.s. I'm very sorry we've made you sad :heart: :slightly_smiling_face:

**Comment by fubuloubu** [comment]
> Are you able to pin-point which test call is failing? Usually this error occurs when you accidentally pass in an ethereum address where a number is expected.

Not really, no but I will check if this is the case. I doubt it, because usually eth-abi Python library is very good about detecting mismatching w/ call types, but you never know.

**Comment by fubuloubu** [comment]
So, the current iteration of `tests/integration/test_calculation.py` is actually mining a ton of blocks (2.3m), this could be what causes it to fail

**Comment by fubuloubu** [comment]
I figured it out! I was setting the timestamp to an invalid value using `evm_increaseTime`. I was setting it to a number w/ 188 bits!
