### ISSUE TITLE
System Error when running Ganache 2.4.0 on win32

### ISSUE THREAD

**Issue by yashagrawal3107** [trufflesuite/ganache#2161]
PLATFORM: win32
GANACHE VERSION: 2.4.0

EXCEPTION:
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.basename (path.js:671:5)
    at FSWatcher.<anonymous> (C:\Program Files\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\static\node\truffle-integration\projectFsWatcher.js:98:18)
    at FSWatcher.emit (events.js:210:5)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:131:12)
```

**Comment by davidmurdoch** [comment]
Please update to Ganache 2.5.4 (https://www.trufflesuite.com/ganache) and try again. Let me know if it is still an issue for you after the update. Thanks!
