### ISSUE TITLE
System Error when running Ganache 2.5.4 on linux

### ISSUE THREAD

**Issue by jtatman** [trufflesuite/ganache#2227]
Using quickstart, changed a few things, default ethereum 1000 instead of 100, enabled logging to file but not verbose, used defaults for everything else, I believe. This was launched from my linux server as an x-windows forward to my windows workstation, using vcXsrv 1.20.1.4. Couple of restarts later on a similar, like nothing happened - but quickstart environment isn't available, so looks like it didn't commit. 

PLATFORM: linux
GANACHE VERSION: 2.5.4

EXCEPTION:
```
Error: CONNECTION ERROR: Couldn't connect to node on WS.
    at Object.InvalidConnection (/tmp/.mount_ganachFI2hcO/resources/static/node/node_modules/web3-providers-ws/node_modules/web3-core-helpers/src/errors.js:35:16)
    at WebsocketProvider._timeout (/tmp/.mount_ganachFI2hcO/resources/static/node/node_modules/web3-providers-ws/src/index.js:255:48)
    at W3CWebSocket.connection.onclose (/tmp/.mount_ganachFI2hcO/resources/static/node/node_modules/web3-providers-ws/src/index.js:155:15)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/tmp/.mount_ganachFI2hcO/resources/static/node/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onClose (/tmp/.mount_ganachFI2hcO/resources/static/node/node_modules/@web3-js/websocket/lib/W3CWebSocket.js:228:10)
    at WebSocketConnection.<anonymous> (/tmp/.mount_ganachFI2hcO/resources/static/node/node_modules/@web3-js/websocket/lib/W3CWebSocket.js:201:17)
    at WebSocketConnection.emit (events.js:210:5)
    at WebSocketConnection.handleSocketClose (/tmp/.mount_ganachFI2hcO/resources/static/node/node_modules/@web3-js/websocket/lib/WebSocketConnection.js:389:14)
    at Socket.emit (events.js:210:5)
    at TCP.<anonymous> (net.js:658:12)
```

**Comment by jtatman** [comment]
Here's the system info:

james@OptiPlex-780:~$ uname -a
Linux OptiPlex-780 5.4.0-54-generic #60~18.04.1-Ubuntu SMP Fri Nov 6 17:25:16 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Also, this is what's at the command line:

connection not open on send()

connection not open on send()

connection not open on send()
