### ISSUE TITLE
System Error when running Ganache 1.0.1 on win32

### ISSUE THREAD

**Issue by godhoomrohit** [trufflesuite/ganache#224]
I was following along the tutorial - http://truffleframework.com/tutorials/pet-shop
Upon "truffle test", got error in console and exception in Ganache.
Exception is thrown on 2nd run

PLATFORM: win32
GANACHE VERSION: 1.0.1

EXCEPTION:
Error: Lost heartbeat from server process!
    at Timeout.setInterval [as _onTimeout] (/src/Services/Chain.js:86:30)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

CONSOLE ERROR:
1st time execution:
Error: The contract code couldn't be stored, please check your gas amount.
    at Object.callback (C:\Users\anand\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:327595:46)
    at C:\Users\anand\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:37991:25
    at C:\Users\anand\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:329533:9
    at C:\Users\anand\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:176186:11
    at C:\Users\anand\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:325200:9
    at XMLHttpRequest.request.onreadystatechange (C:\Users\anand\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:328229:7)
    at XMLHttpRequestEventTarget.dispatchEvent (C:\Users\anand\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:176415:18)
    at XMLHttpRequest._setReadyState (C:\Users\anand\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:176705:12)
    at XMLHttpRequest._onHttpResponseEnd (C:\Users\anand\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:176860:12)
    at IncomingMessage.<anonymous> (C:\Users\anand\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:176820:24)

2nd time execution:
 TestAdoption "before all" hook: prepare suite:
     Error: Could not connect to your Ethereum client. Please check that your Ethereum client:
    - is running
    - is accepting RPC connections (i.e., "--rpc" option is used in geth)
    - is accessible over the network
    - is properly configured in your Truffle configuration file (truffle.js)

      at ProviderError.ExtendableError (C:\Users\anand\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:9401:17)
      at new ProviderError (C:\Users\anand\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:325054:24)
      at C:\Users\anand\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:325137:17
      at C:\Users\anand\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:325195:24
      at XMLHttpRequest.request.onreadystatechange (C:\Users\anand\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:328229:7)
      at XMLHttpRequestEventTarget.dispatchEvent (C:\Users\anand\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:176415:18)
      at XMLHttpRequest._setReadyState (C:\Users\anand\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:176705:12)
      at XMLHttpRequest._onHttpRequestError (C:\Users\anand\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:176895:12)
      at ClientRequest.<anonymous> (C:\Users\anand\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:176765:24)

**Comment by madhatter6822** [comment]
Check your node version, it threw this error on linux for me when I was using the wrong version. Ganache is built using node 8.3.0. Might fix your problem.

**Comment by benjamincburns** [comment]
Thanks for reporting this. The lost heartbeat crash (especially on sleep/wake) should be fixed as of our latest release, v1.0.2, which is out just now!

Unfortunately, you may also be running afoul of trufflesuite/ganache-core#417. I'd suggest subscribing to that case for updates.
