### ISSUE TITLE
System Error when running Ganache 2.5.4 on win32

### ISSUE THREAD

**Issue by scottb1978** [trufflesuite/ganache#2295]
I'm not sure exactly what happened. I was having troubles reproducing an issue which was working from remix but was producing very strange errors from the dapp. I thought I would just restart ganache but once stopped I couldn't start it again. I tried upgrading to the latest version and then uninstall/reinstalling from scratch but now ganche is completely broken for me :(

I've also looked to see if anything else is listening on the port its expecting to start on but there doesn't appear to be. 

PLATFORM: win32
GANACHE VERSION: 2.5.4

EXCEPTION:
```
Error: ENOENT: no such file or directory, open 'C:\Users\scott\AppData\Roaming\Ganache\workspaces\Quickstart\Settings'
    at Object.openSync (fs.js:440:3)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.readFileSync (fs.js:342:35)
    at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
    at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
    at Proxy.getItem (C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\app.asar\node_modules\node-localstorage\LocalStorage.js:237:19)
    at JsonStorage_JsonStorage.getFromStorage (C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\json\JsonStorage.js:18:42)
    at JsonStorage_JsonStorage.getAll (C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\json\JsonStorage.js:44:17)
    at WorkspaceSettings_WorkspaceSettings._getAllRaw (C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\settings\Settings.js:42:26)
```

**Comment by scottb1978** [comment]
I ended up deleting everything in this directory(%AppData%\Ganache\) after an uninstall and it seems to be ok again... phew :D
