### ISSUE TITLE
System Error when running Ganache 2.5.4 on linux

### ISSUE THREAD

**Issue by T00rk** [trufflesuite/ganache#2307]
PLATFORM: linux
GANACHE VERSION: 2.5.4

EXCEPTION:
```
UnknownUserDefinedTypeError: Cannot locate definition for struct Multihash$ (ID 308)
    at storageSizeAndAllocate (/tmp/.mount_ganachbss9T0/resources/static/node/node_modules/@truffle/decoder/lib/allocate/storage.ts:299:17)
    at allocateMembers (/tmp/.mount_ganachbss9T0/resources/static/node/node_modules/@truffle/decoder/lib/allocate/storage.ts:64:27)
    at allocateStruct (/tmp/.mount_ganachbss9T0/resources/static/node/node_modules/@truffle/decoder/lib/allocate/storage.ts:29:10)
    at Object.getStorageAllocations (/tmp/.mount_ganachbss9T0/resources/static/node/node_modules/@truffle/decoder/lib/allocate/storage.ts:19:21)
    at TruffleContractDecoder.<anonymous> (/tmp/.mount_ganachbss9T0/resources/static/node/node_modules/@truffle/decoder/lib/interface/contract-decoder.ts:237:39)
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/.mount_ganachbss9T0/resources/static/node/node_modules/@truffle/decoder/dist/interface/contract-decoder.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by T00rk** [comment]
Duplicate of #2301 
Sorry I used the automatic report function
