### ISSUE TITLE
System Error when running Ganache 1.0.1 on darwin

### ISSUE THREAD

**Issue by elie222** [trufflesuite/ganache#236]
I just opened my laptop after not using it for a few hours. This happens once or twice a day. Each time it happens after a period of inactivity:

PLATFORM: darwin
GANACHE VERSION: 1.0.1

EXCEPTION:
Error: Lost heartbeat from server process!
    at Timeout.setInterval [as _onTimeout] (/src/Services/Chain.js:86:30)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

**Comment by benjamincburns** [comment]
Thanks for reporting. Crash on sleep should be fixed as of v1.0.2, which has just been released!
