### ISSUE TITLE
System Error when running Ganache 1.0.1 on win32

### ISSUE THREAD

**Issue by tph1234** [trufflesuite/ganache#237]
Ganache is just sitting there, then it shuts down with this message. It does it many times repeatedly. Sometimes it dies when I deploy a contract using MyEtherWallet index page.

PLATFORM: win32
GANACHE VERSION: 1.0.1

EXCEPTION:
Error: Lost heartbeat from server process!
    at Timeout.setInterval [as _onTimeout] (/src/Services/Chain.js:86:30)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

**Comment by benjamincburns** [comment]
Thanks for reporting this issue. **Please update to the latest version of Ganache to fix this problem.** The heartbeat failure message has been fixed in our latest version of Ganache. Later versions of Ganache also include more helpful information when opening GitHub issues. Without this information, it is very difficult to diagnose the underlying problem. Because of the large number of independent reports of this issue, this is an automated message. Please reopen if you feel this issue warrants more attention.
