### ISSUE TITLE
System Error when running Ganache 2.6.0-beta.3 on win32

### ISSUE THREAD

**Issue by 786290704** [trufflesuite/ganache#2432]
PLATFORM: win32
GANACHE VERSION: 2.6.0-beta.3

EXCEPTION:
```
Error: EPERM: operation not permitted, rename 'C:\Users\Administrator.SC-202103071542\AppData\Roaming\Ganache\workspaces\labored-money\Settings.3160959276' -> 'C:\Users\Administrator.SC-202103071542\AppData\Roaming\Ganache\workspaces\labored-money\Settings'
    at Object.renameSync (fs.js:643:3)
    at writeFileSync (K:\Ganache\resources\app.asar\node_modules\write-file-atomic\index.js:124:8)
    at Proxy.setItem (K:\Ganache\resources\app.asar\node_modules\node-localstorage\LocalStorage.js:217:7)
    at JsonStorage_JsonStorage.setToStorage (K:\Ganache\resources\app.asar\webpack:\src\main\types\json\JsonStorage.js:48:18)
    at JsonStorage_JsonStorage.setAll (K:\Ganache\resources\app.asar\webpack:\src\main\types\json\JsonStorage.js:58:10)
    at WorkspaceSettings_WorkspaceSettings.setAll (K:\Ganache\resources\app.asar\webpack:\src\main\types\settings\Settings.js:55:19)
    at WorkspaceSettings_WorkspaceSettings.bootstrap (K:\Ganache\resources\app.asar\webpack:\src\main\types\settings\Settings.js:87:10)
    at flatMap (K:\Ganache\resources\app.asar\webpack:\src\main\types\workspaces\WorkspaceManager.js:44:20)
    at Array.flatMap (<anonymous>)
    at WorkspaceManager_WorkspaceManager.enumerateWorkspaces (K:\Ganache\resources\app.asar\webpack:\src\main\types\workspaces\WorkspaceManager.js:17:10)
```

**Comment by 786290704** [comment]
WIN64
