### ISSUE TITLE
System Error when running Ganache 1.6.11 on linux - ENOSPC

### ISSUE THREAD

**Issue by leochan007** [trufflesuite/ganache#244]
PLATFORM: linux
GANACHE VERSION: 1.6.11

EXCEPTION:
```
Error: watch /home/leo/Documents/src_codes/dapp/others/ganache/src/Elements/Modal.js ENOSPC
    at exports._errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1316:19)
    at Object.fs.watch (fs.js:1341:11)
    at Observable._Observable.Observable.create.subj [as _subscribe] (/home/leo/Documents/src_codes/dapp/others/ganache/node_modules/electron-compile/lib/pathwatcher-rx.js:29:34)
    at Observable._trySubscribe (/home/leo/Documents/src_codes/dapp/others/ganache/node_modules/rxjs/Observable.js:172:25)
    at Observable.subscribe (/home/leo/Documents/src_codes/dapp/others/ganache/node_modules/rxjs/Observable.js:160:65)
    at Observable.ConnectableObservable.connect (/home/leo/Documents/src_codes/dapp/others/ganache/node_modules/rxjs/observable/ConnectableObservable.js:40:18)
    at RefCountOperator.call (/home/leo/Documents/src_codes/dapp/others/ganache/node_modules/rxjs/operators/refCount.js:24:49)
    at Observable.subscribe (/home/leo/Documents/src_codes/dapp/others/ganache/node_modules/rxjs/Observable.js:157:22)
    at MapOperator.call (/home/leo/Documents/src_codes/dapp/others/ganache/node_modules/rxjs/operators/map.js:56:23)
```

APPLICATION LOG:
```
T+0ms: Starting server with configuration: {"gasLimit":1000000000,"gasPrice":1,"hostname":"127.0.0.1","mnemonic":"dog current climb visit hub neutral blood green nut effort brick glare","network_id":5777,"port":7545,"total_accounts":10,"unlocked_accounts":[]}
T+237ms: Ganache started successfully!
T+237ms: Waiting for requests...
```

**Comment by benjamincburns** [comment]
`ENOSPC` means that there's no space left on the drive. Try running `df -h` and see whether any of your drives are full?

**Comment by leochan007** [comment]
@benjamincburns not full.

**Comment by benjamincburns** [comment]
@leochan007 I'm afraid I don't recognize that version number. Can you please try with the latest build of Ganache 1.0.2 from our [releases page](https://github.com/trufflesuite/ganache/releases/tag/v1.0.2)?

**Comment by benjamincburns** [comment]
Also can you please report what distribution and version of that distribution you are running?

`cat /etc/issue*` does the trick on most distros for that.

**Comment by benjamincburns** [comment]
Closing this one, as I haven't heard back in over a month, and I've seen no other users reporting this problem.

**Comment by benjamincburns** [comment]
@leochan007 if you're still experiencing this problem, please respond back with the info I requested before and I'll happily help you look into it. Alternatively, ask for help in the [Truffle Gitter Channel](https://gitter.im/ConsenSys/truffle).
