### ISSUE TITLE
UnhandledPromiseRejectionWarning when using BatchRequest

### ISSUE THREAD

**Issue by JSRossiter** [trufflesuite/ganache#2469]
## Expected Behavior

When part of a [BatchRequest](https://web3js.readthedocs.io/en/v1.2.0/web3-eth.html#batchrequest) fails an error should be returned for the relevant request(s) along with successful responses.

## Current Behavior

Nothing is returned to the client and the below is output.
```
(node:4257) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'data' of undefined
    at l.reportErrorInResponse (/Users/jeff/.nvm/versions/node/v14.9.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:42:16635)
    at Object.a [as callback] (/Users/jeff/.nvm/versions/node/v14.9.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:42:14766)
    at /Users/jeff/.nvm/versions/node/v14.9.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:42:15708
    at /Users/jeff/.nvm/versions/node/v14.9.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:171433
    at /Users/jeff/.nvm/versions/node/v14.9.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:42:34025
    at d (/Users/jeff/.nvm/versions/node/v14.9.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:165220)
    at /Users/jeff/.nvm/versions/node/v14.9.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:42:34266
    at /Users/jeff/.nvm/versions/node/v14.9.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:171410
    at /Users/jeff/.nvm/versions/node/v14.9.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:70064
    at /Users/jeff/.nvm/versions/node/v14.9.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:42:34025
    at p (/Users/jeff/.nvm/versions/node/v14.9.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:42:33682)
    at /Users/jeff/.nvm/versions/node/v14.9.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:42:33735
    at t.default (/Users/jeff/.nvm/versions/node/v14.9.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:171665)
    at /Users/jeff/.nvm/versions/node/v14.9.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:42:34649
    at Object.o [as callback] (/Users/jeff/.nvm/versions/node/v14.9.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:69913)
    at n (/Users/jeff/.nvm/versions/node/v14.9.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:217892)
```

## Steps to Reproduce

Execute a Batch Request where one request reverts

## Your Environment

* Ganache version: Ganache CLI v6.12.1 (ganache-core: 2.13.1)
* Node version: 14.9.0
* Operating System and version: MacOS 11.2.3

**Comment by JSRossiter** [comment]
Realized this should be on ganache-core, and that they have an open issue, oops.
