### ISSUE TITLE
System Error when running Ganache 2.5.4 on darwin

### ISSUE THREAD

**Issue by eherrador** [trufflesuite/ganache#2536]
PLATFORM: darwin
GANACHE VERSION: 2.5.4

EXCEPTION:
```
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at ChildProcess.target.send (internal/child_process.js:678:16)
    at eval (webpack-internal:///./src/integrations/filecoin/common/services/FilecoinChainService.js:100:21)
    at new Promise (<anonymous>)
    at FilecoinChainService.startServer (webpack-internal:///./src/integrations/filecoin/common/services/FilecoinChainService.js:86:14)
    at Filecoin.startServer (webpack-internal:///./src/integrations/filecoin/index.js:79:23)
    at IntegrationManager.startServer (webpack-internal:///./src/integrations/index.js:104:27)
    at IpcMainImpl.eval (webpack-internal:///./src/main/index.js:430:28)
```

**Comment by eherrador** [comment]
I was trying to run Filecoin on Ganache following this post: https://www.trufflesuite.com/boxes/filecoin

**Comment by eherrador** [comment]
┏ Electron -------------------

  Debugger listening on ws://127.0.0.1:5858/a7c9faff-0a5c-4554-983e-9a940449a3e4
  For help, see: https://nodejs.org/en/docs/inspector

┗ ----------------------------
┏ Electron -------------------

  DevTools listening on ws://127.0.0.1:9222/devtools/browser/07175902-2625-4216-b2a8-b0b1a51ed869

┗ ----------------------------
┏ Electron -------------------

  Renderer debugger is listening on port 9222

┗ ----------------------------
┏ Electron -------------------

  (node:20173) DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9.

┗ ----------------------------
