### ISSUE TITLE
Ganache crashes on invalid transaction parameters

### ISSUE THREAD

**Issue by stormsson** [trufflesuite/ganache#257]
Ganache crashed after receiving a deploy contract transaction;

- the system has been on sleep mode;
- after that ganache has been restarted more than once 

PLATFORM: darwin
GANACHE VERSION: **1.0.1**

EXCEPTION:
Error: Lost heartbeat from server process!
    at Timeout.setInterval [as _onTimeout] (/src/Services/Chain.js:86:30)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

After downloading 1.0.2 the Exception becomes:
PLATFORM: darwin
GANACHE VERSION: **1.0.2**

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+0ms: Starting server with configuration: {"hostname":"127.0.0.1","mnemonic":"candy maple cake sugar pudding cream honey rich smooth crumble sweet treat","network_id":5777,"port":7544,"total_accounts":10,"unlocked_accounts":[]}
T+267ms: Ganache started successfully!
T+267ms: Waiting for requests...
T+14497ms: eth_blockNumber
T+19696ms: eth_estimateGas
T+29989ms: eth_estimateGas
T+31972ms: eth_getBalance
T+31972ms: eth_gasPrice
T+31972ms: eth_getTransactionCount
T+32023ms: eth_getBalance
T+32023ms: eth_gasPrice
T+32023ms: eth_getTransactionCount
T+32093ms: eth_estimateGas
T+32100ms: 
T+32100ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+32100ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_W
T+32114ms: AssertionError: The field to must have byte length of 20
T+32114ms:     at FakeTransaction.setter [as to] (/node_modules/ganache-cli/build/lib.node.js:7366:9)
T+32114ms:     at /node_modules/ganache-cli/build/lib.node.js:7416:63
T+32114ms:     at Array.forEach (native)
T+32114ms:     at Object.exports.defineProperties (/node_modules/ganache-cli/build/lib.node.js:7415:14)
T+32114ms:     at FakeTransaction.Transaction (/node_modules/ganache-cli/build/lib.node.js:78121:13)
T+32114ms:     at FakeTransaction (/node_modules/ganache-cli/build/lib.node.js:20454:5)
T+32114ms:     at /node_modules/ganache-cli/build/lib.node.js:80343:14
T+32114ms:     at /node_modules/ganache-cli/build/lib.node.js:21924:5
T+32114ms:     at /node_modules/ganache-cli/build/lib.node.js:55954:5
T+32114ms:     at /node_modules/ganache-cli/build/lib.node.js:56320:14
```

**Comment by benjamincburns** [comment]
Hi @stormsson. it should be impossible to get the “Lost heartbeat” error in 1.0.2. We literally deleted it from the code. Can you please use the “Raise Github Issue” button in 1.0.2 and copy/paste the exception and application logs over to this issue rather than raising a new, separate issue?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by benjamincburns** [comment]
@stormsson by any chance are you running a transaction without the `from` field populated?

**Comment by benjamincburns** [comment]
Reproduction code (to turn into a test later):

```javascript
let pify = require('pify')
let Web3 = require('web3') // assuming web3 1.0
let assert = require('assert')

let web3 = new Web3('http://localhost:7545')

(async function reproduction() {
  let accounts = await web3.eth.getAccounts()
  let result = await pify(web3._provider.send)({
    jsonrpc: 2.0,
    id: 123,
    method: 'eth_sendTransaction',
    params:[{
      from: accounts[0],
      to: '0x123',
      value: web3.utils.toWei('1', 'ether')
    }]
  })

  assert(result)
  assert.equal(null, result.error)
})()
```

**Comment by benjamincburns** [comment]
This crash is now fixed on the `develop` branch of [`ganache-core`](https://github.com/trufflesuite/ganache-core) and will go out with the next `Ganache` release.

**Comment by benjamincburns** [comment]
That assessment is correct, but you're passing an empty string. You shouldn't be passing the `to` parameter at all.

**Comment by stormsson** [comment]
Thank you, everything is actually generated automatically by mew but now at least i can check where's the problem

**Comment by benjamincburns** [comment]
This is either another problem we should fix, or a bug which should be reported to MEW. If the other clients accept empty string as null, then likely the prior.

**Comment by stormsson** [comment]
should i open an enhanchement issue on the topic ?

**Comment by benjamincburns** [comment]
Sure. Thanks!
