### ISSUE TITLE
System Error when running Ganache 2.5.4 on darwin

### ISSUE THREAD

**Issue by gen4sp** [trufflesuite/ganache#2624]
It happens after calling the mint function of standard ERC721 (ERC721PresetMinterPauserAutoId)
Not sure what's going on. Any ideas?

PLATFORM: darwin
GANACHE VERSION: 2.5.4

EXCEPTION:
```
TypeError: Cannot read property 'address' of undefined
    at ProjectsWatcher.handleBlock (/Applications/Ganache.app/Contents/Resources/static/node/truffle-integration/projectsWatcher.js:208:24)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Subscription.<anonymous> (/Applications/Ganache.app/Contents/Resources/static/node/truffle-integration/projectsWatcher.js:57:9)
```

**Comment by fdchiu** [comment]
any resolution on this? seeing the same crash...
