### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by almighty972** [trufflesuite/ganache#263]
I'm unable to sign a transaction (with a Ganache Account private key) with a Ganache without having a crash..

PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+0ms: Starting server with configuration: {"hostname":"127.0.0.1","mnemonic":"candy maple cake sugar pudding cream honey rich smooth crumble sweet treat","network_id":5777,"port":7545,"total_accounts":10,"unlocked_accounts":[]}
T+134ms: Ganache started successfully!
T+134ms: Waiting for requests...
T+23396ms: eth_blockNumber
T+81151ms: eth_estimateGas
T+106689ms: eth_estimateGas
T+120447ms: eth_getBalance
T+120447ms: eth_gasPrice
T+120447ms: eth_getTransactionCount
T+120468ms: eth_getBalance
T+120468ms: eth_gasPrice
T+120468ms: eth_getTransactionCount
T+120530ms: eth_estimateGas
T+120536ms: 
T+120536ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+120536ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+120536ms: AssertionError: The field to must have byte length of 20
T+120536ms:     at FakeTransaction.setter [as to] (/node_modules/ganache-cli/build/lib.node.js:7366:9)
T+120536ms:     at /node_modules/ganache-cli/build/lib.node.js:7416:63
T+120536ms:     at Array.forEach (native)
T+120536ms:     at Object.exports.defineProperties (/node_modules/ganache-cli/build/lib.node.js:7415:14)
T+120536ms:     at FakeTransaction.Transaction (/node_modules/ganache-cli/build/lib.node.js:78121:13)
T+120536ms:     at FakeTransaction (/node_modules/ganache-cli/build/lib.node.js:20454:5)
T+120536ms:     at /node_modules/ganache-cli/build/lib.node.js:80343:14
T+120536ms:     at /node_modules/ganache-cli/build/lib.node.js:21924:5
T+120536ms:     at /node_modules/ganache-cli/build/lib.node.js:55954:5
T+120536ms:     at /node_modules/ganache-cli/build/lib.node.js:56320:14
```

**Comment by almighty972** [comment]
Seems to be fixed on `develop` branch (see #257)
