### ISSUE TITLE
Problem with Ganache 1.0.2 install , Version 1.0.1 went fine a month ago

### ISSUE THREAD

**Issue by pszwec** [trufflesuite/ganache#266]
I typed "npm install" in the extracted Ganache folder on a Windows 10 computer. The install ran for a while but the last 50 lines or so had errors and warnings.

OK, I am in Windows and tried to debug. It's looks like something called sharp can't install. I have all the SDK tools installed. Like I wrote in the title, 1.0.1 installed perfectly. I will paste the last 50 lines of the install log as that's where the errors appeared. The 1st 10,000 lines started with silly or info.

I didn't uninstall Ganache 1.0.1 first but didn't see in the read me that I had to. I don't see Ganace in Control Panel, Programs so I don't know how to uninstall it anyway. (Other than delete the folder)

I also tried opening my command prompt as administrator and running it. Same result.

Thanks in advance for your help, 
Peter

## Your Environment
Windows 10 Pro, 64 bit.

38011 info lifecycle sharp@0.18.4~install: sharp@0.18.4
38012 verbose lifecycle sharp@0.18.4~install: unsafe-perm in lifecycle true
38013 verbose lifecycle sharp@0.18.4~install: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\pszwe\Downloads\ganache-develop (1)\ganache-develop\node_modules\sharp\node_modules\.bin;C:\Users\pszwe\Downloads\ganache-develop (1)\ganache-develop\node_modules\.bin;C:\Users\pszwe\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Users\pszwe\AppData\Local\Microsoft\WindowsApps;C:\Users\pszwe\AppData\Roaming\npm;;C:\Program Files\Microsoft VS Code\bin
38014 verbose lifecycle sharp@0.18.4~install: CWD: C:\Users\pszwe\Downloads\ganache-develop (1)\ganache-develop\node_modules\sharp
38015 silly lifecycle sharp@0.18.4~install: Args: [ '/d /s /c', 'node-gyp rebuild' ]
38016 silly lifecycle sharp@0.18.4~install: Returned: code: 1  signal: null
38017 info lifecycle sharp@0.18.4~install: Failed to exec install script
38018 verbose unlock done using C:\Users\pszwe\AppData\Roaming\npm-cache\_locks\staging-e6fed86b818f7507.lock for C:\Users\pszwe\Downloads\ganache-develop (1)\ganache-develop\node_modules\.staging
38019 warn optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@1.0.1 (node_modules\7zip-bin-mac):
38020 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-mac@1.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
38021 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
38021 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
38021 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
38021 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
38022 warn optional SKIPPING OPTIONAL DEPENDENCY: appdmg@0.4.5 (node_modules\appdmg):
38023 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for appdmg@0.4.5: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
38024 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
38024 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
38024 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
38024 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
38025 warn optional SKIPPING OPTIONAL DEPENDENCY: electron-installer-debian@0.7.1 (node_modules\electron-installer-debian):
38026 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for electron-installer-debian@0.7.1: wanted {"os":"darwin,linux","arch":"any"} (current: {"os":"win32","arch":"x64"})
38027 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin,linux
38027 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
38027 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
38027 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
38028 warn optional SKIPPING OPTIONAL DEPENDENCY: electron-installer-redhat@0.5.0 (node_modules\electron-installer-redhat):
38029 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for electron-installer-redhat@0.5.0: wanted {"os":"darwin,linux","arch":"any"} (current: {"os":"win32","arch":"x64"})
38030 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin,linux
38030 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
38030 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
38030 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
38031 warn optional SKIPPING OPTIONAL DEPENDENCY: electron-installer-flatpak@0.8.0 (node_modules\electron-installer-flatpak):
38032 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for electron-installer-flatpak@0.8.0: wanted {"os":"darwin,linux","arch":"any"} (current: {"os":"win32","arch":"x64"})
38033 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin,linux
38033 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
38033 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
38033 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
38034 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
38035 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
38036 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
38036 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
38036 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
38036 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
38037 verbose stack Error: sharp@0.18.4 install: `node-gyp rebuild`
38037 verbose stack Exit status 1
38037 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
38037 verbose stack     at emitTwo (events.js:126:13)
38037 verbose stack     at EventEmitter.emit (events.js:214:7)
38037 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
38037 verbose stack     at emitTwo (events.js:126:13)
38037 verbose stack     at ChildProcess.emit (events.js:214:7)
38037 verbose stack     at maybeClose (internal/child_process.js:925:16)
38037 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
38038 verbose pkgid sharp@0.18.4
38039 verbose cwd C:\Users\pszwe\Downloads\ganache-develop (1)\ganache-develop
38040 verbose Windows_NT 10.0.16299
38041 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
38042 verbose node v8.9.3
38043 verbose npm  v5.5.1
38044 error code ELIFECYCLE
38045 error errno 1
38046 error sharp@0.18.4 install: `node-gyp rebuild`
38046 error Exit status 1
38047 error Failed at the sharp@0.18.4 install script.
38047 error This is probably not a problem with npm. There is likely additional logging output above.
38048 verbose exit [ 1, true ]

**Comment by sahilsehgalinc** [comment]
#npm install
#npm run build-linux

After Installing modules and building Linux packages [above commands working fine] when I try installing ganache via npm I see following error message:

==================================
ubuntu@ldap:~/ganache$ npm start

> ganache@1.1.0 start /home/ubuntu/ganache
> electron-forge start

✔ Checking your system
✔ Locating Application
✔ Preparing native dependencies: 4 / 4
✔ Launching Application
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ganache@1.1.0 start: `electron-forge start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ganache@1.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2018-04-17T07_46_48_409Z-debug.log

**Comment by seesemichaelj** [comment]
@amandiobm This seems to be a generic Electron bug: https://github.com/electron/electron/issues/1518

They report that installing `apt-get install libgconf-2-4` will mitigate the error you're having. Let me know if that works.

**Comment by amandiobm** [comment]
@seesemichaelj tks for the feedback. It works, everything is running. But I received this message.

> ganache@1.2.2 start /mnt/General/Projects/amandio/ganache
> electron-forge start

✔ Checking your system
✔ Locating Application
✔ Preparing native dependencies: 9 / 10
✔ Launching Application
Gtk-Message: 11:11:10.918: Failed to load module "canberra-gtk-module"

Kind regards.
