### ISSUE TITLE
Decoding Error when running Ganache 2.5.4 on darwin

### ISSUE THREAD

**Issue by j1mmie** [trufflesuite/ganache#2745]
I see this error while viewing a Contract that I have deployed via Truffle. The error is in the "Storage" section of the app.

![image](https://user-images.githubusercontent.com/4650220/120282554-15554400-c26f-11eb-92d9-f61fd2daec36.png)

The exception below says it cannot locate a struct named Patch. I have a struct named Patch in my app that exists in its own .sol file. It is being imported in my main contract (named Nfinity).

PLATFORM: darwin
GANACHE VERSION: 2.5.4

EXCEPTION:
```
UnknownUserDefinedTypeError: Cannot locate definition for struct Patch$ (ID 361)
    at storageSizeAndAllocate (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/@truffle/decoder/lib/allocate/storage.ts:299:17)
    at Object.storageSize (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/@truffle/decoder/lib/allocate/storage.ts:194:10)
    at decodeStorageReference (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/@truffle/decoder/lib/decode/storage.ts:105:43)
    at decodeStorageReference.next (<anonymous>)
    at Object.decodeStorage [as default] (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/@truffle/decoder/lib/decode/storage.ts:26:19)
    at decodeStorage.next (<anonymous>)
    at Object.decode [as default] (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/@truffle/decoder/lib/decode/index.ts:26:32)
    at decode.next (<anonymous>)
    at TruffleContractDecoder.<anonymous> (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/@truffle/decoder/lib/interface/contract-decoder.ts:283:24)
    at Generator.next (<anonymous>)
    at fulfilled (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/@truffle/decoder/dist/interface/contract-decoder.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by j1mmie** [comment]
Note: When I move the struct in Patch.sol into my main contract file, nested in a contract declaration, it resolves the issue.
