### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by tobitech** [trufflesuite/ganache#276]
I was trying to deploy a contract to the custom network created by Ganache from Ethereum wallet following this guide - [https://medium.com/crypto-currently/build-your-first-smart-contract-fc36a8ff50ca](url)

PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+0ms: Starting server with configuration: {"hostname":"127.0.0.1","mnemonic":"candy maple cake sugar pudding cream honey rich smooth crumble sweet treat","network_id":5777,"port":7545,"total_accounts":10,"unlocked_accounts":[]}
T+309ms: Ganache started successfully!
T+309ms: Waiting for requests...
T+52890ms: eth_estimateGas
T+52903ms: 
T+52903ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+52903ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+52903ms: AssertionError: The field to must have byte length of 20
T+52903ms:     at FakeTransaction.setter [as to] (/node_modules/ganache-cli/build/lib.node.js:7366:9)
T+52903ms:     at /node_modules/ganache-cli/build/lib.node.js:7416:63
T+52903ms:     at Array.forEach (native)
T+52903ms:     at Object.exports.defineProperties (/node_modules/ganache-cli/build/lib.node.js:7415:14)
T+52903ms:     at FakeTransaction.Transaction (/node_modules/ganache-cli/build/lib.node.js:78121:13)
T+52903ms:     at FakeTransaction (/node_modules/ganache-cli/build/lib.node.js:20454:5)
T+52903ms:     at /node_modules/ganache-cli/build/lib.node.js:80343:14
T+52903ms:     at /node_modules/ganache-cli/build/lib.node.js:21924:5
T+52903ms:     at /node_modules/ganache-cli/build/lib.node.js:55954:5
T+52903ms:     at /node_modules/ganache-cli/build/lib.node.js:56320:14
```

**Comment by benjamincburns** [comment]
Thanks for that, @ksedgwic!

AssertionError: The field to must have byte length of 20

Per #257 this issue is fixed in the current develop branch. The workaround in the mean time is to not include the to field in your transaction when deploying a contract.

We'll have a beta build out which contains this fix in the next couple of days.
