### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by Tpcdev** [trufflesuite/ganache#277]
PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+620405ms:   Block Time: Tue Jan 16 2018 02:50:20 GMT+0100 (CET)
T+621000ms: eth_getTransactionReceipt
T+625163ms: eth_getBlockByNumber
T+625176ms: eth_getBlockByNumber
T+625180ms: eth_getBalance
T+633187ms: eth_getBlockByNumber
T+633200ms: eth_getBlockByNumber
T+633204ms: eth_getBalance
T+641211ms: eth_getBlockByNumber
T+641223ms: eth_getBlockByNumber
T+641227ms: eth_getBalance
T+646675ms: eth_getBlockByNumber
T+646694ms: net_version
T+646697ms: net_version
T+646700ms: eth_getBlockByNumber
T+646702ms: eth_getBalance
T+654716ms: eth_getBlockByNumber
T+654728ms: eth_getBlockByNumber
T+654732ms: eth_getBalance
T+662738ms: eth_getBlockByNumber
T+662754ms: eth_getBlockByNumber
T+662769ms: eth_getBalance
T+670761ms: eth_getBlockByNumber
T+670779ms: eth_getBlockByNumber
T+670793ms: eth_getBalance
T+678782ms: eth_getBlockByNumber
T+686789ms: eth_getBlockByNumber
T+686808ms: eth_getBlockByNumber
T+686825ms: eth_getBalance
T+692973ms: eth_getBlockByNumber
T+692989ms: eth_call
T+693007ms: eth_call
T+693022ms: eth_call
T+693037ms: eth_call
T+693053ms: eth_call
T+693069ms: eth_call
T+693086ms: eth_call
T+693099ms: eth_getBlockByNumber
T+694902ms: eth_getBlockByNumber
T+694918ms: eth_getBlockByNumber
T+694932ms: eth_getBalance
T+695505ms: eth_getBlockByNumber
T+695518ms: eth_call
T+695533ms: eth_call
T+695548ms: eth_call
T+695562ms: eth_call
T+695576ms: eth_call
T+695594ms: eth_call
T+695607ms: eth_call
T+695621ms: eth_getBlockByNumber
T+700814ms: eth_getBlockByNumber
T+700830ms: eth_call
T+700848ms: eth_getBlockByNumber
T+700868ms: eth_call
T+702924ms: eth_getBlockByNumber
T+702940ms: eth_getBlockByNumber
T+702954ms: eth_getBalance
T+706735ms: eth_getBlockByNumber
T+706752ms: eth_call
T+706770ms: eth_call
T+706784ms: eth_call
T+706798ms: eth_call
T+706815ms: eth_call
T+706833ms: eth_call
T+706851ms: eth_call
T+706868ms: eth_getBlockByNumber
T+710945ms: eth_getBlockByNumber
T+710959ms: eth_getBlockByNumber
T+710975ms: eth_getBalance
T+712840ms: eth_getBalance
T+714773ms: eth_getBlockByNumber
T+714788ms: eth_getBlockByNumber
T+714803ms: eth_call
T+714820ms: eth_call
T+714837ms: eth_call
T+714851ms: eth_call
T+714872ms: eth_call
T+714887ms: eth_call
T+714903ms: eth_call
T+716259ms: eth_getBlockByNumber
T+716274ms: eth_call
T+716287ms: eth_call
T+716287ms: eth_call
T+716302ms: eth_call
T+716317ms: eth_call
T+716332ms: eth_call
T+716353ms: eth_call
T+716369ms: eth_getBlockByNumber
T+718965ms: eth_getBlockByNumber
T+726974ms: eth_getBlockByNumber
T+726986ms: eth_getBlockByNumber
T+726990ms: eth_getBalance
T+726994ms: eth_getBalance
T+734997ms: eth_getBlockByNumber
T+735009ms: eth_getBlockByNumber
T+735012ms: eth_getBalance
T+735016ms: eth_getBalance
T+743020ms: eth_getBlockByNumber
T+743031ms: eth_getBlockByNumber
T+743034ms: eth_getBalance
T+743037ms: eth_getBalance
T+751038ms: eth_getBlockByNumber
T+751049ms: eth_getBlockByNumber
T+751054ms: eth_getBalance
T+751064ms: eth_getBalance
T+759060ms: eth_getBlockByNumber
T+760404ms: eth_getBlockByNumber
T+760408ms: eth_call
T+760412ms: eth_call
T+760416ms: eth_call
T+760421ms: eth_call
T+760424ms: eth_call
T+760429ms: eth_call
T+760433ms: eth_call
T+760505ms: eth_getBlockByNumber
T+760541ms: eth_getBlockByNumber
T+760575ms: eth_call
T+767072ms: eth_getBlockByNumber
T+767083ms: eth_getBlockByNumber
T+767086ms: eth_getBalance
T+767090ms: eth_getBalance
T+770437ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+770437ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+770437ms: 
T+770437ms: TypeError: Cannot read property 'pop' of undefined
T+770437ms:     at CheckpointTrie.Trie._updateNode (/node_modules/ganache-cli/build/lib.node.js:56237:23)
T+770437ms:     at /node_modules/ganache-cli/build/lib.node.js:55984:16
T+770437ms:     at /node_modules/ganache-cli/build/lib.node.js:56320:14
T+770437ms:     at processNode (/node_modules/ganache-cli/build/lib.node.js:56325:23)
T+770437ms:     at /node_modules/ganache-cli/build/lib.node.js:56316:5
T+770437ms:     at /node_modules/ganache-cli/build/lib.node.js:56057:7
T+770437ms:     at /node_modules/ganache-cli/build/lib.node.js:17623:7
T+770437ms:     at /node_modules/ganache-cli/build/lib.node.js:22962:16
T+770437ms:     at /node_modules/ganache-cli/build/lib.node.js:23179:32
T+770437ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
```

**Comment by benjamincburns** [comment]
Thanks for reporting this, @Tpcdev!

Unfortunately this report duplicates trufflesuite/ganache-cli#417. Fortunately, we have a fix in the works! This fix will go out as a `ganache-cli` beta within the next 12 hours, and will go out as a Ganache beta within the next few days (possibly even tomorrow).

Closing as this is a duplicate. Please subscribe to trufflesuite/ganache-cli#417 for future news about this bug.
