### ISSUE TITLE
System Error when running Ganache 2.6.0-beta.3 on darwin

### ISSUE THREAD

**Issue by 0fuz** [trufflesuite/ganache#2774]
trying to make ganache gui setup from command 
```ganache-cli -f https://mainnet.infura.io/v3/INFURA_TOKEN -i 1```
cli command works fine but can't make same with gui

gui setup:
`server->chain forking` set https://mainnet.infura.io/v3/INFURA_TOKEN
`server->block number` set latest from etherscan
`chain->hardfork` set "Muir Glacier"

PLATFORM: darwin
GANACHE VERSION: 2.6.0-beta.3

EXCEPTION:
```
Error: Incompatible EIP155-based V 0 and chain id 1. See the second parameter of the Transaction constructor to set the chain id.
    at Transaction._validateV (/private/var/folders/s1/rqyq6bn13xz0j5qtmyfbhb200000gn/T/AppTranslocation/377E53AE-1FC4-4548-A358-25D82C34A649/d/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/node_modules/ethereumjs-tx/src/transaction.ts:370:13)
    at Transaction.set [as v] (/private/var/folders/s1/rqyq6bn13xz0j5qtmyfbhb200000gn/T/AppTranslocation/377E53AE-1FC4-4548-A358-25D82C34A649/d/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/node_modules/ethereumjs-tx/src/transaction.ts:387:16)
    at /private/var/folders/s1/rqyq6bn13xz0j5qtmyfbhb200000gn/T/AppTranslocation/377E53AE-1FC4-4548-A358-25D82C34A649/d/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/lib/utils/transaction.js:116:23
    at Array.forEach (<anonymous>)
    at initData (/private/var/folders/s1/rqyq6bn13xz0j5qtmyfbhb200000gn/T/AppTranslocation/377E53AE-1FC4-4548-A358-25D82C34A649/d/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/lib/utils/transaction.js:110:18)
    at new Transaction (/private/var/folders/s1/rqyq6bn13xz0j5qtmyfbhb200000gn/T/AppTranslocation/377E53AE-1FC4-4548-A358-25D82C34A649/d/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/lib/utils/transaction.js:168:5)
    at Function.fromJSON (/private/var/folders/s1/rqyq6bn13xz0j5qtmyfbhb200000gn/T/AppTranslocation/377E53AE-1FC4-4548-A358-25D82C34A649/d/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/lib/utils/transaction.js:228:16)
    at /private/var/folders/s1/rqyq6bn13xz0j5qtmyfbhb200000gn/T/AppTranslocation/377E53AE-1FC4-4548-A358-25D82C34A649/d/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/lib/forking/forked_blockchain.js:384:21
    at Array.forEach (<anonymous>)
    at Object.callback (/private/var/folders/s1/rqyq6bn13xz0j5qtmyfbhb200000gn/T/AppTranslocation/377E53AE-1FC4-4548-A358-25D82C34A649/d/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/lib/forking/forked_blockchain.js:382:31)
    at sendTxCallback (/private/var/folders/s1/rqyq6bn13xz0j5qtmyfbhb200000gn/T/AppTranslocation/377E53AE-1FC4-4548-A358-25D82C34A649/d/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/node_modules/web3-core-method/src/index.js:664:29)
    at onJsonrpcResult (/private/var/folders/s1/rqyq6bn13xz0j5qtmyfbhb200000gn/T/AppTranslocation/377E53AE-1FC4-4548-A358-25D82C34A649/d/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/node_modules/web3-core-requestmanager/src/index.js:179:9)
    at /private/var/folders/s1/rqyq6bn13xz0j5qtmyfbhb200000gn/T/AppTranslocation/377E53AE-1FC4-4548-A358-25D82C34A649/d/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/lib/forking/forked_blockchain.js:136:11
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by kylezs** [comment]
Also getting this issue, with hardfork istanbul.
