### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by yarrumretep** [trufflesuite/ganache#278]
PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+336026ms:   Block Number: 75
T+336026ms:   Block Time: Mon Jan 15 2018 21:13:14 GMT-0500 (EST)
T+336030ms: eth_getTransactionReceipt
T+336230ms: evm_snapshot
T+504903ms: net_version
T+504911ms: eth_accounts
T+504943ms: eth_accounts
T+504997ms: eth_accounts
T+505006ms: net_version
T+505011ms: net_version
T+505019ms: eth_sendTransaction
T+505057ms:   Transaction: 0xdbfcf3d62a90db133357033090a366c28b49b3a093b9bede9ea8827e8283a206
T+505057ms:   Contract created: 0x82d50ad3c1091866e258fd0f1a7cc9674609d254
T+505057ms:   Gas usage: 269607
T+505057ms:   Block Number: 76
T+505057ms:   Block Time: Mon Jan 15 2018 21:16:03 GMT-0500 (EST)
T+505062ms: eth_newBlockFilter
T+505067ms: eth_getFilterChanges
T+505075ms: eth_getTransactionReceipt
T+505081ms: eth_getCode
T+505096ms: eth_uninstallFilter
T+505100ms: eth_sendTransaction
T+505134ms:   Transaction: 0x289ae161be6b6cdcea57476a531d45daf5e590a20fecca05e88e1bf699ba2558
T+505139ms:   Gas usage: 41981
T+505139ms:   Block Number: 77
T+505139ms:   Block Time: Mon Jan 15 2018 21:16:03 GMT-0500 (EST)
T+505145ms: eth_getTransactionReceipt
T+505248ms: evm_snapshot
T+505350ms: eth_blockNumber
T+505355ms: net_version
T+505360ms: net_version
T+505366ms: eth_sendTransaction
T+505369ms: eth_sendTransaction
T+505408ms:   Transaction: 0x63d5d514fce3a6287426f434e0f938a4183f1f59333054c06fc9753574f5fb24
T+505408ms:   Contract created: 0x1e5fa5deec9aef3bba765d00b41f41ba618e519a
T+505408ms:   Gas usage: 1462020
T+505408ms:   Block Number: 78
T+505408ms:   Block Time: Mon Jan 15 2018 21:16:03 GMT-0500 (EST)
T+505414ms: eth_newBlockFilter
T+505461ms:   Transaction: 0xb25dee545887ec986b090b6ad68f715d761736ef60ddb064547ee305e2202678
T+505461ms:   Contract created: 0x6f2eac0b32f36ac895acad0da1d378ae146f02bb
T+505461ms:   Gas usage: 1462020
T+505461ms:   Block Number: 79
T+505461ms:   Block Time: Mon Jan 15 2018 21:16:03 GMT-0500 (EST)
T+505466ms: eth_newBlockFilter
T+505470ms: eth_getFilterChanges
T+505474ms: eth_getTransactionReceipt
T+505481ms: eth_getCode
T+505486ms: eth_uninstallFilter
T+505972ms: eth_getFilterChanges
T+505985ms: eth_getTransactionReceipt
T+505993ms: eth_getCode
T+505999ms: eth_uninstallFilter
T+506006ms: net_version
T+506012ms: eth_sendTransaction
T+506097ms:   Transaction: 0x794d5fce69e53de32aea065ccbe617bdeb48f3c2d0f847d073254010ed5e6935
T+506097ms:   Contract created: 0xeec918d74c746167564401103096d45bbd494b74
T+506097ms:   Gas usage: 2943885
T+506097ms:   Block Number: 80
T+506097ms:   Block Time: Mon Jan 15 2018 21:16:04 GMT-0500 (EST)
T+506101ms: eth_newBlockFilter
T+506107ms: eth_getFilterChanges
T+506112ms: eth_getTransactionReceipt
T+506119ms: eth_getCode
T+506126ms: eth_uninstallFilter
T+506130ms: miner_stop
T+506133ms: net_version
T+506136ms: eth_sendTransaction
T+506141ms: net_version
T+506145ms: eth_sendTransaction
T+506150ms: net_version
T+506154ms: eth_sendTransaction
T+508164ms: evm_mine
T+508217ms: miner_start
T+508224ms: eth_getLogs
T+555002ms: net_version
T+555011ms: eth_accounts
T+555041ms: eth_accounts
T+555084ms: eth_accounts
T+555094ms: net_version
T+555100ms: net_version
T+555108ms: eth_sendTransaction
T+555113ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+555113ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+555113ms: 
T+555113ms: TypeError: Cannot read property 'gasPrice' of undefined
T+555113ms:     at priceSort (/node_modules/ganache-cli/build/lib.node.js:21947:61)
T+555113ms:     at _siftdown (/node_modules/ganache-cli/build/lib.node.js:74832:11)
T+555113ms:     at heappush (/node_modules/ganache-cli/build/lib.node.js:74659:12)
T+555113ms:     at Heap.push (/node_modules/ganache-cli/build/lib.node.js:74887:14)
T+555113ms:     at BlockchainDouble.sortByPriceAndNonce (/node_modules/ganache-cli/build/lib.node.js:21973:12)
T+555113ms:     at BlockchainDouble.processNextBlock (/node_modules/ganache-cli/build/lib.node.js:22163:8)
T+555113ms:     at /node_modules/ganache-cli/build/lib.node.js:80489:21
T+555113ms:     at Object.async.whilst (/node_modules/ganache-cli/build/lib.node.js:8279:13)
T+555113ms:     at StateManager.processBlocks (/node_modules/ganache-cli/build/lib.node.js:80478:9)
T+555113ms:     at StateManager.processTransaction (/node_modules/ganache-cli/build/lib.node.js:80568:8)
```

**Comment by yarrumretep** [comment]
Having the devil of a time working on getting manual mining implemented to test contract edge cases of multiple transactions in one block.  I'm using the miner_stop rpc call then using evm_mine after i've staged the transactions i'd like to execute in one block.

Found the cool Ganache GUI after wrestling with 'truffle develop' mode.  These errors appear to be causing the actual node process to stop as successive attempts to run indicate the rpc port is not being listened on.  

Using 
```
Truffle v4.0.4 (core: 4.0.4)
Solidity v0.4.18 (solc-js)
```

**Comment by benjamincburns** [comment]
Thanks for reporting this @yarrumretep. I'm tracking this issue over on trufflesuite/ganache-cli#293. It'd be great if you could add your comments to that ticket and we'll tackle it over there.
