### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by absir** [trufflesuite/ganache#280]
PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+4299781ms:   Contract created: 0x8065f4c7b8c2bf53561af92d9da2ea022a0b28ca
T+4299781ms:   Gas usage: 1490387
T+4299781ms:   Block Number: 45
T+4299781ms:   Block Time: Tue Jan 16 2018 19:40:52 GMT+0800 (CST)
T+4299785ms: eth_newBlockFilter
T+4299788ms: eth_getFilterChanges
T+4299795ms: eth_getTransactionReceipt
T+4299800ms: eth_getCode
T+4299811ms: eth_uninstallFilter
T+4299813ms: eth_sendTransaction
T+4299833ms:   Transaction: 0x1dd73ccb5e9572fedb8068a8dcf7c37caa0418303708a1120abefebda18f64e1
T+4299833ms:   Gas usage: 41981
T+4299833ms:   Block Number: 46
T+4299833ms:   Block Time: Tue Jan 16 2018 19:40:52 GMT+0800 (CST)
T+4299837ms: eth_getTransactionReceipt
T+4299859ms: eth_call
T+4349344ms: net_version
T+4349351ms: eth_accounts
T+4349370ms: eth_accounts
T+4349395ms: eth_accounts
T+4349408ms: eth_sendTransaction
T+4349437ms:   Transaction: 0xcdaeb067e1fe3dea1e96e0d341922fde39855c836a49c8d1932dadcad90caf7c
T+4349437ms:   Contract created: 0x4eee4559bd589b1cdfc419f0eed2ff9cbd47f439
T+4349437ms:   Gas usage: 340775
T+4349437ms:   Block Number: 47
T+4349437ms:   Block Time: Tue Jan 16 2018 19:41:42 GMT+0800 (CST)
T+4349442ms: eth_newBlockFilter
T+4349444ms: eth_getFilterChanges
T+4349452ms: eth_getTransactionReceipt
T+4349458ms: eth_getCode
T+4349464ms: eth_uninstallFilter
T+4349467ms: eth_sendTransaction
T+4349485ms:   Transaction: 0x79a2affa84dfeea5bffc16085d632f4612775182df7833de6e686ef098a79575
T+4349485ms:   Contract created: 0xcb152a2aa90055a0d255ca7dbaeb85edfdc86096
T+4349485ms:   Gas usage: 269607
T+4349485ms:   Block Number: 48
T+4349485ms:   Block Time: Tue Jan 16 2018 19:41:42 GMT+0800 (CST)
T+4349490ms: eth_newBlockFilter
T+4349492ms: eth_getFilterChanges
T+4349497ms: eth_getTransactionReceipt
T+4349501ms: eth_getCode
T+4349505ms: eth_uninstallFilter
T+4349507ms: eth_sendTransaction
T+4349550ms:   Transaction: 0xaed70cd305e35c1d21bdf984a77c2a7b24d38879c626c33672e58f9d920980eb
T+4349550ms:   Contract created: 0x23e84570f7b28ad0d5e5545d398009194a8734f3
T+4349550ms:   Gas usage: 1490387
T+4349550ms:   Block Number: 49
T+4349550ms:   Block Time: Tue Jan 16 2018 19:41:42 GMT+0800 (CST)
T+4349554ms: eth_newBlockFilter
T+4349557ms: eth_getFilterChanges
T+4349561ms: eth_getTransactionReceipt
T+4349569ms: eth_getCode
T+4349577ms: eth_uninstallFilter
T+4349582ms: eth_sendTransaction
T+4349604ms:   Transaction: 0x18e1662d2f73e20b4929d751dc67bd77c152b641cdc070e915176a0422697174
T+4349604ms:   Gas usage: 41981
T+4349604ms:   Block Number: 50
T+4349604ms:   Block Time: Tue Jan 16 2018 19:41:42 GMT+0800 (CST)
T+4349608ms: eth_getTransactionReceipt
T+4349632ms: eth_call
T+4676881ms: net_version
T+4676888ms: eth_accounts
T+4676907ms: eth_accounts
T+4676932ms: eth_accounts
T+4676946ms: eth_sendTransaction
T+4677003ms:   Transaction: 0x3e027967eb8c0ebb6f61f343af91353426783571c755e5d0b4d06c1f51c6c4aa
T+4677003ms:   Contract created: 0x8cd918cee8f93989e334bc0107bb33a9586d05c0
T+4677003ms:   Gas usage: 340775
T+4677003ms:   Block Number: 51
T+4677006ms:   Block Time: Tue Jan 16 2018 19:47:09 GMT+0800 (CST)
T+4677010ms: eth_newBlockFilter
T+4677038ms: eth_getFilterChanges
T+4677042ms: eth_getTransactionReceipt
T+4677047ms: eth_getCode
T+4677049ms: eth_uninstallFilter
T+4677052ms: eth_sendTransaction
T+4677074ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+4677074ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+4677074ms: 
T+4677074ms: TypeError: Cannot read property 'get' of undefined
T+4677074ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+4677074ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+4677074ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+4677074ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+4677074ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+4677074ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+4677074ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+4677074ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+4677074ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+4677074ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by benjamincburns** [comment]
This problem is fixed on `ganache-cli@v7.0.0-beta.0` and on the current `develop` branch of Ganache. We'll be releasing a pre-release build with this fix in the next few days.
