### ISSUE TITLE
System Error when running Ganache 1.0.2 on linux

### ISSUE THREAD

**Issue by roehst** [trufflesuite/ganache#281]
During a script that:

makes a reference to a master contract
creates 30 contracts
calls a function in the master contract to register each contract

PLATFORM: linux
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+174228ms: eth_sendTransaction
T+174241ms:   Transaction: 0xa9e2f75adf0cd26cf3d7624af1c336f20d154940e3b34fc517b51b36b8e776f0
T+174241ms:   Contract created: 0x7a307de3980775dcbb331ff603906abc6ccbc9f2
T+174241ms:   Gas usage: 364926
T+174241ms:   Block Number: 146
T+174241ms:   Block Time: Tue Jan 16 2018 11:02:30 GMT-0200 (-02)
T+174244ms: eth_getTransactionReceipt
T+174262ms: eth_call
T+174274ms: eth_estimateGas
T+174286ms: eth_blockNumber
T+174290ms: eth_getBlockByNumber
T+174294ms: eth_sendTransaction
T+174311ms:   Transaction: 0x07a0eb1aa52a169c9b531d893e15177e2b8a5cb3784f3c0076487ab5f1c85d27
T+174311ms:   Gas usage: 48854
T+174311ms:   Block Number: 147
T+174311ms:   Block Time: Tue Jan 16 2018 11:02:30 GMT-0200 (-02)
T+174313ms: eth_call
T+174325ms: eth_estimateGas
T+174343ms: eth_blockNumber
T+174346ms: eth_getBlockByNumber
T+174351ms: eth_sendTransaction
T+174396ms:   Transaction: 0xbfc0cfbf79822af09460ee8aa0af0b4fe8805d179ba982a41a998fd4e8719da6
T+174396ms:   Contract created: 0x27e622dc2888fc99ab9438a59ae30089e3556998
T+174396ms:   Gas usage: 364926
T+174396ms:   Block Number: 148
T+174396ms:   Block Time: Tue Jan 16 2018 11:02:30 GMT-0200 (-02)
T+174399ms: eth_getTransactionReceipt
T+174405ms: eth_call
T+174419ms: eth_estimateGas
T+174434ms: eth_blockNumber
T+174437ms: eth_getBlockByNumber
T+174442ms: eth_sendTransaction
T+174458ms:   Transaction: 0x68508d88b06c1fecc05700cffaf46d55fe062844acd84d1380054de1857db6f4
T+174458ms:   Gas usage: 48790
T+174458ms:   Block Number: 149
T+174458ms:   Block Time: Tue Jan 16 2018 11:02:30 GMT-0200 (-02)
T+174461ms: eth_call
T+174474ms: eth_estimateGas
T+174487ms: eth_blockNumber
T+174491ms: eth_getBlockByNumber
T+174495ms: eth_sendTransaction
T+174514ms:   Transaction: 0xa188b6337a18a3ce444f6d963bd598e4be5ee689949f086a89f2ff684d640d3c
T+174514ms:   Contract created: 0x447db080264bed6ed21d3a082ae4cdd7ebfe4e32
T+174514ms:   Gas usage: 364926
T+174514ms:   Block Number: 150
T+174514ms:   Block Time: Tue Jan 16 2018 11:02:30 GMT-0200 (-02)
T+174516ms: eth_getTransactionReceipt
T+174522ms: eth_call
T+174536ms: eth_estimateGas
T+174549ms: eth_blockNumber
T+174552ms: eth_getBlockByNumber
T+174556ms: eth_sendTransaction
T+174571ms:   Transaction: 0xa30e2051b495fd8018bb68169aa4d7c009ab83286cdeb262eb9acf32ea4098f4
T+174571ms:   Gas usage: 48854
T+174571ms:   Block Number: 151
T+174571ms:   Block Time: Tue Jan 16 2018 11:02:30 GMT-0200 (-02)
T+174574ms: eth_call
T+174585ms: eth_estimateGas
T+174600ms: eth_blockNumber
T+174603ms: eth_getBlockByNumber
T+174608ms: eth_sendTransaction
T+174629ms:   Transaction: 0x025b942680fa80a0c04e46541c66fcdf81e1b847bcee36e4f08bc2d94658e375
T+174629ms:   Contract created: 0xb903a28c384c31f58c51de824e35717f8a4ca75b
T+174629ms:   Gas usage: 364926
T+174629ms:   Block Number: 152
T+174629ms:   Block Time: Tue Jan 16 2018 11:02:30 GMT-0200 (-02)
T+174631ms: eth_getTransactionReceipt
T+174636ms: eth_call
T+174650ms: eth_estimateGas
T+174666ms: eth_blockNumber
T+174669ms: eth_getBlockByNumber
T+174674ms: eth_sendTransaction
T+174715ms:   Transaction: 0xa864cdb9319187eb30439235f6a2a99f25e2d283b8ed8713bd3368bd8ea6a62f
T+174715ms:   Gas usage: 48854
T+174715ms:   Block Number: 153
T+174715ms:   Block Time: Tue Jan 16 2018 11:02:30 GMT-0200 (-02)
T+174718ms: eth_call
T+174724ms: eth_estimateGas
T+174744ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+174744ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_W
T+174744ms: 
T+174744ms: TypeError: Cannot read property 'get' of undefined
T+174744ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+174744ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+174744ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+174744ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+174744ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+174744ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+174744ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+174744ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+174744ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+174744ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by benjamincburns** [comment]
This problem is fixed on `ganache-cli@v7.0.0-beta.0` and on the current `develop` branch of Ganache. We'll be releasing a pre-release build with this fix in the next few days.
