### ISSUE TITLE
Decoding Error when running Ganache 2.5.4 on linux

### ISSUE THREAD

**Issue by vmsh0** [trufflesuite/ganache#2818]
I deployed the following contract using Truffle, solc 0.8.5:

```
pragma solidity ^0.8.0;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";

contract TritiumCoin is ERC20 {
    constructor(uint256 initialSupply) ERC20("Tritium", "TREE") {
        _mint(msg.sender, initialSupply);
    }
}
```

I opened the contract in Ganache and it presented me with the attached screen.
![tmp](https://user-images.githubusercontent.com/1955497/122899713-57dcde80-d34c-11eb-9434-183be10d0c7a.png)

PLATFORM: linux
GANACHE VERSION: 2.5.4

EXCEPTION:
```
UnknownBaseContractIdError: Cannot locate base contract ID 654$ of contract$ TritiumCoin (ID 21)
    at /opt/ganache/resources/static/node/node_modules/@truffle/decoder/lib/allocate/storage.ts:181:13
    at Array.map (<anonymous>)
    at allocateContract (/opt/ganache/resources/static/node/node_modules/@truffle/decoder/lib/allocate/storage.ts:178:59)
    at Object.getStorageAllocations (/opt/ganache/resources/static/node/node_modules/@truffle/decoder/lib/allocate/storage.ts:23:19)
    at TruffleContractDecoder.<anonymous> (/opt/ganache/resources/static/node/node_modules/@truffle/decoder/lib/interface/contract-decoder.ts:237:39)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/ganache/resources/static/node/node_modules/@truffle/decoder/dist/interface/contract-decoder.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by vmsh0** [comment]
Deleting the truffle `build` directory and migrating from scratch fixed it.
