### ISSUE TITLE
System Error when running Ganache 2.5.4 on win32

### ISSUE THREAD

**Issue by bater53** [trufflesuite/ganache#2824]
bater@Xena:/mnt/c/pr0/blockchain-developer-bootcamp$ truffle test
Using network 'development'.

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.

  Contract: Exchange
    deployment
      ✓ tracks the fee account (125ms)
      ✓ tracks the fee percent (111ms)
    fallback
      ✓ reverts when Ether is sent (322ms)
    depositing Ether
      ✓ tracks the Ether deposit (126ms)
      ✓ emits a Deposit event
    withdrawing Ether
      success
        ✓ withdraws Ether funds (177ms)
        ✓ emits a "Withdraw" event
      failure
        ✓ rejects withdraws for insufficient balances (393ms)
    depositing tokens
      success
        ✓ tracks the token deposit (224ms)
        ✓ emits a Deposit event
      failure
        ✓ rejects Ether deposits (318ms)
        ✓ fails when no tokens are approved (358ms)
    withdrawing tokens
      success
        ✓ withdraws token funds (148ms)
        1) "before each" hook for "emits a "Withdraw" event"

  Contract: Token
    2) "before all" hook: prepare suite in "Contract: Token"

  13 passing (37s)
  2 failing

  1) Contract: Exchange
       "before each" hook for "emits a "Withdraw" event":
     Uncaught ProviderError:
Could not connect to your Ethereum client with the following parameters:
    - host       > 127.0.0.1
    - port       > 7545
    - network_id > 5777
Please check that your Ethereum client:
    - is running
    - is accepting RPC connections (i.e., "--rpc" or "--http" option is used in geth)
    - is accessible over the network
    - is properly configured in your Truffle configuration file (truffle-config.js)

      at /home/bater/.nvm/versions/node/v16.14.0/lib/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:75:1
      at /home/bater/.nvm/versions/node/v16.14.0/lib/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:113:1
      at XMLHttpRequest.request.onreadystatechange (/home/bater/.nvm/versions/node/v16.14.0/lib/node_modules/truffle/build/webpack:/node_modules/web3/node_modules/web3-providers-http/lib/index.js:98:1)
      at XMLHttpRequestEventTarget.dispatchEvent (/home/bater/.nvm/versions/node/v16.14.0/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
      at XMLHttpRequest.exports.modules.996763.XMLHttpRequest._setReadyState (/home/bater/.nvm/versions/node/v16.14.0/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:208:1)
      at XMLHttpRequest.exports.modules.996763.XMLHttpRequest._onHttpRequestError (/home/bater/.nvm/versions/node/v16.14.0/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:349:1)
      at ClientRequest.<anonymous> (/home/bater/.nvm/versions/node/v16.14.0/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:252:48)
      at ClientRequest.emit (node:events:520:28)
      at Socket.socketErrorListener (node:_http_client:442:9)
      at Socket.emit (node:events:520:28)
      at emitErrorNT (node:internal/streams/destroy:157:8)
      at emitErrorCloseNT (node:internal/streams/destroy:122:3)
      at processTicksAndRejections (node:internal/process/task_queues:83:21)

  2) Contract: Token
       "before all" hook: prepare suite in "Contract: Token":
     ProviderError:
Could not connect to your Ethereum client with the following parameters:
    - host       > 127.0.0.1
    - port       > 7545
    - network_id > 5777
Please check that your Ethereum client:
    - is running
    - is accepting RPC connections (i.e., "--rpc" or "--http" option is used in geth)
    - is accessible over the network
    - is properly configured in your Truffle configuration file (truffle-config.js)

      at /home/bater/.nvm/versions/node/v16.14.0/lib/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:75:1
      at /home/bater/.nvm/versions/node/v16.14.0/lib/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:113:1
      at XMLHttpRequest.request.onreadystatechange (/home/bater/.nvm/versions/node/v16.14.0/lib/node_modules/truffle/build/webpack:/node_modules/web3/node_modules/web3-providers-http/lib/index.js:98:1)
      at XMLHttpRequestEventTarget.dispatchEvent (/home/bater/.nvm/versions/node/v16.14.0/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
      at XMLHttpRequest.exports.modules.996763.XMLHttpRequest._setReadyState (/home/bater/.nvm/versions/node/v16.14.0/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:208:1)
      at XMLHttpRequest.exports.modules.996763.XMLHttpRequest._onHttpRequestError (/home/bater/.nvm/versions/node/v16.14.0/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:349:1)
      at ClientRequest.<anonymous> (/home/bater/.nvm/versions/node/v16.14.0/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:252:48)
      at ClientRequest.emit (node:events:520:28)
      at Socket.socketOnEnd (node:_http_client:466:9)
      at Socket.emit (node:events:532:35)
      at endReadableNT (node:internal/streams/readable:1346:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21)

UnhandledRejections detected
Promise {
  <rejected> ProviderError:
  Could not connect to your Ethereum client with the following parameters:
      - host       > 127.0.0.1
      - port       > 7545
      - network_id > 5777
  Please check that your Ethereum client:
      - is running
      - is accepting RPC connections (i.e., "--rpc" or "--http" option is used in geth)
      - is accessible over the network
      - is properly configured in your Truffle configuration file (truffle-config.js)

      at /home/bater/.nvm/versions/node/v16.14.0/lib/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:75:1
      at /home/bater/.nvm/versions/node/v16.14.0/lib/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:113:1
      at XMLHttpRequest.request.onreadystatechange (/home/bater/.nvm/versions/node/v16.14.0/lib/node_modules/truffle/build/webpack:/node_modules/web3/node_modules/web3-providers-http/lib/index.js:98:1)
      at XMLHttpRequestEventTarget.dispatchEvent (/home/bater/.nvm/versions/node/v16.14.0/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
      at XMLHttpRequest.exports.modules.996763.XMLHttpRequest._setReadyState (/home/bater/.nvm/versions/node/v16.14.0/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:208:1)
      at XMLHttpRequest.exports.modules.996763.XMLHttpRequest._onHttpRequestError (/home/bater/.nvm/versions/node/v16.14.0/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:349:1)
      at ClientRequest.<anonymous> (/home/bater/.nvm/versions/node/v16.14.0/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:252:48)
      at ClientRequest.emit (node:events:520:28)
      at Socket.socketErrorListener (node:_http_client:442:9)
      at Socket.emit (node:events:520:28)
      at emitErrorNT (node:internal/streams/destroy:157:8)
      at emitErrorCloseNT (node:internal/streams/destroy:122:3)
      at processTicksAndRejections (node:internal/process/task_queues:83:21) {
    uncaught: true
  }
} ProviderError:
Could not connect to your Ethereum client with the following parameters:
    - host       > 127.0.0.1
    - port       > 7545
    - network_id > 5777
Please check that your Ethereum client:
    - is running
    - is accepting RPC connections (i.e., "--rpc" or "--http" option is used in geth)
    - is accessible over the network
    - is properly configured in your Truffle configuration file (truffle-config.js)

    at /home/bater/.nvm/versions/node/v16.14.0/lib/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:75:1
    at /home/bater/.nvm/versions/node/v16.14.0/lib/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:113:1
    at XMLHttpRequest.request.onreadystatechange (/home/bater/.nvm/versions/node/v16.14.0/lib/node_modules/truffle/build/webpack:/node_modules/web3/node_modules/web3-providers-http/lib/index.js:98:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/bater/.nvm/versions/node/v16.14.0/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
    at XMLHttpRequest.exports.modules.996763.XMLHttpRequest._setReadyState (/home/bater/.nvm/versions/node/v16.14.0/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:208:1)
    at XMLHttpRequest.exports.modules.996763.XMLHttpRequest._onHttpRequestError (/home/bater/.nvm/versions/node/v16.14.0/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:349:1)
    at ClientRequest.<anonymous> (/home/bater/.nvm/versions/node/v16.14.0/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:252:48)
    at ClientRequest.emit (node:events:520:28)
    at Socket.socketErrorListener (node:_http_client:442:9)
    at Socket.emit (node:events:520:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  uncaught: true
}

PLATFORM: win32
GANACHE VERSION: 2.5.4

EXCEPTION:
```
TypeError: Cannot read property 'transactions' of null
    at ProjectsWatcher.handleBlock (C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\static\node\truffle-integration\projectsWatcher.js:180:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Subscription.<anonymous> (C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\static\node\truffle-integration\projectsWatcher.js:57:9)
```

**Comment by bater53** [comment]
It says on win32 and I am running windows 64.  I have added everything as windows 64 so how did this all of a sudden become a windows 32 issue?
