### ISSUE TITLE
System Error when running Ganache 1.0.0 on darwin

### ISSUE THREAD

**Issue by sullof** [trufflesuite/ganache#283]
I was testing [https://github.com/0xNIL/initial-free-offering](https://github.com/0xNIL/initial-free-offering)
If I run ganache-cli everything is fine. If I run Ganache I have this error after a few tests.

PLATFORM: darwin
GANACHE VERSION: 1.0.0

EXCEPTION:
Error: Lost heartbeat from server process!
    at Timeout.setInterval [as _onTimeout] (/src/Services/Chain.js:86:30)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

**Comment by benjamincburns** [comment]
Thanks for reporting this issue. **Please update to the latest version of Ganache to fix this problem.** The heartbeat failure message has been fixed in our latest version of Ganache. Later versions of Ganache also include more helpful information when opening GitHub issues. Without this information, it is very difficult to diagnose the underlying problem. Because of the large number of independent reports of this issue, this is an automated message. Please reopen if you feel this issue warrants more attention.

**Comment by sullof** [comment]
Thanks.

**Comment by sullof** [comment]
@benjamincburns 
I updated to last version. Unfortunately I have the same issue if during the tests I am looking at the transaction tab. It works (and it worked) fine if I look at the log.

<img width="731" alt="screen shot 2018-01-16 at 5 18 37 pm" src="https://user-images.githubusercontent.com/108464/35020554-8c7ba4ba-fae1-11e7-93f3-1e898c718622.png">
