### ISSUE TITLE
System Error when running Ganache 1.0.2 on linux

### ISSUE THREAD

**Issue by qwertypomy** [trufflesuite/ganache#285]
PLATFORM: linux
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+188ms: Ganache started successfully!
T+188ms: Waiting for requests...
T+472927ms: net_version
T+472936ms: eth_accounts
T+472949ms: eth_accounts
T+472955ms: net_version
T+472961ms: net_version
T+472968ms: eth_sendTransaction
T+473015ms:   Transaction: 0x8be0fecc49d95ee2c0f932a7aa47abb429c5670b152caa6c55a4918650413fb2
T+473015ms:   Contract created: 0x8cdaf0cd259887258bc13a92c0a6da92698644c0
T+473015ms:   Gas usage: 269607
T+473015ms:   Block Number: 1
T+473019ms:   Block Time: Wed Jan 17 2018 11:22:44 GMT+0200 (EET)
T+473045ms: eth_newBlockFilter
T+473052ms: eth_getFilterChanges
T+473058ms: eth_getTransactionReceipt
T+473063ms: eth_getCode
T+473066ms: eth_uninstallFilter
T+473068ms: eth_sendTransaction
T+473141ms:   Transaction: 0xd7bc86d31bee32fa3988f1c1eabce403a1b5d570340a3a9cdba53a472ee8c956
T+473141ms:   Gas usage: 41981
T+473144ms:   Block Number: 2
T+473144ms:   Block Time: Wed Jan 17 2018 11:22:44 GMT+0200 (EET)
T+473147ms: eth_getTransactionReceipt
T+473154ms: eth_accounts
T+473160ms: net_version
T+473163ms: net_version
T+473166ms: eth_sendTransaction
T+473195ms:   Transaction: 0x8c82248298f717ffcd6d7d3d9de88cb309d2f8ee2ac31aa7606596b1026df8b3
T+473195ms:   Contract created: 0x345ca3e014aaf5dca488057592ee47305d9b3e10
T+473201ms:   Gas usage: 108856
T+473201ms:   Block Number: 3
T+473201ms:   Block Time: Wed Jan 17 2018 11:22:45 GMT+0200 (EET)
T+473207ms: eth_newBlockFilter
T+473210ms: eth_getFilterChanges
T+473216ms: eth_getTransactionReceipt
T+473223ms: eth_getCode
T+473228ms: eth_uninstallFilter
T+473233ms: eth_sendTransaction
T+473247ms:   Transaction: 0xf36163615f41ef7ed8f4a8f192149a0bf633fe1a2398ce001bf44c43dc7bdda0
T+473247ms:   Gas usage: 26981
T+473247ms:   Block Number: 4
T+473250ms:   Block Time: Wed Jan 17 2018 11:22:45 GMT+0200 (EET)
T+473252ms: eth_getTransactionReceipt
T+573107ms: net_version
T+573114ms: eth_accounts
T+573129ms: eth_accounts
T+578537ms: eth_accounts
T+578547ms: eth_sendTransaction
T+578580ms:   Transaction: 0xfdb17029c4e4c7d61de9a34c16fa208f26dbce112507d116344f19fc56a7ca82
T+578580ms:   Contract created: 0x8f0483125fcb9aaaefa9209d8e9d7b9c8b9fb90f
T+578580ms:   Gas usage: 269607
T+578580ms:   Block Number: 5
T+578580ms:   Block Time: Wed Jan 17 2018 11:24:30 GMT+0200 (EET)
T+578585ms: eth_newBlockFilter
T+578589ms: eth_getFilterChanges
T+578597ms: eth_getTransactionReceipt
T+578605ms: eth_getCode
T+578617ms: eth_uninstallFilter
T+578621ms: eth_sendTransaction
T+578652ms:   Transaction: 0x2e369ab2d57c20d6f0be342da05a0e340a8e85de0aef12b3199e44de9005d26c
T+578652ms:   Gas usage: 41981
T+578652ms:   Block Number: 6
T+578655ms:   Block Time: Wed Jan 17 2018 11:24:30 GMT+0200 (EET)
T+578660ms: eth_getTransactionReceipt
T+578663ms: eth_accounts
T+578666ms: eth_sendTransaction
T+578701ms:   Transaction: 0x95225e5445c283d318574cafc89ea0e9f181e2d01454b1d406fd05d00f14df3f
T+578701ms:   Contract created: 0x2c2b9c9a4a25e24b174f26114e8926a9f2128fe4
T+578701ms:   Gas usage: 108856
T+578701ms:   Block Number: 7
T+578701ms:   Block Time: Wed Jan 17 2018 11:24:30 GMT+0200 (EET)
T+578704ms: eth_newBlockFilter
T+578709ms: eth_getFilterChanges
T+578713ms: eth_getTransactionReceipt
T+578719ms: eth_getCode
T+578725ms: eth_uninstallFilter
T+578728ms: eth_sendTransaction
T+578766ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+578766ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_W
T+578766ms: 
T+578766ms: TypeError: Cannot read property 'get' of undefined
T+578766ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+578766ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+578766ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+578766ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+578766ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+578766ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+578766ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+578766ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+578766ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+578766ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by benjamincburns** [comment]
Hi @qwertypomy - thanks for reporting this. The issue you're reporting has been tracked over at trufflesuite/ganache-cli#417, and I'm pleased to say that I'm in the process of publishing a beta release with the fix included. Unfortunately it may take another day to get it out, but if you keep an eye out, it'll show up on the releases page soon.

Cheers.
