### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by yarrumretep** [trufflesuite/ganache#286]
Not sure why this happened.  Could not recreate with same script.  Ganache had been running for > 18 hours.

PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+87756629ms: eth_newBlockFilter
T+87756635ms: eth_getFilterChanges
T+87756642ms: eth_getTransactionReceipt
T+87756655ms: eth_getCode
T+87756663ms: eth_uninstallFilter
T+87756667ms: eth_sendTransaction
T+87756689ms:   Transaction: 0x4ae0c1e448cce75c770844c23492d2b1dc1ca5c3440559bb6d3b6e270e39369a
T+87756689ms:   Gas usage: 26981
T+87756689ms:   Block Number: 91
T+87756689ms:   Block Time: Wed Jan 17 2018 10:00:18 GMT-0500 (EST)
T+87756695ms: eth_getTransactionReceipt
T+87757703ms: evm_snapshot
T+87757724ms: eth_blockNumber
T+87757729ms: eth_sendTransaction
T+87757817ms:   Transaction: 0x4ae70e6bfa0ec9cd059ec3fb02f4a305306a09652ac9237e3f2e13cdf2218525
T+87757817ms:   Contract created: 0x35b338b4ade005f25a8982a597638827b8617ad4
T+87757817ms:   Gas usage: 1084706
T+87757817ms:   Block Number: 92
T+87757822ms:   Block Time: Wed Jan 17 2018 10:00:19 GMT-0500 (EST)
T+87757826ms: eth_newBlockFilter
T+87757829ms: eth_getFilterChanges
T+87757835ms: eth_getTransactionReceipt
T+87757854ms: eth_getCode
T+87757861ms: eth_uninstallFilter
T+87757866ms: eth_sendTransaction
T+87757901ms:   Transaction: 0x679b1c95f45e10260f8febae40e2911ffd0f36f9aca1a5746c7a3278c16ec114
T+87757901ms:   Contract created: 0x62227531b82259561cc9ad4413188f08e536598a
T+87757901ms:   Gas usage: 1297631
T+87757901ms:   Block Number: 93
T+87757901ms:   Block Time: Wed Jan 17 2018 10:00:19 GMT-0500 (EST)
T+87757907ms: eth_newBlockFilter
T+87757910ms: eth_getFilterChanges
T+87757918ms: eth_getTransactionReceipt
T+87757931ms: eth_getCode
T+87757938ms: eth_uninstallFilter
T+87757942ms: eth_sendTransaction
T+87757946ms: eth_call
T+87757971ms:   Transaction: 0x423f171176bf4b1316a1b4a771ac8bd5a57dbe314c068c42098f399d3b8d8456
T+87757971ms:   Gas usage: 30297
T+87757971ms:   Block Number: 94
T+87757971ms:   Block Time: Wed Jan 17 2018 10:00:19 GMT-0500 (EST)
T+87757983ms: eth_getTransactionReceipt
T+87758015ms: eth_blockNumber
T+87758020ms: eth_sendTransaction
T+87758064ms:   Transaction: 0x75f7a91122f110ad617026c70b1acaee49ba9a83b8b2148029be9e23aee601f3
T+87758064ms:   Contract created: 0x1148d9138ccdc770d5a544f4ecd2738831dd5b0e
T+87758064ms:   Gas usage: 1084706
T+87758064ms:   Block Number: 95
T+87758064ms:   Block Time: Wed Jan 17 2018 10:00:19 GMT-0500 (EST)
T+87758070ms: eth_newBlockFilter
T+87758075ms: eth_getFilterChanges
T+87758081ms: eth_getTransactionReceipt
T+87758097ms: eth_getCode
T+87758103ms: eth_uninstallFilter
T+87758109ms: eth_sendTransaction
T+87758162ms:   Transaction: 0xe8f1f8c27cbd7640baf21553172041bfcbf1fc3dd8071b96af54461b31c27937
T+87758162ms:   Contract created: 0x1cff61b8259f05f4bbf7aa4f769321e5fa70b22d
T+87758162ms:   Gas usage: 1297631
T+87758162ms:   Block Number: 96
T+87758162ms:   Block Time: Wed Jan 17 2018 10:00:20 GMT-0500 (EST)
T+87758166ms: eth_newBlockFilter
T+87758170ms: eth_getFilterChanges
T+87758177ms: eth_getTransactionReceipt
T+87758192ms: eth_getCode
T+87758199ms: eth_uninstallFilter
T+87758202ms: eth_sendTransaction
T+87758205ms: eth_call
T+87758235ms:   Transaction: 0xf9e531e7d5a2183e7da1ffbd190bbef6f463c6ba346394ed86b4228c015c9d2f
T+87758235ms:   Gas usage: 30297
T+87758235ms:   Block Number: 97
T+87758235ms:   Block Time: Wed Jan 17 2018 10:00:20 GMT-0500 (EST)
T+87758247ms: eth_getTransactionReceipt
T+87758300ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+87758300ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+87758300ms: 
T+87758300ms: TypeError: Cannot read property 'get' of undefined
T+87758300ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+87758300ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+87758300ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+87758300ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+87758300ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+87758300ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+87758300ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+87758300ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+87758300ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+87758300ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by benjamincburns** [comment]
Yanno, we _have_ to stop meeting like this, @yarrumretep!

This issue is due to trufflesuite/ganache-cli#417. Good news - check the Ganache releases page - the current beta (posted last night) fixes this bug!
