### ISSUE TITLE
System Error when running Ganache 2.5.4 on linux

### ISSUE THREAD

**Issue by chanrose** [trufflesuite/ganache#2873]
Somehow it happens so frequently now as I start generating the bytecode with vyper, whenever I deploy my truffle. It shows this error. Sometimes it works but the Storage say cannot decode my contract.

PLATFORM: linux
GANACHE VERSION: 2.5.4

EXCEPTION:
```
TypeError: Cannot read property 'address' of null
    at ProjectsWatcher.handleBlock (/tmp/.mount_ganachj3jKXS/resources/static/node/truffle-integration/projectsWatcher.js:208:24)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Subscription.<anonymous> (/tmp/.mount_ganachj3jKXS/resources/static/node/truffle-integration/projectsWatcher.js:57:9)
```

**Comment by chanrose** [comment]
Somehow it happens so frequently now as I start generating the bytecode with vyper, whenever I deploy my truffle. It shows this error. Sometimes it works but the Storage say cannot decode my contract.
