### ISSUE TITLE
Decoding Error when running Ganache 2.5.4 on linux

### ISSUE THREAD

**Issue by TomG5** [trufflesuite/ganache#2890]
I was executing a contract migration, with the following code:

```
const Generator = await deployer.deploy(BetGenerator).then( instance => {
    return BetGenerator.deployed()});
const Match =	await Generator.generator("BPL", "XYZ");
```

PLATFORM: linux
GANACHE VERSION: 2.5.4

EXCEPTION:
```
Error: Number can only safely store up to 53 bits
    at assert (/tmp/.mount_GanachAF6xeW/resources/static/node/node_modules/bn.js/lib/bn.js:6:21)
    at BN.toNumber (/tmp/.mount_GanachAF6xeW/resources/static/node/node_modules/bn.js/lib/bn.js:506:7)
    at decodeStorageReference (/tmp/.mount_GanachAF6xeW/resources/static/node/node_modules/@truffle/decoder/lib/decode/storage.ts:87:52)
    at decodeStorageReference.next (<anonymous>)
    at Object.decodeStorage [as default] (/tmp/.mount_GanachAF6xeW/resources/static/node/node_modules/@truffle/decoder/lib/decode/storage.ts:26:19)
    at decodeStorage.next (<anonymous>)
    at Object.decode [as default] (/tmp/.mount_GanachAF6xeW/resources/static/node/node_modules/@truffle/decoder/lib/decode/index.ts:26:32)
    at decode.next (<anonymous>)
    at TruffleContractDecoder.<anonymous> (/tmp/.mount_GanachAF6xeW/resources/static/node/node_modules/@truffle/decoder/lib/interface/contract-decoder.ts:283:24)
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/.mount_GanachAF6xeW/resources/static/node/node_modules/@truffle/decoder/dist/interface/contract-decoder.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by TomG5** [comment]
I removed in my contract an array of contracts that was being pushed and it 'solved' the deployment issue. But the syntax works fine at Remix so it might explain the source of the issue.
