### ISSUE TITLE
System Error when running Ganache 2.5.4 on linux

### ISSUE THREAD

**Issue by thanhhuy1509** [trufflesuite/ganache#2947]
PLATFORM: linux
GANACHE VERSION: 2.5.4

EXCEPTION:
```
Error: connection not open
    at WebsocketProvider.send (/tmp/.mount_ganachVguODO/resources/static/node/node_modules/web3-providers-ws/src/index.js:282:18)
    at Timeout._onTimeout (/tmp/.mount_ganachVguODO/resources/static/node/node_modules/web3-providers-ws/src/index.js:267:19)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

**Comment by bitBadger8** [comment]
Same  bru
