### ISSUE TITLE
Ganache (v2.5.4) New Workspace (Ethereum) errors out in Windows

### ISSUE THREAD

**Issue by rolan18** [trufflesuite/ganache#2986]
On a fresh install of v2.5.4 in Windows 10, I select "New Ethereum Workspace" I get a blank screen.

Environment:
* Ganache version:2.5.4
* Node version:14.17.0
* Operating System and version: Windows 10 (OS build 19043.1165)
* Truffle version: N/A
* Link to your project: N/A

## Current Behavior
I expect it to create a new workspace.
Instead, it hits an error.
After closing the GUI I can reopen it, and a new ethereum workspace with a default name appears.  When selected, it shows the settings menu for the workspace, but not a running blockchain.
Also, the only hostname available is "0.0.0.0 - All Interfaces", despite previously having set up a couple of others.

Here's the output from the console (after inspecting):
C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:18239 Download the React DevTools for a better development experience: https://fb.me/react-devtoolsYou might need to use a local HTTP server (instead of file://): https://fb.me/react-devtools-faq
renderer.js:2 TypeError: Cannot read property 'menu' of undefined
    at TopNavbar_TopNavbar.render (file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/renderer.js:2:152197)
    at ig (file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/renderer.js:2:75031)
    at hg (file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/renderer.js:2:74873)
    at pg (file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/renderer.js:2:77477)
    at Rg (file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/renderer.js:2:91400)
    at Sg (file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/renderer.js:2:91746)
    at Xg (file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/renderer.js:2:96407)
    at Yg (file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/renderer.js:2:96061)
    at If (file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/renderer.js:2:94580)
    at Object.enqueueSetState (file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/renderer.js:2:63697)
    at Router.setState (C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\app.asar\node_modules\react\cjs\react.development.js:413:16)
    at C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\app.asar\node_modules\react-router\modules\Router.js:33:16
    at listener (C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\app.asar\node_modules\history\cjs\history.js:178:24)
    at C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\app.asar\node_modules\history\cjs\history.js:196:23
    at Array.forEach (<anonymous>)
    at Object.notifyListeners (C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\app.asar\node_modules\history\cjs\history.js:195:15)
ug @ renderer.js:2
renderer.js:2 TypeError: Cannot read property 'concat' of undefined
    at new ConfigScreen_ConfigScreen (file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/renderer.js:2:229767)
    at hg (file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/renderer.js:2:72168)
    at pg (file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/renderer.js:2:77477)
    at Rg (file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/renderer.js:2:91400)
    at Sg (file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/renderer.js:2:91746)
    at Xg (file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/renderer.js:2:96407)
    at Yg (file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/renderer.js:2:96061)
    at If (file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/renderer.js:2:94580)
    at Object.enqueueSetState (file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/renderer.js:2:63697)
    at Router.setState (C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\app.asar\node_modules\react\cjs\react.development.js:413:16)
    at C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\app.asar\node_modules\react-router\modules\Router.js:33:16
    at listener (C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\app.asar\node_modules\history\cjs\history.js:178:24)
    at C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\app.asar\node_modules\history\cjs\history.js:196:23
    at Array.forEach (<anonymous>)
    at Object.notifyListeners (C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\app.asar\node_modules\history\cjs\history.js:195:15)
    at setState (C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\app.asar\node_modules\history\cjs\history.js:584:23)
ug @ renderer.js:2
renderer.js:2 Uncaught TypeError: Cannot read property 'menu' of undefined
    at TopNavbar_TopNavbar.render (file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/renderer.js:2:152197)
    at ig (file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/renderer.js:2:75031)
    at hg (file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/renderer.js:2:74873)
    at pg (file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/renderer.js:2:77477)
    at Rg (file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/renderer.js:2:91400)
    at Sg (file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/renderer.js:2:91746)
    at Xg (file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/renderer.js:2:96407)
    at Yg (file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/renderer.js:2:96061)
    at If (file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/renderer.js:2:94580)
    at Object.enqueueSetState (file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/renderer.js:2:63697)
    at Router.setState (C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\app.asar\node_modules\react\cjs\react.development.js:413:16)
    at C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\app.asar\node_modules\react-router\modules\Router.js:33:16
    at listener (C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\app.asar\node_modules\history\cjs\history.js:178:24)
    at C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\app.asar\node_modules\history\cjs\history.js:196:23
    at Array.forEach (<anonymous>)
    at Object.notifyListeners (C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\app.asar\node_modules\history\cjs\history.js:195:15)
DevTools failed to parse SourceMap: file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/renderer.js.map
DevTools failed to parse SourceMap: file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/react-router.js.map
DevTools failed to parse SourceMap: file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/xterm.js.map
DevTools failed to parse SourceMap: file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/xterm-addon-fit.js.map
DevTools failed to parse SourceMap: file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/xml-http-request.js.map
DevTools failed to parse SourceMap: file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/progress-event.js.map
DevTools failed to parse SourceMap: file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/errors.js.map
DevTools failed to parse SourceMap: file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/xml-http-request-event-target.js.map
DevTools failed to parse SourceMap: file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/xml-http-request-upload.js.map
DevTools failed to parse SourceMap: file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/transaction.js.map
DevTools failed to parse SourceMap: file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/index.js.map
DevTools failed to parse SourceMap: file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/account.js.map
DevTools failed to parse SourceMap: file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/bytes.js.map
DevTools failed to parse SourceMap: file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/hash.js.map
DevTools failed to parse SourceMap: file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/signature.js.map
DevTools failed to parse SourceMap: file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/object.js.map
DevTools failed to parse SourceMap: file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/index.js.map
DevTools failed to parse SourceMap: file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/fake.js.map
DevTools failed to parse SourceMap: file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/uri.all.js.map
DevTools failed to parse SourceMap: file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/performance-now.js.map
DevTools failed to parse SourceMap: file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/react-router-dom.js.map
DevTools failed to parse SourceMap: file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/vis-network.min.js.map
DevTools failed to parse SourceMap: file:///C:/Program%20Files/WindowsApps/GanacheUI_2.5.4.0_x64__5dg5pnz03psnj/app/resources/app.asar/styles.css.map

**Comment by bmcgoffin** [comment]
I experienced this same behavior but it happened to me after running a few successful workspaces. I uninstalled and did a fresh install too. I found my network adapter IP address had changed. I was unable to create any new projects or quick starts even after deleting all projects and re-installing the app. After changing the IP address back to the previous IP I was able to create workspaces and quickstarts again. You can find the IP address Ganache is looking for by turning on logging in the Advanced section of the GUI. Then try to create a new project and review the log to see what IP Ganache is attempting to use. My log output looked like: [2021/08/15 08:56:28.703] - Starting server with initial configuration: {"gasLimit":6721975,"gasPrice":20000000000,"hardfork":"muirGlacier","hostname":"172.23.16.1","port":7545, 
After changing the network adapter IP to the 172.23.16.1 address it fixed the issue for me.

**Comment by QinHaoChen97** [comment]
I am having a similar problem on ubuntu 18.04. I set the ganache startup port on the machine I built in mininet, and when I closed mininet I had the above problem. I tried restarting mininet and everything is back to normal, if you are also trying to do network emulation, you can try restoring your original network environment.
