### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by epmiller8464** [trufflesuite/ganache#304]
PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+0ms: Starting server with configuration: {"hostname":"localhost","network_id":10,"port":8545,"total_accounts":10,"unlocked_accounts":[]}
T+144ms: Ganache started successfully!
T+144ms: Waiting for requests...
T+114492ms: eth_accounts
T+2611767ms: eth_accounts
T+2611775ms: eth_accounts
T+2611782ms: net_version
T+2611785ms: net_version
T+2611790ms: eth_sendTransaction
T+2611844ms:   Transaction: 0xf3a1e081c926a5497994af26b13c830bf6a67ec7af6d08a5d709ce85a7942f90
T+2611844ms:   Contract created: 0x32b842157bbac5e294ab3ae05ead16bce2b8f0c7
T+2611844ms:   Gas usage: 269607
T+2611847ms:   Block Number: 1
T+2611847ms:   Block Time: Wed Jan 24 2018 05:11:10 GMT-0600 (CST)
T+2611850ms: eth_newBlockFilter
T+2611852ms: eth_getFilterChanges
T+2611889ms: eth_getTransactionReceipt
T+2611893ms: eth_getCode
T+2611899ms: eth_uninstallFilter
T+2611902ms: eth_sendTransaction
T+2611936ms:   Transaction: 0xd807a70048dda7a10fa28d2e1d22cbed723cba76b3a697bbb03139412fea63a6
T+2611936ms:   Gas usage: 41981
T+2611936ms:   Block Number: 2
T+2611939ms:   Block Time: Wed Jan 24 2018 05:11:10 GMT-0600 (CST)
T+2611941ms: eth_getTransactionReceipt
T+2611948ms: eth_accounts
T+2611953ms: net_version
T+2611956ms: net_version
T+2611961ms: eth_sendTransaction
T+2611990ms:   Transaction: 0xf63b840177ce88d9ff42a70f094585240df7d166645c71a4856ad6c9f9de6dee
T+2611990ms:   Contract created: 0xb8c077956f788470038c25e0c3e5269ca20c253e
T+2611990ms:   Gas usage: 536645
T+2611990ms:   Block Number: 3
T+2611990ms:   Block Time: Wed Jan 24 2018 05:11:10 GMT-0600 (CST)
T+2611995ms:   Runtime Error: revert
T+2626813ms: eth_accounts
T+2626828ms: eth_call
T+2626850ms: eth_call
T+2626863ms: eth_accounts
T+2626871ms: eth_sendTransaction
T+2626891ms:   Transaction: 0x160d1e0a889b7bd7ae5aa7fef647b36262ee7a1f3cb831c2c1b9cd9e7b0e3cec
T+2626891ms:   Contract created: 0x52d9fe0eea98e993eb87cd65ec3ec6eae1f4ec26
T+2626891ms:   Gas usage: 269607
T+2626891ms:   Block Number: 4
T+2626894ms:   Block Time: Wed Jan 24 2018 05:11:25 GMT-0600 (CST)
T+2626897ms: eth_newBlockFilter
T+2626900ms: eth_getFilterChanges
T+2626906ms: eth_getTransactionReceipt
T+2626911ms: eth_getCode
T+2626918ms: eth_uninstallFilter
T+2626921ms: eth_sendTransaction
T+2626967ms:   Transaction: 0xc2c8459351132a94f38b217b7652df6340bc1ac1cd657743970fce0f6d267625
T+2626967ms:   Gas usage: 41981
T+2626967ms:   Block Number: 5
T+2626967ms:   Block Time: Wed Jan 24 2018 05:11:25 GMT-0600 (CST)
T+2626971ms: eth_getTransactionReceipt
T+2626976ms: eth_accounts
T+2626978ms: net_version
T+2626980ms: net_version
T+2626983ms: eth_sendTransaction
T+2627000ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+2627000ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+2627000ms: 
T+2627000ms: TypeError: Cannot read property 'get' of undefined
T+2627000ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+2627000ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+2627000ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+2627000ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+2627000ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+2627000ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+2627000ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+2627000ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+2627000ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+2627000ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by benjamincburns** [comment]
Hi @epmiller8464. Thanks for reporting this. You're running into trufflesuite/ganache-cli#417 here. That bug is fixed in the latest Ganache beta, which can be downloaded from our [releases](https://github.com/trufflesuite/ganache/releases) page!

**Comment by epmiller8464** [comment]
Awesome!
