### ISSUE TITLE
Invalid JSON RPC response (instead of revert)

### ISSUE THREAD

**Issue by nickjm** [trufflesuite/ganache#312]
I was running Ganache 1.0.1 and just updated to 1.1.0-beta.0 All my tests passed on most runs, but after updating to 1.1.0-beta.0 most of my tests fail with the error `Error: Invalid JSON RPC response: {"id":137,"jsonrpc":"2.0"}` or variants of that. I have found this to be because of a different error response. Specifically, I was expecting a `revert` when I got this response. The release notes describe an `error.data` field that informs client what type of error it was, but in my case that field is equal to `undefined`

 

## Expected Behavior

Tests that work in Ganache 1.0.1 should work in 1.1.0. Specifically, when a revert is thrown, I would expect that to be in the error message as before.

## Current Behavior

Now I get an invalid JSON RPC response, which isn't very helpful.

## Steps to Reproduce (for bugs)

Run tests, probably needs to include something like creating a transaction that should fail with a revert check:
```
try {
  await promise; // some generic transaction with a contract that should fail via revert or require.
} catch (error) {
  const revertEvent = error.message.search('revert') >= 0;
  assert(revertEvent, 'expected revert');
}
```
Full Stacktrace:
```
Error: Invalid JSON RPC response: {"id":202,"jsonrpc":"2.0"}
    at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:41483:16)
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:330353:36
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:326008:9
    at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:329052:7)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:176427:18)
    at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:176717:12)
    at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:176872:12)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:176832:24)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickDomainCallback (internal/process/next_tick.js:198:9)
```
## Your Environment

* Version used: 1.1.0-beta.0
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
* Server type and version:
* Operating System and version: Mac High Sierra 10.13.3
* Link to your project:

**Comment by nickjm** [comment]
I think the aforementioned issue and others come from the fact that this version of ganache is using the latest web3 (.2 instead of .1) -- i'm gonna make a new issue that addresses some concerns and close this one

**Comment by nickjm** [comment]
Actually this is still an issue
```
Error: Invalid JSON RPC response: {"id":202,"jsonrpc":"2.0"}
```
returned instead of expected revert

**Comment by nickjm** [comment]
Made a question here: https://ethereum.stackexchange.com/questions/38033/new-ganache-1-1-0-beta-0-causes-invalid-json-rpc-response

**Comment by benjamincburns** [comment]
Hi @nickjm - thanks for reporting this! Let's track it over on trufflesuite/ganache-cli#471.
