### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by truongbm** [trufflesuite/ganache#319]
PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+0ms: Starting server with configuration: {"hostname":"127.0.0.1","mnemonic":"candy maple cake sugar pudding cream honey rich smooth crumble sweet treat","network_id":5777,"port":7545,"total_accounts":10,"unlocked_accounts":[]}
T+429ms: Ganache started successfully!
T+429ms: Waiting for requests...
T+72760ms: eth_estimateGas
T+74521ms: eth_getBalance
T+74521ms: eth_gasPrice
T+74521ms: eth_getTransactionCount
T+74571ms: eth_getBalance
T+74571ms: eth_gasPrice
T+74571ms: eth_getTransactionCount
T+74726ms: eth_estimateGas
T+74733ms: 
T+74733ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+74733ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+74740ms: AssertionError: The field to must have byte length of 20
T+74740ms:     at FakeTransaction.setter [as to] (/node_modules/ganache-cli/build/lib.node.js:7366:9)
T+74740ms:     at /node_modules/ganache-cli/build/lib.node.js:7416:63
T+74740ms:     at Array.forEach (native)
T+74740ms:     at Object.exports.defineProperties (/node_modules/ganache-cli/build/lib.node.js:7415:14)
T+74740ms:     at FakeTransaction.Transaction (/node_modules/ganache-cli/build/lib.node.js:78121:13)
T+74740ms:     at FakeTransaction (/node_modules/ganache-cli/build/lib.node.js:20454:5)
T+74740ms:     at /node_modules/ganache-cli/build/lib.node.js:80343:14
T+74740ms:     at /node_modules/ganache-cli/build/lib.node.js:21924:5
T+74740ms:     at /node_modules/ganache-cli/build/lib.node.js:55954:5
T+74740ms:     at /node_modules/ganache-cli/build/lib.node.js:56320:14
```

**Comment by benjamincburns** [comment]
Hi @truongbm. Thank you for reporting this. If you search closed issues you'll see numerous reports of this same problem. Fortunately, this issue is fixed in the current beta.
