### ISSUE TITLE
System Error when running Ganache 1.0.2 on linux

### ISSUE THREAD

**Issue by almindor** [trufflesuite/ganache#321]
Running dapp tests (lots of contract deploys then transactions)

PLATFORM: linux
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+1215145ms:   Gas usage: 53028
T+1215145ms:   Block Number: 292
T+1215145ms:   Block Time: Tue Jan 30 2018 09:50:52 GMT-0700 (MST)
T+1215146ms: eth_getTransactionReceipt
T+1215592ms: eth_getFilterChanges
T+1215592ms: eth_getFilterChanges
T+1215592ms: eth_getFilterChanges
T+1215592ms: eth_getFilterChanges
T+1215598ms: eth_blockNumber
T+1215600ms: eth_sendTransaction
T+1215651ms:   Transaction: 0xfa6b667cb63f1b543193467e95f77dcdef933e00ad144468a6b36f0dc3f0146f
T+1215651ms:   Gas usage: 123363
T+1215651ms:   Block Number: 293
T+1215651ms:   Block Time: Tue Jan 30 2018 09:50:52 GMT-0700 (MST)
T+1215652ms: eth_getTransactionReceipt
T+1216092ms: eth_getFilterChanges
T+1216093ms: eth_getFilterChanges
T+1216093ms: eth_getFilterChanges
T+1216093ms: eth_getFilterChanges
T+1216099ms: eth_sendTransaction
T+1216148ms:   Transaction: 0x36fb0876159a59a1190111d091d57d9489ca4b8a83d4f694f15b8a6b761e8da7
T+1216148ms:   Gas usage: 70985
T+1216148ms:   Block Number: 294
T+1216148ms:   Block Time: Tue Jan 30 2018 09:50:53 GMT-0700 (MST)
T+1216150ms: eth_getTransactionReceipt
T+1216594ms: eth_getFilterChanges
T+1216596ms: eth_getFilterChanges
T+1216596ms: eth_getFilterChanges
T+1216596ms: eth_getFilterChanges
T+1216665ms: eth_uninstallFilter
T+1216738ms: eth_uninstallFilter
T+1216815ms: eth_uninstallFilter
T+1216888ms: eth_uninstallFilter
T+1388851ms: net_version
T+1388856ms: eth_accounts
T+1388875ms: eth_accounts
T+1397585ms: eth_accounts
T+1397592ms: eth_sendTransaction
T+1397618ms:   Transaction: 0x12e3b57d5e218c9930fa4c80fa2784dd1bb55fc7af0877b8f624c8a4e539575d
T+1397618ms:   Contract created: 0xd8733aabb2c67149a18e1fd7a6569cc721b474b8
T+1397618ms:   Gas usage: 269607
T+1397618ms:   Block Number: 295
T+1397618ms:   Block Time: Tue Jan 30 2018 09:53:54 GMT-0700 (MST)
T+1397620ms: eth_newBlockFilter
T+1397622ms: eth_getFilterChanges
T+1397629ms: eth_getTransactionReceipt
T+1397760ms: eth_getCode
T+1397767ms: eth_uninstallFilter
T+1397768ms: eth_sendTransaction
T+1397781ms:   Transaction: 0xf156dafbd951abbd01347836b0dabd2f03478ac3f1b7e2d6d98262085cdf7b88
T+1397781ms:   Gas usage: 41981
T+1397781ms:   Block Number: 296
T+1397781ms:   Block Time: Tue Jan 30 2018 09:53:55 GMT-0700 (MST)
T+1397782ms: eth_getTransactionReceipt
T+1397888ms: eth_accounts
T+1397970ms: net_version
T+1397977ms: eth_sendTransaction
T+1397979ms: eth_sendTransaction
T+1398055ms:   Transaction: 0x5862fd43bb76b7614fde96678daf28fa1aff1cd3f5c31d9bdfa7306b9a318403
T+1398055ms:   Contract created: 0x31284dd9b04450ac07d44f3d4f93c71a536a6971
T+1398055ms:   Gas usage: 6244287
T+1398055ms:   Block Number: 297
T+1398055ms:   Block Time: Tue Jan 30 2018 09:53:55 GMT-0700 (MST)
T+1398058ms: eth_newBlockFilter
T+1398070ms:   Transaction: 0x8316bf2b925f172c1268a46ccedb2cde2c092e954e15760f1cc720900f1e8962
T+1398070ms:   Contract created: 0xc9f92b8284123b4206c0951ad5dc11e68a5e7dee
T+1398070ms:   Gas usage: 121800
T+1398070ms:   Block Number: 298
T+1398070ms:   Block Time: Tue Jan 30 2018 09:53:55 GMT-0700 (MST)
T+1398072ms: eth_newBlockFilter
T+1398073ms: eth_getFilterChanges
T+1398075ms: eth_getFilterChanges
T+1398078ms: eth_getTransactionReceipt
T+1398166ms: eth_getCode
T+1398166ms: eth_getTransactionReceipt
T+1398195ms: eth_getCode
T+1398197ms: eth_uninstallFilter
T+1398198ms: eth_uninstallFilter
T+1398200ms: eth_sendTransaction
T+1398202ms: eth_sendTransaction
T+1398215ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+1398215ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_W
T+1398215ms: 
T+1398215ms: TypeError: Cannot read property 'get' of undefined
T+1398215ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+1398215ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+1398215ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+1398215ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+1398215ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+1398215ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+1398215ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+1398215ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+1398215ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+1398215ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by benjamincburns** [comment]
This is fixed as of trufflesuite/ganache-core#417.

Re: broken tests, 1.1.0-beta.0 has a known issue where it produces an empty response when transactions are rejected prior to running (aka prior to entering the transaction pool). The next beta will be out in the next 24-48h, and it has fixed this problem.
