### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by wang502** [trufflesuite/ganache#323]
PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+112668ms: eth_getTransactionReceipt
T+112679ms: eth_call
T+112683ms:   Transaction: 0x700a0690a0ca51819280a3c59316b5f9c01c94266440981ad791e0c6f05b99f0
T+112683ms:   Gas usage: 42694
T+112683ms:   Block Number: 15
T+112683ms:   Block Time: Tue Jan 30 2018 18:43:10 GMT-0500 (EST)
T+112689ms: eth_getTransactionReceipt
T+112692ms: eth_call
T+112793ms: eth_sendTransaction
T+112831ms:   Transaction: 0x3f9de433f1747e832e1e15b7aa64b8a4e8e8095811b91513cd3469dc6bb9451d
T+112831ms:   Gas usage: 27606
T+112831ms:   Block Number: 16
T+112831ms:   Block Time: Tue Jan 30 2018 18:43:10 GMT-0500 (EST)
T+112838ms: eth_getTransactionReceipt
T+112842ms: eth_call
T+319656ms: eth_accounts
T+319779ms: eth_accounts
T+336338ms: eth_accounts
T+336366ms: eth_sendTransaction
T+336425ms:   Transaction: 0xc935f916c3bce5a94bc687a707850b4f9f82b062840bf6b4f6597d83d29594fa
T+336425ms:   Contract created: 0xecfcab0a285d3380e488a39b4bb21e777f8a4eac
T+336425ms:   Gas usage: 269543
T+336425ms:   Block Number: 17
T+336425ms:   Block Time: Tue Jan 30 2018 18:46:54 GMT-0500 (EST)
T+336432ms: eth_newBlockFilter
T+336439ms: eth_getFilterChanges
T+336450ms: eth_getTransactionReceipt
T+336456ms: eth_getCode
T+336476ms: eth_uninstallFilter
T+336480ms: eth_sendTransaction
T+336628ms:   Transaction: 0x64df98e7d3f1cf5dc7eaa5264011714bf49802d9fda56003e202434903c2581b
T+336628ms:   Gas usage: 41981
T+336628ms:   Block Number: 18
T+336628ms:   Block Time: Tue Jan 30 2018 18:46:54 GMT-0500 (EST)
T+336634ms: eth_getTransactionReceipt
T+336640ms: eth_accounts
T+336648ms: eth_sendTransaction
T+336668ms:   Transaction: 0x272f1a6b1023bfeb6bb506ebd6147d1b07dec5c8b93582718b73818ad4a0d520
T+336668ms:   Contract created: 0x4e72770760c011647d4873f60a3cf6cdea896cd8
T+336668ms:   Gas usage: 1962183
T+336668ms:   Block Number: 19
T+336676ms:   Block Time: Tue Jan 30 2018 18:46:54 GMT-0500 (EST)
T+336683ms: eth_newBlockFilter
T+336690ms: eth_getFilterChanges
T+336696ms: eth_getTransactionReceipt
T+336704ms: eth_getCode
T+336713ms: eth_uninstallFilter
T+336725ms: eth_sendTransaction
T+336905ms:   Transaction: 0x2613896914f5d1eeaed6be42e3e0466d891206e27c197a7bac0078225f4d693a
T+336905ms:   Gas usage: 26981
T+336905ms:   Block Number: 20
T+336905ms:   Block Time: Tue Jan 30 2018 18:46:54 GMT-0500 (EST)
T+336910ms: eth_getTransactionReceipt
T+405550ms: eth_accounts
T+405704ms: eth_accounts
T+420917ms: eth_accounts
T+420936ms: eth_sendTransaction
T+420970ms:   Transaction: 0xeb2a0e4e4c24322073c7cb39177b60b85c26de947d04161231c83c871322739d
T+420970ms:   Contract created: 0x13274fe19c0178208bcbee397af8167a7be27f6f
T+420970ms:   Gas usage: 269543
T+420970ms:   Block Number: 21
T+420970ms:   Block Time: Tue Jan 30 2018 18:48:19 GMT-0500 (EST)
T+420974ms: eth_newBlockFilter
T+420979ms: eth_getFilterChanges
T+420983ms: eth_getTransactionReceipt
T+420991ms: eth_getCode
T+421004ms: eth_uninstallFilter
T+421009ms: eth_sendTransaction
T+421041ms:   Transaction: 0x77f46a5fa693338c4b20fedf5391b4de823415377cdd79674055f088a8e2df4f
T+421041ms:   Gas usage: 41981
T+421041ms:   Block Number: 22
T+421045ms:   Block Time: Tue Jan 30 2018 18:48:19 GMT-0500 (EST)
T+421049ms: eth_getTransactionReceipt
T+421053ms: eth_accounts
T+421063ms: eth_sendTransaction
T+421141ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+421141ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+421141ms: 
T+421141ms: TypeError: Cannot read property 'get' of undefined
T+421141ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+421141ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+421141ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+421141ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+421141ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+421141ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+421141ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+421141ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+421141ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+421141ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by benjamincburns** [comment]
Hi @wang502. Thanks for reporting! This issue is already documented over at trufflesuite/ganache-cli#417, and I'm pleased to say that a fix is in place in the latest Ganache beta.
