### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by sabhiram** [trufflesuite/ganache#326]
This happened when running `truffle test`. 

PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+1325013ms: eth_sendTransaction
T+1325912ms:   Transaction: 0x7fca33ad3722aed6f4e3c571fb1cbfd673c7ff71a3f8a7f95b514db93cefe493
T+1325912ms:   Contract created: 0xdd56e578c079532a04d879391596ac95751d7fbc
T+1325912ms:   Gas usage: 6412362
T+1325912ms:   Block Number: 175
T+1325912ms:   Block Time: Wed Jan 31 2018 20:25:50 GMT-0800 (PST)
T+1325915ms: eth_newBlockFilter
T+1325920ms: eth_getFilterChanges
T+1325934ms: eth_getTransactionReceipt
T+1325941ms: eth_getCode
T+1325943ms: eth_uninstallFilter
T+1325944ms: eth_call
T+1325955ms: eth_sendTransaction
T+1325979ms:   Transaction: 0x3c2037cb470f3ec19d55c05ad1ca9d34b92952d3932e657887f565e10d56b34a
T+1325979ms:   Gas usage: 70138
T+1325979ms:   Block Number: 176
T+1325979ms:   Block Time: Wed Jan 31 2018 20:25:51 GMT-0800 (PST)
T+1325982ms: eth_getTransactionReceipt
T+1325988ms: eth_call
T+1326001ms: eth_blockNumber
T+1326004ms: eth_sendTransaction
T+1326595ms:   Transaction: 0x204b7e20a2863f1f8eca25b1d76bc100f7528368fec5dc3800d7bf6a2dc7397a
T+1326595ms:   Contract created: 0xaa862ddac09f6736a61e1124040fd883a6533c19
T+1326595ms:   Gas usage: 6412362
T+1326595ms:   Block Number: 177
T+1326595ms:   Block Time: Wed Jan 31 2018 20:25:51 GMT-0800 (PST)
T+1326598ms: eth_newBlockFilter
T+1326600ms: eth_getFilterChanges
T+1326609ms: eth_getTransactionReceipt
T+1326617ms: eth_getCode
T+1326621ms: eth_uninstallFilter
T+1326623ms: eth_call
T+1326630ms: eth_call
T+1326647ms: eth_sendTransaction
T+1326670ms:   Transaction: 0x58d1f888e6495a31c4ba622e7c56eb43ccebd4441cb1654c0d0d0d34a22f03de
T+1326670ms:   Gas usage: 70138
T+1326670ms:   Block Number: 178
T+1326670ms:   Block Time: Wed Jan 31 2018 20:25:52 GMT-0800 (PST)
T+1326673ms: eth_getTransactionReceipt
T+1326677ms: eth_call
T+1326690ms: eth_getLogs
T+1326704ms: eth_blockNumber
T+1326707ms: eth_sendTransaction
T+1327281ms:   Transaction: 0x191e73852b4730bb312bce73be43efde0bbab61c1e49cd653974e988205e29dc
T+1327281ms:   Contract created: 0x432adf73ac67ff0810eae7dec53dbf077f228a6e
T+1327281ms:   Gas usage: 6412362
T+1327281ms:   Block Number: 179
T+1327281ms:   Block Time: Wed Jan 31 2018 20:25:52 GMT-0800 (PST)
T+1327283ms: eth_newBlockFilter
T+1327286ms: eth_getFilterChanges
T+1327295ms: eth_getTransactionReceipt
T+1327302ms: eth_getCode
T+1327305ms: eth_uninstallFilter
T+1327306ms: eth_call
T+1327315ms: eth_call
T+1327354ms: eth_sendTransaction
T+1327377ms:   Transaction: 0x94b286a298f20a0c0f91b7054cac645cc10085ff4e96437d3522296270a284de
T+1327377ms:   Gas usage: 70138
T+1327377ms:   Block Number: 180
T+1327377ms:   Block Time: Wed Jan 31 2018 20:25:52 GMT-0800 (PST)
T+1327379ms: eth_getTransactionReceipt
T+1327383ms: eth_sendTransaction
T+1327406ms:   Transaction: 0x4d316873c75d06e234fabd63bcc129b3d8903175a124c26840b8c45cb31a52c7
T+1327406ms:   Gas usage: 55138
T+1327406ms:   Block Number: 181
T+1327406ms:   Block Time: Wed Jan 31 2018 20:25:52 GMT-0800 (PST)
T+1327408ms: eth_getTransactionReceipt
T+1327417ms: eth_sendTransaction
T+1328055ms:   Transaction: 0x805108cab7c0e99b211f39b6ca0e76b4d44a721935bc973506c0f91d7a7ae61a
T+1328055ms:   Gas usage: 4847545
T+1328055ms:   Block Number: 182
T+1328055ms:   Block Time: Wed Jan 31 2018 20:25:53 GMT-0800 (PST)
T+1328057ms: eth_getTransactionReceipt
T+1328079ms: eth_call
T+1328110ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+1328110ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+1328110ms: 
T+1328110ms: TypeError: Cannot read property 'get' of undefined
T+1328110ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+1328110ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+1328110ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+1328110ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+1328110ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+1328110ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+1328110ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+1328110ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+1328110ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+1328110ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by benjamincburns** [comment]
Hi @sabhiram - thanks for reporting this. This issue (trufflesuite/ganache-cli#417) is fixed in the current beta.
