### ISSUE TITLE
System Error when running Ganache 1.0.2 on linux

### ISSUE THREAD

**Issue by nguyenngocanhvu** [trufflesuite/ganache#328]
PLATFORM: linux
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+747358ms:   Transaction: 0x4d94887277b1678f89db974197cb67773b5e658b896a8507df76f95ef04046bc
T+747358ms:   Contract created: 0xf69bf0cc5c02d97120e6fa1ee7a71eed98caf875
T+747358ms:   Gas usage: 1809201
T+747358ms:   Block Number: 46
T+747358ms:   Block Time: Mon Feb 05 2018 09:38:17 GMT+0700 (+07)
T+747360ms: eth_newBlockFilter
T+747362ms: eth_getFilterChanges
T+747369ms: eth_getTransactionReceipt
T+747372ms: eth_getCode
T+747378ms: eth_uninstallFilter
T+747380ms: eth_sendTransaction
T+747398ms:   Transaction: 0x481e59a4cce66670fe36a38a12423a4e3a0360ed03bbb6b04efc0e00ba7da4c7
T+747398ms:   Gas usage: 26965
T+747398ms:   Block Number: 47
T+747398ms:   Block Time: Mon Feb 05 2018 09:38:17 GMT+0700 (+07)
T+747400ms: eth_getTransactionReceipt
T+747413ms: evm_snapshot
T+747427ms: eth_blockNumber
T+747431ms: eth_sendTransaction
T+747458ms:   Transaction: 0xf87fc2d49eeee2763539d47b4ab5dd3534852fde327baf765c9f913ea5e1b947
T+747458ms:   Contract created: 0xf6860f23a1ab1de9ce4b28b108d6dfe037a469a5
T+747458ms:   Gas usage: 1809585
T+747458ms:   Block Number: 48
T+747458ms:   Block Time: Mon Feb 05 2018 09:38:17 GMT+0700 (+07)
T+747460ms: eth_newBlockFilter
T+747463ms: eth_getFilterChanges
T+747468ms: eth_getTransactionReceipt
T+747472ms: eth_getCode
T+747477ms: eth_uninstallFilter
T+747477ms: eth_sendTransaction
T+747569ms:   Transaction: 0x6297c39e836779829005162a9a5aef64837c92628bfc2dbe504c6cb7b20d5824
T+747569ms:   Gas usage: 1011293
T+747569ms:   Block Number: 49
T+747569ms:   Block Time: Mon Feb 05 2018 09:38:17 GMT+0700 (+07)
T+747571ms: eth_getTransactionReceipt
T+747578ms: net_version
T+747580ms: eth_call
T+747593ms: net_version
T+747595ms: eth_call
T+747604ms: net_version
T+747608ms: eth_sendTransaction
T+747636ms:   Transaction: 0xa3f4c6c07d6c9a4aa146248ea019ea8cdd9c3132082f40b6698c8386d1198a42
T+747636ms:   Gas usage: 219050
T+747636ms:   Block Number: 50
T+747636ms:   Block Time: Mon Feb 05 2018 09:38:17 GMT+0700 (+07)
T+747637ms: eth_getTransactionReceipt
T+747644ms: net_version
T+747646ms: eth_sendTransaction
T+747698ms:   Transaction: 0x927becad0bd6d6d4e329526fcb10f7be3ec22a53abbabb4eb9549618d11a2e84
T+747698ms:   Gas usage: 26056
T+747698ms:   Block Number: 51
T+747701ms:   Block Time: Mon Feb 05 2018 09:38:17 GMT+0700 (+07)
T+747706ms: eth_getTransactionReceipt
T+761553ms: net_version
T+761559ms: eth_accounts
T+761581ms: eth_accounts
T+768094ms: eth_accounts
T+768108ms: eth_sendTransaction
T+768133ms:   Transaction: 0xaa6d6dddb15a6a46ec1a36e5a210a38c3cc3265ca556bcfb11afa0a311f9d099
T+768133ms:   Contract created: 0x7e05f63cf65a0e77caf4bc5260755040446a7db6
T+768133ms:   Gas usage: 201556
T+768133ms:   Block Number: 52
T+768135ms:   Block Time: Mon Feb 05 2018 09:38:38 GMT+0700 (+07)
T+768137ms: eth_newBlockFilter
T+768140ms: eth_getFilterChanges
T+768149ms: eth_getTransactionReceipt
T+768155ms: eth_getCode
T+768167ms: eth_uninstallFilter
T+768169ms: eth_sendTransaction
T+768192ms:   Transaction: 0x310f9b1776bb4812470e03bc1b20394a842e4e1cf1175758837d7216a4839c6a
T+768192ms:   Gas usage: 41965
T+768192ms:   Block Number: 53
T+768194ms:   Block Time: Mon Feb 05 2018 09:38:38 GMT+0700 (+07)
T+768197ms: eth_getTransactionReceipt
T+768201ms: eth_accounts
T+768248ms: net_version
T+768252ms: net_version
T+768256ms: eth_sendTransaction
T+768314ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+768314ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_W
T+768314ms: 
T+768314ms: TypeError: Cannot read property 'get' of undefined
T+768314ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+768314ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+768314ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+768314ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+768314ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+768314ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+768314ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+768314ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+768314ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+768314ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by benjamincburns** [comment]
Thanks for reporting this! This is fixed as of trufflesuite/ganache-core#417.

This fix is in 1.1.0-beta.0, but that version has a known issue where it produces an empty response when transactions are rejected prior to running (aka prior to entering the transaction pool). The next beta will be out in the next 24-48h, and it has fixed this problem, so I'd hold off until then.
