### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by wang502** [trufflesuite/ganache#329]
PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+2471998ms:   Runtime Error: revert
T+2472001ms: eth_blockNumber
T+2472004ms: eth_sendTransaction
T+2472132ms:   Transaction: 0xfee92c2662578a7f0ec6eab782adebe9e9bc38a7eba59d06ff48d43889ab060a
T+2472132ms:   Gas usage: 100887
T+2472132ms:   Block Number: 120
T+2472132ms:   Block Time: Mon Feb 05 2018 18:05:31 GMT-0500 (EST)
T+2472136ms: eth_getTransactionReceipt
T+2472143ms: eth_call
T+2587604ms: eth_accounts
T+2587811ms: eth_accounts
T+2610074ms: eth_accounts
T+2610088ms: eth_sendTransaction
T+2610124ms:   Transaction: 0xb5ac6f8f565a1b6f50e124875540c44b80b0bdb6befc052954d53a2483130257
T+2610124ms:   Contract created: 0x78f417302de7d49046688e4e39807e6addc47877
T+2610124ms:   Gas usage: 269607
T+2610124ms:   Block Number: 121
T+2610128ms:   Block Time: Mon Feb 05 2018 18:07:49 GMT-0500 (EST)
T+2610132ms: eth_newBlockFilter
T+2610135ms: eth_getFilterChanges
T+2610140ms: eth_getTransactionReceipt
T+2610147ms: eth_getCode
T+2610160ms: eth_uninstallFilter
T+2610164ms: eth_sendTransaction
T+2610190ms:   Transaction: 0x0f4afc67b1c5704c756e6f60f239b83c66aae73546458e6cd191179694192573
T+2610190ms:   Gas usage: 41981
T+2610190ms:   Block Number: 122
T+2610194ms:   Block Time: Mon Feb 05 2018 18:07:49 GMT-0500 (EST)
T+2610197ms: eth_getTransactionReceipt
T+2610203ms: eth_accounts
T+2610211ms: net_version
T+2610215ms: net_version
T+2610218ms: eth_sendTransaction
T+2610258ms:   Transaction: 0xb19a9939811cbce04ca4094e8af4143e23d1a9c18911ebffe93812f179e94f50
T+2610258ms:   Contract created: 0x96a08824f87070075262dbce23c6babffdca0493
T+2610258ms:   Gas usage: 2068698
T+2610258ms:   Block Number: 123
T+2610262ms:   Block Time: Mon Feb 05 2018 18:07:50 GMT-0500 (EST)
T+2610265ms: eth_newBlockFilter
T+2610268ms: eth_getFilterChanges
T+2610271ms: eth_getTransactionReceipt
T+2610280ms: eth_getCode
T+2610289ms: eth_uninstallFilter
T+2610293ms: eth_sendTransaction
T+2610318ms:   Transaction: 0xfcddaf899841da51287e0938fbfe53ce392d6b1f0d60eeb1a0e4ef791ec25448
T+2610318ms:   Gas usage: 26981
T+2610318ms:   Block Number: 124
T+2610321ms:   Block Time: Mon Feb 05 2018 18:07:50 GMT-0500 (EST)
T+2610325ms: eth_getTransactionReceipt
T+2610349ms: evm_snapshot
T+2610593ms: eth_blockNumber
T+2610598ms: eth_sendTransaction
T+2610640ms:   Transaction: 0x80425cab1303c443cad65f6299932d4d959f5347a7ecd0c27c0300090433a423
T+2610640ms:   Contract created: 0x17647ef21c6fd7e67486c57affbb1faf9eb30ea5
T+2610640ms:   Gas usage: 2068698
T+2610640ms:   Block Number: 125
T+2610640ms:   Block Time: Mon Feb 05 2018 18:07:50 GMT-0500 (EST)
T+2610674ms: eth_newBlockFilter
T+2610678ms: eth_getFilterChanges
T+2610686ms: eth_getTransactionReceipt
T+2610698ms: eth_getCode
T+2610705ms: eth_uninstallFilter
T+2610709ms: eth_blockNumber
T+2610716ms: eth_sendTransaction
T+2610790ms:   Transaction: 0xc1a2ea0e1b0ec680766e8be05356e19e47f557ea23ea58e907c73fb2cf428931
T+2610790ms:   Gas usage: 109041
T+2610790ms:   Block Number: 126
T+2610794ms:   Block Time: Mon Feb 05 2018 18:07:50 GMT-0500 (EST)
T+2610797ms: eth_getTransactionReceipt
T+2610805ms: eth_blockNumber
T+2610811ms: eth_call
T+2610874ms: eth_blockNumber
T+2610879ms: eth_call
T+2610905ms: eth_blockNumber
T+2610910ms: eth_call
T+2610930ms: eth_blockNumber
T+2610937ms: eth_sendTransaction
T+2611032ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+2611032ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+2611032ms: 
T+2611032ms: TypeError: Cannot read property 'get' of undefined
T+2611032ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+2611032ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+2611032ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+2611032ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+2611032ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+2611032ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+2611032ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+2611032ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+2611032ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+2611032ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by wang502** [comment]
Duplicate Issue that has been resolved. Gonna close it.
