### ISSUE TITLE
System Error when running Ganache 1.0.2 on linux

### ISSUE THREAD

**Issue by AdrianClv** [trufflesuite/ganache#332]
Running `truffle test` after upgrading from 1.0.1

PLATFORM: linux
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+66473ms: eth_getTransactionReceipt
T+66477ms: eth_getCode
T+66480ms: eth_uninstallFilter
T+66482ms: net_version
T+66484ms: eth_sendTransaction
T+66507ms:   Transaction: 0xe96e454b0e9d276536d81b8a62f6be4eba12ef70b337a4bb7c84bf2c3e99b637
T+66507ms:   Gas usage: 121960
T+66507ms:   Block Number: 59
T+66507ms:   Block Time: Sat Feb 17 2018 12:03:39 GMT+0100 (CET)
T+66509ms: eth_getTransactionReceipt
T+66515ms: net_version
T+66518ms: eth_sendTransaction
T+66530ms:   Transaction: 0x3957366ad77b7f9867bcb65cf63883ce1e7592bffaadf88a9831f09a898f932a
T+66530ms:   Gas usage: 45170
T+66530ms:   Block Number: 60
T+66530ms:   Block Time: Sat Feb 17 2018 12:03:39 GMT+0100 (CET)
T+66532ms: eth_getTransactionReceipt
T+66535ms: net_version
T+66538ms: eth_sendTransaction
T+66576ms:   Transaction: 0xe3b2d3365179bcd9edc1236aa097ff7a54817a67475105bd9c0141d11f1c3a78
T+66576ms:   Gas usage: 93576
T+66576ms:   Block Number: 61
T+66576ms:   Block Time: Sat Feb 17 2018 12:03:39 GMT+0100 (CET)
T+66578ms: eth_getTransactionReceipt
T+66582ms: net_version
T+66584ms: eth_call
T+66595ms: net_version
T+66598ms: eth_call
T+66607ms: net_version
T+66609ms: eth_call
T+66617ms: eth_blockNumber
T+66619ms: net_version
T+66622ms: eth_call
T+66633ms: net_version
T+66636ms: eth_call
T+66644ms: net_version
T+66647ms: eth_sendTransaction
T+66660ms:   Transaction: 0x465ff83205adb61192d49c33990507a48e261a5fe6c80c9aafed33500caf055a
T+66660ms:   Contract created: 0x74e3fc764c2474f25369b9d021b7f92e8441a2dc
T+66660ms:   Gas usage: 658905
T+66660ms:   Block Number: 62
T+66660ms:   Block Time: Sat Feb 17 2018 12:03:39 GMT+0100 (CET)
T+66662ms: eth_newBlockFilter
T+66664ms: eth_getFilterChanges
T+66669ms: eth_getTransactionReceipt
T+66672ms: eth_getCode
T+66675ms: eth_uninstallFilter
T+66675ms: net_version
T+66678ms: eth_sendTransaction
T+66695ms:   Transaction: 0x81cb81bd803e4aee1dd9bafc266daae13221905c077f805a734558ba35746749
T+66695ms:   Contract created: 0x98d9f9e8debd4a632682ba207670d2a5acd3c489
T+66695ms:   Gas usage: 2044814
T+66695ms:   Block Number: 63
T+66695ms:   Block Time: Sat Feb 17 2018 12:03:39 GMT+0100 (CET)
T+66697ms: eth_newBlockFilter
T+66699ms: eth_getFilterChanges
T+66704ms: eth_getTransactionReceipt
T+66707ms: eth_getCode
T+66711ms: eth_uninstallFilter
T+66711ms: net_version
T+66713ms: eth_sendTransaction
T+66730ms:   Transaction: 0x44591cd45652075865a74c50d1a245674bc1dd16c2282e8f18cc2a1bd13d93fb
T+66730ms:   Gas usage: 121960
T+66730ms:   Block Number: 64
T+66730ms:   Block Time: Sat Feb 17 2018 12:03:39 GMT+0100 (CET)
T+66732ms: eth_getTransactionReceipt
T+66735ms: net_version
T+66738ms: eth_sendTransaction
T+66750ms:   Transaction: 0xb682daac64438658d31eb5c53162550f2285e269814beaabff2856280ea7fab9
T+66750ms:   Gas usage: 45170
T+66750ms:   Block Number: 65
T+66750ms:   Block Time: Sat Feb 17 2018 12:03:39 GMT+0100 (CET)
T+66752ms: eth_getTransactionReceipt
T+66756ms: net_version
T+66758ms: eth_sendTransaction
T+66791ms:   Transaction: 0x2f19dadb507cb4e479bcf9a055adce9330d2031ecdf0a6e98dd5b7c3be2cd17a
T+66791ms:   Gas usage: 93576
T+66791ms:   Block Number: 66
T+66791ms:   Block Time: Sat Feb 17 2018 12:03:39 GMT+0100 (CET)
T+66793ms: eth_getTransactionReceipt
T+66858ms: evm_increaseTime
T+66864ms: net_version
T+66867ms: eth_sendTransaction
T+66917ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+66917ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_W
T+66917ms: 
T+66917ms: TypeError: Cannot read property 'get' of undefined
T+66917ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+66917ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+66917ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+66917ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+66917ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+66917ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+66917ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+66917ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+66917ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+66917ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by AdrianClv** [comment]
Duplicate https://github.com/trufflesuite/ganache/issues/328
