### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by blackwatertepes** [trufflesuite/ganache#339]
PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+15555438ms: eth_getTransactionReceipt
T+15555440ms: eth_blockNumber
T+15555442ms: eth_sendTransaction
T+15555524ms:   Transaction: 0x5b10f6a10b1670085afe5ad6e657970640e4674598fefbf1ffe2ef6d68157ff4
T+15555524ms:   Gas usage: 68452
T+15555524ms:   Block Number: 456
T+15555524ms:   Block Time: Sun Feb 11 2018 18:00:35 GMT-0800 (PST)
T+15555566ms: eth_getTransactionReceipt
T+15555570ms: eth_blockNumber
T+15555572ms: eth_blockNumber
T+15555575ms: eth_blockNumber
T+15555577ms: eth_blockNumber
T+15555579ms: eth_call
T+15555581ms: eth_blockNumber
T+15555583ms: eth_sendTransaction
T+15555585ms: eth_blockNumber
T+15555588ms: eth_getLogs
T+15555591ms: eth_blockNumber
T+15555595ms:   Transaction: 0x37289b85575cdfabd70ea279a183ed5febd83915b5d44ff54598a891203d2cb0
T+15555595ms:   Gas usage: 23665
T+15555595ms:   Block Number: 457
T+15555597ms:   Block Time: Sun Feb 11 2018 18:00:35 GMT-0800 (PST)
T+15555597ms:   Runtime Error: revert
T+15575369ms: eth_accounts
T+15575392ms: eth_accounts
T+15577199ms: eth_accounts
T+15577211ms: eth_sendTransaction
T+15577237ms:   Transaction: 0x4dfc2c7c1bc675819b670bb3e7b6d7d40a361fef4497b0a5b183fb5aad465a14
T+15577237ms:   Contract created: 0x82353f271d7e240027344c57cf68aa50041e5e7e
T+15577237ms:   Gas usage: 269607
T+15577237ms:   Block Number: 458
T+15577237ms:   Block Time: Sun Feb 11 2018 18:00:57 GMT-0800 (PST)
T+15577239ms: eth_newBlockFilter
T+15577244ms: eth_getFilterChanges
T+15577251ms: eth_getTransactionReceipt
T+15577256ms: eth_getCode
T+15577261ms: eth_uninstallFilter
T+15577263ms: eth_sendTransaction
T+15577309ms:   Transaction: 0x1590905f35d761c4c12e91cec46a3dd80aeeac8564be20297c31a1b5cc520239
T+15577309ms:   Contract created: 0xe5fcb7960adc9f0bcd88daa3c699e01836fcd24f
T+15577309ms:   Gas usage: 2988153
T+15577309ms:   Block Number: 459
T+15577309ms:   Block Time: Sun Feb 11 2018 18:00:57 GMT-0800 (PST)
T+15577312ms: eth_newBlockFilter
T+15577314ms: eth_getFilterChanges
T+15577321ms: eth_getTransactionReceipt
T+15577328ms: eth_getCode
T+15577336ms: eth_uninstallFilter
T+15577338ms: eth_sendTransaction
T+15577355ms:   Transaction: 0xab45bfbb74a4cb7e033e4b2396da2647de3ef720758267e8a1c242aa7aacd173
T+15577355ms:   Gas usage: 41981
T+15577355ms:   Block Number: 460
T+15577355ms:   Block Time: Sun Feb 11 2018 18:00:57 GMT-0800 (PST)
T+15577357ms: eth_getTransactionReceipt
T+15577379ms: evm_snapshot
T+15577403ms: eth_sendTransaction
T+15577445ms:   Transaction: 0xef0b222ccc723575b8004508cf63f4071b8914ddb7f98b556d341938a38451b0
T+15577445ms:   Contract created: 0xb3c29740ef5eb52717afe637fb1ba23c0bf556d7
T+15577445ms:   Gas usage: 2988153
T+15577445ms:   Block Number: 461
T+15577445ms:   Block Time: Sun Feb 11 2018 18:00:57 GMT-0800 (PST)
T+15577447ms: eth_newBlockFilter
T+15577450ms: eth_getFilterChanges
T+15577458ms: eth_getTransactionReceipt
T+15577467ms: eth_getCode
T+15577472ms: eth_uninstallFilter
T+15577475ms: eth_sendTransaction
T+15577501ms:   Transaction: 0xb2a9d9bd93ccecf8fb476621c222119e27f3bc9beeefbc0569cd334d92a81f0f
T+15577501ms:   Gas usage: 45615
T+15577501ms:   Block Number: 462
T+15577501ms:   Block Time: Sun Feb 11 2018 18:00:57 GMT-0800 (PST)
T+15577503ms: eth_getTransactionReceipt
T+15577512ms: eth_blockNumber
T+15577533ms: eth_blockNumber
T+15577537ms: eth_call
T+15577619ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+15577619ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+15577619ms: 
T+15577619ms: TypeError: Cannot read property 'get' of undefined
T+15577619ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+15577619ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+15577619ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+15577619ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+15577619ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+15577619ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+15577619ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+15577619ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+15577619ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+15577619ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by benjamincburns** [comment]
Thanks for reporting this! This is fixed as of trufflesuite/ganache-core#417.

This fix is in 1.1.0-beta.0, but that version has a known issue where it produces an empty response when transactions are rejected prior to running (aka prior to entering the transaction pool). The next beta will be out in the next 24-48h, and it has fixed this problem, so I'd hold off until then.
