### ISSUE TITLE
System Error when running Ganache 2.5.4 on win32

### ISSUE THREAD

**Issue by santiagoziel** [trufflesuite/ganache#3415]
Working with the ethers.js library from a Vs Code terminal that i launched from a WSL ubuntu shell on my windows Laptop.

When trying to conect to the blockchain I got a "Network not found" error, so I followed the steps marked in a comment by u/[mattjaf](https://github.com/mattjaf) [here](https://github.com/smartcontractkit/full-blockchain-solidity-course-js/discussions/286).

After that i got it working fine, deployed a contract and tested some transactions.

I turned off my laptop and today when tring to keep working I started Ganache and after selecting the Quikstrt option i keep getting :
![image](https://user-images.githubusercontent.com/45303560/180573848-5e28ec16-7707-49d2-b557-62f6deb6b79a.png)

Relaunching the application does not help and neither does deleting and re instaling it.

PLATFORM: win32
GANACHE VERSION: 2.5.4

EXCEPTION:
```
Error: EPERM: operation not permitted, rename 'C:\Users\santi\AppData\Roaming\Ganache\default\Settings.3302481753' -> 'C:\Users\santi\AppData\Roaming\Ganache\default\Settings'
    at Object.renameSync (fs.js:643:3)
    at writeFileSync (C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\app.asar\node_modules\write-file-atomic\index.js:124:8)
    at Proxy.setItem (C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\app.asar\node_modules\node-localstorage\LocalStorage.js:217:7)
    at JsonStorage_JsonStorage.setToStorage (C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\json\JsonStorage.js:48:18)
    at JsonStorage_JsonStorage.setAll (C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\json\JsonStorage.js:58:10)
    at WorkspaceSettings_WorkspaceSettings.setAll (C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\settings\Settings.js:55:19)
    at WorkspaceSettings_WorkspaceSettings.bootstrap (C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\settings\Settings.js:87:10)
    at Workspace_Workspace.bootstrap (C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\workspaces\Workspace.js:78:19)
    at WorkspaceManager_WorkspaceManager.bootstrap (C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\types\workspaces\WorkspaceManager.js:78:26)
    at C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\app.asar\webpack:\src\main\index.js:236:22
```

**Comment by santiagoziel** [comment]
Uninstalling and deleting the folder:
C:\Users\santi\AppData\Roaming\Ganache

Got me working back to normal , Im not going to cose the issue just yet as I would like to get a bit of feedback on to maybe why this happended and how to prevent it.
