### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by MoMannn** [trufflesuite/ganache#347]
PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+16122ms: eth_call
T+16132ms: eth_blockNumber
T+16135ms: eth_sendTransaction
T+16152ms:   Transaction: 0x2daa01cdc9e42c31143ede09f556dad06f69767b039e1c431912a97f013483c7
T+16152ms:   Gas usage: 24678
T+16152ms:   Block Number: 11
T+16152ms:   Block Time: Fri Feb 16 2018 19:36:16 GMT+0100 (CET)
T+16152ms:   Runtime Error: revert
T+16155ms: eth_call
T+16167ms: eth_blockNumber
T+16170ms: eth_sendTransaction
T+16184ms:   Transaction: 0xee3f08aa5ee3b5b74d5ace9ec3ac1e18f9925927c4f66255a24723483427cfe9
T+16184ms:   Gas usage: 24634
T+16184ms:   Block Number: 12
T+16187ms:   Block Time: Fri Feb 16 2018 19:36:16 GMT+0100 (CET)
T+16187ms:   Runtime Error: revert
T+16189ms: eth_call
T+16196ms: eth_blockNumber
T+16199ms: eth_sendTransaction
T+16241ms:   Transaction: 0x6fc7f5ad2a08a7cfb5201c4c2f35df901edee9a2295dd8e47d04eb886aefd059
T+16241ms:   Gas usage: 123068
T+16241ms:   Block Number: 13
T+16241ms:   Block Time: Fri Feb 16 2018 19:36:16 GMT+0100 (CET)
T+16244ms: eth_call
T+16254ms: eth_blockNumber
T+16258ms: eth_sendTransaction
T+16427ms:   Transaction: 0x24eb05a567156f83ed859988a98264a83120074ee66b38358d79e2dcd49aa24a
T+16427ms:   Gas usage: 71490
T+16427ms:   Block Number: 14
T+16427ms:   Block Time: Fri Feb 16 2018 19:36:16 GMT+0100 (CET)
T+16427ms:   Runtime Error: revert
T+16429ms: eth_call
T+16439ms: eth_blockNumber
T+16442ms: eth_call
T+16456ms: eth_blockNumber
T+16459ms: eth_call
T+16469ms: eth_blockNumber
T+16472ms: eth_call
T+16491ms: eth_blockNumber
T+16494ms: eth_call
T+16504ms: eth_blockNumber
T+16507ms: eth_sendTransaction
T+16530ms:   Transaction: 0x2a0380c77ec8ae45c0be3200385e15b89baddce20fc7d29b5c6bc2b1d93342a2
T+16530ms:   Gas usage: 48687
T+16530ms:   Block Number: 15
T+16530ms:   Block Time: Fri Feb 16 2018 19:36:16 GMT+0100 (CET)
T+16533ms: eth_call
T+16549ms: eth_blockNumber
T+16552ms: eth_sendTransaction
T+16573ms:   Transaction: 0x678db33ecf01d1acc1eacb705b98be76e09ca144684ff4190eab748832cd20a3
T+16573ms:   Gas usage: 17381
T+16573ms:   Block Number: 16
T+16573ms:   Block Time: Fri Feb 16 2018 19:36:16 GMT+0100 (CET)
T+16575ms: eth_call
T+16584ms: eth_blockNumber
T+16587ms: eth_call
T+16597ms: eth_blockNumber
T+16602ms: eth_sendTransaction
T+16621ms:   Transaction: 0xacbdcafb2392e484c880a4f9878b55783e33d1131094e663fc7024c17fb68d10
T+16621ms:   Gas usage: 48687
T+16621ms:   Block Number: 17
T+16621ms:   Block Time: Fri Feb 16 2018 19:36:16 GMT+0100 (CET)
T+16623ms: eth_sendTransaction
T+16705ms:   Transaction: 0x21073c3574dc8603ebb60460e5d75baa2c808c2bd094f9a870984ccaf83acb4b
T+16705ms:   Gas usage: 90798
T+16705ms:   Block Number: 18
T+16705ms:   Block Time: Fri Feb 16 2018 19:36:16 GMT+0100 (CET)
T+16707ms: eth_call
T+16717ms: eth_call
T+16728ms: eth_call
T+16739ms: eth_blockNumber
T+16742ms: eth_sendTransaction
T+16764ms:   Transaction: 0x878559c433779d56af5eec1d1ff23b61cab55b5d9e1079e0d07951f79cb73c9c
T+16764ms:   Gas usage: 24668
T+16764ms:   Block Number: 19
T+16764ms:   Block Time: Fri Feb 16 2018 19:36:16 GMT+0100 (CET)
T+16764ms:   Runtime Error: revert
T+16766ms: eth_call
T+16780ms: eth_call
T+16788ms: eth_call
T+16812ms: eth_blockNumber
T+16815ms: eth_sendTransaction
T+16839ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+16839ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+16839ms: 
T+16839ms: TypeError: Cannot read property 'get' of undefined
T+16839ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+16839ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+16839ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+16839ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+16839ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+16839ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+16839ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+16839ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+16839ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+16839ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by benjamincburns** [comment]
Hi @MoMannn,

Thanks for reporting this. This is trufflesuite/ganache-cli#417, and it has been fixed in the current beta. There are some other known bugs in that beta however, so I'm in the middle of publishing a new beta version now.
