### ISSUE TITLE
System Error when running Ganache 1.0.2 on linux

### ISSUE THREAD

**Issue by sabinebertram** [trufflesuite/ganache#352]
PLATFORM: linux
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+1060083ms: eth_call
T+1060096ms: eth_accounts
T+1060102ms: eth_sendTransaction
T+1060162ms:   Transaction: 0xaa70931c631152ae2bda4d5af14e7afb0a00345d3f47c3e68e2294c0ff01d6f0
T+1060162ms:   Gas usage: 96803
T+1060162ms:   Block Number: 378
T+1060162ms:   Block Time: Wed Feb 21 2018 17:23:46 GMT+0100 (CET)
T+1060168ms: eth_call
T+1060188ms: eth_accounts
T+1060197ms: eth_sendTransaction
T+1060239ms:   Transaction: 0x05d2229f38762c43901f71bf14cbe28020ac275f71b00db1542beba7e3a4d797
T+1060239ms:   Gas usage: 96803
T+1060239ms:   Block Number: 379
T+1060239ms:   Block Time: Wed Feb 21 2018 17:23:46 GMT+0100 (CET)
T+1060242ms: eth_call
T+1060268ms: eth_accounts
T+1060273ms: eth_sendTransaction
T+1060311ms:   Transaction: 0xebbe8ce3a0a4e70c0170706f62b9c8172d84dea1a9ce9ca1ef45ba4e65f6485f
T+1060311ms:   Gas usage: 96803
T+1060311ms:   Block Number: 380
T+1060311ms:   Block Time: Wed Feb 21 2018 17:23:46 GMT+0100 (CET)
T+1060315ms: eth_call
T+1060333ms: eth_accounts
T+1060339ms: eth_sendTransaction
T+1060410ms:   Transaction: 0x16febc5eb325628820380c1f9b155ebd3e9602b83689ab791510926297d7827d
T+1060410ms:   Gas usage: 96803
T+1060410ms:   Block Number: 381
T+1060410ms:   Block Time: Wed Feb 21 2018 17:23:46 GMT+0100 (CET)
T+1060415ms: eth_call
T+1060436ms: eth_accounts
T+1060441ms: eth_sendTransaction
T+1060547ms:   Transaction: 0x2f46d4bfd72dcf0b09caac2e15ed906238f13b295ee5dd3ba7b62dd48fa04ad2
T+1060547ms:   Gas usage: 96803
T+1060547ms:   Block Number: 382
T+1060547ms:   Block Time: Wed Feb 21 2018 17:23:46 GMT+0100 (CET)
T+1060550ms: eth_call
T+1060564ms: eth_accounts
T+1060572ms: eth_sendTransaction
T+1060605ms:   Transaction: 0xf7236eaa9f02196c5065bddc02e16afbe54d0ad8f7aacd2b35dd8ab57276526d
T+1060605ms:   Gas usage: 96803
T+1060605ms:   Block Number: 383
T+1060605ms:   Block Time: Wed Feb 21 2018 17:23:46 GMT+0100 (CET)
T+1060609ms: eth_call
T+1060632ms: eth_accounts
T+1060641ms: eth_sendTransaction
T+1060679ms:   Transaction: 0x7e7eb9433e8c4df39cf17e4e99c43448cd84ab3bca5e69fcc0d41e59b27715a9
T+1060679ms:   Gas usage: 96739
T+1060679ms:   Block Number: 384
T+1060679ms:   Block Time: Wed Feb 21 2018 17:23:46 GMT+0100 (CET)
T+1060684ms: eth_call
T+1060705ms: eth_accounts
T+1060713ms: eth_sendTransaction
T+1060762ms:   Transaction: 0x7978b34521235232d6ef3daac045b40b9fe9ddcaf157dcb8aafa9145eae9918c
T+1060762ms:   Gas usage: 96803
T+1060762ms:   Block Number: 385
T+1060762ms:   Block Time: Wed Feb 21 2018 17:23:46 GMT+0100 (CET)
T+1060770ms: eth_call
T+1060783ms: eth_accounts
T+1060790ms: eth_sendTransaction
T+1060834ms:   Transaction: 0xf996e1672544444d081090175144a11d98115b50654cbfe451e94dbe6f61d78c
T+1060834ms:   Gas usage: 96803
T+1060840ms:   Block Number: 386
T+1060844ms:   Block Time: Wed Feb 21 2018 17:23:46 GMT+0100 (CET)
T+1060851ms: eth_call
T+1060870ms: eth_accounts
T+1060876ms: eth_sendTransaction
T+1060919ms:   Transaction: 0x2ec6a6ba24a27cb85369bace8e40cec18705ab18120d0bc92faec4e71cb229c3
T+1060919ms:   Gas usage: 96803
T+1060919ms:   Block Number: 387
T+1060919ms:   Block Time: Wed Feb 21 2018 17:23:46 GMT+0100 (CET)
T+1060922ms: eth_call
T+1060943ms: eth_accounts
T+1060952ms: eth_sendTransaction
T+1061017ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+1061017ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_W
T+1061017ms: 
T+1061017ms: TypeError: Cannot read property 'get' of undefined
T+1061017ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+1061017ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+1061017ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+1061017ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+1061017ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+1061017ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+1061017ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+1061017ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+1061017ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+1061017ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by benjamincburns** [comment]
Hi @sabinebertram, thanks for reporting. This is fixed in the current beta, available on our releases page.
