### ISSUE TITLE
System Error when running Ganache 1.0.2 on linux

### ISSUE THREAD

**Issue by jenarvaezg** [trufflesuite/ganache#356]
PLATFORM: linux
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+2332317ms:   Block Number: 89
T+2332333ms:   Block Time: Fri Feb 23 2018 08:47:52 GMT+0100 (CET)
T+2332339ms: eth_getTransactionReceipt
T+2332346ms: eth_sendTransaction
T+2332476ms:   Transaction: 0xb43afe06e11d354edd0ab77e4d3d228949c49e0a7a12c6b08ef96f801f4cc8c7
T+2332476ms:   Gas usage: 22201
T+2332476ms:   Block Number: 90
T+2332476ms:   Block Time: Fri Feb 23 2018 08:47:52 GMT+0100 (CET)
T+2332476ms:   Runtime Error: revert
T+2332484ms: eth_call
T+2332498ms: eth_blockNumber
T+2332612ms: eth_sendTransaction
T+2332618ms:   Transaction: 0x52e1073fd0a0d081b3055f2dcab83fdd0ad55442f8ee222e8f39b9e485813472
T+2332618ms:   Gas usage: 22201
T+2332618ms:   Block Number: 91
T+2332618ms:   Block Time: Fri Feb 23 2018 08:47:52 GMT+0100 (CET)
T+2332618ms:   Runtime Error: revert
T+2332621ms: eth_call
T+2332640ms: eth_blockNumber
T+2332653ms: eth_sendTransaction
T+2332700ms:   Transaction: 0xb76ac36ea1214fa30ac3c780177db9e2a3b365c0e5c8786d89aaea48c943c282
T+2332720ms:   Gas usage: 22201
T+2332725ms:   Block Number: 92
T+2332725ms:   Block Time: Fri Feb 23 2018 08:47:53 GMT+0100 (CET)
T+2332733ms:   Runtime Error: revert
T+2332742ms: eth_call
T+2344791ms: eth_accounts
T+2344819ms: eth_accounts
T+2344834ms: eth_sendTransaction
T+2344891ms:   Transaction: 0xec1700eececdaa1adc481c60ea3727c520695de83f5b0eacb6a863b7139e14e7
T+2344901ms:   Contract created: 0x23e84570f7b28ad0d5e5545d398009194a8734f3
T+2344909ms:   Gas usage: 269543
T+2344909ms:   Block Number: 93
T+2344909ms:   Block Time: Fri Feb 23 2018 08:48:05 GMT+0100 (CET)
T+2344919ms: eth_newBlockFilter
T+2344923ms: eth_getFilterChanges
T+2344933ms: eth_getTransactionReceipt
T+2345003ms: eth_getCode
T+2345007ms: eth_uninstallFilter
T+2345010ms: eth_sendTransaction
T+2345026ms:   Transaction: 0xdb4ff927ee3f17d68888423da5087d8366a5a1a879c47753237fa2441270c013
T+2345026ms:   Gas usage: 41981
T+2345026ms:   Block Number: 94
T+2345032ms:   Block Time: Fri Feb 23 2018 08:48:05 GMT+0100 (CET)
T+2345036ms: eth_getTransactionReceipt
T+2345085ms: eth_accounts
T+2345091ms: eth_sendTransaction
T+2345127ms:   Transaction: 0x867a1bca7e51779e9e62baf897e36a18310b4e64e5655e77b23fce38c3a8771e
T+2345127ms:   Contract created: 0x8cd918cee8f93989e334bc0107bb33a9586d05c0
T+2345132ms:   Gas usage: 675480
T+2345132ms:   Block Number: 95
T+2345132ms:   Block Time: Fri Feb 23 2018 08:48:05 GMT+0100 (CET)
T+2345140ms: eth_newBlockFilter
T+2345151ms: eth_getFilterChanges
T+2345158ms: eth_getTransactionReceipt
T+2345163ms: eth_getCode
T+2345172ms: eth_uninstallFilter
T+2345176ms: eth_sendTransaction
T+2345215ms:   Transaction: 0xcb57c24cbe1647824cd890a9a569316b83a0f7b01f0c52ebd77c3dfff4159d63
T+2345215ms:   Gas usage: 26981
T+2345215ms:   Block Number: 96
T+2345215ms:   Block Time: Fri Feb 23 2018 08:48:05 GMT+0100 (CET)
T+2345219ms: eth_getTransactionReceipt
T+2345256ms: evm_snapshot
T+2345267ms: eth_blockNumber
T+2345282ms: eth_sendTransaction
T+2345369ms:   Transaction: 0x5db69035acc81a6839c2f668106c78a65f5f0f7925eda7fb8d90e1c4b11d5cae
T+2345369ms:   Gas usage: 54548
T+2345369ms:   Block Number: 97
T+2345369ms:   Block Time: Fri Feb 23 2018 08:48:05 GMT+0100 (CET)
T+2345376ms: eth_getTransactionReceipt
T+2345389ms: eth_call
T+2345476ms: eth_blockNumber
T+2345488ms: eth_sendTransaction
T+2345545ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+2345545ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_W
T+2345545ms: 
T+2345545ms: TypeError: Cannot read property 'get' of undefined
T+2345545ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+2345545ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+2345545ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+2345545ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+2345545ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+2345545ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+2345545ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+2345545ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+2345545ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+2345545ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by benjamincburns** [comment]
Hi @jenarvaezg, thanks for reporting this. Unfortunately this report duplicates trufflesuite/ganache-cli#417. Fortunately, this issue is already fixed in the current beta! Please check out our releases page for more info.
