### ISSUE TITLE
System Error when running Ganache 1.0.2 on linux

### ISSUE THREAD

**Issue by bernatcanal** [trufflesuite/ganache#357]
PLATFORM: linux
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+100905ms:   Block Time: Fri Feb 23 2018 22:12:07 GMT+0100 (CET)
T+100907ms: eth_getTransactionReceipt
T+100915ms: eth_accounts
T+100923ms: eth_sendTransaction
T+100948ms:   Transaction: 0xedf05224276be59e924653e48ba1f51773755f7e2d359f876a74e1b85e1a4497
T+100948ms:   Contract created: 0xeec918d74c746167564401103096d45bbd494b74
T+100948ms:   Gas usage: 1869515
T+100948ms:   Block Number: 15
T+100951ms:   Block Time: Fri Feb 23 2018 22:12:08 GMT+0100 (CET)
T+100953ms: eth_newBlockFilter
T+100954ms: eth_getFilterChanges
T+100958ms: eth_getTransactionReceipt
T+100963ms: eth_getCode
T+100969ms: eth_uninstallFilter
T+100969ms: eth_sendTransaction
T+101006ms:   Transaction: 0x7481b74f273c73b55d9bd16286d7ea81f72589feb840275a0731ca03f1e7f7b9
T+101006ms:   Gas usage: 26981
T+101006ms:   Block Number: 16
T+101006ms:   Block Time: Fri Feb 23 2018 22:12:08 GMT+0100 (CET)
T+101010ms: eth_getTransactionReceipt
T+101041ms: eth_call
T+101041ms: eth_call
T+139272ms: net_version
T+139281ms: eth_accounts
T+139298ms: eth_accounts
T+139348ms: eth_accounts
T+139358ms: eth_sendTransaction
T+139381ms:   Transaction: 0x9633aba535391c8768c300e1d9c9b80aa652f5c98a7d6431f10a272452507853
T+139381ms:   Contract created: 0xecfcab0a285d3380e488a39b4bb21e777f8a4eac
T+139381ms:   Gas usage: 269607
T+139381ms:   Block Number: 17
T+139384ms:   Block Time: Fri Feb 23 2018 22:12:46 GMT+0100 (CET)
T+139386ms: eth_newBlockFilter
T+139389ms: eth_getFilterChanges
T+139394ms: eth_getTransactionReceipt
T+139398ms: eth_getCode
T+139407ms: eth_uninstallFilter
T+139410ms: eth_sendTransaction
T+139432ms:   Transaction: 0x64df98e7d3f1cf5dc7eaa5264011714bf49802d9fda56003e202434903c2581b
T+139432ms:   Gas usage: 41981
T+139432ms:   Block Number: 18
T+139432ms:   Block Time: Fri Feb 23 2018 22:12:46 GMT+0100 (CET)
T+139435ms: eth_getTransactionReceipt
T+139442ms: eth_accounts
T+139451ms: eth_sendTransaction
T+139474ms:   Transaction: 0x086921cd31a96643633c7bf42172ac30610489a0fa687e6bcbf8b9775860d0af
T+139474ms:   Contract created: 0x4e72770760c011647d4873f60a3cf6cdea896cd8
T+139474ms:   Gas usage: 1869515
T+139474ms:   Block Number: 19
T+139474ms:   Block Time: Fri Feb 23 2018 22:12:46 GMT+0100 (CET)
T+139476ms: eth_newBlockFilter
T+139479ms: eth_getFilterChanges
T+139484ms: eth_getTransactionReceipt
T+139490ms: eth_getCode
T+139496ms: eth_uninstallFilter
T+139496ms: eth_sendTransaction
T+139518ms:   Transaction: 0x2613896914f5d1eeaed6be42e3e0466d891206e27c197a7bac0078225f4d693a
T+139518ms:   Gas usage: 26981
T+139518ms:   Block Number: 20
T+139518ms:   Block Time: Fri Feb 23 2018 22:12:46 GMT+0100 (CET)
T+139520ms: eth_getTransactionReceipt
T+139542ms: eth_call
T+140549ms: eth_call
T+203646ms: net_version
T+203652ms: eth_accounts
T+203669ms: eth_accounts
T+203718ms: eth_accounts
T+203727ms: eth_sendTransaction
T+203769ms:   Transaction: 0x6ef0d25d9fb67b0f09c78583380f4bad73ad1de89d34ccb4eb44a7def3fc33b6
T+203769ms:   Contract created: 0x13274fe19c0178208bcbee397af8167a7be27f6f
T+203769ms:   Gas usage: 269607
T+203769ms:   Block Number: 21
T+203769ms:   Block Time: Fri Feb 23 2018 22:13:50 GMT+0100 (CET)
T+203771ms: eth_newBlockFilter
T+203775ms: eth_getFilterChanges
T+203785ms: eth_getTransactionReceipt
T+203791ms: eth_getCode
T+203813ms: eth_uninstallFilter
T+203816ms: eth_sendTransaction
T+203836ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+203836ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_W
T+203836ms: 
T+203836ms: TypeError: Cannot read property 'get' of undefined
T+203836ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+203836ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+203836ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+203836ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+203836ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+203836ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+203836ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+203836ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+203836ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+203836ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by benjamincburns** [comment]
Hi @bernatcanal , thanks for reporting this. Unfortunately this report duplicates trufflesuite/ganache-cli#417. Fortunately, this issue is already fixed in the current beta! Please check out our [releases](https://github.com/trufflesuite/ganache/releases) page for more info.
