### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by LK** [trufflesuite/ganache#358]
Ran into this error while running `truffle test`. I have my `beforeEach` hook set up to create the necessary contracts, and while the first test passed the second errored in the hook with "The contract code couldn't be stored, please check your gas amount." At this point Ganache crashed with the following error.

PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+148635ms: eth_sendTransaction
T+148651ms:   Transaction: 0xe6560bcefdb934ca3bc97d2ec63e67edbf58ed716c63aea62ba23ec38c68e03a
T+148651ms:   Contract created: 0x8acee021a27779d8e98b9650722676b850b25e11
T+148651ms:   Gas usage: 269607
T+148651ms:   Block Number: 34
T+148651ms:   Block Time: Fri Feb 23 2018 20:56:03 GMT-0500 (EST)
T+148654ms: eth_newBlockFilter
T+148656ms: eth_getFilterChanges
T+148664ms: eth_getTransactionReceipt
T+148672ms: eth_getCode
T+148681ms: eth_uninstallFilter
T+148681ms: eth_sendTransaction
T+148701ms:   Transaction: 0x5ef83bc84690e0a14a30bb02f358bc1ff44f19ab487996f7323f063e95e417f4
T+148701ms:   Gas usage: 41981
T+148701ms:   Block Number: 35
T+148701ms:   Block Time: Fri Feb 23 2018 20:56:03 GMT-0500 (EST)
T+148704ms: eth_getTransactionReceipt
T+148711ms: eth_accounts
T+148736ms: eth_sendTransaction
T+148781ms:   Transaction: 0x4ecf0bd78c8a5ed6885c2e4ba85e057d96e28c78a0b4c3e07a4235bb89573c76
T+148781ms:   Gas usage: 26981
T+148781ms:   Block Number: 36
T+148781ms:   Block Time: Fri Feb 23 2018 20:56:03 GMT-0500 (EST)
T+148784ms: eth_getTransactionReceipt
T+148808ms: evm_snapshot
T+148920ms: eth_blockNumber
T+148923ms: net_version
T+148927ms: eth_sendTransaction
T+148948ms:   Transaction: 0xd2f224b8cdcc39c2d9de5d0fdd36488030b6d8229b594f7b89252511588abf74
T+148948ms:   Contract created: 0x4e71920b7330515faf5ea0c690f1ad06a85fb60c
T+148948ms:   Gas usage: 344336
T+148948ms:   Block Number: 37
T+148948ms:   Block Time: Fri Feb 23 2018 20:56:04 GMT-0500 (EST)
T+148951ms: eth_newBlockFilter
T+148953ms: eth_getFilterChanges
T+148958ms: eth_getTransactionReceipt
T+148962ms: eth_getCode
T+148966ms: eth_uninstallFilter
T+148966ms: net_version
T+148969ms: eth_sendTransaction
T+149013ms:   Transaction: 0x2469a4953b6d6428b82b96ac5c031d80d2c444b86b8b213430ebb792c5a89fe5
T+149013ms:   Contract created: 0xb9b7e0cb2edf5ea031c8b297a5a1fa20379b6a0a
T+149013ms:   Gas usage: 1390906
T+149013ms:   Block Number: 38
T+149013ms:   Block Time: Fri Feb 23 2018 20:56:04 GMT-0500 (EST)
T+149015ms: eth_newBlockFilter
T+149018ms: eth_getFilterChanges
T+149024ms: eth_getTransactionReceipt
T+149028ms: eth_getCode
T+149032ms: eth_uninstallFilter
T+149032ms: net_version
T+149038ms: eth_sendTransaction
T+149052ms:   Transaction: 0xedef90058721531e5d7b9a26fd420f63cff0306d782a01a675a856fe94f39746
T+149052ms:   Gas usage: 28205
T+149052ms:   Block Number: 39
T+149052ms:   Block Time: Fri Feb 23 2018 20:56:04 GMT-0500 (EST)
T+149055ms: eth_getTransactionReceipt
T+149058ms: net_version
T+149063ms: eth_sendTransaction
T+149128ms:   Transaction: 0x59ac875143132aad138d69437407878c18448623c62db8059d4c359167ffbbf3
T+149128ms:   Gas usage: 103882
T+149128ms:   Block Number: 40
T+149128ms:   Block Time: Fri Feb 23 2018 20:56:04 GMT-0500 (EST)
T+149131ms: eth_getTransactionReceipt
T+149140ms: net_version
T+149143ms: eth_call
T+149155ms: net_version
T+149157ms: eth_call
T+149175ms: net_version
T+149177ms: eth_sendTransaction
T+149239ms:   Transaction: 0xd0de60bbec1f961b9cbc3a87e80c8dda8d40cb86bf0a77affaf03c9e1c98e591
T+149239ms:   Gas usage: 88882
T+149239ms:   Block Number: 41
T+149239ms:   Block Time: Fri Feb 23 2018 20:56:04 GMT-0500 (EST)
T+149243ms: eth_getTransactionReceipt
T+149246ms: net_version
T+149250ms: eth_call
T+149294ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+149294ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+149294ms: 
T+149294ms: TypeError: Cannot read property 'get' of undefined
T+149294ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+149294ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+149294ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+149294ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+149294ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+149294ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+149294ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+149294ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+149294ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+149294ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by benjamincburns** [comment]
Hi @LK, thanks for reporting this. Unfortunately this report duplicates trufflesuite/ganache-cli#417. Fortunately, this issue is already fixed in the current beta! Check out our [releases](https://github.com/trufflesuite/ganache/releases) page for more info.
