### ISSUE TITLE
System Error when running Ganache 2.5.4 on darwin

### ISSUE THREAD

**Issue by cooper09** [trufflesuite/ganache#3605]
PLATFORM: darwin
GANACHE VERSION: 2.5.4

EXCEPTION:
```
Error: Incompatible EIP155-based V 0 and chain id 1. See the second parameter of the Transaction constructor to set the chain id.
    at Transaction._validateV (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/node_modules/ethereumjs-tx/src/transaction.ts:370:13)
    at Transaction.set [as v] (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/node_modules/ethereumjs-tx/src/transaction.ts:387:16)
    at /Applications/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/lib/utils/transaction.js:116:23
    at Array.forEach (<anonymous>)
    at initData (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/lib/utils/transaction.js:110:18)
    at new Transaction (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/lib/utils/transaction.js:168:5)
    at Function.fromJSON (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/lib/utils/transaction.js:228:16)
    at /Applications/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/lib/forking/forked_blockchain.js:384:21
    at Array.forEach (<anonymous>)
    at Object.callback (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/lib/forking/forked_blockchain.js:382:31)
    at sendTxCallback (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/node_modules/web3-core-method/src/index.js:664:29)
    at onJsonrpcResult (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/node_modules/web3-core-requestmanager/src/index.js:179:9)
    at /Applications/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/lib/forking/forked_blockchain.js:136:11
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
![Screen Shot 2022-09-02 at 12 25 57 PM](https://user-images.githubusercontent.com/840749/188197718-b93f34be-c797-49dc-b1c3-d886c2903746.png)


What is this. I'm running Ganache 2.5.4 ...does it need to be updated...how do you update ganache..your doc support leaves something to be desired....

```
![Screen Shot 2022-09-02 at 12 28 55 PM](https://user-images.githubusercontent.com/840749/188198170-d51f8e8a-97b0-430e-9430-fbcd28e947df.png)

**Comment by cooper09** [comment]
![Screen Shot 2022-09-02 at 12 25 57 PM](https://user-images.githubusercontent.com/840749/188198398-e72ecbc0-9008-466b-90b7-dd28328965c1.png)
