### ISSUE TITLE
Handle NotFoundError: Key not found in database

### ISSUE THREAD

**Issue by superlazycoder** [trufflesuite/ganache#362]
PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+190646079ms:   Block Time: Mon Nov 19 2018 00:58:15 GMT-0800 (PST)
T+190646224ms: eth_newBlockFilter
T+190646402ms: eth_getFilterChanges
T+190646532ms: eth_getTransactionReceipt
T+190646659ms: eth_getCode
T+190646788ms: eth_uninstallFilter
T+190646788ms: net_version
T+190646928ms: eth_sendTransaction
T+190647056ms:   Transaction: 0x5cc1be24d796f9fb7ff4e2a507111b826375ed8e5201b2f5247537a9d0243176
T+190647056ms:   Gas usage: 23613
T+190647056ms:   Block Number: 7
T+190647056ms:   Block Time: Mon Nov 19 2018 00:58:15 GMT-0800 (PST)
T+190647056ms:   Runtime Error: revert
T+190647183ms: eth_blockNumber
T+190647183ms: net_version
T+190647183ms: eth_sendTransaction
T+190647310ms:   Transaction: 0x293e46cd9bbddd2f7cfa0bdd376ce8b7a7b3f20edaada62026a3b6faae985249
T+190647310ms:   Contract created: 0xa6b5f711d9654984052b479957c3d4075dea8ca0
T+190647310ms:   Gas usage: 782054
T+190647310ms:   Block Number: 8
T+190647310ms:   Block Time: Mon Nov 19 2018 00:58:15 GMT-0800 (PST)
T+190647500ms: eth_newBlockFilter
T+190647622ms: eth_getFilterChanges
T+190647754ms: eth_getTransactionReceipt
T+190647879ms: eth_getCode
T+190648001ms: eth_sendTransaction
T+190648128ms:   Transaction: 0xcbcf3b7ab304ce96935b8fa3e615d288d6dd400db18e2c022db85d7b839f084f
T+190648128ms:   Gas usage: 21040
T+190648128ms:   Block Number: 9
T+190648128ms:   Block Time: Mon Nov 19 2018 00:58:15 GMT-0800 (PST)
T+190648254ms: eth_uninstallFilter
T+190648254ms: net_version
T+190648378ms: eth_sendTransaction
T+190648502ms:   Transaction: 0x058d70fd6c1ee26bc7f974deb798dd125f06b5d32849d1171252f797a85d9e1c
T+190648502ms:   Gas usage: 21753
T+190648502ms:   Block Number: 10
T+190648502ms:   Block Time: Mon Nov 19 2018 00:58:15 GMT-0800 (PST)
T+190648502ms:   Runtime Error: revert
T+190648502ms: eth_blockNumber
T+190648502ms: net_version
T+190648502ms: eth_sendTransaction
T+190648632ms:   Transaction: 0x6a02f8c7f5067923c6f57e53813d5f168dfa9ea3b1a7476e7e0769f030e55433
T+190648632ms:   Contract created: 0xec2acea4f22bbf9c38c49fff431f25c525b80de0
T+190648632ms:   Gas usage: 782054
T+190648632ms:   Block Number: 11
T+190648632ms:   Block Time: Mon Nov 19 2018 00:58:15 GMT-0800 (PST)
T+190648632ms: eth_newBlockFilter
T+190648766ms: eth_getFilterChanges
T+190648958ms: eth_getTransactionReceipt
T+190649087ms: eth_getCode
T+190649212ms: eth_sendTransaction
T+190649212ms:   Transaction: 0xbbc0c736ef9a97383cb9dc5502549869fc728531645d9fb6260a7cf5cde7e107
T+190649212ms:   Gas usage: 21040
T+190649212ms:   Block Number: 12
T+190649212ms:   Block Time: Mon Nov 19 2018 00:58:15 GMT-0800 (PST)
T+190649336ms: eth_getBalance
T+190649459ms: eth_getBalance
T+190649582ms: eth_uninstallFilter
T+190649582ms: net_version
T+190649706ms: eth_sendTransaction
T+190649833ms:   Transaction: 0x26e478de4b759ed020be1e2c4e4782c0a4e7b9b6371e3f48f837baf2ba52ba11
T+190649833ms:   Gas usage: 72461
T+190649833ms:   Block Number: 13
T+190649833ms:   Block Time: Mon Nov 19 2018 00:58:15 GMT-0800 (PST)
T+190649833ms: eth_getTransactionReceipt
T+190649990ms: eth_getBalance
T+190650151ms: eth_getBalance
T+190650311ms: net_version
T+190650441ms: eth_sendTransaction
T+190650577ms:   Transaction: 0x7d5e2f02e3457cb51f1148ce3fd3338616269b3ad85203a35bdf5dc5f405ddb6
T+190650577ms:   Gas usage: 57461
T+190650577ms:   Block Number: 14
T+190650577ms:   Block Time: Mon Nov 19 2018 00:58:16 GMT-0800 (PST)
T+190650704ms: eth_getTransactionReceipt
T+190650834ms: eth_getBalance
T+190650834ms: eth_getBalance
T+190650961ms: net_version
T+190650961ms: eth_sendTransaction
T+190651087ms:   Transaction: 0x7d5e2f02e3457cb51f1148ce3fd3338616269b3ad85203a35bdf5dc5f405ddb6
T+190651087ms:   Gas usage: 57461
T+190651087ms:   Block Number: 15
T+190651087ms:   Block Time: Mon Nov 19 2018 00:58:16 GMT-0800 (PST)
T+190651087ms: eth_getTransactionReceipt
T+190651216ms: eth_getBalance
T+190651364ms: eth_getBalance
T+190651563ms: net_version
T+190651690ms: eth_call
T+190651817ms: evm_revert
T+190651952ms: 
T+190651952ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+190651952ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+190652079ms: NotFoundError: Key not found in database
T+190652079ms:     at /node_modules/ganache-cli/build/lib.node.js:75532:18
T+190652079ms:     at /node_modules/ganache-cli/build/lib.node.js:75297:19
T+190652079ms:     at /node_modules/ganache-cli/build/lib.node.js:77442:21
T+190652079ms:     at ReadFileContext.callback (/node_modules/ganache-cli/build/lib.node.js:77339:14)
T+190652079ms:     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:336:13)
```

**Comment by seesemichaelj** [comment]
I'm going to close this since it has only been reported in `v1.0.2`. Please upgrade to a newer version (currently `v1.2.1+`). If you still have this issue, open a new issue. Thanks!
