### ISSUE TITLE
System Error when running Ganache 1.0.2 on win32

### ISSUE THREAD

**Issue by cand126** [trufflesuite/ganache#367]
PLATFORM: win32
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+0ms: Starting server with configuration: {"hostname":"127.0.0.1","mnemonic":"candy maple cake sugar pudding cream honey rich smooth crumble sweet treat","network_id":5777,"port":7545,"total_accounts":10,"unlocked_accounts":[]}
T+126ms: Ganache started successfully!
T+126ms: Waiting for requests...
T+64187ms: net_version
T+64194ms: eth_accounts
T+64209ms: eth_accounts
T+65076ms: eth_accounts
T+65085ms: eth_sendTransaction
T+65130ms:   Transaction: 0xd3afceeeeba861d56b6bdf68c5acbf3f7049ece5629e87521091cb3fd189f8ab
T+65130ms:   Contract created: 0x8cdaf0cd259887258bc13a92c0a6da92698644c0
T+65130ms:   Gas usage: 269607
T+65130ms:   Block Number: 1
T+65130ms:   Block Time: Mon Feb 26 2018 22:59:53 GMT+0100 (西歐標準時間)
T+65133ms: eth_newBlockFilter
T+65137ms: eth_getFilterChanges
T+65149ms: eth_getTransactionReceipt
T+65153ms: eth_getCode
T+65165ms: eth_uninstallFilter
T+65165ms: eth_sendTransaction
T+65194ms:   Transaction: 0xd7bc86d31bee32fa3988f1c1eabce403a1b5d570340a3a9cdba53a472ee8c956
T+65194ms:   Gas usage: 41981
T+65194ms:   Block Number: 2
T+65194ms:   Block Time: Mon Feb 26 2018 22:59:53 GMT+0100 (西歐標準時間)
T+65197ms: eth_getTransactionReceipt
T+65204ms: eth_accounts
T+65213ms: eth_sendTransaction
T+65256ms:   Transaction: 0x711b890f0fb0273901b59b8722e7a38b25f1ff8c4a6ff0f915089b9bd27f1edd
T+65256ms:   Contract created: 0x345ca3e014aaf5dca488057592ee47305d9b3e10
T+65256ms:   Gas usage: 559362
T+65256ms:   Block Number: 3
T+65261ms:   Block Time: Mon Feb 26 2018 22:59:53 GMT+0100 (西歐標準時間)
T+65263ms: eth_newBlockFilter
T+65265ms: eth_getFilterChanges
T+65268ms: eth_getTransactionReceipt
T+65270ms: eth_getCode
T+65273ms: eth_uninstallFilter
T+65273ms: eth_sendTransaction
T+65322ms:   Transaction: 0xf36163615f41ef7ed8f4a8f192149a0bf633fe1a2398ce001bf44c43dc7bdda0
T+65322ms:   Gas usage: 26981
T+65322ms:   Block Number: 4
T+65322ms:   Block Time: Mon Feb 26 2018 22:59:53 GMT+0100 (西歐標準時間)
T+65329ms: eth_getTransactionReceipt
T+65346ms: evm_snapshot
T+65354ms: eth_blockNumber
T+65360ms: eth_call
T+65575ms: eth_getBalance
T+65590ms: eth_call
T+65612ms: eth_call
T+65628ms: eth_call
T+65642ms: eth_call
T+65832ms: eth_getBalance
T+136913ms: net_version
T+136919ms: eth_accounts
T+136935ms: eth_accounts
T+137808ms: eth_accounts
T+137817ms: eth_sendTransaction
T+137842ms:   Transaction: 0x97e5ded884f0b8d20f68a30e5d55f5cf527a65e4d817bf3554c2ca253377552d
T+137842ms:   Contract created: 0x8f0483125fcb9aaaefa9209d8e9d7b9c8b9fb90f
T+137842ms:   Gas usage: 269607
T+137842ms:   Block Number: 5
T+137842ms:   Block Time: Mon Feb 26 2018 23:01:06 GMT+0100 (西歐標準時間)
T+137846ms: eth_newBlockFilter
T+137849ms: eth_getFilterChanges
T+137887ms: eth_getTransactionReceipt
T+137889ms: eth_getCode
T+137894ms: eth_uninstallFilter
T+137894ms: eth_sendTransaction
T+137925ms: E:\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:63898
T+137925ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_
T+137925ms: 
T+137925ms: TypeError: Cannot read property 'get' of undefined
T+137925ms:     at dbGet (E:\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:56029:7)
T+137925ms:     at E:\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:17614:5
T+137925ms:     at E:\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:23091:20
T+137925ms:     at iterate (E:\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:23172:13)
T+137925ms:     at E:\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:23184:29
T+137925ms:     at E:\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:22954:16
T+137925ms:     at E:\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:17619:7
T+137925ms:     at E:\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:56034:9
T+137925ms:     at dispatchError (E:\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:36358:36)
T+137925ms:     at E:\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:22744:14
```

**Comment by benjamincburns** [comment]
Hi @cand126, thanks for reporting this. This bug is trufflesuite/ganache-cli#417, and is fixed in the current beta. Check out our [releases](https://github.com/trufflesuite/ganache/releases) page for more info.
