### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by stv1024** [trufflesuite/ganache#369]
PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+14319ms: eth_getTransactionReceipt
T+14326ms: eth_sendTransaction
T+14354ms:   Transaction: 0x0163d779a796bcf61280a046290f75824cea902b3276255cfa44bb22642dfb19
T+14354ms:   Contract created: 0xde5491f774f0cb009abcea7326342e105dbb1b2e
T+14354ms:   Gas usage: 1589894
T+14354ms:   Block Number: 36
T+14354ms:   Block Time: Tue Feb 27 2018 18:09:43 GMT+0800 (CST)
T+14358ms: eth_newBlockFilter
T+14745ms: eth_getFilterChanges
T+14748ms: eth_getFilterChanges
T+14750ms: eth_getFilterChanges
T+14750ms: eth_getFilterChanges
T+14752ms: eth_getFilterChanges
T+14754ms: eth_getFilterChanges
T+14754ms: eth_getFilterChanges
T+14757ms: eth_getTransactionReceipt
T+14764ms: eth_getCode
T+14768ms: eth_uninstallFilter
T+14771ms: eth_sendTransaction
T+14789ms:   Transaction: 0x0d691e6215458cbaf9072c818991dcb3f559e8478b7cc32fd7b299dd4cd7fbcd
T+14789ms:   Gas usage: 45682
T+14789ms:   Block Number: 37
T+14789ms:   Block Time: Tue Feb 27 2018 18:09:43 GMT+0800 (CST)
T+14792ms: eth_getTransactionReceipt
T+14797ms: eth_sendTransaction
T+14831ms:   Transaction: 0xb21c1cdf3eb92a4d58ddeea6be1de85c7a90f9f264e7d3dbd87bdebc62ba2bc4
T+14831ms:   Gas usage: 45930
T+14831ms:   Block Number: 38
T+14831ms:   Block Time: Tue Feb 27 2018 18:09:43 GMT+0800 (CST)
T+14833ms: eth_getTransactionReceipt
T+14841ms: net_version
T+14844ms: eth_sendTransaction
T+15075ms:   Transaction: 0x9ab351d8a21074543c5a246cb2706702c97686c798a6ccac6b469708a21d2ca7
T+15075ms:   Contract created: 0xd54b47f8e6a1b97f3a84f63c867286272b273b7c
T+15075ms:   Gas usage: 6492859
T+15075ms:   Block Number: 39
T+15075ms:   Block Time: Tue Feb 27 2018 18:09:43 GMT+0800 (CST)
T+15078ms: eth_newBlockFilter
T+15250ms: eth_getFilterChanges
T+15254ms: eth_getFilterChanges
T+15256ms: eth_getFilterChanges
T+15258ms: eth_getFilterChanges
T+15260ms: eth_getFilterChanges
T+15260ms: eth_getFilterChanges
T+15262ms: eth_getFilterChanges
T+15265ms: eth_getTransactionReceipt
T+15278ms: eth_getCode
T+15282ms: eth_uninstallFilter
T+15284ms: net_version
T+15286ms: eth_sendTransaction
T+15301ms:   Transaction: 0x2a761651e0daf0fdc07defc7770db90aa69d5d51852ef42ee83cec66ce59e285
T+15301ms:   Gas usage: 28591
T+15301ms:   Block Number: 40
T+15301ms:   Block Time: Tue Feb 27 2018 18:09:44 GMT+0800 (CST)
T+15304ms: eth_getTransactionReceipt
T+15309ms: eth_sendTransaction
T+15345ms:   Transaction: 0x095b0688e9a1c5d2a652b1c8ea52c7c5a511d16de23b24fc7feeef7201ed5f23
T+15345ms:   Gas usage: 46238
T+15345ms:   Block Number: 41
T+15345ms:   Block Time: Tue Feb 27 2018 18:09:44 GMT+0800 (CST)
T+15347ms: eth_getTransactionReceipt
T+15357ms: eth_sendTransaction
T+15371ms:   Transaction: 0x8de70525a63f9a5411d59a3e71da2629e0fa925bcfa41bd82cf8a542852b206f
T+15371ms:   Gas usage: 27566
T+15371ms:   Block Number: 42
T+15371ms:   Block Time: Tue Feb 27 2018 18:09:44 GMT+0800 (CST)
T+15375ms: eth_getTransactionReceipt
T+15380ms: eth_newFilter
T+15382ms: eth_newFilter
T+15382ms: eth_newFilter
T+15384ms: eth_newFilter
T+15386ms: eth_newFilter
T+15388ms: eth_newFilter
T+15388ms: eth_blockNumber
T+15390ms: eth_getFilterLogs
T+15393ms: eth_getFilterLogs
T+15394ms: eth_getFilterLogs
T+15494ms: eth_blockNumber
T+15512ms: eth_getFilterLogs
T+15514ms: eth_getFilterLogs
T+15516ms: eth_getFilterLogs
T+15518ms: eth_call
T+15579ms: eth_sendTransaction
T+15638ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+15638ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+15638ms: 
T+15638ms: TypeError: Cannot read property 'get' of undefined
T+15638ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+15638ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+15638ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+15638ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+15638ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+15638ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+15638ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+15638ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+15638ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+15638ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by benjamincburns** [comment]
Hi @stv1024, thanks for reporting this! Unfortunately this report duplicates trufflesuite/ganache-cli#417. Fortunately, this issue is already fixed in the current beta! Check out our releases page for more info.
