### ISSUE TITLE
System Error when running Ganache 1.0.2 on linux

### ISSUE THREAD

**Issue by ddbit** [trufflesuite/ganache#372]
PLATFORM: linux
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+156919ms: eth_newBlockFilter
T+156927ms: eth_getFilterChanges
T+156933ms: eth_getTransactionReceipt
T+156939ms: eth_getCode
T+156951ms: eth_uninstallFilter
T+156954ms: eth_sendTransaction
T+156977ms:   Transaction: 0x834bf7895ffbaa129edd5925cae516d4966677bfebc1568dc56fc1ca9018e1a0
T+156977ms:   Gas usage: 41984
T+156982ms:   Block Number: 64
T+156982ms:   Block Time: Wed Feb 28 2018 00:18:28 GMT+0100 (CET)
T+156984ms: eth_getTransactionReceipt
T+157334ms: evm_snapshot
T+157351ms: eth_blockNumber
T+157355ms: net_version
T+157388ms: eth_sendTransaction
T+157393ms:   Transaction: 0x04bbdd2a2c21cb961c3128b13e2caa7c004bf73f8ef433ef2d0f57a6df4f7ee1
T+157393ms:   Contract created: 0xd5e8aa91bda51688e6f3de82e52fb38e35298515
T+157393ms:   Gas usage: 460322
T+157393ms:   Block Number: 65
T+157400ms:   Block Time: Wed Feb 28 2018 00:18:28 GMT+0100 (CET)
T+157444ms: eth_newBlockFilter
T+157451ms: eth_getFilterChanges
T+157460ms: eth_getTransactionReceipt
T+157471ms: eth_getCode
T+157478ms: eth_uninstallFilter
T+157481ms: net_version
T+157483ms: eth_sendTransaction
T+157494ms:   Transaction: 0xe0368f63e3210515da4a720ca23757a067341b3a4859625fc642bd20e40b2628
T+157494ms:   Contract created: 0xa509542ada3196a38bd6fd03b253547ee09220c4
T+157494ms:   Gas usage: 387558
T+157494ms:   Block Number: 66
T+157494ms:   Block Time: Wed Feb 28 2018 00:18:28 GMT+0100 (CET)
T+157499ms: eth_newBlockFilter
T+157502ms: eth_getFilterChanges
T+157508ms: eth_getTransactionReceipt
T+157550ms: eth_getCode
T+157557ms: eth_uninstallFilter
T+157560ms: net_version
T+157565ms: eth_sendTransaction
T+157567ms:   Transaction: 0x6de1d690b93d80c0154690fdd445e1d262e4476fd2c984065966dc757f670058
T+157567ms:   Gas usage: 53474
T+157567ms:   Block Number: 67
T+157569ms:   Block Time: Wed Feb 28 2018 00:18:28 GMT+0100 (CET)
T+157573ms: eth_getTransactionReceipt
T+157581ms: net_version
T+157584ms: eth_call
T+157603ms: eth_blockNumber
T+157607ms: net_version
T+157615ms: eth_sendTransaction
T+157636ms:   Transaction: 0x95f3b9fb3057b4461a700f174cf88ebbb259cf8e20f58ce37e0fa1a41621b2f9
T+157636ms:   Contract created: 0x27032850077abef46fc9c2b39b96885b40abc3ec
T+157636ms:   Gas usage: 460322
T+157636ms:   Block Number: 68
T+157636ms:   Block Time: Wed Feb 28 2018 00:18:28 GMT+0100 (CET)
T+157640ms: eth_newBlockFilter
T+157646ms: eth_getFilterChanges
T+157652ms: eth_getTransactionReceipt
T+157660ms: eth_getCode
T+157666ms: eth_uninstallFilter
T+157668ms: net_version
T+157671ms: eth_sendTransaction
T+157715ms:   Transaction: 0xc6a2ba7f9c6b9b555d0562796fa42ad08cba1ef35d79a61253ed43c712aebf37
T+157715ms:   Contract created: 0x6b76731b504303a65488dbc138d7019c249b4216
T+157715ms:   Gas usage: 387558
T+157715ms:   Block Number: 69
T+157715ms:   Block Time: Wed Feb 28 2018 00:18:29 GMT+0100 (CET)
T+157719ms: eth_newBlockFilter
T+157721ms: eth_getFilterChanges
T+157728ms: eth_getTransactionReceipt
T+157735ms: eth_getCode
T+157739ms: eth_uninstallFilter
T+157745ms: net_version
T+157748ms: eth_sendTransaction
T+157779ms:   Transaction: 0x4d9648d94a365ae9965786095cf14d9daa4e85eded0b2b6ae07d20185db17abd
T+157779ms:   Gas usage: 53474
T+157779ms:   Block Number: 70
T+157784ms:   Block Time: Wed Feb 28 2018 00:18:29 GMT+0100 (CET)
T+157786ms: eth_getTransactionReceipt
T+157792ms: net_version
T+157801ms: eth_sendTransaction
T+157920ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+157920ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_W
T+157920ms: 
T+157920ms: TypeError: Cannot read property 'get' of undefined
T+157920ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+157920ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+157920ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+157920ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+157920ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+157920ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+157920ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+157920ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+157920ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+157920ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by benjamincburns** [comment]
Hi @ddbit, thanks for reporting this. Unfortunately this report duplicates trufflesuite/ganache-cli#417. Fortunately, this issue is already fixed in the current beta! Check out our releases page for more info.
