### ISSUE TITLE
System Error when running Ganache 1.1.0-beta.1 on darwin

### ISSUE THREAD

**Issue by renqingyang** [trufflesuite/ganache#373]
PLATFORM: darwin
GANACHE VERSION: 1.1.0-beta.1

EXCEPTION:
```
Error: listen EADDRINUSE 127.0.0.1:8545
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at doListening (net.js:1397:7)
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)
```

APPLICATION LOG:
```
T+0ms: Starting server with configuration: {"hostname":"localhost","port":8545,"network_id":5777,"total_accounts":10,"unlocked_accounts":[],"mnemonic":"candy maple cake sugar pudding cream honey rich smooth crumble sweet treat","vmErrorsOnRPCResponse":true}
```

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #665. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
