### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by nicallennn** [trufflesuite/ganache#380]
PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+19482ms: eth_getBlockByNumber
T+19492ms:   Transaction: 0xd7bc86d31bee32fa3988f1c1eabce403a1b5d570340a3a9cdba53a472ee8c956
T+19492ms:   Gas usage: 41981
T+19492ms:   Block Number: 2
T+19494ms:   Block Time: Thu Mar 01 2018 19:46:21 GMT+0000 (GMT)
T+19496ms: eth_getTransactionReceipt
T+19505ms: eth_accounts
T+19514ms: eth_sendTransaction
T+19547ms:   Transaction: 0xd0fc03d5a050f51734c3fe01f4a01294faa65a13a47b3eab31da77fccb33833e
T+19547ms:   Contract created: 0x345ca3e014aaf5dca488057592ee47305d9b3e10
T+19547ms:   Gas usage: 849663
T+19547ms:   Block Number: 3
T+19549ms:   Block Time: Thu Mar 01 2018 19:46:21 GMT+0000 (GMT)
T+19551ms: eth_newBlockFilter
T+19553ms: eth_getFilterChanges
T+19561ms: eth_getTransactionReceipt
T+19566ms: eth_getCode
T+19574ms: eth_uninstallFilter
T+19577ms: eth_sendTransaction
T+19599ms: eth_getBlockByNumber
T+19603ms:   Transaction: 0xf36163615f41ef7ed8f4a8f192149a0bf633fe1a2398ce001bf44c43dc7bdda0
T+19603ms:   Gas usage: 26981
T+19603ms:   Block Number: 4
T+19607ms:   Block Time: Thu Mar 01 2018 19:46:21 GMT+0000 (GMT)
T+19610ms: eth_getTransactionReceipt
T+19688ms: evm_snapshot
T+19698ms: eth_blockNumber
T+19703ms: eth_sendTransaction
T+19719ms: eth_getBlockByNumber
T+19735ms:   Transaction: 0xc188fe4112bef5af4719eb9916ba7c0582db26a1add7d3b2d930451f76f70e61
T+19735ms:   Gas usage: 23190
T+19735ms:   Block Number: 5
T+19737ms:   Block Time: Thu Mar 01 2018 19:46:21 GMT+0000 (GMT)
T+19737ms:   Runtime Error: revert
T+19741ms: eth_call
T+19774ms: eth_blockNumber
T+19779ms: eth_sendTransaction
T+19818ms:   Transaction: 0x3ede3482bc7b96d5592590eaf47c54bfdf9449d6bc064b6090b3fade58114c06
T+19818ms:   Gas usage: 157811
T+19818ms:   Block Number: 6
T+19818ms:   Block Time: Thu Mar 01 2018 19:46:21 GMT+0000 (GMT)
T+19843ms: eth_getBlockByNumber
T+19851ms: eth_getTransactionReceipt
T+19883ms: eth_sendTransaction
T+19944ms:   Transaction: 0x029ff82058258f439a77ffc22f61033054eb662593fb9cc71dc4cc5450db24aa
T+19944ms:   Gas usage: 77470
T+19944ms:   Block Number: 7
T+19944ms:   Block Time: Thu Mar 01 2018 19:46:21 GMT+0000 (GMT)
T+19948ms: eth_getTransactionReceipt
T+19951ms: eth_call
T+19955ms: eth_getBlockByNumber
T+19981ms: eth_sendTransaction
T+20002ms:   Transaction: 0x1454a00c30e0ff0cde2da835d927ff97fd728d81840e40a329ec77c56e2785e7
T+20002ms:   Gas usage: 22683
T+20002ms:   Block Number: 8
T+20002ms:   Block Time: Thu Mar 01 2018 19:46:21 GMT+0000 (GMT)
T+20002ms:   Runtime Error: revert
T+20004ms: eth_call
T+20035ms: eth_blockNumber
T+20039ms: eth_sendTransaction
T+20070ms: eth_getBlockByNumber
T+20085ms:   Transaction: 0x22fbd679f05f8924ef0120805f0d463eb643d3e86dc7b8b80e546167caaa7b36
T+20085ms:   Gas usage: 62925
T+20085ms:   Block Number: 9
T+20085ms:   Block Time: Thu Mar 01 2018 19:46:21 GMT+0000 (GMT)
T+20088ms: eth_getTransactionReceipt
T+20093ms: eth_sendTransaction
T+20111ms:   Transaction: 0x17277df5a96440b754cf3f7d2253c01141be6d5b1ced966b433314eb331ce847
T+20111ms:   Gas usage: 22962
T+20111ms:   Block Number: 10
T+20111ms:   Block Time: Thu Mar 01 2018 19:46:21 GMT+0000 (GMT)
T+20114ms:   Runtime Error: revert
T+20116ms: eth_call
T+20154ms: eth_blockNumber
T+20159ms: eth_sendTransaction
T+20162ms: evm_revert
T+20181ms: eth_getBlockByNumber
T+20192ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+20192ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+20192ms: 
T+20192ms: TypeError: Cannot read property 'toJSON' of null
T+20192ms:     at /node_modules/ganache-cli/build/lib.node.js:80442:24
T+20192ms:     at /node_modules/ganache-cli/build/lib.node.js:21713:5
T+20192ms:     at /node_modules/ganache-cli/build/lib.node.js:78351:7
T+20192ms:     at /node_modules/ganache-cli/build/lib.node.js:7539:16
T+20192ms:     at /node_modules/ganache-cli/build/lib.node.js:7756:32
T+20192ms:     at /node_modules/ganache-cli/build/lib.node.js:7531:16
T+20192ms:     at /node_modules/ganache-cli/build/lib.node.js:78346:9
T+20192ms:     at Object.decode (/node_modules/ganache-cli/build/lib.node.js:47235:5)
T+20192ms:     at /node_modules/ganache-cli/build/lib.node.js:78343:20
T+20192ms:     at /node_modules/ganache-cli/build/lib.node.js:7668:20
```

**Comment by nicallennn** [comment]
Error: RPC Error: NotFoundError: Key not found in database
    at /Applications/Ganache.app/Contents/Resources/app/node_modules/ganache-cli/build/lib.node.js:75532:18
    at /Applications/Ganache.app/Contents/Resources/app/node_modules/ganache-cli/build/lib.node.js:75297:19
    at /Applications/Ganache.app/Contents/Resources/app/node_modules/ganache-cli/build/lib.node.js:77442:21
    at ReadFileContext.callback (/Applications/Ganache.app/Contents/Resources/app/node_modules/ganache-cli/build/lib.node.js:77339:14)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:336:13)
      at intermediary (/usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-core/lib/testing/testrunner.js:230:1)
      at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-provider/wrapper.js:134:1
      at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
      at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
      at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
      at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
      at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
      at endReadableNT (_stream_readable.js:1101:12)
      at process._tickCallback (internal/process/next_tick.js:152:19)

**Comment by nicallennn** [comment]
various errors going on now. all are caused by running the same command...... truffle test. sometimes ganache crashes, other times it stays up but blocks stop getting mined.....

**Comment by nicallennn** [comment]
this was caused by an error in the solidity code. closed
