### ISSUE TITLE
Blockchain process exited prematurely with code '7', due to signal 'null' when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by kkom** [trufflesuite/ganache#394]
I was following this guide to deploy a simple smart contract:

https://medium.com/crypto-currently/build-your-first-smart-contract-fc36a8ff50ca

Rough repro steps:

1. Copy-paste this Solidity code from the Medium guide:

```
pragma solidity ^0.4.0;
contract Counter {
    int private count = 0;
    function incrementCounter() public {
        count += 1;
    }
    function decrementCounter() public {
        count -= 1;
    }
    function getCount() public constant returns (int) {
        return count;
    }
}
```

Here is the contract's bytecode:

```
606060405260008055341561001357600080fd5b60fb806100216000396000f3006060604052600436106053576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff1680635b34b966146058578063a87d942c14606a578063f5c5ad83146090575b600080fd5b3415606257600080fd5b606860a2565b005b3415607457600080fd5b607a60b4565b6040518082815260200191505060405180910390f35b3415609a57600080fd5b60a060bd565b005b60016000808282540192505081905550565b60008054905090565b600160008082825403925050819055505600a165627a7a723058208831ba2c8428eead0e05467aed6cb222a933ba8126f77ba9e7b4348ced17b2350029
```

2. Launch Ganache with vanilla configuration.

3. Use MyEtherWallet 3.20.03 to deploy the contract on the Ganache test network:

- connect to the network using its address from "RPC server" section
- fill in the bytecode above and use auto populated 124604 gas liimit 
- use the first address's private key to unlock the wallet
- click on "Sign transaction"

At this point Ganache crashes with the reported exception.

This is the raw transaction generated:

```
{"nonce":"0x00","gasPrice":"0x098bca5a00","gasLimit":"0x01e6bc","to":"","value":"0x00","data":"0x606060405260008055341561001357600080fd5b60fb806100216000396000f3006060604052600436106053576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff1680635b34b966146058578063a87d942c14606a578063f5c5ad83146090575b600080fd5b3415606257600080fd5b606860a2565b005b3415607457600080fd5b607a60b4565b6040518082815260200191505060405180910390f35b3415609a57600080fd5b60a060bd565b005b60016000808282540192505081905550565b60008054905090565b600160008082825403925050819055505600a165627a7a723058208831ba2c8428eead0e05467aed6cb222a933ba8126f77ba9e7b4348ced17b2350029","chainId":1}
```

PLATFORM: darwin (Mac OS X High Sierra 10.13.3)
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+0ms: Starting server with configuration: {"hostname":"127.0.0.1","mnemonic":"candy maple cake sugar pudding cream honey rich smooth crumble sweet treat","network_id":5777,"port":7545,"total_accounts":10,"unlocked_accounts":[]}
T+212ms: Ganache started successfully!
T+212ms: Waiting for requests...
T+295049ms: eth_blockNumber
T+366776ms: eth_blockNumber
T+483582ms: eth_estimateGas
T+559548ms: eth_estimateGas
T+576882ms: eth_getBalance
T+576882ms: eth_gasPrice
T+576882ms: eth_getTransactionCount
T+576899ms: eth_getBalance
T+576899ms: eth_gasPrice
T+576899ms: eth_getTransactionCount
T+576958ms: eth_estimateGas
T+576962ms: 
T+576962ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+576962ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+576968ms: AssertionError: The field to must have byte length of 20
T+576968ms:     at FakeTransaction.setter [as to] (/node_modules/ganache-cli/build/lib.node.js:7366:9)
T+576968ms:     at /node_modules/ganache-cli/build/lib.node.js:7416:63
T+576968ms:     at Array.forEach (native)
T+576968ms:     at Object.exports.defineProperties (/node_modules/ganache-cli/build/lib.node.js:7415:14)
T+576968ms:     at FakeTransaction.Transaction (/node_modules/ganache-cli/build/lib.node.js:78121:13)
T+576968ms:     at FakeTransaction (/node_modules/ganache-cli/build/lib.node.js:20454:5)
T+576968ms:     at /node_modules/ganache-cli/build/lib.node.js:80343:14
T+576968ms:     at /node_modules/ganache-cli/build/lib.node.js:21924:5
T+576968ms:     at /node_modules/ganache-cli/build/lib.node.js:55954:5
T+576968ms:     at /node_modules/ganache-cli/build/lib.node.js:56320:14
```

**Comment by kkom** [comment]
Notably, if I restart Ganache and deploy the already signed contract from MyEtherWallet, things work as expected. I.e. the transaction count of the address from which I signed and deployed the contract goes up.

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #668. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
