### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by Mc01** [trufflesuite/ganache#395]
Bug appear when running tests with Truffle several times in row.

PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+27789282ms: eth_getFilterChanges
T+27789289ms: eth_getTransactionReceipt
T+27789300ms: eth_getCode
T+27789308ms: eth_uninstallFilter
T+27789310ms: eth_sendTransaction
T+27789334ms:   Transaction: 0xc684b0e3876590f09cf93b130abe0e423378d903be23bb6a123975fcec99be8b
T+27789334ms:   Gas usage: 27006
T+27789334ms:   Block Number: 128
T+27789337ms:   Block Time: Wed Jul 11 2018 18:17:12 GMT+0200 (CEST)
T+27789340ms: eth_getTransactionReceipt
T+27789379ms: evm_snapshot
T+27789503ms: eth_blockNumber
T+27789532ms: eth_sendTransaction
T+27789543ms:   Transaction: 0x9b08b10f4a4733d3a4affcc93c80d54fa470ef2f1b13f723db9af1edba07ec7c
T+27789543ms:   Contract created: 0x219ebb52f4e92c4fa554e80316b95d4adefb3ed6
T+27789543ms:   Gas usage: 2817147
T+27789543ms:   Block Number: 129
T+27789543ms:   Block Time: Wed Jul 11 2018 18:17:12 GMT+0200 (CEST)
T+27789560ms: eth_newBlockFilter
T+27789576ms: eth_getFilterChanges
T+27789578ms: eth_getTransactionReceipt
T+27789582ms: eth_getCode
T+27789586ms: eth_uninstallFilter
T+27789589ms: eth_sendTransaction
T+27789629ms:   Transaction: 0xa346b3c420c08e7a242ba66ad1fd3d9018a233a24170a368b19928997e8e69bd
T+27789629ms:   Gas usage: 91074
T+27789629ms:   Block Number: 130
T+27789629ms:   Block Time: Wed Jul 11 2018 18:17:12 GMT+0200 (CEST)
T+27789633ms: eth_getTransactionReceipt
T+27789636ms: eth_sendTransaction
T+27789675ms:   Transaction: 0x1db43f3d8a5503eae3c3cb7d1abfede1537a4e55ee34d9a12a09df26fc414f17
T+27789675ms:   Gas usage: 169871
T+27789675ms:   Block Number: 131
T+27789675ms:   Block Time: Wed Jul 11 2018 18:17:12 GMT+0200 (CEST)
T+27789677ms: eth_getTransactionReceipt
T+27789682ms: eth_sendTransaction
T+27789745ms:   Transaction: 0x3e8b679b1cd416aeda542b437e55e712e09a2fd07290e79de41c394320441404
T+27789745ms:   Gas usage: 170568
T+27789745ms:   Block Number: 132
T+27789745ms:   Block Time: Wed Jul 11 2018 18:17:12 GMT+0200 (CEST)
T+27789748ms: eth_getTransactionReceipt
T+27789753ms: eth_call
T+27789774ms: eth_call
T+27789797ms: eth_call
T+27789812ms: eth_call
T+27789826ms: eth_call
T+27789844ms: eth_call
T+27789859ms: eth_blockNumber
T+27789864ms: eth_sendTransaction
T+27789897ms:   Transaction: 0xf9f6bfd78a9db91631f9b12450a8677f13c993c94c30fcfb96636cb319250a70
T+27789897ms:   Contract created: 0xbab15d629b84e2c9575da294ab24b227e15fa02f
T+27789897ms:   Gas usage: 2817147
T+27789897ms:   Block Number: 133
T+27789901ms:   Block Time: Wed Jul 11 2018 18:17:12 GMT+0200 (CEST)
T+27789903ms: eth_newBlockFilter
T+27789905ms: eth_getFilterChanges
T+27789910ms: eth_getTransactionReceipt
T+27789919ms: eth_getCode
T+27789922ms: eth_uninstallFilter
T+27789925ms: eth_sendTransaction
T+27789956ms:   Transaction: 0x8b9cc247d36d2b46f7b1bcdbf31c3c6fbe8236278a2de6f184dc1c366f6d46a1
T+27789956ms:   Gas usage: 91074
T+27789956ms:   Block Number: 134
T+27789956ms:   Block Time: Wed Jul 11 2018 18:17:12 GMT+0200 (CEST)
T+27789959ms: eth_getTransactionReceipt
T+27789962ms: eth_sendTransaction
T+27789998ms:   Transaction: 0xe5a2350be9dc85b32cd74fc2a8b56293b0111c95752619daacab72b8bb11b032
T+27789998ms:   Gas usage: 169871
T+27789998ms:   Block Number: 135
T+27790001ms:   Block Time: Wed Jul 11 2018 18:17:12 GMT+0200 (CEST)
T+27790003ms: eth_getTransactionReceipt
T+27790028ms: eth_sendTransaction
T+27790046ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+27790046ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+27790046ms: 
T+27790046ms: TypeError: Cannot read property 'get' of undefined
T+27790046ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+27790046ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+27790046ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+27790046ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+27790046ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+27790046ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+27790046ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+27790046ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+27790046ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+27790046ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #667. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
