### ISSUE TITLE
System Error when running Ganache 1.0.2 on linux

### ISSUE THREAD

**Issue by grigio** [trufflesuite/ganache#397]
tried to run `truffle test` of https://github.com/skiral/gilgamesh-token-contract

PLATFORM: linux
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+48521ms: eth_blockNumber
T+48534ms: eth_call
T+48539ms: net_version
T+48548ms: eth_sendTransaction
T+48553ms: eth_sendTransaction
T+48562ms: eth_getFilterChanges
T+48727ms:   Transaction: 0x1143a25b8199b2d5cd4a9233c435c2b1b6d24534e22fc7e83a974dea47425636
T+48727ms:   Contract created: 0x96a08824f87070075262dbce23c6babffdca0493
T+48733ms:   Gas usage: 1776558
T+48733ms:   Block Number: 129
T+48733ms:   Block Time: Thu Mar 08 2018 09:34:10 GMT+0100 (CET)
T+48738ms: eth_newBlockFilter
T+48813ms:   Transaction: 0x0ef2aa70798e85830534e117caad26b8dae0a6ba348f40272816fc5a0605dc52
T+48813ms:   Gas usage: 30882
T+48813ms:   Block Number: 130
T+48813ms:   Block Time: Thu Mar 08 2018 09:34:10 GMT+0100 (CET)
T+48821ms: eth_getTransactionReceipt
T+48828ms: eth_getTransactionReceipt
T+48833ms: net_version
T+48837ms: eth_getCode
T+48842ms: eth_sendTransaction
T+48848ms: eth_uninstallFilter
T+48852ms: net_version
T+48855ms: eth_call
T+48881ms:   Transaction: 0xc7d82ec7745638955c40ff443be1d2e0b8888f958949509b2d387d6fba9ed1a2
T+48881ms:   Gas usage: 42265
T+48881ms:   Block Number: 131
T+48881ms:   Block Time: Thu Mar 08 2018 09:34:10 GMT+0100 (CET)
T+48886ms: eth_getTransactionReceipt
T+48904ms: net_version
T+48911ms: net_version
T+48915ms: eth_blockNumber
T+48924ms: eth_sendTransaction
T+48928ms: eth_sendTransaction
T+48932ms: net_version
T+48937ms: eth_sendTransaction
T+48944ms: net_version
T+48950ms: eth_call
T+49016ms:   Transaction: 0x438879cfa7c48d54e925be6e48c0b23e98b1f7be7c9e3d7e4cca23adf87880d8
T+49016ms:   Gas usage: 28571
T+49016ms:   Block Number: 132
T+49016ms:   Block Time: Thu Mar 08 2018 09:34:10 GMT+0100 (CET)
T+49034ms: eth_getTransactionReceipt
T+49051ms: eth_getFilterChanges
T+49080ms:   Transaction: 0xbb999d2dbebe4b92d4d74870cd7709fb2f0e656fe820f6b7ec9782aef197f8aa
T+49080ms:   Gas usage: 28635
T+49080ms:   Block Number: 133
T+49080ms:   Block Time: Thu Mar 08 2018 09:34:10 GMT+0100 (CET)
T+49086ms: eth_getTransactionReceipt
T+49218ms:   Transaction: 0x5bdfc51870838929627b66818b96636a844a705c48f56bff332a48f0f90e8b33
T+49218ms:   Contract created: 0xcb95f554b1d4fe89d5d917c0962f81629e97a6df
T+49218ms:   Gas usage: 1776558
T+49218ms:   Block Number: 134
T+49218ms:   Block Time: Thu Mar 08 2018 09:34:10 GMT+0100 (CET)
T+49227ms: eth_newBlockFilter
T+49300ms: net_version
T+49309ms: eth_call
T+49314ms: eth_getTransactionReceipt
T+49314ms: eth_getTransactionReceipt
T+49314ms: eth_getTransactionReceipt
T+49314ms: eth_getTransactionReceipt
T+49314ms: eth_getTransactionReceipt
T+49350ms: eth_getCode
T+49354ms: eth_getCode
T+49354ms: eth_getCode
T+49363ms: eth_getCode
T+49374ms: eth_getCode
T+49383ms: eth_uninstallFilter
T+49389ms: net_version
T+49394ms: eth_call
T+49401ms: net_version
T+49409ms: eth_call
T+49421ms: net_version
T+49433ms: eth_call
T+49444ms: net_version
T+49450ms: eth_call
T+49464ms: net_version
T+49473ms: eth_call
T+49507ms: net_version
T+49522ms: eth_call
T+49549ms: net_version
T+49556ms: eth_getFilterChanges
T+49563ms: eth_call
T+49579ms: net_version
T+49588ms: eth_call
T+49596ms: eth_getTransactionReceipt
T+49603ms: eth_getCode
T+49613ms: eth_uninstallFilter
T+49618ms: net_version
T+49623ms: eth_call
T+49633ms: net_version
T+49638ms: eth_call
T+49666ms: net_version
T+49670ms: eth_call
T+49718ms: net_version
T+49727ms: eth_call
T+49768ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+49768ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_W
T+49768ms: 
T+49768ms: TypeError: Cannot read property 'get' of undefined
T+49768ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+49768ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+49768ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+49768ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+49768ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+49768ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+49768ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+49768ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+49768ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+49768ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by hacktar** [comment]
same error running Ganache UI
Blockchain process exited prematurely with code '7', due to signal 'null'.
