### ISSUE TITLE
Fail to catch contract revert using expect in unit test

### ISSUE THREAD

**Issue by Wei-Tianxiang** [trufflesuite/ganache#4010]
Hello,

I am currently writing unit tests for a Solidity contract using the Truffle framework and a Ganache EVM node. In the unit test, I am trying to use the expectRevert() function from OpenZeppelin's test helper to catch the revert exception thrown by a function. The unit test runs and passes on my local Mac environment, but it fails when run on a remote Linux server (where I have also installed a Ganache node).

Below are the details of my local environment:

MacBook Air M1 2020
MacOS Ventura 13.0.1 (22A400)
Node: v18.12.1
NPM: 9.1.2
"@openzeppelin/test-helpers": "^0.5.15"
"chai": "^4.3.7"
Ganache: v7.5.0 (@ganache/cli: 0.6.0, @ganache/core: 0.6.0)

Below are the details of the remote server environment:

NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
Ganache: v7.5.0 (@ganache/cli: 0.6.0, @ganache/core: 0.6.0)
Node: v18.12.1
NPM: 8.19.2

the code block with error is
```javascript
tx = await expectRevert(
        onchain_market.submitOnChainResult(
          data_vhash,
          request_hash,
          12876,
          result,
          result_signature
        ),
        "insufficient amount"
      );
```

The output truffle gave me is
```
 1) submit result
    > No events were emitted

18 passing (3s)
  1 failing

  1) Contract: TESTSGXStaticDataMarket
       init
         submit result:
     AssertionError: Expected to fail with insufficient amount, but failed with: StatusError: Transaction: 0x52636df20bb5197042620dd24098baf2721cae7bfee5526d0b212767e0030b98 exited with an error (status 0).
     Please check that the transaction:
     - satisfies all conditions set by Solidity `require` statements.
     - does not trigger a Solidity `revert` statement.

      at fails (node_modules/truffle-assertions/index.js:155:13)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at Context.<anonymous> (/home/weitx/treehole-contract/test/test_request.js:100:12)
```

I also tried to use the npm package `truffle-assertions` to catch revert errors later, but it also produced the same error as the above error. Hope to get your answer, thank you very much!

**Comment by MicaiahReid** [comment]
What ganache startup options are being used? Are they the same between the Mac and Linux environments?

**Comment by Wei-Tianxiang** [comment]
Yes, on the Mac environment, I used the GUI Ganache, with local host and port set to 7545, network id to 5777, and on the Linux server, I used the Ganache cli, with the same arguments

**Comment by davidmurdoch** [comment]
Ganache GUI and `ganache` the npm package, are not currently in sync. Ganache GUI still uses old hardfork rules. We are expecting to ship an update to Ganache GUI to align it with the npm package in early January. 

If you don't want to wait until then you can download the Release artifact zip from https://github.com/trufflesuite/ganache-ui/actions/runs/3681577316 and use the development version contained within. Note: this development version has not be signed or notarized, so macOS may make it annoying to install, depending on your security settings.

p.s., I'm curious why you told us in your first response that you were using `Ganache: v7.5.0 (@ganache/cli: 0.6.0, @ganache/core: 0.6.0)` in your Mac environment, when you weren't. We spent a good bit of time trying to figure out what was going wrong across OSes because of that.

**Comment by Wei-Tianxiang** [comment]
when I type `ganache --version` and `ganache-cli --version` in my shell on my local Mac environment, this is exactly the output `ganache v7.5.0 (@ganache/cli: 0.6.0, @ganache/core: 0.6.0)`

**Comment by davidmurdoch** [comment]
Ah, Ganache UI uses it's own internal version. Your system's version doesn't matter.

**Comment by Wei-Tianxiang** [comment]
> Ah, Ganache UI uses it's own internal version. Your system's version doesn't matter.

So, do two ganache versions on my Mac env and Linux env align?

**Comment by davidmurdoch** [comment]
Use CLI on both.
