### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by loki-sama** [trufflesuite/ganache#403]
Ganache just crashed don't have much more than this error message.

PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+514300917ms:   Block Time: Fri Mar 09 2018 20:23:01 GMT+0100 (CET)
T+514300920ms: eth_getTransactionReceipt
T+514300930ms: eth_call
T+514300946ms: eth_call
T+514887623ms: eth_accounts
T+514887687ms: eth_accounts
T+514887729ms: net_version
T+514887733ms: net_version
T+514887740ms: eth_sendTransaction
T+514887779ms:   Transaction: 0x73d52af9a1da917ad0eacb133a879cf9efc54d2a678d7e51d20b52bb56e68cef
T+514887779ms:   Contract created: 0x8065f4c7b8c2bf53561af92d9da2ea022a0b28ca
T+514887779ms:   Gas usage: 269607
T+514887779ms:   Block Number: 45
T+514887779ms:   Block Time: Fri Mar 09 2018 20:32:48 GMT+0100 (CET)
T+514887782ms: eth_newBlockFilter
T+514887786ms: eth_getFilterChanges
T+514887795ms: eth_getTransactionReceipt
T+514887802ms: eth_getCode
T+514887813ms: eth_uninstallFilter
T+514887818ms: eth_sendTransaction
T+514887843ms:   Transaction: 0xd92e5401eece08c37242e363a5741f4f74d529a1a3e3f005131ddbb497eded33
T+514887843ms:   Gas usage: 41981
T+514887843ms:   Block Number: 46
T+514887843ms:   Block Time: Fri Mar 09 2018 20:32:48 GMT+0100 (CET)
T+514887847ms: eth_getTransactionReceipt
T+514887859ms: eth_accounts
T+514887980ms: net_version
T+514887986ms: net_version
T+514887990ms: eth_sendTransaction
T+514888068ms:   Transaction: 0x89c00df8fc65e4ca1f1bee3c842f3876201d6939d70d871df9e0a4ddc051f192
T+514888068ms:   Contract created: 0x4eee4559bd589b1cdfc419f0eed2ff9cbd47f439
T+514888068ms:   Gas usage: 213240
T+514888068ms:   Block Number: 47
T+514888071ms:   Block Time: Fri Mar 09 2018 20:32:49 GMT+0100 (CET)
T+514888073ms: eth_newBlockFilter
T+514888076ms: eth_getFilterChanges
T+514888080ms: eth_getTransactionReceipt
T+514888086ms: eth_getCode
T+514888092ms: eth_uninstallFilter
T+514888096ms: net_version
T+514888102ms: net_version
T+514888106ms: eth_sendTransaction
T+514888131ms:   Transaction: 0x170478d7b013785749594e73e3a17c14c2f587e43872f34d20ae209894603ee5
T+514888131ms:   Contract created: 0xcb152a2aa90055a0d255ca7dbaeb85edfdc86096
T+514888131ms:   Gas usage: 259561
T+514888131ms:   Block Number: 48
T+514888134ms:   Block Time: Fri Mar 09 2018 20:32:49 GMT+0100 (CET)
T+514888138ms: eth_newBlockFilter
T+514888141ms: eth_getFilterChanges
T+514888145ms: eth_getTransactionReceipt
T+514888152ms: eth_getCode
T+514888156ms: eth_uninstallFilter
T+514888159ms: net_version
T+514888162ms: net_version
T+514888164ms: eth_sendTransaction
T+514888191ms:   Transaction: 0xd1b1a125f76177ced39befa78ebb5d7836538ccc506854e4f181384240f13f03
T+514888191ms:   Contract created: 0x23e84570f7b28ad0d5e5545d398009194a8734f3
T+514888191ms:   Gas usage: 535704
T+514888194ms:   Block Number: 49
T+514888194ms:   Block Time: Fri Mar 09 2018 20:32:49 GMT+0100 (CET)
T+514888197ms: eth_newBlockFilter
T+514888200ms: eth_getFilterChanges
T+514888205ms: eth_getTransactionReceipt
T+514888212ms: eth_getCode
T+514888245ms: eth_uninstallFilter
T+514888248ms: eth_sendTransaction
T+514888276ms:   Transaction: 0x77f087d45cbfa630c0750cdfcadbce9fa407fbc81914b6ba2e60fab3659efe3d
T+514888276ms:   Gas usage: 26981
T+514888276ms:   Block Number: 50
T+514888276ms:   Block Time: Fri Mar 09 2018 20:32:49 GMT+0100 (CET)
T+514888279ms: eth_getTransactionReceipt
T+514897590ms: eth_accounts
T+514897628ms: eth_accounts
T+514904239ms: eth_accounts
T+514904302ms: eth_sendTransaction
T+514904337ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+514904337ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+514904337ms: 
T+514904337ms: TypeError: Cannot read property 'pop' of undefined
T+514904337ms:     at CheckpointTrie.Trie._updateNode (/node_modules/ganache-cli/build/lib.node.js:56237:23)
T+514904337ms:     at /node_modules/ganache-cli/build/lib.node.js:55984:16
T+514904337ms:     at /node_modules/ganache-cli/build/lib.node.js:56320:14
T+514904337ms:     at processNode (/node_modules/ganache-cli/build/lib.node.js:56325:23)
T+514904337ms:     at /node_modules/ganache-cli/build/lib.node.js:56363:11
T+514904337ms:     at /node_modules/ganache-cli/build/lib.node.js:56057:7
T+514904337ms:     at /node_modules/ganache-cli/build/lib.node.js:17623:7
T+514904337ms:     at /node_modules/ganache-cli/build/lib.node.js:22962:16
T+514904337ms:     at /node_modules/ganache-cli/build/lib.node.js:23179:32
T+514904337ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
```

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #666. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
