### ISSUE TITLE
System Error when running Ganache 1.0.2 on linux

### ISSUE THREAD

**Issue by reoxey** [trufflesuite/ganache#410]
PLATFORM: linux
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+2295218ms:   Transaction: 0x1f7138ce6f17a2b56c80338b7cf85dbbff12b18001e72e89d7668e004aa24223
T+2295223ms:   Gas usage: 109409
T+2295232ms:   Block Number: 41
T+2295247ms:   Block Time: Mon Mar 12 2018 12:46:16 GMT+0530 (IST)
T+2295373ms: eth_getTransactionReceipt
T+2295395ms: eth_call
T+2295414ms: eth_blockNumber
T+2295773ms: eth_getBalance
T+2296035ms: eth_getBalance
T+2296053ms: eth_sendTransaction
T+2296106ms:   Transaction: 0x852ff88984e75752295b40e149ec84fd6389e87abe7b63994e424e15fc70f33e
T+2296106ms:   Gas usage: 22201
T+2296116ms:   Block Number: 42
T+2296116ms:   Block Time: Mon Mar 12 2018 12:46:17 GMT+0530 (IST)
T+2296116ms:   Runtime Error: revert
T+2296126ms: eth_getLogs
T+2296134ms: eth_blockNumber
T+2296140ms: eth_sendTransaction
T+2296268ms:   Transaction: 0x7d64d8fdbee600f5493eea3c5cf2a63f322116e4fd2f41f2ea2a294726a56e94
T+2296268ms:   Gas usage: 59523
T+2296268ms:   Block Number: 43
T+2296273ms:   Block Time: Mon Mar 12 2018 12:46:17 GMT+0530 (IST)
T+2296280ms: eth_getTransactionReceipt
T+2340826ms: net_version
T+2340848ms: eth_accounts
T+2340881ms: eth_accounts
T+2340922ms: eth_accounts
T+2340964ms: eth_sendTransaction
T+2341088ms:   Transaction: 0x98202bc850a4a9a7d82394e89fc6f2d784c49e4de83ca8bad5df495f69589179
T+2341094ms:   Contract created: 0xf328c11c4df88d18fcbd30ad38d8b4714f4b33bf
T+2341113ms:   Gas usage: 269607
T+2341123ms:   Block Number: 44
T+2341129ms:   Block Time: Mon Mar 12 2018 12:47:02 GMT+0530 (IST)
T+2341139ms: eth_newBlockFilter
T+2341147ms: eth_getFilterChanges
T+2341162ms: eth_getTransactionReceipt
T+2341167ms: eth_getCode
T+2341183ms: eth_uninstallFilter
T+2341190ms: eth_sendTransaction
T+2341237ms:   Transaction: 0x87b4db9c873e4fa7e5f74466508206f0500ebdc3c935a90f4cdb691233020c68
T+2341237ms:   Gas usage: 41981
T+2341237ms:   Block Number: 45
T+2341241ms:   Block Time: Mon Mar 12 2018 12:47:02 GMT+0530 (IST)
T+2341246ms: eth_getTransactionReceipt
T+2341265ms: eth_accounts
T+2341282ms: eth_sendTransaction
T+2341341ms:   Transaction: 0x70e8f6ff8ea0a88fd5aad844a754e8a83b357a65a05a8034c5affd7e3fca46aa
T+2341341ms:   Contract created: 0xb9b7e0cb2edf5ea031c8b297a5a1fa20379b6a0a
T+2341341ms:   Gas usage: 687290
T+2341355ms:   Block Number: 46
T+2341355ms:   Block Time: Mon Mar 12 2018 12:47:02 GMT+0530 (IST)
T+2341362ms: eth_newBlockFilter
T+2341369ms: eth_getFilterChanges
T+2341374ms: eth_getTransactionReceipt
T+2341386ms: eth_getCode
T+2341397ms: eth_uninstallFilter
T+2341401ms: eth_sendTransaction
T+2341451ms:   Transaction: 0x9cf76c25edbaaf553a783a9d640c7e676375f90c183f354b4a3611cffcaeabf9
T+2341451ms:   Gas usage: 26981
T+2341451ms:   Block Number: 47
T+2341455ms:   Block Time: Mon Mar 12 2018 12:47:02 GMT+0530 (IST)
T+2341461ms: eth_getTransactionReceipt
T+2341488ms: evm_snapshot
T+2341519ms: eth_blockNumber
T+2341582ms: eth_call
T+2341771ms: eth_blockNumber
T+2341805ms: eth_sendTransaction
T+2341815ms:   Transaction: 0xb09260c36f70d18e1ce99336dae45f936dfad44bc81a606d483f92ce4d7abe51
T+2341829ms:   Gas usage: 109409
T+2341833ms:   Block Number: 48
T+2341845ms:   Block Time: Mon Mar 12 2018 12:47:03 GMT+0530 (IST)
T+2341850ms: eth_getTransactionReceipt
T+2341975ms: eth_call
T+2342013ms: eth_blockNumber
T+2342018ms: eth_getBalance
T+2342319ms: eth_getBalance
T+2342332ms: eth_sendTransaction
T+2342440ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+2342440ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_W
T+2342440ms: 
T+2342440ms: TypeError: Cannot read property 'get' of undefined
T+2342440ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+2342440ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+2342440ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+2342440ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+2342440ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+2342440ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+2342440ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+2342440ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+2342440ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+2342440ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #667. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
