### ISSUE TITLE
System Error when running Ganache 1.0.2 on win32

### ISSUE THREAD

**Issue by Artod** [trufflesuite/ganache#416]
PLATFORM: win32
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+3135930ms: eth_newBlockFilter
T+3135936ms: eth_getFilterChanges
T+3135948ms: eth_getTransactionReceipt
T+3135961ms: eth_getCode
T+3136005ms: eth_uninstallFilter
T+3136005ms: eth_sendTransaction
T+3136009ms: eth_sendTransaction
T+3136052ms:   Transaction: 0xb603f766c25be75e6b0826ef15aec29503695d5f43d933eb557338113835a486
T+3136052ms:   Gas usage: 26981
T+3136052ms:   Block Number: 241
T+3136052ms:   Block Time: Wed Mar 14 2018 00:00:56 GMT-0400 (Восточное время США (лето))
T+3136059ms: eth_getTransactionReceipt
T+3136311ms:   Transaction: 0x6cab6ff427721cf0997c5345c6988bea1a7b8d54517809c9eb18c7f25625d546
T+3136311ms:   Contract created: 0x4ebf5dee668b0d71be8ecbeb98ccc44cdbe8ef85
T+3136311ms:   Gas usage: 3039762
T+3136311ms:   Block Number: 242
T+3136311ms:   Block Time: Wed Mar 14 2018 00:00:56 GMT-0400 (Восточное время США (лето))
T+3136318ms: eth_newBlockFilter
T+3136323ms: eth_getFilterChanges
T+3136333ms: eth_getTransactionReceipt
T+3136348ms: eth_getCode
T+3136432ms: eth_uninstallFilter
T+3143623ms: net_version
T+3143633ms: eth_accounts
T+3143694ms: eth_accounts
T+3143781ms: eth_accounts
T+3143814ms: eth_sendTransaction
T+3143856ms:   Transaction: 0x5cc9aabba30bf7e76ddb90fd709742ebc8e59bb93bf747da4c781a2f1c06a8a0
T+3143856ms:   Contract created: 0x81babbf5199ceb5c9ad90ebe3ed4167201beedd3
T+3143856ms:   Gas usage: 268535
T+3143856ms:   Block Number: 243
T+3143856ms:   Block Time: Wed Mar 14 2018 00:01:04 GMT-0400 (Восточное время США (лето))
T+3143859ms: eth_newBlockFilter
T+3143866ms: eth_getFilterChanges
T+3143875ms: eth_getTransactionReceipt
T+3143883ms: eth_getCode
T+3143896ms: eth_uninstallFilter
T+3143902ms: eth_sendTransaction
T+3143939ms:   Transaction: 0x91923796aa251c998ca74510922aef3c664bf22fa9ab29ea75fe0ef74ef23be2
T+3143939ms:   Gas usage: 41981
T+3143939ms:   Block Number: 244
T+3143939ms:   Block Time: Wed Mar 14 2018 00:01:04 GMT-0400 (Восточное время США (лето))
T+3143943ms: eth_getTransactionReceipt
T+3143956ms: eth_accounts
T+3144009ms: eth_sendTransaction
T+3144071ms:   Transaction: 0x6bdedabe9d3a1c6641fa12c83074a8727e106bf67b79f494e1b8db6090cca1c7
T+3144071ms:   Contract created: 0x7419f8f92a40d72850267ce81dc392acd2540a0f
T+3144071ms:   Gas usage: 1402909
T+3144071ms:   Block Number: 245
T+3144071ms:   Block Time: Wed Mar 14 2018 00:01:04 GMT-0400 (Восточное время США (лето))
T+3144105ms: eth_newBlockFilter
T+3144112ms: eth_getFilterChanges
T+3144176ms: eth_getTransactionReceipt
T+3144185ms: eth_getCode
T+3144192ms: eth_uninstallFilter
T+3144200ms: eth_sendTransaction
T+3144205ms: eth_sendTransaction
T+3144238ms: C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:63898
T+3144238ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&
T+3144238ms: 
T+3144238ms: TypeError: Cannot read property 'get' of undefined
T+3144238ms:     at dbGet (C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:56029:7)
T+3144238ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:17614:5
T+3144238ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:23091:20
T+3144238ms:     at iterate (C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:23172:13)
T+3144238ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:23184:29
T+3144238ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:22954:16
T+3144238ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:17619:7
T+3144238ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:56034:9
T+3144238ms:     at dispatchError (C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:36358:36)
T+3144238ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:22744:14
```

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #667. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
