### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by patmaddox** [trufflesuite/ganache#419]
I have no idea what caused this. Ganache was working fine until just a minute ago.

PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+0ms: Starting server with configuration: {"hostname":"127.0.0.1","mnemonic":"candy maple cake sugar pudding cream honey rich smooth crumble sweet treat","network_id":5777,"port":8545,"total_accounts":10,"unlocked_accounts":[]}
T+240ms: Ganache started successfully!
T+240ms: Waiting for requests...
T+2541ms: eth_getBlockByNumber
T+4145ms: eth_accounts
T+4181ms: eth_sendTransaction
T+4260ms:   Transaction: 0x85566b64f9730f8ae845fb4f794d76255251a551683ed45d118c373fe109900c
T+4260ms:   Contract created: 0x8cdaf0cd259887258bc13a92c0a6da92698644c0
T+4260ms:   Gas usage: 269543
T+4263ms:   Block Number: 1
T+4263ms:   Block Time: Wed Mar 14 2018 11:35:29 GMT-0600 (MDT)
T+4267ms: eth_newBlockFilter
T+4272ms: eth_getFilterChanges
T+4278ms: eth_getTransactionReceipt
T+4286ms: eth_getCode
T+4299ms: eth_uninstallFilter
T+4304ms: eth_sendTransaction
T+4344ms:   Transaction: 0xd7bc86d31bee32fa3988f1c1eabce403a1b5d570340a3a9cdba53a472ee8c956
T+4344ms:   Gas usage: 41981
T+4344ms:   Block Number: 2
T+4347ms:   Block Time: Wed Mar 14 2018 11:35:29 GMT-0600 (MDT)
T+4349ms: eth_getTransactionReceipt
T+4353ms: eth_accounts
T+4372ms: eth_sendTransaction
T+4410ms:   Transaction: 0xd59c8dd846e84a298c864cfa96d2ec6b9fa635ac31252d2baec7ef97d87cdd8d
T+4410ms:   Contract created: 0x345ca3e014aaf5dca488057592ee47305d9b3e10
T+4410ms:   Gas usage: 401014
T+4410ms:   Block Number: 3
T+4410ms:   Block Time: Wed Mar 14 2018 11:35:29 GMT-0600 (MDT)
T+4412ms: eth_newBlockFilter
T+4417ms: eth_getFilterChanges
T+4421ms: eth_getTransactionReceipt
T+4428ms: eth_getCode
T+4438ms: eth_uninstallFilter
T+4438ms: eth_sendTransaction
T+4478ms:   Transaction: 0xf36163615f41ef7ed8f4a8f192149a0bf633fe1a2398ce001bf44c43dc7bdda0
T+4478ms:   Gas usage: 26981
T+4478ms:   Block Number: 4
T+4478ms:   Block Time: Wed Mar 14 2018 11:35:29 GMT-0600 (MDT)
T+4484ms: eth_getTransactionReceipt
T+5709ms: eth_accounts
T+5715ms: net_version
T+5724ms: eth_call
T+5728ms: eth_getBalance
T+5738ms: eth_getBalance
T+5743ms: eth_getBalance
T+5749ms: eth_getBalance
T+5756ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+5756ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+5756ms: 
T+5756ms: TypeError: Cannot read property 'get' of undefined
T+5756ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+5756ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+5756ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+5756ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+5756ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+5756ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+5756ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+5756ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+5756ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+5756ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #667. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
