### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by bachloxo** [trufflesuite/ganache#421]
PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+262ms: Ganache started successfully!
T+262ms: Waiting for requests...
T+171836ms: net_version
T+171844ms: eth_accounts
T+171915ms: eth_accounts
T+176475ms: eth_accounts
T+176555ms: eth_sendTransaction
T+176611ms:   Transaction: 0x386d4a1e26ae4b5b8c387ba3abd286e3104c105d97039008eae4352539951448
T+176611ms:   Contract created: 0x8cdaf0cd259887258bc13a92c0a6da92698644c0
T+176611ms:   Gas usage: 269607
T+176611ms:   Block Number: 1
T+176615ms:   Block Time: Thu Mar 15 2018 16:08:10 GMT+0700 (+07)
T+176618ms: eth_newBlockFilter
T+176620ms: eth_getFilterChanges
T+176626ms: eth_getTransactionReceipt
T+176632ms: eth_getCode
T+176643ms: eth_uninstallFilter
T+176646ms: eth_sendTransaction
T+176684ms:   Transaction: 0x7adf6b662f5ca3e20f2a7dccca42ea107a451807bfd0426031299396eef85a7d
T+176684ms:   Gas usage: 41981
T+176684ms:   Block Number: 2
T+176688ms:   Block Time: Thu Mar 15 2018 16:08:10 GMT+0700 (+07)
T+176692ms: eth_getTransactionReceipt
T+176696ms: eth_accounts
T+176779ms: eth_sendTransaction
T+176812ms:   Transaction: 0x9c64440a7791a36c2d2af6e2c27fc6a36ee0d1f9a2a4e5e2aed134d328797c22
T+176812ms:   Gas usage: 26981
T+176812ms:   Block Number: 3
T+176812ms:   Block Time: Thu Mar 15 2018 16:08:10 GMT+0700 (+07)
T+176815ms: eth_getTransactionReceipt
T+178267ms: eth_getBlockByNumber
T+178539ms: evm_snapshot
T+178796ms: eth_blockNumber
T+178922ms: eth_blockNumber
T+178931ms: eth_blockNumber
T+179043ms: eth_getBlockByNumber
T+179055ms: net_version
T+179058ms: eth_sendTransaction
T+179134ms:   Transaction: 0x3aa913ac15e4e080912e638e9f5dfbcc9e3da5ae70645529ab8264967f5cb973
T+179134ms:   Contract created: 0xf25186b5081ff5ce73482ad761db0eb0d25abfbf
T+179134ms:   Gas usage: 2042616
T+179134ms:   Block Number: 4
T+179134ms:   Block Time: Thu Mar 15 2018 16:08:13 GMT+0700 (+07)
T+179137ms: eth_newBlockFilter
T+179141ms: eth_getFilterChanges
T+179146ms: eth_getTransactionReceipt
T+179152ms: eth_getCode
T+179158ms: eth_uninstallFilter
T+179161ms: net_version
T+179166ms: eth_sendTransaction
T+179234ms:   Transaction: 0xf0cbc69eb15cab3fa0872ddf879617a728407802a5c3db17fad94d54c0fcf214
T+179234ms:   Contract created: 0x8f0483125fcb9aaaefa9209d8e9d7b9c8b9fb90f
T+179234ms:   Gas usage: 2706679
T+179234ms:   Block Number: 5
T+179234ms:   Block Time: Thu Mar 15 2018 16:08:13 GMT+0700 (+07)
T+179238ms: eth_newBlockFilter
T+179240ms: eth_getFilterChanges
T+179245ms: eth_getTransactionReceipt
T+179250ms: eth_getCode
T+179254ms: eth_uninstallFilter
T+179257ms: net_version
T+179260ms: eth_sendTransaction
T+179295ms:   Transaction: 0xe1283197eea0255a2ea7da6f5738870a469118bb56557beedcbaf7c916d5917a
T+179295ms:   Gas usage: 37627
T+179295ms:   Block Number: 6
T+179295ms:   Block Time: Thu Mar 15 2018 16:08:13 GMT+0700 (+07)
T+179298ms: eth_getTransactionReceipt
T+179305ms: net_version
T+179308ms: eth_sendTransaction
T+179332ms:   Transaction: 0x0c2c1441a7a07edfa55290b12ff38598f2a5f6b7385bf54cb6d605894a28f61a
T+179332ms:   Gas usage: 28833
T+179332ms:   Block Number: 7
T+179332ms:   Block Time: Thu Mar 15 2018 16:08:13 GMT+0700 (+07)
T+179337ms: eth_getTransactionReceipt
T+179340ms: net_version
T+179373ms: eth_sendTransaction
T+179393ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+179393ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+179393ms: 
T+179393ms: TypeError: Cannot read property 'get' of undefined
T+179393ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+179393ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+179393ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+179393ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+179393ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+179393ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+179393ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+179393ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+179393ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+179393ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #667. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
