### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by edanisko** [trufflesuite/ganache#424]
PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+334953ms: eth_getBalance
T+334976ms: eth_getTransactionByHash
T+337093ms: eth_gasPrice
T+337112ms: eth_getBlockByNumber
T+337134ms: eth_estimateGas
T+342975ms: eth_getBlockByNumber
T+342983ms: eth_getBlockByNumber
T+342990ms: eth_getBalance
T+342996ms: eth_getBlockByNumber
T+343001ms: eth_getBalance
T+343008ms: eth_getBlockByNumber
T+343013ms: eth_getBalance
T+343028ms: eth_sendRawTransaction
T+343049ms: eth_getTransactionByHash
T+345354ms: eth_getTransactionCount
T+345419ms: eth_sendRawTransaction
T+345596ms: eth_getBlockByNumber
T+345612ms: eth_getTransactionReceipt
T+345620ms: eth_call
T+348453ms: eth_getTransactionReceipt
T+349448ms: eth_getTransactionReceipt
T+350451ms: eth_getTransactionReceipt
T+351026ms: eth_getBlockByNumber
T+351039ms: eth_getBlockByNumber
T+351048ms: eth_getBalance
T+351797ms: eth_getTransactionReceipt
T+352446ms: eth_getTransactionReceipt
T+353452ms: eth_getTransactionReceipt
T+354034ms: eth_gasPrice
T+354054ms: eth_getBlockByNumber
T+354077ms: eth_estimateGas
T+354983ms: eth_getTransactionReceipt
T+355641ms: eth_getTransactionReceipt
T+356446ms: eth_getTransactionReceipt
T+356555ms: eth_getTransactionCount
T+356588ms: eth_sendRawTransaction
T+356707ms: eth_getBlockByNumber
T+356713ms: eth_getTransactionReceipt
T+356722ms: eth_call
T+357818ms: eth_getTransactionReceipt
T+357823ms: eth_getTransactionReceipt
T+358444ms: eth_getTransactionReceipt
T+358873ms: eth_getTransactionReceipt
T+359093ms: eth_getBlockByNumber
T+359105ms: eth_getBlockByNumber
T+359114ms: eth_getBalance
T+359122ms: eth_getBlockByNumber
T+359129ms: eth_getBalance
T+359187ms: eth_sendRawTransaction
T+359202ms: eth_getTransactionByHash
T+359208ms: eth_getTransactionByHash
T+359213ms: eth_getTransactionByHash
T+359899ms: eth_getTransactionReceipt
T+359906ms: eth_getTransactionReceipt
T+361362ms: net_version
T+361367ms: net_version
T+361373ms: net_version
T+361457ms: eth_call
T+361457ms: eth_call
T+361463ms: eth_call
T+361463ms: eth_call
T+361463ms: eth_call
T+361470ms: eth_call
T+361487ms: eth_call
T+367168ms: eth_getBlockByNumber
T+367178ms: eth_getBlockByNumber
T+367182ms: eth_getBalance
T+367187ms: eth_getBlockByNumber
T+367192ms: eth_getBalance
T+367263ms: eth_sendRawTransaction
T+367267ms: eth_sendRawTransaction
T+367298ms: eth_getTransactionByHash
T+367305ms: eth_getTransactionByHash
T+367305ms: eth_getTransactionByHash
T+375254ms: eth_getBlockByNumber
T+375269ms: eth_getBlockByNumber
T+375284ms: eth_getBalance
T+375355ms: eth_sendRawTransaction
T+375361ms: eth_sendRawTransaction
T+379364ms: eth_gasPrice
T+379390ms: eth_getBlockByNumber
T+379406ms: eth_getCode
T+379427ms: eth_estimateGas
T+383328ms: eth_getBlockByNumber
T+383339ms: eth_getBlockByNumber
T+383345ms: eth_getBalance
T+383357ms: eth_getBlockByNumber
T+383364ms: eth_getBalance
T+383403ms: eth_sendRawTransaction
T+383468ms: eth_getTransactionByHash
T+383476ms: eth_getTransactionByHash
T+383482ms: eth_getTransactionByHash
T+385862ms: eth_getTransactionCount
T+385919ms: eth_sendRawTransaction
T+386117ms: eth_getBlockByNumber
T+386125ms: eth_getTransactionReceipt
T+386134ms: eth_call
T+390299ms: net_version
T+390306ms: net_version
T+390314ms: net_version
T+390556ms: eth_call
T+390564ms: eth_call
T+390572ms: eth_call
T+390580ms: eth_call
T+390590ms: eth_call
T+390599ms: eth_call
T+390605ms: eth_call
T+391531ms: eth_getBlockByNumber
T+391535ms: eth_getBlockByNumber
T+391541ms: eth_getBalance
T+391546ms: eth_sendRawTransaction
T+396814ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+396814ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+396814ms: 
T+396814ms: TypeError: Cannot read property 'pop' of undefined
T+396814ms:     at CheckpointTrie.Trie._updateNode (/node_modules/ganache-cli/build/lib.node.js:56237:23)
T+396814ms:     at /node_modules/ganache-cli/build/lib.node.js:55984:16
T+396814ms:     at /node_modules/ganache-cli/build/lib.node.js:56320:14
T+396814ms:     at processNode (/node_modules/ganache-cli/build/lib.node.js:56325:23)
T+396814ms:     at /node_modules/ganache-cli/build/lib.node.js:56316:5
T+396814ms:     at /node_modules/ganache-cli/build/lib.node.js:56057:7
T+396814ms:     at /node_modules/ganache-cli/build/lib.node.js:17623:7
T+396814ms:     at /node_modules/ganache-cli/build/lib.node.js:22962:16
T+396814ms:     at /node_modules/ganache-cli/build/lib.node.js:23179:32
T+396814ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
```

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #666. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
