### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by cd4761** [trufflesuite/ganache#426]
PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+44984ms:   Block Time: Fri Mar 16 2018 11:39:31 GMT+0900 (KST)
T+44989ms: eth_getTransactionReceipt
T+45070ms: eth_accounts
T+45074ms: eth_sendTransaction
T+45175ms:   Transaction: 0x2ad71f63499f01e34bdc7eb8071918d5085504dbf6f0221268f9067c2d2f9b3d
T+45175ms:   Gas usage: 190743
T+45175ms:   Block Number: 2
T+45175ms:   Block Time: Fri Mar 16 2018 11:39:31 GMT+0900 (KST)
T+45179ms: eth_accounts
T+45189ms: eth_sendTransaction
T+45286ms:   Transaction: 0x896cfe160d01d8521b8a180b229ffbabc5b41b804a13b6bbce2624e26be3b480
T+45286ms:   Gas usage: 190807
T+45289ms:   Block Number: 3
T+45289ms:   Block Time: Fri Mar 16 2018 11:39:31 GMT+0900 (KST)
T+45292ms: eth_accounts
T+45300ms: eth_sendTransaction
T+45362ms:   Transaction: 0xa8fcf7c9bb8c6ee97e1eba73284968c2e72fcf6aeb09b49c3621fd248e5b10ec
T+45362ms:   Gas usage: 190807
T+45362ms:   Block Number: 4
T+45362ms:   Block Time: Fri Mar 16 2018 11:39:31 GMT+0900 (KST)
T+45365ms: eth_accounts
T+45375ms: eth_sendTransaction
T+45430ms:   Transaction: 0x5fbdc999274a5086c60295c6c22968b10e973586100eff431e85a83d9ef5034b
T+45430ms:   Gas usage: 190807
T+45430ms:   Block Number: 5
T+45430ms:   Block Time: Fri Mar 16 2018 11:39:31 GMT+0900 (KST)
T+45434ms: eth_accounts
T+45442ms: eth_sendTransaction
T+45517ms:   Transaction: 0x2e7c5e75406ad2c469330bca2063346e6d232b9770a496c1e56bfcff903adbfd
T+45517ms:   Gas usage: 190807
T+45517ms:   Block Number: 6
T+45520ms:   Block Time: Fri Mar 16 2018 11:39:31 GMT+0900 (KST)
T+45523ms: eth_accounts
T+45530ms: eth_sendTransaction
T+45627ms:   Transaction: 0xa14e7b7c2d996855f84139d779594cc50fdff7659bf106d5d35c0c82dc015140
T+45627ms:   Gas usage: 190807
T+45627ms:   Block Number: 7
T+45627ms:   Block Time: Fri Mar 16 2018 11:39:32 GMT+0900 (KST)
T+45630ms: eth_accounts
T+45639ms: eth_sendTransaction
T+45697ms:   Transaction: 0xb3f35bd04fcf4f36e9a6ee17938b40fb884f6ce4ee995524d03db20d7379a599
T+45697ms:   Gas usage: 207029
T+45697ms:   Block Number: 8
T+45697ms:   Block Time: Fri Mar 16 2018 11:39:32 GMT+0900 (KST)
T+45700ms: eth_accounts
T+45710ms: eth_sendTransaction
T+45774ms:   Transaction: 0x5fdb0eb19fdd09741d458e94746412064ed434f525556c95d91e6168b94bd042
T+45774ms:   Gas usage: 190807
T+45774ms:   Block Number: 9
T+45774ms:   Block Time: Fri Mar 16 2018 11:39:32 GMT+0900 (KST)
T+45777ms: eth_accounts
T+45785ms: eth_sendTransaction
T+45839ms:   Transaction: 0xc6a037e915334df258506c2986c4dc9830334dd6db7dbb9e1adf8ccad1e454d4
T+45839ms:   Gas usage: 190807
T+45839ms:   Block Number: 10
T+45839ms:   Block Time: Fri Mar 16 2018 11:39:32 GMT+0900 (KST)
T+45861ms: eth_accounts
T+45873ms: eth_sendTransaction
T+45930ms:   Transaction: 0x9025c061b5236ff8a7d69afa4d99061bc6a765a7f10e729e229ffbd13ab9ba8b
T+45930ms:   Gas usage: 190807
T+45930ms:   Block Number: 11
T+45930ms:   Block Time: Fri Mar 16 2018 11:39:32 GMT+0900 (KST)
T+45933ms: eth_accounts
T+45942ms: eth_sendTransaction
T+45995ms:   Transaction: 0x6ec97bbc23d68e3f5dddf53609ec1ab0e1f2485155ebc809de40583619012386
T+45995ms:   Gas usage: 190743
T+45995ms:   Block Number: 12
T+45995ms:   Block Time: Fri Mar 16 2018 11:39:32 GMT+0900 (KST)
T+45999ms: eth_accounts
T+46008ms: eth_sendTransaction
T+46083ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+46083ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+46083ms: 
T+46083ms: TypeError: Cannot read property 'get' of undefined
T+46083ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+46083ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+46083ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+46083ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+46083ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+46083ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+46083ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+46083ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+46083ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+46083ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #667. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
