### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by liaoquanlei** [trufflesuite/ganache#428]
PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+1099781ms: eth_getTransactionReceipt
T+1099843ms: eth_accounts
T+1099857ms: eth_sendTransaction
T+1099912ms:   Transaction: 0xfba0f36c10015807c7efb2458b0c5b40d615c7239988a3bbb78811ddb5a1deb8
T+1099912ms:   Contract created: 0x9f544a3fc3d1045e6ec49d4ecef6dcd700457165
T+1099912ms:   Gas usage: 149942
T+1099912ms:   Block Number: 35
T+1099912ms:   Block Time: Fri Mar 16 2018 19:25:27 GMT+0800 (CST)
T+1099925ms: eth_newBlockFilter
T+1099938ms: eth_getFilterChanges
T+1099949ms: eth_getTransactionReceipt
T+1099955ms: eth_getCode
T+1151627ms: net_version
T+1151632ms: eth_accounts
T+1151702ms: eth_call
T+1151722ms: eth_call
T+1151735ms: eth_accounts
T+1151743ms: eth_sendTransaction
T+1151769ms:   Transaction: 0x481224b4a556666ee4e151e13cfd8da55709d39a7212374dd7cf0bab013e5049
T+1151769ms:   Contract created: 0x9f544a3fc3d1045e6ec49d4ecef6dcd700457165
T+1151769ms:   Gas usage: 269607
T+1151769ms:   Block Number: 36
T+1151769ms:   Block Time: Fri Mar 16 2018 19:26:19 GMT+0800 (CST)
T+1151771ms: eth_newBlockFilter
T+1151774ms: eth_getFilterChanges
T+1151782ms: eth_getTransactionReceipt
T+1151789ms: eth_getCode
T+1151803ms: eth_uninstallFilter
T+1151806ms: eth_sendTransaction
T+1151817ms:   Transaction: 0xac57b682631e1cb0799324f50f55b248f9616a3830c0e686647085a0e22e9fce
T+1151817ms:   Gas usage: 21464
T+1151817ms:   Block Number: 37
T+1151817ms:   Block Time: Fri Mar 16 2018 19:26:19 GMT+0800 (CST)
T+1151824ms: eth_getTransactionReceipt
T+1151836ms: eth_accounts
T+1151844ms: eth_sendTransaction
T+1151872ms:   Transaction: 0xe00ef1bfa4d461739277287cdd2590533b74044326bca848371705ecb87bcd77
T+1151872ms:   Contract created: 0x8273e4b8ed6c78e252a9fca5563adfcc75c91b2a
T+1151872ms:   Gas usage: 149942
T+1151872ms:   Block Number: 38
T+1151872ms:   Block Time: Fri Mar 16 2018 19:26:19 GMT+0800 (CST)
T+1151875ms: eth_newBlockFilter
T+1151879ms: eth_getFilterChanges
T+1151885ms: eth_getTransactionReceipt
T+1151895ms: eth_getCode
T+1151907ms: eth_uninstallFilter
T+1151917ms: eth_sendTransaction
T+1151938ms:   Transaction: 0x94cf24b62478682425faa299a65d0cf89145405f1443f1cd1c85b3ede893c03a
T+1151938ms:   Gas usage: 21464
T+1151938ms:   Block Number: 39
T+1151938ms:   Block Time: Fri Mar 16 2018 19:26:19 GMT+0800 (CST)
T+1151946ms: eth_getTransactionReceipt
T+1172942ms: eth_call
T+1195741ms: net_version
T+1195747ms: eth_accounts
T+1195764ms: eth_call
T+1195782ms: eth_call
T+1195798ms: eth_accounts
T+1195811ms: eth_sendTransaction
T+1195855ms:   Transaction: 0x4bcc665fbb5d1d39a1f55f3f5eb57bb3437c72aa9868fe41958a6cba2aae0753
T+1195855ms:   Contract created: 0x74e3fc764c2474f25369b9d021b7f92e8441a2dc
T+1195855ms:   Gas usage: 269607
T+1195855ms:   Block Number: 40
T+1195855ms:   Block Time: Fri Mar 16 2018 19:27:03 GMT+0800 (CST)
T+1195858ms: eth_newBlockFilter
T+1195861ms: eth_getFilterChanges
T+1195871ms: eth_getTransactionReceipt
T+1195877ms: eth_getCode
T+1195891ms: eth_uninstallFilter
T+1195898ms: eth_sendTransaction
T+1195914ms:   Transaction: 0x2e6ab872ff6a97b3e1d8fe2930ad972f89ec7283bc9d1dc9be761b0efbbcd98b
T+1195914ms:   Gas usage: 21464
T+1195914ms:   Block Number: 41
T+1195914ms:   Block Time: Fri Mar 16 2018 19:27:03 GMT+0800 (CST)
T+1195920ms: eth_getTransactionReceipt
T+1195954ms: eth_accounts
T+1195964ms: eth_sendTransaction
T+1196011ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+1196011ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+1196011ms: 
T+1196011ms: TypeError: Cannot read property 'get' of undefined
T+1196011ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+1196011ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+1196011ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+1196011ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+1196011ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+1196011ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+1196011ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+1196011ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+1196011ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+1196011ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #667. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
