### ISSUE TITLE
System Error when running Ganache 1.0.2 on linux ubuntu16.04

### ISSUE THREAD

**Issue by zemingyu** [trufflesuite/ganache#430]
PLATFORM: linux
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+104434ms:   Block Time: Sun Mar 18 2018 17:30:31 GMT+1100 (AEDT)
T+104443ms: eth_getTransactionReceipt
T+104449ms: eth_sendTransaction
T+104479ms:   Transaction: 0x4ca0a6152b5e883192f20c501f29bddcc52e3cd7696e4c8bad7be55f317ab0b7
T+104479ms:   Gas usage: 28883
T+104479ms:   Block Number: 62
T+104484ms:   Block Time: Sun Mar 18 2018 17:30:31 GMT+1100 (AEDT)
T+104496ms: eth_getTransactionReceipt
T+104499ms: eth_sendTransaction
T+104529ms:   Transaction: 0xf9cb82cb8854eaec3b3465f3dcf8dec82e9cb64510d0f4c40e413c18da079641
T+104534ms:   Gas usage: 29251
T+104555ms:   Block Number: 63
T+104558ms:   Block Time: Sun Mar 18 2018 17:30:31 GMT+1100 (AEDT)
T+104562ms: eth_getTransactionReceipt
T+104568ms: eth_call
T+104583ms: eth_blockNumber
T+104595ms: eth_sendTransaction
T+104705ms:   Transaction: 0x86ecfd27e12dc16ecf533c94b758c1d697869c293310a4b3188cbf014ca1d09e
T+104708ms:   Contract created: 0xa03ff23ad9f0b66b139a5f3ec303f6db9d933363
T+104712ms:   Gas usage: 1591054
T+104715ms:   Block Number: 64
T+104718ms:   Block Time: Sun Mar 18 2018 17:30:31 GMT+1100 (AEDT)
T+104725ms: eth_newBlockFilter
T+104733ms: eth_getFilterChanges
T+104740ms: eth_getTransactionReceipt
T+104744ms: eth_getCode
T+104748ms: eth_uninstallFilter
T+104751ms: eth_sendTransaction
T+104756ms:   Transaction: 0xfac5fa08d31b7e50ecb3a69d8cedae0029b0d3350cbe0c74784cd8e026c69471
T+104760ms:   Gas usage: 28635
T+104763ms:   Block Number: 65
T+104769ms:   Block Time: Sun Mar 18 2018 17:30:31 GMT+1100 (AEDT)
T+104774ms: eth_getTransactionReceipt
T+104778ms: eth_sendTransaction
T+104833ms:   Transaction: 0x10af6f4cbfe78c886f3375368876280a41d8e1a1dd66301dee5487ac0ce28f44
T+104838ms:   Gas usage: 28883
T+104842ms:   Block Number: 66
T+104845ms:   Block Time: Sun Mar 18 2018 17:30:31 GMT+1100 (AEDT)
T+104850ms: eth_getTransactionReceipt
T+104859ms: eth_sendTransaction
T+104871ms:   Transaction: 0xb894cc36b59909f132df9f4db306beb896ec47eb9447c5942bb2e0ccf9473d2f
T+104871ms:   Gas usage: 29251
T+104871ms:   Block Number: 67
T+104871ms:   Block Time: Sun Mar 18 2018 17:30:31 GMT+1100 (AEDT)
T+104879ms: eth_getTransactionReceipt
T+104884ms: eth_call
T+104901ms: eth_blockNumber
T+104906ms: eth_sendTransaction
T+104951ms:   Transaction: 0x990d3dd120b732e64abfa81c2d8446d7cbd26a2f19744f70f180a6b48cb34ef2
T+104951ms:   Contract created: 0x5e4c33acd1ce7131ec6ddfdfc8cb140863a8d2f7
T+104951ms:   Gas usage: 1591054
T+104951ms:   Block Number: 68
T+104958ms:   Block Time: Sun Mar 18 2018 17:30:31 GMT+1100 (AEDT)
T+104962ms: eth_newBlockFilter
T+104968ms: eth_getFilterChanges
T+104975ms: eth_getTransactionReceipt
T+104984ms: eth_getCode
T+104988ms: eth_uninstallFilter
T+104994ms: eth_sendTransaction
T+105018ms:   Transaction: 0xab18e6081da3282a8451873e35b19e97b4daf340fb9364ca40ff75bd9a7d6015
T+105018ms:   Gas usage: 28635
T+105018ms:   Block Number: 69
T+105018ms:   Block Time: Sun Mar 18 2018 17:30:32 GMT+1100 (AEDT)
T+105025ms: eth_getTransactionReceipt
T+105030ms: eth_sendTransaction
T+105199ms:   Transaction: 0xd16ba3e87706e9099582eab0ad291077862c306a8c4e9be0528573caad5eee42
T+105210ms:   Gas usage: 28883
T+105214ms:   Block Number: 70
T+105218ms:   Block Time: Sun Mar 18 2018 17:30:32 GMT+1100 (AEDT)
T+105225ms: eth_getTransactionReceipt
T+105228ms: eth_sendTransaction
T+105236ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+105236ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_W
T+105236ms: 
T+105236ms: TypeError: Cannot read property 'get' of undefined
T+105236ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+105236ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+105236ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+105236ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+105236ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+105236ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+105236ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+105236ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+105236ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+105236ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #667. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
