### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by JeanoLee** [trufflesuite/ganache#435]
PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+2145826ms:   Block Time: Tue Mar 20 2018 11:38:25 GMT+0900 (KST)
T+2145845ms:   Transaction: 0x76621d33e507cdec9006d6a73c7853840af2f0db56ebf6b36c40ce00702ad1dc
T+2145845ms:   Gas usage: 14538
T+2145845ms:   Block Number: 223
T+2145845ms:   Block Time: Tue Mar 20 2018 11:38:25 GMT+0900 (KST)
T+2145847ms: eth_call
T+2145858ms: eth_call
T+2145868ms: eth_call
T+2145879ms: eth_call
T+2145889ms: eth_call
T+2145899ms: eth_call
T+2145911ms: eth_call
T+2145922ms: eth_getLogs
T+2145929ms: eth_blockNumber
T+2145932ms: eth_sendTransaction
T+2145976ms:   Transaction: 0xc181fadb31da92db01c8ea380d175d729e8d018ceb6057d293e847f22bc20221
T+2145976ms:   Contract created: 0xb14b6519d62b3c68c4f378703eaf23283104a377
T+2145976ms:   Gas usage: 401096
T+2145976ms:   Block Number: 224
T+2145976ms:   Block Time: Tue Mar 20 2018 11:38:25 GMT+0900 (KST)
T+2145978ms: eth_newBlockFilter
T+2145981ms: eth_getFilterChanges
T+2145988ms: eth_getTransactionReceipt
T+2145993ms: eth_getCode
T+2145996ms: eth_uninstallFilter
T+2145998ms: eth_call
T+2146010ms: eth_sendTransaction
T+2146010ms: eth_sendTransaction
T+2146012ms: eth_sendTransaction
T+2146012ms: eth_sendTransaction
T+2146014ms: eth_sendTransaction
T+2146015ms: eth_sendTransaction
T+2146015ms: eth_sendTransaction
T+2146030ms:   Transaction: 0x9ed038e9eff49fbd1bb0daedf4482375aa87c76079861db0b520e0de46953a4d
T+2146030ms:   Gas usage: 105140
T+2146030ms:   Block Number: 225
T+2146030ms:   Block Time: Tue Mar 20 2018 11:38:25 GMT+0900 (KST)
T+2146049ms:   Transaction: 0x8bf5925a3a81cfdd920ebf8bef506f002c939644dc4baf41d4120fad0c0ede77
T+2146049ms:   Gas usage: 90140
T+2146049ms:   Block Number: 226
T+2146049ms:   Block Time: Tue Mar 20 2018 11:38:25 GMT+0900 (KST)
T+2146070ms:   Transaction: 0x45cda8296385968f72384545373bd4edc7eae87d4e8e2b9e34d57eaeda6bc730
T+2146070ms:   Gas usage: 90140
T+2146070ms:   Block Number: 227
T+2146070ms:   Block Time: Tue Mar 20 2018 11:38:25 GMT+0900 (KST)
T+2146090ms:   Transaction: 0x04f998cf43b2f9bd090f6e3b2e3bd8a277d3946dc1e9c03f074db5cf5ca5867e
T+2146090ms:   Gas usage: 90140
T+2146090ms:   Block Number: 228
T+2146090ms:   Block Time: Tue Mar 20 2018 11:38:25 GMT+0900 (KST)
T+2146109ms:   Transaction: 0x5d689c3db799c9b12d1bf01d088266f2171f714a26da24eaca04ed5c4b7003dd
T+2146109ms:   Gas usage: 90140
T+2146109ms:   Block Number: 229
T+2146109ms:   Block Time: Tue Mar 20 2018 11:38:25 GMT+0900 (KST)
T+2146133ms:   Transaction: 0x56ad2625ec6c102b896db618dc6990d15d5bcdba932a55915c22b4b8af9443ad
T+2146133ms:   Gas usage: 90140
T+2146133ms:   Block Number: 230
T+2146133ms:   Block Time: Tue Mar 20 2018 11:38:25 GMT+0900 (KST)
T+2146154ms:   Transaction: 0x18efc538d2776f665d6e7ef5dd6987f200d70b4db165bda19854975921d772f2
T+2146154ms:   Gas usage: 90140
T+2146154ms:   Block Number: 231
T+2146156ms:   Block Time: Tue Mar 20 2018 11:38:25 GMT+0900 (KST)
T+2146157ms: eth_call
T+2146172ms: eth_call
T+2146183ms: eth_call
T+2146194ms: eth_call
T+2146204ms: eth_call
T+2146214ms: eth_call
T+2146227ms: eth_call
T+2146237ms: eth_call
T+2146259ms: eth_call
T+2146261ms: eth_call
T+2146263ms: eth_call
T+2146263ms: eth_call
T+2146265ms: eth_call
T+2146266ms: eth_call
T+2146266ms: eth_call
T+2146277ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+2146277ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+2146277ms: 
T+2146277ms: TypeError: Cannot read property 'get' of undefined
T+2146277ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+2146277ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+2146277ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+2146277ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+2146277ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+2146277ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+2146277ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+2146277ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+2146277ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+2146277ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #667. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
