### ISSUE TITLE
System Error when running Ganache 1.0.2 on win32

### ISSUE THREAD

**Issue by DebojyotiBasuDAir** [trufflesuite/ganache#436]
PLATFORM: win32
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+0ms: Starting server with configuration: {"hostname":"127.0.0.1","mnemonic":"candy maple cake sugar pudding cream honey rich smooth crumble sweet treat","network_id":5777,"port":7545,"total_accounts":10,"unlocked_accounts":[]}
T+288ms: Ganache started successfully!
T+288ms: Waiting for requests...
T+10456ms: eth_accounts
T+10461ms: eth_call
T+10479ms: eth_getBalance
T+10491ms: eth_getBalance
T+10497ms: eth_getBalance
T+10500ms: eth_call
T+10502ms: eth_getBalance
T+10507ms: eth_getBalance
T+10513ms: eth_getBalance
T+10521ms: eth_call
T+10524ms: eth_getBalance
T+10529ms: eth_getBalance
T+10544ms: eth_getBalance
T+10553ms: eth_getBalance
T+22759ms: eth_gasPrice
T+22763ms: eth_sendTransaction
T+41544ms: eth_accounts
T+41547ms: eth_call
T+41552ms: eth_getBalance
T+41570ms: eth_getBalance
T+41576ms: eth_call
T+41579ms: eth_getBalance
T+41583ms: eth_getBalance
T+41589ms: C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:63898
T+41589ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&
T+41589ms: 
T+41589ms: TypeError: Cannot read property 'pop' of undefined
T+41589ms:     at CheckpointTrie.Trie._updateNode (C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:56237:23)
T+41589ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:55984:16
T+41589ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:56320:14
T+41589ms:     at processNode (C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:56325:23)
T+41589ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:56316:5
T+41589ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:56057:7
T+41589ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:17623:7
T+41589ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:22962:16
T+41589ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:23179:32
T+41589ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:22954:16
```

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #666. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
