### ISSUE TITLE
System Error when running Ganache 1.0.2 on win32

### ISSUE THREAD

**Issue by ntfox0001** [trufflesuite/ganache#439]
PLATFORM: win32
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+61697484ms: eth_getBalance
T+61699463ms: net_version
T+61704463ms: net_version
T+61707439ms: eth_getBalance
T+61707443ms: eth_getBalance
T+61707447ms: eth_getBalance
T+61707450ms: eth_getBalance
T+61707454ms: eth_getBalance
T+61707457ms: eth_getBalance
T+61707460ms: eth_getBalance
T+61707464ms: eth_getBalance
T+61707469ms: eth_getBalance
T+61707473ms: eth_getBalance
T+61709464ms: net_version
T+61714471ms: net_version
T+61717442ms: eth_getBalance
T+61717447ms: eth_getBalance
T+61717452ms: eth_getBalance
T+61717456ms: eth_getBalance
T+61717460ms: eth_getBalance
T+61717463ms: eth_getBalance
T+61717466ms: eth_getBalance
T+61717470ms: eth_getBalance
T+61717470ms: eth_getBalance
T+61717473ms: eth_getBalance
T+61719465ms: net_version
T+61724468ms: net_version
T+61727441ms: eth_getBalance
T+61727444ms: eth_getBalance
T+61727447ms: eth_getBalance
T+61727450ms: eth_getBalance
T+61727474ms: eth_getBalance
T+61727474ms: eth_getBalance
T+61727477ms: eth_getBalance
T+61727481ms: eth_getBalance
T+61727486ms: eth_getBalance
T+61727489ms: eth_getBalance
T+61729466ms: net_version
T+61734469ms: net_version
T+61737440ms: eth_getBalance
T+61737444ms: eth_getBalance
T+61737448ms: eth_getBalance
T+61737452ms: eth_getBalance
T+61737455ms: eth_getBalance
T+61737457ms: eth_getBalance
T+61737457ms: eth_getBalance
T+61737461ms: eth_getBalance
T+61737461ms: eth_getBalance
T+61737465ms: eth_getBalance
T+61739467ms: net_version
T+61744467ms: net_version
T+61747457ms: eth_getBalance
T+61747464ms: eth_getBalance
T+61747464ms: eth_getBalance
T+61747476ms: eth_getBalance
T+61747482ms: eth_getBalance
T+61747488ms: eth_getBalance
T+61747492ms: eth_getBalance
T+61747495ms: eth_getBalance
T+61747497ms: eth_getBalance
T+61747501ms: eth_getBalance
T+61749467ms: net_version
T+61754470ms: net_version
T+61757443ms: eth_getBalance
T+61757447ms: eth_getBalance
T+61757451ms: eth_getBalance
T+61757455ms: eth_getBalance
T+61757458ms: eth_getBalance
T+61757458ms: eth_getBalance
T+61757461ms: eth_getBalance
T+61757463ms: eth_getBalance
T+61757466ms: eth_getBalance
T+61757469ms: eth_getBalance
T+61759469ms: net_version
T+61764471ms: net_version
T+61767443ms: eth_getBalance
T+61767447ms: eth_getBalance
T+61767453ms: eth_getBalance
T+61767453ms: eth_getBalance
T+61767457ms: eth_getBalance
T+61767464ms: eth_getBalance
T+61767469ms: eth_getBalance
T+61767469ms: eth_getBalance
T+61767469ms: eth_getBalance
T+61767474ms: eth_getBalance
T+61767833ms: net_version
T+61767847ms: eth_sendTransaction
T+61767923ms:   Transaction: 0xa16a59e0fff552cedd0c84a4a3331bac72b7ffaecaec77ebdab9990a26f2f538
T+61767923ms:   Contract created: 0x23e84570f7b28ad0d5e5545d398009194a8734f3
T+61767923ms:   Gas usage: 1190976
T+61767923ms:   Block Number: 49
T+61767926ms:   Block Time: Wed Mar 21 2018 10:26:48 GMT+0800 (中国标准时间)
T+61767928ms: eth_newBlockFilter
T+61767932ms: eth_getFilterChanges
T+61767943ms: eth_getTransactionReceipt
T+61767995ms: eth_getCode
T+61767998ms: eth_uninstallFilter
T+61768001ms: net_version
T+61768011ms: eth_sendTransaction
T+61768063ms: C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:63898
T+61768063ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&
T+61768063ms: 
T+61768063ms: TypeError: Cannot read property 'get' of undefined
T+61768063ms:     at dbGet (C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:56029:7)
T+61768063ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:17614:5
T+61768063ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:23091:20
T+61768063ms:     at iterate (C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:23172:13)
T+61768063ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:23184:29
T+61768063ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:22954:16
T+61768063ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:17619:7
T+61768063ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:56034:9
T+61768063ms:     at dispatchError (C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:36358:36)
T+61768063ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:22744:14
```

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #667. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
