### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by bachloxo** [trufflesuite/ganache#441]
PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+47883ms: net_version
T+47885ms: eth_sendTransaction
T+47924ms:   Transaction: 0xd8fad52d25c63a26fb4220117103994795aba87f69652f0a4c36be9771f6de03
T+47924ms:   Gas usage: 30366
T+47924ms:   Block Number: 212
T+47924ms:   Block Time: Fri Jul 14 2023 19:53:32 GMT+0700 (+07)
T+47927ms: eth_getTransactionReceipt
T+48096ms: eth_blockNumber
T+48269ms: eth_blockNumber
T+48343ms: net_version
T+48353ms: eth_call
T+48375ms: net_version
T+48381ms: eth_call
T+48401ms: net_version
T+48409ms: eth_call
T+48435ms: net_version
T+48439ms: eth_sendTransaction
T+48465ms:   Transaction: 0x60a86bdacfefdee19f5758785ff1461c29a5f44bc6c1f52721dacffc51b549f8
T+48465ms:   Gas usage: 44097
T+48465ms:   Block Number: 213
T+48469ms:   Block Time: Fri Jul 14 2023 19:53:33 GMT+0700 (+07)
T+48472ms: eth_getTransactionReceipt
T+48476ms: net_version
T+48479ms: eth_sendTransaction
T+48510ms:   Transaction: 0x77b3dd73596e2bb2a498ea4ed5811be521554719db1db4ef2d48771929e2aa42
T+48514ms:   Gas usage: 28157
T+48517ms:   Block Number: 214
T+48517ms:   Block Time: Fri Jul 14 2023 19:53:33 GMT+0700 (+07)
T+48521ms: eth_getTransactionReceipt
T+48525ms: net_version
T+48528ms: eth_sendTransaction
T+48541ms:   Transaction: 0x753c712f38948c4b2a88af95de3c899b21f6815ce81ae072c3d18e4e20c0e7c1
T+48541ms:   Gas usage: 23780
T+48541ms:   Block Number: 215
T+48541ms:   Block Time: Fri Jul 14 2023 19:53:33 GMT+0700 (+07)
T+48543ms:   Runtime Error: revert
T+48546ms: net_version
T+48550ms: eth_call
T+48562ms: net_version
T+48565ms: eth_sendTransaction
T+48591ms:   Transaction: 0x6d52ff62e08233df739871b7092205f5a27965f04e4b8ff0266c5d66cc9c723d
T+48594ms:   Gas usage: 29097
T+48594ms:   Block Number: 216
T+48597ms:   Block Time: Fri Jul 14 2023 19:53:33 GMT+0700 (+07)
T+48601ms: eth_getTransactionReceipt
T+48604ms: eth_blockNumber
T+48738ms: eth_getBlockByNumber
T+48749ms: net_version
T+48751ms: eth_sendTransaction
T+48786ms:   Transaction: 0x6ce6ed510083e66d363aa801c769d13a5ccf8ad1c7bf362063cf531a10c45efe
T+48786ms:   Contract created: 0xe843cde33060bf9cb11723934ead6a3de410ddee
T+48786ms:   Gas usage: 2042616
T+48786ms:   Block Number: 217
T+48786ms:   Block Time: Fri Jul 14 2023 19:53:33 GMT+0700 (+07)
T+48789ms: eth_newBlockFilter
T+48791ms: eth_getFilterChanges
T+48799ms: eth_getTransactionReceipt
T+48803ms: eth_getCode
T+48807ms: eth_uninstallFilter
T+48809ms: net_version
T+48811ms: eth_sendTransaction
T+48848ms:   Transaction: 0x36c3c05d84923236c72f1abf1bb2873b4effaf1eb004ff197854603eaab6495c
T+48848ms:   Contract created: 0xe0bf6021e023a197dbb3fabe64efa880e13d3f4b
T+48848ms:   Gas usage: 2706679
T+48848ms:   Block Number: 218
T+48848ms:   Block Time: Fri Jul 14 2023 19:53:33 GMT+0700 (+07)
T+48850ms: eth_newBlockFilter
T+48852ms: eth_getFilterChanges
T+48858ms: eth_getTransactionReceipt
T+48863ms: eth_getCode
T+48867ms: eth_uninstallFilter
T+48869ms: net_version
T+48872ms: eth_sendTransaction
T+48903ms:   Transaction: 0x80cc6d213ad1e4c874ffa20f36c848ffcaa87038a301b7e4917cb3b03735a6de
T+48903ms:   Gas usage: 37627
T+48903ms:   Block Number: 219
T+48903ms:   Block Time: Fri Jul 14 2023 19:53:33 GMT+0700 (+07)
T+48906ms: eth_getTransactionReceipt
T+48910ms: net_version
T+48914ms: eth_sendTransaction
T+48960ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+48960ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+48960ms: 
T+48960ms: TypeError: Cannot read property 'get' of undefined
T+48960ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+48960ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+48960ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+48960ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+48960ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+48960ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+48960ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+48960ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+48960ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+48960ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #667. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
