### ISSUE TITLE
System Error when running Ganache 1.0.2 on linux

### ISSUE THREAD

**Issue by hjorthjort** [trufflesuite/ganache#442]
Caused by running `truffle test`. Two crashes, crash log provided for both of them.

# Crash 1

PLATFORM: linux
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+62775609ms:   Gas usage: 263169
T+62775609ms:   Block Number: 538
T+62775609ms:   Block Time: Wed Mar 21 2018 18:20:34 GMT+0900 (JST)
T+62775613ms: eth_newBlockFilter
T+62775614ms: eth_getFilterChanges
T+62775616ms: eth_getFilterChanges
T+62775620ms: eth_getTransactionReceipt
T+62775635ms: eth_getCode
T+62775638ms: eth_getTransactionReceipt
T+62775640ms: eth_uninstallFilter
T+62775642ms: eth_getCode
T+62775780ms: eth_uninstallFilter
T+62775782ms: eth_sendTransaction
T+62775842ms:   Transaction: 0x4e13a13c7416e5e35529c6b9789ab7013ab0fcc9dad6d983e35fbdf4878001e0
T+62775842ms:   Contract created: 0xf07ed3a526698d6d649591bbf15572c8f0622aba
T+62775842ms:   Gas usage: 5186022
T+62775842ms:   Block Number: 539
T+62775842ms:   Block Time: Wed Mar 21 2018 18:20:34 GMT+0900 (JST)
T+62775844ms: eth_newBlockFilter
T+62775847ms: eth_getFilterChanges
T+62775851ms: eth_getTransactionReceipt
T+62775872ms: eth_getCode
T+62775891ms: eth_uninstallFilter
T+62775893ms: eth_blockNumber
T+62775895ms: eth_sendTransaction
T+62775987ms:   Transaction: 0xb64cce8e7857cf080e919e7df47650c0664539a70914b4c9687f7c132d9619d1
T+62775987ms:   Gas usage: 1128207
T+62775987ms:   Block Number: 540
T+62775987ms:   Block Time: Wed Mar 21 2018 18:20:34 GMT+0900 (JST)
T+62775990ms: eth_getTransactionReceipt
T+62775997ms: eth_blockNumber
T+62776000ms: eth_sendTransaction
T+62776047ms:   Transaction: 0x87ba2c0c2b6f99dd23566f1f775e383a9dfe3f1828c498d5fa239ea459913d95
T+62776047ms:   Gas usage: 32729
T+62776047ms:   Block Number: 541
T+62776047ms:   Block Time: Wed Mar 21 2018 18:20:34 GMT+0900 (JST)
T+62776049ms: eth_getTransactionReceipt
T+62776053ms: eth_blockNumber
T+62776056ms: eth_sendTransaction
T+62776270ms:   Transaction: 0x1c1eb60d485ffb5f0382b3d2e3cd99e9e76b3d4e6317cbd48b270b9c49eb2989
T+62776270ms:   Gas usage: 122221
T+62776270ms:   Block Number: 542
T+62776270ms:   Block Time: Wed Mar 21 2018 18:20:34 GMT+0900 (JST)
T+62776272ms: eth_getTransactionReceipt
T+62776280ms: eth_blockNumber
T+62776284ms: eth_sendTransaction
T+62776487ms:   Transaction: 0xb78bf50451c308529c255c4d93764e0890a081954b7fc811e1cc291c52dd13ad
T+62776487ms:   Gas usage: 1244555
T+62776487ms:   Block Number: 543
T+62776487ms:   Block Time: Wed Mar 21 2018 18:20:35 GMT+0900 (JST)
T+62776489ms: eth_getTransactionReceipt
T+62776496ms: eth_getLogs
T+62796614ms: net_version
T+62796620ms: eth_accounts
T+62796636ms: eth_accounts
T+62800183ms: eth_accounts
T+62800277ms: eth_sendTransaction
T+62800305ms:   Transaction: 0x52d605d71852ba90391eac4bfff0f7e96acae8764951044b05719e77bfcd3fc8
T+62800305ms:   Contract created: 0x8585d1f3bde564cb4b87efaf90d2e247962ad76b
T+62800305ms:   Gas usage: 269607
T+62800305ms:   Block Number: 544
T+62800308ms:   Block Time: Wed Mar 21 2018 18:20:59 GMT+0900 (JST)
T+62800310ms: eth_newBlockFilter
T+62800312ms: eth_getFilterChanges
T+62800318ms: eth_getTransactionReceipt
T+62800324ms: eth_getCode
T+62800334ms: eth_uninstallFilter
T+62800337ms: eth_sendTransaction
T+62800359ms:   Transaction: 0x3857dc891e802abc0afb1b827fa402b64ce0949ebdeba69978a915c3ca4af3ae
T+62800359ms:   Gas usage: 41981
T+62800359ms:   Block Number: 545
T+62800359ms:   Block Time: Wed Mar 21 2018 18:20:59 GMT+0900 (JST)
T+62800361ms: eth_getTransactionReceipt
T+62800366ms: eth_accounts
T+62800408ms: eth_sendTransaction
T+62800450ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+62800450ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_W
T+62800450ms: 
T+62800450ms: TypeError: Cannot read property 'get' of undefined
T+62800450ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+62800450ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+62800450ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+62800450ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+62800450ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+62800450ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+62800450ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+62800450ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+62800450ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+62800450ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

# Crash 2

PLATFORM: linux
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+557035ms:   Contract created: 0xaa79f17ed8a1326eb5f13873586a60597c495dd7
T+557035ms:   Gas usage: 263105
T+557035ms:   Block Number: 126
T+557035ms:   Block Time: Wed Mar 21 2018 18:31:12 GMT+0900 (JST)
T+557037ms: eth_newBlockFilter
T+557040ms: eth_getFilterChanges
T+557042ms: eth_getFilterChanges
T+557044ms: eth_getTransactionReceipt
T+557046ms: eth_getCode
T+557048ms: eth_getTransactionReceipt
T+557050ms: eth_getCode
T+557052ms: eth_uninstallFilter
T+557187ms: eth_uninstallFilter
T+557190ms: eth_sendTransaction
T+557230ms:   Transaction: 0xd80c455d0b56c023cc1b7cdbd37a59b6627d3f1eb004939bf3ea044dc8911186
T+557230ms:   Contract created: 0xdd65c920a296f5feeca6e92f86fcd641fe41d5c6
T+557230ms:   Gas usage: 5497288
T+557230ms:   Block Number: 127
T+557230ms:   Block Time: Wed Mar 21 2018 18:31:13 GMT+0900 (JST)
T+557232ms: eth_newBlockFilter
T+557234ms: eth_getFilterChanges
T+557239ms: eth_getTransactionReceipt
T+557246ms: eth_getCode
T+557252ms: eth_uninstallFilter
T+557254ms: eth_blockNumber
T+557256ms: eth_sendTransaction
T+557311ms:   Transaction: 0x94fa5c0fff1d7e6634d97d51f82fc1a422ad493dfb82cb73661c1afeced1204d
T+557311ms:   Gas usage: 1147816
T+557311ms:   Block Number: 128
T+557311ms:   Block Time: Wed Mar 21 2018 18:31:13 GMT+0900 (JST)
T+557313ms: eth_getTransactionReceipt
T+557320ms: eth_blockNumber
T+557323ms: eth_sendTransaction
T+557359ms:   Transaction: 0x4417cf27e0cc556789f059ae42857c4a8c058a49b259c74dd1ecc7a094cc673a
T+557359ms:   Gas usage: 32729
T+557359ms:   Block Number: 129
T+557359ms:   Block Time: Wed Mar 21 2018 18:31:13 GMT+0900 (JST)
T+557363ms: eth_getTransactionReceipt
T+557366ms: eth_blockNumber
T+557369ms: eth_sendTransaction
T+557595ms:   Transaction: 0xf3e47f04f19314a87d3aeee0481febb46d8839345aa9bf84d78b9a47f5703f26
T+557595ms:   Gas usage: 122221
T+557595ms:   Block Number: 130
T+557595ms:   Block Time: Wed Mar 21 2018 18:31:13 GMT+0900 (JST)
T+557597ms: eth_getTransactionReceipt
T+557605ms: eth_blockNumber
T+557608ms: eth_sendTransaction
T+557766ms:   Transaction: 0x7739c8c37a75b07dcb89a3462d9e1a15488e9d289764bc0c00ce362c4cc5e174
T+557766ms:   Gas usage: 1272104
T+557766ms:   Block Number: 131
T+557766ms:   Block Time: Wed Mar 21 2018 18:31:13 GMT+0900 (JST)
T+557768ms: eth_getTransactionReceipt
T+557775ms: eth_getLogs
T+562167ms: net_version
T+562173ms: eth_accounts
T+562189ms: eth_accounts
T+565881ms: eth_accounts
T+565921ms: eth_sendTransaction
T+565938ms:   Transaction: 0xff3c09a3f43473f778ee21a3a95d19789a8d5ecb0e972050d422a7d1a5370077
T+565938ms:   Contract created: 0xfa21e79ca2dfb3ab15469796069622903919159c
T+565938ms:   Gas usage: 269607
T+565938ms:   Block Number: 132
T+565938ms:   Block Time: Wed Mar 21 2018 18:31:21 GMT+0900 (JST)
T+565940ms: eth_newBlockFilter
T+565943ms: eth_getFilterChanges
T+565949ms: eth_getTransactionReceipt
T+565954ms: eth_getCode
T+565964ms: eth_uninstallFilter
T+565967ms: eth_sendTransaction
T+565981ms:   Transaction: 0x5e5638d68071d961b43068193f812e6cab6831c83fa6101fde8508aa3eb491ac
T+565981ms:   Gas usage: 41981
T+565981ms:   Block Number: 133
T+565981ms:   Block Time: Wed Mar 21 2018 18:31:21 GMT+0900 (JST)
T+565983ms: eth_getTransactionReceipt
T+565988ms: eth_accounts
T+566050ms: eth_sendTransaction
T+566058ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+566058ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_W
T+566058ms: 
T+566058ms: TypeError: Cannot read property 'get' of undefined
T+566058ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+566058ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+566058ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+566058ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+566058ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+566058ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+566058ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+566058ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+566058ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+566058ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #667. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
