### ISSUE TITLE
 RangeError: Invalid string length

### ISSUE THREAD

**Issue by zacklif** [trufflesuite/ganache#443]
PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+145317ms:   Block Time: Wed Mar 21 2018 19:29:25 GMT+0200 (IST)
T+145369ms: eth_getTransactionReceipt
T+145475ms: eth_getBlockByNumber
T+145496ms: eth_getLogs
T+153478ms: eth_getBlockByNumber
T+161488ms: eth_getBlockByNumber
T+169501ms: eth_getBlockByNumber
T+183296ms: eth_getBlockByNumber
T+183318ms: net_version
T+183325ms: net_version
T+183331ms: eth_getBlockByNumber
T+183339ms: eth_getBalance
T+183345ms: eth_getBalance
T+183351ms: eth_getBalance
T+183361ms: eth_getBalance
T+183365ms: eth_getBalance
T+183365ms: eth_getBalance
T+183371ms: eth_getLogs
T+183375ms: eth_getTransactionByHash
T+186276ms: net_version
T+186282ms: net_version
T+186315ms: eth_call
T+186335ms: eth_call
T+191350ms: eth_getBlockByNumber
T+196179ms: eth_getBlockByNumber
T+196189ms: eth_getCode
T+196210ms: eth_estimateGas
T+199362ms: eth_getBlockByNumber
T+199796ms: eth_getTransactionCount
T+199818ms: eth_sendRawTransaction
T+201056ms:   Transaction: 0x8d881f3ad444c80c8be051a425197c85ab2fd648dcb75a4587bc1af22a11dea0
T+201056ms:   Gas usage: 2564487
T+201062ms:   Block Number: 6
T+201062ms:   Block Time: Wed Mar 21 2018 19:30:21 GMT+0200 (IST)
T+201129ms: eth_getTransactionReceipt
T+201528ms: eth_getLogs
T+207372ms: eth_getBlockByNumber
T+207390ms: eth_getBlockByNumber
T+207394ms: eth_getBalance
T+207397ms: eth_getBalance
T+207401ms: eth_getBalance
T+207405ms: eth_getBalance
T+207408ms: eth_getBalance
T+207413ms: eth_getBalance
T+207416ms: eth_getLogs
T+212814ms: eth_getBlockByNumber
T+212836ms: eth_estimateGas
T+215401ms: eth_getBlockByNumber
T+215428ms: eth_getTransactionCount
T+215455ms: eth_sendRawTransaction
T+216641ms:   Transaction: 0x80617eec272be2f9d83f84ba9c5aa5a46915c00c254b0089b02ed981546075e5
T+216641ms:   Gas usage: 2568342
T+216641ms:   Block Number: 7
T+216641ms:   Block Time: Wed Mar 21 2018 19:30:37 GMT+0200 (IST)
T+216704ms: eth_getTransactionReceipt
T+216808ms: eth_getLogs
T+223413ms: eth_getBlockByNumber
T+223425ms: eth_getBlockByNumber
T+223431ms: eth_getBalance
T+223434ms: eth_getBalance
T+223437ms: eth_getBalance
T+223440ms: eth_getBalance
T+223443ms: eth_getBalance
T+223447ms: eth_getBalance
T+223450ms: eth_getLogs
T+231440ms: eth_getBlockByNumber
T+239450ms: eth_getBlockByNumber
T+247464ms: eth_getBlockByNumber
T+255475ms: eth_getBlockByNumber
T+261492ms: eth_getBlockByNumber
T+261516ms: eth_estimateGas
T+263513ms: eth_getBlockByNumber
T+267395ms: eth_getTransactionCount
T+267416ms: eth_sendRawTransaction
T+268794ms:   Transaction: 0xdd3f5a2ace9a067367ee00cad498b69f2a852c5ab1647497ac84359199608f83
T+268794ms:   Gas usage: 5105110
T+268794ms:   Block Number: 8
T+268794ms:   Block Time: Wed Mar 21 2018 19:31:28 GMT+0200 (IST)
T+268799ms:   Runtime Error: out of gas
T+271528ms: eth_getBlockByNumber
T+271539ms: eth_getBlockByNumber
T+271546ms: eth_getBalance
T+271553ms: eth_getBalance
T+271557ms: eth_getBalance
T+271560ms: eth_getBalance
T+271562ms: eth_getBalance
T+271562ms: eth_getBalance
T+271565ms: eth_getLogs
T+279553ms: eth_getBlockByNumber
T+287567ms: eth_getBlockByNumber
T+295579ms: eth_getBlockByNumber
T+303593ms: eth_getBlockByNumber
T+311603ms: eth_getBlockByNumber
T+319612ms: eth_getBlockByNumber
T+327626ms: eth_getBlockByNumber
T+330545ms: net_version
T+330559ms: eth_accounts
T+330569ms: debug_traceTransaction
T+335641ms: eth_getBlockByNumber
T+343652ms: eth_getBlockByNumber
T+353808ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+353808ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+353808ms: 
T+353808ms: RangeError: Invalid string length
T+353808ms:     at JSON.stringify (<anonymous>)
T+353808ms:     at /node_modules/ganache-cli/build/lib.node.js:95755:33
T+353808ms:     at intermediary (/node_modules/ganache-cli/build/lib.node.js:26103:5)
T+353808ms:     at Web3ProviderEngine._inspectResponseForNewBlock (/node_modules/ganache-cli/build/lib.node.js:47967:12)
T+353808ms:     at /node_modules/ganache-cli/build/lib.node.js:47867:14
T+353808ms:     at /node_modules/ganache-cli/build/lib.node.js:27494:16
T+353808ms:     at replenish (/node_modules/ganache-cli/build/lib.node.js:28014:25)
T+353808ms:     at iterateeCallback (/node_modules/ganache-cli/build/lib.node.js:28004:17)
T+353808ms:     at /node_modules/ganache-cli/build/lib.node.js:27979:16
T+353808ms:     at async.eachSeries.resultObj.id (/node_modules/ganache-cli/build/lib.node.js:47847:9)
```

**Comment by seesemichaelj** [comment]
Thanks for reporting this! Please upgrade to the latest version (currently 1.2.1).

You can get it at https://github.com/trufflesuite/ganache/releases

If you're still having issues in the new version, please report a new issue.

Thanks!
