### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by zachdoty** [trufflesuite/ganache#444]
PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+289535ms: eth_call
T+293252ms: eth_getBlockByNumber
T+293259ms: eth_getBlockByNumber
T+293264ms: eth_getBalance
T+293268ms: eth_getBalance
T+293272ms: eth_getBalance
T+293275ms: eth_getBalance
T+293279ms: eth_getBalance
T+293279ms: eth_getBalance
T+293283ms: eth_getBlockByNumber
T+293287ms: eth_getBalance
T+293290ms: eth_getBalance
T+293294ms: eth_getBlockByNumber
T+293296ms: eth_getBalance
T+293298ms: eth_getBalance
T+293298ms: eth_getBalance
T+293300ms: eth_getBalance
T+293302ms: eth_getBalance
T+293304ms: eth_getBlockByNumber
T+293306ms: eth_getBalance
T+293308ms: eth_getBalance
T+293677ms: eth_call
T+294355ms: eth_call
T+297582ms: eth_getBlockByNumber
T+297591ms: eth_getCode
T+297603ms: eth_estimateGas
T+299308ms: eth_getTransactionCount
T+299337ms: eth_sendRawTransaction
T+300512ms:   Transaction: 0xdf52361f8e8f793eb878f7f5bfe35473beb7a33b43cc275caa75b23c3ca9670d
T+300512ms:   Gas usage: 605042
T+300512ms:   Block Number: 150
T+300512ms:   Block Time: Wed Mar 21 2018 15:40:11 GMT-0700 (PDT)
T+301292ms: eth_getBlockByNumber
T+301301ms: eth_getBlockByNumber
T+301306ms: eth_getBalance
T+301311ms: eth_getBalance
T+301311ms: eth_getBalance
T+301316ms: eth_getBalance
T+301321ms: eth_getBalance
T+301321ms: eth_getBalance
T+301325ms: eth_getBlockByNumber
T+301328ms: eth_getBalance
T+301332ms: eth_getBalance
T+301334ms: eth_getBlockByNumber
T+301339ms: eth_getBalance
T+301341ms: eth_getBalance
T+301341ms: eth_getBalance
T+301341ms: eth_getBalance
T+301343ms: eth_getBalance
T+301347ms: eth_getBlockByNumber
T+301349ms: eth_getBalance
T+301351ms: eth_getBalance
T+301354ms: eth_getBalance
T+302321ms: eth_call
T+302321ms: eth_call
T+302356ms: eth_call
T+302356ms: eth_call
T+302356ms: eth_call
T+302356ms: eth_call
T+302356ms: eth_call
T+302356ms: eth_call
T+302363ms: eth_call
T+302370ms: eth_call
T+302379ms: eth_call
T+302387ms: eth_call
T+302394ms: eth_call
T+302404ms: eth_call
T+303312ms: eth_call
T+304344ms: eth_call
T+305907ms: eth_getBlockByNumber
T+305916ms: eth_getCode
T+305926ms: eth_estimateGas
T+307474ms: eth_getTransactionCount
T+307501ms: eth_sendRawTransaction
T+308545ms:   Transaction: 0xc49c48275ffcd60747dfefeb94e01cebccbe67e2d09778ccdff81c03a2c7f7a4
T+308545ms:   Gas usage: 211329
T+308545ms:   Block Number: 154
T+308545ms:   Block Time: Wed Mar 21 2018 15:40:19 GMT-0700 (PDT)
T+309341ms: eth_getBlockByNumber
T+309349ms: eth_getBlockByNumber
T+309353ms: eth_getBalance
T+309356ms: eth_getBalance
T+309356ms: eth_getBalance
T+309360ms: eth_getBalance
T+309363ms: eth_getBalance
T+309363ms: eth_getBalance
T+309366ms: eth_getBlockByNumber
T+309371ms: eth_getBalance
T+309371ms: eth_getBalance
T+309375ms: eth_getBlockByNumber
T+309378ms: eth_getBalance
T+309382ms: eth_getBalance
T+309382ms: eth_getBalance
T+309385ms: eth_getBalance
T+309388ms: eth_getBalance
T+309390ms: eth_getBlockByNumber
T+309393ms: eth_getBalance
T+309395ms: eth_getBalance
T+309397ms: eth_getBalance
T+310410ms: eth_call
T+310410ms: eth_call
T+310433ms: eth_call
T+310436ms: eth_call
T+310436ms: eth_call
T+310441ms: eth_call
T+310441ms: eth_call
T+310444ms: eth_call
T+310447ms: eth_call
T+310450ms: eth_call
T+310461ms: eth_call
T+310468ms: eth_call
T+310476ms: eth_call
T+310483ms: eth_call
T+310530ms: eth_call
T+310530ms: eth_call
T+310984ms: eth_call
T+312498ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+312498ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+312498ms: 
T+312498ms: TypeError: Cannot read property 'pop' of undefined
T+312498ms:     at CheckpointTrie.Trie._updateNode (/node_modules/ganache-cli/build/lib.node.js:56237:23)
T+312498ms:     at /node_modules/ganache-cli/build/lib.node.js:55984:16
T+312498ms:     at /node_modules/ganache-cli/build/lib.node.js:56320:14
T+312498ms:     at processNode (/node_modules/ganache-cli/build/lib.node.js:56325:23)
T+312498ms:     at /node_modules/ganache-cli/build/lib.node.js:56316:5
T+312498ms:     at /node_modules/ganache-cli/build/lib.node.js:56057:7
T+312498ms:     at /node_modules/ganache-cli/build/lib.node.js:17623:7
T+312498ms:     at /node_modules/ganache-cli/build/lib.node.js:22962:16
T+312498ms:     at /node_modules/ganache-cli/build/lib.node.js:23179:32
T+312498ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
```

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #666. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
