### ISSUE TITLE
System Error when running Ganache 1.0.2 on linux

### ISSUE THREAD

**Issue by kyriediculous** [trufflesuite/ganache#445]
while running truffle migrate --reset --compile-all

PLATFORM: linux
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+2162185ms: net_version
T+2162192ms: net_version
T+2162197ms: eth_sendTransaction
T+2162266ms:   Transaction: 0x212f4a86fa8f9572ba543ddb941aa6ed73c3f60ae53d41f157f3a18fa927aabe
T+2162266ms:   Contract created: 0x38cf23c52bb4b13f051aec09580a2de845a7fa35
T+2162266ms:   Gas usage: 1098021
T+2162266ms:   Block Number: 18
T+2162266ms:   Block Time: Thu Mar 22 2018 02:48:10 GMT+0100 (CET)
T+2162272ms: eth_newBlockFilter
T+2162276ms: eth_getFilterChanges
T+2162280ms: eth_getTransactionReceipt
T+2162286ms: eth_getCode
T+2162298ms: eth_uninstallFilter
T+2162303ms: eth_sendTransaction
T+2162354ms:   Transaction: 0x4fc6b3eca03ea14afc47c9e270803b1e2abea930e8bfba599c0c23cf974158c3
T+2162354ms:   Gas usage: 26981
T+2162354ms:   Block Number: 19
T+2162359ms:   Block Time: Thu Mar 22 2018 02:48:11 GMT+0100 (CET)
T+2162363ms: eth_getTransactionReceipt
T+2166873ms: eth_getBlockByNumber
T+2166882ms: eth_getBlockByNumber
T+2166893ms: eth_getBlockByNumber
T+2166898ms: eth_getBalance
T+2174903ms: eth_getBlockByNumber
T+2180182ms: net_version
T+2180187ms: net_version
T+2182916ms: eth_getBlockByNumber
T+2190928ms: eth_getBlockByNumber
T+2198940ms: eth_getBlockByNumber
T+2206952ms: eth_getBlockByNumber
T+2214963ms: eth_getBlockByNumber
T+2222975ms: eth_getBlockByNumber
T+2230989ms: eth_getBlockByNumber
T+2239004ms: eth_getBlockByNumber
T+2247017ms: eth_getBlockByNumber
T+2255029ms: eth_getBlockByNumber
T+2263041ms: eth_getBlockByNumber
T+2271052ms: eth_getBlockByNumber
T+2279063ms: eth_getBlockByNumber
T+2287074ms: eth_getBlockByNumber
T+2295085ms: eth_getBlockByNumber
T+2303096ms: eth_getBlockByNumber
T+2311109ms: eth_getBlockByNumber
T+2319120ms: eth_getBlockByNumber
T+2327129ms: eth_getBlockByNumber
T+2335141ms: eth_getBlockByNumber
T+2343152ms: eth_getBlockByNumber
T+2351164ms: eth_getBlockByNumber
T+2359176ms: eth_getBlockByNumber
T+2367187ms: eth_getBlockByNumber
T+2375199ms: eth_getBlockByNumber
T+2383211ms: eth_getBlockByNumber
T+2391223ms: eth_getBlockByNumber
T+2399234ms: eth_getBlockByNumber
T+2407246ms: eth_getBlockByNumber
T+2415257ms: eth_getBlockByNumber
T+2423270ms: eth_getBlockByNumber
T+2431282ms: eth_getBlockByNumber
T+2439293ms: eth_getBlockByNumber
T+2447304ms: eth_getBlockByNumber
T+2455316ms: eth_getBlockByNumber
T+2463327ms: eth_getBlockByNumber
T+2471338ms: eth_getBlockByNumber
T+2479349ms: eth_getBlockByNumber
T+2487361ms: eth_getBlockByNumber
T+2495373ms: eth_getBlockByNumber
T+2503385ms: eth_getBlockByNumber
T+2511396ms: eth_getBlockByNumber
T+2519408ms: eth_getBlockByNumber
T+2527419ms: eth_getBlockByNumber
T+2535431ms: eth_getBlockByNumber
T+2543443ms: eth_getBlockByNumber
T+2551454ms: eth_getBlockByNumber
T+2559319ms: net_version
T+2559327ms: eth_accounts
T+2559335ms: eth_accounts
T+2559350ms: net_version
T+2559354ms: net_version
T+2559360ms: eth_sendTransaction
T+2559409ms:   Transaction: 0x0f9da53d8dc9e280fc5b3317d3dc236d2efdd7a55612ef2cce560400143098e6
T+2559409ms:   Contract created: 0xbaaa2a3237035a2c7fa2a33c76b44a8c6fe18e87
T+2559409ms:   Gas usage: 269607
T+2559409ms:   Block Number: 20
T+2559421ms:   Block Time: Thu Mar 22 2018 02:54:48 GMT+0100 (CET)
T+2559424ms: eth_newBlockFilter
T+2559424ms: eth_getFilterChanges
T+2559428ms: eth_getTransactionReceipt
T+2559439ms: eth_getCode
T+2559453ms: eth_uninstallFilter
T+2559460ms: eth_sendTransaction
T+2559467ms: eth_getBlockByNumber
T+2559478ms: eth_getBlockByNumber
T+2559490ms: eth_getBlockByNumber
T+2559494ms: eth_getBalance
T+2559522ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+2559522ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_W
T+2559522ms: 
T+2559522ms: TypeError: Cannot read property 'get' of undefined
T+2559522ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+2559522ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+2559522ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+2559522ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+2559522ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+2559522ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+2559522ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+2559522ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+2559522ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+2559522ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #667. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
