### ISSUE TITLE
System Error when running Ganache 1.6.11 on darwin

### ISSUE THREAD

**Issue by genshun9** [trufflesuite/ganache#447]
PLATFORM: darwin
GANACHE VERSION: 1.6.11

EXCEPTION:
```
Error: listen EADDRNOTAVAIL 10.0.33.151:7545
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1249:19)
    at listen (net.js:1298:10)
    at doListening (net.js:1397:7)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

APPLICATION LOG:
```
T+0ms: Starting server with initial configuration: {"hostname":"10.0.33.151","port":7545,"network_id":5777,"total_accounts":10,"unlocked_accounts":[],"vmErrorsOnRPCResponse":true}
```

**Comment by hacktar** [comment]
Seems you put a custom IP in settings.
If you changed IP in Settings and now it doesn't start anymore, you could change it to 127.0.0.1 manually editing the Settings file in ~/Library/Application\ Support/Ganache/

**Comment by genshun9** [comment]
thank you !!
