### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by dingzhongchang** [trufflesuite/ganache#451]
PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+27431ms:   Gas usage: 1784528
T+27431ms:   Block Number: 3
T+27438ms:   Block Time: Fri Mar 23 2018 12:31:52 GMT+0800 (CST)
T+27444ms: eth_newBlockFilter
T+27448ms: eth_getFilterChanges
T+27456ms: eth_getTransactionReceipt
T+27462ms: eth_getCode
T+27468ms: eth_uninstallFilter
T+27472ms: eth_sendTransaction
T+27597ms:   Transaction: 0xc939c90de3ef4754a901a244a1dedef37424f405e07ac346904f1301a2656025
T+27597ms:   Contract created: 0xf25186b5081ff5ce73482ad761db0eb0d25abfbf
T+27597ms:   Gas usage: 2338172
T+27597ms:   Block Number: 4
T+27597ms:   Block Time: Fri Mar 23 2018 12:31:52 GMT+0800 (CST)
T+27602ms: eth_newBlockFilter
T+27608ms: eth_getFilterChanges
T+27615ms: eth_getTransactionReceipt
T+27624ms: eth_getCode
T+27657ms: eth_uninstallFilter
T+27663ms: eth_sendTransaction
T+27718ms:   Transaction: 0x059cf1bbc372b9348ce487de910358801bbbd1c89182853439bec0afaee6c7db
T+27718ms:   Gas usage: 26981
T+27718ms:   Block Number: 5
T+27718ms:   Block Time: Fri Mar 23 2018 12:31:52 GMT+0800 (CST)
T+27724ms: eth_getTransactionReceipt
T+29070ms: eth_getBlockByNumber
T+30321ms: evm_snapshot
T+30411ms: eth_blockNumber
T+30421ms: eth_call
T+30457ms: net_version
T+30464ms: eth_getCode
T+30473ms: eth_call
T+30500ms: eth_blockNumber
T+30509ms: eth_call
T+30534ms: net_version
T+30539ms: eth_getCode
T+30550ms: eth_sendTransaction
T+30594ms:   Transaction: 0x3ded745b07bf8d60d19dba651c7426db9be010ab166e6a5a23e9152a9a1d4782
T+30594ms:   Gas usage: 44187
T+30594ms:   Block Number: 6
T+30594ms:   Block Time: Fri Mar 23 2018 12:31:55 GMT+0800 (CST)
T+30600ms: eth_getTransactionReceipt
T+30611ms: eth_call
T+30641ms: eth_blockNumber
T+30648ms: eth_call
T+30678ms: net_version
T+30685ms: eth_getCode
T+30692ms: eth_call
T+30723ms: eth_blockNumber
T+30736ms: eth_call
T+30780ms: net_version
T+30829ms: eth_getCode
T+30835ms: eth_call
T+30857ms: eth_blockNumber
T+30863ms: eth_call
T+30921ms: net_version
T+30925ms: eth_getCode
T+30932ms: eth_sendTransaction
T+31069ms:   Transaction: 0xc7c8a1467c9fa2924d8c0e0d7e57f78b44607817df12dfaa5cea837dd964946b
T+31069ms:   Gas usage: 184034
T+31074ms:   Block Number: 7
T+31074ms:   Block Time: Fri Mar 23 2018 12:31:56 GMT+0800 (CST)
T+31078ms: eth_getTransactionReceipt
T+31084ms: eth_call
T+31120ms: eth_blockNumber
T+31129ms: eth_call
T+31173ms: net_version
T+31179ms: eth_getCode
T+31186ms: eth_call
T+31201ms: eth_blockNumber
T+31206ms: eth_call
T+31278ms: net_version
T+31282ms: eth_getCode
T+31287ms: eth_call
T+31295ms: eth_blockNumber
T+31345ms: eth_call
T+31375ms: net_version
T+31380ms: eth_getCode
T+31386ms: eth_call
T+31419ms: eth_blockNumber
T+31423ms: eth_call
T+31456ms: net_version
T+31462ms: eth_getCode
T+31468ms: eth_sendTransaction
T+31561ms:   Transaction: 0x8443b0f47ee2f7e052294c2590944dfd01d59a027089bea6b328f41f282b32a3
T+31561ms:   Gas usage: 183238
T+31565ms:   Block Number: 8
T+31565ms:   Block Time: Fri Mar 23 2018 12:31:56 GMT+0800 (CST)
T+31569ms: eth_getTransactionReceipt
T+31572ms: eth_call
T+31587ms: eth_blockNumber
T+31593ms: eth_call
T+31626ms: net_version
T+31631ms: eth_getCode
T+31635ms: eth_call
T+31693ms: eth_blockNumber
T+31698ms: eth_call
T+31731ms: net_version
T+31734ms: eth_getCode
T+31740ms: eth_call
T+31808ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+31808ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+31808ms: 
T+31808ms: TypeError: Cannot read property 'get' of undefined
T+31808ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+31808ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+31808ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+31808ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+31808ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+31808ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+31808ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+31808ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+31808ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+31808ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #667. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
