### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by okwme** [trufflesuite/ganache#453]
PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+15838834ms:   Block Time: Fri Mar 23 2018 16:45:25 GMT-0400 (EDT)
T+15838834ms: eth_newBlockFilter
T+15838834ms: eth_getFilterChanges
T+15838834ms: eth_getFilterChanges
T+15838834ms: eth_getTransactionReceipt
T+15838933ms: eth_getTransactionReceipt
T+15838933ms: eth_getCode
T+15838933ms: eth_getCode
T+15838933ms: eth_uninstallFilter
T+15838933ms: net_version
T+15838933ms: eth_uninstallFilter
T+15838933ms: eth_sendTransaction
T+15838980ms: eth_sendTransaction
T+15839007ms:   Transaction: 0xf5c38f063baa550ed57c23135feadbcd28b62d0ffab116fd4b9042ca91703762
T+15839007ms:   Contract created: 0x34a0fd58890fb761f4ee8d7673ca49b49552f799
T+15839007ms:   Gas usage: 6123152
T+15839007ms:   Block Number: 710
T+15839007ms:   Block Time: Fri Mar 23 2018 16:45:25 GMT-0400 (EDT)
T+15839007ms: eth_newBlockFilter
T+15839119ms:   Transaction: 0x6b92891e712dab9a966f80c39a2c228303a40949c7e44375b44c3396f742d0aa
T+15839119ms:   Gas usage: 44137
T+15839119ms:   Block Number: 711
T+15839119ms:   Block Time: Fri Mar 23 2018 16:45:25 GMT-0400 (EDT)
T+15839119ms: eth_getTransactionReceipt
T+15839119ms: eth_getFilterChanges
T+15839152ms: net_version
T+15839361ms: eth_sendTransaction
T+15839361ms: eth_getTransactionReceipt
T+15839361ms: eth_getCode
T+15839361ms: eth_uninstallFilter
T+15839361ms: net_version
T+15839464ms: eth_sendTransaction
T+15839515ms:   Transaction: 0x251daee275e68eb3f0b2197da05b7c1a53c97c168e26047b9761dd7dc4349e25
T+15839515ms:   Gas usage: 43629
T+15839515ms:   Block Number: 712
T+15839515ms:   Block Time: Fri Mar 23 2018 16:45:25 GMT-0400 (EDT)
T+15839515ms: eth_getTransactionReceipt
T+15839515ms: eth_sendTransaction
T+15839551ms:   Transaction: 0xf2d21c71e26f3b2dc05c73baa42a835a427753325a03e7d7a259856a4058d8ce
T+15839551ms:   Gas usage: 44137
T+15839551ms:   Block Number: 713
T+15839551ms:   Block Time: Fri Mar 23 2018 16:45:25 GMT-0400 (EDT)
T+15839551ms: eth_getTransactionReceipt
T+15839551ms: net_version
T+15839551ms: eth_sendTransaction
T+15839554ms:   Transaction: 0x04a470173dfc28e743ddad80585d77709119d41f747515e94f47032de278f76e
T+15839554ms:   Gas usage: 42406
T+15839554ms:   Block Number: 714
T+15839554ms:   Block Time: Fri Mar 23 2018 16:45:25 GMT-0400 (EDT)
T+15839554ms: eth_getTransactionReceipt
T+15839557ms: eth_sendTransaction
T+15839645ms:   Transaction: 0x7cadb3e7f68fcfc4563d8b730c0525bde85292aab4b35d436fb105a49c67d04b
T+15839645ms:   Gas usage: 22771
T+15839645ms:   Block Number: 715
T+15839645ms:   Block Time: Fri Mar 23 2018 16:45:25 GMT-0400 (EDT)
T+15839645ms:   Runtime Error: revert
T+15839645ms: eth_blockNumber
T+15839645ms: net_version
T+15839645ms: eth_call
T+15839645ms:   Transaction: 0x2a5a780547e470bb3a5dd7ff9d710ebe3516ce085c106d6544bedc8aeafa26e0
T+15839645ms:   Gas usage: 42250
T+15839645ms:   Block Number: 716
T+15839645ms:   Block Time: Fri Mar 23 2018 16:45:25 GMT-0400 (EDT)
T+15839655ms: eth_getTransactionReceipt
T+15839655ms: eth_sendTransaction
T+15839658ms: net_version
T+15839658ms: eth_call
T+15839660ms:   Transaction: 0x6d927db65e9d27bc0360d311b929982ae771f6f8ea416780ad5bbd109a960180
T+15839660ms:   Gas usage: 42294
T+15839660ms:   Block Number: 717
T+15839660ms:   Block Time: Fri Mar 23 2018 16:45:26 GMT-0400 (EDT)
T+15839660ms: eth_getTransactionReceipt
T+15839802ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+15839802ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+15839802ms: 
T+15839802ms: TypeError: Cannot read property 'get' of undefined
T+15839802ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+15839802ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+15839802ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+15839802ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+15839802ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+15839802ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+15839802ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+15839802ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+15839802ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+15839802ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #667. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
