### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by fotesco** [trufflesuite/ganache#454]
PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+3454635ms: eth_getTransactionReceipt
T+3454683ms: eth_accounts
T+3454770ms: eth_sendTransaction
T+3454791ms:   Transaction: 0x4eb6c187be6dc4830fccc954895cd16f6db011e1add726270c5f547e44fcb06c
T+3454791ms:   Contract created: 0x98d9f9e8debd4a632682ba207670d2a5acd3c489
T+3454791ms:   Gas usage: 121054
T+3454791ms:   Block Number: 39
T+3454791ms:   Block Time: Fri Mar 23 2018 17:30:17 GMT-0700 (PDT)
T+3454795ms: eth_newBlockFilter
T+3454798ms: eth_getFilterChanges
T+3454803ms: eth_getTransactionReceipt
T+3454809ms: eth_getCode
T+3454815ms: eth_uninstallFilter
T+3454818ms: eth_sendTransaction
T+3454831ms:   Transaction: 0xe5e99c48bfb96cdba21d3d93050d044d7d15b7e1728a5132e8d045e4b104cc74
T+3454831ms:   Contract created: 0x8e4c131b37383e431b9cd0635d3cf9f3f628edae
T+3454831ms:   Gas usage: 114018
T+3454831ms:   Block Number: 40
T+3454831ms:   Block Time: Fri Mar 23 2018 17:30:17 GMT-0700 (PDT)
T+3454834ms: eth_newBlockFilter
T+3454836ms: eth_getFilterChanges
T+3454843ms: eth_getTransactionReceipt
T+3454849ms: eth_getCode
T+3454852ms: eth_uninstallFilter
T+3454855ms: eth_sendTransaction
T+3454868ms:   Transaction: 0xccceb9f7cf3dce01ca61d87139e679c835c3928d07b06494244d2824dbe7d40a
T+3454868ms:   Contract created: 0x1411cb266fced1587b0aa29e9d5a9ef3db64a9c5
T+3454868ms:   Gas usage: 113010
T+3454868ms:   Block Number: 41
T+3454868ms:   Block Time: Fri Mar 23 2018 17:30:17 GMT-0700 (PDT)
T+3454870ms: eth_newBlockFilter
T+3454873ms: eth_getFilterChanges
T+3454879ms: eth_getTransactionReceipt
T+3454883ms: eth_getCode
T+3454887ms: eth_uninstallFilter
T+3454889ms: eth_sendTransaction
T+3454906ms:   Transaction: 0x42b209bf7a7f5e57a7c21c1859b61bae2d3f0d6efad3a035efa3b719258328d7
T+3454906ms:   Contract created: 0x2467636bea0f3c2441227eedbffac59f11d54a80
T+3454906ms:   Gas usage: 106164
T+3454906ms:   Block Number: 42
T+3454906ms:   Block Time: Fri Mar 23 2018 17:30:17 GMT-0700 (PDT)
T+3454909ms: eth_newBlockFilter
T+3454912ms: eth_getFilterChanges
T+3454920ms: eth_getTransactionReceipt
T+3454924ms: eth_getCode
T+3454962ms: eth_uninstallFilter
T+3454965ms: eth_sendTransaction
T+3454984ms:   Transaction: 0x89b45e1d764e07ff57d15646f7ec6b2b3e65b9be9e8093bffc38ed1a404209a1
T+3454984ms:   Gas usage: 26984
T+3454984ms:   Block Number: 43
T+3454984ms:   Block Time: Fri Mar 23 2018 17:30:17 GMT-0700 (PDT)
T+3454986ms: eth_getTransactionReceipt
T+3455015ms: eth_accounts
T+3455041ms: eth_sendTransaction
T+3455071ms:   Transaction: 0x216be1f489241c7b8fcbaf930d619e4da92333e45e74a26d787ef88e9329e292
T+3455071ms:   Contract created: 0x913bbcfea2f347a24cfca441d483e7cbac8de3db
T+3455071ms:   Gas usage: 2672801
T+3455071ms:   Block Number: 44
T+3455071ms:   Block Time: Fri Mar 23 2018 17:30:17 GMT-0700 (PDT)
T+3455073ms: eth_newBlockFilter
T+3455077ms: eth_getFilterChanges
T+3455083ms: eth_getTransactionReceipt
T+3455089ms: eth_getCode
T+3455114ms: eth_uninstallFilter
T+3455117ms: eth_sendTransaction
T+3455136ms:   Transaction: 0x988e233e84089ce35f0d29fd2ce401df2f9a5d425536fca298838a81478276a7
T+3455136ms:   Gas usage: 26984
T+3455136ms:   Block Number: 45
T+3455136ms:   Block Time: Fri Mar 23 2018 17:30:18 GMT-0700 (PDT)
T+3455139ms: eth_getTransactionReceipt
T+3455148ms: eth_accounts
T+3455199ms: eth_sendTransaction
T+3455201ms: eth_sendTransaction
T+3455203ms: eth_sendTransaction
T+3455251ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+3455251ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+3455251ms: 
T+3455251ms: TypeError: Cannot read property 'get' of undefined
T+3455251ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+3455251ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+3455251ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+3455251ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+3455251ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+3455251ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+3455251ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+3455251ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+3455251ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+3455251ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #667. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
