### ISSUE TITLE
System Error when running Ganache 1.0.2 on win32

### ISSUE THREAD

**Issue by AlonNavon** [trufflesuite/ganache#463]
PLATFORM: win32
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+0ms: Starting server with configuration: {"hostname":"127.0.0.1","mnemonic":"candy maple cake sugar pudding cream honey rich smooth crumble sweet treat","network_id":5777,"port":7545,"total_accounts":10,"unlocked_accounts":[]}
T+355ms: Ganache started successfully!
T+355ms: Waiting for requests...
T+7566ms: eth_blockNumber
T+9825ms: eth_getBalance
T+9825ms: eth_gasPrice
T+9825ms: eth_getTransactionCount
T+9858ms: eth_getBalance
T+9858ms: eth_gasPrice
T+9858ms: eth_getTransactionCount
T+12787ms: eth_sendRawTransaction
T+20887ms: eth_getBalance
T+20887ms: eth_gasPrice
T+20887ms: eth_getTransactionCount
T+20908ms: eth_getBalance
T+20908ms: eth_gasPrice
T+20908ms: eth_getTransactionCount
T+37202ms: eth_sendRawTransaction
T+85171ms: eth_getBalance
T+85171ms: eth_gasPrice
T+85171ms: eth_getTransactionCount
T+85187ms: eth_getBalance
T+85187ms: eth_gasPrice
T+85187ms: eth_getTransactionCount
T+87287ms: eth_sendRawTransaction
T+87382ms:   Transaction: 0x2cc75eda29cc5f2e36d1062fdbbf0ebd16ffd964813c6a4a2946ecb18cc31beb
T+87382ms:   Contract created: 0x8cdaf0cd259887258bc13a92c0a6da92698644c0
T+87382ms:   Gas usage: 67762
T+87382ms:   Block Number: 1
T+87382ms:   Block Time: Sun Mar 25 2018 18:53:54 GMT+0300 (Jerusalem Daylight Time)
T+87382ms:   Runtime Error: revert
T+114850ms: eth_call
T+116770ms: eth_call
T+118125ms: eth_call
T+141789ms: eth_call
T+145042ms: eth_call
T+146482ms: eth_call
T+155089ms: eth_call
T+200785ms: eth_estimateGas
T+205612ms: eth_getBalance
T+205612ms: eth_gasPrice
T+205612ms: eth_getTransactionCount
T+205644ms: eth_getBalance
T+205644ms: eth_gasPrice
T+205644ms: eth_getTransactionCount
T+205704ms: eth_estimateGas
T+205712ms: 
T+205712ms: C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:63898
T+205712ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&
T+205712ms: AssertionError: The field to must have byte length of 20
T+205712ms:     at FakeTransaction.setter [as to] (C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:7366:9)
T+205712ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:7416:63
T+205712ms:     at Array.forEach (native)
T+205712ms:     at Object.exports.defineProperties (C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:7415:14)
T+205712ms:     at FakeTransaction.Transaction (C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:78121:13)
T+205712ms:     at FakeTransaction (C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:20454:5)
T+205712ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:80343:14
T+205712ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:21924:5
T+205712ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:55954:5
T+205712ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:56320:14
```

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #668. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
