### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by jackwzp** [trufflesuite/ganache#468]
PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+431026ms: eth_getBalance
T+431031ms: eth_getBalance
T+431031ms: eth_getTransactionReceipt
T+432908ms: eth_getBlockByNumber
T+433252ms: net_version
T+437348ms: eth_accounts
T+437355ms: eth_estimateGas
T+437415ms: net_version
T+437420ms: eth_sendTransaction
T+437471ms:   Transaction: 0xf49e98a22b87ea8305df2dc70694492299e9956c4211bff67305e4808ddb477e
T+437471ms:   Gas usage: 77160
T+437471ms:   Block Number: 7
T+437471ms:   Block Time: Wed Mar 28 2018 16:16:52 GMT-0400 (EDT)
T+437476ms: net_version
T+437481ms: eth_getTransactionReceipt
T+437498ms: eth_getTransactionByHash
T+437498ms: eth_getBalance
T+437512ms: eth_getBalance
T+437519ms: eth_getBalance
T+437519ms: eth_getBalance
T+437519ms: eth_getBalance
T+437524ms: eth_getBalance
T+437536ms: eth_getBalance
T+437542ms: eth_getBalance
T+437542ms: eth_getBalance
T+437542ms: eth_getBalance
T+437542ms: eth_getBalance
T+437560ms: eth_getBalance
T+437567ms: eth_getBalance
T+437567ms: eth_getBalance
T+437567ms: eth_getBalance
T+437567ms: eth_getBalance
T+437572ms: eth_getBalance
T+437587ms: eth_getBalance
T+437587ms: eth_getBalance
T+437596ms: eth_getBalance
T+437596ms: eth_getTransactionReceipt
T+438254ms: net_version
T+438291ms: eth_getBalance
T+438301ms: eth_getBalance
T+438301ms: eth_getBalance
T+438301ms: eth_getBalance
T+438301ms: eth_getBalance
T+438301ms: eth_getBalance
T+438301ms: eth_getBalance
T+438301ms: eth_getBalance
T+438301ms: eth_getBalance
T+438320ms: eth_getBalance
T+438320ms: eth_getBalance
T+438320ms: eth_getBalance
T+438326ms: eth_getBalance
T+438326ms: eth_getBalance
T+438326ms: eth_getBalance
T+438326ms: eth_getBalance
T+438326ms: eth_getBalance
T+438326ms: eth_getBalance
T+438326ms: eth_getBalance
T+438326ms: eth_getBalance
T+439840ms: eth_call
T+439879ms: eth_call
T+439940ms: eth_call
T+439984ms: eth_call
T+439989ms: eth_call
T+443754ms: net_version
T+448743ms: eth_getBlockByNumber
T+448757ms: net_version
T+448757ms: eth_getBalance
T+448757ms: eth_getBalance
T+448757ms: eth_getBalance
T+448757ms: eth_getBalance
T+448767ms: eth_getBalance
T+448767ms: eth_getBalance
T+448775ms: eth_getBalance
T+448775ms: eth_getBalance
T+448775ms: eth_getBalance
T+448775ms: eth_getBalance
T+448781ms: eth_getBalance
T+448781ms: eth_getBalance
T+448781ms: eth_getBalance
T+448781ms: eth_getBalance
T+448781ms: eth_getBalance
T+448789ms: eth_getBalance
T+448789ms: eth_getBalance
T+448789ms: eth_getBalance
T+448789ms: eth_getBalance
T+448794ms: eth_getBalance
T+453754ms: net_version
T+458748ms: net_version
T+458748ms: eth_getBalance
T+458748ms: eth_getBalance
T+458822ms: eth_getBalance
T+458822ms: eth_getBalance
T+458822ms: eth_getBalance
T+458822ms: eth_getBalance
T+458822ms: eth_getBalance
T+458822ms: eth_getBalance
T+458822ms: eth_getBalance
T+458822ms: eth_getBalance
T+458822ms: eth_getBalance
T+458822ms: eth_getBalance
T+458822ms: eth_getBalance
T+458822ms: eth_getBalance
T+458822ms: eth_getBalance
T+458822ms: eth_getBalance
T+458822ms: eth_getBalance
T+458822ms: eth_getBalance
T+458822ms: eth_getBalance
T+458822ms: eth_getBalance
T+463742ms: eth_getBlockByNumber
T+463750ms: net_version
T+468663ms: eth_call
T+468730ms: eth_call
T+468824ms: net_version
T+468824ms: eth_getBalance
T+468824ms: eth_getBalance
T+468844ms: eth_getBalance
T+468844ms: eth_getBalance
T+468844ms: eth_getBalance
T+468844ms: eth_getBalance
T+468871ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+468871ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+468871ms: 
T+468871ms: TypeError: Cannot read property 'get' of undefined
T+468871ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+468871ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+468871ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+468871ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+468871ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+468871ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+468871ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+468871ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+468871ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+468871ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #667. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
