### ISSUE TITLE
System Error when running Ganache 1.0.2 on win32

### ISSUE THREAD

**Issue by mussawir** [trufflesuite/ganache#469]
PLATFORM: win32
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+21439ms: eth_getBalance
T+21442ms: eth_getBalance
T+21445ms: eth_getBalance
T+21447ms: eth_getBalance
T+21449ms: eth_getBalance
T+21451ms: eth_getBalance
T+21454ms: eth_getBalance
T+21456ms: eth_getBalance
T+21458ms: eth_getBalance
T+21461ms: eth_getBalance
T+21463ms: eth_getBalance
T+21466ms: eth_getBalance
T+21468ms: eth_getBalance
T+21471ms: eth_getBalance
T+21473ms: eth_getBalance
T+21476ms: eth_getBalance
T+21478ms: eth_getBalance
T+21480ms: eth_getBalance
T+21483ms: eth_getBalance
T+21487ms: eth_getBalance
T+21489ms: eth_getBalance
T+21491ms: eth_getBalance
T+21494ms: eth_getBalance
T+21495ms: eth_getBalance
T+21497ms: eth_getBalance
T+21499ms: eth_getBalance
T+21500ms: eth_getBalance
T+21502ms: eth_getBalance
T+21504ms: eth_getBalance
T+21505ms: eth_getBalance
T+21507ms: eth_getBalance
T+21508ms: eth_getBalance
T+21510ms: eth_getBlockByNumber
T+21512ms: net_version
T+21513ms: eth_estimateGas
T+21515ms: net_version
T+21515ms: eth_getBalance
T+21515ms: eth_getBalance
T+21515ms: eth_getBalance
T+21515ms: eth_getBalance
T+21517ms: eth_getBalance
T+21518ms: eth_getBalance
T+21518ms: eth_getBalance
T+21520ms: eth_getBalance
T+21521ms: eth_getBalance
T+21523ms: eth_getBalance
T+21525ms: eth_getBalance
T+21526ms: eth_getBalance
T+21526ms: eth_getBalance
T+21526ms: eth_getBalance
T+21528ms: eth_getBalance
T+21529ms: eth_getBalance
T+21531ms: eth_getBalance
T+21533ms: eth_getBalance
T+21535ms: eth_getBalance
T+21537ms: eth_getBalance
T+21539ms: eth_getBalance
T+21541ms: eth_getBalance
T+21543ms: eth_getBalance
T+21544ms: eth_getBalance
T+21546ms: eth_getBalance
T+21548ms: eth_getBalance
T+21550ms: eth_getBalance
T+21552ms: eth_getBalance
T+21554ms: eth_getBalance
T+21557ms: eth_getBalance
T+21559ms: eth_getBalance
T+21561ms: eth_getBalance
T+21563ms: eth_getBalance
T+21564ms: eth_getBalance
T+21566ms: eth_getBalance
T+21568ms: eth_getBalance
T+21570ms: eth_getBalance
T+21570ms: eth_getBalance
T+21572ms: eth_getBalance
T+21574ms: eth_getBalance
T+21577ms: eth_getBalance
T+21579ms: eth_getBalance
T+21581ms: eth_getBalance
T+21583ms: eth_getBalance
T+21584ms: eth_getBalance
T+21586ms: eth_getBalance
T+21588ms: eth_getBalance
T+21590ms: eth_getBalance
T+21592ms: eth_getBalance
T+21594ms: eth_getBalance
T+21596ms: eth_getBalance
T+21598ms: eth_getBalance
T+21599ms: eth_getBalance
T+21601ms: eth_getBalance
T+21603ms: eth_getBalance
T+21606ms: eth_getBalance
T+21608ms: eth_getBalance
T+21610ms: eth_getBalance
T+21613ms: eth_getBalance
T+21615ms: eth_getBalance
T+21617ms: eth_getBalance
T+21619ms: eth_getBalance
T+21621ms: eth_getBalance
T+21624ms: eth_getBalance
T+21626ms: eth_getBalance
T+21628ms: eth_getBalance
T+21630ms: eth_getBalance
T+21630ms: eth_getBalance
T+21632ms: eth_getBalance
T+21634ms: eth_getBalance
T+21636ms: eth_getBalance
T+21638ms: eth_getBalance
T+21638ms: eth_getBalance
T+21642ms: eth_getBalance
T+21644ms: eth_getBalance
T+21647ms: eth_getBalance
T+21649ms: eth_getBalance
T+21652ms: eth_getBalance
T+21654ms: eth_getBalance
T+21657ms: eth_getBalance
T+21660ms: C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:63898
T+21660ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&
T+21660ms: 
T+21660ms: TypeError: Cannot read property 'get' of undefined
T+21660ms:     at dbGet (C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:56029:7)
T+21660ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:17614:5
T+21660ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:23091:20
T+21660ms:     at iterate (C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:23172:13)
T+21660ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:23184:29
T+21660ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:22954:16
T+21660ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:17619:7
T+21660ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:56034:9
T+21660ms:     at dispatchError (C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:36358:36)
T+21660ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:22744:14
```

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #667. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
