### ISSUE TITLE
System Error when running Ganache 1.0.2 on win32

### ISSUE THREAD

**Issue by seanxlliu** [trufflesuite/ganache#477]
PLATFORM: win32
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+8382536ms:   Runtime Error: invalid opcode
T+8383478ms: eth_call
T+8383492ms: eth_getBlockByNumber
T+8383496ms: eth_sendTransaction
T+8383516ms:   Transaction: 0x4baa876232d5561401bdec54baced0abb3ce5dfd18b32201d3f4d8774b25bcb2
T+8383516ms:   Gas usage: 210000
T+8383516ms:   Block Number: 134
T+8383516ms:   Block Time: Fri Mar 30 2018 16:16:17 GMT+0800 (中国标准时间)
T+8383516ms:   Runtime Error: invalid opcode
T+8384467ms: eth_getBlockByNumber
T+8384476ms: eth_getBlockByNumber
T+8384479ms: eth_call
T+8384480ms: eth_getBalance
T+8384482ms: eth_getBalance
T+8384485ms: eth_getBlockByNumber
T+8384488ms: eth_getBalance
T+8384491ms: eth_getBlockByNumber
T+8384493ms: eth_getBalance
T+8384496ms: eth_getBalance
T+8384499ms: eth_getBlockByNumber
T+8384502ms: eth_getBalance
T+8384503ms: eth_getBlockByNumber
T+8384506ms: eth_sendTransaction
T+8384508ms: eth_getBlockByNumber
T+8384510ms: eth_getBalance
T+8384511ms: eth_getBalance
T+8384517ms: eth_getBlockByNumber
T+8384520ms: eth_getBalance
T+8384523ms: eth_getBalance
T+8384527ms: eth_getBlockByNumber
T+8384529ms: eth_getBalance
T+8384532ms:   Transaction: 0x2c483050dca0d4acb3480e00fb80a97097578d4549a1e407d0c120ed79fbbac0
T+8384532ms:   Gas usage: 210000
T+8384532ms:   Block Number: 135
T+8384532ms:   Block Time: Fri Mar 30 2018 16:16:18 GMT+0800 (中国标准时间)
T+8384534ms:   Runtime Error: invalid opcode
T+8384536ms: eth_getBlockByNumber
T+8384538ms: eth_getBalance
T+8384540ms: eth_getBalance
T+8384545ms: eth_getBlockByNumber
T+8384547ms: eth_getBalance
T+8384548ms: eth_getBalance
T+8384905ms: eth_call
T+8385478ms: eth_call
T+8385496ms: eth_getBlockByNumber
T+8385500ms: eth_sendTransaction
T+8385521ms:   Transaction: 0x275f8606ee081a661d3d6d2cc432e62d0ce65c99ef1d0b4f3bd5159fc867b481
T+8385521ms:   Gas usage: 210000
T+8385521ms:   Block Number: 136
T+8385521ms:   Block Time: Fri Mar 30 2018 16:16:19 GMT+0800 (中国标准时间)
T+8385521ms:   Runtime Error: invalid opcode
T+8386479ms: eth_call
T+8386491ms: eth_getBlockByNumber
T+8386494ms: eth_sendTransaction
T+8386510ms:   Transaction: 0x4b04b9f4f0233cea8b687572cfe7720a232f17bd80238c8d060b74328e24b7ab
T+8386510ms:   Gas usage: 210000
T+8386510ms:   Block Number: 137
T+8386510ms:   Block Time: Fri Mar 30 2018 16:16:20 GMT+0800 (中国标准时间)
T+8386510ms:   Runtime Error: invalid opcode
T+8387026ms: eth_getBlockByNumber
T+8387036ms: eth_getBlockByNumber
T+8387043ms: eth_getBalance
T+8387046ms: eth_getBalance
T+8387049ms: eth_getBalance
T+8387060ms: eth_getBalance
T+8387063ms: eth_getBalance
T+8387067ms: eth_getBalance
T+8387070ms: eth_getBalance
T+8387072ms: eth_getBalance
T+8387076ms: eth_getBalance
T+8387078ms: eth_getBalance
T+8387082ms: eth_getBlockByNumber
T+8387088ms: eth_call
T+8387093ms: eth_getBlockByNumber
T+8387098ms: eth_getBalance
T+8387103ms: eth_getBalance
T+8387105ms: eth_getBalance
T+8387163ms: C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:63898
T+8387163ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&
T+8387163ms: 
T+8387163ms: TypeError: Cannot read property 'get' of undefined
T+8387163ms:     at dbGet (C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:56029:7)
T+8387163ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:17614:5
T+8387163ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:23091:20
T+8387163ms:     at iterate (C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:23172:13)
T+8387163ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:23184:29
T+8387163ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:22954:16
T+8387163ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:17619:7
T+8387163ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:56034:9
T+8387163ms:     at dispatchError (C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:36358:36)
T+8387163ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:22744:14
```

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #667. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
