### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by leonmak** [trufflesuite/ganache#478]
PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+391830621ms: eth_getFilterChanges
T+391831128ms: eth_getFilterChanges
T+391831628ms: eth_getFilterChanges
T+391832130ms: eth_getFilterChanges
T+391832631ms: eth_getFilterChanges
T+391833136ms: eth_getFilterChanges
T+391833639ms: eth_getFilterChanges
T+391834140ms: eth_getFilterChanges
T+391834643ms: eth_getFilterChanges
T+391835149ms: eth_getFilterChanges
T+391835650ms: eth_getFilterChanges
T+391836154ms: eth_getFilterChanges
T+391836660ms: eth_getFilterChanges
T+391837163ms: eth_getFilterChanges
T+391837670ms: eth_getFilterChanges
T+391838173ms: eth_getFilterChanges
T+391838675ms: eth_getFilterChanges
T+391839177ms: eth_getFilterChanges
T+391839677ms: eth_getFilterChanges
T+391840180ms: eth_getFilterChanges
T+391840685ms: eth_getFilterChanges
T+391841187ms: eth_getFilterChanges
T+391841695ms: eth_getFilterChanges
T+391842192ms: eth_getFilterChanges
T+391842691ms: eth_getFilterChanges
T+391843193ms: eth_getFilterChanges
T+391843694ms: eth_getFilterChanges
T+391844200ms: eth_getFilterChanges
T+391844702ms: eth_getFilterChanges
T+391845203ms: eth_getFilterChanges
T+391845704ms: eth_getFilterChanges
T+391846209ms: eth_getFilterChanges
T+391846715ms: eth_getFilterChanges
T+391847216ms: eth_getFilterChanges
T+391847720ms: eth_getFilterChanges
T+391848219ms: eth_getFilterChanges
T+391848720ms: eth_getFilterChanges
T+391849225ms: eth_getFilterChanges
T+391849730ms: eth_getFilterChanges
T+391850233ms: eth_getFilterChanges
T+391850738ms: eth_getFilterChanges
T+391851237ms: eth_getFilterChanges
T+391851737ms: eth_getFilterChanges
T+391852240ms: eth_getFilterChanges
T+391852743ms: eth_getFilterChanges
T+391853247ms: eth_getFilterChanges
T+391853750ms: eth_getFilterChanges
T+391854250ms: eth_getFilterChanges
T+391854754ms: eth_getFilterChanges
T+391855258ms: eth_getFilterChanges
T+391855764ms: eth_getFilterChanges
T+391856270ms: eth_getFilterChanges
T+391856770ms: eth_getFilterChanges
T+391857271ms: eth_getFilterChanges
T+391857770ms: eth_getFilterChanges
T+391858274ms: eth_getFilterChanges
T+391858776ms: eth_getFilterChanges
T+391859287ms: eth_getFilterChanges
T+391859784ms: eth_getFilterChanges
T+391860287ms: eth_getFilterChanges
T+391860791ms: eth_getFilterChanges
T+391861292ms: eth_getFilterChanges
T+391861796ms: eth_getFilterChanges
T+391862300ms: eth_getFilterChanges
T+391862803ms: eth_getFilterChanges
T+391863303ms: eth_getFilterChanges
T+391863809ms: eth_getFilterChanges
T+391864311ms: eth_getFilterChanges
T+391864820ms: eth_getFilterChanges
T+391865321ms: eth_getFilterChanges
T+391865824ms: eth_getFilterChanges
T+391866328ms: eth_getFilterChanges
T+391866834ms: eth_getFilterChanges
T+391867337ms: eth_getFilterChanges
T+391867840ms: eth_getFilterChanges
T+391868344ms: eth_getFilterChanges
T+391868846ms: eth_getFilterChanges
T+391869349ms: eth_getFilterChanges
T+391869858ms: eth_getFilterChanges
T+391870360ms: eth_getFilterChanges
T+391870862ms: eth_getFilterChanges
T+391871370ms: eth_getFilterChanges
T+391871870ms: eth_getFilterChanges
T+391872372ms: eth_getFilterChanges
T+391872875ms: eth_getFilterChanges
T+391873378ms: eth_getFilterChanges
T+391873882ms: eth_getFilterChanges
T+391874387ms: eth_getFilterChanges
T+391874890ms: eth_getFilterChanges
T+391875388ms: eth_getFilterChanges
T+391875895ms: eth_getFilterChanges
T+391876394ms: eth_getFilterChanges
T+391876896ms: eth_getFilterChanges
T+391877400ms: eth_getFilterChanges
T+391877902ms: eth_getFilterChanges
T+391878321ms: eth_accounts
T+391878338ms: eth_accounts
T+391878351ms: eth_sendTransaction
T+391878382ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+391878382ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+391878382ms: 
T+391878382ms: TypeError: Cannot read property 'pop' of undefined
T+391878382ms:     at CheckpointTrie.Trie._updateNode (/node_modules/ganache-cli/build/lib.node.js:56237:23)
T+391878382ms:     at /node_modules/ganache-cli/build/lib.node.js:55984:16
T+391878382ms:     at /node_modules/ganache-cli/build/lib.node.js:56320:14
T+391878382ms:     at processNode (/node_modules/ganache-cli/build/lib.node.js:56325:23)
T+391878382ms:     at /node_modules/ganache-cli/build/lib.node.js:56363:11
T+391878382ms:     at /node_modules/ganache-cli/build/lib.node.js:56057:7
T+391878382ms:     at /node_modules/ganache-cli/build/lib.node.js:17623:7
T+391878382ms:     at /node_modules/ganache-cli/build/lib.node.js:22962:16
T+391878382ms:     at /node_modules/ganache-cli/build/lib.node.js:23179:32
T+391878382ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
```

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #669. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
