### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by sidsaha** [trufflesuite/ganache#479]
PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+4179644ms:   Contract created: 0xe28158ecfde143e2536761c3254c7c31efd97271
T+4179644ms:   Gas usage: 268535
T+4179644ms:   Block Number: 88
T+4179644ms:   Block Time: Sat Mar 31 2018 01:19:14 GMT+0530 (IST)
T+4179647ms: eth_newBlockFilter
T+4179651ms: eth_getFilterChanges
T+4179660ms: eth_getTransactionReceipt
T+4179666ms: eth_getCode
T+4179680ms: eth_uninstallFilter
T+4179680ms: eth_sendTransaction
T+4179715ms:   Transaction: 0xb12686eea8719f869042ca7a9bec1ab03c66c270b18f9b176ecafda7883309f4
T+4179715ms:   Gas usage: 41981
T+4179715ms:   Block Number: 89
T+4179715ms:   Block Time: Sat Mar 31 2018 01:19:14 GMT+0530 (IST)
T+4179718ms: eth_getTransactionReceipt
T+4184337ms: net_version
T+4184347ms: eth_accounts
T+4184387ms: eth_accounts
T+4226936ms: net_version
T+4226945ms: eth_accounts
T+4226954ms: eth_accounts
T+4226983ms: eth_sendTransaction
T+4227017ms:   Transaction: 0x68ef454e124c30e0d3d585508892a1a1afb17793ed659f054833bc34c5d2ecf8
T+4227017ms:   Contract created: 0xb3756baf00a7e62ee5a18a32ea39db2af5ede7fe
T+4227017ms:   Gas usage: 268535
T+4227017ms:   Block Number: 90
T+4227017ms:   Block Time: Sat Mar 31 2018 01:20:01 GMT+0530 (IST)
T+4227021ms: eth_newBlockFilter
T+4227024ms: eth_getFilterChanges
T+4227032ms: eth_getTransactionReceipt
T+4227038ms: eth_getCode
T+4227050ms: eth_uninstallFilter
T+4227052ms: eth_sendTransaction
T+4227074ms:   Transaction: 0x0370727fd2f41d0531c28d2e5e10b081370e5986423b1246bf07055e341ffdaa
T+4227074ms:   Gas usage: 41981
T+4227074ms:   Block Number: 91
T+4227074ms:   Block Time: Sat Mar 31 2018 01:20:01 GMT+0530 (IST)
T+4227078ms: eth_getTransactionReceipt
T+4231524ms: net_version
T+4231534ms: eth_accounts
T+4231562ms: eth_accounts
T+4251700ms: net_version
T+4251712ms: eth_accounts
T+4251719ms: eth_accounts
T+4251747ms: eth_sendTransaction
T+4251785ms:   Transaction: 0x3084f1209a293885328199371b417b0aad1ebdf5b5d8b4cf6a8af4f3dbf04e87
T+4251785ms:   Contract created: 0x9fd9828a17ef3402540e9d53e25b7e785021dc6e
T+4251785ms:   Gas usage: 268535
T+4251785ms:   Block Number: 92
T+4251785ms:   Block Time: Sat Mar 31 2018 01:20:26 GMT+0530 (IST)
T+4251788ms: eth_newBlockFilter
T+4251791ms: eth_getFilterChanges
T+4251799ms: eth_getTransactionReceipt
T+4251804ms: eth_getCode
T+4251816ms: eth_uninstallFilter
T+4251820ms: eth_sendTransaction
T+4251842ms:   Transaction: 0x679c09be0010262c01b3d92c5f368cd8891de6526a061bbd3e98dfc811058054
T+4251842ms:   Gas usage: 41981
T+4251842ms:   Block Number: 93
T+4251842ms:   Block Time: Sat Mar 31 2018 01:20:26 GMT+0530 (IST)
T+4251845ms: eth_getTransactionReceipt
T+4256230ms: net_version
T+4256240ms: eth_accounts
T+4256267ms: eth_accounts
T+4280267ms: net_version
T+4280277ms: eth_accounts
T+4280288ms: eth_accounts
T+4280317ms: eth_sendTransaction
T+4280355ms:   Transaction: 0x3cfc1f5df9c02297339b33b3d64ecf8797dcd33badaaf5539195f8563870e18f
T+4280355ms:   Contract created: 0xaa862ddac09f6736a61e1124040fd883a6533c19
T+4280355ms:   Gas usage: 268535
T+4280355ms:   Block Number: 94
T+4280355ms:   Block Time: Sat Mar 31 2018 01:20:54 GMT+0530 (IST)
T+4280360ms: eth_newBlockFilter
T+4280364ms: eth_getFilterChanges
T+4280372ms: eth_getTransactionReceipt
T+4280381ms: eth_getCode
T+4280422ms: eth_uninstallFilter
T+4280426ms: eth_sendTransaction
T+4280464ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+4280464ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+4280464ms: 
T+4280464ms: TypeError: Cannot read property 'get' of undefined
T+4280464ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+4280464ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+4280464ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+4280464ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+4280464ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+4280464ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+4280464ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+4280464ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+4280464ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+4280464ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #667. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
