### ISSUE TITLE
System Error when running Ganache 1.1.0 on darwin

### ISSUE THREAD

**Issue by CirrusThink** [trufflesuite/ganache#482]
PLATFORM: darwin
GANACHE VERSION: 1.1.0

EXCEPTION:
```
Error: listen EADDRNOTAVAIL 108.189.244.140:7545
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at Server.setupListenHandle [as _listen2] (net.js:1302:19)
    at listenInCluster (net.js:1367:12)
    at doListen (net.js:1493:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: Starting server with initial configuration: {"hostname":"xxx.xxx.xxx.xxx","port":7545,"network_id":5777,"total_accounts":10,"unlocked_accounts":[],"vmErrorsOnRPCResponse":true}
```

**Comment by hacktar** [comment]
Seems you put a custom IP in settings.
If you changed IP in Settings and now it doesn't start anymore, you could change it to 127.0.0.1 manually editing the Settings file in ~/Library/Application\ Support/Ganache/

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #666. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
