### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by adilw3nomad** [trufflesuite/ganache#485]
Sorry man I had ganache in the background and left it running, changed a js test and re ran it after not using ganache for an hour or two, got this error. 

PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+214077ms: eth_getTransactionReceipt
T+214079ms: eth_call
T+214085ms: eth_sendTransaction
T+214111ms:   Transaction: 0x47cdc4185fef9f7420cd985f3ac27aa4b925a3be63e8834eeacb3dfcbab74043
T+214111ms:   Gas usage: 41938
T+214111ms:   Block Number: 37
T+214114ms:   Block Time: Mon Apr 02 2018 13:31:39 GMT+0100 (BST)
T+214116ms: eth_getTransactionReceipt
T+214120ms: eth_call
T+2191986ms: eth_accounts
T+2192003ms: eth_accounts
T+2198006ms: eth_accounts
T+2198097ms: eth_sendTransaction
T+2198144ms:   Transaction: 0x538e3e6bc60e756ebaf597d9e07e9b97c1385f675ee81be8c6d42edcd1250f91
T+2198144ms:   Contract created: 0xd54b47f8e6a1b97f3a84f63c867286272b273b7c
T+2198144ms:   Gas usage: 269607
T+2198144ms:   Block Number: 38
T+2198144ms:   Block Time: Mon Apr 02 2018 14:04:43 GMT+0100 (BST)
T+2198146ms: eth_newBlockFilter
T+2198150ms: eth_getFilterChanges
T+2198159ms: eth_getTransactionReceipt
T+2198165ms: eth_getCode
T+2198174ms: eth_uninstallFilter
T+2198176ms: eth_sendTransaction
T+2198191ms:   Transaction: 0x22b6349c82f24e9c62c3c10fc47ee70d49cc667d2c8c57560e37763a317d3e30
T+2198191ms:   Gas usage: 41981
T+2198191ms:   Block Number: 39
T+2198191ms:   Block Time: Mon Apr 02 2018 14:04:43 GMT+0100 (BST)
T+2198193ms: eth_getTransactionReceipt
T+2198199ms: eth_accounts
T+2198321ms: eth_sendTransaction
T+2198337ms:   Transaction: 0x9fd0a1879e4def19a0f6947ae79e84902da490247822b3205db5882c2b73edf9
T+2198337ms:   Contract created: 0xcfed223fab2a41b5a5a5f9aaae2d1e882cb6fe2d
T+2198337ms:   Gas usage: 402288
T+2198337ms:   Block Number: 40
T+2198337ms:   Block Time: Mon Apr 02 2018 14:04:44 GMT+0100 (BST)
T+2198340ms: eth_newBlockFilter
T+2198343ms: eth_getFilterChanges
T+2198349ms: eth_getTransactionReceipt
T+2198353ms: eth_getCode
T+2198357ms: eth_uninstallFilter
T+2198359ms: eth_sendTransaction
T+2198370ms:   Transaction: 0x120cb4052b98010189649bb7b86dcf8a06f9e1f55db8a06f2621e794ae1be94f
T+2198370ms:   Contract created: 0x8273e4b8ed6c78e252a9fca5563adfcc75c91b2a
T+2198370ms:   Gas usage: 94828
T+2198370ms:   Block Number: 41
T+2198370ms:   Block Time: Mon Apr 02 2018 14:04:44 GMT+0100 (BST)
T+2198372ms: eth_newBlockFilter
T+2198376ms: eth_getFilterChanges
T+2198381ms: eth_getTransactionReceipt
T+2198384ms: eth_getCode
T+2198411ms: eth_uninstallFilter
T+2198411ms: eth_sendTransaction
T+2198448ms:   Transaction: 0xc1fdc6222f4c23ca7818ba4f886cc4b67d076bc740a06238ac9abd9586f6ad2d
T+2198448ms:   Gas usage: 26981
T+2198448ms:   Block Number: 42
T+2198448ms:   Block Time: Mon Apr 02 2018 14:04:44 GMT+0100 (BST)
T+2198450ms: eth_getTransactionReceipt
T+2199652ms: evm_snapshot
T+2199681ms: eth_blockNumber
T+2199685ms: eth_call
T+2199699ms: eth_call
T+2199711ms: eth_sendTransaction
T+2199729ms:   Transaction: 0x819af3557b36eae69721da3d9cb1b5603e9a183727179622f3d85b42ada06bcc
T+2199729ms:   Gas usage: 41579
T+2199729ms:   Block Number: 43
T+2199729ms:   Block Time: Mon Apr 02 2018 14:04:45 GMT+0100 (BST)
T+2199733ms: eth_getTransactionReceipt
T+2199735ms: eth_call
T+2199750ms: eth_blockNumber
T+2199753ms: eth_call
T+2199763ms: eth_blockNumber
T+2199766ms: eth_call
T+2199778ms: eth_blockNumber
T+2199780ms: eth_call
T+2199789ms: eth_call
T+2199810ms: eth_blockNumber
T+2199814ms: eth_call
T+2199825ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+2199825ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+2199825ms: 
T+2199825ms: TypeError: Cannot read property 'get' of undefined
T+2199825ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+2199825ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+2199825ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+2199825ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+2199825ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+2199825ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+2199825ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+2199825ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+2199825ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+2199825ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by adilw3nomad** [comment]
Just to be clear, I restarted Ganache and it's working fine. Not a persistent problem

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #667. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
