### ISSUE TITLE
System Error when running Ganache 1.1.0 on darwin

### ISSUE THREAD

**Issue by johnhforrest** [trufflesuite/ganache#486]
PLATFORM: darwin
GANACHE VERSION: 1.1.0

EXCEPTION:
```
Error: accept EMFILE
    at exports._errnoException (util.js:1024:11)
    at TCP.onconnection (net.js:1529:24)
```

APPLICATION LOG:
```
T+154199361ms: eth_getBlockByNumber
T+154199364ms: eth_getBlockByNumber
T+154199367ms: eth_getBlockByNumber
T+154199371ms: eth_getBlockByNumber
T+154199371ms: eth_getBlockByNumber
T+154199371ms: eth_getBlockByNumber
T+154199377ms: eth_getBlockByNumber
T+154199386ms: eth_getBlockByNumber
T+154199390ms: eth_getBlockByNumber
T+154199392ms: eth_getBlockByNumber
T+154199396ms: eth_getBlockByNumber
T+154199399ms: eth_getBlockByNumber
T+154199404ms: eth_getBlockByNumber
T+154199407ms: eth_getBlockByNumber
T+154199410ms: eth_getBlockByNumber
T+154199412ms: eth_getBlockByNumber
T+154199416ms: eth_getBlockByNumber
T+154199420ms: eth_getBlockByNumber
T+154199420ms: eth_getBlockByNumber
T+154199423ms: eth_getBlockByNumber
T+154199426ms: eth_getBlockByNumber
T+154199429ms: eth_getBlockByNumber
T+154199432ms: eth_getBlockByNumber
T+154199436ms: eth_getBlockByNumber
T+154199440ms: eth_getBlockByNumber
T+154199440ms: eth_getBlockByNumber
T+154199445ms: eth_getBlockByNumber
T+154199445ms: eth_getBlockByNumber
T+154199450ms: eth_getBlockByNumber
T+154199455ms: eth_getBlockByNumber
T+154199459ms: eth_getBlockByNumber
T+154199466ms: eth_getBlockByNumber
T+154199471ms: eth_getBlockByNumber
T+154199474ms: eth_getBlockByNumber
T+154199478ms: eth_getBlockByNumber
T+154199484ms: eth_getBlockByNumber
T+154199488ms: eth_getBlockByNumber
T+154199493ms: eth_getBlockByNumber
T+154199497ms: eth_getBlockByNumber
T+154199501ms: eth_getBlockByNumber
T+154199505ms: eth_getBlockByNumber
T+154199509ms: evm_mine
T+154199515ms: eth_getBlockByNumber
T+154199519ms: eth_getBlockByNumber
T+154199524ms: eth_getBlockByNumber
T+154199528ms: eth_getBlockByNumber
T+154199534ms: eth_getBlockByNumber
T+154199538ms: eth_getBlockByNumber
T+154199542ms: eth_getBlockByNumber
T+154199546ms: eth_getBlockByNumber
T+154199552ms: eth_getBlockByNumber
T+154199556ms: eth_getBlockByNumber
T+154199561ms: eth_getBlockByNumber
T+154199565ms: eth_getBlockByNumber
T+154199571ms: eth_getBlockByNumber
T+154199571ms: eth_getBlockByNumber
T+154199575ms: eth_getBlockByNumber
T+154199579ms: eth_getBlockByNumber
T+154199583ms: eth_getBlockByNumber
T+154199588ms: eth_getBlockByNumber
T+154199588ms: eth_getBlockByNumber
T+154199593ms: eth_getBlockByNumber
T+154199596ms: eth_getBlockByNumber
T+154199600ms: eth_getBlockByNumber
T+154199605ms: eth_getBlockByNumber
T+154199608ms: eth_getBlockByNumber
T+154199612ms: eth_getBlockByNumber
T+154199612ms: eth_getBlockByNumber
T+154199616ms: eth_getBlockByNumber
T+154199620ms: eth_getBlockByNumber
T+154199623ms: eth_getBlockByNumber
T+154199626ms: eth_getBlockByNumber
T+154199630ms: eth_getBlockByNumber
T+154199633ms: eth_getBlockByNumber
T+154199636ms: eth_getBlockByNumber
T+154199639ms: eth_getBlockByNumber
T+154199642ms: eth_getBlockByNumber
T+154199642ms: eth_getBlockByNumber
T+154199645ms: eth_getBlockByNumber
T+154199649ms: eth_getBlockByNumber
T+154199649ms: eth_getBlockByNumber
T+154199653ms: eth_getBlockByNumber
T+154199653ms: eth_getBlockByNumber
T+154199657ms: eth_getBlockByNumber
T+154199660ms: eth_getBlockByNumber
T+154199663ms: eth_getBlockByNumber
T+154199663ms: eth_getBlockByNumber
T+154199667ms: eth_getBlockByNumber
T+154199670ms: eth_getBlockByNumber
T+154199673ms: eth_getBlockByNumber
T+154199676ms: eth_getBlockByNumber
T+154199679ms: eth_getBlockByNumber
T+154199679ms: eth_getBlockByNumber
T+154199682ms: eth_getBlockByNumber
T+154199686ms: eth_getBlockByNumber
T+154199689ms: eth_getBlockByNumber
T+154199692ms: eth_getBlockByNumber
T+154199695ms: eth_getBlockByNumber
T+154199698ms: eth_getBlockByNumber
T+154199702ms: eth_getBlockByNumber
T+154199705ms: eth_getBlockByNumber
T+154199708ms: eth_getBlockByNumber
T+154199711ms: eth_getBlockByNumber
T+154199715ms: eth_getBlockByNumber
T+154199719ms: eth_getBlockByNumber
T+154199722ms: eth_getBlockByNumber
T+154199726ms: eth_getBlockByNumber
T+154199730ms: eth_getBlockByNumber
T+154199734ms: eth_getBlockByNumber
T+154199734ms: eth_getBlockByNumber
T+154199739ms: eth_getBlockByNumber
T+154199743ms: eth_getBlockByNumber
T+154199746ms: eth_getBlockByNumber
T+154199751ms: eth_getBlockByNumber
T+154199757ms: eth_getBlockByNumber
T+154199761ms: eth_getBlockByNumber
T+154199766ms: eth_getBlockByNumber
T+154199772ms: eth_getBlockByNumber
T+154199776ms: eth_getBlockByNumber
T+154199779ms: eth_getBlockByNumber
T+154199784ms: eth_getBlockByNumber
T+154199784ms: eth_getBlockByNumber
T+154199788ms: eth_getBlockByNumber
T+154199793ms: eth_getBlockByNumber
T+154199797ms: eth_getBlockByNumber
T+154199797ms: eth_getBlockByNumber
T+154199803ms: eth_getBlockByNumber
T+154199809ms: eth_getBlockByNumber
T+154199809ms: eth_getBlockByNumber
T+154199814ms: eth_getBlockByNumber
T+154199819ms: eth_getBlockByNumber
T+154199823ms: eth_getBlockByNumber
T+154199827ms: eth_getBlockByNumber
T+154199831ms: eth_getBlockByNumber
T+154199831ms: eth_getBlockByNumber
T+154199837ms: eth_getBlockByNumber
T+154199841ms: eth_getBlockByNumber
T+154199847ms: eth_getBlockByNumber
T+154199852ms: eth_getBlockByNumber
T+154199856ms: eth_getBlockByNumber
T+154199860ms: eth_getBlockByNumber
T+154199866ms: eth_getBlockByNumber
T+154199866ms: eth_getBlockByNumber
T+154199870ms: eth_getBlockByNumber
T+154199870ms: eth_getBlockByNumber
T+154199875ms: eth_getBlockByNumber
T+154199879ms: eth_getBlockByNumber
T+154199884ms: eth_getBlockByNumber
T+154199889ms: eth_getBlockByNumber
T+154199893ms: eth_getBlockByNumber
T+154199897ms: eth_getBlockByNumber
T+154199897ms: eth_getBlockByNumber
T+154199901ms: eth_getBlockByNumber
T+154199905ms: eth_getBlockByNumber
T+154199905ms: eth_getBlockByNumber
T+154199909ms: eth_getBlockByNumber
T+154199914ms: eth_getBlockByNumber
T+154199918ms: eth_getBlockByNumber
T+154199922ms: eth_getBlockByNumber
T+154199926ms: eth_getBlockByNumber
T+154199930ms: eth_getBlockByNumber
T+154199934ms: eth_getBlockByNumber
T+154199938ms: eth_getBlockByNumber
T+154199938ms: eth_getBlockByNumber
T+154199941ms: eth_getBlockByNumber
T+154199944ms: eth_getBlockByNumber
T+154199944ms: eth_getBlockByNumber
T+154199944ms: eth_getBlockByNumber
T+154199944ms: eth_getBlockByNumber
T+154199947ms: eth_getBlockByNumber
T+154199955ms: evm_mine
```

**Comment by seesemichaelj** [comment]
Thanks for reporting this! This error is actually related to having too many files open. Please see [this link](http://blog.izs.me/post/56827866110/wtf-is-emfile-and-why-does-it-happen-to-me) for more details on how to fix the issue.

I'm going to keep this open for us to add a modal that explains this on this error rather than giving the bug modal.
