### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by jordanpentacore** [trufflesuite/ganache#489]
PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+0ms: Starting server with configuration: {"hostname":"127.0.0.1","mnemonic":"candy maple cake sugar pudding cream honey rich smooth crumble sweet treat","network_id":5777,"port":7545,"total_accounts":10,"unlocked_accounts":[]}
T+267ms: Ganache started successfully!
T+267ms: Waiting for requests...
T+39771ms: net_version
T+39781ms: eth_accounts
T+39788ms: eth_accounts
T+44443ms: eth_accounts
T+44483ms: net_version
T+44487ms: net_version
T+44492ms: eth_sendTransaction
T+44560ms:   Transaction: 0xa3826cd7df4a1ef1abab07631584b3a09202bacc2beb1a92dbe8084c159a3bb1
T+44560ms:   Contract created: 0x8cdaf0cd259887258bc13a92c0a6da92698644c0
T+44560ms:   Gas usage: 268535
T+44560ms:   Block Number: 1
T+44564ms:   Block Time: Tue Apr 03 2018 20:20:39 GMT+0200 (CEST)
T+44568ms: eth_newBlockFilter
T+44572ms: eth_getFilterChanges
T+44577ms: eth_getTransactionReceipt
T+44583ms: eth_getCode
T+44595ms: eth_uninstallFilter
T+44599ms: eth_sendTransaction
T+44646ms:   Transaction: 0xd7bc86d31bee32fa3988f1c1eabce403a1b5d570340a3a9cdba53a472ee8c956
T+44646ms:   Gas usage: 41981
T+44646ms:   Block Number: 2
T+44646ms:   Block Time: Tue Apr 03 2018 20:20:39 GMT+0200 (CEST)
T+44649ms: eth_getTransactionReceipt
T+44659ms: eth_accounts
T+44928ms: net_version
T+44932ms: net_version
T+44935ms: eth_sendTransaction
T+45011ms:   Transaction: 0xf881a19c209277440148e520e77629d10a922be0041974f7c5480d68a2b20996
T+45011ms:   Contract created: 0x345ca3e014aaf5dca488057592ee47305d9b3e10
T+45011ms:   Gas usage: 3073842
T+45011ms:   Block Number: 3
T+45011ms:   Block Time: Tue Apr 03 2018 20:20:39 GMT+0200 (CEST)
T+45056ms: eth_newBlockFilter
T+45061ms: eth_getFilterChanges
T+45064ms: eth_getTransactionReceipt
T+45068ms: eth_getCode
T+45071ms: eth_uninstallFilter
T+45076ms: net_version
T+45076ms: net_version
T+45080ms: net_version
T+45084ms: net_version
T+45087ms: net_version
T+45090ms: net_version
T+45093ms: eth_sendTransaction
T+45096ms: eth_sendTransaction
T+45096ms: eth_sendTransaction
T+45103ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+45103ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+45103ms: 
T+45103ms: TypeError: Cannot read property 'get' of undefined
T+45103ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+45103ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+45103ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+45103ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+45103ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+45103ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+45103ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+45103ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+45103ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+45103ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #667. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
