### ISSUE TITLE
System Error when running Ganache 1.1.0 on darwin

### ISSUE THREAD

**Issue by flo-pereira** [trufflesuite/ganache#491]
PLATFORM: darwin
GANACHE VERSION: 1.1.0

EXCEPTION:
```
Error: listen EADDRNOTAVAIL 35.205.205.79:8545
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at Server.setupListenHandle [as _listen2] (net.js:1302:19)
    at listenInCluster (net.js:1367:12)
    at doListen (net.js:1493:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: Starting server with initial configuration: {"hostname":"35.205.205.79","network_id":45645,"port":8545,"total_accounts":10,"unlocked_accounts":[],"vmErrorsOnRPCResponse":true}
```

**Comment by hacktar** [comment]
Seems you put a custom IP in settings.
If you changed IP in Settings and now it doesn't start anymore, you could change it to 127.0.0.1 manually editing the Settings file in ~/Library/Application\ Support/Ganache/

**Comment by flo-pereira** [comment]
👍
