### ISSUE TITLE
System Error when running Ganache 1.0.2 on linux

### ISSUE THREAD

**Issue by yattishr** [trufflesuite/ganache#492]
PLATFORM: linux
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+2918343ms: eth_getCode
T+2918349ms: eth_uninstallFilter
T+2918354ms: eth_sendTransaction
T+2918364ms:   Transaction: 0xfa7590c098dadc2a7a34837494e86b795ce2ca46a7fb48287a0821e4a850d54c
T+2918364ms:   Gas usage: 41981
T+2918371ms:   Block Number: 62
T+2918371ms:   Block Time: Wed Apr 04 2018 16:00:19 GMT+0200 (SAST)
T+2918377ms: eth_getTransactionReceipt
T+2918415ms: eth_accounts
T+2918436ms: eth_sendTransaction
T+2918470ms:   Transaction: 0x370564f7356a79fba7f9a571af0830a31b59196f62a0b0335c3a52e8743bc2ad
T+2918470ms:   Contract created: 0x2467636bea0f3c2441227eedbffac59f11d54a80
T+2918470ms:   Gas usage: 686754
T+2918470ms:   Block Number: 63
T+2918470ms:   Block Time: Wed Apr 04 2018 16:00:19 GMT+0200 (SAST)
T+2918474ms: eth_newBlockFilter
T+2918480ms: eth_getFilterChanges
T+2918494ms: eth_getTransactionReceipt
T+2918502ms: eth_getCode
T+2918514ms: eth_uninstallFilter
T+2918518ms: eth_sendTransaction
T+2918555ms:   Transaction: 0xff6988bc126aab237920b42b693621f2059083b4d084db08e8d625fdb3340a27
T+2918555ms:   Gas usage: 26981
T+2918555ms:   Block Number: 64
T+2918555ms:   Block Time: Wed Apr 04 2018 16:00:20 GMT+0200 (SAST)
T+2918560ms: eth_getTransactionReceipt
T+2918695ms: evm_snapshot
T+2918710ms: eth_blockNumber
T+2918727ms: eth_call
T+2918750ms: eth_blockNumber
T+2918756ms: eth_sendTransaction
T+2918879ms:   Transaction: 0xfa0c58ad6d37b63a3c5571e5c9715767410e49d9eacf2110cd28befd1ff66451
T+2918879ms:   Gas usage: 110497
T+2918879ms:   Block Number: 65
T+2918879ms:   Block Time: Wed Apr 04 2018 16:00:20 GMT+0200 (SAST)
T+2918883ms: eth_getTransactionReceipt
T+2918895ms: eth_sendTransaction
T+2918915ms:   Transaction: 0x793371a879839932ac0a6d25c3088d0542054c59b0ed8846876c66a1046431e9
T+2918915ms:   Gas usage: 21651
T+2918915ms:   Block Number: 66
T+2918915ms:   Block Time: Wed Apr 04 2018 16:00:20 GMT+0200 (SAST)
T+2918919ms:   Runtime Error: revert
T+2918924ms: eth_call
T+2918946ms: eth_getLogs
T+2918959ms: eth_blockNumber
T+2918973ms: eth_sendTransaction
T+2919002ms:   Transaction: 0x6fa9e62e170b5b3b3bf07a143aff6e57b3d111e3e7e8a76bdeadf191436de3fb
T+2919002ms:   Gas usage: 21651
T+2919002ms:   Block Number: 67
T+2919008ms:   Block Time: Wed Apr 04 2018 16:00:20 GMT+0200 (SAST)
T+2919008ms:   Runtime Error: revert
T+2919014ms: eth_call
T+2919035ms: eth_getLogs
T+2919042ms: eth_blockNumber
T+2919056ms: eth_sendTransaction
T+2919103ms:   Transaction: 0x57164d67adee22cb35bc67a69c88dd357775b9e649ed59d228cb7f4fab112015
T+2919103ms:   Gas usage: 21651
T+2919103ms:   Block Number: 68
T+2919103ms:   Block Time: Wed Apr 04 2018 16:00:20 GMT+0200 (SAST)
T+2919103ms:   Runtime Error: revert
T+2919109ms: eth_call
T+2919174ms: eth_getLogs
T+2919182ms: evm_revert
T+2919235ms: evm_snapshot
T+2919244ms: eth_blockNumber
T+2919249ms: eth_call
T+2919280ms: eth_blockNumber
T+2919288ms: eth_sendTransaction
T+2919358ms:   Transaction: 0x8192a83165df0fc9f7852943c60ff151fe932b545d7f705fc6c37a321a111bf5
T+2919358ms:   Gas usage: 110433
T+2919358ms:   Block Number: 65
T+2919369ms:   Block Time: Wed Apr 04 2018 16:00:20 GMT+0200 (SAST)
T+2919373ms: eth_getTransactionReceipt
T+2919379ms: eth_call
T+2919410ms: eth_blockNumber
T+2919616ms: eth_getBalance
T+2919774ms: eth_getBalance
T+2919791ms: eth_sendTransaction
T+2919958ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+2919958ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_W
T+2919958ms: 
T+2919958ms: TypeError: Cannot read property 'get' of undefined
T+2919958ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+2919958ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+2919958ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+2919958ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+2919958ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+2919958ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+2919958ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+2919958ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+2919958ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+2919958ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #667. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
