### ISSUE TITLE
System Error when running Ganache 1.1.0 on linux

### ISSUE THREAD

**Issue by berkes** [trufflesuite/ganache#500]
I had ganache-1.1.0-beta.0-x86_64.AppImage installed. Deleted it. Reinstalled. Now it fails with this error.

I assume it has some left-over database or state somewhere. I'll try to nuke any leftover configs, files and storage and see if that solves this crash.

PLATFORM: linux
GANACHE VERSION: 1.1.0

EXCEPTION:
```
Error: listen EADDRNOTAVAIL 192.168.1.235:7545
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at Server.setupListenHandle [as _listen2] (net.js:1302:19)
    at listenInCluster (net.js:1367:12)
    at doListen (net.js:1493:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: Starting server with initial configuration: {"hostname":"192.168.1.235","network_id":5777,"port":7545,"total_accounts":15,"unlocked_accounts":[],"vmErrorsOnRPCResponse":true}
```

**Comment by berkes** [comment]
So, indeed, removing the `~/.config/Ganache` data-file did the trick.

In case anyone wants to solve this bug, here's some strace log aquired with `strace -o ganache_crash.log ganache-1.1.0-x86_64.AppImage`. HTH.
