### ISSUE TITLE
System Error when running Ganache 1.0.2 on win32

### ISSUE THREAD

**Issue by jonasvag** [trufflesuite/ganache#504]
PLATFORM: win32
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+0ms: Starting server with configuration: {"hostname":"127.0.0.1","mnemonic":"candy maple cake sugar pudding cream honey rich smooth crumble sweet treat","network_id":5777,"port":7545,"total_accounts":10,"unlocked_accounts":[]}
T+458ms: Ganache started successfully!
T+458ms: Waiting for requests...
T+2330ms: eth_getBlockByNumber
T+10344ms: eth_getBlockByNumber
T+18355ms: eth_getBlockByNumber
T+26368ms: eth_getBlockByNumber
T+34383ms: eth_getBlockByNumber
T+38615ms: net_version
T+38634ms: eth_accounts
T+38665ms: eth_call
T+38719ms: eth_call
T+38745ms: eth_accounts
T+38768ms: eth_sendTransaction
T+38853ms:   Transaction: 0x546b188cb1e2961db0499fa2899f7cc9ca8c7ff9694024f18ebc501b88813a13
T+38853ms:   Contract created: 0x8cdaf0cd259887258bc13a92c0a6da92698644c0
T+38853ms:   Gas usage: 269607
T+38853ms:   Block Number: 1
T+38857ms:   Block Time: Sat Apr 07 2018 00:49:50 GMT+0300 (FLE Daylight Time)
T+38862ms: eth_newBlockFilter
T+38873ms: eth_getFilterChanges
T+38890ms: eth_getTransactionReceipt
T+38901ms: eth_getCode
T+38916ms: eth_sendTransaction
T+38920ms: eth_uninstallFilter
T+38997ms:   Transaction: 0xd7bc86d31bee32fa3988f1c1eabce403a1b5d570340a3a9cdba53a472ee8c956
T+38997ms:   Gas usage: 41981
T+38997ms:   Block Number: 2
T+38997ms:   Block Time: Sat Apr 07 2018 00:49:50 GMT+0300 (FLE Daylight Time)
T+39105ms: eth_getTransactionReceipt
T+39118ms: eth_accounts
T+39131ms: eth_sendTransaction
T+39242ms: C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:63898
T+39242ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&
T+39242ms: 
T+39242ms: TypeError: Cannot read property 'get' of undefined
T+39242ms:     at dbGet (C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:56029:7)
T+39242ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:17614:5
T+39242ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:23091:20
T+39242ms:     at iterate (C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:23172:13)
T+39242ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:23184:29
T+39242ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:22954:16
T+39242ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:17619:7
T+39242ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:56034:9
T+39242ms:     at dispatchError (C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:36358:36)
T+39242ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:22744:14
```

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #667. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
