### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by CaliosD** [trufflesuite/ganache#505]
I ran `truffle migrate` at my project path in the terminal, then showed following error:
```
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Could not connect to your Ethereum client. Please check that your Ethereum client:
    - is running
    - is accepting RPC connections (i.e., "--rpc" option is used in geth)
    - is accessible over the network
    - is properly configured in your Truffle configuration file (truffle.js)

```
I wonder what happened and here's more detail below. Hope to help

PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+0ms: Starting server with configuration: {"hostname":"127.0.0.1","mnemonic":"candy maple cake sugar pudding cream honey rich smooth crumble sweet treat","network_id":5777,"port":7545,"total_accounts":10,"unlocked_accounts":[]}
T+210ms: Ganache started successfully!
T+210ms: Waiting for requests...
T+24585ms: net_version
T+24591ms: eth_accounts
T+24606ms: eth_call
T+24639ms: eth_call
T+24654ms: eth_accounts
T+24664ms: eth_sendTransaction
T+24704ms:   Transaction: 0xb47c765b7913245e6956f7fba9812153840f8a58f9a300366004d9484130b037
T+24704ms:   Contract created: 0x8cdaf0cd259887258bc13a92c0a6da92698644c0
T+24704ms:   Gas usage: 269607
T+24704ms:   Block Number: 1
T+24708ms:   Block Time: Sun Apr 08 2018 10:57:28 GMT+0800 (CST)
T+24711ms: eth_newBlockFilter
T+24715ms: eth_getFilterChanges
T+24721ms: eth_getTransactionReceipt
T+24727ms: eth_getCode
T+24738ms: eth_uninstallFilter
T+24740ms: eth_sendTransaction
T+24761ms:   Transaction: 0xddd0939f95dc24ef9d62771574bab137308c5741aafd3516ede9a6ab017639a5
T+24761ms:   Gas usage: 21464
T+24761ms:   Block Number: 2
T+24765ms:   Block Time: Sun Apr 08 2018 10:57:28 GMT+0800 (CST)
T+24768ms: eth_getTransactionReceipt
T+24772ms: eth_accounts
T+24789ms: eth_sendTransaction
T+24814ms:   Transaction: 0x946335e00c999c1248714a67a994784e4ecbfcaf86bd298a4b572df102600770
T+24814ms:   Contract created: 0x345ca3e014aaf5dca488057592ee47305d9b3e10
T+24814ms:   Gas usage: 382570
T+24814ms:   Block Number: 3
T+24816ms:   Block Time: Sun Apr 08 2018 10:57:28 GMT+0800 (CST)
T+24819ms: eth_newBlockFilter
T+24821ms: eth_getFilterChanges
T+24826ms: eth_getTransactionReceipt
T+24831ms: eth_getCode
T+24835ms: eth_uninstallFilter
T+24838ms: eth_sendTransaction
T+24864ms:   Transaction: 0xe32ce1ebf69f20b7f0f5fc9f4a95d377244284089437bca88a52f0582fd7e3fc
T+24864ms:   Contract created: 0xf25186b5081ff5ce73482ad761db0eb0d25abfbf
T+24864ms:   Gas usage: 700183
T+24864ms:   Block Number: 4
T+24864ms:   Block Time: Sun Apr 08 2018 10:57:28 GMT+0800 (CST)
T+24866ms: eth_newBlockFilter
T+24901ms: eth_getFilterChanges
T+24904ms: eth_getTransactionReceipt
T+24907ms: eth_getCode
T+24910ms: eth_uninstallFilter
T+24913ms: eth_sendTransaction
T+24929ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+24929ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+24929ms: 
T+24929ms: TypeError: Cannot read property 'get' of undefined
T+24929ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+24929ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+24929ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+24929ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+24929ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+24929ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+24929ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+24929ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+24929ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+24929ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #667. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
