### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by vincentleeuwen** [trufflesuite/ganache#511]
PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+293588ms:   Runtime Error: revert
T+293592ms: eth_call
T+293633ms: eth_blockNumber
T+293637ms: eth_sendTransaction
T+293664ms: eth_getBlockByNumber
T+293683ms:   Transaction: 0x24c5fffc081016613b72f0a98b8ca5386023daea71ec621b12dce853294c164d
T+293683ms:   Contract created: 0x1411cb266fced1587b0aa29e9d5a9ef3db64a9c5
T+293683ms:   Gas usage: 1445904
T+293683ms:   Block Number: 51
T+293683ms:   Block Time: Mon Apr 09 2018 17:18:49 GMT+0200 (CEST)
T+293689ms: eth_newBlockFilter
T+293694ms: eth_getFilterChanges
T+293698ms: eth_getTransactionReceipt
T+293703ms: eth_getCode
T+293709ms: eth_uninstallFilter
T+293712ms: eth_sendTransaction
T+293714ms: eth_blockNumber
T+293716ms: eth_sendTransaction
T+293735ms:   Transaction: 0x32ee4108f1321bb7abd6ebb79d35050c639c201f2d187141fbff40d1a36422b9
T+293735ms:   Gas usage: 43635
T+293735ms:   Block Number: 52
T+293735ms:   Block Time: Mon Apr 09 2018 17:18:49 GMT+0200 (CEST)
T+293739ms: eth_getTransactionReceipt
T+293748ms: eth_call
T+293783ms: eth_getBlockByNumber
T+293791ms:   Transaction: 0xc90b901dadb5254f96b3795675f8a16db33827554dd43bca388d528e6de06b6a
T+293791ms:   Contract created: 0x855d1c79ad3fb086d516554dc7187e3fdfc1c79a
T+293791ms:   Gas usage: 1445904
T+293794ms:   Block Number: 53
T+293794ms:   Block Time: Mon Apr 09 2018 17:18:49 GMT+0200 (CEST)
T+293797ms: eth_newBlockFilter
T+293807ms: eth_getFilterChanges
T+293815ms: eth_getTransactionReceipt
T+293820ms: eth_getCode
T+293826ms: eth_uninstallFilter
T+293826ms: eth_sendTransaction
T+293845ms:   Transaction: 0xbadb7e6d32a7c60cfbac82972a903dc3ae9e7205cc2e823d05eb6c13d955e044
T+293845ms:   Gas usage: 23318
T+293845ms:   Block Number: 54
T+293845ms:   Block Time: Mon Apr 09 2018 17:18:50 GMT+0200 (CEST)
T+293845ms:   Runtime Error: revert
T+293849ms: eth_call
T+293861ms: eth_blockNumber
T+293865ms: eth_sendTransaction
T+293917ms: eth_getBlockByNumber
T+293941ms:   Transaction: 0x1b853cb69007caff7a6017a4c3e8bfa329b69b26b8e5596d593659611ee0e4b3
T+293941ms:   Contract created: 0x913bbcfea2f347a24cfca441d483e7cbac8de3db
T+293941ms:   Gas usage: 1445904
T+293941ms:   Block Number: 55
T+293941ms:   Block Time: Mon Apr 09 2018 17:18:50 GMT+0200 (CEST)
T+293945ms: eth_newBlockFilter
T+293949ms: eth_getFilterChanges
T+293953ms: eth_getTransactionReceipt
T+293959ms: eth_getCode
T+293964ms: eth_uninstallFilter
T+293967ms: eth_sendTransaction
T+293970ms: eth_blockNumber
T+293973ms: eth_sendTransaction
T+293988ms:   Transaction: 0xe56baf4a244de338105947b4eb3592f3643fa613f1115c91c7060d2fc6140b1c
T+293988ms:   Gas usage: 28591
T+293988ms:   Block Number: 56
T+293988ms:   Block Time: Mon Apr 09 2018 17:18:50 GMT+0200 (CEST)
T+293992ms: eth_getTransactionReceipt
T+293997ms: eth_call
T+294034ms: eth_getBlockByNumber
T+294038ms:   Transaction: 0x57ef1ff0772a678f97162d3324876597ad33500da352be694a6963c34f4c826b
T+294038ms:   Contract created: 0x4a5cd58b24e3bf04360b06bfeaf45a39aa8035b6
T+294038ms:   Gas usage: 1445904
T+294038ms:   Block Number: 57
T+294043ms:   Block Time: Mon Apr 09 2018 17:18:50 GMT+0200 (CEST)
T+294047ms: eth_newBlockFilter
T+294081ms: eth_getFilterChanges
T+294085ms: eth_getTransactionReceipt
T+294091ms: eth_getCode
T+294094ms: eth_uninstallFilter
T+294094ms: eth_sendTransaction
T+294116ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+294116ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+294116ms: 
T+294116ms: TypeError: Cannot read property 'get' of undefined
T+294116ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+294116ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+294116ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+294116ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+294116ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+294116ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+294116ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+294116ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+294116ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+294116ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #667. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
