### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by CrazyTeaFs** [trufflesuite/ganache#515]
PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+235342ms: eth_getTransactionReceipt
T+235352ms: eth_accounts
T+235392ms: eth_sendTransaction
T+235619ms:   Transaction: 0xd421894d18d061e91769850bb03910c2a2b2a9925f832e1ac58f43c381b63022
T+235619ms:   Contract created: 0xf204a4ef082f5c04bb89f7d5e6568b796096735a
T+235619ms:   Gas usage: 99726
T+235619ms:   Block Number: 12
T+235619ms:   Block Time: Tue Apr 10 2018 14:10:27 GMT+0800 (CST)
T+235628ms: eth_newBlockFilter
T+235632ms: eth_getFilterChanges
T+235637ms: eth_getTransactionReceipt
T+235654ms: eth_getCode
T+241585ms: eth_getBlockByNumber
T+241597ms: eth_getBlockByNumber
T+241615ms: eth_getBlockByNumber
T+241619ms: eth_getBalance
T+241623ms: eth_getBalance
T+241627ms: eth_getBalance
T+241631ms: eth_getBalance
T+241634ms: eth_getBalance
T+241634ms: eth_getBalance
T+241638ms: eth_getBalance
T+241638ms: eth_getBalance
T+241642ms: eth_getBalance
T+241645ms: eth_getBalance
T+241648ms: eth_getLogs
T+241652ms: eth_getBalance
T+241655ms: eth_getBalance
T+241655ms: eth_getBalance
T+249631ms: eth_getBlockByNumber
T+257642ms: eth_getBlockByNumber
T+265659ms: eth_getBlockByNumber
T+273674ms: eth_getBlockByNumber
T+281690ms: eth_getBlockByNumber
T+289709ms: eth_getBlockByNumber
T+297722ms: eth_getBlockByNumber
T+305735ms: eth_getBlockByNumber
T+313747ms: eth_getBlockByNumber
T+321766ms: eth_getBlockByNumber
T+329780ms: eth_getBlockByNumber
T+337795ms: eth_getBlockByNumber
T+345807ms: eth_getBlockByNumber
T+353821ms: eth_getBlockByNumber
T+361834ms: eth_getBlockByNumber
T+369847ms: eth_getBlockByNumber
T+377861ms: eth_getBlockByNumber
T+385875ms: eth_getBlockByNumber
T+393887ms: eth_getBlockByNumber
T+401904ms: eth_getBlockByNumber
T+409919ms: eth_getBlockByNumber
T+417934ms: eth_getBlockByNumber
T+425948ms: eth_getBlockByNumber
T+433964ms: eth_getBlockByNumber
T+441981ms: eth_getBlockByNumber
T+449995ms: eth_getBlockByNumber
T+458010ms: eth_getBlockByNumber
T+466026ms: eth_getBlockByNumber
T+474041ms: eth_getBlockByNumber
T+482054ms: eth_getBlockByNumber
T+490067ms: eth_getBlockByNumber
T+498081ms: eth_getBlockByNumber
T+506100ms: eth_getBlockByNumber
T+514115ms: eth_getBlockByNumber
T+522131ms: eth_getBlockByNumber
T+530140ms: eth_getBlockByNumber
T+538157ms: eth_getBlockByNumber
T+546173ms: eth_getBlockByNumber
T+554186ms: eth_getBlockByNumber
T+562197ms: eth_getBlockByNumber
T+570206ms: eth_getBlockByNumber
T+578221ms: eth_getBlockByNumber
T+586238ms: eth_getBlockByNumber
T+594250ms: eth_getBlockByNumber
T+602261ms: eth_getBlockByNumber
T+605390ms: net_version
T+605398ms: eth_accounts
T+605405ms: eth_accounts
T+605434ms: eth_sendTransaction
T+605477ms:   Transaction: 0xd20014b17b26ff4d239c53d8cf4881ea6f189067004ad25a7e6c4dd378a907be
T+605481ms:   Contract created: 0xf204a4ef082f5c04bb89f7d5e6568b796096735a
T+605481ms:   Gas usage: 269607
T+605481ms:   Block Number: 13
T+605481ms:   Block Time: Tue Apr 10 2018 14:16:37 GMT+0800 (CST)
T+605484ms: eth_newBlockFilter
T+605487ms: eth_getFilterChanges
T+605493ms: eth_getTransactionReceipt
T+605499ms: eth_getCode
T+605510ms: eth_uninstallFilter
T+605513ms: eth_sendTransaction
T+605554ms:   Transaction: 0xdca60c150751afa08f8b9481aa0aae548eacc8f192f44a029f85b682feec6195
T+605554ms:   Gas usage: 41981
T+605554ms:   Block Number: 14
T+605558ms:   Block Time: Tue Apr 10 2018 14:16:37 GMT+0800 (CST)
T+605561ms: eth_getTransactionReceipt
T+605571ms: eth_accounts
T+605720ms: eth_sendTransaction
T+606020ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+606020ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+606020ms: 
T+606020ms: TypeError: Cannot read property 'get' of undefined
T+606020ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+606020ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+606020ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+606020ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+606020ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+606020ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+606020ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+606020ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+606020ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+606020ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #667. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
