### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by phillipgibb** [trufflesuite/ganache#518]
This must have happened when I ran truffle migrate, which has been working fine earlier with no updates since.

The last successful command before this was:
truffle migrate --reset --compile-all
which I did after reinstalling metamask because of a nonce issue.

PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+0ms: Starting server with configuration: {"hostname":"127.0.0.1","mnemonic":"candy maple cake sugar pudding cream honey rich smooth crumble sweet treat","network_id":5777,"port":9545,"total_accounts":10,"unlocked_accounts":[]}
T+228ms: Ganache started successfully!
T+228ms: Waiting for requests...
T+28736ms: net_version
T+28743ms: eth_accounts
T+28761ms: eth_call
T+28803ms: eth_call
T+28817ms: eth_accounts
T+28830ms: eth_sendTransaction
T+28879ms:   Transaction: 0x6687651869801aebefff8d74a68ab0c8238850b6458917102b2f48924c83f113
T+28879ms:   Contract created: 0x8cdaf0cd259887258bc13a92c0a6da92698644c0
T+28879ms:   Gas usage: 223007
T+28879ms:   Block Number: 1
T+28882ms:   Block Time: Tue Apr 10 2018 17:29:40 GMT+0200 (EET)
T+28885ms: eth_newBlockFilter
T+28927ms: eth_getFilterChanges
T+28931ms: eth_getTransactionReceipt
T+28935ms: eth_getCode
T+28938ms: eth_uninstallFilter
T+28942ms: eth_sendTransaction
T+28966ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+28966ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+28966ms: 
T+28966ms: TypeError: Cannot read property 'get' of undefined
T+28966ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+28966ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+28966ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+28966ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+28966ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+28966ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+28966ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+28966ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+28966ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+28966ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #667. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
