### ISSUE TITLE
System Error when running Ganache 1.0.2 on linux

### ISSUE THREAD

**Issue by borovik96** [trufflesuite/ganache#525]
PLATFORM: linux
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+2499565ms: eth_getBalance
T+2499640ms: eth_getBalance
T+2499713ms: eth_call
T+2499767ms: eth_getBalance
T+2499774ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+2499774ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_W
T+2499774ms: 
T+2499774ms: TypeError: Cannot read property 'get' of undefined
T+2499774ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+2499774ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+2499774ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+2499774ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+2499774ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+2499774ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+2499774ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+2499774ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+2499774ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+2499774ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #667. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
