### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by oyaoyaoyana** [trufflesuite/ganache#526]
PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+0ms: Starting server with configuration: {"hostname":"127.0.0.1","mnemonic":"candy maple cake sugar pudding cream honey rich smooth crumble sweet treat","network_id":5777,"port":7545,"total_accounts":10,"unlocked_accounts":[]}
T+686ms: Ganache started successfully!
T+686ms: Waiting for requests...
T+323662ms: net_version
T+323696ms: eth_accounts
T+323725ms: eth_accounts
T+323774ms: eth_sendTransaction
T+323975ms:   Transaction: 0x4d72dc06cf4b94ffbe360ee5826a4541e660d1e7b13e83d07ff11a6760888448
T+323975ms:   Contract created: 0x8cdaf0cd259887258bc13a92c0a6da92698644c0
T+323975ms:   Gas usage: 268471
T+323981ms:   Block Number: 1
T+323990ms:   Block Time: Fri Apr 13 2018 14:34:41 GMT+0900 (JST)
T+323995ms: eth_newBlockFilter
T+324003ms: eth_getFilterChanges
T+324120ms: eth_getTransactionReceipt
T+324130ms: eth_getCode
T+324146ms: eth_uninstallFilter
T+324152ms: eth_sendTransaction
T+324320ms:   Transaction: 0x8b72d2614becb7c5ec4ac836736c6d7d25c2d7207f9fd1957898f30b948804a1
T+324320ms:   Gas usage: 41981
T+324320ms:   Block Number: 2
T+324327ms:   Block Time: Fri Apr 13 2018 14:34:41 GMT+0900 (JST)
T+324336ms: eth_getTransactionReceipt
T+324470ms: eth_accounts
T+324497ms: eth_sendTransaction
T+324776ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+324776ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+324776ms: 
T+324776ms: TypeError: Cannot read property 'get' of undefined
T+324776ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+324776ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+324776ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+324776ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+324776ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+324776ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+324776ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+324776ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+324776ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+324776ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #667. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
