### ISSUE TITLE
System Error when running Ganache 1.1.0 on darwin

### ISSUE THREAD

**Issue by guenoledc** [trufflesuite/ganache#529]
From console (geth attach http://localhost:7545)

>var filter = web3.eth.filter('latest')
>filter.get( function(error, result) { console.log("new block", result); } )

PLATFORM: darwin
GANACHE VERSION: 1.1.0

EXCEPTION:
```
TypeError: n.getAllResults is not a function
    at o.d.getFilterLogs (/node_modules/ganache-cli/build/webpack:/ganache/node_modules/web3-provider-engine/subproviders/filters.js:201:1)
    at Timeout._onTimeout (/node_modules/ganache-cli/build/webpack:/ganache/node_modules/web3-provider-engine/subproviders/filters.js:82:1)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
```

APPLICATION LOG:
```
T+23606ms: eth_getFilterChanges
T+23609ms: FilterSubprovider - no filter with that id: 0x04
T+24106ms: eth_getFilterChanges
T+24109ms: FilterSubprovider - no filter with that id: 0x04
T+24378ms: evm_mine
T+24612ms: eth_getFilterChanges
T+24615ms: FilterSubprovider - no filter with that id: 0x04
T+25114ms: eth_getFilterChanges
T+25117ms: FilterSubprovider - no filter with that id: 0x04
T+25154ms: evm_mine
T+25396ms: evm_mine
T+25614ms: eth_getFilterChanges
T+25617ms: FilterSubprovider - no filter with that id: 0x04
T+25734ms: evm_mine
T+26116ms: eth_getFilterChanges
T+26118ms: FilterSubprovider - no filter with that id: 0x04
T+26410ms: evm_mine
T+26620ms: eth_getFilterChanges
T+26623ms: FilterSubprovider - no filter with that id: 0x04
T+27125ms: eth_getFilterChanges
T+27127ms: FilterSubprovider - no filter with that id: 0x04
T+27424ms: evm_mine
T+27628ms: eth_getFilterChanges
T+27631ms: FilterSubprovider - no filter with that id: 0x04
T+28127ms: eth_getFilterChanges
T+28129ms: FilterSubprovider - no filter with that id: 0x04
T+28210ms: eth_getBlockByNumber
T+28438ms: evm_mine
T+28627ms: eth_getFilterChanges
T+28630ms: FilterSubprovider - no filter with that id: 0x04
T+29133ms: eth_getFilterChanges
T+29136ms: FilterSubprovider - no filter with that id: 0x04
T+29455ms: evm_mine
T+29633ms: eth_getFilterChanges
T+29636ms: FilterSubprovider - no filter with that id: 0x04
T+30133ms: eth_getFilterChanges
T+30142ms: FilterSubprovider - no filter with that id: 0x04
T+30165ms: evm_mine
T+30472ms: evm_mine
T+30637ms: eth_getFilterChanges
T+30645ms: FilterSubprovider - no filter with that id: 0x04
T+30757ms: evm_mine
T+31143ms: eth_getFilterChanges
T+31150ms: FilterSubprovider - no filter with that id: 0x04
T+31493ms: evm_mine
T+31643ms: eth_getFilterChanges
T+31650ms: FilterSubprovider - no filter with that id: 0x04
T+32143ms: eth_getFilterChanges
T+32151ms: FilterSubprovider - no filter with that id: 0x04
T+32509ms: evm_mine
T+32646ms: eth_getFilterChanges
T+32671ms: FilterSubprovider - no filter with that id: 0x04
T+33144ms: eth_getFilterChanges
T+33153ms: FilterSubprovider - no filter with that id: 0x04
T+33562ms: evm_mine
T+33645ms: eth_getFilterChanges
T+33652ms: FilterSubprovider - no filter with that id: 0x04
T+34575ms: evm_mine
T+35178ms: evm_mine
T+35592ms: evm_mine
T+35769ms: evm_mine
T+36228ms: eth_getBlockByNumber
T+36610ms: evm_mine
T+37620ms: evm_mine
T+38634ms: evm_mine
T+39655ms: evm_mine
T+40192ms: evm_mine
T+40673ms: evm_mine
T+40784ms: evm_mine
T+41695ms: evm_mine
T+42711ms: evm_mine
T+43728ms: evm_mine
T+44239ms: eth_getBlockByNumber
T+44746ms: evm_mine
T+45210ms: evm_mine
T+45757ms: evm_mine
T+45799ms: evm_mine
T+46778ms: evm_mine
T+47797ms: evm_mine
T+48815ms: evm_mine
T+49831ms: evm_mine
T+50228ms: evm_mine
T+50816ms: evm_mine
T+50844ms: evm_mine
T+51866ms: evm_mine
T+52255ms: eth_getBlockByNumber
T+52883ms: evm_mine
T+53900ms: evm_mine
T+54917ms: evm_mine
T+55246ms: evm_mine
T+55843ms: evm_mine
T+55934ms: evm_mine
T+56946ms: evm_mine
T+57965ms: evm_mine
T+58982ms: evm_mine
T+59997ms: evm_mine
T+60265ms: evm_mine
T+60279ms: eth_getBlockByNumber
T+60868ms: evm_mine
T+61017ms: evm_mine
T+62032ms: evm_mine
T+63054ms: evm_mine
T+64072ms: evm_mine
T+65089ms: evm_mine
T+65280ms: evm_mine
T+65890ms: evm_mine
T+66101ms: evm_mine
T+67120ms: evm_mine
T+68133ms: evm_mine
T+68297ms: eth_getBlockByNumber
T+69151ms: evm_mine
T+70170ms: evm_mine
T+70293ms: evm_mine
T+70908ms: evm_mine
T+71186ms: evm_mine
T+72204ms: evm_mine
T+73046ms: eth_newBlockFilter
T+73218ms: evm_mine
T+74235ms: evm_mine
T+75253ms: evm_mine
T+75310ms: evm_mine
T+75925ms: evm_mine
T+76269ms: evm_mine
T+76309ms: eth_getBlockByNumber
T+77286ms: evm_mine
T+78301ms: evm_mine
T+79317ms: evm_mine
T+80329ms: evm_mine
T+80329ms: evm_mine
T+80944ms: evm_mine
T+81349ms: evm_mine
T+82365ms: evm_mine
T+83231ms: eth_getFilterLogs
T+83378ms: evm_mine
T+84341ms: eth_getBlockByNumber
T+84410ms: evm_mine
T+85351ms: evm_mine
T+85444ms: evm_mine
T+85961ms: evm_mine
T+86484ms: evm_mine
T+87693ms: evm_mine
T+88723ms: evm_mine
T+89751ms: evm_mine
T+90807ms: evm_mine
T+91011ms: evm_mine
T+91842ms: evm_mine
T+92869ms: evm_mine
T+93935ms: evm_mine
T+94989ms: evm_mine
T+96021ms: evm_mine
T+96060ms: evm_mine
T+97059ms: evm_mine
T+98097ms: evm_mine
T+99142ms: evm_mine
T+100198ms: evm_mine
T+101078ms: evm_mine
T+101226ms: evm_mine
T+102261ms: evm_mine
T+103296ms: evm_mine
T+104356ms: evm_mine
T+105411ms: evm_mine
T+106132ms: evm_mine
T+106482ms: evm_mine
T+107511ms: evm_mine
T+108560ms: evm_mine
T+109596ms: evm_mine
T+110636ms: evm_mine
T+111174ms: evm_mine
T+111664ms: evm_mine
T+112705ms: evm_mine
T+113742ms: evm_mine
T+114782ms: evm_mine
T+115815ms: evm_mine
T+116226ms: evm_mine
T+116857ms: evm_mine
```

**Comment by seesemichaelj** [comment]
Thanks for reporting this, I'm going to close this in favor of #709
