### ISSUE TITLE
System Error when running Ganache 1.0.2 on linux

### ISSUE THREAD

**Issue by jerryji** [trufflesuite/ganache#537]
PLATFORM: linux (Ubuntu 17.10.1 64-bit)
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+1090788ms:   Contract created: 0x51815cebef59b88dafd1a5f24095eee1236ffcdd
T+1090788ms:   Gas usage: 2894783
T+1090788ms:   Block Number: 82
T+1090792ms:   Block Time: Sun Apr 15 2018 20:24:30 GMT+0800 (+08)
T+1090794ms: eth_newBlockFilter
T+1090796ms: eth_getFilterChanges
T+1090799ms: eth_getTransactionReceipt
T+1090807ms: eth_getCode
T+1090812ms: eth_uninstallFilter
T+1090813ms: eth_sendTransaction
T+1090844ms:   Transaction: 0x211293e064a4ea6bc136d0ece229154f58992ca039110ee7a6bb4ce243e57071
T+1090844ms:   Contract created: 0x66078a97def9d40b2ca7abb44733dd897ec6231d
T+1090844ms:   Gas usage: 2955728
T+1090844ms:   Block Number: 83
T+1090846ms:   Block Time: Sun Apr 15 2018 20:24:30 GMT+0800 (+08)
T+1090848ms: eth_newBlockFilter
T+1090851ms: eth_getFilterChanges
T+1090855ms: eth_getTransactionReceipt
T+1090862ms: eth_getCode
T+1090869ms: eth_uninstallFilter
T+1090874ms: eth_sendTransaction
T+1090893ms:   Transaction: 0x6b4787742de39f4c1ccf4b332f157bc11d98810f7ff3efee93a963cf6fd5a717
T+1090893ms:   Gas usage: 63682
T+1090893ms:   Block Number: 84
T+1090893ms:   Block Time: Sun Apr 15 2018 20:24:30 GMT+0800 (+08)
T+1090895ms: eth_getTransactionReceipt
T+1090898ms: eth_sendTransaction
T+1090924ms:   Transaction: 0xef2c836b9bd86e0ae19d1f5901e20c5489fccc5fcac7c52ddb266f2c2cc0e183
T+1090924ms:   Gas usage: 31946
T+1090924ms:   Block Number: 85
T+1090924ms:   Block Time: Sun Apr 15 2018 20:24:30 GMT+0800 (+08)
T+1090926ms: eth_getTransactionReceipt
T+1090930ms: eth_sendTransaction
T+1090975ms:   Transaction: 0x269a0dabdcad2a67a7238cca0d5e33188b2282323e4d1c1b0f8d99b379ef940c
T+1090975ms:   Gas usage: 33501
T+1090975ms:   Block Number: 86
T+1090975ms:   Block Time: Sun Apr 15 2018 20:24:30 GMT+0800 (+08)
T+1090977ms:   Runtime Error: revert
T+1090979ms: eth_getLogs
T+1281430ms: net_version
T+1281435ms: eth_accounts
T+1281457ms: eth_accounts
T+1283790ms: eth_accounts
T+1283818ms: eth_sendTransaction
T+1283848ms:   Transaction: 0xaea2be1cad23d23851ff858d5991e7235852ddcb45e81a8efad67426ec115bb0
T+1283848ms:   Contract created: 0xde5bb8b8961faef05b2ab38a70c81bdbc91add29
T+1283848ms:   Gas usage: 268535
T+1283848ms:   Block Number: 87
T+1283850ms:   Block Time: Sun Apr 15 2018 20:27:43 GMT+0800 (+08)
T+1283853ms: eth_newBlockFilter
T+1283857ms: eth_getFilterChanges
T+1283861ms: eth_getTransactionReceipt
T+1283866ms: eth_getCode
T+1283879ms: eth_uninstallFilter
T+1283880ms: eth_sendTransaction
T+1283898ms:   Transaction: 0xcb63ea63c7865e4cf3b020d4d4e08a62853a7ffa5783989e52a6d1fbd26ee509
T+1283898ms:   Gas usage: 41981
T+1283898ms:   Block Number: 88
T+1283898ms:   Block Time: Sun Apr 15 2018 20:27:43 GMT+0800 (+08)
T+1283900ms: eth_getTransactionReceipt
T+1283908ms: eth_accounts
T+1283958ms: eth_sendTransaction
T+1284027ms:   Transaction: 0x3878ac8c277c77cfab3e240649a9ad2399056427ff37bef4b1aa17a8e633675b
T+1284027ms:   Contract created: 0x1cff61b8259f05f4bbf7aa4f769321e5fa70b22d
T+1284029ms:   Gas usage: 2894783
T+1284029ms:   Block Number: 89
T+1284029ms:   Block Time: Sun Apr 15 2018 20:27:43 GMT+0800 (+08)
T+1284031ms: eth_newBlockFilter
T+1284033ms: eth_getFilterChanges
T+1284040ms: eth_getTransactionReceipt
T+1284048ms: eth_getCode
T+1284082ms: eth_uninstallFilter
T+1284084ms: eth_sendTransaction
T+1284085ms: eth_sendTransaction
T+1284118ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+1284118ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_W
T+1284118ms: 
T+1284118ms: TypeError: Cannot read property 'get' of undefined
T+1284118ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+1284118ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+1284118ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+1284118ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+1284118ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+1284118ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+1284118ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+1284118ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+1284118ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+1284118ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #667. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
