### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by XatMassacrE** [trufflesuite/ganache#542]
PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+10584493ms: eth_call
T+10584517ms: eth_blockNumber
T+10584521ms: net_version
T+10584525ms: eth_call
T+10584546ms: net_version
T+10584550ms: eth_call
T+10584571ms: eth_blockNumber
T+10584576ms: net_version
T+10584579ms: eth_blockNumber
T+10584585ms: eth_sendTransaction
T+10584585ms: net_version
T+10584595ms: eth_sendTransaction
T+10584657ms:   Transaction: 0xd169c816156c5141798a4ee154957c54db6d06f130bbd61cd81e8450fb5069d0
T+10584657ms:   Gas usage: 105187
T+10584657ms:   Block Number: 86
T+10584657ms:   Block Time: Mon Apr 16 2018 17:14:38 GMT+0800 (CST)
T+10584660ms: eth_getTransactionReceipt
T+10584669ms: net_version
T+10584673ms: eth_call
T+10584685ms:   Transaction: 0x2a6a02be37f3dccaafba8587e3bdc7be55a1a832d01811ff3b5923ae4c776aa5
T+10584685ms:   Gas usage: 22978
T+10584685ms:   Block Number: 87
T+10584685ms:   Block Time: Mon Apr 16 2018 17:14:38 GMT+0800 (CST)
T+10584690ms:   Runtime Error: revert
T+10871080ms: net_version
T+10871094ms: eth_accounts
T+10871284ms: eth_accounts
T+10872671ms: eth_accounts
T+10873259ms: net_version
T+10873267ms: net_version
T+10873282ms: eth_sendTransaction
T+10873348ms:   Transaction: 0x363aea2cd0efff8f10380f4c6c9e5174bbf92f1d843271e917e27f0197c5e6e2
T+10873353ms:   Contract created: 0x27032850077abef46fc9c2b39b96885b40abc3ec
T+10873358ms:   Gas usage: 202027
T+10873363ms:   Block Number: 88
T+10873363ms:   Block Time: Mon Apr 16 2018 17:19:27 GMT+0800 (CST)
T+10873367ms: eth_newBlockFilter
T+10873372ms: eth_getFilterChanges
T+10873381ms: eth_getTransactionReceipt
T+10873392ms: eth_getCode
T+10873417ms: eth_uninstallFilter
T+10873421ms: eth_sendTransaction
T+10873473ms:   Transaction: 0xcc0cfe95d5a4678c2538746c66b464c50c0962dfb6b02ae85328815a76d58e17
T+10873478ms:   Gas usage: 41984
T+10873483ms:   Block Number: 89
T+10873488ms:   Block Time: Mon Apr 16 2018 17:19:27 GMT+0800 (CST)
T+10873492ms: eth_getTransactionReceipt
T+10873509ms: eth_accounts
T+10874008ms: net_version
T+10874012ms: net_version
T+10874017ms: eth_sendTransaction
T+10874076ms:   Transaction: 0x6be8cce7aab5964e1cff147fbfb28887872a49de82be31bd03bb09f103ae0e3c
T+10874076ms:   Contract created: 0xaba7902442c5739c6f0c182691d48d63d06a212e
T+10874076ms:   Gas usage: 2506050
T+10874076ms:   Block Number: 90
T+10874080ms:   Block Time: Mon Apr 16 2018 17:19:27 GMT+0800 (CST)
T+10874111ms: eth_newBlockFilter
T+10874124ms: eth_getFilterChanges
T+10874150ms: eth_getTransactionReceipt
T+10874171ms: eth_getCode
T+10875123ms: eth_uninstallFilter
T+10875127ms: eth_sendTransaction
T+10875163ms:   Transaction: 0x7a4e5a0681100c2020b7d420cbce9fe30635eae153574e24e94ce381be69baa7
T+10875163ms:   Gas usage: 26984
T+10875163ms:   Block Number: 91
T+10875168ms:   Block Time: Mon Apr 16 2018 17:19:28 GMT+0800 (CST)
T+10875174ms: eth_getTransactionReceipt
T+10877345ms: evm_snapshot
T+10877843ms: eth_sendTransaction
T+10877979ms:   Transaction: 0x5108c5d4cb244c028bfbfee642ceb6870216216766d61d05be542dd9457c4e6f
T+10877979ms:   Gas usage: 1952453
T+10877979ms:   Block Number: 92
T+10877979ms:   Block Time: Mon Apr 16 2018 17:19:31 GMT+0800 (CST)
T+10877990ms: eth_getTransactionReceipt
T+10878001ms: eth_blockNumber
T+10878015ms: eth_call
T+10878049ms: eth_blockNumber
T+10878055ms: net_version
T+10878060ms: eth_call
T+10878156ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+10878156ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+10878156ms: 
T+10878156ms: TypeError: Cannot read property 'get' of undefined
T+10878156ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+10878156ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+10878156ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+10878156ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+10878156ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+10878156ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+10878156ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+10878156ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+10878156ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+10878156ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #667. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
