### ISSUE TITLE
System Error when running Ganache 1.1.0 on win32

### ISSUE THREAD

**Issue by if1999615** [trufflesuite/ganache#552]
I believe I had two instances running. Might be helpful to add additional port numbers for multiple instances?

PLATFORM: win32
GANACHE VERSION: 1.1.0

EXCEPTION:
```
Error: listen EADDRINUSE 127.0.0.1:7545
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at Server.setupListenHandle [as _listen2] (net.js:1319:14)
    at listenInCluster (net.js:1367:12)
    at doListen (net.js:1493:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: Starting server with initial configuration: {"hostname":"127.0.0.1","port":7545,"network_id":5777,"total_accounts":10,"unlocked_accounts":[],"vmErrorsOnRPCResponse":true}
```

**Comment by seesemichaelj** [comment]
Hey @if1999615 and @zachlysobey! Unfortunately we do not support running multiple instances of Ganache simultaneously currently. They share the same `Settings` file which will mean they'll both try to run on the same port.

We're still determining whether or not we'll support multiple instances (see #684), but we're currently working the "nicer way to fail"! Thanks for the feedback
