### ISSUE TITLE
Crashes when asked to get logs for a non-existent filter id

### ISSUE THREAD

**Issue by jackkinsella** [trufflesuite/ganache#556]
I ran Ganache GUI, then with truffle I deployed some smart contracts to the same network/port combo. Then I (mistakenly) asked a Ruby program to get the filter logs for a filter id that didn't exist ('0x01').

PLATFORM: darwin
GANACHE VERSION: 1.1.0

EXCEPTION:
```javascript
TypeError: n.getAllResults is not a function
    at o.d.getFilterLogs (/node_modules/ganache-cli/build/webpack:/ganache/node_modules/web3-provider-engine/subproviders/filters.js:201:1)
    at Timeout._onTimeout (/node_modules/ganache-cli/build/webpack:/ganache/node_modules/web3-provider-engine/subproviders/filters.js:82:1)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
```

APPLICATION LOG:
```
T+0ms: eth_unsubscribe
T+1ms: Starting server with initial configuration: {"hostname":"127.0.0.1","port":7545,"network_id":2,"total_accounts":10,"unlocked_accounts":[],"vmErrorsOnRPCResponse":true}
T+112ms: Ganache started successfully!
T+112ms: Waiting for requests...
T+13803ms: eth_accounts
T+13816ms: eth_accounts
T+13845ms: eth_sendTransaction
T+13892ms:   Transaction: 0x6beec6785ce79cbbf5a13097c5e4b917bbce174b5cb2c922ee552b960db8786f
T+13892ms:   Contract created: 0xf24f407987119d9f904be9fd3803767b197df7ba
T+13892ms:   Gas usage: 310111
T+13892ms:   Block Number: 1
T+13892ms:   Block Time: Thu Apr 19 2018 11:08:48 GMT+0200 (CEST)
T+13893ms: eth_newBlockFilter
T+13895ms: eth_getFilterChanges
T+13904ms: eth_getTransactionReceipt
T+13935ms: eth_getCode
T+13946ms: eth_uninstallFilter
T+13947ms: eth_sendTransaction
T+13995ms:   Transaction: 0x541aa99aed3afb748e71c6a7b51a2ce71bc369bcd5ed98fab215144b39da65d3
T+13995ms:   Gas usage: 42006
T+13996ms:   Block Number: 2
T+13996ms:   Block Time: Thu Apr 19 2018 11:08:49 GMT+0200 (CEST)
T+13998ms: eth_getTransactionReceipt
T+14003ms: eth_accounts
T+14124ms: eth_sendTransaction
T+14164ms:   Transaction: 0x1f4bd8970c170a7d5a5c200d801e1c7fbe1835a1d08f53a56ace0715c20424a7
T+14164ms:   Contract created: 0x22268e2ce50c9b17bfe5d796c9073391bd343558
T+14164ms:   Gas usage: 1849464
T+14166ms:   Block Number: 3
T+14166ms:   Block Time: Thu Apr 19 2018 11:08:49 GMT+0200 (CEST)
T+14168ms: eth_newBlockFilter
T+14178ms: eth_getFilterChanges
T+14191ms: eth_getTransactionReceipt
T+14219ms: eth_getCode
T+14224ms: eth_uninstallFilter
T+14225ms: eth_sendTransaction
T+14269ms:   Transaction: 0xac0c1c3060cb99e1ae2add6229d3c238be22b7f628b33255830af68d51f4c80e
T+14269ms:   Contract created: 0x5bb86ad0087dc54125a54085dcf6dc7d4b0caae4
T+14269ms:   Gas usage: 1252269
T+14270ms:   Block Number: 4
T+14270ms:   Block Time: Thu Apr 19 2018 11:08:49 GMT+0200 (CEST)
T+14272ms: eth_newBlockFilter
T+14274ms: eth_getFilterChanges
T+14283ms: eth_getTransactionReceipt
T+14322ms: eth_getCode
T+14346ms: eth_uninstallFilter
T+14347ms: eth_sendTransaction
T+14388ms:   Transaction: 0xf013f9099367dfb9a1fc4743166439e94aa4cfa6c1b594c780d50921a546e13d
T+14388ms:   Gas usage: 27006
T+14389ms:   Block Number: 5
T+14389ms:   Block Time: Thu Apr 19 2018 11:08:49 GMT+0200 (CEST)
T+14391ms: eth_getTransactionReceipt
T+21108ms: eth_accounts
T+21140ms: net_version
T+21144ms: eth_getTransactionCount
T+21165ms: eth_sendRawTransaction
T+21208ms:   Transaction: 0x4494becde8cba2bb026521223eed970336e0522ce55703d8eb11303d080600c9
T+21208ms:   Gas usage: 22663
T+21209ms:   Block Number: 6
T+21209ms:   Block Time: Thu Apr 19 2018 11:08:56 GMT+0200 (CEST)
T+21210ms: eth_newFilter
T+21222ms: eth_getFilterLogs
```

**Comment by seesemichaelj** [comment]
Thanks for reporting this, I'm going to close this in favor of #709
