### ISSUE TITLE
System Error when running Ganache 1.0.2 on linux

### ISSUE THREAD

**Issue by bhanu-ratnakaram** [trufflesuite/ganache#563]
PLATFORM: linux
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+12884ms:   Gas usage: 21046
T+12884ms:   Block Number: 10
T+12888ms:   Block Time: Fri Apr 20 2018 09:46:08 GMT+0100 (BST)
T+12888ms:   Runtime Error: revert
T+12890ms: eth_call
T+12909ms: eth_blockNumber
T+12915ms: eth_sendTransaction
T+12990ms:   Transaction: 0xb704fb9529a8917d37a77b71dfe614411df4c66fc3af2aa6ac0d85a32c9a0ef2
T+12990ms:   Contract created: 0xf204a4ef082f5c04bb89f7d5e6568b796096735a
T+12990ms:   Gas usage: 2879961
T+12990ms:   Block Number: 11
T+12990ms:   Block Time: Fri Apr 20 2018 09:46:08 GMT+0100 (BST)
T+12994ms: eth_newBlockFilter
T+12998ms: eth_getFilterChanges
T+13003ms: eth_getTransactionReceipt
T+13010ms: eth_getCode
T+13016ms: eth_uninstallFilter
T+13020ms: eth_sendTransaction
T+13050ms:   Transaction: 0xd30623d0d9e75fc1305af00666077118f6c44783c87e001fe429542f16ea95d2
T+13050ms:   Gas usage: 37698
T+13050ms:   Block Number: 12
T+13053ms:   Block Time: Fri Apr 20 2018 09:46:08 GMT+0100 (BST)
T+13056ms: eth_getTransactionReceipt
T+13088ms: eth_call
T+13096ms: eth_call
T+13170ms: eth_blockNumber
T+13175ms: eth_sendTransaction
T+13211ms:   Transaction: 0x7f01a9cf5033bb4018d7240743f88cbc68bdbf2358fe96696940f1129b1168dc
T+13211ms:   Contract created: 0x82d50ad3c1091866e258fd0f1a7cc9674609d254
T+13211ms:   Gas usage: 2879961
T+13211ms:   Block Number: 13
T+13211ms:   Block Time: Fri Apr 20 2018 09:46:08 GMT+0100 (BST)
T+13217ms: eth_newBlockFilter
T+13220ms: eth_getFilterChanges
T+13225ms: eth_getTransactionReceipt
T+13232ms: eth_getCode
T+13237ms: eth_uninstallFilter
T+13239ms: eth_call
T+13260ms: eth_blockNumber
T+13266ms: eth_sendTransaction
T+13331ms:   Transaction: 0xe0834b9f7ce3c87971bd7a91e0f5e9a2777001ff5ae27515ce2d0c287c8048a2
T+13331ms:   Contract created: 0xdda6327139485221633a1fcd65f4ac932e60a2e1
T+13331ms:   Gas usage: 2879961
T+13331ms:   Block Number: 14
T+13335ms:   Block Time: Fri Apr 20 2018 09:46:08 GMT+0100 (BST)
T+13337ms: eth_newBlockFilter
T+13339ms: eth_getFilterChanges
T+13348ms: eth_getTransactionReceipt
T+13354ms: eth_getCode
T+13360ms: eth_uninstallFilter
T+13363ms: eth_call
T+13387ms: eth_blockNumber
T+13396ms: eth_sendTransaction
T+13458ms:   Transaction: 0x55323f13e728caf3fa06ea563618e4ef3e09a257f5d62b75d07d0761098b9736
T+13458ms:   Contract created: 0xeec918d74c746167564401103096d45bbd494b74
T+13458ms:   Gas usage: 2879961
T+13458ms:   Block Number: 15
T+13458ms:   Block Time: Fri Apr 20 2018 09:46:08 GMT+0100 (BST)
T+13460ms: eth_newBlockFilter
T+13465ms: eth_getFilterChanges
T+13473ms: eth_getTransactionReceipt
T+13480ms: eth_getCode
T+13486ms: eth_uninstallFilter
T+13490ms: eth_sendTransaction
T+13515ms:   Transaction: 0xb895790f90fb56a326362683fb5885f45d1d9375ddb9b6a733666e88a8633a56
T+13515ms:   Gas usage: 42441
T+13519ms:   Block Number: 16
T+13519ms:   Block Time: Fri Apr 20 2018 09:46:09 GMT+0100 (BST)
T+13523ms: eth_getTransactionReceipt
T+13526ms: eth_call
T+13537ms: eth_call
T+13553ms: eth_sendTransaction
T+13609ms:   Transaction: 0x1cb177c32595c344ed38e0bcc181a10f389ee230dd107c1c689e6f7fdd775836
T+13609ms:   Gas usage: 26523
T+13609ms:   Block Number: 17
T+13609ms:   Block Time: Fri Apr 20 2018 09:46:09 GMT+0100 (BST)
T+13614ms:   Runtime Error: revert
T+13618ms: eth_call
T+13625ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+13625ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_W
T+13625ms: 
T+13625ms: TypeError: Cannot read property 'get' of undefined
T+13625ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+13625ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+13625ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+13625ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+13625ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+13625ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+13625ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+13625ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+13625ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+13625ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by seesemichaelj** [comment]
See my comments in #667. This issue was fixed sometime in 1.1.0; please upgrade to the latest version (1.2.1 currently)
