### ISSUE TITLE
System Error when running Ganache 1.0.2 on linux

### ISSUE THREAD

**Issue by bhanu-ratnakaram** [trufflesuite/ganache#564]
PLATFORM: linux
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+285443ms:   Block Number: 120
T+285443ms:   Block Time: Fri Apr 20 2018 11:40:37 GMT+0100 (BST)
T+285447ms: eth_getTransactionReceipt
T+285561ms: evm_snapshot
T+285569ms: eth_blockNumber
T+285577ms: eth_sendTransaction
T+285719ms:   Transaction: 0x92499a5ad4dd9f4ad52e9c866c04265901ec7e97d973b8afb08664c633bbd786
T+285719ms:   Contract created: 0x90fbc44fc6f93b773d0111b830bb27cd42292c9f
T+285719ms:   Gas usage: 2879961
T+285719ms:   Block Number: 121
T+285722ms:   Block Time: Fri Apr 20 2018 11:40:37 GMT+0100 (BST)
T+285728ms: eth_newBlockFilter
T+285731ms: eth_getFilterChanges
T+285734ms: eth_getTransactionReceipt
T+285740ms: eth_getCode
T+285747ms: eth_uninstallFilter
T+285750ms: eth_call
T+285774ms: eth_blockNumber
T+285780ms: eth_sendTransaction
T+285865ms:   Transaction: 0x795b897e6e33a5d9baf2ca80407010e98063a4d2c48c774cfebf1d0e78cfff97
T+285865ms:   Contract created: 0x17647ef21c6fd7e67486c57affbb1faf9eb30ea5
T+285865ms:   Gas usage: 2879961
T+285865ms:   Block Number: 122
T+285865ms:   Block Time: Fri Apr 20 2018 11:40:37 GMT+0100 (BST)
T+285868ms: eth_newBlockFilter
T+285871ms: eth_getFilterChanges
T+285878ms: eth_getTransactionReceipt
T+285886ms: eth_getCode
T+285893ms: eth_uninstallFilter
T+285895ms: eth_call
T+285913ms: eth_call
T+285931ms: eth_call
T+285956ms: eth_call
T+285979ms: eth_call
T+286048ms: eth_call
T+286057ms: eth_call
T+286060ms: eth_blockNumber
T+286114ms: eth_sendTransaction
T+286198ms:   Transaction: 0x0d01a341709eead5740d471f79aa1b7d977706bd9eb0c7e11e8951a077ebcea9
T+286198ms:   Contract created: 0x4b31c27826c810007749860be339ecc28f56fb1b
T+286198ms:   Gas usage: 2879961
T+286198ms:   Block Number: 123
T+286200ms:   Block Time: Fri Apr 20 2018 11:40:37 GMT+0100 (BST)
T+286203ms: eth_newBlockFilter
T+286205ms: eth_getFilterChanges
T+286210ms: eth_getTransactionReceipt
T+286217ms: eth_getCode
T+286223ms: eth_uninstallFilter
T+286226ms: eth_sendTransaction
T+286294ms:   Transaction: 0xfd262b4cd8c8351f30dc97b6ce91d44ec76ba18c8ec42257a426d447ba1c13d3
T+286294ms:   Contract created: 0x5ca9f95992eb68163efdf8bf751e813f2c53c450
T+286294ms:   Gas usage: 2881945
T+286296ms:   Block Number: 124
T+286296ms:   Block Time: Fri Apr 20 2018 11:40:37 GMT+0100 (BST)
T+286299ms: eth_newBlockFilter
T+286302ms: eth_getFilterChanges
T+286308ms: eth_getTransactionReceipt
T+286315ms: eth_getCode
T+286320ms: eth_uninstallFilter
T+286327ms: eth_call
T+286343ms: eth_blockNumber
T+286348ms: eth_sendTransaction
T+286423ms:   Transaction: 0xc9571985bae82bbe32b0ef5a045cb7fee85322042a30b63ea46d5f153e934d46
T+286423ms:   Contract created: 0xcb95f554b1d4fe89d5d917c0962f81629e97a6df
T+286429ms:   Gas usage: 2879961
T+286431ms:   Block Number: 125
T+286431ms:   Block Time: Fri Apr 20 2018 11:40:38 GMT+0100 (BST)
T+286433ms: eth_newBlockFilter
T+286435ms: eth_getFilterChanges
T+286443ms: eth_getTransactionReceipt
T+286451ms: eth_getCode
T+286457ms: eth_uninstallFilter
T+286460ms: eth_call
T+286473ms: eth_sendTransaction
T+286555ms:   Transaction: 0xa99828112c5e83c7d7967fe93616f606305ec48cad7af7fe14b679d93df33401
T+286555ms:   Gas usage: 21046
T+286559ms:   Block Number: 126
T+286559ms:   Block Time: Fri Apr 20 2018 11:40:38 GMT+0100 (BST)
T+286559ms:   Runtime Error: revert
T+286562ms: eth_call
T+286570ms: eth_blockNumber
T+286576ms: eth_sendTransaction
T+286656ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+286656ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_W
T+286656ms: 
T+286656ms: TypeError: Cannot read property 'get' of undefined
T+286656ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+286656ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+286656ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+286656ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+286656ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+286656ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+286656ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+286656ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+286656ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+286656ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by seesemichaelj** [comment]
See my comments in #667. This issue was fixed sometime in 1.1.0; please upgrade to the latest version (1.2.1 currently)
