### ISSUE TITLE
System Error when running Ganache 1.1.0 on darwin

### ISSUE THREAD

**Issue by CodeOpsTechnologies** [trufflesuite/ganache#586]
PLATFORM: darwin
GANACHE VERSION: 1.1.0

EXCEPTION:
```
Blockchain process exited prematurely with code '1', due to signal 'null'.
```

APPLICATION LOG:
```
T+0ms: module.js:487
T+0ms:     throw err;
T+0ms:     ^
T+0ms: 
T+0ms: Error: Cannot find module 'ganache-cli'
T+0ms:     at Function.Module._resolveFilename (module.js:485:15)
T+0ms:     at Function.Module._load (module.js:437:25)
T+0ms:     at Module.require (module.js:513:17)
T+0ms:     at require (internal/module.js:11:18)
T+0ms:     at Object.<anonymous> (/src/chain.js:3:18)
T+0ms:     at Object.<anonymous> (/src/chain.js:162:3)
T+0ms:     at Module._compile (module.js:569:30)
T+0ms:     at Object.Module._extensions..js (module.js:580:10)
T+0ms:     at Module.load (module.js:503:32)
T+0ms:     at tryModuleLoad (module.js:466:12)
```

**Comment by CodeOpsTechnologies** [comment]
This error happened when I installed Ganache and started with npm start. MacOS platform.

**Comment by seesemichaelj** [comment]
Hi @CodeOpsTechnologies! Thanks for reporting this. I apologize it's taken so long for one of us to respond.

Have you been able to get his to work? Do you remember if you used a DMG or did `npm install`? If it's still not working, can you try updating to the latest version (https://github.com/trufflesuite/ganache/releases)?

Thanks!

**Comment by seesemichaelj** [comment]
Closing due to inactivity. Please open a new issue if you still have problems with the latest versions. Thanks!
