### ISSUE TITLE
build-mac RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by dily3825002** [trufflesuite/ganache#590]
build-mac RangeError: Maximum call stack size exceeded

RangeError: Maximum call stack size exceeded
    at computeSortedPaths (/Users/dily/egretia-tool/node_modules/_electron-builder-lib@20.6.2@electron-builder-lib/src/util/packageDependencies.ts:57:1)
    at computeSortedPaths (/Users/dily/egretia-tool/node_modules/_electron-builder-lib@20.6.2@electron-builder-lib/src/util/packageDependencies.ts:66:7)
    at computeSortedPaths (/Users/dily/egretia-tool/node_modules/_electron-builder-lib@20.6.2@electron-builder-lib/src/util/packageDependencies.ts:66:7)
    at computeSortedPaths (/Users/dily/egretia-tool/node_modules/_electron-builder-lib@20.6.2@electron-builder-lib/src/util/packageDependencies.ts:66:7)
    at computeSortedPaths (/Users/dily/egretia-tool/node_modules/_electron-builder-lib@20.6.2@electron-builder-lib/src/util/packageDependencies.ts:66:7)
    at computeSortedPaths (/Users/dily/egretia-tool/node_modules/_electron-builder-lib@20.6.2@electron-builder-lib/src/util/packageDependencies.ts:66:7)
    at computeSortedPaths (/Users/dily/egretia-tool/node_modules/_electron-builder-lib@20.6.2@electron-builder-lib/src/util/packageDependencies.ts:66:7)
    at computeSortedPaths (/Users/dily/egretia-tool/node_modules/_electron-builder-lib@20.6.2@electron-builder-lib/src/util/packageDependencies.ts:66:7)
    at computeSortedPaths (/Users/dily/egretia-tool/node_modules/_electron-builder-lib@20.6.2@electron-builder-lib/src/util/packageDependencies.ts:66:7)
    at computeSortedPaths (/Users/dily/egretia-tool/node_modules/_electron-builder-lib@20.6.2@electron-builder-lib/src/util/packageDependencies.ts:66:7)
    at computeSortedPaths (/Users/dily/egretia-tool/node_modules/_electron-builder-lib@20.6.2@electron-builder-lib/src/util/packageDependencies.ts:66:7)
    at computeSortedPaths (/Users/dily/egretia-tool/node_modules/_electron-builder-lib@20.6.2@electron-builder-lib/src/util/packageDependencies.ts:66:7)
    at computeSortedPaths (/Users/dily/egretia-tool/node_modules/_electron-builder-lib@20.6.2@electron-builder-lib/src/util/packageDependencies.ts:66:7)
    at computeSortedPaths (/Users/dily/egretia-tool/node_modules/_electron-builder-lib@20.6.2@electron-builder-lib/src/util/packageDependencies.ts:66:7)
    at computeSortedPaths (/Users/dily/egretia-tool/node_modules/_electron-builder-lib@20.6.2@electron-builder-lib/src/util/packageDependencies.ts:66:7)
    at computeSortedPaths (/Users/dily/egretia-tool/node_modules/_electron-builder-lib@20.6.2@electron-builder-lib/src/util/packageDependencies.ts:66:7)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (/Users/dily/egretia-tool/node_modules/_bluebird@3.5.1@bluebird/js/release/debuggability.js:400:19)
    at Promise._then (/Users/dily/egretia-tool/node_modules/_bluebird@3.5.1@bluebird/js/release/promise.js:232:17)
    at Promise.then (/Users/dily/egretia-tool/node_modules/_bluebird@3.5.1@bluebird/js/release/promise.js:125:17)
    at Object.args [as handler] (/Users/dily/egretia-tool/node_modules/_electron-builder@20.6.2@electron-builder/src/cli/cli.ts:48:50)
    at Object.runCommand (/Users/dily/egretia-tool/node_modules/_yargs@11.0.0@yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/Users/dily/egretia-tool/node_modules/_yargs@11.0.0@yargs/yargs.js:1014:30)
    at Object.get [as argv] (/Users/dily/egretia-tool/node_modules/_yargs@11.0.0@yargs/yargs.js:957:21)
    at Object.<anonymous> (/Users/dily/egretia-tool/node_modules/_electron-builder@20.6.2@electron-builder/out/cli/cli.js:148:373)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! egretia@1.1.0 make: `electron-builder build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the egretia@1.1.0 make script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dily/.npm/_logs/2018-05-04T10_09_14_859Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! egretia@1.1.0 build-mac: `npm run make`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the egretia@1.1.0 build-mac script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dily/.npm/_logs/2018-05-04T10_09_14_891Z-debug.log

**Comment by seesemichaelj** [comment]
Thanks for reporting this! We can't reproduce this issue. Please open a new issue if you're still having issues with the latest versions. Thanks!
