### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by CaliforniaSoil** [trufflesuite/ganache#591]
PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+19049018ms: eth_getFilterChanges
T+19049520ms: eth_getFilterChanges
T+19050021ms: eth_getFilterChanges
T+19052842ms: eth_getFilterChanges
T+19052842ms: eth_getFilterChanges
T+19052842ms: eth_getFilterChanges
T+19052842ms: eth_getFilterChanges
T+19053211ms: eth_getFilterChanges
T+19053713ms: eth_getFilterChanges
T+19054214ms: eth_getFilterChanges
T+19054716ms: eth_getFilterChanges
T+19055216ms: eth_getFilterChanges
T+19055716ms: eth_getFilterChanges
T+19056216ms: eth_getFilterChanges
T+19056718ms: eth_getFilterChanges
T+19057223ms: eth_getFilterChanges
T+19057725ms: eth_getFilterChanges
T+19058226ms: eth_getFilterChanges
T+19058732ms: eth_getFilterChanges
T+19059232ms: eth_getFilterChanges
T+19059732ms: eth_getFilterChanges
T+19060233ms: eth_getFilterChanges
T+19060733ms: eth_getFilterChanges
T+19061233ms: eth_getFilterChanges
T+19061734ms: eth_getFilterChanges
T+19062235ms: eth_getFilterChanges
T+19062735ms: eth_getFilterChanges
T+19063237ms: eth_getFilterChanges
T+19063743ms: eth_getFilterChanges
T+19064247ms: eth_getFilterChanges
T+19064752ms: eth_getFilterChanges
T+19065251ms: eth_getFilterChanges
T+19065754ms: eth_getFilterChanges
T+19066256ms: eth_getFilterChanges
T+19066758ms: eth_getFilterChanges
T+19067257ms: eth_getFilterChanges
T+19067763ms: eth_getFilterChanges
T+19068265ms: eth_getFilterChanges
T+19068765ms: eth_getFilterChanges
T+19069265ms: eth_getFilterChanges
T+19069770ms: eth_getFilterChanges
T+19070272ms: eth_getFilterChanges
T+19070776ms: eth_getFilterChanges
T+19071280ms: eth_getFilterChanges
T+19071784ms: eth_getFilterChanges
T+19072284ms: eth_getFilterChanges
T+19072785ms: eth_getFilterChanges
T+19073285ms: eth_getFilterChanges
T+19073791ms: eth_getFilterChanges
T+19074295ms: eth_getFilterChanges
T+19074799ms: eth_getFilterChanges
T+19075299ms: eth_getFilterChanges
T+19075798ms: eth_getFilterChanges
T+19076300ms: eth_getFilterChanges
T+19076800ms: eth_getFilterChanges
T+19077104ms: eth_accounts
T+19077113ms: eth_accounts
T+19077120ms: eth_sendTransaction
T+19077184ms:   Transaction: 0xac0d46e6c8b46e7ae1ae2b229ae95f8798534392eac5410b6217e1762c4ee5a0
T+19077184ms:   Contract created: 0xfb88de099e13c3ed21f80a7a1e49f8caecf10df6
T+19077184ms:   Gas usage: 269607
T+19077184ms:   Block Number: 12
T+19077184ms:   Block Time: Fri May 04 2018 20:34:20 GMT-0700 (PDT)
T+19077187ms: eth_newBlockFilter
T+19077191ms: eth_getFilterChanges
T+19077200ms: eth_getTransactionReceipt
T+19077208ms: eth_getCode
T+19077214ms: eth_uninstallFilter
T+19077217ms: eth_sendTransaction
T+19077246ms:   Transaction: 0x1135ea1dd6947f262d65dde8712d17b4b0ec0a36cc917772ce8acd7fe01ca8e2
T+19077246ms:   Gas usage: 41981
T+19077246ms:   Block Number: 13
T+19077249ms:   Block Time: Fri May 04 2018 20:34:20 GMT-0700 (PDT)
T+19077252ms: eth_getTransactionReceipt
T+19077255ms: eth_accounts
T+19077260ms: eth_sendTransaction
T+19077301ms: eth_getFilterChanges
T+19077345ms:   Transaction: 0x63d6c36504220a1b889df82f6b9401852e3a06bec929842824aa8e0baffeda05
T+19077345ms:   Contract created: 0xf204a4ef082f5c04bb89f7d5e6568b796096735a
T+19077345ms:   Gas usage: 464936
T+19077345ms:   Block Number: 14
T+19077347ms:   Block Time: Fri May 04 2018 20:34:20 GMT-0700 (PDT)
T+19077351ms: eth_newBlockFilter
T+19077354ms: eth_getFilterChanges
T+19077358ms: eth_getTransactionReceipt
T+19077361ms: eth_getCode
T+19077363ms: eth_uninstallFilter
T+19077366ms: eth_sendTransaction
T+19077373ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+19077373ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+19077373ms: 
T+19077373ms: TypeError: Cannot read property 'get' of undefined
T+19077373ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+19077373ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+19077373ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+19077373ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+19077373ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+19077373ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+19077373ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+19077373ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+19077373ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+19077373ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #667. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
