### ISSUE TITLE
System Error when running Ganache 1.0.2 on linux

### ISSUE THREAD

**Issue by tcmartin** [trufflesuite/ganache#602]
PLATFORM: linux
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+16877815ms:   Transaction: 0x22b2fd2ef8392d6033744d739b9f6e6d8a7363a259ce1a0d46e6fd49d8390625
T+16877815ms:   Gas usage: 52602
T+16877815ms:   Block Number: 269
T+16877815ms:   Block Time: Mon May 07 2018 20:55:09 GMT-0500 (CDT)
T+16877818ms: eth_getTransactionReceipt
T+16877821ms: eth_call
T+16877829ms: eth_call
T+16877841ms: eth_sendTransaction
T+16877863ms:   Transaction: 0x16b9bda279d188112eecca94ae481a5cbb4dfbfee578997db8fb731840451943
T+16877863ms:   Gas usage: 22602
T+16877863ms:   Block Number: 270
T+16877863ms:   Block Time: Mon May 07 2018 20:55:09 GMT-0500 (CDT)
T+16877863ms: eth_getTransactionReceipt
T+16877866ms: eth_call
T+16877874ms: eth_call
T+16877886ms: eth_blockNumber
T+16877888ms: eth_sendTransaction
T+16877923ms:   Transaction: 0xafd6f4c12e4efb3369f5920c15481097ba3ef50987e89fa7631329f78fa75818
T+16877923ms:   Contract created: 0x6102a67ca8bb97e0f5fa9991eb13f952e8cf9e4b
T+16877923ms:   Gas usage: 1450169
T+16877923ms:   Block Number: 271
T+16877923ms:   Block Time: Mon May 07 2018 20:55:10 GMT-0500 (CDT)
T+16877925ms: eth_newBlockFilter
T+16877928ms: eth_getFilterChanges
T+16877934ms: eth_getTransactionReceipt
T+16877941ms: eth_getCode
T+16877945ms: eth_uninstallFilter
T+16877945ms: eth_call
T+16877955ms: eth_sendTransaction
T+16877972ms:   Transaction: 0xedfc190cfe1461202fa46404ec3cc4a5e848638e4c6e78fab83d89957db5c59e
T+16877972ms:   Gas usage: 52602
T+16877972ms:   Block Number: 272
T+16877972ms:   Block Time: Mon May 07 2018 20:55:10 GMT-0500 (CDT)
T+16877974ms: eth_getTransactionReceipt
T+16877979ms: eth_sendTransaction
T+16878002ms:   Transaction: 0xda058bb9b6c70e8384de0643bfeca0d194bba5ccaa850f1c68459f87c8f9b4e8
T+16878002ms:   Gas usage: 37602
T+16878002ms:   Block Number: 273
T+16878002ms:   Block Time: Mon May 07 2018 20:55:10 GMT-0500 (CDT)
T+16878003ms: eth_getTransactionReceipt
T+16878007ms: eth_getLogs
T+16878010ms: eth_blockNumber
T+16878013ms: eth_sendTransaction
T+16878039ms:   Transaction: 0x876f23ac98cf396f295af897ef641ec9d4bedd42591b177c3d27328f45547159
T+16878039ms:   Contract created: 0x3e40b53406eb383e9e0f5e91044a1fec1be6735c
T+16878039ms:   Gas usage: 1450169
T+16878039ms:   Block Number: 274
T+16878039ms:   Block Time: Mon May 07 2018 20:55:10 GMT-0500 (CDT)
T+16878041ms: eth_newBlockFilter
T+16878043ms: eth_getFilterChanges
T+16878049ms: eth_getTransactionReceipt
T+16878056ms: eth_getCode
T+16878060ms: eth_uninstallFilter
T+16878061ms: eth_call
T+16878070ms: eth_sendTransaction
T+16878088ms:   Transaction: 0xd77e11790b4237e4b932dc1e68300eb2ce709fb3cb34032312614b10b27a3a89
T+16878088ms:   Gas usage: 23306
T+16878088ms:   Block Number: 275
T+16878088ms:   Block Time: Mon May 07 2018 20:55:10 GMT-0500 (CDT)
T+16878090ms: eth_getTransactionReceipt
T+16878095ms: eth_getLogs
T+16878100ms: eth_blockNumber
T+16878103ms: eth_sendTransaction
T+16878129ms:   Transaction: 0xf1e1fc39af33be9b2805858d5447b8fc997118a35712034a74f444b088b3540a
T+16878129ms:   Contract created: 0x6e4d800d3ce2a259a31653a9d89d36ecd274e3a4
T+16878129ms:   Gas usage: 1450169
T+16878129ms:   Block Number: 276
T+16878129ms:   Block Time: Mon May 07 2018 20:55:10 GMT-0500 (CDT)
T+16878131ms: eth_newBlockFilter
T+16878135ms: eth_getFilterChanges
T+16878159ms: eth_getTransactionReceipt
T+16878162ms: eth_getCode
T+16878165ms: eth_uninstallFilter
T+16878165ms: eth_call
T+16878174ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+16878174ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_W
T+16878174ms: 
T+16878174ms: TypeError: Cannot read property 'get' of undefined
T+16878174ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+16878174ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+16878174ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+16878174ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+16878174ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+16878174ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+16878174ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+16878174ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+16878174ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+16878174ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #667. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
