### ISSUE TITLE
System Error when running Ganache 1.1.0 on win32

### ISSUE THREAD

**Issue by mato777** [trufflesuite/ganache#603]
PLATFORM: win32
GANACHE VERSION: 1.1.0

EXCEPTION:
```
Error: listen EADDRNOTAVAIL 54.68.229.213:4444
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at Server.setupListenHandle [as _listen2] (net.js:1302:19)
    at listenInCluster (net.js:1367:12)
    at doListen (net.js:1493:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: Starting server with initial configuration: {"blocktime":"10","hostname":"54.68.229.213","network_id":11,"port":4444,"total_accounts":10,"unlocked_accounts":[],"vmErrorsOnRPCResponse":true}
T+10423ms: evm_mine
T+20490ms: evm_mine
T+30545ms: evm_mine
T+40592ms: evm_mine
T+50648ms: evm_mine
T+60702ms: evm_mine
T+70759ms: evm_mine
T+80803ms: evm_mine
T+90848ms: evm_mine
T+100896ms: evm_mine
T+110943ms: evm_mine
T+120991ms: evm_mine
T+131051ms: evm_mine
T+141099ms: evm_mine
```

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #666. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
