### ISSUE TITLE
Ganache crashes when host name is other than local host 

### ISSUE THREAD

**Issue by rafalf** [trufflesuite/ganache#604]
Windows 10, Windows 2012 Server 
Ganache - v1.1.0 

**Steps to reproduce:**
1. Install ganache 
2. Enter a valid ip address ( 34.213.xx.xx in my case )
3. Save and restart 

**Result:**
It crashes 
```
Error: listen EADDRNOTAVAIL 34.xxx.xx.xx:7545
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at Server.setupListenHandle [as _listen2] (net.js:1302:19)
    at listenInCluster (net.js:1367:12)
    at doListen (net.js:1493:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by rafalf** [comment]
not a bug
