### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by CaliforniaSoil** [trufflesuite/ganache#625]
The error occurred while I was running my test suite for exceptions. I was testing whether the app would allow a buyer to purchase an article with insufficient funds in their account. After running the test suite 7 times, ganache crashed.

PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+10574077ms:   Gas usage: 269607
T+10574077ms:   Block Number: 87
T+10574077ms:   Block Time: Tue May 15 2018 00:41:51 GMT-0700 (PDT)
T+10574079ms: eth_newBlockFilter
T+10574082ms: eth_getFilterChanges
T+10574090ms: eth_getTransactionReceipt
T+10574095ms: eth_getCode
T+10574100ms: eth_uninstallFilter
T+10574103ms: eth_sendTransaction
T+10574117ms:   Transaction: 0x7972d21fa1935063e3767c6022cb1344edf2d3a25e0482c8c8d98b95fc9a2874
T+10574117ms:   Gas usage: 41981
T+10574117ms:   Block Number: 88
T+10574117ms:   Block Time: Tue May 15 2018 00:41:51 GMT-0700 (PDT)
T+10574119ms: eth_getTransactionReceipt
T+10574125ms: eth_accounts
T+10574131ms: eth_sendTransaction
T+10574149ms:   Transaction: 0x243a30394c5f089a04f9f61542a714087047dc26fe4096572213e879bd3f6280
T+10574149ms:   Contract created: 0x9efec315e368e8812025b85b399a69513cd0e716
T+10574149ms:   Gas usage: 686754
T+10574149ms:   Block Number: 89
T+10574149ms:   Block Time: Tue May 15 2018 00:41:51 GMT-0700 (PDT)
T+10574152ms: eth_newBlockFilter
T+10574154ms: eth_getFilterChanges
T+10574163ms: eth_getTransactionReceipt
T+10574169ms: eth_getCode
T+10574174ms: eth_uninstallFilter
T+10574176ms: eth_sendTransaction
T+10574192ms:   Transaction: 0x6c527cdabf9d512a1ebfa0ff1d7310c620e7b4ad5a2f3daae2ecbcc4f34dc90c
T+10574192ms:   Gas usage: 26981
T+10574192ms:   Block Number: 90
T+10574192ms:   Block Time: Tue May 15 2018 00:41:51 GMT-0700 (PDT)
T+10574195ms: eth_getTransactionReceipt
T+10574207ms: evm_snapshot
T+10574213ms: eth_blockNumber
T+10574217ms: eth_call
T+10574235ms: eth_blockNumber
T+10574240ms: eth_sendTransaction
T+10574273ms:   Transaction: 0x8d5db8524734c5817af1c87eb2e39488855730ae84f93b4013956815c04169c2
T+10574273ms:   Gas usage: 110433
T+10574273ms:   Block Number: 91
T+10574273ms:   Block Time: Tue May 15 2018 00:41:51 GMT-0700 (PDT)
T+10574276ms: eth_getTransactionReceipt
T+10574282ms: eth_sendTransaction
T+10574299ms:   Transaction: 0x8aff487436aae6aa9766b30994afad0cb3a2babcd368d4ad2f11c64fa7d00537
T+10574299ms:   Gas usage: 22201
T+10574299ms:   Block Number: 92
T+10574299ms:   Block Time: Tue May 15 2018 00:41:51 GMT-0700 (PDT)
T+10574299ms:   Runtime Error: revert
T+10574302ms: eth_call
T+10574323ms: eth_blockNumber
T+10574327ms: eth_sendTransaction
T+10574343ms:   Transaction: 0x3d566e0eba73c38ad114e680f9ede3722e47cbe1d7fc21f63d71c42330254645
T+10574343ms:   Gas usage: 22429
T+10574343ms:   Block Number: 93
T+10574343ms:   Block Time: Tue May 15 2018 00:41:51 GMT-0700 (PDT)
T+10574343ms:   Runtime Error: revert
T+10574346ms: eth_call
T+10574372ms: eth_blockNumber
T+10574378ms: eth_sendTransaction
T+10574406ms:   Transaction: 0x16d31696f8708c69ea680930e3d7d5335e3252e12114fa91d322a9a6e4cf09e7
T+10574406ms:   Gas usage: 54548
T+10574406ms:   Block Number: 94
T+10574406ms:   Block Time: Tue May 15 2018 00:41:51 GMT-0700 (PDT)
T+10574409ms: eth_getTransactionReceipt
T+10574415ms: eth_sendTransaction
T+10574447ms:   Transaction: 0x4efe7085d20f36d1a8ee489ee80d24683486ff454474e9deeec9114cf43d1f71
T+10574447ms:   Gas usage: 21922
T+10574447ms:   Block Number: 95
T+10574447ms:   Block Time: Tue May 15 2018 00:41:51 GMT-0700 (PDT)
T+10574447ms:   Runtime Error: revert
T+10574450ms: eth_call
T+10574474ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+10574474ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+10574474ms: 
T+10574474ms: TypeError: Cannot read property 'get' of undefined
T+10574474ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+10574474ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+10574474ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+10574474ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+10574474ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+10574474ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+10574474ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+10574474ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+10574474ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+10574474ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #667. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
