### ISSUE TITLE
System Error when running Ganache 1.1.0 on linux

### ISSUE THREAD

**Issue by pkulxl** [trufflesuite/ganache#637]
PLATFORM: linux
GANACHE VERSION: 1.1.0

EXCEPTION:
```
TypeError: Cannot set property 'logger' of undefined
    at /src/chain.js:55:20
    at stopServer (/src/chain.js:39:5)
    at startServer (/src/chain.js:44:3)
    at process.<anonymous> (/src/chain.js:134:7)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at process.S.process.emit (/node_modules/ganache-cli/build/webpack:/ganache/node_modules/source-map-support/source-map-support.js:122:1)
    at emit (internal/child_process.js:768:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: Starting server with initial configuration: {}
```

**Comment by seesemichaelj** [comment]
I believe this issue was in the `develop` branch before the `1.2.0` release, and it was fixed in the `1.2.0` release.

Thanks for reporting however!
