### ISSUE TITLE
System Error when running Ganache 1.1.0 on win64

### ISSUE THREAD

**Issue by DuclosNgassa** [trufflesuite/ganache#638]
Error: listen EACCES 127.0.0.1:7545
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at Server.setupListenHandle [as _listen2] (net.js:1302:19)
    at listenInCluster (net.js:1367:12)
    at doListen (net.js:1493:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by seesemichaelj** [comment]
Hey @DuclosNgassa, thanks for reporting this! Looks like this is a duplicate of #627.

I'm going to close this issue in favor for that one. Thanks again!
