### ISSUE TITLE
System Error when running Ganache 1.0.2 on linux

### ISSUE THREAD

**Issue by ferittuncer** [trufflesuite/ganache#643]
PLATFORM: linux
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+22439ms: eth_getFilterChanges
T+22450ms: eth_getTransactionReceipt
T+22459ms: eth_getCode
T+22464ms: eth_uninstallFilter
T+22468ms: net_version
T+22470ms: eth_sendTransaction
T+22521ms:   Transaction: 0xc1952629f2c0c084f86bfced9418780dd1edd2cdc51e2166c5a9502cf0e62500
T+22521ms:   Contract created: 0xbd2c938b9f6bfc1a66368d08cb44dc3eb2ae27be
T+22521ms:   Gas usage: 1569047
T+22521ms:   Block Number: 50
T+22526ms:   Block Time: Fri May 18 2018 19:29:39 GMT+0300 (+03)
T+22530ms: eth_newBlockFilter
T+22533ms: eth_getFilterChanges
T+22537ms: eth_getTransactionReceipt
T+22544ms: eth_getCode
T+22548ms: eth_uninstallFilter
T+22551ms: net_version
T+22554ms: eth_sendTransaction
T+22595ms:   Transaction: 0xbe93ac57f1ef504f60d6315f1f6eee43c94ae2ebb48ac0a6281e829625e50f8a
T+22595ms:   Gas usage: 87483
T+22598ms:   Block Number: 51
T+22598ms:   Block Time: Fri May 18 2018 19:29:39 GMT+0300 (+03)
T+22602ms: eth_getTransactionReceipt
T+22606ms: net_version
T+22609ms: eth_sendTransaction
T+22683ms:   Transaction: 0x36b21f0e6707490941ae6d307385af753f926743d246fa76d5d5863e869a84c1
T+22683ms:   Gas usage: 167538
T+22683ms:   Block Number: 52
T+22686ms:   Block Time: Fri May 18 2018 19:29:39 GMT+0300 (+03)
T+22689ms: eth_getTransactionReceipt
T+22694ms: net_version
T+22714ms: eth_sendTransaction
T+22759ms:   Transaction: 0x2fde62cdcc1ca94e1370c439053d5e75eb0c425b3fda220636671919720141b3
T+22759ms:   Gas usage: 23453
T+22759ms:   Block Number: 53
T+22759ms:   Block Time: Fri May 18 2018 19:29:39 GMT+0300 (+03)
T+22765ms:   Runtime Error: revert
T+22769ms: eth_blockNumber
T+22773ms: net_version
T+22776ms: eth_sendTransaction
T+22798ms:   Transaction: 0xeead63423bb8876c79e6301d2aaf9b55c38060ab61078ebf4315bd8979c94476
T+22798ms:   Contract created: 0xcfde289f03197e8c2f8fb0c7dfd98f41ce283925
T+22798ms:   Gas usage: 822073
T+22798ms:   Block Number: 54
T+22802ms:   Block Time: Fri May 18 2018 19:29:39 GMT+0300 (+03)
T+22804ms: eth_newBlockFilter
T+22807ms: eth_getFilterChanges
T+22810ms: eth_getTransactionReceipt
T+22813ms: eth_getCode
T+22815ms: eth_uninstallFilter
T+22817ms: net_version
T+22821ms: eth_sendTransaction
T+22861ms:   Transaction: 0xe58cddfcac774e5e04e2016648461b31bccf55d64a8c3b442e41fb626402a7e9
T+22861ms:   Contract created: 0x8acee021a27779d8e98b9650722676b850b25e11
T+22861ms:   Gas usage: 1569111
T+22861ms:   Block Number: 55
T+22865ms:   Block Time: Fri May 18 2018 19:29:39 GMT+0300 (+03)
T+22868ms: eth_newBlockFilter
T+22871ms: eth_getFilterChanges
T+22874ms: eth_getTransactionReceipt
T+22884ms: eth_getCode
T+22892ms: eth_uninstallFilter
T+22896ms: net_version
T+22901ms: eth_sendTransaction
T+22939ms:   Transaction: 0x7294762a8a61e40b25ab6e78aabcade34625e3dc9d8292e5d66968e9e3260042
T+22939ms:   Gas usage: 87483
T+22939ms:   Block Number: 56
T+22939ms:   Block Time: Fri May 18 2018 19:29:40 GMT+0300 (+03)
T+22943ms: eth_getTransactionReceipt
T+22950ms: net_version
T+22954ms: eth_sendTransaction
T+23031ms:   Transaction: 0xfa8e8c22b0c379355d2f1a539a4790e119021476c290f91889752ae16bb7a175
T+23031ms:   Gas usage: 167538
T+23034ms:   Block Number: 57
T+23034ms:   Block Time: Fri May 18 2018 19:29:40 GMT+0300 (+03)
T+23036ms: eth_getTransactionReceipt
T+23155ms: eth_getBalance
T+23168ms: net_version
T+23173ms: eth_sendTransaction
T+23276ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+23276ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_W
T+23276ms: 
T+23276ms: TypeError: Cannot read property 'get' of undefined
T+23276ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+23276ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+23276ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+23276ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+23276ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+23276ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+23276ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+23276ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+23276ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+23276ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #667. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
