### ISSUE TITLE
System Error when running Ganache 1.0.2 on win32

### ISSUE THREAD

**Issue by JoelAH** [trufflesuite/ganache#648]
PLATFORM: win32
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+0ms: Starting server with configuration: {"hostname":"127.0.0.1","mnemonic":"candy maple cake sugar pudding cream honey rich smooth crumble sweet treat","network_id":5777,"port":7545,"total_accounts":10,"unlocked_accounts":[]}
T+407ms: Ganache started successfully!
T+407ms: Waiting for requests...
T+12003ms: net_version
T+12016ms: eth_accounts
T+12031ms: eth_accounts
T+12052ms: eth_sendTransaction
T+12236ms:   Transaction: 0xfcdac01d670ac01d3c138fac07e169fa4cad5be769b9e801730864c6bf00207f
T+12236ms:   Contract created: 0x8cdaf0cd259887258bc13a92c0a6da92698644c0
T+12236ms:   Gas usage: 269543
T+12236ms:   Block Number: 1
T+12243ms:   Block Time: Sun May 20 2018 15:31:45 GMT-0500 (SA Pacific Standard Time)
T+12247ms: eth_newBlockFilter
T+12252ms: eth_getFilterChanges
T+12260ms: eth_getTransactionReceipt
T+12279ms: eth_getCode
T+12298ms: eth_uninstallFilter
T+12305ms: eth_sendTransaction
T+12401ms:   Transaction: 0xd7bc86d31bee32fa3988f1c1eabce403a1b5d570340a3a9cdba53a472ee8c956
T+12401ms:   Gas usage: 41981
T+12408ms:   Block Number: 2
T+12415ms:   Block Time: Sun May 20 2018 15:31:45 GMT-0500 (SA Pacific Standard Time)
T+12504ms: eth_getTransactionReceipt
T+12515ms: eth_accounts
T+12521ms: eth_sendTransaction
T+12635ms:   Transaction: 0x923994770be3954d12f3c9a32320d5253cdd8823ee2bc0db259bb71bfb848620
T+12635ms:   Contract created: 0x345ca3e014aaf5dca488057592ee47305d9b3e10
T+12642ms:   Gas usage: 1051185
T+12642ms:   Block Number: 3
T+12642ms:   Block Time: Sun May 20 2018 15:31:45 GMT-0500 (SA Pacific Standard Time)
T+12647ms: eth_newBlockFilter
T+12665ms: eth_getFilterChanges
T+12675ms: eth_getTransactionReceipt
T+12688ms: eth_getCode
T+12703ms: eth_uninstallFilter
T+12711ms: eth_sendTransaction
T+12735ms:   Transaction: 0x917e9ac5c27d7abb7a1bdbc007c3061eadd4e7e2eb3189a5f4cda680eef386b9
T+12735ms:   Gas usage: 26981
T+12735ms:   Block Number: 4
T+12742ms:   Block Time: Sun May 20 2018 15:31:45 GMT-0500 (SA Pacific Standard Time)
T+12753ms: eth_getTransactionReceipt
T+41231ms: net_version
T+41247ms: eth_accounts
T+41279ms: eth_accounts
T+41302ms: eth_accounts
T+41326ms: eth_sendTransaction
T+41403ms:   Transaction: 0x928b39ef00d25e11149c54fbdd024e4c9849a68d497bc5d23a107140680313cd
T+41403ms:   Contract created: 0xf25186b5081ff5ce73482ad761db0eb0d25abfbf
T+41403ms:   Gas usage: 269543
T+41403ms:   Block Number: 5
T+41411ms:   Block Time: Sun May 20 2018 15:32:14 GMT-0500 (SA Pacific Standard Time)
T+41418ms: eth_newBlockFilter
T+41424ms: eth_getFilterChanges
T+41432ms: eth_getTransactionReceipt
T+41436ms: eth_getCode
T+41491ms: eth_uninstallFilter
T+41495ms: eth_sendTransaction
T+41558ms: C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:63898
T+41558ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&
T+41558ms: 
T+41558ms: TypeError: Cannot read property 'get' of undefined
T+41558ms:     at dbGet (C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:56029:7)
T+41558ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:17614:5
T+41558ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:23091:20
T+41558ms:     at iterate (C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:23172:13)
T+41558ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:23184:29
T+41558ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:22954:16
T+41558ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:17619:7
T+41558ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:56034:9
T+41558ms:     at dispatchError (C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:36358:36)
T+41558ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:22744:14
```

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #667. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
