### ISSUE TITLE
System Error when running Ganache 1.0.2 on win32

### ISSUE THREAD

**Issue by garrison1234** [trufflesuite/ganache#658]
Ganache crashes constantly for no apparent reason. This seems to happen only when not doing automining.

PLATFORM: win32
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+546199ms: eth_getFilterChanges
T+546199ms: eth_getFilterChanges
T+546199ms: eth_getFilterChanges
T+546278ms: eth_getFilterChanges
T+546351ms: eth_getFilterChanges
T+546351ms: eth_getFilterChanges
T+546351ms: eth_getFilterChanges
T+546670ms: eth_getFilterChanges
T+546670ms: eth_getFilterChanges
T+546670ms: eth_getFilterChanges
T+546670ms: eth_getFilterChanges
T+546670ms: eth_getFilterChanges
T+546695ms: eth_getFilterChanges
T+546695ms: eth_getFilterChanges
T+546695ms: eth_getFilterChanges
T+546695ms: eth_getFilterChanges
T+546695ms: eth_getFilterChanges
T+546781ms: eth_getFilterChanges
T+546866ms: eth_getFilterChanges
T+546866ms: eth_getFilterChanges
T+546866ms: eth_getFilterChanges
T+547170ms: eth_getFilterChanges
T+547170ms: eth_getFilterChanges
T+547170ms: eth_getFilterChanges
T+547170ms: eth_getFilterChanges
T+547170ms: eth_getFilterChanges
T+547210ms: eth_getFilterChanges
T+547210ms: eth_getFilterChanges
T+547210ms: eth_getFilterChanges
T+547210ms: eth_getFilterChanges
T+547210ms: eth_getFilterChanges
T+547245ms: eth_sendTransaction
T+547276ms: eth_getTransactionReceipt
T+547287ms: eth_getFilterChanges
T+547370ms: eth_getFilterChanges
T+547370ms: eth_getFilterChanges
T+547370ms: eth_getFilterChanges
T+547718ms: eth_getFilterChanges
T+547756ms: eth_getFilterChanges
T+547765ms: eth_getFilterChanges
T+547765ms: eth_getFilterChanges
T+547785ms: eth_getFilterChanges
T+547817ms: eth_getFilterChanges
T+547817ms: eth_getFilterChanges
T+547835ms: eth_getFilterChanges
T+547835ms: eth_getFilterChanges
T+547835ms: eth_getFilterChanges
T+547860ms: eth_getFilterChanges
T+547893ms: eth_getFilterChanges
T+547893ms: eth_getFilterChanges
T+547893ms: eth_getFilterChanges
T+547903ms:   Transaction: 0xd4351b8a95d5874e7b25163c298c663fb767597e92040ae05bfeecfb394ee54c
T+547903ms:   Gas usage: 38984
T+547903ms:   Block Number: 109
T+547914ms:   Block Time: Thu May 24 2018 19:29:21 GMT-0700 (Pacific Daylight Time)
T+548182ms: eth_getFilterChanges
T+548182ms: eth_getFilterChanges
T+548182ms: eth_getFilterChanges
T+548182ms: eth_getFilterChanges
T+548182ms: eth_getFilterChanges
T+548235ms: eth_getFilterChanges
T+548235ms: eth_getFilterChanges
T+548235ms: eth_getFilterChanges
T+548235ms: eth_getFilterChanges
T+548235ms: eth_getFilterChanges
T+548285ms: eth_getTransactionReceipt
T+548553ms: eth_getFilterChanges
T+548570ms: eth_getFilterChanges
T+548570ms: eth_getFilterChanges
T+548570ms: eth_getFilterChanges
T+548789ms: eth_getFilterChanges
T+548789ms: eth_getFilterChanges
T+548789ms: eth_getFilterChanges
T+548789ms: eth_getFilterChanges
T+548789ms: eth_getFilterChanges
T+548799ms: eth_coinbase
T+548842ms: eth_call
T+548869ms: eth_call
T+548881ms: eth_getFilterChanges
T+548926ms: eth_getBalance
T+548934ms: eth_getFilterChanges
T+548934ms: eth_getFilterChanges
T+548934ms: eth_getFilterChanges
T+548934ms: eth_getFilterChanges
T+548934ms: eth_getFilterChanges
T+548954ms: eth_getFilterChanges
T+548954ms: eth_getFilterChanges
T+548954ms: eth_getFilterChanges
T+549295ms: eth_getFilterChanges
T+549295ms: eth_getFilterChanges
T+549295ms: eth_getFilterChanges
T+549295ms: eth_getFilterChanges
T+549295ms: eth_getFilterChanges
T+549330ms: C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:63898
T+549330ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&
T+549330ms: 
T+549330ms: TypeError: Cannot read property 'get' of undefined
T+549330ms:     at dbGet (C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:56029:7)
T+549330ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:17614:5
T+549330ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:23091:20
T+549330ms:     at iterate (C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:23172:13)
T+549330ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:23184:29
T+549330ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:22954:16
T+549330ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:17619:7
T+549330ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:56034:9
T+549330ms:     at dispatchError (C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:36358:36)
T+549330ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:22744:14
```

**Comment by seesemichaelj** [comment]
Hey @garrison1234, thanks for reporting this! A lot of users have been reporting a similar issue, and I'd like to ask if you were doing anything in particular when this happened? Were you doing anything with `truffle` or ...? The more details, the better! Thanks again!

**Comment by garrison1234** [comment]
Hi thanksfor the quick reply. I was sending transactions and watching
events directly on the front end. I think it happens when one transaction
quickly after another one.

**Comment by seesemichaelj** [comment]
Alright thanks; I'll take that into consideration when debugging. It'd be great if there was an open source contract or something to know what you're running, but I can try to replicate the results myself.

**Comment by garrison1234** [comment]
This is the contract. I think the error happens mostly when calling
revealWinner().

**Comment by seesemichaelj** [comment]
Were you intending to upload something?

**Comment by garrison1234** [comment]
I had replied by email and attached it. Here's the contract, it won't let me attach it:

pragma solidity ^0.4.19;

contract Hashminer {
  // custom types
  struct Player {
  uint nonce;
  address wallet;
  }

  // state variables
  address owner;
  bool gameLocked;
  uint maxNumberOfPlayers = 4; // must be 2^N
  mapping (uint => Player) public players;
  uint[65] takenNonces; // array size must be at least maxNumberOfPlayers+1
  uint playerCounter;
  uint gameCost = 50 finney;
  uint blockNumber;
  bytes32 blockHash;
  uint winningNonce;
  address winner;
  uint prize = 50 finney;
  uint callerIncentive = 2 finney;
  address caller;

  // events
  event LogGameLock(
    bool _gameLocked
  );
  event LogGameOptionsSet(
    uint _maxNumberOfPlayers,
    uint _gameCost,
    uint _prize,
    uint _callerIncentive
  );
  event LogHouseWithdraw(
    address _wallet,
    uint _withdrawAmount
  );
  event LogPlayerAdded(
    uint _playerCounter,
    uint _nonce,
    address _wallet
  );
  event LogPlayersReady(
    uint _blockNumber
  );
  event LogGameFinished(
    uint _blockNumber,
    bytes32 _blockHash,
    uint _winningNonce,
    address _winner,
    address _caller,
    bool _gameLocked
  );

  // constructor
  function Hashminer() public {
    owner = msg.sender;
  }

  // deactivate the contract
  function kill() public {
    // only allow the contract owner
    require(msg.sender == owner);

    // check that game is locked and not active. This ensures deactivation is only possible when game is inactive
    require(gameLocked && (playerCounter == 0));

    selfdestruct(owner);
  }

  // lock or unlock game after current game ends for game option changes and front-end updates
  function lockGame() public {
    // only allow the contract owner
    require(msg.sender == owner);

    // lock/unlock game
    gameLocked = !gameLocked;
    LogGameLock(gameLocked);
  }

  // change game settings
  function setGameOptions(uint _maxNumberOfPlayers, uint _gameCost,
    uint _prize, uint _callerIncentive) public {
    // only allow the contract owner to make changes
    require(msg.sender == owner);

    // check that game is locked and not active. This ensures game rules are not changed during game
    require(gameLocked && (playerCounter == 0));

    // change game settings
    maxNumberOfPlayers = _maxNumberOfPlayers;
    gameCost = _gameCost;
    prize = _prize;
    callerIncentive = _callerIncentive;
    LogGameOptionsSet(maxNumberOfPlayers, gameCost, prize, callerIncentive);
  }

  // transfer funds from house to given an address
  function houseWithdraw(uint _withdrawAmount, address _wallet) public {
    // only allow the contract owner to withdraw
    require(msg.sender == owner);

    // check that game is locked and not active. This ensures there will be enough funds to pay the current game winner
    require(gameLocked && (playerCounter == 0));

    // transfer to  address _wallet
    _wallet.transfer(_withdrawAmount);
    LogHouseWithdraw(_wallet, _withdrawAmount);
  }

  // add player to the game
  function playGame(uint _nonce) payable public {
    // check that value transferred matches the cost to play
    require(msg.value == gameCost);

    // check that game is unlocked or already active
    require((!gameLocked) || (playerCounter > 0));

    // check that the nonce is within the accepted range of values
    require((0 <= _nonce) && (_nonce < maxNumberOfPlayers));

    // check that the nonce has not been taken. This also checks that the game is not full.
    for (uint i = 0; i < playerCounter; i++) {
      if (_nonce == takenNonces[i]) {revert();}
    }

    // add nonce to list of already chosen ones.
    takenNonces[playerCounter] = _nonce;

    // save player struct with nonce and address in players[]
    players[_nonce] = Player(_nonce, msg.sender);

    LogPlayerAdded(playerCounter, _nonce, msg.sender);

    // add new player
    playerCounter++;

    // save number of the block that will determine the winner if game is full
    if (playerCounter == maxNumberOfPlayers) {
      blockNumber = block.number + 3;
      LogPlayersReady(blockNumber);
    }
  }

  // reveal game winner, transfer the prize and the reward to the caller
  function revealWinner() public {
    // check that game is full
    require(playerCounter == maxNumberOfPlayers);

    // check that the block that determines the winner has been mined
    require(block.number > blockNumber);

    // obtain hash of the block that determined the winner
    blockHash = block.blockhash(blockNumber);

    // obtain winning nonce. The desired blockHash ending for a given nonce is varied each game
    winningNonce = (uint(keccak256(blockNumber, blockHash)) & (maxNumberOfPlayers - 1));

    // transfer prize to winning player
    winner = players[winningNonce].wallet;
    winner.transfer(prize);

    // reset playerCounter
    playerCounter = 0;

    // store the caller address and transfer their reward
    caller = msg.sender;
    caller.transfer(callerIncentive);
    LogGameFinished(blockNumber, blockHash, winningNonce, winner, caller, gameLocked);
  }

  // get game information
  function getGameInfo() public view returns (
    address _owner,
    bool _gameLocked,
    uint _maxNumberOfPlayers,
    uint _playerCounter,
    uint _gameCost,
    uint _blockNumber,
    bytes32 _blockHash,
    uint _winningNonce,
    address _winner,
    uint _prize,
    uint _callerIncentive,
    address _caller
    ) {
    return(
      owner,
      gameLocked,
      maxNumberOfPlayers,
      playerCounter,
      gameCost,
      blockNumber,
      blockHash,
      winningNonce,
      winner,
      prize,
      callerIncentive,
      caller);
  }

  // get current players information
  function getPlayersInfo() public view returns (address[], uint[]) {
    // prepare output arrays
    address[] memory playerAddresses = new address[](playerCounter);
    uint[] memory playerNonces = new uint[](playerCounter);

    // iterate over all taken nonces
    for(uint i = 0; i < playerCounter;  i++) {
      // save player addresses and nonces
      playerAddresses[i] = players[takenNonces[i]].wallet;
      playerNonces[i] = players[takenNonces[i]].nonce;
    }

    return (playerAddresses, playerNonces);
  }

}

**Comment by seesemichaelj** [comment]
great thanks!
