### ISSUE TITLE
System Error when running Ganache 1.1.0 on darwin

### ISSUE THREAD

**Issue by ohhhhhhhhhh** [trufflesuite/ganache#659]
PLATFORM: darwin
GANACHE VERSION: 1.1.0

EXCEPTION:
```
Error: listen EADDRNOTAVAIL 127.98.89.89:7888
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at Server.setupListenHandle [as _listen2] (net.js:1302:19)
    at listenInCluster (net.js:1367:12)
    at doListen (net.js:1493:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: eth_unsubscribe
T+1ms: Starting server with initial configuration: {"hostname":"127.98.89.89","port":7888,"network_id":5777,"total_accounts":10,"unlocked_accounts":[],"vmErrorsOnRPCResponse":true}
```

**Comment by seesemichaelj** [comment]
Thanks for the issue report; greatly appreciated! Lots of similar issues; we're currently looking into it.

**Comment by seesemichaelj** [comment]
I'm going to go ahead and close this in favor of tracking the issue via #666. Feel free to make a comment on this issue or that one; I will see it either way. Thanks!
