### ISSUE TITLE
System Error when running Ganache 1.1.0 on darwin

### ISSUE THREAD

**Issue by newpouy** [trufflesuite/ganache#677]
PLATFORM: darwin
GANACHE VERSION: 1.1.0

EXCEPTION:
```
Error: listen EADDRNOTAVAIL 60.205.93.215:31313
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at Server.setupListenHandle [as _listen2] (net.js:1302:19)
    at listenInCluster (net.js:1367:12)
    at doListen (net.js:1493:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: Starting server with initial configuration: {"hostname":"60.205.93.215","port":31313,"network_id":1,"total_accounts":1,"unlocked_accounts":[],"vmErrorsOnRPCResponse":true}
```

I just wanted to know what happen if i put the mainnet ip address in the ganache setting. But the result is like above. I cannot even open Ganache... 

please let me know how to change the initial configuration of Ganache

**Comment by newpouy** [comment]
I found this(https://github.com/trufflesuite/ganache/issues/488) there is a solution.
Duplicate of 488#
