### ISSUE TITLE
System Error when running Ganache 1.1.0 on win32

### ISSUE THREAD

**Issue by bdumont78** [trufflesuite/ganache#689]
PLATFORM: win32
GANACHE VERSION: 1.1.0

EXCEPTION:
```
Error: listen EADDRNOTAVAIL 10.104.46.100:7545
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at Server.setupListenHandle [as _listen2] (net.js:1302:19)
    at listenInCluster (net.js:1367:12)
    at doListen (net.js:1493:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: Starting server with initial configuration: {"hostname":"10.104.46.100","port":7545,"network_id":5777,"total_accounts":10,"unlocked_accounts":[],"vmErrorsOnRPCResponse":true,"gasLimit":2000000000000000,"gasPrice":1}
```

**Comment by seesemichaelj** [comment]
Hey thanks for reporting this! We're already tracking this issue in #666. There are instructions in #666 on how to change your settings back to normal
