### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by NatalieChin80** [trufflesuite/ganache#695]
I was running the code: https://github.com/STKtoken/STK-smart-contracts on branch `develop` on the `StkChannelClosing.js`. Ganache crashes on the last one - but not consistently (only sometimes).  

```
    it('Should be able to have token remain in the channel after settling',async()=>
    {
        const token = await STKToken .deployed();
        const channel = await STKChannel.deployed();
        await token.approve(channel.address,100);
        const allowance = await token.allowance(accounts[0],channel.address);
        await token.transfer(channel.address, 100);
        const balance = await token.balanceOf(channel.address);
        
        const nonce = 5;
        const amount = 5;
        const cryptoParams = closingHelper.getClosingParameters(nonce,amount,STKChannel.address,signersPk);
        const cost = await  channel.close.estimateGas(nonce,amount,cryptoParams.v,cryptoParams.r,cryptoParams.s, {from:stackAddress});
        await channel.close(nonce,amount,cryptoParams.v,cryptoParams.r,cryptoParams.s, {from:stackAddress});
        const data  = await channel.channelData_.call();
        
        const blocksToWait = data[indexes.TIMEOUT];
        const returnToken = false;
        console.log('waiting for '+ blocksToWait.valueOf() + ' blocks');
        
        for(i = 0;i<blocksToWait;i++)
        {
            var transaction = {from:web3.eth.accounts[0],to:web3.eth.accounts[1],gasPrice:1000000000,value:100};
            web3.eth.sendTransaction(transaction);
        }
        
        const depositedTokens = await token.balanceOf(channel.address);
        const oldUserBalance = await token.balanceOf(userAddress);
        const oldStackBalance = await token.balanceOf(stackAddress);
        const oldChannelBalance = await token.balanceOf(channel.address);
        const amountToBeTransferred = data[indexes.AMOUNT_OWED];
        await channel.settle(returnToken);
        const newUserBalance = await token.balanceOf(userAddress);
        const newStackBalance = await token.balanceOf(stackAddress);
        const newChannelBalance = await token.balanceOf(channel.address);
        
        assert.equal(parseInt(newStackBalance.valueOf()),parseInt(oldStackBalance.valueOf()) + parseInt(amountToBeTransferred.valueOf()), 'The stack account value should be credited');
        
        assert.equal(parseInt(newChannelBalance.valueOf()),parseInt(oldChannelBalance.valueOf()) - parseInt(amountToBeTransferred.valueOf()), 'Unspent token should remain in the channel account');
        
        assert.equal(parseInt(newUserBalance.valueOf()),parseInt(oldUserBalance.valueOf()), 'The User address account value should remain the same');
    })
```

PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+108426ms: net_version
T+108432ms: eth_accounts
T+108452ms: eth_accounts
T+108490ms: eth_accounts
T+108509ms: eth_sendTransaction
T+108537ms:   Transaction: 0x9bb4774727eb0e8a4c2d563d1cf74a4aa6adee61200c1f9ddab321548c15b737
T+108537ms:   Contract created: 0x4e5abdbbc5570491dc23da911d737d8fa22e0ed9
T+108537ms:   Gas usage: 277462
T+108537ms:   Block Number: 42
T+108537ms:   Block Time: Mon Jun 04 2018 10:45:51 GMT-0400 (EDT)
T+108540ms: eth_newBlockFilter
T+108544ms: eth_getFilterChanges
T+108553ms: eth_getTransactionReceipt
T+108559ms: eth_getCode
T+108569ms: eth_uninstallFilter
T+108572ms: eth_sendTransaction
T+108600ms:   Transaction: 0x8d5949fc3f59c08b26f6239b884f24533b5edf9026d979f4e6fe6a36c775b027
T+108600ms:   Gas usage: 42008
T+108600ms:   Block Number: 43
T+108600ms:   Block Time: Mon Jun 04 2018 10:45:51 GMT-0400 (EDT)
T+108602ms: eth_getTransactionReceipt
T+108612ms: eth_accounts
T+108738ms: eth_sendTransaction
T+108762ms:   Transaction: 0x81979b3aa987bc739cb304a8352bd462080551ba7e1b43c124410358323d9a24
T+108762ms:   Contract created: 0x396b2d2711051d88fa6d6ac4e6621761a2338c08
T+108762ms:   Gas usage: 74748
T+108762ms:   Block Number: 44
T+108762ms:   Block Time: Mon Jun 04 2018 10:45:51 GMT-0400 (EDT)
T+108764ms: eth_newBlockFilter
T+108767ms: eth_getFilterChanges
T+108775ms: eth_getTransactionReceipt
T+108780ms: eth_getCode
T+108785ms: eth_uninstallFilter
T+108787ms: eth_sendTransaction
T+108808ms:   Transaction: 0x58d4671247e002267d4aea5842ab8936c13af8a74db779c9238ead3aa1583926
T+108808ms:   Contract created: 0x297a29c8f39cd7f09e9908b2ee30dea78876084d
T+108808ms:   Gas usage: 1223473
T+108808ms:   Block Number: 45
T+108808ms:   Block Time: Mon Jun 04 2018 10:45:51 GMT-0400 (EDT)
T+108812ms: eth_newBlockFilter
T+108814ms: eth_getFilterChanges
T+108822ms: eth_getTransactionReceipt
T+108827ms: eth_getCode
T+108835ms: eth_uninstallFilter
T+108838ms: eth_sendTransaction
T+108882ms:   Transaction: 0xcc2541d886649a50160367a8d4bd1825840c947d507e87c0c8d3d265aeb9456c
T+108882ms:   Contract created: 0xd28919bf9c8418dcd84657538bd144d30f6751a3
T+108882ms:   Gas usage: 1066512
T+108882ms:   Block Number: 46
T+108882ms:   Block Time: Mon Jun 04 2018 10:45:51 GMT-0400 (EDT)
T+108885ms: eth_newBlockFilter
T+108887ms: eth_getFilterChanges
T+108894ms: eth_getTransactionReceipt
T+108899ms: eth_getCode
T+109004ms: eth_accounts
T+109098ms: eth_accounts
T+109111ms: eth_uninstallFilter
T+109114ms: eth_sendTransaction
T+109180ms:   Transaction: 0x10343cdcc2b509e1ac9f0fc30fddfd733578c74128c16f4e482cfe1e14460412
T+109180ms:   Contract created: 0x5522ac494a6f3e54f643a1dffba2da9714d7f421
T+109180ms:   Gas usage: 788531
T+109180ms:   Block Number: 47
T+109180ms:   Block Time: Mon Jun 04 2018 10:45:52 GMT-0400 (EDT)
T+109183ms: eth_newBlockFilter
T+109186ms: eth_getFilterChanges
T+109194ms: eth_getTransactionReceipt
T+109200ms: eth_getCode
T+109216ms: eth_uninstallFilter
T+109220ms: eth_sendTransaction
T+109248ms:   Transaction: 0x68e1ef73546dddd04ec701e98b7f5ab5a2d5c438e7a5c7a0b5bd889c4002db35
T+109248ms:   Gas usage: 27008
T+109248ms:   Block Number: 48
T+109248ms:   Block Time: Mon Jun 04 2018 10:45:52 GMT-0400 (EDT)
T+109251ms: eth_getTransactionReceipt
T+109361ms: evm_snapshot
T+109386ms: eth_blockNumber
T+109399ms: eth_sendTransaction
T+109450ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+109450ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+109450ms: 
T+109450ms: TypeError: Cannot read property 'get' of undefined
T+109450ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+109450ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+109450ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+109450ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+109450ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+109450ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+109450ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+109450ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+109450ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+109450ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by seesemichaelj** [comment]
Thanks so much for the details! This will help us figure out the root cause of the problem.

We're tracking this issue in #667
