### ISSUE TITLE
TypeError: n.getAllResults is not a function

### ISSUE THREAD

**Issue by vshall20** [trufflesuite/ganache#709]
PLATFORM: darwin
GANACHE VERSION: 1.1.0

EXCEPTION:
```
TypeError: n.getAllResults is not a function
    at o.d.getFilterLogs (/node_modules/ganache-cli/build/webpack:/ganache/node_modules/web3-provider-engine/subproviders/filters.js:201:1)
    at Timeout._onTimeout (/node_modules/ganache-cli/build/webpack:/ganache/node_modules/web3-provider-engine/subproviders/filters.js:82:1)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
```

APPLICATION LOG:
```
T+0ms: Starting server with initial configuration: {"hostname":"127.0.0.1","port":7545,"network_id":5777,"total_accounts":10,"unlocked_accounts":[],"vmErrorsOnRPCResponse":true}
T+225ms: Ganache started successfully!
T+225ms: Waiting for requests...
T+489ms: eth_getFilterChanges
T+493ms: FilterSubprovider - no filter with that id: 0x04
T+990ms: eth_getFilterChanges
T+993ms: FilterSubprovider - no filter with that id: 0x04
T+1493ms: eth_getFilterChanges
T+1495ms: FilterSubprovider - no filter with that id: 0x04
T+1999ms: eth_getFilterChanges
T+2002ms: FilterSubprovider - no filter with that id: 0x04
T+2503ms: eth_getFilterChanges
T+2506ms: FilterSubprovider - no filter with that id: 0x04
T+2980ms: eth_getBlockByNumber
T+3007ms: eth_getFilterChanges
T+3010ms: FilterSubprovider - no filter with that id: 0x04
T+3507ms: eth_getFilterChanges
T+3510ms: FilterSubprovider - no filter with that id: 0x04
T+4009ms: eth_getFilterChanges
T+4012ms: FilterSubprovider - no filter with that id: 0x04
T+4513ms: eth_getFilterChanges
T+4516ms: FilterSubprovider - no filter with that id: 0x04
T+5016ms: eth_getFilterChanges
T+5018ms: FilterSubprovider - no filter with that id: 0x04
T+5522ms: eth_getFilterChanges
T+5525ms: FilterSubprovider - no filter with that id: 0x04
T+6024ms: eth_getFilterChanges
T+6027ms: FilterSubprovider - no filter with that id: 0x04
T+6526ms: eth_getFilterChanges
T+6528ms: FilterSubprovider - no filter with that id: 0x04
T+7027ms: eth_getFilterChanges
T+7029ms: FilterSubprovider - no filter with that id: 0x04
T+7531ms: eth_getFilterChanges
T+7533ms: FilterSubprovider - no filter with that id: 0x04
T+8033ms: eth_getFilterChanges
T+8036ms: FilterSubprovider - no filter with that id: 0x04
T+10992ms: eth_getBlockByNumber
T+14184ms: net_version
T+14191ms: eth_accounts
T+14199ms: eth_accounts
T+14303ms: eth_sendTransaction
T+14365ms:   Transaction: 0xfb1bc75b22b6415ecf88c1f7f390052d2d029da33c058f38fb91bc471f6bdeb7
T+14365ms:   Contract created: 0x64cbb064400b0fbe97443e7f816d2dccf118e526
T+14365ms:   Gas usage: 277462
T+14365ms:   Block Number: 1
T+14367ms:   Block Time: Thu Jun 07 2018 21:40:36 GMT+0530 (IST)
T+14370ms: eth_newBlockFilter
T+14371ms: eth_getFilterChanges
T+14386ms: eth_getTransactionReceipt
T+14416ms: eth_getCode
T+14427ms: eth_uninstallFilter
T+14429ms: eth_sendTransaction
T+14487ms:   Transaction: 0xeab59db2257fcee6fd17f62762530fa9177c11522f448e74a37cf55a2e96a381
T+14487ms:   Gas usage: 42008
T+14487ms:   Block Number: 2
T+14488ms:   Block Time: Thu Jun 07 2018 21:40:36 GMT+0530 (IST)
T+14490ms: eth_getTransactionReceipt
T+14492ms: eth_accounts
T+14634ms: eth_sendTransaction
T+14862ms:   Transaction: 0x40a1e1ae5848a11c4a7f6e07842e1fc593008b12c36fd70557e6f3ba3c08da8e
T+14862ms:   Contract created: 0x43a0c3f8667e182ec02affae988ba60c0c1ff37c
T+14862ms:   Gas usage: 4482617
T+14862ms:   Block Number: 3
T+14863ms:   Block Time: Thu Jun 07 2018 21:40:37 GMT+0530 (IST)
T+14866ms: eth_newBlockFilter
T+14871ms: eth_getFilterChanges
T+14903ms: eth_getTransactionReceipt
T+14912ms: eth_getCode
T+15028ms: eth_uninstallFilter
T+15030ms: eth_sendTransaction
T+15085ms:   Transaction: 0x9049ee7db813cb15f75987ad47ca35d130c12a4ec29bcadb255031de7967f2e9
T+15085ms:   Gas usage: 27008
T+15085ms:   Block Number: 4
T+15085ms:   Block Time: Thu Jun 07 2018 21:40:37 GMT+0530 (IST)
T+15087ms: eth_getTransactionReceipt
T+19006ms: eth_getBlockByNumber
T+27021ms: eth_getBlockByNumber
T+30486ms: eth_call
T+30488ms: eth_newBlockFilter
T+30524ms: eth_getFilterLogs
T+30525ms: eth_getFilterChanges
T+31030ms: eth_getFilterChanges
T+31533ms: eth_getFilterChanges
T+32037ms: eth_getFilterChanges
T+32540ms: eth_getFilterChanges
T+33043ms: eth_getFilterChanges
T+33549ms: eth_getFilterChanges
T+34052ms: eth_getFilterChanges
T+34555ms: eth_getFilterChanges
T+35034ms: eth_getBlockByNumber
T+35057ms: eth_getFilterChanges
T+35562ms: eth_getFilterChanges
T+36065ms: eth_getFilterChanges
T+36568ms: eth_getFilterChanges
T+37074ms: eth_getFilterChanges
T+37577ms: eth_getFilterChanges
T+38080ms: eth_getFilterChanges
T+38644ms: eth_getFilterChanges
T+39081ms: eth_getFilterChanges
```

**Comment by seesemichaelj** [comment]
Thanks for reporting this! Looks like multiple users are encountering this issue. We'll see if we can take a look into it

**Comment by seesemichaelj** [comment]
For future reference:
@nandubatchu asked `Does all types of filters work with Ganache?`

**Comment by benjamincburns** [comment]
This looks like a bug in web3-provider-engine. `n` at that point is not what we expect it to be (my guess: `null` or `undefined`)

**Comment by seesemichaelj** [comment]
It looks like this bug is still present in `v1.2.1`. We're going to track this issue in #879. I'm going to close this in favor of that issue.
