### ISSUE TITLE
System Error when running Ganache 1.1.0 on darwin

### ISSUE THREAD

**Issue by vshall20** [trufflesuite/ganache#735]
PLATFORM: darwin
GANACHE VERSION: 1.1.0

EXCEPTION:
```
TypeError: n.getAllResults is not a function
    at o.d.getFilterLogs (/node_modules/ganache-cli/build/webpack:/ganache/node_modules/web3-provider-engine/subproviders/filters.js:201:1)
    at Timeout._onTimeout (/node_modules/ganache-cli/build/webpack:/ganache/node_modules/web3-provider-engine/subproviders/filters.js:82:1)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
```

APPLICATION LOG:
```
T+76086ms: eth_getFilterChanges
T+76086ms: eth_getFilterChanges
T+76093ms: eth_getFilterChanges
T+76093ms: eth_getFilterChanges
T+76591ms: eth_getFilterChanges
T+76591ms: eth_getFilterChanges
T+76591ms: eth_getFilterChanges
T+76596ms: eth_getFilterChanges
T+76596ms: eth_getFilterChanges
T+77095ms: eth_getFilterChanges
T+77095ms: eth_getFilterChanges
T+77095ms: eth_getFilterChanges
T+77095ms: eth_getFilterChanges
T+77095ms: eth_getFilterChanges
T+77450ms: eth_getBlockByNumber
T+77597ms: eth_getFilterChanges
T+77597ms: eth_getFilterChanges
T+77597ms: eth_getFilterChanges
T+77597ms: eth_getFilterChanges
T+77597ms: eth_getFilterChanges
T+78101ms: eth_getFilterChanges
T+78101ms: eth_getFilterChanges
T+78101ms: eth_getFilterChanges
T+78101ms: eth_getFilterChanges
T+78101ms: eth_getFilterChanges
T+78605ms: eth_getFilterChanges
T+78605ms: eth_getFilterChanges
T+78605ms: eth_getFilterChanges
T+78610ms: eth_getFilterChanges
T+78610ms: eth_getFilterChanges
T+79111ms: eth_getFilterChanges
T+79111ms: eth_getFilterChanges
T+79111ms: eth_getFilterChanges
T+79111ms: eth_getFilterChanges
T+79111ms: eth_getFilterChanges
T+79614ms: eth_getFilterChanges
T+79614ms: eth_getFilterChanges
T+79614ms: eth_getFilterChanges
T+79614ms: eth_getFilterChanges
T+79614ms: eth_getFilterChanges
T+80118ms: eth_getFilterChanges
T+80118ms: eth_getFilterChanges
T+80118ms: eth_getFilterChanges
T+80118ms: eth_getFilterChanges
T+80118ms: eth_getFilterChanges
T+80623ms: eth_getFilterChanges
T+80623ms: eth_getFilterChanges
T+80623ms: eth_getFilterChanges
T+80623ms: eth_getFilterChanges
T+80623ms: eth_getFilterChanges
T+81125ms: eth_getFilterChanges
T+81125ms: eth_getFilterChanges
T+81125ms: eth_getFilterChanges
T+81125ms: eth_getFilterChanges
T+81125ms: eth_getFilterChanges
T+81627ms: eth_getFilterChanges
T+81627ms: eth_getFilterChanges
T+81627ms: eth_getFilterChanges
T+81627ms: eth_getFilterChanges
T+81627ms: eth_getFilterChanges
T+82131ms: eth_getFilterChanges
T+82131ms: eth_getFilterChanges
T+82131ms: eth_getFilterChanges
T+82136ms: eth_getFilterChanges
T+82136ms: eth_getFilterChanges
T+82636ms: eth_getFilterChanges
T+82636ms: eth_getFilterChanges
T+82636ms: eth_getFilterChanges
T+82636ms: eth_getFilterChanges
T+82636ms: eth_getFilterChanges
T+83141ms: eth_getFilterChanges
T+83141ms: eth_getFilterChanges
T+83141ms: eth_getFilterChanges
T+83141ms: eth_getFilterChanges
T+83146ms: eth_getFilterChanges
T+83642ms: eth_getFilterChanges
T+83642ms: eth_getFilterChanges
T+83647ms: eth_getFilterChanges
T+83647ms: eth_getFilterChanges
T+83647ms: eth_getFilterChanges
T+84144ms: eth_getFilterChanges
T+84144ms: eth_getFilterChanges
T+84144ms: eth_getFilterChanges
T+84144ms: eth_getFilterChanges
T+84151ms: eth_getFilterChanges
T+84650ms: eth_getFilterChanges
T+84650ms: eth_getFilterChanges
T+84650ms: eth_getFilterChanges
T+84650ms: eth_getFilterChanges
T+84650ms: eth_getFilterChanges
T+85152ms: eth_getFilterChanges
T+85152ms: eth_getFilterChanges
T+85152ms: eth_getFilterChanges
T+85152ms: eth_getFilterChanges
T+85152ms: eth_getFilterChanges
T+85657ms: eth_getFilterChanges
T+85657ms: eth_getFilterChanges
T+85657ms: eth_getFilterChanges
T+85657ms: eth_getFilterChanges
T+85657ms: eth_getFilterChanges
T+86159ms: eth_getFilterChanges
T+86159ms: eth_getFilterChanges
T+86159ms: eth_getFilterChanges
T+86159ms: eth_getFilterChanges
T+86159ms: eth_getFilterChanges
T+86666ms: eth_getFilterChanges
T+86666ms: eth_getFilterChanges
T+86666ms: eth_getFilterChanges
T+86666ms: eth_getFilterChanges
T+86666ms: eth_getFilterChanges
T+87168ms: eth_getFilterChanges
T+87168ms: eth_getFilterChanges
T+87168ms: eth_getFilterChanges
T+87168ms: eth_getFilterChanges
T+87168ms: eth_getFilterChanges
T+87674ms: eth_getFilterChanges
T+87674ms: eth_getFilterChanges
T+87674ms: eth_getFilterChanges
T+87674ms: eth_getFilterChanges
T+87674ms: eth_getFilterChanges
T+88174ms: eth_getFilterChanges
T+88174ms: eth_getFilterChanges
T+88174ms: eth_getFilterChanges
T+88174ms: eth_getFilterChanges
T+88174ms: eth_getFilterChanges
T+88676ms: eth_getFilterChanges
T+88676ms: eth_getFilterChanges
T+88676ms: eth_getFilterChanges
T+88682ms: eth_getFilterChanges
T+88682ms: eth_getFilterChanges
T+89181ms: eth_getFilterChanges
T+89181ms: eth_getFilterChanges
T+89181ms: eth_getFilterChanges
T+89181ms: eth_getFilterChanges
T+89185ms: eth_getFilterChanges
T+89686ms: eth_getFilterChanges
T+89686ms: eth_getFilterChanges
T+89686ms: eth_getFilterChanges
T+89686ms: eth_getFilterChanges
T+89686ms: eth_getFilterChanges
T+90191ms: eth_getFilterChanges
T+90191ms: eth_getFilterChanges
T+90191ms: eth_getFilterChanges
T+90191ms: eth_getFilterChanges
T+90191ms: eth_getFilterChanges
T+90696ms: eth_getFilterChanges
T+90696ms: eth_getFilterChanges
T+90696ms: eth_getFilterChanges
T+90696ms: eth_getFilterChanges
T+90696ms: eth_getFilterChanges
T+91199ms: eth_getFilterChanges
T+91199ms: eth_getFilterChanges
T+91199ms: eth_getFilterChanges
T+91199ms: eth_getFilterChanges
T+91199ms: eth_getFilterChanges
T+91701ms: eth_getFilterChanges
T+91701ms: eth_getFilterChanges
T+91701ms: eth_getFilterChanges
T+91701ms: eth_getFilterChanges
T+91701ms: eth_getFilterChanges
T+92203ms: eth_getFilterChanges
T+92203ms: eth_getFilterChanges
T+92203ms: eth_getFilterChanges
T+92203ms: eth_getFilterChanges
T+92203ms: eth_getFilterChanges
T+92708ms: eth_getFilterChanges
T+92708ms: eth_getFilterChanges
T+92714ms: eth_getFilterChanges
T+92714ms: eth_getFilterChanges
T+92714ms: eth_getFilterChanges
T+93215ms: eth_getFilterChanges
T+93215ms: eth_getFilterChanges
T+93220ms: eth_getFilterChanges
T+93220ms: eth_getFilterChanges
T+93220ms: eth_getFilterChanges
```

**Comment by seesemichaelj** [comment]
Hi @vshall20, this is the same error that you reported in #709. Thanks however!
