### ISSUE TITLE
System Error when running Ganache 1.1.0 on darwin

### ISSUE THREAD

**Issue by kipliklotrika** [trufflesuite/ganache#742]
Just changed local network environment. Now, I'm not able to change listening address.

PLATFORM: darwin
GANACHE VERSION: 1.1.0

EXCEPTION:
```
Error: listen EADDRNOTAVAIL 192.168.100.161:7545
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at Server.setupListenHandle [as _listen2] (net.js:1302:19)
    at listenInCluster (net.js:1367:12)
    at doListen (net.js:1493:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: Starting server with initial configuration: {"hostname":"192.168.100.161","port":7545,"network_id":5777,"total_accounts":10,"unlocked_accounts":[],"vmErrorsOnRPCResponse":true,"gasLimit":10000000}
```

**Comment by seesemichaelj** [comment]
Thanks for reporting this! We're tracking the issue in #666. You can get your Ganache back up and running by changing the hostname to an interface that the computer you are running Ganache from has access to (i.e. `127.0.0.1` or `0.0.0.0`) in the `~/Library/Application\ Support/Ganache/Settings` file.

If you're trying to connect to another RPC instance, see my comment here: https://github.com/trufflesuite/ganache/issues/731#issuecomment-396683496
