### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by JCCDex** [trufflesuite/ganache#745]
PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+13021ms: eth_uninstallFilter
T+13025ms: eth_sendTransaction
T+13069ms:   Transaction: 0xd7bc86d31bee32fa3988f1c1eabce403a1b5d570340a3a9cdba53a472ee8c956
T+13073ms:   Gas usage: 41981
T+13076ms:   Block Number: 2
T+13076ms:   Block Time: Wed Jun 13 2018 15:22:10 GMT+0800 (CST)
T+13082ms: eth_getTransactionReceipt
T+13086ms: eth_accounts
T+13979ms: eth_sendTransaction
T+14016ms:   Transaction: 0x3f10ec127819db7aa9c3cf863a749acfed95c8e4e5cccf776478ff00bddec85a
T+14016ms:   Contract created: 0x345ca3e014aaf5dca488057592ee47305d9b3e10
T+14016ms:   Gas usage: 2168470
T+14016ms:   Block Number: 3
T+14019ms:   Block Time: Wed Jun 13 2018 15:22:11 GMT+0800 (CST)
T+14022ms: eth_newBlockFilter
T+14025ms: eth_getFilterChanges
T+14029ms: eth_getTransactionReceipt
T+14038ms: eth_getCode
T+14048ms: eth_uninstallFilter
T+14052ms: eth_sendTransaction
T+14122ms:   Transaction: 0x16d104ae5812162dbd2127fb27cb2b93e8a1eb2679727b6d6e8d76e999c54854
T+14122ms:   Contract created: 0xf25186b5081ff5ce73482ad761db0eb0d25abfbf
T+14122ms:   Gas usage: 1159528
T+14122ms:   Block Number: 4
T+14122ms:   Block Time: Wed Jun 13 2018 15:22:11 GMT+0800 (CST)
T+14125ms: eth_newBlockFilter
T+14128ms: eth_getFilterChanges
T+14135ms: eth_getTransactionReceipt
T+14139ms: eth_getCode
T+14146ms: eth_uninstallFilter
T+14149ms: eth_sendTransaction
T+14622ms:   Transaction: 0xb6ff8572affdff58771b066f3f068e5c842f3e303d38837072986c1e8739d1c2
T+14622ms:   Contract created: 0x8f0483125fcb9aaaefa9209d8e9d7b9c8b9fb90f
T+14622ms:   Gas usage: 2180140
T+14622ms:   Block Number: 5
T+14622ms:   Block Time: Wed Jun 13 2018 15:22:11 GMT+0800 (CST)
T+14626ms: eth_newBlockFilter
T+14629ms: eth_getFilterChanges
T+14636ms: eth_getTransactionReceipt
T+14643ms: eth_getCode
T+14648ms: eth_uninstallFilter
T+14651ms: eth_sendTransaction
T+14690ms:   Transaction: 0xbed97adbc4e2b56b11b1c13a0491cf35abaf53ba717ccfc8766876adadc83535
T+14690ms:   Contract created: 0x8f0483125fcb9aaaefa9209d8e9d7b9c8b9fb90f
T+14690ms:   Gas usage: 1300469
T+14690ms:   Block Number: 6
T+14690ms:   Block Time: Wed Jun 13 2018 15:22:11 GMT+0800 (CST)
T+14693ms: eth_newBlockFilter
T+14697ms: eth_getFilterChanges
T+14701ms: eth_getTransactionReceipt
T+14705ms: eth_getCode
T+14812ms: eth_uninstallFilter
T+14814ms: eth_sendTransaction
T+14833ms:   Transaction: 0x0faca9f680c3dbf3e6d41c8695e44a8a3c27184f28d4d0eebaa633ea51b8736d
T+14833ms:   Gas usage: 26981
T+14833ms:   Block Number: 7
T+14833ms:   Block Time: Wed Jun 13 2018 15:22:12 GMT+0800 (CST)
T+14836ms: eth_getTransactionReceipt
T+15500ms: evm_snapshot
T+15621ms: eth_gasPrice
T+15625ms: eth_blockNumber
T+15629ms: eth_call
T+15645ms: eth_blockNumber
T+15651ms: eth_newFilter
T+15653ms: eth_sendTransaction
T+15706ms:   Transaction: 0xe5fcc3de2d30a3b6014b6bb1bb17700289807176d70938e94445c91d39998e3e
T+15706ms:   Gas usage: 135905
T+15706ms:   Block Number: 8
T+15709ms:   Block Time: Wed Jun 13 2018 15:22:12 GMT+0800 (CST)
T+15712ms: eth_sendTransaction
T+15758ms:   Transaction: 0x994ac63e09e53696903177a5a6379e47d0bbf9cfdbc9aacbcfc38ee1d128b3c5
T+15758ms:   Gas usage: 135905
T+15758ms:   Block Number: 9
T+15760ms:   Block Time: Wed Jun 13 2018 15:22:12 GMT+0800 (CST)
T+15863ms: eth_getTransactionByHash
T+15876ms: eth_call
T+15902ms: eth_call
T+15920ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+15920ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+15920ms: 
T+15920ms: TypeError: Cannot read property 'get' of undefined
T+15920ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+15920ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+15920ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+15920ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+15920ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+15920ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+15920ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+15920ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+15920ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+15920ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by seesemichaelj** [comment]
Thanks for reporting this!

This apparently was fixed in `v1.1.0`. I suggest upgrading to the latest release (https://github.com/trufflesuite/ganache/releases)

Thanks!
