### ISSUE TITLE
System Error when running Ganache 1.1.0 on darwin

### ISSUE THREAD

**Issue by dshm** [trufflesuite/ganache#754]
PLATFORM: darwin
GANACHE VERSION: 1.1.0

EXCEPTION:
```
Blockchain process exited prematurely with code '1', due to signal 'null'.
```

APPLICATION LOG:
```
T+0ms: Error: Cannot find module 'lodash.padstart'
T+0ms:     at Function.Module._resolveFilename (module.js:485:15)
T+0ms:     at Function.Module._load (module.js:437:25)
T+0ms:     at Module.require (module.js:513:17)
T+0ms:     at require (internal/module.js:11:18)
T+0ms:     at Object.<anonymous> (/src/chain/logging.js:3:16)
T+0ms:     at Object.<anonymous> (/src/chain/logging.js:86:3)
T+0ms:     at Module._compile (module.js:569:30)
T+0ms:     at Object.Module._extensions..js (module.js:580:10)
T+0ms:     at Module.load (module.js:503:32)
T+0ms:     at tryModuleLoad (module.js:466:12)
T+0ms:     at Function.Module._load (module.js:458:3)
T+0ms:     at Module.require (module.js:513:17)
T+0ms:     at require (internal/module.js:11:18)
T+0ms:     at Object.<anonymous> (/src/chain/chain.js:5:15)
T+0ms:     at Object.<anonymous> (/src/chain/chain.js:185:3)
T+0ms:     at Module._compile (module.js:569:30)
T+0ms:     at Object.Module._extensions..js (module.js:580:10)
T+0ms:     at Module.load (module.js:503:32)
T+0ms:     at tryModuleLoad (module.js:466:12)
T+0ms:     at Function.Module._load (module.js:458:3)
T+0ms:     at Function.Module.runMain (module.js:605:10)
T+0ms:     at startup (bootstrap_node.js:167:16)
T+0ms:     at bootstrap_node.js:589:3
```

**Comment by seesemichaelj** [comment]
Thanks for reporting this! This issue should have only been present in the `develop` branch and never made it to `master`/release. 9ffbb50c7ee1b5c0c541799604bb1f162281debd fixed this
