### ISSUE TITLE
System Error when running Ganache 1.1.0 on win32

### ISSUE THREAD

**Issue by JoseYang** [trufflesuite/ganache#819]
PLATFORM: win32
GANACHE VERSION: 1.1.0

EXCEPTION:
```
Error: listen EADDRNOTAVAIL 192.168.3.238:7545
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at Server.setupListenHandle [as _listen2] (net.js:1302:19)
    at listenInCluster (net.js:1367:12)
    at doListen (net.js:1493:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: Starting server with initial configuration: {"hostname":"192.168.3.238","port":7545,"network_id":5777,"total_accounts":10,"unlocked_accounts":[],"vmErrorsOnRPCResponse":true}
```

**Comment by seesemichaelj** [comment]
This issue is occurring because you specified a hostname which isn't available for use on your PC. The issue #666 was resolved in 1.2.x

If you're trying to connect to another RPC instance, see my comment here: https://github.com/trufflesuite/ganache/issues/731#issuecomment-396683496

### Please Update
We updated the interface and made it easier for you to change the settings when they don't work (like this issue).

Head over to https://github.com/trufflesuite/ganache/releases/latest to get the most recent version of Ganache!
