### ISSUE TITLE
System Error when running Ganache 1.0.2 on win32

### ISSUE THREAD

**Issue by amitlzkpa** [trufflesuite/ganache#844]
Nothing special; basic testing of project I built from petshop

PLATFORM: win32
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+3786270ms:   Block Time: Sun Jul 15 2018 19:57:04 GMT-0400 (Eastern Daylight Time)
T+3786270ms:   Runtime Error: revert
T+3786275ms: eth_getLogs
T+3786281ms: eth_blockNumber
T+3786285ms: eth_sendTransaction
T+3786491ms:   Transaction: 0x9f6d57c96d0313e4b693101640f26e2fddcf19d7ffb9693c67c0ff43499c4e5f
T+3786491ms:   Contract created: 0xbd2e0bd56dea31e24082bf88fd0ad88ff27ef95c
T+3786491ms:   Gas usage: 994990
T+3786491ms:   Block Number: 590
T+3786491ms:   Block Time: Sun Jul 15 2018 19:57:04 GMT-0400 (Eastern Daylight Time)
T+3786494ms: eth_newBlockFilter
T+3786498ms: eth_getFilterChanges
T+3786506ms: eth_getTransactionReceipt
T+3786513ms: eth_getCode
T+3786518ms: eth_uninstallFilter
T+3786522ms: eth_sendTransaction
T+3786573ms:   Transaction: 0x75205356bcdef42b29cae813e91a84d4c749e0e8faded479e5f2dc5caeedeab4
T+3786573ms:   Gas usage: 103112
T+3786573ms:   Block Number: 591
T+3786573ms:   Block Time: Sun Jul 15 2018 19:57:05 GMT-0400 (Eastern Daylight Time)
T+3786577ms: eth_sendTransaction
T+3786645ms:   Transaction: 0x8ecce121c371c231348daa56c68669761eb2feca228eaae5e24508af8da301cb
T+3786645ms:   Gas usage: 85109
T+3786645ms:   Block Number: 592
T+3786645ms:   Block Time: Sun Jul 15 2018 19:57:05 GMT-0400 (Eastern Daylight Time)
T+3786648ms: eth_getTransactionReceipt
T+3786653ms: eth_sendTransaction
T+3786757ms:   Transaction: 0x78aedc85f47d55f578fa6b198fca68d1ebafb8a9e38e75cf4ab4f64b4609e9aa
T+3786757ms:   Gas usage: 45180
T+3786757ms:   Block Number: 593
T+3786757ms:   Block Time: Sun Jul 15 2018 19:57:05 GMT-0400 (Eastern Daylight Time)
T+3786760ms: eth_getTransactionReceipt
T+3786763ms: eth_sendTransaction
T+3786777ms:   Transaction: 0x13662e1c4509fd4a8f7c90d7ccad9941e8674033cc48d8974206021925532ab0
T+3786777ms:   Gas usage: 23425
T+3786777ms:   Block Number: 594
T+3786777ms:   Block Time: Sun Jul 15 2018 19:57:05 GMT-0400 (Eastern Daylight Time)
T+3786777ms:   Runtime Error: revert
T+3786782ms: eth_getLogs
T+3832080ms: net_version
T+3832090ms: eth_accounts
T+3832132ms: eth_accounts
T+3833774ms: eth_accounts
T+3833790ms: eth_sendTransaction
T+3833863ms:   Transaction: 0xb6916306dd2e49490e8864c3416230748178d18f97577c5b7f45ed56a005ef3a
T+3833863ms:   Contract created: 0xa45f2beb30c980ff3b888631c5966fbc6285a99c
T+3833863ms:   Gas usage: 269607
T+3833863ms:   Block Number: 595
T+3833863ms:   Block Time: Sun Jul 15 2018 19:57:52 GMT-0400 (Eastern Daylight Time)
T+3833866ms: eth_newBlockFilter
T+3833871ms: eth_getFilterChanges
T+3833883ms: eth_getTransactionReceipt
T+3833891ms: eth_getCode
T+3833907ms: eth_uninstallFilter
T+3833910ms: eth_sendTransaction
T+3834201ms:   Transaction: 0xc4078c07194de1450236c42bcf5b6ce1a454387392467eb83c0f5b9fdd58ea46
T+3834201ms:   Gas usage: 41981
T+3834201ms:   Block Number: 596
T+3834201ms:   Block Time: Sun Jul 15 2018 19:57:52 GMT-0400 (Eastern Daylight Time)
T+3834205ms: eth_getTransactionReceipt
T+3834216ms: eth_accounts
T+3834270ms: eth_sendTransaction
T+3834339ms: C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:63898
T+3834339ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&
T+3834339ms: 
T+3834339ms: TypeError: Cannot read property 'get' of undefined
T+3834339ms:     at dbGet (C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:56029:7)
T+3834339ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:17614:5
T+3834339ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:23091:20
T+3834339ms:     at iterate (C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:23172:13)
T+3834339ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:23184:29
T+3834339ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:22954:16
T+3834339ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:17619:7
T+3834339ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:56034:9
T+3834339ms:     at dispatchError (C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:36358:36)
T+3834339ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:22744:14
```

**Comment by seesemichaelj** [comment]
Thanks for reporting this! We're tracking this common issue in #667. I'm going to close this issue in favor of that one.

On a separate (and potentially related note), I see you're still running `v1.0.2`. I suggest heading to the [releases page](https://github.com/trufflesuite/ganache/releases/) and getting the latest version (`v1.2.1` at the time of writing this)
