### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by n1c01a5** [trufflesuite/ganache#852]
When I ran the truffle tests from this repository https://github.com/kleros/kleros

Ganache failed with this error: `Blockchain process exited prematurely with code '7', due to signal 'null'.`

The workflow:
```
git clone https://github.com/kleros/kleros.git
cd kleros
yarn
yarn migrate
truffle compile
truffle test
```

PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+39523ms: eth_getTransactionReceipt
T+39531ms: net_version
T+39533ms: eth_sendTransaction
T+39573ms:   Transaction: 0xc3c2219cd7a90a450ce1e0f8ac3548b777f4eefed36b1becb8f9787d2249e66d
T+39573ms:   Gas usage: 58694
T+39573ms:   Block Number: 184
T+39573ms:   Block Time: Mon Jul 23 2018 14:32:35 GMT+0300 (EEST)
T+39576ms: eth_getTransactionReceipt
T+39584ms: net_version
T+39588ms: eth_call
T+39617ms: net_version
T+39621ms: eth_call
T+39641ms: net_version
T+39646ms: eth_call
T+39667ms: net_version
T+39671ms: eth_sendTransaction
T+39711ms:   Transaction: 0xca6a14f6ead09229f296c7c781fe84b7ecc00563e0d8aefceafccdd30054d404
T+39711ms:   Gas usage: 62641
T+39711ms:   Block Number: 185
T+39711ms:   Block Time: Mon Jul 23 2018 14:32:35 GMT+0300 (EEST)
T+39714ms: eth_getTransactionReceipt
T+39721ms: net_version
T+39725ms: eth_sendTransaction
T+39838ms:   Transaction: 0x9c35688faf696c000c4bdf503454750f28704e69dfe57c18a0318d64b73e5241
T+39838ms:   Gas usage: 297463
T+39838ms:   Block Number: 186
T+39838ms:   Block Time: Mon Jul 23 2018 14:32:35 GMT+0300 (EEST)
T+39841ms: eth_getTransactionReceipt
T+39851ms: net_version
T+39867ms: eth_sendTransaction
T+39937ms:   Transaction: 0xe5be3a25c6702bacd8e3a39a61b2ab767e1f3a5c2804dfa143e85063ea4329dd
T+39937ms:   Gas usage: 35995
T+39937ms:   Block Number: 187
T+39937ms:   Block Time: Mon Jul 23 2018 14:32:35 GMT+0300 (EEST)
T+39940ms: eth_getTransactionReceipt
T+39944ms: net_version
T+39947ms: eth_sendTransaction
T+39978ms:   Transaction: 0x0efdc5832cee59f1f8c42f3f9f1d48720ff5a63efb7e7bc209b99320e9e9208e
T+39978ms:   Gas usage: 36310
T+39978ms:   Block Number: 188
T+39978ms:   Block Time: Mon Jul 23 2018 14:32:35 GMT+0300 (EEST)
T+39982ms: eth_getTransactionReceipt
T+39988ms: net_version
T+39994ms: eth_call
T+40017ms: net_version
T+40021ms: eth_sendTransaction
T+40092ms:   Transaction: 0x59fd9f6f0527854af136953e5375592e3375586cff9ceff51a3adbcce8aad5c8
T+40092ms:   Gas usage: 123525
T+40092ms:   Block Number: 189
T+40092ms:   Block Time: Mon Jul 23 2018 14:32:35 GMT+0300 (EEST)
T+40096ms: eth_getTransactionReceipt
T+40101ms: net_version
T+40105ms: eth_sendTransaction
T+40125ms:   Transaction: 0x56ed9ef328e59fb8786e4bb98180e4a8b5add46cf6946dc1813bb3eac0c505b0
T+40125ms:   Gas usage: 23380
T+40125ms:   Block Number: 190
T+40125ms:   Block Time: Mon Jul 23 2018 14:32:35 GMT+0300 (EEST)
T+40125ms:   Runtime Error: revert
T+40129ms: net_version
T+40133ms: eth_call
T+40152ms: net_version
T+40156ms: eth_sendTransaction
T+40231ms:   Transaction: 0xa07e44f59d45aae604c9ae51f0b3ead8d86fb1d0055305dd34530a3a7bb484e3
T+40231ms:   Gas usage: 113392
T+40231ms:   Block Number: 191
T+40231ms:   Block Time: Mon Jul 23 2018 14:32:35 GMT+0300 (EEST)
T+40234ms: eth_getTransactionReceipt
T+40241ms: net_version
T+40246ms: eth_call
T+40273ms: net_version
T+40278ms: eth_sendTransaction
T+40339ms:   Transaction: 0x22d2242eac3c8e916c6ea87257a1e292a9bf8110a482b67275a02abe4d3aa430
T+40339ms:   Gas usage: 96624
T+40339ms:   Block Number: 192
T+40339ms:   Block Time: Mon Jul 23 2018 14:32:35 GMT+0300 (EEST)
T+40342ms: eth_getTransactionReceipt
T+40351ms: net_version
T+40367ms: eth_call
T+40387ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+40387ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+40387ms: 
T+40387ms: TypeError: Cannot read property 'get' of undefined
T+40387ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+40387ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+40387ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+40387ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+40387ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+40387ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+40387ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+40387ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+40387ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+40387ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by n1c01a5** [comment]
it worked with 1.2.1 version
