### ISSUE TITLE
System Error when running Ganache 1.0.2 on linux

### ISSUE THREAD

**Issue by licolsan** [trufflesuite/ganache#858]
This is my error when I run loop to  execute transaction to blockchain, actually when I want to transfer tokens to all existed wallet account.

PLATFORM: linux
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+192693ms: eth_getTransactionReceipt
T+192695ms:   Transaction: 0xa15fb149ea90526a6637dbb917dd7c7a409360a6844daef866bc9d804ed14019
T+192695ms:   Gas usage: 51406
T+192695ms:   Block Number: 73
T+192695ms:   Block Time: Sun Jul 29 2018 21:12:15 GMT+0700 (+07)
T+192845ms: eth_getTransactionReceipt
T+192848ms:   Transaction: 0x8eea0506669913e8a307a4c65abdd98cdc0a24e6f83b6b95e0f41c2dd54211b2
T+192848ms:   Gas usage: 51406
T+192848ms:   Block Number: 74
T+192848ms:   Block Time: Sun Jul 29 2018 21:12:15 GMT+0700 (+07)
T+192850ms: eth_getTransactionReceipt
T+192853ms:   Transaction: 0xc332be050e27aac96e0bf38b2900eb6e2a339402c0a2420e2020ee4fede54851
T+192853ms:   Gas usage: 51406
T+192853ms:   Block Number: 75
T+192853ms:   Block Time: Sun Jul 29 2018 21:12:15 GMT+0700 (+07)
T+192856ms: eth_getTransactionReceipt
T+193122ms:   Transaction: 0x4d6b41d3648d71864903bae1b8f899a03dd6c1681dabd1b737f078a766dc770b
T+193122ms:   Gas usage: 51406
T+193122ms:   Block Number: 76
T+193122ms:   Block Time: Sun Jul 29 2018 21:12:15 GMT+0700 (+07)
T+193128ms: eth_getTransactionReceipt
T+193133ms:   Transaction: 0x169bd81794af06ac037f4ce21303af0d946a63476a2025955f35dfd78609e858
T+193133ms:   Gas usage: 51406
T+193133ms:   Block Number: 77
T+193133ms:   Block Time: Sun Jul 29 2018 21:12:15 GMT+0700 (+07)
T+193136ms: eth_getTransactionReceipt
T+193141ms:   Transaction: 0x2b105ddb7a57679106601b4010976f3c85f95f9de4411da577057c90f7423dac
T+193141ms:   Gas usage: 51406
T+193145ms:   Block Number: 78
T+193145ms:   Block Time: Sun Jul 29 2018 21:12:15 GMT+0700 (+07)
T+193150ms: eth_getTransactionReceipt
T+193154ms:   Transaction: 0x9686b6dfb0832facecdb08c3b39c53bdb2767ba949cf5c0bb088852ebe48a4fe
T+193154ms:   Gas usage: 51406
T+193154ms:   Block Number: 79
T+193158ms:   Block Time: Sun Jul 29 2018 21:12:15 GMT+0700 (+07)
T+193161ms: eth_getTransactionReceipt
T+193164ms:   Transaction: 0x87bd896bc766a6e71e9e3677a8c6f57de24ff5e7977d72adafd36dc6db2ca5ca
T+193164ms:   Gas usage: 51406
T+193164ms:   Block Number: 80
T+193164ms:   Block Time: Sun Jul 29 2018 21:12:15 GMT+0700 (+07)
T+193168ms: eth_getTransactionReceipt
T+193171ms:   Transaction: 0xe81cf5d0d67c0e3e51a8b857870aa27bb041be304a6b35622033a022f05af098
T+193171ms:   Gas usage: 51406
T+193171ms:   Block Number: 81
T+193171ms:   Block Time: Sun Jul 29 2018 21:12:15 GMT+0700 (+07)
T+193175ms: eth_getTransactionReceipt
T+193178ms:   Transaction: 0x87b79d194e7175937e3f584e956ee2f4835c792ca90d103a8b2741afe1e21746
T+193178ms:   Gas usage: 51406
T+193178ms:   Block Number: 82
T+193178ms:   Block Time: Sun Jul 29 2018 21:12:15 GMT+0700 (+07)
T+193186ms: eth_getTransactionReceipt
T+193189ms:   Transaction: 0x48a934cb26dc91b94d7b8606e36525457fbf5088d53c8617e16e7ac0b3891a5e
T+193189ms:   Gas usage: 51406
T+193189ms:   Block Number: 83
T+193189ms:   Block Time: Sun Jul 29 2018 21:12:15 GMT+0700 (+07)
T+193192ms: eth_getTransactionReceipt
T+193343ms:   Transaction: 0xd22fd305c8ac3b99040d0dab89fad3c035f685019e8f12b164bc1624ff35e4ab
T+193343ms:   Gas usage: 51406
T+193343ms:   Block Number: 84
T+193343ms:   Block Time: Sun Jul 29 2018 21:12:15 GMT+0700 (+07)
T+193346ms: eth_getTransactionReceipt
T+193542ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+193542ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_W
T+193542ms: 
T+193542ms: TypeError: Cannot read property 'get' of undefined
T+193542ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+193542ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+193542ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+193542ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+193542ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+193542ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+193542ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+193542ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+193542ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+193542ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by seesemichaelj** [comment]
@licolsan is this error reproducible/repeatable for you? We've been tracking this issue in #667, but I'm speculating that the issue is no longer a problem in more recent releases. Please try upgrading Ganache to the [latest version](https://github.com/trufflesuite/ganache/releases) and see if that fixes the problem.

If your problem is reproducible reliably, and the issue goes away after upgrading, please let me know so I can inform others they need to upgrade.

**Comment by seesemichaelj** [comment]
I'm actually almost certain the issue is no longer present in versions `1.1.0+` as we haven't had any reports of this issue with those versions.

**Comment by licolsan** [comment]
Okay, I see. thank you so much! :+1: :D
