### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by IronHED** [trufflesuite/ganache#861]
Following the Truffle Debug instructions attempting to perform a migrate.

PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+18262ms:   Transaction: 0xd7bc86d31bee32fa3988f1c1eabce403a1b5d570340a3a9cdba53a472ee8c956
T+18262ms:   Gas usage: 42008
T+18262ms:   Block Number: 6
T+18266ms:   Block Time: Fri Aug 03 2018 21:15:14 GMT-0400 (EDT)
T+69371ms: net_version
T+69379ms: eth_accounts
T+79044ms: eth_call
T+79080ms: eth_call
T+79096ms: eth_accounts
T+79110ms: eth_sendTransaction
T+79115ms: eth_newBlockFilter
T+79121ms: eth_getFilterChanges
T+79131ms: eth_getTransactionReceipt
T+79627ms: eth_getFilterChanges
T+80127ms: eth_getFilterChanges
T+80629ms: eth_getFilterChanges
T+81130ms: eth_getFilterChanges
T+81335ms:   Transaction: 0x4031892d2b949d8f2b9d0e2cab3b960ed339c563f1a3b45c49455987ce2b8f9c
T+81335ms:   Contract created: 0x345ca3e014aaf5dca488057592ee47305d9b3e10
T+81335ms:   Gas usage: 277462
T+81339ms:   Block Number: 27
T+81339ms:   Block Time: Fri Aug 03 2018 21:16:18 GMT-0400 (EDT)
T+81630ms: eth_getFilterChanges
T+82131ms: eth_getFilterChanges
T+82631ms: eth_getFilterChanges
T+83132ms: eth_getFilterChanges
T+83632ms: eth_getFilterChanges
T+84132ms: eth_getFilterChanges
T+84632ms: eth_getFilterChanges
T+84636ms: eth_getTransactionReceipt
T+84640ms: eth_getCode
T+84650ms: eth_uninstallFilter
T+84654ms: eth_sendTransaction
T+84659ms: eth_getTransactionReceipt
T+85668ms: eth_getTransactionReceipt
T+86675ms: eth_getTransactionReceipt
T+87269ms:   Transaction: 0xcc6faa4193f59d7da676c7557e13271f41a8a97ca0ce171911aaf0355b92f11d
T+87269ms:   Gas usage: 42008
T+87269ms:   Block Number: 29
T+87272ms:   Block Time: Fri Aug 03 2018 21:16:24 GMT-0400 (EDT)
T+87682ms: eth_getTransactionReceipt
T+87691ms: eth_accounts
T+87703ms: eth_sendTransaction
T+87707ms: eth_newBlockFilter
T+87711ms: eth_getFilterChanges
T+87717ms: eth_getTransactionReceipt
T+88211ms: eth_getFilterChanges
T+88715ms: eth_getFilterChanges
T+89216ms: eth_getFilterChanges
T+89719ms: eth_getFilterChanges
T+90221ms: eth_getFilterChanges
T+90305ms:   Transaction: 0x717f91e571da7f03af4f94076880e9caabe3f178605627476a886d97a094f848
T+90305ms:   Contract created: 0x8f0483125fcb9aaaefa9209d8e9d7b9c8b9fb90f
T+90305ms:   Gas usage: 153311
T+90305ms:   Block Number: 30
T+90308ms:   Block Time: Fri Aug 03 2018 21:16:27 GMT-0400 (EDT)
T+90726ms: eth_getFilterChanges
T+91231ms: eth_getFilterChanges
T+91736ms: eth_getFilterChanges
T+92239ms: eth_getFilterChanges
T+92242ms: eth_getTransactionReceipt
T+92248ms: eth_getCode
T+92260ms: eth_uninstallFilter
T+92265ms: eth_sendTransaction
T+92270ms: eth_getTransactionReceipt
T+93273ms: eth_getTransactionReceipt
T+93278ms:   Transaction: 0x61826f086be719997aa398ef8cbc8ba8d3fb9cdd04f7486fb0f2e0c7565d2b59
T+93278ms:   Gas usage: 27008
T+93278ms:   Block Number: 31
T+93282ms:   Block Time: Fri Aug 03 2018 21:16:30 GMT-0400 (EDT)
T+120641ms: eth_sendTransaction
T+120648ms: eth_getTransactionReceipt
T+121660ms: eth_getTransactionReceipt
T+122664ms: eth_getTransactionReceipt
T+123406ms:   Transaction: 0xe5fb8bfa239a2c1a4db58bf381ce033d7a50d96f380688e71f9a94d832e29b56
T+123406ms:   Gas usage: 298373
T+123406ms:   Block Number: 41
T+123410ms:   Block Time: Fri Aug 03 2018 21:17:00 GMT-0400 (EDT)
T+123672ms: eth_getTransactionReceipt
T+142885ms: debug_traceTransaction
T+143080ms: eth_getTransactionByHash
T+143094ms: eth_getCode
T+322210ms: net_version
T+322219ms: eth_accounts
T+339427ms: eth_call
T+342428ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+342428ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+342428ms: 
T+342428ms: TypeError: Cannot read property 'pop' of undefined
T+342428ms:     at CheckpointTrie.Trie._updateNode (/node_modules/ganache-cli/build/lib.node.js:56237:23)
T+342428ms:     at /node_modules/ganache-cli/build/lib.node.js:55984:16
T+342428ms:     at /node_modules/ganache-cli/build/lib.node.js:56320:14
T+342428ms:     at processNode (/node_modules/ganache-cli/build/lib.node.js:56325:23)
T+342428ms:     at /node_modules/ganache-cli/build/lib.node.js:56316:5
T+342428ms:     at /node_modules/ganache-cli/build/lib.node.js:56057:7
T+342428ms:     at /node_modules/ganache-cli/build/lib.node.js:17623:7
T+342428ms:     at /node_modules/ganache-cli/build/lib.node.js:22962:16
T+342428ms:     at /node_modules/ganache-cli/build/lib.node.js:23179:32
T+342428ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
```

**Comment by seesemichaelj** [comment]
Hey @ironhed! Thanks for reporting this! Please upgrade to the latest version (currently 1.2.1).

You can get it at https://github.com/trufflesuite/ganache/releases

If you're still having issues in the new version, please report a new issue.

Thanks!
