### ISSUE TITLE
System Error when running Ganache 1.1.0 on win32

### ISSUE THREAD

**Issue by benjaimess** [trufflesuite/ganache#877]
PLATFORM: win32
GANACHE VERSION: 1.1.0

EXCEPTION:
```
Error: Number can only safely store up to 53 bits
    at n (C:\Program Files\WindowsApps\Ganache_1.1.0.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\ganache-cli\build\webpack:\ganache\node_modules\bn.js\lib\bn.js:14:1)
    at c.toNumber (C:\Program Files\WindowsApps\Ganache_1.1.0.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\ganache-cli\build\webpack:\ganache\node_modules\bn.js\lib\bn.js:511:1)
    at Object.t.bufferToInt (C:\Program Files\WindowsApps\Ganache_1.1.0.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\ganache-cli\build\webpack:\ganache\node_modules\ethereumjs-util\dist\index.js:208:1)
    at Object.number (C:\Program Files\WindowsApps\Ganache_1.1.0.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\ganache-cli\build\webpack:\ganache\external "buffer":1:1)
    at n.blockchain.getQueuedNonce (C:\Program Files\WindowsApps\Ganache_1.1.0.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\ganache-cli\build\webpack:\ganache\node_modules\ganache-core\lib\statemanager.js:807:1)
    at C:\Program Files\WindowsApps\Ganache_1.1.0.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\ganache-cli\build\webpack:\ganache\node_modules\ganache-core\lib\blockchain_double.js:382:1
    at C:\Program Files\WindowsApps\Ganache_1.1.0.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\ganache-cli\build\webpack:\ganache\node_modules\merkle-patricia-tree\baseTrie.js:93:1
    at C:\Program Files\WindowsApps\Ganache_1.1.0.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\ganache-cli\build\webpack:\ganache\node_modules\merkle-patricia-tree\baseTrie.js:524:1
    at Object.return (C:\Program Files\WindowsApps\Ganache_1.1.0.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\ganache-cli\build\webpack:\ganache\node_modules\merkle-patricia-tree\baseTrie.js:489:1)
    at C:\Program Files\WindowsApps\Ganache_1.1.0.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\ganache-cli\build\webpack:\ganache\node_modules\merkle-patricia-tree\baseTrie.js:292:1
    at e (C:\Program Files\WindowsApps\Ganache_1.1.0.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\ganache-cli\build\webpack:\ganache\node_modules\merkle-patricia-tree\baseTrie.js:519:1)
    at C:\Program Files\WindowsApps\Ganache_1.1.0.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\ganache-cli\build\webpack:\ganache\node_modules\merkle-patricia-tree\baseTrie.js:519:1
    at C:\Program Files\WindowsApps\Ganache_1.1.0.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\ganache-cli\build\webpack:\ganache\node_modules\merkle-patricia-tree\baseTrie.js:188:1
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: Starting server with initial configuration: {"hostname":"127.0.0.1","port":7545,"network_id":5777,"total_accounts":10,"unlocked_accounts":[],"vmErrorsOnRPCResponse":true}
T+650ms: Ganache started successfully!
T+650ms: Waiting for requests...
T+30697ms: eth_getTransactionCount
T+30793ms: eth_sendRawTransaction
```

**Comment by davidmurdoch** [comment]
Hey @benjaimess, thanks for reporting this!

I noticed you're still on v1.1.0. I would highly consider up upgrading to v1.2.1 (https://github.com/trufflesuite/ganache/releases). That might actually resolve your problem (with some upgraded dependencies).

Another thing you could check is to make sure your code isn't attempting to pass around non-numeric data to a method expecting a numeric type. Some common mistakes devs make related to this issue can be found here: https://github.com/ethereumjs/ethereumjs-vm/issues/114

If upgrading fixes things for you, or you figure out it was a code issue on your side, let us know (and please close this issue)!

Otherwise, let us know what you were trying to do when you received this error and we'll take a closer look when we get a chance.

Thanks again!

**Comment by seesemichaelj** [comment]
We're also tracking this issue #847. I'm fairly certain this got fixed when we upgraded a dependency version

**Comment by seesemichaelj** [comment]
I'm actually going to close this in favor of #847
