### ISSUE TITLE
System Error when running Ganache 1.2.1 on darwin

### ISSUE THREAD

**Issue by jun0jang** [trufflesuite/ganache#879]
>>> w3 = web3.Web3(web3.HTTPProvider('http://localhost:7545'))
>>> a = w3.eth.filter('latest')
>>> a.get_all_entries()
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=7545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10e318a20>: Failed to establish a new connection: [Errno 61] Connection refused',))

PLATFORM: darwin
GANACHE VERSION: 1.2.1

EXCEPTION:
```
TypeError: c.getAllResults is not a function
    at o.d.getFilterLogs (/node_modules/ganache-cli/build/webpack:/ganache/node_modules/web3-provider-engine/subproviders/filters.js:198:1)
    at Timeout._onTimeout (/node_modules/ganache-cli/build/webpack:/ganache/node_modules/web3-provider-engine/subproviders/filters.js:78:1)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
```

APPLICATION LOG:
```
T+0ms: Starting server (version 1.2.1) with initial configuration: {"hostname":"127.0.0.1","port":7545,"network_id":5777,"default_balance_ether":100,"total_accounts":10,"unlocked_accounts":[],"locked":false,"vmErrorsOnRPCResponse":true,"verbose":false}
T+301ms: Ganache started successfully!
T+301ms: Waiting for requests...
T+5382ms: eth_newBlockFilter
T+10009ms: eth_getFilterChanges
T+15077ms: eth_accounts
T+15082ms: eth_accounts
T+15093ms: eth_sendTransaction
T+15240ms:   Transaction: 0x5ba5764dbdc2e96c3723bde82795b523be46ea19aa822770f25b4b4a87b18803
T+15240ms:   Gas usage: 21000
T+15240ms:   Block Number: 1
T+15240ms:   Block Time: Wed Aug 22 2018 13:27:22 GMT+0900 (KST)
T+16791ms: eth_getFilterChanges
T+43121ms: eth_accounts
T+43124ms: eth_accounts
T+43132ms: eth_sendTransaction
T+43274ms:   Transaction: 0x8b1d723bf20ec4be19333b3fa69ab56490f4df24f35c415ee6e9e8efefc2747d
T+43274ms:   Gas usage: 21000
T+43276ms:   Block Number: 2
T+43276ms:   Block Time: Wed Aug 22 2018 13:27:50 GMT+0900 (KST)
T+43521ms: eth_accounts
T+43525ms: eth_accounts
T+43534ms: eth_sendTransaction
T+43659ms:   Transaction: 0xb89ca066dc4fbb36b2c07c818e298c87189c368c1e5030845045e4ac71f1c0dc
T+43659ms:   Gas usage: 21000
T+43660ms:   Block Number: 3
T+43660ms:   Block Time: Wed Aug 22 2018 13:27:51 GMT+0900 (KST)
T+120420ms: eth_getFilterChanges
T+134723ms: eth_getFilterChanges
T+195906ms: eth_newBlockFilter
T+198625ms: eth_newBlockFilter
T+203773ms: eth_getFilterChanges
T+209225ms: eth_getFilterChanges
T+209945ms: eth_getFilterChanges
T+210569ms: eth_getFilterChanges
T+235261ms: eth_getFilterChanges
T+315186ms: eth_getFilterLogs
T+315208ms: eth_unsubscribe
```

**Comment by seesemichaelj** [comment]
Thanks @jun0jang for reporting this! Thanks for the reproduction steps! We'll check this one out!

**Comment by benjamincburns** [comment]
Pretty sure the bug [is here](https://github.com/MetaMask/provider-engine/blob/master/subproviders/filters.js#L197-L200). It's caused by calling `eth_getFilterLogs` with a filter ID for a block filter instead of a log filter. Lines 197-200 should return an error rather than trying to return all results for a non log filter type.

**Comment by benjamincburns** [comment]
Submitted MetaMask/provider-engine#276 to address this issue.

**Comment by davidmurdoch** [comment]
@balexander4 this issue should now be fixed in `develop`. Could you check if this is still an issue and close it if it's been resolved?
