### ISSUE TITLE
eth_getBlockByHash returns error instead of null

### ISSUE THREAD

**Issue by timmclean** [trufflesuite/ganache#906]
The eth_getBlockByHash method returns a "Key not found in database" error if the block hash does not match any known block.

## Expected Behavior
The [Ethereum RPC documentation](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getblockbyhash) says that eth_getBlockByHash should return null when no block is found. E.g. Infura responds like this:
```
{
  "id": 1,
  "jsonrpc": "2.0",
  "result": null
}
```

## Current Behavior
Currently Ganache returns an error response:
```
{
  "id": 1,
  "jsonrpc": "2.0",
  "error": {
    "message": "Key not found in database",
    "code": -32000,
    "data": {
      "stack": "NotFoundError: Key not found in database\n    at /usr/local/lib/node_modules/ganache-cli/build/cli.node.js:2:773948\n    at /usr/local/lib/node_modules/ganache-cli/build/cli.node.js:2:776500\n    at /usr/local/lib/node_modules/ganache-cli/build/cli.node.js:2:748581\n    at ReadFileContext.callback (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:2:750214)\n    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:352:13)",
      "name": "NotFoundError"
    }
  }
}
```

## Steps to Reproduce
```
curl http://localhost:8545 -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"eth_getBlockByHash","params":["0x8888888888888888888888888888888888888888888888888888888888888888",true],"id":1}'
```
To reproduce the Infura output:
```
curl https://mainnet.infura.io -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"eth_getBlockByHash","params":["0x8888888888888888888888888888888888888888888888888888888888888888",true],"id":1}'
```

## Your Environment
* Version used: Ganache CLI v6.1.0 (ganache-core: 2.1.0)

**Comment by davidmurdoch** [comment]
Hey @timmclean, thanks for taking the time to report this!

I've confirmed that this is an issue in the latest release as well as our development branch and added it to our backlog of issues.

**Comment by timmclean** [comment]
Thanks @davidmurdoch, I appreciate you looking into this!
