### ISSUE TITLE
Cannot read property 'pop' of undefined

### ISSUE THREAD

**Issue by takahser** [trufflesuite/ganache#952]
Okay, I'm not sure what happened, but ganache crashed and prompted me to raise an issue. This was the output it provided:

```
TypeError: Cannot read property 'pop' of undefined
    at CheckpointTrie.Trie._updateNode (/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:360:23)
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:107:16
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:461:14
    at processNode (/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:471:23)
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:516:13
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:180:7
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/util.js:75:7
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:52:16
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:269:32
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:44:16
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/util.js:71:7
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:157:9
    at /node_modules/ganache-core/lib/database/levelupobjectadapter.js:30:23
    at /node_modules/ganache-core/node_modules/level-sublevel/shell.js:101:15
    at /node_modules/ganache-core/node_modules/level-sublevel/nut.js:121:19
    at /node_modules/ganache-core/node_modules/cachedown/index.js:58:21
    at ReadFileContext.callback (/node_modules/ganache-core/lib/database/filedown.js:27:14)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
```

The error happened, when I tried to redeploy a contract.

**Comment by davidmurdoch** [comment]
Thanks @takahser for reporting this. It's possibly related to https://github.com/trufflesuite/ganache-core/issues/187 and we'll be tracking the issue there.
