### ISSUE TITLE
evm_mine system error when running Ganache 1.2.2 on darwin

### ISSUE THREAD

**Issue by PaulRBerg** [trufflesuite/ganache#961]
Occurred when I called `evm_mine` via Postman:

```
{
	"id": 1,
	"jsonrpc": "2.0",
	"method": "evm_mine",
	"params":[
		"2018-11-12T21:51:01Z"
	]
}
```

PLATFORM: darwin
GANACHE VERSION: 1.2.2

EXCEPTION:
```
Error: Number can only safely store up to 53 bits
    at assert (/node_modules/ganache-core/node_modules/bn.js/lib/bn.js:6:21)
    at BN.toNumber (/node_modules/ganache-core/node_modules/bn.js/lib/bn.js:506:7)
    at Object.exports.bufferToInt (/node_modules/ganache-core/node_modules/ethereumjs-util/dist/index.js:196:40)
    at SubscriptionSubprovider._notificationResultFromBlock (/node_modules/ganache-core/node_modules/web3-provider-engine/subproviders/subscriptions.js:121:44)
    at SubscriptionSubprovider._notificationHandler (/node_modules/ganache-core/node_modules/web3-provider-engine/subproviders/subscriptions.js:91:19)
    at Array.forEach (<anonymous>)
    at BlockFilter.<anonymous> (/node_modules/ganache-core/node_modules/web3-provider-engine/subproviders/subscriptions.js:62:15)
    at emitOne (events.js:115:13)
    at BlockFilter.emit (events.js:210:7)
    at BlockFilter.update (/node_modules/ganache-core/node_modules/web3-provider-engine/subproviders/filters.js:319:8)
    at emitOne (events.js:120:20)
    at Web3ProviderEngine.emit (events.js:210:7)
    at Web3ProviderEngine._setCurrentBlock (/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:165:8)
    at GanacheBlockTracker.Web3ProviderEngine.self._blockTracker.on (/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:35:10)
    at emitOne (events.js:120:20)
    at GanacheBlockTracker.emit (events.js:210:7)
    at GanacheBlockTracker._setCurrentBlock (/node_modules/ganache-core/lib/block_tracker.js:63:8)
    at emitOne (events.js:115:13)
    at BlockchainDouble.emit (events.js:210:7)
    at async.parallel (/node_modules/ganache-core/lib/blockchain_double.js:243:14)
    at /node_modules/ganache-core/node_modules/async/dist/async.js:3888:9
    at /node_modules/ganache-core/node_modules/async/dist/async.js:473:16
```

APPLICATION LOG:
```
T+0ms: Starting server (version 1.2.2) with initial configuration: {"hostname":"127.0.0.1","port":7545,"network_id":7923,"total_accounts":10,"unlocked_accounts":[],"vmErrorsOnRPCResponse":true,"default_balance_ether":100,"locked":false,"verbose":false}
T+43ms: Ganache started successfully!
T+43ms: Waiting for requests...
T+3959ms: evm_mine
T+3976ms: eth_unsubscribe
```

**Comment by davidmurdoch** [comment]
Related to https://github.com/trufflesuite/ganache/issues/847
