### ISSUE TITLE
Unexpected token =

### ISSUE THREAD

**Issue by ligi** [trufflesuite/ganache#97]
when trying to build gananche on linux as described in the README I get:

```
⋊> ~/g/3/ganache on master ◦ npm run build-linux                        13:45:33

> ganache@1.0.0 build-linux /home/ligi/git/3rd/ganache
> cd ./node_modules/rabin-bindings && node-gyp rebuild && cd ../../ && npm run make

sh: 1: cd: can't cd to ./node_modules/rabin-bindings

npm ERR! Linux 4.10.0-38-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build-linux"
npm ERR! node v4.7.2
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! ganache@1.0.0 build-linux: `cd ./node_modules/rabin-bindings && node-gyp rebuild && cd ../../ && npm run make`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the ganache@1.0.0 build-linux script 'cd ./node_modules/rabin-bindings && node-gyp rebuild && cd ../../ && npm run make'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ganache package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd ./node_modules/rabin-bindings && node-gyp rebuild && cd ../../ && npm run make
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ganache
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ganache
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ligi/git/3rd/ganache/npm-debug.log

```

**Comment by tcoulter** [comment]
Please make sure you run `npm install` first before running `npm run build-linux`

**Comment by ligi** [comment]
thanks - when doing this I end up with another error:

```
⋊> ~/g/3/ganache on master ◦ npm run build-linux                        18:25:07

> ganache@1.0.0 build-linux /home/ligi/git/3rd/ganache
> cd ./node_modules/rabin-bindings && node-gyp rebuild && cd ../../ && npm run make

make: Entering directory '/home/ligi/git/3rd/ganache/node_modules/rabin-bindings/build'
  CXX(target) Release/obj.target/rabin-bindings/bindings.o
  CXX(target) Release/obj.target/rabin-bindings/src/rabin.o
  CXX(target) Release/obj.target/rabin-bindings/src/rabin_wrap.o
  SOLINK_MODULE(target) Release/obj.target/rabin-bindings.node
  COPY Release/rabin-bindings.node
make: Leaving directory '/home/ligi/git/3rd/ganache/node_modules/rabin-bindings/build'

> ganache@1.0.0 make /home/ligi/git/3rd/ganache
> electron-forge make


An unhandled exception has occurred inside Forge:
Unexpected token =
SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ligi/git/3rd/ganache/node_modules/electron-forge/dist/electron-forge.js:18:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:990:3

npm ERR! Linux 4.10.0-38-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "make"
npm ERR! node v4.7.2
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! ganache@1.0.0 make: `electron-forge make`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ganache@1.0.0 make script 'electron-forge make'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ganache package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-forge make
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ganache
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ganache
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ligi/git/3rd/ganache/npm-debug.log

npm ERR! Linux 4.10.0-38-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build-linux"
npm ERR! node v4.7.2
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! ganache@1.0.0 build-linux: `cd ./node_modules/rabin-bindings && node-gyp rebuild && cd ../../ && npm run make`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ganache@1.0.0 build-linux script 'cd ./node_modules/rabin-bindings && node-gyp rebuild && cd ../../ && npm run make'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ganache package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd ./node_modules/rabin-bindings && node-gyp rebuild && cd ../../ && npm run make
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ganache
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ganache
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ligi/git/3rd/ganache/npm-debug.log
```

[npm-debug.log](https://github.com/trufflesuite/ganache/files/1485137/npm-debug.log)

**Comment by benjamincburns** [comment]
@ligi You're running node v4.7.2. You'll want to be running a newer version to build Ganache, as it's written mostly in ES6. I'd recommend installing [NVM](https://github.com/creationix/nvm), and using that to install/use the latest stable node release.

**Comment by benjamincburns** [comment]
We were missing the `rabin-bindings` package from our dev dependencies.  I've added that to the current `develop` branch. Otherwise I just pushed out a new linux build today and didn't encounter any other issues, so I'm going to close this.

@ligi thanks for reporting this. Please do reopen if you're still having issues!
