### ISSUE TITLE
System Error when running Ganache 1.2.1 on darwin

### ISSUE THREAD

**Issue by shydesky** [trufflesuite/ganache#972]
PLATFORM: darwin
GANACHE VERSION: 1.2.1

EXCEPTION:
```
TypeError: e.reject is not a function
    at u.<anonymous> (/node_modules/ganache-cli/build/webpack:/ganache/node_modules/ganache-core/lib/webSocketServer.js:49:1)
    at emitOne (events.js:115:13)
    at u.emit (events.js:210:7)
    at u.processFrame (/node_modules/ganache-cli/build/webpack:/ganache/node_modules/websocket/lib/WebSocketConnection.js:529:1)
    at /node_modules/ganache-cli/build/webpack:/ganache/node_modules/websocket/lib/WebSocketConnection.js:321:34
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+107353ms: eth_getBalance
T+107354ms: eth_getBalance
T+107357ms: eth_getBalance
T+107358ms: eth_getBalance
T+111330ms: eth_blockNumber
T+112201ms: eth_getBlockByNumber
T+112318ms: net_version
T+112320ms: eth_accounts
T+117343ms: eth_getBalance
T+117345ms: eth_getBalance
T+117350ms: eth_getBalance
T+117355ms: eth_getBalance
T+117356ms: eth_getBalance
T+117357ms: eth_getBalance
T+117358ms: net_version
T+117359ms: eth_accounts
T+117361ms: eth_getBalance
T+117363ms: eth_getBalance
T+117365ms: eth_getBalance
T+117372ms: eth_getBalance
T+122314ms: net_version
T+122316ms: eth_accounts
T+127202ms: eth_getBlockByNumber
T+127324ms: net_version
T+127325ms: eth_accounts
T+127325ms: eth_getBalance
T+127325ms: eth_getBalance
T+127325ms: eth_getBalance
T+127325ms: eth_getBalance
T+127327ms: eth_getBalance
T+127328ms: eth_getBalance
T+127330ms: eth_getBalance
T+127332ms: eth_getBalance
T+127336ms: eth_getBalance
T+127338ms: eth_getBalance
T+131338ms: eth_blockNumber
T+132323ms: net_version
T+132325ms: eth_accounts
T+137327ms: net_version
T+137329ms: eth_getBalance
T+137330ms: eth_getBalance
T+137332ms: eth_getBalance
T+137334ms: eth_getBalance
T+137335ms: eth_getBalance
T+137336ms: eth_getBalance
T+137337ms: eth_accounts
T+137339ms: eth_getBalance
T+137342ms: eth_getBalance
T+137345ms: eth_getBalance
T+137348ms: eth_getBalance
T+142196ms: eth_getBlockByNumber
T+142317ms: net_version
T+142318ms: eth_accounts
T+147345ms: eth_getBalance
T+147347ms: eth_getBalance
T+147351ms: eth_getBalance
T+147352ms: eth_getBalance
T+147354ms: eth_getBalance
T+147355ms: eth_getBalance
T+147357ms: eth_getBalance
T+147359ms: net_version
T+147360ms: eth_accounts
T+147361ms: eth_getBalance
T+147361ms: eth_getBalance
T+147363ms: eth_getBalance
T+151346ms: eth_blockNumber
T+152318ms: net_version
T+152319ms: eth_accounts
T+157204ms: eth_getBlockByNumber
T+157324ms: net_version
T+157326ms: eth_getBalance
T+157327ms: eth_getBalance
T+157328ms: eth_getBalance
T+157329ms: eth_getBalance
T+157330ms: eth_getBalance
T+157331ms: eth_getBalance
T+157333ms: eth_getBalance
T+157334ms: eth_getBalance
T+157335ms: eth_accounts
T+157338ms: eth_getBalance
T+157341ms: eth_getBalance
T+162320ms: net_version
T+162321ms: eth_accounts
T+167327ms: eth_getBalance
T+167329ms: eth_getBalance
T+167330ms: eth_getBalance
T+167331ms: eth_getBalance
T+167333ms: eth_getBalance
T+167334ms: eth_getBalance
T+167336ms: eth_getBalance
T+167337ms: net_version
T+167339ms: eth_accounts
T+167346ms: eth_getBalance
T+167347ms: eth_getBalance
T+167348ms: eth_getBalance
T+171356ms: eth_blockNumber
T+172197ms: eth_getBlockByNumber
T+172317ms: net_version
T+172318ms: eth_accounts
T+177348ms: net_version
T+177349ms: eth_accounts
T+177350ms: eth_getBalance
T+177351ms: eth_getBalance
T+177352ms: eth_getBalance
T+177353ms: eth_getBalance
T+177354ms: eth_getBalance
T+177356ms: eth_getBalance
T+177357ms: eth_getBalance
T+177359ms: eth_getBalance
T+177361ms: eth_getBalance
T+177362ms: eth_getBalance
T+182317ms: net_version
T+182319ms: eth_accounts
T+187203ms: eth_getBlockByNumber
T+187325ms: net_version
T+187327ms: eth_getBalance
T+187328ms: eth_getBalance
T+187330ms: eth_getBalance
T+187331ms: eth_getBalance
T+187332ms: eth_getBalance
T+187333ms: eth_getBalance
T+187335ms: eth_accounts
T+187336ms: eth_getBalance
T+187337ms: eth_getBalance
T+187338ms: eth_getBalance
T+187340ms: eth_getBalance
T+191367ms: eth_blockNumber
T+192320ms: net_version
T+192321ms: eth_accounts
T+197322ms: net_version
T+197327ms: eth_getBalance
T+197328ms: eth_accounts
T+197329ms: eth_getBalance
T+197331ms: eth_getBalance
T+197332ms: eth_getBalance
T+197334ms: eth_getBalance
T+197336ms: eth_getBalance
T+197337ms: eth_getBalance
T+197339ms: eth_getBalance
T+197340ms: eth_getBalance
T+197342ms: eth_getBalance
T+202201ms: eth_getBlockByNumber
T+202316ms: net_version
T+202318ms: eth_accounts
T+207346ms: net_version
T+207348ms: eth_accounts
T+207349ms: eth_getBalance
T+207350ms: eth_getBalance
T+207352ms: eth_getBalance
T+207353ms: eth_getBalance
T+207354ms: eth_getBalance
T+207354ms: eth_getBalance
T+207355ms: eth_getBalance
T+207356ms: eth_getBalance
T+207357ms: eth_getBalance
T+207360ms: eth_getBalance
T+211377ms: eth_blockNumber
T+212319ms: net_version
T+212320ms: eth_accounts
T+217202ms: eth_getBlockByNumber
T+217327ms: net_version
T+217329ms: eth_getBalance
T+217330ms: eth_getBalance
T+217331ms: eth_getBalance
T+217332ms: eth_getBalance
T+217334ms: eth_getBalance
T+217335ms: eth_getBalance
T+217338ms: eth_accounts
T+217339ms: eth_getBalance
T+217340ms: eth_getBalance
T+217340ms: eth_getBalance
T+217341ms: eth_getBalance
T+222323ms: net_version
T+222324ms: eth_accounts
T+225385ms: eth_unsubscribe
```

**Comment by davidmurdoch** [comment]
@shydesky, please update to the latest Ganache (v1.2.2 has tons of stability improvements) and if this is still a problem please feel free to reopen this issue.
