### ISSUE TITLE
how to use? Method personal_importRawKey not supported.

### ISSUE THREAD

**Issue by lyricalpolymath** [trufflesuite/ganache#99]
**I've made it run well but I'm confused as to how we are supposed to use it.**

for instance:
I can't seem to be able to import the private keys of the accounts 
(neither with geth nor via rpc)

copying the key from one account and doing:
`personal.importRawKey("c87509....LongKeyHere","passKeyHere")`
yields

```
Error: Error: Method personal_importRawKey not supported.
    at GethApiDouble.handleRequest (~/path/to/Ganache/node_modules/ethereumjs-testrpc/build/lib.node.js:79613:16)
    at next (~/path/to/Ganache/node_modules/ethereumjs-testrpc/build/lib.node.js:47831:18)
    at GethDefaults.handleRequest (~/path/to/Ganache/node_modules/ethereumjs-testrpc/build/lib.node.js:79522:12)
    at next (~/path/to/Ganache/node_modules/ethereumjs-testrpc/build/lib.node.js:47831:18)
    at FilterSubprovider.handleRequest (~/path/to/Ganache/node_modules/ethereumjs-testrpc/build/lib.node.js:54285:7)
    at next (~/path/to/Ganache/node_modules/ethereumjs-testrpc/build/lib.node.js:47831:18)
    at DelayedBlockFilter.handleRequest (~/path/to/Ganache/node_modules/ethereumjs-testrpc/build/lib.node.js:79350:3)
    at next (~/path/to/Ganache/node_modules/ethereumjs-testrpc/build/lib.node.js:47831:18)
    at ReactiveBlockTracker.handleRequest (~/path/to/Ganache/node_modules/ethereumjs-testrpc/build/lib.node.js:79477:12)
    at next (~/path/to/Ganache/node_modules/ethereumjs-testrpc/build/lib.node.js:47831:18)
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at <anonymous>:1:1    
```

and I can't seem to be able to even start a miner
```
miner.start()
ReferenceError: 'miner' is not defined
```

how do you actually use it?
thanks

**Comment by lyricalpolymath** [comment]
ok got it...it works like testrpc :) it's a UI for a testrpc

just for others who might have the same question this is one way in which you would use it , with geth Console

- when you start Ganache, in the interface you will see "RPC server http://127.0.0.1:7545"
that's your rpc endpoint where you can attach the geth console (or web3 provider)

- `geth attach http://127.0.0.1:7545`

- the accounts will be available without having to import them in `eth.accounts`
(no need to import the private keys like in my previous question, they are already loaded as your accounts)

- so to send a sample transaction form the first account to the second one you could
`eth.sendTransaction({from: eth.accounts[0], to:eth.accounts[1], value: web3.toWei(50, 'ether')})`

- watch in Ganache the balances change automatically
