### ISSUE TITLE
ganache-cli 6.7.0 - Could not connect to your Ethereum client with the following parameters 

### ISSUE THREAD

**Issue by abhayks1** [trufflesuite/ganache#990]
Hi Team,

Our travis tests are running on ganache-cli version `6.7.0`.
ganache-cli is behaving strangely. Issue we are facing is that ganache is getting killed abruptly.
After restarting the build multiple times, test passes. 
Below is the build url: https://travis-ci.org/mosaicdao/mosaic-1/builds/620642401
```
{ Error: 
Could not connect to your Ethereum client with the following parameters:
    - host       > localhost
    - port       > 8545
    - network_id > 1575468748758
Please check that your Ethereum client:
    - is running
    - is accepting RPC connections (i.e., "--rpc" option is used in geth)
    - is accessible over the network
    - is properly configured in your Truffle configuration file (truffle-config.js)
    at ProviderError.ExtendableError (/home/travis/build/mosaicdao/mosaic-1/node_modules/truffle/build/webpack:/packages/error/index.js:10:1)
    at new ProviderError (/home/travis/build/mosaicdao/mosaic-1/node_modules/truffle/build/webpack:/packages/provider/error.js:12:1)
    at /home/travis/build/mosaicdao/mosaic-1/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:75:1
    at /home/travis/build/mosaicdao/mosaic-1/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:107:1
    at XMLHttpRequest.request.onreadystatechange (/home/travis/build/mosaicdao/mosaic-1/node_modules/truffle/build/webpack:/~/web3-providers-http/src/index.js:102:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/travis/build/mosaicdao/mosaic-1/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
    at XMLHttpRequest._setReadyState (/home/travis/build/mosaicdao/mosaic-1/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:208:1)
    at XMLHttpRequest._onHttpRequestError (/home/travis/build/mosaicdao/mosaic-1/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:349:1)
    at ClientRequest.<anonymous> (/home/travis/build/mosaicdao/mosaic-1/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:252:47)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:73:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```

Below is the truffle config:

```
module.exports = {
  networks: {
    development: {
      host: 'localhost',
      network_id: '*',
      port: 8545,
      gas: 12000000,
      gasPrice: 0x01,
    },
  },
  compilers: {
    solc: {
      version: '0.5.8',
      settings: {
        optimizer: {
          enabled: true,
          runs: 200,
        },
      },
    },
  },
  mocha: {
    enableTimeouts: false
  },
};
```

Ganache is being started with below command:
```
./node_modules/.bin/ganache-cli" \
    --accounts=1000 \
    --defaultBalanceEther=10000 \
    --gasLimit 0xfffffffffff
```
Below is how we are creating our web3 object:
```
const web3 = new Web3('http://localhost:8545');
```
How can above issue be fixed?

**Comment by davidmurdoch** [comment]
This has likely been fixed in the latest alpha release of ganache. If you are experiencing this issue please try out the new alpha. You can find the release notes here: https://github.com/trufflesuite/ganache/releases/tag/ganache%407.0.0-alpha.1

If you try the new alpha please do come back and leave an update. Doing so will be very helpful!

**Comment by haltman-at** [comment]
We're going to close this for issue maintenance, but please let us know if there's still a problem here and we'll see what we can do.  Thank you all!
